- cpp/src/CMakeLists.txt
- cpp/src/jni/jni_common.h
- cpp/src/proto/substrait_utils.cc
- cpp/src/proto/substrait_utils.h
This pr updated the Substrait parsing process in native code to align with the updated Substrait.
https://github.com/oap-project/gazelle-jni/issues/36.
> [GJ-36] Updating Substrait parsing process

- cpp/src/jni/jni_wrapper.cc
This PR is a following PR of https://github.com/oap-project/gazelle-jni/pull/50 to add the init method in Native.
https://github.com/oap-project/gazelle-jni/issues/49.
> [GJ-49] Add init method in Native

- cpp/src/CMakeLists.txt
- cpp/src/proto/substrait_to_velox_expr.cc
- cpp/src/proto/substrait_to_velox_plan.cc
- cpp/src/proto/substrait_to_velox_plan.h
- cpp/src/proto/type_utils.h
This pr:
- Changed to use Velox's Arrow converter
- Added String type support
Closes https://github.com/oap-project/gazelle-jni/issues/53.
> [GJ-53] Add Velox-to-Arrow conversion

- docs/GazelleJniUsage.md
https://github.com/oap-project/gazelle-jni/issues/13
> [GJ-13] Update doc

- jvm/pom.xml
- jvm/src/main/scala/com/intel/oap/execution/BasicScanExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/BatchScanExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/FileSourceScanExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/com/intel/oap/execution/NativeWholestageRowRDD.scala
- jvm/src/main/scala/com/intel/oap/execution/WholeStageTransformerExec.scala
- jvm/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
- jvm/src/main/scala/com/intel/oap/extension/columnar/ColumnarGuardRule.scala
- jvm/src/test/scala/com/intel/oap/benchmarks/BenchmarkTest.scala
- jvm/src/test/scala/com/intel/oap/benchmarks/TableBenchmarkTest.scala
- pom.xml
Support to use DS V1 API to query from Hive table.
Closes https://github.com/oap-project/gazelle-jni/issues/58
> [GJ-58] Support Spark DS V1

- jvm/pom.xml
- jvm/src/main/scala/com/intel/oap/execution/BasicScanExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/BatchScanExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/FileSourceScanExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/com/intel/oap/execution/NativeWholestageRowRDD.scala
- jvm/src/main/scala/com/intel/oap/execution/WholeStageTransformerExec.scala
- jvm/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
- jvm/src/main/scala/com/intel/oap/extension/columnar/ColumnarGuardRule.scala
- jvm/src/test/scala/com/intel/oap/benchmarks/BenchmarkTest.scala
- jvm/src/test/scala/com/intel/oap/benchmarks/TableBenchmarkTest.scala
- pom.xml
> [GJ-58] Support Spark DS V1 (#59)

- cpp/src/compute/protobuf_utils.cc
- cpp/src/compute/protobuf_utils.h
- cpp/src/jni/jni_common.h
Closes https://github.com/oap-project/gazelle-jni/issues/63.
> [GJ-63] Print substrait plan in json string

- cpp/src/compute/protobuf_utils.cc
- cpp/src/compute/protobuf_utils.h
- cpp/src/jni/jni_common.h
- jvm/src/main/scala/com/intel/oap/expression/AggregateFunctionsBuilder.scala
- jvm/src/main/scala/com/intel/oap/expression/ArithmeticTransformer.scala
- jvm/src/main/scala/com/intel/oap/expression/BinaryOperatorTransformer.scala
- jvm/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
- jvm/src/main/scala/com/intel/oap/expression/NamedExpressionsTransformer.scala
- jvm/src/main/scala/com/intel/oap/expression/UnaryOperatorTransformer.scala
> Rebase to PR_76

- cpp/src/compute/substrait_to_velox_expr.cc
- cpp/src/compute/substrait_to_velox_plan.cc
- cpp/src/compute/substrait_utils.cc
- cpp/src/compute/substrait_utils.h
This pr added the neccessary change to aligh with the new Substrait names.
https://github.com/oap-project/gazelle-jni/issues/75.
> [GJ-75] Align with new names

- cpp/gazelle-cpp/compute/substrait_arrow.cc
- cpp/gazelle-cpp/compute/substrait_arrow.h
- cpp/src/CMakeLists.txt
- cpp/src/compute/kernels_ext.cc
- cpp/src/compute/kernels_ext.h
- cpp/src/compute/substrait_utils.cc
- cpp/src/compute/substrait_utils.h
- cpp/src/jni/exec_backend.h
- cpp/src/jni/exec_backend_test.cc
- cpp/src/jni/jni_wrapper.cc
- cpp/src/operators/shuffle/splitter.cc
- jvm/src/main/java/com/intel/oap/substrait/rel/InputRelNode.java
- jvm/src/main/java/com/intel/oap/substrait/rel/RelBuilder.java
- jvm/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
- jvm/src/main/resources/substrait/proto/substrait/algebra.proto
- jvm/src/main/scala/com/intel/oap/GazelleJniConfig.scala
- jvm/src/main/scala/com/intel/oap/execution/HashAggregateExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/com/intel/oap/execution/WholeStageTransformerExec.scala
- jvm/src/main/scala/com/intel/oap/substrait/SubstraitContext.scala
This pr enabled the second stage computing on master branch. A fake result will be returned.
The change to Substrait will soon be raised to Substrait in a PR.
By setting below config as false, final aggregation can be fallbacked.
`spark.oap.sql.columnar.hashagg.enablefinal`
Closes https://github.com/oap-project/gazelle-jni/issues/79.
> [GJ-79] Enable the second stage on master branch

- cpp/src/compute/substrait_utils.cc
- jvm/src/main/java/com/intel/oap/substrait/expression/AggregateFunctionNode.java
- jvm/src/main/java/com/intel/oap/substrait/expression/ExpressionBuilder.java
- jvm/src/main/java/com/intel/oap/substrait/type/I32TypeNode.java
- jvm/src/main/java/com/intel/oap/substrait/type/I64TypeNode.java
- jvm/src/main/scala/com/intel/oap/execution/HashAggregateExecTransformer.scala
- jvm/src/main/scala/com/intel/oap/expression/AggregateFunctionsBuilder.scala
- jvm/src/main/scala/com/intel/oap/expression/ArithmeticTransformer.scala
- jvm/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
This pr:
- Enabled the transformation needed in TPC-H Q1.
- Separate pre-projection from Agg.
Closes https://github.com/oap-project/gazelle-jni/issues/86.
> [GJ-86] Enable q1 transformation

- cpp/src/jni/jni_wrapper.cc
- docs/GlutenUsage.md
Add missing JNI init function to spark_columnar_jni backend
> Add missing JNI init function

- cpp/src/jni/jni_wrapper.cc
Closes https://github.com/oap-project/gluten/issues/118.
> [GJ-118] Remove redundant JNI funciton nativeInitNative from gazelle-jni

- jvm/src/main/java/io/glutenproject/vectorized/ColumnarFactory.java
- jvm/src/main/java/io/glutenproject/vectorized/ExpressionEvaluator.java
- jvm/src/main/scala/io/glutenproject/GazelleJniConfig.scala
- jvm/src/main/scala/io/glutenproject/execution/CoalesceBatchesExec.scala
- jvm/src/main/scala/io/glutenproject/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
- jvm/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
- jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
- jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
- jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
> [HOTFIX] Remove parameter 'loadch'

- cpp/gazelle-cpp/compute/substrait_arrow.cc
- cpp/gazelle-cpp/compute/substrait_arrow.h
Closes https://github.com/oap-project/gluten/issues/112.
> [GJ-112] Enable filter pushdown for TPCH Q1&Q6 on arrow backend

- jvm/src/main/java/io/glutenproject/vectorized/JniInstance.java
Fixed the library loading issue when the release directory is not accessible.
Fixed https://github.com/oap-project/gluten/issues/145.
Verified in a cluster test.
> [Gluten-145] Fix library loading

- jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
Fix NPE when executing with ClickHouse backend
Closes #153 
> [Gluten-153] Fix NPE when executing with ClickHouse backend

- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
> [OPPRO-90] Fix performance regression

- docs/GlutenInstallation.md
- docs/GlutenUsage.md
- docs/SparkHadoopInstallation.md
- tools/build_velox.sh
> [Gluten-137]Some fixes for documentation and build_velox.sh script

- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- jvm/src/main/java/io/glutenproject/substrait/expression/IfThenNode.java
- jvm/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
- jvm/src/main/scala/io/glutenproject/expression/ArithmeticTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/BinaryOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/CaseWhenOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/CoalesceOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/ConcatOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
- jvm/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/IfOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/InExpressionTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/InSetOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/RoundOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/ScalarSubqueryTransformer.scala
- jvm/src/main/scala/io/glutenproject/expression/UnaryOperatorTransformer.scala
Support case_when, InSet, Extract expression.
Close #171 .
> [Gluten-171] Support case_when, InSet, Extract expression

- .github/workflows/dev_cron.yml
- .github/workflows/unittests.yml
Change to use self runners on AWS EC2
Has been tested in another personal repository
> [DNM]Change to use self-hosted runners

- jvm/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
- jvm/src/main/java/io/glutenproject/substrait/expression/NullLiteralNode.java
- jvm/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- jvm/src/main/scala/io/glutenproject/expression/ScalarSubqueryTransformer.scala
Supported sending the result of scalar subquery through Substrait plan.
locally tested
> [OPPRO-104] Support scalar subquery expression

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/BatchIterator.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeBlock.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHStreamReader.java
- backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CHColumnarBatchSerializer.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- jvm/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
- jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
- jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
Add `xxx#exprId` for each names in substrait plan except for the base_schema of read rel.
Close #190 .
> [Gluten-190] Fix some CH shuffle errors

- .github/workflows/unittests.yml
set settings.xml overwrite to false
Tested on local server
> [DNM]set settings.xml overwrite to false

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
Use original Filter for arrow backend.
A quick fix for https://github.com/oap-project/gluten/issues/194.
> [OPPRO-104] Use original Filter for arrow backend

- cpp/src/jni/jni_wrapper.cc
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
Work together with https://github.com/oap-project/velox/pull/16 to reduce memory leak
> [OPPRO-148] JavaRecordBatchIterator not being destructed

- README.md
Remove Conda discription in README since we haven't support conda for Gluten installation right now.
Only readme update.
> Remove Conda description in README

- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- cpp/velox/compute/VeloxToRowConverter.cc
- cpp/velox/compute/VeloxToRowConverter.h
- cpp/velox/jni/jni_wrapper.cc
To fix the memory pool being early released issue.
Depends on https://github.com/oap-project/velox/pull/20.
Locally verified.
> [OPPRO-105] Use a global memory pool

- cpp/velox/benchmarks/BenchmarkUtils.cc
- cpp/velox/benchmarks/BenchmarkUtils.h
- cpp/velox/benchmarks/HashJoinBenchmark.cc
- cpp/velox/benchmarks/QueryBenchmark.cc
Fixed the benchmark compilation.
Locally verified.
> [OPPRO-155] Fix benchmark

- jvm/src/main/java/io/glutenproject/substrait/type/DecimalTypeNode.java
- jvm/src/main/java/io/glutenproject/substrait/type/TimestampTypeNode.java
- jvm/src/main/java/io/glutenproject/substrait/type/TypeBuilder.java
- jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
Add Decimal/ Timestamp support to Spark->Substrait conversion
> [OPPRO-127] Add Decimal/ Timestamp support to Spark->Substrait conversion

- tools/build_velox.sh
This patch adds the missing the parquet components in velox building
pass jenkins
> [OPPRO-46] fix parquet build

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/java/io/glutenproject/execution/VeloxNativeColumnarToRowExec.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
- cpp/src/jni/exec_backend.h
- cpp/velox/benchmarks/BenchmarkUtils.cc
- cpp/velox/benchmarks/BenchmarkUtils.h
- cpp/velox/benchmarks/QueryBenchmark.cc
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/BroadcastBuildSideRDD.scala
- jvm/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/io/glutenproject/execution/NativeWholestageRowRDD.scala
- jvm/src/main/scala/io/glutenproject/execution/ShuffledHashJoinExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
- jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
- jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
- jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala
This PR merged the operators which should be in a single transformer together. Reverted some changes to break transformer and supported a new pattern of scan combining with join.
Suuported multiple scan nodes in a whole stage transformer.
Removed fake arrow output.
Depends on https://github.com/oap-project/velox/pull/24.
Verified on TPC-H
> [OPPRO-163] Merge the operators

- backends-velox/src/main/java/io/glutenproject/execution/VeloxNativeColumnarToRowExec.scala
- backends-velox/src/main/java/io/glutenproject/vectorized/ShuffleDecompressionJniWrapper.java
- backends-velox/src/main/java/io/glutenproject/vectorized/ShuffleSplitterJniWrapper.java
- backends-velox/src/main/scala/io/glutenproject/expression/ArrowConverterUtils.scala
- backends-velox/src/main/scala/io/glutenproject/utils/ArrowAbiUtil.scala
- backends-velox/src/main/scala/io/glutenproject/vectorized/ArrowColumnarBatchSerializer.scala
- backends-velox/src/main/scala/org/apache/spark/shuffle/VeloxColumnarShuffleWriter.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkVectorUtils.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/utils/VeloxExecUtil.scala
- cpp/src/jni/jni_common.h
- cpp/src/jni/jni_wrapper.cc
- jvm/src/main/java/io/glutenproject/vectorized/NativeColumnarToRowJniWrapper.java
- jvm/src/main/java/io/glutenproject/vectorized/NativePartitioning.java
> [OPPRO-152] Use Arrow C ABI to interchange data between C++ and Java for Shuffle and ColumnToRow

- jvm/src/main/scala/io/glutenproject/GlutenPlugin.scala
This[ init logic](https://github.com/oap-project/gluten/blob/5206687bfd9434e01a2fdd81740b99e77795a51c/cpp/velox/compute/DwrfDatasource.cc#L29) no longer need to do again with this patch.
> [OPPRO-171] Initialize Native code in GlutenDriverPlugin

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
- jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- jvm/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/io/glutenproject/execution/ShuffledHashJoinExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
- jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala
Added output rows and batches to each transformer.
> [OPPRO-167] Add output metrics

- .github/workflows/unittests.yml
- tools/trigger_perf_test.sh
> CI: trigger performance test on each pull request

- backends-velox/src/main/java/io/glutenproject/spark/sql/execution/datasources/velox/DwrfDatasourceJniWrapper.java
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxDatasourceUtil.scala
- backends-velox/src/main/scala/org/apache/spark/sql/DwrfWriteExtension.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/DwrfFileFormat.scala
- cpp/velox/compute/DwrfDatasource.cc
- cpp/velox/compute/DwrfDatasource.h
- cpp/velox/jni/jni_wrapper.cc
- jvm/src/main/scala/io/glutenproject/GlutenPlugin.scala
> [OPPRO-177] Support dwrf write

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/spark/sql/DwrfWriteExtension.scala
- jvm/src/main/scala/io/glutenproject/GlutenPlugin.scala
- jvm/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
- jvm/src/main/scala/io/glutenproject/extension/OthersExtensionOverrides.scala
- jvm/src/test/scala/io/glutenproject/backendsapi/SparkPlanExecApiImplSuite.scala
> [OPPRO-180] Move the DWRF Write Extension initialize to OtherExtensionOverrides

- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- jvm/src/main/scala/io/glutenproject/GlutenConfig.scala
> [Gluten-234] Remove CPU type limitation

- .github/workflows/unittests.yml
- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/BlockSplitIterator.java
- backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CloseableCHColumnBatchIterator.scala
- backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CloseablePartitionedBlockIterator.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- backends-velox/pom.xml
- jvm/pom.xml
> [Gluten-244] Remove 'testFailureIgnore' = true in pom.xml and fix some memory leak for ClickHouse Backend

- .github/workflows/unittests.yml
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/BatchIterator.java
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/java/io/glutenproject/vectorized/ArrowInIterator.java
- backends-velox/src/main/java/io/glutenproject/vectorized/ArrowOutIterator.java
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
- backends-velox/src/main/scala/io/glutenproject/utils/ArrowAbiUtil.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/v2/arrow/SparkMemoryUtils.scala
- cpp/gazelle-cpp/compute/substrait_arrow.cc
- cpp/gazelle-cpp/compute/substrait_arrow.h
- cpp/src/compute/kernels_ext.cc
- cpp/src/compute/kernels_ext.h
- cpp/src/compute/substrait_utils.cc
- cpp/src/compute/substrait_utils.h
- cpp/src/jni/exec_backend.h
- cpp/src/jni/jni_wrapper.cc
- cpp/velox/CMakeLists.txt
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- cpp/velox/compute/bridge.cc
- cpp/velox/compute/bridge.h
- jvm/src/main/java/io/glutenproject/vectorized/ExpressionEvaluator.java
- jvm/src/main/java/io/glutenproject/vectorized/GeneralOutIterator.java
- jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala
Use ArrowArray as data flow instead of RecordBatch
manual TPCH test
> 【OPPRO-175】Remove C ABI RecordBatch, change to ArrowArray

- cpp/velox/CMakeLists.txt
- cpp/velox/compute/DwrfDatasource.cc
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxToRowConverter.cc
- tools/build_velox.sh
> [OPPRO-124] upgrade velox

- backends-velox/src/main/scala/io/glutenproject/execution/VeloxNativeColumnarToRowExec.scala
> [OPPRO-204] Close info with task listener

- cpp/CMakeLists.txt
> fix compile_commands.json not created

- backends-velox/pom.xml
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxWholeStageTransformerSuite.scala
Fixed whole stage transformer suite.
Fixed https://github.com/oap-project/gluten/issues/276.
Verified on CI.
> [Gluten-276] Fix whole stage transformer suite

- README.md
Correct the typoerror for speedup description.
n/a
> [OPPRO-287] Correct Speedup description in README.

- backends-velox/pom.xml
- backends-velox/src/main/java/io/glutenproject/exception/JniExceptionDescriber.java
- cpp/CMake/BuildArrow.cmake
- cpp/CMake/ConfigArrow.cmake
- cpp/src/CMakeLists.txt
- cpp/src/jni/jni_common.h
- cpp/src/jni/jni_wrapper.cc
- cpp/velox/jni/jni_wrapper.cc
- jvm/src/main/java/io/glutenproject/vectorized/JniLibLoader.java
- tools/build_arrow.sh
- tools/build_velox.sh
With Arrow 9, it will raise corrected size, prev.size in fastbin
Because libarrow_dataset_jni.so static link libarrow.so, repeated link will cause this issue
> Rebase Arrow to upstream Arrow - Remove libarrow_dataset module

- README.md
- docs/Velox.md
update the issue status in readme.
> [DNM] Update README.md

- cpp/src/jni/jni_wrapper.cc
Fixed the missing metrics of rawInputBytes.
Locally verified.
> [OPPRO-167] Fix missing metrics

- cpp/src/jni/jni_wrapper.cc
- cpp/src/utils/metrics.h
- cpp/velox/compute/VeloxPlanConverter.cc
- jvm/src/main/java/io/glutenproject/vectorized/Metrics.java
- jvm/src/main/java/io/glutenproject/vectorized/OperatorMetrics.java
- jvm/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
Removed cpuNanos and blockedWallNanos and changed the description for wallNanos.
under test
> [OPPRO-167] Remove two metrics and change decription

- backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CloseableCHColumnBatchIterator.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- backends-velox/src/main/scala/io/glutenproject/vectorized/CloseableColumnBatchIterator.scala
Correct the scan time of the metrics
Close #301 .
> [Gluten-301] Correct metrics time

- tools/build_arrow.sh
to fix https://github.com/oap-project/gluten/pull/293
> [OPPRO-189] fix miss arrow-c-data module

- backends-velox/workload/tpch/README.md
- backends-velox/workload/tpch/gen_data/dwrf_dataset/tpch_convert_parquet_dwrf.scala
- backends-velox/workload/tpch/gen_data/parquet_dataset/tpch_datagen_parquet.scala
- backends-velox/workload/tpch/run_tpch/tpch_dwrf.scala
- docs/ArrowBackend.md
- docs/ArrowInstallation.md
- docs/Velox.md
Add a scala code as an example to run TPC-H testing.
N/A for README and example code change.
> [OPPRO-203]Add a scala example for TPC-H testing

- jvm/src/main/java/io/glutenproject/vectorized/JniResourceHelper.java
Fix NPE in JniResourceHelper.extractHeaders0.
Close #307 .
> [Gluten-307] Fix NPE in JniResourceHelper.extractHeaders0

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- jvm/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
> [Gluten-309] Fix fallback issue when executing 'select count(*)' or 'select count(1)'

- cpp/velox/compute/VeloxToRowConverter.cc
Supported null handling in Velox to Row conversion.
Tested with https://github.com/oap-project/velox/pull/36 and https://github.com/oap-project/velox/pull/35.
> [OPPRO-41] Handle null in velox to row

- .github/workflows/unittests.yml
This patch adds https proxy for servers in intel lab
> adding https proxy to mvn cmd

- .github/workflows/unittests.yml
This patch adds selected TPCDS queries for arrow backend.
pass GHA
> add-back arrow backend tests

- .github/workflows/unittests.yml
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2TPCDSBenchmarkTest.scala
> [HOTFIX] Remove caching ccache files

- tools/build_velox.sh
Change back to use main branch of oap-project Velox.
under test
> [Following OPPRO-233] Change back velox branch

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseSyntheticDataSuite.scala
Using libpath parameter for UT
> [HOTFIX] Using libpath parameter for UT

- backends-velox/pom.xml
- tools/build_arrow.sh
> [OPPRO-236] Add the dataset module when compile arrow java

- .github/workflows/unittests.yml
> add gluten Clickhouse backend CD

- backends-velox/workload/tpch/run_tpch/tpch_parquet.scala
- docs/Velox.md
remove dwrf format from readme.
> [OPPRO-368] Add parquet support in readme. Remove dwrf

- backends-clickhouse/src/main/java/io/glutenproject/execution/SparkRowIterator.java
improve the performance of converting row to column by reducing jvm calls
> [CH-136]improve the performance of converting row batch to column batch

- cpp/velox/CMakeLists.txt
- cpp/velox/compute/DwrfDatasource.cc
- cpp/velox/compute/DwrfDatasource.h
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- tools/build_velox.sh
support to read dwrf file from hdfs as described in #388 
manual tests
1. read the source file from hdfs ,like
```
val lineitem = spark.read.format("dwrf").load("hdfs://testcluster/user/hive/warehouse/lineitem_dw")
```
2 .and then run a tpch scripts 
```
select
l_returnflag,
l_linestatus,
sum(l_quantity) as sum_qty,
sum(l_extendedprice) as sum_base_price,
sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
avg(l_quantity) as avg_qty,
avg(l_extendedprice) as avg_price,
avg(l_discount) as avg_disc,
count(*) as count_order
from
lineitem
where
l_shipdate <= '1998-9-01'
group by
l_returnflag,
l_linestatus
order by
l_returnflag,
l_linestatus
```
> [GLUTEN-158] Support read dwrf file from hdfs

- backends-velox/workload/tpcds/README.md
- backends-velox/workload/tpch/README.md
- docs/Velox.md
Added ninja installation command and java requirement.
pass CI
> [OPPRO-270] improve Velox backend doc

- gluten-ut/pom.xml
- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
Fixed runtime dependencies issue and enabled gluten interval expression suite.
under test
> [OPPRO-273] Enable gluten interval expression suite

- backends-velox/src/main/java/io/glutenproject/vectorized/CompressType.java
- backends-velox/src/main/scala/org/apache/spark/shuffle/VeloxColumnarShuffleWriter.scala
- cpp/src/operators/shuffle/splitter.cc
> [OPPRO-283] Enable gzip/zstd codec

- cpp/velox/compute/VeloxPlanConverter.cc
To align with Spark's behavior, set casting to int by truncate in Velox.
> [OPPRO-228] Cast to int by truncate

- pom.xml
#466 
mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=ON
> [Gluten-466] Fix maven build issue

- pom.xml
Reverts oap-project/gluten#477
> Revert "[Gluten-466] Fix maven build issue"

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2TPCDSBenchmarkTest.scala
- backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/GenTPCHTableScripts.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
- jvm/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- jvm/src/main/scala/io/glutenproject/execution/NativeWholeStageColumnarRDD.scala
- jvm/src/main/scala/io/glutenproject/softaffinity/SoftAffinityManager.scala
- jvm/src/main/scala/io/glutenproject/softaffinity/scheduler/SoftAffinityListener.scala
- jvm/src/main/scala/io/glutenproject/softaffinity/strategy/SoftAffinityAllocationTrait.scala
- jvm/src/main/scala/io/glutenproject/softaffinity/strategy/SoftAffinityStrategy.scala
- jvm/src/main/scala/org/apache/spark/softaffinity/SoftAffinityUtil.scala
- jvm/src/test/scala/org/apache/spark/softaffinity/SoftAffinitySuite.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
Support soft affinity scheduling for Gluten.
> [CH-182] Support soft affinity scheduling for Gluten

- README.md
- docs/Velox.md
> [DNM] Update Doc2

- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
Fix error after merging #492 .
> [HOTFIX] Fix error after merging #492

- gluten-core/pom.xml
> [OPPRO-295] Remove h2 dependency

- docs/ClickHouse.md
update readme for clickhouse backend. Add some usage instructions,
> [CH]Update Readme for clickhouse backend

- .github/workflows/unittests.yml
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHFilterExecTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
support prewhere on mergetree scan
unit tests
test by CH[[185]]
> [CH-179] support prewhere on mergetree

- backends-velox/src/main/scala/org/apache/spark/sql/VeloxColumnarRules.scala
- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- ep/build-velox/src/build_velox.sh
- gluten-core/src/main/java/io/glutenproject/substrait/rel/ExpandRelNode.java
- gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
- gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-core/src/main/scala/io/glutenproject/execution/CustomExpandExec.scala
- gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
Add expand operator support in gluten with velox backend.
Added UT and TPC-DS verification
> [OPPRO-301] Add expand operator

- ep/build-velox/src/build_velox.sh
> [OPPRO-301] revert test velox branch

- .github/workflows/unittests.yml
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/execution/RowToCHNativeColumnarExec.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/io/glutenproject/execution/VeloxRowToArrowColumnarExec.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GlutenRowToColumnarExec.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
- gluten-core/src/main/scala/org/apache/spark/rdd/EmptyRDD.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
- gluten-core/src/test/scala/io/glutenproject/backendsapi/SparkPlanExecApiImplSuite.scala
- gluten-ut/pom.xml
- gluten-ut/src/test/scala/io/glutenproject/utils/NotSupport.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseNotSupport.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsBaseTrait.scala
> [CH-190] enable tests in GlutenDataFrameAggregateSuite

- .github/workflows/unittests.yml
> fix CH ci error

- cpp/velox/compute/VeloxToRowConverter.cc
- gluten-core/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
- gluten-core/src/main/scala/io/glutenproject/expression/InSetOperatorTransformer.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
Fix some null point errors to pass GlutenPredicateSuite.
unit tests
> [OPPRO-310] Fix InSetOperatorTransformer toTransformer

- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- ep/build-velox/src/build_velox.sh
This PR supports limit on Velox backend.
verified on Jenkins.
> [OPPRO-307] Support limit on Velox backend

- .github/workflows/unittests.yml
> [CI] speed up velox unit test with more action runner

- backends-velox/src/main/scala/org/apache/spark/sql/VeloxColumnarRules.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarSubqueryBroadcastExec.scala
- shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
This PR made some clean up for isSupportAdaptive and ColumnarBroadcastExchangeAdaptor.
> [OPPRO-317] Some clean up for isSupportAdaptive and ColumnarBroadcastExchangeAdaptor

- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/jni/jni_wrapper.cc
- cpp/velox/memory/velox_memory_pool.cc
> [OPPRO-321]Upgrade velox ww47

- backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashAggregateExecTransformer.scala
- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- ep/build-velox/src/build_velox.sh
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
This PR supports StddevSamp on Velox backend.
> [OPPRO-316] Support StddevSamp on Velox backend

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
- cpp/velox/compute/ArrowTypeUtils.cc
> [OPPRO-324]Add date type validation

- gluten-core/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
It seems the headers are not necessary for gluten workers
pass jenkins
> Clean up on extracting jar

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
- ep/build-velox/src/build_velox.sh
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
> [OPPRO-326] Add byte array bool validation

- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHMemoryAllocatorManager.java
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/java/io/glutenproject/memory/alloc/VeloxMemoryAllocatorManager.java
- backends-velox/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
- gluten-core/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocatorManager.java
- gluten-core/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocators.java
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- gluten-core/src/main/scala/org/apache/spark/util/memory/TaskMemoryResourceManager.scala
> [CH-120][Follow-Up] Move interface getManaged() to NativeMemoryAllocatorManager

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
> [OPPRO-329] Enable Spark UT "GlutenCollectionExpressionsSuite".

- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
1. The `ConstantFolding` rule should be excluded to avoid static evaluation in UT. This code logic was unintentionally removed before. We are proposing to add it back.
2. We found for some UT the input can be `InternalRow.empty`. We need exclude this case to avoid unexpectedly calling `convertInternalRowToDataFrame`, not only for `EmptyRow`.
> [OPPRO-332] Add back the code for excluding ConstantFolding rule

- gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
This PR added metrics to limit and expand transformers.
under test
> [OPPRO-167] Add metrics to limit and expand transformers

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/NativeWholeStageColumnarRDD.scala
- gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
This PR fixed the duplicated updating for output metrics of project transformer.
under test
> [OPPRO-167] Fix the output metrics of project transformer

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
> [OPPRO-331] Add timestamp and decimal validation

- cpp/velox/compute/ArrowTypeUtils.cc
- cpp/velox/tests/shuffle_split_test.cc
Fix code style problem, one line in [ArrowTypeUtils.cc](https://github.com/oap-project/gluten/pull/627/files#diff-f2c198a8f0900c2ea373494a41ac37bfcb4f629b82716ba4072a66d3ebc09dbb) not follow the code style.
> Quick Fix codestyle

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
- gluten-core/src/main/scala/io/glutenproject/expression/IfOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryOperatorTransformer.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenConditionalExpressionSuite.scala
> [CH-202] Support condition expression, include if/else and case/when

- backends-velox/src/main/java/io/glutenproject/vectorized/ArrowWritableColumnVector.java
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxTransformerApi.scala
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxExpressionUtil.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
- cpp/velox/compute/ArrowTypeUtils.cc
- cpp/velox/compute/ArrowTypeUtils.h
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
> [OPPRO-338] Add struct type validation

- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/Constants.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/DataGen.scala
- tools/gluten-it/src/main/scala/org/apache/spark/sql/GlutenTypeUtils.scala
Migrated from https://github.com/zhztheplayer/gluten-it/pull/9
`typeMapping.containsKey(m.from)` was not suitable for DecimalType.
> [OPPRO-343] DecimalType doesn't get correctly processed in gluten-it

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenConditionalExpressionSuite.scala
> [OPPRO-341] Enable GlutenConditionalExpressionSuite

- backends-velox/workload/tpcds/README.md
- backends-velox/workload/tpcds/gen_data/parquet_dataset/tpcds_datagen_parquet.scala
- backends-velox/workload/tpch/README.md
this patch improved the example tpcds test to use partition dataset as it is more common in tpcds performance test
> [skip ci]refine example tpcds workloads

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxTransformerApi.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
This PR fixed the incorrect connection of project to its grandchild plan.
> [OPPRO-348] Fix the fallback of shuffle

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
> [CH-225] Fix decimal bug cased by big-endian encoding in spark row. #228

- .github/workflows/unittests.yml
- cpp/compile.sh
- docs/GlutenUsage.md
- docs/Velox.md
- tools/one_step_veloxbackend.sh
> [OPPRO-319] Add one_step_veloxbackend.sh document

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
1.  enable AnsiCastSuiteBase case except “INF”
1. sparkUT.
> [OPPRO-352] Enable AnsiCastSuiteBase/TryCastSuite

- gluten-core/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/CaseWhenOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ComplexTypeMergingExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/HashExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/InExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/NamedExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/QuaternaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/String2TrimExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
- gluten-data/src/main/scala/io/glutenproject/expression/GlutenAliasTransformer.scala
Remove some uselessly type check.
> [GLUTEN-587][FOLLOWUP] Refactor Gluten ExpressionConverter - Part One - Simplify ExpressionConverter, remove repetitive code

- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
add check_overflow transform support
test by CH[[231]]
> [Gluten-692] Support spark check_overflow function. #231

- gluten-core/pom.xml
this fixes the security issue reported by github depbot
pass jenkins
> remove unused dependencies: pgsql, maridb, sqlserver 

- .github/workflows/unittests.yml
- cpp/velox/compute/DwrfDatasource.cc
- cpp/velox/compute/RegistrationAllFunctions.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/memory/VeloxMemoryPool.cc
- cpp/velox/memory/VeloxMemoryPool.h
- docs/GlutenUsage.md
- docs/Velox.md
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
- tools/one_step_veloxbackend.sh
1. some interface changed.  eg createReader/registerAllWindowFunctions.
2. memory pool was refactor by velox. So we follow velox class  [MemoryPoolImpl](https://github.com/facebookincubator/velox/blob/main/velox/common/memory/Memory.cpp#L134) to implement gluten  WrappedVeloxMemoryPool.
3. remove Build spark3.2 and spark3.3 at the same time in CircleCI.  
4. rebase to velox 557f6d8610.
TPCH、TPCDS jenkens.
> [OPPRO-357] ww50 Upgrade Velox

- gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
This PR added metrics to window operator.
Verified locally.
> [OPPRO-167] Add metrics to window operator

- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
Remove the unnecessary cast
existing tests
> Remove some unnecessary code for instance cast

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
Enable Orc format file parsing in clickhouse backend
unit tests
test by CH[[214]]
> [CH-208]Support parsing ORC format files

- docs/Velox.md
- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameNaFunctionsSuite.scala
add GlutenDataFrameNaFunctionsSuite.
SparkUT
> Pass GlutenDataFrameNaFunctionsSuite

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameWindowFramesSuite.scala
Pass GlutenDataFrameWindowFramesSuite
Spark UT
> Pass GlutenDataFrameWindowFramesSuite

- README.md
- backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHAggAndShuffleBenchmark.scala
Fix bug in CHAggAndShuffleBenchmark when executing non-where
> [HOTFIX] Fix bug in CHAggAndShuffleBenchmark when executing non-where

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxExpressionUtil.scala
- gluten-core/src/main/java/io/glutenproject/substrait/expression/IntLiteralNode.java
- gluten-core/src/main/java/io/glutenproject/substrait/expression/StringLiteralNode.java
- gluten-core/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-core/src/main/scala/io/glutenproject/expression/QuaternaryExpressionTransformer.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> [CH-219] Support rlike/regexp_replace/regexp_extract/coalesce/DATE_ADD/DATE_SUB/DATEDIFF/modulo/concat_ws/collect_list/FROM_UNIXTIME

- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
> Fix type validate in HashAgg

- .github/workflows/unittests.yml
> Exit docker when task finish

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> Enable GlutenBroadcastExchangeSuite

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
* GlutenReuseExchangeAndSubquerySuite
* GlutenSQLWindowFunctionSuite
* GlutenSameResultSuite
Spark UT
> Pass some UTs

- .github/workflows/unittests.yml
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
Imported SQL query test suite. We need to add the name of a query file to the supported list after enabling it.
Tested on CI.
> Import SQL query test suite

- backends-velox/workload/tpch/run_tpch/tpch_parquet.sh
- docs/developers/HowTo.md
There are some common questions about developing, debugging, and testing been asked again and again. 
In order to help the developers to contribute to Gluten as soon as possible, I collected these frequently asked questions and organized them in the form of Q&A. 
It's convenient for the developers to check and learn.
> [Document] add HowTo.md to help developers to debug and test on Gluten 

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/java/io/glutenproject/substrait/expression/WindowFunctionNode.java
Clickhouse supports window function now.
unit test
test by CH[[235]]
> [CH-218]Clickhouse supports window function

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> Enable GlutenExistenceJoinSuite

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> Enable GlutenOuterJoinSuite

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/execution/joins/GlutenInnerJoinSuite.scala
> Enable GlutenInnerJoinSuite

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/execution/GlutenExchangeSuite.scala
> Enable GlutenExchangeSuite

- backends-clickhouse/src/main/scala/io/glutenproject/execution/BlockGlutenColumnarToRowExec.scala
- gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
- gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
Partial enable GlutenSubquerySuite for ClickHouse Backend.
Close #773.
> [Gluten-773] Partial enable GlutenSubquerySuite for ClickHouse Backend

- README.md
- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- gluten-core/pom.xml
- gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala
This reverts commit cc6d264ccb9999f19584d1021724fed0f6df4c3b.
> Revert "[Gluten-547] Shade protobuf to avoid jar conflicts (#767)"

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameSuite.scala
> [OPPRO-365] Enable GlutenDataFrameSuite.

- .github/workflows/unittests.yml
- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> Enable GlutenBroadcastJoinSuite

- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
If the metrics updater is none, there is no need to call the function `updateTransformerMetricsInternal`. Otherwise, the operator and metric index will become out of range or unmatched. 
> Fix the NPE when updating metrics

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
> [Gluten-800] Add order columns for match checkAnswer

- cpp/velox/compute/DwrfDatasource.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/memory/VeloxMemoryPool.cc
> Upgrade velox to 1/3

- gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameSuite.scala
Rewrite the describe test for aggregation test. Previously the describe function generates unmatched execution plan.
Testing on CI.
> Rewrite the describe test

- gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GlutenRowToColumnarExec.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ArrayExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/MapExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/QuaternaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ScalarSubqueryTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/WindowFunctionsBuilder.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarQueryStagePrepOverrides.scala
- gluten-core/src/main/scala/io/glutenproject/extension/OthersExtensionOverrides.scala
- gluten-core/src/main/scala/io/glutenproject/extension/StrategyOverrides.scala
- gluten-core/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
- pom.xml
remove unused imports
compile successfully
> [MINOR] Remove unused imports

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- ep/build-velox/src/get_velox.sh
- gluten-core/src/main/java/io/glutenproject/substrait/rel/AggregateRelNode.java
- gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
> Pass the filter info in aggregate operator from jvm to native

- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
Support more fields of extract function, which close https://github.com/Kyligence/ClickHouse/issues/227
test by CH[[252]]
> [CH-227] Support more fields of extract function. 

- cpp/velox/jni/JniWrapper.cc
- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
> [OPPRO-265]  Partially enable GlutenSQLQueryTestSuite

- dev/intellij-codestyle.xml
A follow-up about related discussions in #514
> Minor: Include scalafmt into Intellij formatter config

- docs/Velox.md
Update docs since #788 changes.
> Update Gluten + HDFS docs.

- gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
Enable a unit test for count(1)/count(*).
unit tests
test by CH[[260]]
> [CH-259]Enable a count ut

- docs/ClickHouse.md
> Update clickhouse readme

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/memory/VeloxMemoryPool.cc
> Upgrade velox to 2023/1/11

- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
Fixed by [VELOX#PR114](https://github.com/oap-project/velox/pull/114)
> Partial enable PostgreSQL in GlutenSQLQueryTestSuite

- cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
- cpp/core/operators/shuffle/splitter.cc
Follow up https://github.com/oap-project/gluten/pull/699.
> Fix cpp code format issue

- gluten-data/src/main/scala/org/apache/spark/shuffle/GlutenColumnarShuffleWriter.scala
Optimize the code of GlutenColumnarShuffleWriter
> Optimize the code of GlutenColumnarShuffleWriter

- backends-clickhouse/pom.xml
- backends-gazelle/pom.xml
- backends-velox/pom.xml
- gluten-core/pom.xml
- gluten-data/pom.xml
- gluten-ut/common/pom.xml
- gluten-ut/spark32/pom.xml
- gluten-ut/spark33/pom.xml
- pom.xml
- shims/common/pom.xml
- shims/spark32/pom.xml
- shims/spark33/pom.xml
- substrait/substrait-spark/pom.xml
> [refactor pom.xml] Simplify pom.xml

- cpp/velox/compute/WholeStageResultIterator.h
This patch removed the duplicated files in hdfs build
pass jenkins
> fix hdfs build

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/spark/sql/VeloxColumnarRules.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxStringFunctionsSuite.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCDSSuite.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
- gluten-core/src/main/scala/io/glutenproject/extension/StrategyOverrides.scala
- gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenTransformerApi.scala
- gluten-data/src/main/scala/io/glutenproject/execution/GlutenRowToArrowColumnarExec.scala
- gluten-data/src/main/scala/io/glutenproject/vectorized/GlutenColumnarBatchSerializer.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarInMemoryRelation.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenBuildSideRelation.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/python/ColumnarArrowPythonRunner.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/GlutenExecUtil.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/velox/DwrfScanBuilder.scala
Remove some unused imports for velox backend
> Remove some unused imports for velox backend

- .github/workflows/unittests.yml
- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
- substrait/substrait-spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala
- substrait/substrait-spark/src/test/scala/io/substrait/spark/TPCHPlan.scala
> Separate CI and set unit test log level to WARN

- cpp/velox/compute/VeloxBackend.cc
- docs/Velox.md
* Update Gluten velox doc for HDFS in HA mode.
* Make the code for creating hdfs client more reasonable.
> Update Gluten HDFS HA mode doc and make code more reasonable

- docs/ClickHouse.md
* removed Arrow install step
* add ch backend debug options
> Update clickhouse backend readme

- tools/gluten-te/dockerfile-tpc
This is not covered by GHA CI so skip it
> Wrong syntax in gluten-te's dockerfile script

- backends-clickhouse/src/main/scala/io/glutenproject/execution/BlockGlutenColumnarToRowExec.scala
- gluten-core/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
- gluten-core/src/main/java/io/glutenproject/substrait/type/NothingNode.java
- gluten-core/src/main/java/io/glutenproject/substrait/type/TypeBuilder.java
- gluten-core/src/main/resources/substrait/proto/substrait/type.proto
- gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [CH-232] Support DataTypeNothing, which close https://github.com/Kyligence/ClickHouse/issues/232

- docs/Velox.md
> Fix Velox docs for generated jar location

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [CH-265] Enable `IN/INSET` test case

- cpp/velox/compute/DwrfDatasource.cc
- cpp/velox/memory/VeloxMemoryPool.cc
- gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-core/src/main/resources/substrait/proto/substrait/plan.proto
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQuerySuite.scala
* Ignore SPARK-33677 UT case, will fix it later.
* Upgrade substrait to 0.22.0.
test by CH[[277]]
> Upgrade Velox to 2023/1/31

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
- gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/NamedExpressionsTransformer.scala
Support offloading grouping sets into clickhouse
unit tests
test by CH[[251]]
> [CH-250]Support grouping sets

- .github/workflows/unittests.yml
- cpp/compile.sh
- dev/builddeps-veloxbe.sh
- docs/ArrowBackend.md
- docs/GlutenUsage.md
- docs/Velox.md
- docs/developers/HowTo.md
- docs/developers/MicroBenchmarks.md
> Remove compile.sh from doc

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-core/src/main/scala/io/glutenproject/expression/StructExpressionTransformer.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenJsonFunctionsSuite.scala
Support more json functions
unit tests
test by CH[[264]]
> [CH-264] support more json functions

- cpp/core/operators/shuffle/splitter.cc
> bugfix：fix the bug of splitter using fixed_width_col_cnt_

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenApproxCountDistinctForIntervalsQuerySuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCTEHintSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCTEInlineSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCachedTableSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenConfigBehaviorSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCountMinSketchAggQuerySuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCsvFunctionsSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameHintSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameWriterV2Suite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDatasetCacheSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenExpressionsSchemaSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenExtraStrategiesSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenMiscFunctionsSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenProcessingTimeSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenScalaReflectionRelationSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSerializationSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenTypedImperativeAggregateSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenUnwrapCastInComparisonEndToEndSuite.scala
Import the remaining useful tests from spark sql.
https://github.com/oap-project/gluten/issues/374
Testing on CI.
> Import the remaining tests

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
see https://github.com/Kyligence/ClickHouse/issues/283
unit tests
test by CH[[288]]
> [CH-283] Aggregate function with const arguments on window

- docs/SupportProgress.md
as title
No test needed, just use the markdown preview function to verify the fix works.
> fix broken image link in SupportProgress.md

- ep/build-arrow/src/get_arrow.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> Enable GlutenJsonFunctionsSuite

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDatasetSerializerRegistratorSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDeprecatedAPISuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenMetadataCacheSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenShowCreateTableSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenStatisticsCollectionSuite.scala
> add some passing tests

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/connector/GlutenDataSourceV2Suite.scala
> Enable GlutenDataSourceV2Suite

- docs/VeloxNotSupport.md
Add spark columnar reading to VeloxNotSupport.
On CI.
> Add spark columnar reading

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQuerySuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/orc/GlutenOrcQuerySuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/orc/GlutenOrcSourceSuite.scala
Enable several test suites.
Testing on CI.
> Enable several test suites

- gluten-data/src/main/java/io/glutenproject/columnarbatch/ArrowColumnarBatches.java
- gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenColumnarToRowExec.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/connector/GlutenDataSourceV2SQLSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/connector/GlutenWriteDistributionAndOrderingSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenFileSourceStrategySuite.scala
Fixed C2R on case that should fallback to vanilla Spark. Enabled some test suites.
Testing on CI.
> Fix C2R on case that should fallback

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenFileSourceStrategySuite.scala
Fix failed unit test on CI.
Testing on CI.
> Fix failed unit test on CI

- cpp/core/operators/shuffle/splitter.cc
1. add an anonymous namespace for module functions
2. move `sizeof_binary_offset` into the loop to fix a bug of `splitter::CreateRecordBatchFromBuffer`
3. modify the comment to avoid misleading
> [cpp] bugfix for splitter::CreateRecordBatchFromBuffer

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenReadSchemaSuite.scala
Enable some remaining tests.
Testing on CI.
> Enable some remaining tests

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> [VL] Enable GlutenBucketedReadWithoutHiveSupportSuite

- .github/labeler.yml
- .github/workflows/labeler.yml
This patch enables auto labeling for PRs
> [Gluten-core] [CI] Auto labeling for pull requests

- gluten-data/src/main/scala/io/glutenproject/execution/GlutenRowToArrowColumnarExec.scala
- gluten-data/src/main/scala/org/apache/spark/sql/utils/SparkArrowUtil.scala
> [VL] [Gluten-911] Fix NullType issue

- docs/developers/docker_centos8.md
- docs/developers/docker_ubuntu22.04.md
- ep/build-velox/src/build_velox.sh
1. add readme for developer to install gluten+velox on centos8.
2.  fix folly not found problem.
> Install gluten+velox on Centos8

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala
add column name on range partition sorting expressions
unit tests
> [CH-293] upgrade clickhouse to 23.1

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [CH][HOTFIX] Fix ch backend upgrade issue

- docs/Velox.md
> fix the typo about how to enable s3 support

- docs/VeloxNotSupport.md
Add Gluten's limitation in detail in doc.
> [VL] Add Gluten velox backend limitation

- cpp/core/operators/shuffle/splitter.cc
The compress_time metric in the PartitionWriter has not been assigned a value, so the total_compress_time_ metric of Splitter cannot obtain accurate data based on it.
> [VL] Fix PartitionWriter metric issue

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [Gluten-core-926] Sync timezone to backend

- .github/workflows/unittests.yml
> [CH] upgrade image version

- docs/VeloxNotSupport.md
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Record the compression codec limitation on certain file format.
Testing on CI.
> [VL] Record the limitation of compression codec

- cpp/core/utils/Print.h
- cpp/velox/shuffle/VeloxSplitter.cc
- cpp/velox/shuffle/VeloxSplitter.h
- cpp/velox/tests/VeloxSplitterTest.cc
1. add tests for VeloxSplitter to validate the PR #1003
2. this work is still in progress, you can review this PR when it's finished.
> [VL] Add Unit-Test for VeloxSplitter

- gluten-core/src/main/java/io/glutenproject/substrait/rel/GenerateRelNode.java
Fix the GenerateRelNode and clean up the code
> [Gluten-core] Fix the GenerateRelNode and clean up the code

- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
This is a small PR, just to see the hadoop configuration key more clearly.
> Add SPARK_HADOOP_PREFIX definition

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/WindowFunctionsBuilder.scala
Support more window functions, lead/lag/dense_rank
`first_value` and `last_value` have different effects in CH, will be added later
unit tests
test by CH[[322]]
> [CH-279] Support more window functions, lead/lag/dense_rank

- cpp/core/utils/Print.h
- cpp/velox/compute/RegistrationAllFunctions.cc
- cpp/velox/shuffle/VeloxSplitter.cc
- cpp/velox/shuffle/VeloxSplitter.h
- cpp/velox/tests/VeloxSplitterTest.cc
add tests for Velox Splitter
more tests are still on the way
> [VL] Add tests for Velox Splitter

- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-core/src/main/scala/io/glutenproject/expression/NamedStructTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/collectionOperationTransformer.scala
> [CH-269]support more struct/array/map functions

- backends-velox/src/main/scala/io/glutenproject/utils/VeloxExpressionUtil.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [CH-290] support to_date/date_format/trunc/add_months/map_from_arrays/translate

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
Support aggregate function collect_list
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this) 
test by CH[[295]]
> [CH-294] support collect_list

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseParquetSuite.scala
> [CH-306]Fix read empty parquet

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- gluten-core/src/main/java/io/glutenproject/substrait/type/MapNode.java
- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
> [CH-256] fully support from_unixtime and arrayJoin

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/ITransformerApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenTransformerApi.scala
Refactor the scan validation logic of different backends.
Testing on CI.
> [Gluten-core] Refactor scan validation

- cpp/velox/shuffle/VeloxSplitter.cc
- cpp/velox/tests/VeloxSplitterTest.cc
> [VL] bugfix for VeloxSinglePartSplitter

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
Enable "function date_add", "function date_sub", "datediff"
> [CH] Enable GlutenDateFunctionsSuite

- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
There are some tests re-written in an abstract class for testing, but it is not actually used.
> [VL] Fix a test issue in GlutenParquetFilterSuite

- cpp/velox/CMakeLists.txt
- cpp/velox/benchmarks/BenchmarkUtils.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/VeloxInitializer.cc
- cpp/velox/compute/VeloxInitializer.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/jni/JniWrapper.cc
This patch improve Velox local cache support:
- expose more configurations on cache: memory cache size, use o_direct write
- move the velox backend initializations into a separate file
manual test.
> [Gluten-1013] [VL] Support Velox local cache

- docs/Velox.md
> [VL] Fix wrong link in doc

- README.md
- docs/developers/CppCodingStyle.md
> [document] update the document of CppCodingStyle.md

- gluten-core/src/main/java/io/glutenproject/vectorized/JniLibLoader.java
- gluten-core/src/main/java/io/glutenproject/vectorized/JniWorkspace.java
- gluten-core/src/main/scala/org/apache/spark/util/GlutenShutdownManager.scala
Use JVM delete on exit hook to delete tmp work dir.
manual test
> [Gluten-core] Delete spark_columnar_plugin_xxx on exit

- cpp/core/operators/shuffle/splitter.cc
- cpp/core/operators/shuffle/splitter.h
- cpp/velox/shuffle/VeloxSplitter.cc
- cpp/velox/shuffle/VeloxSplitter.h
- cpp/velox/tests/VeloxSplitterTest.cc
You can review and approve this PR.
but please don't merge this PR before @jinchengchenghh enable the Velox splitter PR.
I will merge it myself later.
> [VL] Velox splitter supports dictionary encoding

- cpp/core/operators/shuffle/splitter.cc
- cpp/core/operators/shuffle/splitter.h
- cpp/velox/shuffle/VeloxSplitter.cc
- cpp/velox/shuffle/VeloxSplitter.h
- cpp/velox/tests/VeloxSplitterTest.cc
This reverts commit 9be2f04fd4c35f90fd0e46ed2be9d8957bf973c8.
> [VL] Revert "Velox splitter supports dictionary encoding (#1069)"

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
Add some decimal case
test by CH[[348]]
> [CH] Add ch backend decimal suite

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
Fixes Window's fallback logic.
under test
> [VL] Fix window validation

- .github/workflows/velox_be.yml
- README.md
- backends-clickhouse/pom.xml
- backends-velox/pom.xml
- backends-velox/workload/tpch/gen_data/dwrf_dataset/tpch_convert_parquet_dwrf.sh
- backends-velox/workload/tpch/run_tpch/tpch_parquet.sh
- cpp/compile.sh
- dev/builddeps-veloxbe.sh
- docs/ClickHouse.md
- docs/GlutenUsage.md
- docs/UsingS3.md
- docs/Velox.md
- docs/developers/HowTo.md
- docs/developers/MicroBenchmarks.md
- docs/developers/NewToGluten.md
- ep/build-arrow/src/build_arrow_for_velox.sh
- gluten-core/pom.xml
- gluten-data/pom.xml
- gluten-ut/common/pom.xml
- gluten-ut/pom.xml
- gluten-ut/spark32/pom.xml
- gluten-ut/spark33/pom.xml
- package/pom.xml
- pom.xml
- shims/common/pom.xml
- shims/pom.xml
- shims/spark32/pom.xml
- shims/spark33/pom.xml
- substrait/substrait-spark/pom.xml
- tools/gluten-it/pom.xml
1. fix typo build_test -> build_tests
2. add os system name/backend name in jar.
3. change 1.0.0 -> 0.5.0.
4. add  versions-maven-plugin to manage version.
--usage： mvn versions:set -DnewVersion=1.0.3-SNAPSHOT
here is an example name :
For ubuntu 20.04
gluten-velox-bundle-spark3.3_2.12-ubuntu_20.04-0.5.0-SNAPSHOT.jar
For centos 8
gluten-velox-bundle-spark3.3_2.12-centos_8-0.5.0-SNAPSHOT.jar
> [VL] Rename jar for release

- cpp/core/jni/JniWrapper.cc
> [Gluten-core] Remove jni unload log

- docs/developers/NewToGluten.md
> [Documentation] Fix the typo problems of NewToGluten

- docs/developers/docker_centos8.md
- ep/build-velox/src/build_velox.sh
> [VL] Update doc for centos8 install

- docs/Velox.md
> [VL] Add Celeborn support in doc

- cpp/velox/compute/VeloxInitializer.cc
Fix #1124 
Gluten should avoid the behavior may outlive the task, it breaks task execution model.
I'm not sure how performance boost can be gained from split preload, but I guess it gains little. When Velox has more suitable split preload mechanism that execute within lifecycle of task, we will consider open this feature then.
> [Gluten-1124] Close connector preload split on current memory management.

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
Please refer to #1162 
Test manually by check spark WebUI
> [Gluten-1162][CK]fix CoaleseBatches metrics: concatTime and collectTime

- cpp/core/jni/JniWrapper.cc
- gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleSplitterJniWrapper.java
- gluten-data/src/main/scala/org/apache/spark/shuffle/GlutenColumnarShuffleWriter.scala
Optimize the method of obtaining taskAttemptId in nativeMake
> [VL] Optimize the method of obtaining taskAttemptId in nativeMake

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHBroadcastBuildSideRDD.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BroadcastBuildSideRDD.scala
- gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenIteratorApi.scala
Reduce GC Time when executing BHJ for CH backend.
Close #1165.
> [Gluten-1165] Reduce GC Time when executing BHJ for CH backend.

- cpp/core/jni/JniWrapper.cc
- gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleSplitterJniWrapper.java
Optimize nativeMake in JniWrapper
> [VL] Optimize nativeMake in JniWrapper

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
support function isNaN for ch backend
unit tests and manual tests
related issue: [issue-328](https://github.com/Kyligence/ClickHouse/issues/328)
> [CH-328] Support function isNaN

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
support functions position/locate for CH
related issue: [CH-313](https://github.com/Kyligence/ClickHouse/issues/313)
test by CH[[314]]
> [CH-313] support functions position/locate

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHShuffleSplitterJniWrapper.java
- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
related issue: [issue-353](https://github.com/Kyligence/ClickHouse/issues/353)
test by CH[[354]]
> [CH-353] ShuffleSplitter improvement for CH backend

- dev/buildbundle-veloxbe.sh
> [VL] Fix spark 3.3 build broken

- dev/builddeps-veloxbe.sh
- docs/GlutenUsage.md
- docs/SupportProgress.md
- docs/Velox.md
- docs/developers/CppCodingStyle.md
- docs/developers/HowTo.md
> [VL] Fix typo in doc

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
Fix some CH backend test cases
> [CH] Fix some CH backend test cases

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenJoinSuite.scala
Support full join and join on condition
test by CH[[366]]
> [CH-366]Support full join

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
Fix inconsistent results when the start_pos parameter of the position function is null
> [CH] Fix inconsistent results of position function for ch backend

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- gluten-core/src/main/java/io/glutenproject/vectorized/NativeExpressionEvaluator.java
- gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
- gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenTransformerApi.scala
Introduce post process for native config to inject some spark config to it
> [CH-318] Introduce post process for native config to inject some spark config to it 

- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenCoalesceShufflePartitionsSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/exchange/GlutenEnsureRequirementsSuite.scala
Remove some print method in ut
> [CH] Remove some print method in ut

- README.md
Add Meituan's email into Contact.
n/a
> [VL]Add Meituan email in contact.

- gluten-core/pom.xml
- pom.xml
- shims/common/pom.xml
- shims/pom.xml
> [GLUTEN-1207] Fix a dependency issue for spark shims

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- ep/build-velox/src/get_velox.sh
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameWindowFunctionsSuite.scala
support corr, covar_pop and covar_samp agg function.
add test in velox backend TestOperator.
> [VL] Agg support Covariance function

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Enabled UT on casting from bool/date/float to decimal.
https://github.com/oap-project/velox/pull/170
https://github.com/oap-project/gluten/issues/1217
Testing on CI.
> [VL][UT] Enable UT on some cast functions

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
fix memory leak on coalesce
unit tests
test by CH[[315]]
> [CH] Fix memory leak on coalesce

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala
unit tests
close https://github.com/Kyligence/ClickHouse/issues/382
> [CH-382] Fix bug about `collect_list`

- pom.xml
Migrate the Celeborn package to the official version
> [VL] Migrate the Celeborn package to the official version

- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/h/TpchDataGen.scala
Support tpch to use decimal type in Velox CI
> [VL] Support tpch to use decimal type in Velox CI

- cpp/core/compute/Backend.h
- cpp/core/tests/BackendTest.cc
- cpp/velox/benchmarks/BenchmarkUtils.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
1. the GetResultIterator() used by by unit test & benchmark doesn't need the argument `sessionConf`
2. make `confMap` under the anonymous namespace
3. change the argument to the type of `const reference` 
> [VL] Refactor Backend's interface and ConfMap

- .github/workflows/velox_be.yml
- tools/gluten-it/src/main/java/io/glutenproject/integration/tpc/Tpc.java
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/TpcSuite.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/ds/TpcdsSuite.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/h/TpchSuite.scala
Support Celeborn Integration Testing in Velox CI
> [VL] Support Celeborn integration testing in Velox CI

- cpp/velox/tests/ArrowToVeloxTest.cc
> [VL] Enable decimalV2A test

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
decimal sum support overflow
ci test
> [VL] Decimal sum support overflow

- .github/workflows/velox_be.yml
- tools/gluten-it/README.md
- tools/gluten-it/src/main/java/io/glutenproject/integration/tpc/Tpc.java
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/Constants.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/TpcSuite.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/action/QueriesCompare.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/ds/TpcdsSuite.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/h/TpchSuite.scala
> [VL] Following #1185, do some clean-ups against Velox + Celeborn CI

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCDSSuite.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/ds/TpcdsSuite.scala
- Fix allowPrecisionLoss false mode
- Fix decimal * int literal
> [GLUTEN-1246] [CORE] Fix scale may be negative issue

- gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-data/src/main/scala/io/glutenproject/execution/GlutenFilterExecTransformer.scala
Minor change for log.
Manually tested in local.
> minor log change for filter validation

- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenBloomFilterAggregateQuerySuite.scala
Encounter this error when we run q93, we increase settings "spark.sql.optimizer.runtime.bloomFilter.maxNumItems" for our tests. add UT for fix in velox.
Reason: (5404631 vs. 4000000) estimatedNumItems argument must be constant for all input rows
Expression: newVal == val
Function: setConstantArgument
File: /var/git/Velox/velox/functions/sparksql/aggregates/BloomFilterAggAggregate.cpp
Line: 225
UT.
> [VL] Ut for bloomfilter validation fix

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala
- dev/package.sh
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
package and load so from jar support alinux
> [VL] package and velox scripts add alinux support

- dev/package.sh
package.sh has some format error.
> [VL] Quick fix package.sh

- tools/gluten-te/centos/centos-7-deps.sh
The connection to centos.org is unstable on CI servers
> [CI] Update repo url for centos 7

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
Fixes: https://github.com/Kyligence/ClickHouse/issues/398
unit tests
test by CH[[404]]
> [CH-398] Add test case for `collect_list`

- gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarHashedRelation.scala
> [minor] fix typo

- cpp/core/operators/r2c/RowToArrowColumnarConverter.cc
- cpp/core/shuffle/ArrowShuffleWriter.cc
Some newly added codes make compilation under aarch64 fail. This PR fixes these issues.
Compile success under aarch64 env.
> Fix aarch64 compile error

- gluten-core/src/main/scala/io/glutenproject/softaffinity/SoftAffinityManager.scala
- gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinityUtil.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
The job gets stuck in log printing for a long time while trying to read a large amount of files, thus we add a config to control the loglevel for soft-affinity.
unit tests.
> [GLUTEN-1357][CORE] Change soft-affinity log level from INFO to DEBUG

- .github/workflows/velox_be.yml
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/Constants.scala
- tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/action/QueriesCompare.scala
Increase the scale of testing TPC-DS dataset from 0.1G to 1.0G, 10.0G and 30.0G.
Testing the time consumption.
> [VL][CI] Increase the scale of testing dataset

- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
> [GLUTEN-1396][ClickHouse-Backend] fix assert failure in c2r and r2c 

- backends-velox/src/main/java/io/glutenproject/spark/sql/execution/datasources/velox/DatasourceJniWrapper.java
- backends-velox/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxDatasourceUtil.scala
- backends-velox/src/main/scala/org/apache/spark/sql/VeloxColumnarRules.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxColumnarBatchIterator.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxWriteQueue.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/v2/velox/VeloxParquetDatasourceV2.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/v2/velox/VeloxParquetTable.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetFileFormat.scala
- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCDSSuite.scala
- cpp/core/compute/Backend.h
- cpp/core/config/GlutenConfig.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/operators/writer/Datasource.h
- cpp/velox/CMakeLists.txt
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/VeloxParquetDatasource.cc
- cpp/velox/compute/VeloxParquetDatasource.h
- cpp/velox/jni/JniWrapper.cc
- ep/build-velox/src/get_velox.sh
- gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
- Add VeloxParquetFileFormat to offload Parquet write to native and use Velox parquet writer to write parquet file.
- Remove Dwrf file format 
Add unit test
> [GLUTEN-1245][VL][Feat]  Add VeloxParquetFileFormat to support parquet write in velox backend.

- .gitignore
- docs/ClickHouse.md
> [CH] refine clickhouse doc

- cpp-ch/local-engine/Storages/ch_parquet/OptimizedArrowColumnToCHColumn.cpp
Fix the bug: exceptions throws when select from a colum contains a lot of NULL value
(Fixes: \#1452)
manual tests
> [GLUTEN-1452][CH]Bug fix select column with lots of NULL value

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseColumnarShuffleAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
Fix ut errors after disable CoalesceBatchesExec for CH backend
Fixed: #1483.
Close #1483.
> [GLUTEN-1483][CH] Fix ut errors after disable CoalesceBatchesExec for CH backend

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/test/scala/io/glutenproject/RunTPCHTest.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- docs/ClickHouse.md
- gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
- support spill settings: max_bytes_before_external_sort and max_bytes_before_external_group_by 
- fix wrong expression mapping of murmur3hash
(Fixes: \#1376)
> [GLUTEN-1376][CH] feat: support spill settings: max_bytes_before_external_sort and max_bytes_before_external_group_by

- cpp/velox/CMakeLists.txt
- cpp/velox/compute/RegistrationAllFunctions.cc
Move row_number() method from presto sql to spark sql.
existing unit test.
> [GLUTEN--1491] [VL] [feat] Refine row_number() method in velox backend.

- gluten-data/src/main/java/io/glutenproject/vectorized/ArrowColumnVector.java
- gluten-data/src/main/java/io/glutenproject/vectorized/ArrowWritableColumnVector.java
Fix no such method exception of shaded arrow
#1416
> [GLUTEN-1416][VL] Fix no such method exception of shaded arrow

- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenMathFunctionsSuite.scala
Fix expression ut result is not check.And add check result.
Test by UT.
> [Gluten] Fix expression ut result is not check

- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Common/QueryContext.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- docs/ClickHouse.md
- gluten-core/pom.xml
- gluten-ut/pom.xml
- pom.xml
- shims/pom.xml
- substrait/substrait-spark/pom.xml
checkout https://github.com/Kyligence/ClickHouse/issues/384
this Patch will later be test covered by our integration test
> [GLUTEN-384][CH] support reading from S3 and local cache on S3

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Functions/regexpExtractAllSpark.cpp
- cpp-ch/local-engine/Functions/registerFunctions.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
Fixes: https://github.com/Kyligence/ClickHouse/issues/416
> [GLUTEN-1391][CH]support function regexp_extract_all

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHInitializerApi.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
FIx clickhouse backend not sync timezone config
> [GLUTEN-1502][CH] Fix timezone config sync to backend

- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHManagedReservationListener.java
- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHMemoryAllocatorManager.java
- backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CHColumnarBatchSerializer.scala
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Common/QueryContext.cpp
- gluten-core/src/main/java/io/glutenproject/memory/GlutenMemoryConsumer.java
- gluten-core/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocator.java
- pom.xml
this PR is first step of https://github.com/oap-project/gluten/issues/1472
> [GLUTEN-1472][CH] Refine clickhouse memory audit

- docs/Configuration.md
- docs/SupportProgress.md
- docs/VeloxNotSupport.md
- docs/_config.yml
- docs/archive.md
- docs/contact-us.md
- docs/developers/CppCodingStyle.md
- docs/developers/HowTo.md
- docs/developers/MicroBenchmarks.md
- docs/developers/NewToGluten.md
- docs/developers/README.md
- docs/developers/docker_centos7.md
- docs/developers/docker_centos8.md
- docs/developers/docker_ubuntu22.04.md
- docs/developers/velox-function-development-guide.md
- docs/download.md
- docs/get-started/ClickHouse.md
- docs/get-started/GlutenUsage.md
- docs/get-started/UsingS3.md
- docs/get-started/Velox.md
- docs/get-started/getting-started.md
- docs/index.md
Doc refactor to enable github pages
Docs refactor, use exist UTs
> [GLUTEN-1480][DOC] Refactor to enable github pages

- .github/workflows/code_style.yml
- dev/formatcppcode.sh
- docs/developers/NewToGluten.md
> [VL] Use clang-format 12 to format check

- docs/VeloxNotSupport.md
Add the limitation for df.describe() method
No need test
> [VL] [DOC] Add the limitation for df.describe() method

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/expression/CHExpressionTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-1394][CH] support sha1/sha2/crc32 hash functions

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
re open some test cases since we have solved  #1472
> [CH] un-ignore some test cases

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
Bug fix no result returned in max/min/sum/count while select from empty table/partition
the related pr of clickhouse backend:  https://github.com/Kyligence/ClickHouse/pull/424
the related issue: https://github.com/Kyligence/ClickHouse/issues/425
fix issue #1404 
by unit test
> [GLUTEN-1404][CH] Bug fix no result returned in max/min/sum/count while select from empty table/partition

- README.md
- docs/contact-us.md
- docs/developers/HowTo.md
- docs/developers/NewToGluten.md
- docs/developers/docker_centos7.md
- docs/developers/docker_centos8.md
- docs/developers/docker_ubuntu22.04.md
- docs/download.md
- docs/get-started/ClickHouse.md
- docs/get-started/GlutenUsage.md
- docs/get-started/Velox.md
- docs/index.md
Fix link issue in https://oap-project.github.io/gluten/
Docs fix, use exist UTs
> [GLUTEN-1545][DOC] Fix link issues in github pages

- cpp/core/CMakeLists.txt
- cpp/core/benchmarks/ShuffleSplitBenchmark.cc
- cpp/core/compute/Backend.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/shuffle/ArrowShuffleWriter.cc
- cpp/core/shuffle/ArrowShuffleWriter.h
- cpp/core/shuffle/FallbackRangePartitioner.cc
- cpp/core/shuffle/FallbackRangePartitioner.h
- cpp/core/shuffle/HashPartitioner.cc
- cpp/core/shuffle/HashPartitioner.h
- cpp/core/shuffle/Partitioner.cc
- cpp/core/shuffle/Partitioner.h
- cpp/core/shuffle/RoundRobinPartitioner.cc
- cpp/core/shuffle/RoundRobinPartitioner.h
- cpp/core/shuffle/ShuffleWriter.h
- cpp/core/shuffle/SinglePartPartitioner.cc
- cpp/core/shuffle/SinglePartPartitioner.h
- cpp/core/shuffle/type.h
- cpp/core/tests/ArrowShuffleWriterTest.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
- docs/developers/NewToGluten.md
（1）Decoupling Partitioner(compute partition) and ShuffleWriter
（2）Add RoundRobinPartitioner 、SinglePartPartitioner、HashPartitioner、 FallbackRangePartitioner to support different partition methods
(Fixes: \#1205)
> [GLUTEN-1205][VL] Refactor shuffle partitioner

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenJsonExpressionsSuite.scala
> [GLUTEN-1524][CH] Apply new functions merged into ClickHouse/ClickHouse after v23.1: regexpExtract/jsonarraylength

- ep/build-velox/src/get_velox.sh
reset velox repo/branch to oap-project for PR 1513
> [VL] set velox repo/branch to oap-project

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-1431][CH]Fix cast exception when input value is null

- docs/get-started/GlutenUsage.md
- ep/build-velox/src/build_velox.sh
https://github.com/oap-project/gluten/issues/1575
> [GLUTEN-1575][VL] Add a parameter run_setup_script to control whether to run velox setup

- README.md
Fix links for [Build with Velox] and [Build with ClickHouse Backend]
> [DOC] Fix links for [Build with Velox] and [Build with ClickHouse Backend]

- ep/build-arrow/src/build_arrow.sh
output compile_commands.json when building arrow.
> [VL] Generate compile_commands.json on arrow build

- gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenJoinSuite.scala
> [GLUTEN-1577][CORE] Respect spark's config for case sensitive when get attribute name

- cpp/core/CMakeLists.txt
- cpp/core/benchmarks/CompressionBenchmark.cc
- cpp/core/benchmarks/ShuffleSplitBenchmark.cc
- cpp/core/jni/JniCommon.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/memory/HbwAllocator.cc
- cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
- cpp/core/shuffle/ArrowShuffleWriter.cc
- cpp/core/shuffle/HashPartitioner.cc
- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/LocalPartitionWriter.h
- cpp/core/shuffle/PartitionWriterCreator.h
- cpp/core/shuffle/rss/CelebornPartitionWriter.cc
- cpp/core/shuffle/rss/CelebornPartitionWriter.h
- cpp/core/tests/ArrowShuffleWriterTest.cc
- cpp/core/tests/HbwAllocatorTest.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/VeloxInitializer.cc
- cpp/velox/jni/JniWrapper.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
#1544 had rebase conflictions with #1580 , this is a fix for the new codes.
> [VL] Following GLUTEN-1205, fix malformed namings

- .github/workflows/velox_be.yml
disable static linking test temporary
pass GHA
> [VL][HOTFIX] disable static linking test temporary

- .github/workflows/clickhouse_be_trigger.yml
fix github action ch trigger error
> [CH] Fix github action ch trigger error

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [CH] Enable tpcds more tests

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
This PR will lead to CI failed, revert first.
Reverts oap-project/gluten#1624
> Revert "[CH] Enable tpcds more tests"

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
Fix substait parse error.
Enable tpcds fixed tests.
> [Gluten-1315][CH] Enable tpcds fixed tests

- cpp-ch/CMakeLists.txt
- cpp-ch/clickhouse.version
> [GLUTEN-1634][CH] enable update clickhouse version with config file

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
- cpp/velox/compute/VeloxColumnarToRowConverter.cc
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/tests/ArrowToVeloxTest.cc
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenIteratorApi.scala
- gluten-data/src/main/scala/io/glutenproject/execution/GlutenRowToArrowColumnarExec.scala
- gluten-data/src/main/scala/org/apache/spark/sql/utils/SparkArrowUtil.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLInsertTestSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenStatisticsCollectionSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetPartitionDiscoverySuite.scala
Offload timestamp reader to Velox.
https://github.com/oap-project/velox/pull/205
https://github.com/oap-project/gluten/issues/1433
under test
> [GLUTEN-1433][VL] feat: offload timestamp scan to Velox - phase 1

- cpp/core/shuffle/ArrowShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
Fix cpp build failure on aarch64
> [Minor] Fix arm build

- gluten-core/src/main/scala/org/apache/spark/util/SparkResourcesUtil.scala
Support get the total cores of the Spark application in kubernetes.
> [GLUTEN-1658] [CORE] feat: Support SparkResourcesUtil.scala in k8s

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
The issue is described in here #1645
unit tests
> [GLUTEN-1645][CH] Disable vectorized reading of vanilla Spark for CH backend

- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- cpp/velox/CMakeLists.txt
- cpp/velox/compute/VeloxParquetDatasource.cc
- cpp/velox/compute/VeloxParquetDatasource.h
- ep/build-velox/src/get_velox.sh
This patch adds hdfs support for parquet write
(Fixes: #1638)
> [GLUTEN-1638][VL] feat: Add hdfs  support in parquet write

- backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoader.scala
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderCentos7.scala
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderCentos8.scala
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderUbuntu2004.scala
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderUbuntu2204.scala
> [MINOR] add missing ASF header

- cpp-ch/local-engine/Builder/BroadCastJoinBuilder.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [CH] minor improvements for BroadCastJoinBuilder

- docs/get-started/ClickHouse.md
> [CH] minor, update jenkins ci url

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> [GLUTEN-1478][VL] fix: Enable the date relate functions in GlutenDateExpressionSuite

- docs/get-started/Velox.md
It seems there is no kerberos docs, but the libhdfs3 supports it.
This pr improves the docs about hdfs and kerberos with velox.
> [VL][DOCS] Improve hdfs and kerberos docs with velox

- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/URLDecoder.h
- cpp/core/utils/metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
- ep/build-velox/src/get_velox.sh
- gluten-data/src/main/java/io/glutenproject/metrics/Metrics.java
- gluten-data/src/main/java/io/glutenproject/metrics/OperatorMetrics.java
- gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenMetricsApi.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/BatchScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/FileSourceScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
Support metrics on splits and row groups.
Fixes: https://github.com/oap-project/gluten/issues/1704.
under test
> [GLUTEN-1704][VL] Support metrics on splits and row groups

- cpp-ch/CMakeLists.txt
- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Functions/regexpExtractAllSpark.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Shuffle/SelectorBuilder.h
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.h
- cpp-ch/local-engine/Storages/StorageJoinFromReadBuffer.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
rebase ClickHouse to date 20230517, mainly improve seek performance, speed up 1.18
> [GLUTEN-1632][CH]Update Clickhouse Version (20230517)

- cpp-ch/local-engine/docker/image/Dockerfile
(Fixes: #1738)
manual tests, run ep/build-clickhouse/src/build_clickhouse.sh
> [GLUTEN-1738][CH]Update libchbuilder dockerfile to make build latest Clickhouse

- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
https://github.com/oap-project/gluten/issues/1478
Testing on CI.
> [GLUTEN-1478][VL] enable timestamp expression tests

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> [GLUTEN-1478][VL] fix: enable makedecimal suite

- backends-velox/src/main/java/io/glutenproject/spark/sql/execution/datasources/velox/DatasourceJniWrapper.java
- backends-velox/src/main/scala/io/glutenproject/utils/VeloxDatasourceUtil.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetFileFormat.scala
- cpp/core/compute/Backend.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/operators/writer/Datasource.h
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/VeloxParquetDatasource.cc
- cpp/velox/compute/VeloxParquetDatasource.h
- ep/build-velox/src/get_velox.sh
This patch improved the parquet write behavior on HDFS/Local
Fixes: #1712 
pass jenkins
> [GLUTEN-1712][VL] feat: Write parquet data into temp dir

- cpp/velox/benchmarks/CMakeLists.txt
- cpp/velox/benchmarks/ParquetWriteBenchmark.cc
This PR add the parquet writer benchmark in velox backend.
> [VL] Add parquet write benchmark

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Fixed with https://github.com/oap-project/gluten/pull/1735
> [GLUTEN-1478] Enable failed UT in GlutenIntervalExpressionsSuite

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
dependency https://github.com/oap-project/velox/pull/266
> [VL] Result mismatch with Vanilla Spark on log2/log10

- cpp/velox/benchmarks/ParquetWriteBenchmark.cc
Fix parquet write benchmark compile issue
> [VL] fix: fix parquet write benchmark compile

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
https://github.com/oap-project/gluten/issues/1478
> [VL] Enable tests for string for ascii, replace

- ep/build-velox/src/get_velox.sh
fix alinux3 velox compilation exception
> [GLUTEN-1760][VL] fix alinux3 velox compilation exception

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenLiteralExpressionSuite.scala
Enable `from decimal`.
Depends on: https://github.com/oap-project/velox/pull/283.
https://github.com/oap-project/gluten/issues/1478
Testing on CI.
> [GLUTEN-1478][VL] Enable test on casting from decimal to bool

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHValidatorApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuit.scala
- cpp-ch/local-engine/Functions/FunctionGetJsonObject.cpp
- cpp-ch/local-engine/Functions/FunctionGetJsonObject.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
Fixes: https://github.com/oap-project/gluten/issues/1518
unit tests
> [GLUTEN-1518][CH] Improve compatibility of get_json_object

- cpp/core/jni/JniCommon.h
- cpp/velox/compute/VeloxInitializer.cc
- cpp/velox/compute/VeloxInitializer.h
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
support split preload
Fixes: #1794
> [GLUTEN-1794][VL] support split preload

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuit.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseMetricsSuite.scala
- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/AggregateRelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-1754][CH] Support aggregate functions with multiple arguments

- cpp-ch/local-engine/Functions/FunctionGetJsonObject.h
> [CH]fix a typos

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
This patch adds support for basic sql like `select sum(1)  from table`, following the example of `count(1)`
> [VL] Fix: Support select sum(1)

- cpp-ch/local-engine/Common/Logger.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [CH] Format log output for CH backend

- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-384][CH] fix bug for aws cn case

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- ep/build-velox/src/get_velox.sh
> [GLUTEN-1809][VL] Enable date type for kPreceding & kFollowing window range bound

- cpp-ch/local-engine/Operator/ExpandStep.cpp
- gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
> [CH] Fix expand transformer can't collect metrics

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/PlanNodesUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetColumnarShuffleAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
Fix error 'attribute binding failed.' when executing hash agg
Close #1620.
(Fixes: #1620)
> [GLUTEN-1620][CH] Fix error 'attribute binding failed.' when executing hash agg

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/proto/CMakeLists.txt
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230603)

- cpp-ch/local-engine/Operator/BlocksBufferPoolTransform.cpp
- cpp-ch/local-engine/Operator/BlocksBufferPoolTransform.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-1847][CH]Prefech data from  source nodes

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230607)

- cpp/core/compute/Backend.h
- cpp/core/jni/JniWrapper.cc
- cpp/velox/benchmarks/QueryBenchmark.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
Add SparkTaskInfo to wrap stageId, taskId, partitionId, and use it to identify Velox task.
> [GLUTEN-CORE] [VL] Add SparkTaskInfo to wrap stageId, taskId, partitionId

- gluten-core/src/main/java/io/glutenproject/substrait/expression/StructLiteralNode.java
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-1860] StructLiteral support null literal

- docs/get-started/Velox.md
> [VL][DOC] Update celeborn doc

- backends-clickhouse/src/main/scala/org/apache/spark/sql/hive/CHHiveTableScanExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/JsonFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/JsonFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
(Fixes: \#1877)
代码改动: 
- 复用HiveText input format, 去除重复代码
- 修复text格式input_field_names初始化错误导致的查询失败
- 修复count(1)/count(*)查询失败 
> [GLUTEN-1877][CH] Fix bugs when reading hive text

- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/joins/GlutenBroadcastJoinSuite.scala
> [UT] Fix a config overwritten issue in UT

- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/resources/gluten-source-exclude-sparkshims.xml
- ep/build-clickhouse/src/build_clickhouse.sh
- ep/build-clickhouse/src/package.sh
- ep/build-clickhouse/src/resources/bin/check_env.sh
- ep/build-clickhouse/src/resources/bin/gluten.sh
Separate spark shims from gluten jar so that one gluten package can run on spark32 and spark33
(Fixes: \#1934)
> [GLUTEN-1934][CH] Separate spark shims from gluten jar

- cpp-ch/CMakeLists.txt
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/tests/CMakeLists.txt
- cpp-ch/local-engine/tests/gtest_ch_join.cpp
- cpp-ch/local-engine/tests/gtest_ch_storages.cpp
- cpp-ch/local-engine/tests/gtest_local_engine.cpp
- cpp-ch/local-engine/tests/gtest_parquet_read.cpp
Reopen C++ Unit test and benchmark test.
(Fixes: #1929)
Using Existed Test.
> [GLUTEN-1929][CH][TEST]Fix: Enable C++ Unit test

- .github/workflows/velox_be.yml
- dev/get_spark_env.sh
move slow tests into another job for Spark3.3
pass GHA
> [GLUTEN-1336][VL] CI: move slow tests into another job for Spark3.3

- docs/developers/docker_centos7.md
- docs/developers/docker_centos8.md
- docs/developers/docker_ubuntu22.04.md
- docs/get-started/Velox.md
Rectify the documentation
(Fixes: \#1980)
Local compilation successful.
> [GLUTEN-1980][VL][DOCS] Update the documentation for compiling Gluten+Velox with Docker

- ep/build-velox/src/build_velox.sh
If we use custom Arrow code path and build it before Velox, Velox could use pre-build libs.
> [BUILD] Allow use custom ARROW_HOME for Velox

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230616)

- backends-clickhouse/src/main/scala/org/apache/spark/sql/hive/CHHiveTableScanExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseFileFormatSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
* Fix the null behavior consistent with spark
* Fix date and datetime may read wrong day
test by ut
> [GLUTEN-1938][CH] Fix hive reader read empty as null

- gluten-ut/pom.xml
- gluten-ut/spark32/pom.xml
add jvm args in compile scala test code to avoid stackoverflow
> [UT] Minor: add jvm xss configuration in gluten-ut to avoid stackoverflow

- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Exclude `should be able to resolve a persistent view`.
Testing on CI.
> [UT][VL] Exclude unstable test 

- cpp-ch/local-engine/Common/CHUtil.cpp
> [CH] Add new config use_current_directory_as_tmp

- cpp-ch/local-engine/CMakeLists.txt
> [GLUTEN-1963][CH] fix clang16 compile error

- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/statistics/SparkFunctionStatistics.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/statistics/SparkFunctionStatistics.scala
This is a rough summary by testing example query for spark registered functions.
There are some false positive & false negative cases for some functions. For such situation, we need to use a suitable test sql to do the check. Will include this in a follow-up PR.
> [GLUTEN-1945] Support summarizing the supported spark built-in functions

- backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala
- cpp/core/jni/JniWrapper.cc
- cpp/core/operators/c2r/ArrowColumnarToRowConverter.h
- cpp/core/operators/c2r/ColumnarToRow.h
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxColumnarToRowConverter.cc
- cpp/velox/compute/VeloxColumnarToRowConverter.h
- gluten-data/src/main/java/io/glutenproject/columnarbatch/GlutenColumnarBatches.java
- gluten-data/src/main/java/io/glutenproject/vectorized/NativeColumnarToRowJniWrapper.java
> [GLUTEN-CORE][VL] Minor refactor c2r codes to improve readability

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Functions/CMakeLists.txt
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230624)

- docs/get-started/Velox.md
Update docs about hdfs support.
Fixes: #2047
> [GLUTEN-2047][DOC] Fix hdfs docs for build and configuration

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.h
> [GLUTEN-1956][CH] Fix error conversion of Float32 in CHColumnToSparkRow

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/expression/CHExpressionTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenPredicateSuite.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-1942][CH] Support function EqualNullSafe

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetWriteSuite.scala
- ep/build-velox/src/get_velox.sh
https://github.com/oap-project/gluten/issues/2036
> [GLUTEN-2036][VL] fix: Fix the core dump issue when the reading the written parquet file by velox parquet writer

- docs/get-started/ClickHouse.md
> [GLUTEN-2076][CH]Update doc about gluten on yarn with clickhouse backend

- backends-clickhouse/src/main/scala/org/apache/spark/sql/hive/CHHiveTableScanExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
Fix error
```
Error in query: Can't find required partition column day in partition schema StructType()
```
(Fixes: \#2022)
> [GLUTEN-2022][CH]Fix error: Can't find required partition column day in partition schema StructType()

- dev/gluten-build-info.sh
- gluten-core/pom.xml
- gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
- gluten-core/src/main/scala/io/glutenproject/glutenproject.scala
log build info on loading gluten plugin for clickhouse backend
(Fixes: \#2024)
manual tests
> [GLUTEN-2024][CH] log build info

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/AggregateRelParser.h
- cpp-ch/local-engine/Parser/RelParser.h
> [GLUTEN-2079][CH]Support aggregate expression with filter

- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
> [GLUTEN-2101][CH] Fixes bugs in aggregate expressions with filter

- gluten-core/src/main/scala/org/apache/spark/util/memory/TaskResources.scala
Don't log task failed message when it's a speculation task
(Fixes: \#2085)
> [GLUTEN-2085] Don't log task failed message when it's a speculation task

- cpp/CMakeLists.txt
- cpp/compile.sh
- docs/get-started/Velox.md
- ep/build-arrow/src/build_arrow.sh
- ep/build-arrow/src/get_arrow.sh
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
After this PR, ep location will like below:
Velox: ep/build-velox/velox-ep
Arrow: ep/build-arrow/arrow-ep
Arrow install dir: ep/build-arrow/arrow_install
> [DOC] Fix docs for build Velox/Arrow separately and related scripts

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
this pr is relay on another clickhouse pr: https://github.com/ClickHouse/ClickHouse/pull/50712
(Fixes: \#1892)
unit tests 
> [GLUTEN-1892][CH]Bug fix txt table field delimiter by whitespace or tab

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/WindowRelParser.cpp
Fix window function lead/lag use null as default value
Fixes: #2009
UT coverage.
> [GLUTEN-2009][CH] Fix window function lead/lag use null as default value

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/expression/CHExpressionTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDatetimeExpressionSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
Support date_trunc function.
Close #2109.
(Fixes: #2109)
> [GLUTEN-2109] Support date_trunc function

- backends-clickhouse/src/test/resources/tpcds-queries-output/q17.out
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
> [GLUTEN-2140][CH] tpcds q17 inconsistent result in stddev_samp, ignore this

- cpp-ch/local-engine/Parser/FunctionExecutor.cpp
- cpp-ch/local-engine/Parser/FunctionParser.cpp
- cpp-ch/local-engine/Parser/FunctionParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/example_udf/myMd5.cpp
> [GLUTEN-1874][CH]Refactor non-nullable columns resolving

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/WindowRelParser.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2060][CH]Support first_value/last_value

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230630)

- docs/get-started/Velox.md
- docs/get-started/VeloxS3.md
Fix markdown xml parsing issue when deploy to github page
Just doc update, no tests required
> [GLUTEN-2154][DOC] Fix Github pages parsing Markdown files issue

- gluten-core/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala
> [GLUTEN-1866][CORE] Fix a NPE in creating gluten executor endpoint

- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/json/GlutenJsonSuite.scala
add GlutenAdaptiveQueryExecSuite and GlutenJsonSuite for spark3.3
UT
> [GLUTEN-1336][VL] UT: add GlutenAdaptiveQueryExecSuite and GlutenJsonSuite for spark3.3

- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-2191][CH] Improve transform for `arrayElement` and `tupleElement`

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-1554][CH] Support collect_set

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230707)

- cpp/core/compute/Backend.h
- cpp/core/compute/ResultIterator.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
- cpp/core/operators/c2r/ColumnarToRow.cc
- cpp/core/operators/c2r/ColumnarToRow.h
- cpp/core/operators/r2c/RowToColumnar.h
- cpp/core/shuffle/ArrowShuffleWriter.cc
- cpp/core/shuffle/ArrowShuffleWriter.h
- cpp/core/shuffle/ShuffleWriter.h
- cpp/core/shuffle/utils.h
- cpp/core/utils/metrics.h
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
- docs/get-started/Velox.md
- docs/get-started/VeloxS3.md
- tools/gluten-te/centos/defaults.conf
- tools/gluten-te/ubuntu/defaults.conf
Fix coverity cpp scan issues
Using exist UTs
> [GLUTEN-2187][VL] Fix coverity cpp scan issues

- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
- gluten-core/src/main/java/io/glutenproject/row/SparkRowInfo.java
- gluten-core/src/main/java/io/glutenproject/vectorized/JniResourceHelper.java
- gluten-core/src/main/java/io/glutenproject/vectorized/NativeSerializableObject.java
- gluten-data/src/main/java/io/glutenproject/memory/alloc/ManagedReservationListener.java
- gluten-data/src/main/java/io/glutenproject/metrics/Metrics.java
- gluten-data/src/main/java/io/glutenproject/metrics/OperatorMetrics.java
- gluten-data/src/main/java/io/glutenproject/vectorized/ArrowWritableColumnVector.java
- gluten-data/src/main/java/io/glutenproject/vectorized/NativeColumnarToRowInfo.java
Fix coverity Java scan issues
Using exist UTs
> [GLUTEN-2227][VL] Fix coverity Java scan issues

- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
> [GLUTEN-1434][VL] Optimize shuffle get batch

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Enables tests on nested struct schema pruning with its support.
Depends on: https://github.com/oap-project/velox/pull/354.
Testing on CI.
> [GLUTEN-1476][VL] Enable nested struct schema pruning

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Operator/EmptyProjectStep.cpp
- cpp-ch/local-engine/Operator/EmptyProjectStep.h
- cpp-ch/local-engine/Parser/ProjectRelParser.cpp
- cpp-ch/local-engine/Parser/ProjectRelParser.h
- cpp-ch/local-engine/Parser/RelParser.cpp
- cpp-ch/local-engine/Parser/RelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-2243][CH] Fixes error on empty `project`

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-1822][CH] reverse/concat functions support array type parameter

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/hash.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/murmur3hash.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/xxhash64.cpp
> [GLUTEN-2256][CH]Fix xxhash64/hash when input args has byte/short types

- gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
Remove the fallback logic on merge schema option.
Testing on CI.
> [GLUTEN-1476][CORE] Enable merge schema option

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
> [CH] Fix TPCDS q14

- docs/velox-backend-limitations.md
Update limitations of table scan.
Testing on CI.
> [GLUTEN-2240][DOC] Update limitations of table scan

- gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
Caused by https://github.com/oap-project/gluten/commit/36860d4eba9430b437d054a71a96f6eae6050fa2
> [CORE] Quick fix for CI failure

- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-2090] fix type id cast bug

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
- cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.cpp
- cpp-ch/local-engine/Parser/aggregate_function_parser/CountParser.cpp
- cpp-ch/local-engine/Parser/aggregate_function_parser/CountParser.h
Fixes: https://github.com/oap-project/gluten/issues/1790
unit tests
> [GLUTEN-1790][CH] Support count with multiple arguments

- cpp-ch/local-engine/Builder/BroadCastJoinBuilder.cpp
- cpp-ch/local-engine/Parser/FunctionParser.cpp
- cpp-ch/local-engine/Parser/RelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/SparkRowToCHColumn.h
- cpp-ch/local-engine/Parser/TypeParser.cpp
- cpp-ch/local-engine/Parser/TypeParser.h
- cpp-ch/local-engine/Parser/WindowRelParser.cpp
- cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.cpp
- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
> [CH] Refactor type parsing

- README.md
- docs/velox-backend-limitations.md
> [DOC] Refine some documents

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
- backends-clickhouse/src/test/scala/io/glutenproject/s3/S3AuthSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Common/QueryContext.h
- cpp-ch/local-engine/Common/common.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
> [GLUTEN-2199][CH] support dynamically configure per bucket roles

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionNextDay.cpp
- cpp-ch/local-engine/Functions/SparkFunctionNextDay.h
- cpp-ch/local-engine/Parser/scalar_function_parser/CommonScalarFunctionParser.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/CommonScalarFunctionParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2266][CH] Support last_day/next_day

- docs/get-started/Velox.md
Remove the extra command `make -j` because it is already in the script `compile.sh`. In addition, updated the version of spark.
> [VL][DOC] Refine build guide for velox backend

- docs/get-started/Velox.md
> [VL][DOC] Cherry-pick: refine build guide for velox backend

- README.md
- backends-clickhouse/pom.xml
- backends-velox/pom.xml
- docs/developers/NewToGluten.md
- gluten-celeborn/pom.xml
- gluten-core/pom.xml
- gluten-data/pom.xml
- gluten-ut/common/pom.xml
- gluten-ut/pom.xml
- gluten-ut/spark32/pom.xml
- gluten-ut/spark33/pom.xml
- package/pom.xml
- pom.xml
- shims/common/pom.xml
- shims/pom.xml
- shims/spark32/pom.xml
- shims/spark33/pom.xml
- substrait/substrait-spark/pom.xml
- tools/gluten-it/common/pom.xml
- tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/SparkRunModes.java
- tools/gluten-it/package/pom.xml
- tools/gluten-it/pom.xml
Preparing for 1.0 release
Use exist UTs
> [GLUTEN-2274] Preparing Gluten release v1.0.0

- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/WholeStageResultIterator.cc
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [GLUTEN-2306][VL] Set spark session timezone for velox to use

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionHashingExtended.h
- cpp-ch/local-engine/tests/gtest_hash.cpp
> Fix murmurhash3 decimal128 diff issue

- backends-velox/src/main/scala/org/apache/spark/sql/hive/execution/HiveFileFormat.scala
This PR enable the spark sql compression configuration in InsertIntoCommand.
> [GLUTEN-2327][CORE]Fix the  spark sql compression configuration  does not effect in InsertIntoCommand

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
Fix wrong schema when there is no aggregate function
Close #2198.
Fixes: #2198 
> [GLUTEN-2198][CH] Fix wrong schema when there is no aggregate function

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/arrayContains.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/arrayPosition.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2193][CH] Support array_position and fix array_contains

- backends-clickhouse/src/test/java/org/apache/hadoop/mapred/UserDefineTextInputFormat.java
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
> [GLUTEN-2355][CH] Support user-define textInputFormat in HiveTextTransform

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
adjust CH decimal type to Spark decimal type in plus/minus/multiply/divide
(Fixes: \#2270)
> [GLUTEN-2270][CH] fix decimal result errors in tpcds q49,q83,q90

- backends-velox/pom.xml
- backends-velox/src/main/scala/org/apache/spark/sql/hive/execution/HiveFileFormat.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
This pr add some additional vanilla Spark config check if we can safely convert hive write to velox write.
- HiveUtils.CONVERT_METASTORE_PARQUET
- HiveUtils.CONVERT_INSERTING_PARTITIONED_TABLE
Add tests
> [VL] Correct hive write table

- backends-velox/pom.xml
Remove unnecessary change in pom 
Pass CI
> [GLUTEN-2364][FOLLOWUP] Remove unnecessary change

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionStrToMap.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/CommonScalarFunctionParser.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2265][CH] Support `str_to_map`

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2367][CH] Support functions positive/negative

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHValidatorApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxValidator.scala
- cpp/velox/jni/VeloxJniWrapper.cc
- gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendsApiManager.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/ValidatorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/MapExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/QuaternaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala
- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
- gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java
- gluten-data/src/main/java/io/glutenproject/vectorized/PlanEvaluatorJniWrapper.java
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/joins/GlutenBroadcastJoinSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/joins/GlutenBroadcastJoinSuite.scala
Replace doValidate interface with doNativeValidateWithFailureReason.
> [CORE] Unify native validation interface in java side

- cpp/velox/compute/VeloxInitializer.cc
- ep/build-velox/src/get_velox.sh
Depends on https://github.com/oap-project/velox/pull/360
> [GLUTEN-2309][VL]Test velox streaming window

- cpp/velox/compute/VeloxInitializer.cc
Reverts oap-project/gluten#2310
> Revert "[GLUTEN-2309][VL]Test velox streaming window"

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkParseURL.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/ParseURLParser.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/ParseURLParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2264][CH] Support parse_url

- cpp/velox/compute/VeloxInitializer.cc
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
Enable stacktrace for velox user erro
Fixes: #2397
pass GHA
> [GLUTEN-2397] [VL] Enable stacktrace for velox user error

- cpp/core/jni/JniWrapper.cc
- cpp/velox/memory/VeloxMemoryPool.cc
> [VL] cpp refactor: avoid memory leak and setting defaultPoolRoot repeatly

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
- backends-clickhouse/src/test/scala/io/glutenproject/s3/S3AuthSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Common/QueryContext.h
- cpp-ch/local-engine/Common/common.cpp
- cpp-ch/local-engine/Storages/Output/WriteBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/jni/jni_error.h
- cpp-ch/local-engine/local_engine_jni.cpp
> [Gluten-2199][CH] Fix lock issue2

- cpp/velox/compute/VeloxBackend.cc
> [VL] add session conf output for debug

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkParseURL.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/ParseURLParser.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/ParseURLParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2264][CH] Support parse_url 

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/aggregate_function_parser/CountParser.cpp
> [GLUTEN-2448][CH] Fixed types mismatch in `count` with multiple arguments

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/tests/gtest_parquet_write.cpp
- cpp-ch/local-engine/tests/gtest_spark_row.cpp
> [GLUTEN-2466][CH] Allow nullable complex types when writing into parquet/orc

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ClickHouseAppendDataExec.scala
- backends-clickhouse/src/test/resources/substrait-plans/covar_samp-covar_pop-partial-agg-stage.json
- backends-clickhouse/src/test/resources/substrait-plans/tpch-q2-in-one-wholestage.json
- backends-clickhouse/src/test/resources/substrait-plans/tpch-q4-wholestage-2.json
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorHandler.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/substrait/SubstraitParser.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.h
- cpp/velox/tests/data/filter_upper.json
- cpp/velox/tests/data/if_then.json
- docs/developers/SubstraitModifications.md
- gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesBuilder.java
- gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
- gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java
- gluten-core/src/main/java/io/glutenproject/substrait/type/ColumnTypeNode.java
- gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-core/src/main/resources/substrait/proto/substrait/type.proto
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
- gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
Parse partition column value and location from catalog, instead of extract from path.
After this PR, we could support custom partition location, which means the location does not follow hive style.
Fixes: https://github.com/oap-project/gluten/issues/2389
> [GLUTEN-2389][VL] Support more general partition location parsing

- .github/workflows/velox_tpch_bench.yml
- .github/workflows/velox_tpch_merge.yml
- allow users to trigger TPCH benchmark with comment "Benchmark Velox"
- auto trigger TPCH benchmark after each patch merge
> [VL][CI] trigger TPCH benchmark on merge

- .github/workflows/velox_tpch_bench.yml
- .github/workflows/velox_tpch_merge.yml
> [MINOR][VL] fix CI dependencies on curl

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> [GLUTEN-2127] Follow up work for enabling vanilla spark vectorized reader

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230727)

- cpp/velox/CMakeLists.txt
- cpp/velox/benchmarks/QueryBenchmark.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxInitializer.cc
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/memory/VeloxMemoryPool.cc
- cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.h
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
- cpp/velox/substrait/TypeUtils.cc
- cpp/velox/substrait/TypeUtils.h
- cpp/velox/substrait/VeloxSubstraitSignature.cc
- cpp/velox/substrait/VeloxSubstraitSignature.h
- cpp/velox/substrait/VeloxToSubstraitExpr.cc
- cpp/velox/substrait/VeloxToSubstraitType.cc
- cpp/velox/tests/FunctionTest.cc
- cpp/velox/tests/VeloxSubstraitRoundTripTest.cc
- cpp/velox/tests/VeloxSubstraitSignatureTest.cc
- cpp/velox/utils/ConfigExtractor.cc
- cpp/velox/utils/ConfigExtractor.h
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
Integrate Gluten with https://github.com/oap-project/velox/commits/update.
Verified with TPC-H.
> Integrate with Velox update branch

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/tests/gtest_nested_utils.cpp
close issues: \#2463 and \#2459
(Fixes: \#2463)
Notice: it must be merged after https://github.com/Kyligence/ClickHouse/pull/453
> [GLUTEN-2463][CH] Allow nullable tuple column as input in Nested::flatten

- gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
Fix q72 More than one key found from build side relation output error.
> [GLUTEN-1141][FOLLOWUP][VL]Fix q72 duplicate join key

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/BatchIterator.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/execution/NativeFileScanColumnarRDD.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseMetricsUTUtils.scala
- backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorHandler.scala
- gluten-core/src/main/java/io/glutenproject/vectorized/GeneralOutIterator.java
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
- gluten-data/src/main/java/io/glutenproject/vectorized/ColumnarBatchOutIterator.java
- gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java
WholeStageTransformContext's intputAttr and outputAttr are unused.
> [CORE] Minor refactor WholeStageTransformContext

- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/memory/VeloxMemoryPool.cc
This is mainly to provide some changes that will be useful for upcoming Velox upgrading works.
> [VL] Correct some size/capacity configs used for Velox memory management

- tools/gluten-it/common/pom.xml
- tools/gluten-it/common/src/test/java/io/glutenproject/integration/tpc/TpcTest.java
- tools/gluten-it/package/pom.xml
- tools/gluten-it/pom.xml
This is to fix some issues against running gluten-it from IDEs.
> [VL] Adjust scopes of dependencies of gluten-it

- gluten-data/src/main/scala/io/glutenproject/metrics/BatchScanMetricsUpdater.scala
Minor fix for batch scan metrics.
> [Gluten] Minor fix for batch scan metrics

- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
- gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornColumnarBatchSerializer.scala
- gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
- gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornPartitionPusher.scala
- pom.xml
> [VL] Upgrade celeborn to 0.3.0

- backends-velox/src/main/java/io/glutenproject/fs/OnHeapFileSystem.java
- backends-velox/src/test/java/io/glutenproject/fs/OnHeapFileSystemTest.java
> Fix a code format issue

- .github/workflows/velox_be.yml
> [VL] Upgrade celeborn CI to 0.3.0

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseWriteParquetTableSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2508][CH] support function initcap

- .github/workflows/clickhouse_be_trigger.yml
> [GLUTEN-1632] minor, fix Gluten ClickHouse CI not triggered

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230802)

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ContextInitializer.scala
- cpp/CMake/ConfigArrow.cmake
- cpp/CMakeLists.txt
- cpp/core/benchmarks/CompressionBenchmark.cc
- cpp/core/memory/ArrowMemoryPool.cc
- cpp/core/memory/ArrowMemoryPool.h
- cpp/velox/memory/LargeMemoryPool.cc
- cpp/velox/memory/LargeMemoryPool.h
- cpp/velox/utils/VeloxArrowUtils.cc
- cpp/velox/utils/VeloxArrowUtils.h
- dev/builddeps-veloxbe.sh
- ep/build-velox/src/get_velox.sh
1. Remove the arrow compile steps in Gluten.
2. Update the API change between Arrow 12 and Arrow 8 in Gluten.
Existing Uts
> [GLUTEN-2533][VL]Degrade arrow version to 8.0

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/execution/NativeFileScanColumnarRDD.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseWriteParquetTableSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/utils/UTSystemParameters.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorHandler.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/local_engine_jni.cpp
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenParquetWriterInjectsBase.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
Const Columns may cause issues in runtime and output format.
Vanilla Cickhouse insert queries will add an materialize transform to eliminate all const columns before outputing, let's copy this behavior. 
> [GLUTEN-1925][CH] fix const column issues in native parquet writer

- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
The previous change in #2557 is not sufficient, making a follow-up to address it.
Pass GA.
> [GLUTEN-2557][VL][FOLLOWUP] Compatible with CELEBORN-798

- gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
> [CORE] Minor fix GenerateExecTransformer mismatch node name

- cpp/compile.sh
- cpp/velox/compute/VeloxInitializer.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.h
Fix HDFS header to align with Velox.
> Fix HDFS header

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ContextInitializer.scala
- dev/package.sh
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
> [VL] Support Alinux2 OS

- .github/workflows/velox_be.yml
> [VL][FOLLOWUP] Upgrade celeborn CI to 0.3.0

- backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala
- cpp/core/compute/Backend.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
- cpp/core/operators/c2r/ArrowColumnarToRowConverter.h
- cpp/core/operators/c2r/ColumnarToRow.h
- cpp/core/operators/r2c/RowToColumnar.h
- cpp/velox/benchmarks/ColumnarToRowBenchmark.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/operators/serializer/VeloxColumnarToRowConverter.cc
- cpp/velox/operators/serializer/VeloxColumnarToRowConverter.h
- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
- cpp/velox/tests/ColumnarToRowTest.cc
- cpp/velox/tests/VeloxColumnarToRowTest.cc
- cpp/velox/tests/VeloxRowToColumnarTest.cc
- gluten-data/src/main/java/io/glutenproject/vectorized/NativeColumnarToRowJniWrapper.java
- gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala
Clean headers and separate default implementation with Velox's.
> [VL] Minor refactor c2r and r2c cpp codes

- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
Since oap/velox has already include this commit after rebase, let's add it.
Tested in GlutenStringExpressionsSuite
> [VL] Add overlay function support for Velox backend

- docs/get-started/Velox.md
> [VL][DOC] Upgrade celeborn doc to 0.3.0

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/concatWs.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2164][CH] Support function concat_ws

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionArraySort.cpp
- cpp-ch/local-engine/Functions/SparkFunctionArraySort.h
- cpp-ch/local-engine/Parser/scalar_function_parser/sortArray.cpp
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2193][CH] Support sort_array

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/build.yml
> [Core] Minor fix the bug.yml repeated id issue

- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
> [GLUTEN-2600][CH] enhance S3 client caching

- .github/ISSUE_TEMPLATE/bug.yml
> [Core] Minor refactor issue template

- .github/ISSUE_TEMPLATE/bug.yml
> [Core] Fix the alignment problem in bug.yml

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/TypeParser.cpp
- cpp-ch/local-engine/Parser/TypeParser.h
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
- gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
- gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
> [GLUTEN-2490][CH] Extract file schema as a common config for all formats to avoid read schema from HDFS

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDecimalSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.h
Fix decimal precision overflow
test by ut
> [GLUTEN-2591][CH] Fix decimal precision overflow

- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
> [GLUTEN-2652][CH] init common csv settings in global context

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
support lambda function referring root column
UT
> [GLUTEN-2439][VL]Supportlambda function referring root column

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
(Fixes: \#2655)
previously implemented in CH: https://github.com/ClickHouse/ClickHouse/pull/51472
> [GLUTEN-2655][CH] support function substring_index

- gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
No regression issue on enabled UTs with pushed down aggregation.
> [CORE] Minor code refactor for checking pushed down aggregation

- docs/get-started/ClickHouse.md
This pr add document for how to use celeborn in clickhouse backend.
> [doc] add doc for celeborn support to clickhouse backend

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-2474][CH]Fix date convertion for invalid input

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/elt.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2679][CH] Support function elt

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/log1p.cpp
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2639][CH] Fix log1p with input arg <= -1.0

- cpp-ch/local-engine/Operator/ExpandTransform.cpp
> [GLUTEN-1680][CH] Fix ExpandTransform exception

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseFileFormatSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-2711][CH] Fix core dump when filter not has expression 

- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
This is another fix also due to https://github.com/ClickHouse/ClickHouse/pull/53180, it's follow-up of https://github.com/oap-project/gluten/pull/2717
> [CH] Minor fix : Fix build issue due to https://github.com/ClickHouse/ClickHouse/pull/53180

- backends-velox/src/main/scala/io/glutenproject/execution/RowToVeloxColumnarExec.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala
Let c2r/r2c could return early when input iterator is empty and initialize resources later.
> [VL] Minor refactor c2r/r2c java code for return early

- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHNativeMemoryAllocatorManagerImpl.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/BatchIterator.java
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorHandler.scala
- backends-velox/src/main/scala/io/glutenproject/execution/RowToVeloxColumnarExec.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala
- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/TaskContext.cc
- cpp/core/utils/TaskContext.h
- cpp/velox/benchmarks/QueryBenchmark.cc
- gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornColumnarBatchSerializer.scala
- gluten-core/src/main/java/io/glutenproject/vectorized/GeneralOutIterator.java
- gluten-core/src/main/scala/org/apache/spark/util/TaskResource.scala
- gluten-core/src/main/scala/org/apache/spark/util/TaskResources.scala
- gluten-data/src/main/java/io/glutenproject/init/JniTaskContext.scala
- gluten-data/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocatorManagerImpl.java
- gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
- gluten-data/src/main/java/io/glutenproject/vectorized/ColumnarBatchOutIterator.java
- gluten-data/src/main/scala/io/glutenproject/vectorized/CloseableColumnBatchIterator.scala
- gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
- gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala
Add new method `resourceName` for TaskResource to help find which resource may has problem when debug.
> [CORE][VL] Add resource name for TaskResource interface

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHAbstractSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- backends-velox/src/test/scala/io/glutenproject/benchmarks/NativeBenchmarkPlanGenerator.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
PlanJson not init all times. Only load in debug level.
Test by ut.
> [GLUTEN-2626] PlanJson load in debug level in WholeStageTransformer

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHInputPartitionsUtil.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/TransformerHandler.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/utils/InputPartitionsUtil.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/TestFileSourceScanExecTransformer.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/extension/TestFileSourceScanExecTransformer.scala
- shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
Support bucketed read
(Fixes: \#1864)
existing unit tests on bucket read
> [GLUTEN-1864][CORE] feat: Support bucketed read

- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
> [GLUTEN-2699][CORE] Fix a cast issue in DPP when gluten scan is disabled

- gluten-core/src/main/scala/io/glutenproject/expression/MapExpressionTransformer.scala
This is a mirror pr. We found that the program does not print unsupported information correctly when using `GetMapValue`.
unit tests
> [Gluten-CORE][MINNOR] Add the unsupported message for map functions

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetGraceHashJoinSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-1798][CH] Support `grace hash join`

- cpp-ch/CMakeLists.txt
> [CH] Improvement of ch compile script

- backends-clickhouse/pom.xml
- backends-clickhouse/src/test/resources/text-data/field_data_type_not_match/d.txt
- backends-clickhouse/src/test/resources/text-data/field_too_much_few/a.txt
- backends-clickhouse/src/test/resources/text-data/field_too_much_few/b.txt
- backends-clickhouse/src/test/resources/text-data/field_too_much_few/c.txt
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
- docs/get-started/ClickHouse.md
this pr relay on the clickhouse prs: https://github.com/ClickHouse/ClickHouse/pull/51716,  https://github.com/ClickHouse/ClickHouse/pull/51273
(Fixes: \#2180)
1. fix the csv deserialization erros as described in issue #2180, like csv field too many or too few or data type mismatch;
2. remove the unused dependencies (json-serde of openx, as we now can use json-serde of hive to run the tests.)
unit tests
> [GLUTEN-2180][CH]Bug fix hive text format deserialization errors

- cpp/CMakeLists.txt
- cpp/velox/operators/writer/VeloxParquetDatasource.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.h
Enable velox native parquet write after degrade Arrow version to 8.0.
> [GLUTEN-2746][VL] Enable velox native parquet write

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
- cpp-ch/local-engine/local_engine_jni.cpp
- gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
- gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [GLUTEN-2456][CH] Support use push down filter to skip rowgroups in parquet input format reader

- ep/build-clickhouse/src/package.sh
> [GLUTEN-2758][CH] fix gluten package script with adaptive protobuf version

- gluten-core/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/utils/DecimalArithmeticUtil.scala
Fix the result type of decimal arithmetic expression.
> Fix the result type of decimal arithmetic expression

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecHandler.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
(Fixes: [ISSUE-2627](https://github.com/oap-project/gluten/issues/2627))
fixes: https://github.com/oap-project/gluten/issues/2587
manual tests
> [GLUTEN-2627][VL] support map extract

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecHandler.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ArrayExpressionTransformer.scala
Fixes: [ISSUE-2682](https://github.com/oap-project/gluten/issues/2682)
pass ut
> [GLUTEN-2682][VL] support array extract

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/findInset.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-2688][CH] Support function find_in_set

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/arrayIntersect.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
CH arrayIntersect and Spark array_intersect return the same array element but may different permutation, we temporarily ignore it.
UT
> [GLUTEN-2193][CH] Support function array_intersect

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/sequence.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ArrayExpressionTransformer.scala
Fix sequence with null value as argument and move the convert implemention of sequence to function parser of ch backend.
(Fixes: \#2491)
UT
> [GLUTEN-2491][CH] Fix sequence with null value as argument

- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
- cpp/velox/substrait/TypeUtils.h
Fix the validation failure for the Real(FP32)  type column
> [VL] Add support for filter pushdown of float type

- gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [CORE] Minor code refactor for handling native write

- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
Support bucket name contains '.'
(Fixes: #2809)
Test by local ut
> [GLUTEN-2809][CH] Fix s3 read error with 403

- cpp-ch/local-engine/Builder/SerializedPlanBuilder.cpp
- cpp-ch/local-engine/Builder/SerializedPlanBuilder.h
- cpp-ch/local-engine/Functions/SparkFunctionPositionUTF8.cpp
- cpp-ch/local-engine/Operator/PartitionColumnFillingTransform.cpp
- cpp-ch/local-engine/Parser/RelMetric.cpp
- cpp-ch/local-engine/Parser/RelMetric.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/SparkRowToCHColumn.cpp
- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.cpp
- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
Avoid unnecessary copy of temporary variables
(Fixes: \#2833)
using existed sytle
> [GLUTEN-2833] [CH] Avoid unnecessary copy of temporary variables

- cpp-ch/local-engine/Storages/Output/FileWriterWrappers.cpp
> [CH] Add log to print native write info

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230822)

- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.cpp
- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
(Fixes: \#2839)
Other changes: 
- Fix code style (aBcDe -> a_bc_de)
> [GLUTEN-2839][CH] Deduplicate actions in  removenullable step

- cpp/velox/substrait/SubstraitToVeloxPlan.cc
> [VL] Fix fallback caused by filter of array/map column type

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2830][CH] Enable Spark 32 UT

- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHManagedCHReservationListener.java
- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHNativeMemoryAllocators.java
- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHInputPartitionsUtil.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
- backends-clickhouse/src/test/java/org/apache/spark/memory/TestTaskMemoryManagerSuite.java
- cpp/core/jni/JniCommon.h
- cpp/core/jni/JniWrapper.cc
- gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
- gluten-core/src/main/java/io/glutenproject/memory/MemoryUsage.java
- gluten-core/src/main/java/io/glutenproject/memory/MemoryUsageStats.java
- gluten-core/src/main/java/io/glutenproject/memory/memtarget/MemoryTarget.java
- gluten-core/src/main/java/io/glutenproject/memory/memtarget/MemoryTargets.java
- gluten-core/src/main/java/io/glutenproject/memory/memtarget/OverAcquire.java
- gluten-core/src/main/java/io/glutenproject/memory/memtarget/TaskManagedMemoryTarget.java
- gluten-core/src/main/java/io/glutenproject/memory/memtarget/ThrowOnOomMemoryTarget.java
- gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/GlutenMemoryConsumer.java
- gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
- gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkResourceUtil.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkRuleUtil.scala
- gluten-core/src/main/scala/org/apache/spark/util/TaskResources.scala
- gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
- gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ManagedAllocationListener.java
- gluten-data/src/main/java/io/glutenproject/memory/nmm/ManagedReservationListener.java
- gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManagers.java
- gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
The new OOM log message:
```
23/08/24 19:24:08 ERROR ManagedReservationListener: Error reserving memory from target
io.glutenproject.memory.memtarget.ThrowOnOomMemoryTarget$OutOfMemoryException: Not enough spark off-heap execution memory. Acquired: 8388608, granted: 0. Try tweaking config option spark.memory.offHeap.size to get larger space to run this application. 
Current config settings: 
spark.gluten.memory.offHeap.size.in.bytes=1024.0 MiB
spark.gluten.memory.task.offHeap.size.in.bytes=14.2 MiB
Memory consumer stats:
from GlutenMemoryConsumer/BuildSideRelation#BatchSerializer@2d68d411: Current used bytes: 8.0 MiB, peak bytes: 8.0 MiB
from                GlutenMemoryConsumer/WholeStageIterator@218fcda2: Current used bytes: 8.0 MiB, peak bytes: 8.0 MiB
from …
```
> [VL] Enrich Spark task OOM error message

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ContextInitializer.scala
- dev/package.sh
- dev/vcpkg/setup-build-depends.sh
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
Add support for tencentos 3.2 which is widely used in tencent 
manual test with tencentos 3.2
> [VL] Support tencentos 3.2

- cpp-ch/local-engine/Common/QueryContext.cpp
fix thread status destroy on other thread, when use prefer cache shuffle writer
fix #2906 
unit tests
> [GLUTEN-2906] [CH] Fix thread status destroy on other thread

- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [Gluten-2600][CH] fix client cache concurrent issue

- cpp/core/jni/JniCommon.h
- cpp/core/jni/JniWrapper.cc
- gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornPartitionPusher.scala
Reuse celeborn push array
Celeborn CI
> [VL] Reuse celeborn push array

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseFileFormatSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Parser/TypeParser.cpp
- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
Fix when partition key is date, and value is range 1900~1970, join with an error.
(Fixes: #2925)
Test by ut
> [GLUTEN-2925][CH] Fix range partition with date error

- cpp/velox/memory/VeloxMemoryManager.cc
@Yohahaha @ulysses-you @zhouyuan
> [VL] Following #2888, fix a hidden code conflict that fails compilation

- .github/workflows/velox_tpch_bench.yml
- .github/workflows/velox_tpch_merge.yml
Send PR number when trigger performance benchmark
Use exist UTs
> [GLUTEN-2920][CI] Pass PR number when trigger performance benchmark

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseFileFormatSuite.scala
> [GLUTEN-2934][CH] Fix error knownfloatingpointnormalized

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseNativeWriteTableSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-2942][CH] fix inconsistency of native write and non-native read of orc format table  

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDecimalSuite.scala
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
(Fixes: \#2767, #2834)
Test by ut
> [GLUTEN-2767][GLUTEN-2834][CH] Fix negative decimal32 return wrong value

- dev/vcpkg/setup-build-depends.sh
Miss autoconf-archive for tencentos in #2852 which is added by #2148
manual tests with tencentos 3.2
> [VL] install autoconf-archive for tencentos 3.2

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/clickhouse.version
> [GLUTEN-2340][CH] Support nullable complex types in getLeastSupertype

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-2886][CH] Set default join spill settings and improve sort/groupby spill settings

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHStreamReader.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/OnHeapCopyShuffleInputStream.java
- backends-clickhouse/src/main/java/io/glutenproject/vectorized/StorageJoinBuilder.java
- backends-clickhouse/src/main/java/org/apache/spark/storage/CHShuffleReadStreamFactory.java
- backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CHColumnarBatchSerializer.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/joins/ClickHouseBuildSideRelation.scala
- backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHHashBuildBenchmark.scala
- backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHStorageJoinBenchmark.scala
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.h
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- cpp-ch/local-engine/Parser/JoinRelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
- cpp-ch/local-engine/Shuffle/ShuffleReader.h
- cpp-ch/local-engine/local_engine_jni.cpp
- gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/utils/SubstraitUtil.scala
This is follow up of  #2725.  What I  found is that calling java method in c++ thread is quite slow, Let's move such call in jni thread.
(Fixes: \#2723)
Using Existed UT
> [GLUTEN-2723][CH] Improve Broadcast Join performance -- Part 2

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
(Fixes: \#2947)
It is closed by pr: https://github.com/oap-project/gluten/pull/2994
> [GLUTEN-2947][CH] Add uts for issue https://github.com/oap-project/gluten/issues/2947.

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230904)

- ep/build-clickhouse/src/package.sh
Add celeborn package to build script
manual tests
> [CH] Add celeborn package to build script

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHBlockStripes.java
- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.cpp
- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.h
- cpp-ch/local-engine/local_engine_jni.cpp
- shims/common/src/main/scala/org/apache/spark/sql/execution/datasources/BlockStripes.java
> [CH] Fix possible memory leak caused by unintialized variable

- cpp/core/jni/JniCommon.h
> [VL][FOLLOWUP] Reuse celeborn push array

- cpp/core/shuffle/LocalPartitionWriter.cc
> [GLUTEN-2987] Fix SpillInfo out of range

- CONTRIBUTING.md
Introduce some conventions of the community on PR, issue, coding, code review, etc., which can also reduce review cost.
> [GLUTEN-2756] Add a contributing guide

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/gluten/celeborn/CelebornHashBasedCHColumnarShuffleWriter.scala
> [GLUTEN-3041][CH] Add configure for celeborn spill threshold

- cpp/core/CMakeLists.txt
- cpp/core/compute/Backend.h
- cpp/core/jni/JniCommon.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/memory/AllocationListener.cc
- cpp/core/memory/AllocationListener.h
- cpp/core/memory/MemoryAllocator.cc
- cpp/core/memory/MemoryAllocator.h
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/memory/VeloxMemoryManager.h
> [GLUTEN-2974] [VL] Minor refactor for AllocationListener and VeloxMemoryMamanger to non copyable and non assignable

- cpp-ch/local-engine/Storages/Output/BlockStripeSplitter.cpp
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala
> [GLUTEN-3051][CH] Fix core caused by invalid partition column index in native write

- cpp/core/compute/Backend.h
- cpp/core/jni/JniWrapper.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/memory/VeloxMemoryManager.h
> [VL] (Refactor) Using createXXX replace getXXX to indicate creating object

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/gluten/celeborn/CelebornCHPartitionPusher.scala
- cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
- cpp-ch/local-engine/jni/CelebornClient.h
optimize celeborn client, reuse jbyte array
unit tests
> [CH] optimize celeborn client, reuse jbyte array

- cpp/core/compute/Backend.h
- cpp/core/compute/ProtobufUtils.cc
Note: This doesn't fix https://github.com/oap-project/gluten/issues/1727, just to avoid nesting limit error throwing during printing plans in debug build, to make sure the query would not fail by that.
> [VL] Protobuf nesting limit error causes task failure when printing plan to stdout in debug build

- backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHManagedCHReservationListener.java
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [GLUTEN-3019][CH] Add gluten ch config throw if memory exceed

- cpp/velox/compute/VeloxInitializer.cc
- cpp/velox/memory/VeloxMemoryManager.cc
> [VL] Setting FLAGS to avoid creating unnecessary shared leaf pools  

- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
> [GLUTEN-3090][CH] Fix Method get64 is not supported for Nothing 

- cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
(Fixes: \#3102)
Manual test and CI.
> [CH] Fix hangs on CHShuffleSplitterJniWrapper.stop

- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala
> [GLUTEN-2894][CH] Enable output rows metric for native write

- ep/build-velox/src/build_velox.sh
> [GLUTEN-3099][VL] Support building velox on aarch64

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/mapFromArraysUnaligned.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/sequence.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
> [GLUTEN-2492][CH] fix posexplode cannot handle null value as argument 

- cpp/velox/operators/writer/VeloxParquetDatasource.cc
> [GLUTEN-2746][VL]Fix failed ut in parquet write

- pom.xml
> [CELEBORN][FOLLOWUP] Unify the celeborn shuffle manager of velox and ch

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-3105][CH] Fix json output format for integers and denormals

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
- gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
> [GLUTEN-3108][CH] Fix parsing failure when row serde is org.apache.hadoop.hive.serde2.OpenCSVSerde 

- README.md
Add Alibaba name in README.
N/A, only README update
> [Core] Add Alibaba name in README

- README.md
> [DOC] add Baidu in README

- cpp-ch/local-engine/Parser/FilterRelParser.cpp
- cpp-ch/local-engine/Parser/FilterRelParser.h
- cpp-ch/local-engine/Parser/RelParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-3150][CH] Uniform filter rel parsing process

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Functions/CMakeLists.txt
- cpp-ch/local-engine/Functions/SparkFunctionRegexpExtractAll.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230918)

- .github/workflows/velox_be.yml
this is quick fix on Centos7 CI
the pre-built image has some issue if updating some dependencies. this patch bypass the dependency setup stage. 
pass GHA
> [VL][CI] fix centos7 CI

- .github/workflows/velox_be.yml
- tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/Parameterized.java
- tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/TpcRunner.scala
Q67 and Q95 SF30 will be run within 8 threads, 72 partitions, and 3g/5g off-heap memory for each PR.
Failures will be ignored temporarily.
> [VL] Set a GitHub Actions workflow run for TPC-DS Q67/Q95 low memory case

- .github/workflows/clickhouse_be_trigger.yml
Add celeborn path for ch ci
CI
> [CH] Add celeborn path for ch ci

- cpp/core/shuffle/FallbackRangePartitioner.cc
- cpp/core/shuffle/FallbackRangePartitioner.h
- cpp/core/shuffle/Partitioner.cc
- cpp/core/shuffle/Partitioner.h
- cpp/core/shuffle/RoundRobinPartitioner.cc
- cpp/core/shuffle/RoundRobinPartitioner.h
- cpp/core/shuffle/ShuffleWriter.cc
- cpp/core/shuffle/ShuffleWriter.h
- cpp/core/shuffle/SinglePartPartitioner.cc
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
- cpp/velox/utils/Common.h
I proposed this PR to get more detailed information for shuffling writing.
I divided the shuffle writing into several small steps, We can gather the time-consuming for each step after the shuffle writing is completed by setting `VELOX_SHUFFLE_WRITER_LOG_FLAG `.
We can make changes to improve the shuffle writing performance and check the result by this timing info.
> [VL] Log more info for shuffle write

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20230919)

- gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala
In range partitioning we create a batch and offloaded as pidBatch, but no place to close it.
Add batchHolder empty check in VeloxExecutionCtx dtor will find this issue.
> [VL] Close pidBatch after composed in range partitioning

- cpp/core/compute/ExecutionCtx.h
- cpp/core/compute/ResultIterator.cc
- cpp/core/compute/ResultIterator.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/operators/r2c/RowToColumnar.h
- cpp/core/utils/metrics.h
- cpp/velox/compute/VeloxExecutionCtx.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/operators/plannodes/RowVectorStream.h
- cpp/velox/substrait/VeloxToSubstraitPlan.cc
- cpp/velox/tests/ExecutionCtxTest.cc
It seems to be a better way to use `enum`, it makes adding a new metric item easier and the code is also simpler.
> [VL] Refactor getMetrics to decrease metrics related redundant code

- backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
Decimal sum and avg have the meaning of overflow when the child field is null, and gluten's row_constructor_with_null cannot be used.
SPARK-28067: Aggregate sum should not return wrong results for decimal overflow
SPARK-35955: Aggregate avg should not return wrong results for decimal overflow
> [GLUTEN-2961][VL][CORE] Decimal sum avg use row_constructor

- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
> [GLUTEN-3226][CH] Use midpoint offset to select rowgroups

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/decode.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/encode.cpp
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-3190][CH] Support expr decode/encode

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-3124][CH] fix explode inconsistency when input is null 

- gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManagers.java
- gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
Remove NativeMemoryManager#tmpInstance usage check, make it more flexible, caller should know why use this method clearly.
> [CORE] Remove usage limit of NativeMemoryManager#tmpInstance

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-1349][CH] Support convert 'NaN' to int

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SortRelParser.cpp
> [GLUTEN-3195][CH] Drop const sort fields

- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
Enable agg prefetch, which can be usefull in single thread execution.
(Fixes: \#3250)
UT
> [CH] Enable agg prefetch

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.h
Fixes: #3173 , #3104
unit tests
> [GLUTEN-3173][CH]fixed issues about get_json_object

- tools/gluten-it/pom.xml
> [VL] Address dependency alert 37

- gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedCHColumnarShuffleWriter.scala
- gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
- gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedVeloxColumnarShuffleWriter.scala
Extract the common parts of these two celeborn shuffle writers into the common module.
CI
> [CELEBORN] Refactor celeborn velox and clickhouse shuffle writer

- cpp/core/memory/AllocationListener.cc
- cpp/core/shuffle/RoundRobinPartitioner.h
- cpp/core/shuffle/rss/CelebornPartitionWriter.cc
- cpp/core/tests/CMakeLists.txt
- cpp/core/tests/RoundRobinPartitionerTest.cc
> [CORE] Fix format and add UnitTest of class RoundRobinPartitioner

- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
this patch fixes GenerateExec with ArrayType
(Fixes: #2943)
existing UT
> [GLUTEN-2943][VL] follow up to cleanup on `GenerateExec`

- docs/get-started/Velox.md
update dependency libraries deploy method to readme
> [VL] Update dependency libraries deploy method

- gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
OAP/Velox will skip sort for window, so we should always make sure the ordering requirements is satisfied to avoid potential issue.
PASS CI
> [VL] Window transformer should require child ordering

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetIOSuite.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetIOSuite.scala
Ignore several tests on ORC and parquet write codec.
Locally tested.
> [VL][UT] Ignore several tests

- gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
Fix typo in `ExpandExecTransformer`
No
> [GLUTEN-3334]Fix typo in `ExpandExecTransformer`

- cpp/core/shuffle/Utils.h
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
Reverts oap-project/gluten#3318
> [VL] Revert "[VL] Refine the allocation and update for shuffle split validity buffer"

- README.md
> [DOC] Add Microsoft in README

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/divide.cpp
> [GLUTEN-3287][CH] Fix diff when divide zero

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-3216][CH] Support struct type in hash partitioning and aggregation

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-3135][CH]Bug fix to_date can not convert timestamp with timezone

- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxBlockStripes.java
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
- cpp/core/compute/ExecutionCtx.h
- cpp/core/jni/JniWrapper.cc
- cpp/velox/compute/VeloxExecutionCtx.cc
- cpp/velox/compute/VeloxExecutionCtx.h
- gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala
- gluten-data/src/main/java/io/glutenproject/datasource/velox/DatasourceJniWrapper.java
- shims/common/src/main/scala/org/apache/spark/sql/execution/datasources/BlockStripes.java
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
This PR only supports static dynamic partition writes. Additionally, we have removed the sort operator before writing, as it is unnecessary for static partition writes.
existing uts
> [GLUTEN-3075][VL]FEAT: Support static partition write in velox backend

- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
- cpp-ch/local-engine/Shuffle/PartitionWriter.h
> [GLUTEN-3366][CH]Bug fix multi-thread unsafe problem for celeborn shuffle write

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
> [GLUTEN-3373][CH] Support uuid function

- gluten-ut/common/src/test/scala/io/glutenproject/utils/BackendTestSettings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
> [VL] Branch upstream_velox: Untangle test case filter code

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHFormatWriterInjects.scala
> [GLUTEN-3405][CH]tolerate empty blocks when native writing

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
> [GLUTEN-3134][CH]Bug fix left join field not match

- cpp-ch/local-engine/Operator/ExpandTransform.cpp
- cpp-ch/local-engine/Operator/ExpandTransorm.h
> [GLUTEN-3417][CH] Reduce memory consumption in `Expand` operator

- gluten-core/src/main/scala/io/glutenproject/execution/CoalesceExecTransformer.scala
This operator should be removed out of WholeStageTransform
(Fixes: #3371)
existing UT
> [GLUTEN-3371][CORE] fix CoalesceExec

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ListenerApiImpl.scala
- cpp/CMakeLists.txt
This pr is a followup of https://github.com/oap-project/gluten/pull/3341 to fix the issue on macOS.
manually test
> [GLUTEN-2961][VL][FOLLOWUP] Fix issue on macOS

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-3431][CH] Fix convertion from  `Inf` to `int`

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-3446][CH] Fix unprecise issue when parse float from string

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-3489][CH] Fix exception when in-filter contains null value

- gluten-data/src/main/java/io/glutenproject/init/NativeBackendInitializer.java
> Fix a typo in error message of native backend initialization

- cpp/velox/CMakeLists.txt
- ep/build-velox/src/get_velox.sh
The `external/duckdb/tpch/dbgen/libdbgen.a` needs to be changed to align with this static lib's change in upstream velox.
> [VL] Fix compile issue after rebasing velox

- cpp/velox/compute/VeloxBackend.cc
These codes already be invoked in velox `HiveConnectorFactory::initialize()` https://github.com/oap-project/velox/blob/b8fc63ec35f049a49e417ba4b0845c2b1e367748/velox/connectors/hive/HiveConnector.cpp#L138-L160
> [VL] Remove unnecessary registerFileSystem and registerReader

- cpp/velox/benchmarks/common/BenchmarkUtils.h
- cpp/velox/benchmarks/common/FileReaderIterator.h
- ep/build-velox/src/get_velox.sh
Drops commit https://github.com/oap-project/velox/commit/aaeab8db057d3a6b35a083eeeb39abf5966fa3a6
> [VL] Fix Arrow ABI include

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- ep/build-velox/src/get_velox.sh
Removes https://github.com/oap-project/velox/commit/5d8d0377906030d1510e3ed17ffce4e1c8cfc72c by adding the same logic in Gluten.
under test
> [VL] Remove the usage of isUnquotedPathCharacter in Velox

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/elementAt.cpp
> [GLUTEN-3412][CH]Bug fix element_at 1st argument is map type

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseNativeWriteTableSuite.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [GLUTEN-3383][CH] Respect spark config spark.sql.orc.compression.codec for CH backend

- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
> [GLUTEN-3509][CH]Fix partition lock problems in shuffle write

- cpp/velox/CMakeLists.txt
- cpp/velox/tests/CMakeLists.txt
Fixes https://github.com/oap-project/gluten/issues/3531
> [GLUTEN-3531][VL] Build: Undefined reference while linking velox_plan_conversion_test in debug build

- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
(Fixes: \#3297)
related pr: https://github.com/ClickHouse/ClickHouse/pull/55330
> [GLUTEN-3297][CH] Refactor filter push down framework in gluten, support orc FPD and reuse parquet FPD in CH.

- cpp/velox/CMakeLists.txt
- ep/build-velox/src/build_velox.sh
See build issue https://github.com/oap-project/gluten/issues/3538
> [GLUTEN-3538][VL] Build: Unregistered hive connector factory in debug build

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxStringFunctionsSuite.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
Ported from https://github.com/oap-project/gluten/pull/2271. Contributed by @myandpr.
> [VL] Support left Spark function

- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
The previous implementation doesn't actually take effect.
Added UT.
> [VL] Hot-fix shuffle writer EvictGuard

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20231103)

- backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
Implement methods needsPreProjection and needsPostProjection in HashAggregateExecBaseTransformer in a more elegant and concise manner.
CI
> [CORE] Optimize some methods in agg transformer

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
> [GLUTEN-3521][CH] Fix substring start index can not be 0

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-3451][CH]Bug fix to_date can not convert 1970-01-01

- cpp/CMake/BuildGTest.cmake
- cpp/CMake/BuildGflags.cmake
- cpp/CMake/BuildGlog.cmake
- cpp/CMake/BuildGoogleBenchmark.cmake
- cpp/CMake/ResolveDependency.cmake
- cpp/CMake/Simdjson.cmake
- cpp/CMakeLists.txt
Specify deps download url by `export GLUTEN_XXX_URL=path` if needed.
> [VL] Support custom cmake deps download url

- gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
Previous bhj + exchange joint validation may not work because of bugs. The patch is to fix the broken logic.
> [VL] Fix a bug that may break bhj + exchange validation in a corner case

- .github/workflows/ch_code_style.yml
- .github/workflows/clickhouse_be_trigger.yml
- .github/workflows/code_style.yml
- .github/workflows/velox_be.yml
- .github/workflows/velox_tpch_bench.yml
- .github/workflows/velox_tpch_merge.yml
Bump checkout action to V4
pass GHA
> [CI] bump checkout action to v4

- docs/developers/UsingJemallocWithCH.md
> Add doc using jemalloc with ch backend.

- gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
Fix nativeBufferSize assign bug
(Fixes: \#3716)
> Fix nativeBufferSize assign bug

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
There are some randomly failed ( result not match ) when running ut for PR #3537.
> [HOTFIX][CH] Fix randomly failed ut for PR#3537

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/expression/CHExpressionTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/StringExpressionTransformer.scala
As CH has some limitations for supporting translate function, but velox not, this PR proposes to separate the implementations.
Existing spark UTs.
> [GLUTEN-1902] Separate the implementations for TranslateTransformer

- gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
> [CORE] Remove redundant case match for HiveTableScanExecTransformer

- cpp-ch/local-engine/CMakeLists.txt
(Fixes: \#3745)
Before:
After:
> [CH] Reduce libch.so size

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-3692][CH]Fix count no result on empty table

- cpp/velox/compute/VeloxBackend.cc
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
> [GLUTEN-3739][VL] Add config to disable velox file handle cache

- gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornPartitionPusher.scala
> [CELEBORN] Fix push small data

- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
Fix https://github.com/oap-project/gluten/issues/3702
This PR adds a configuration option to Velox backend, allowing users to choose between window types (sort or streaming). This modification resolves the OOM issue associated with streaming windows.
Adding new unit test.
> [GLUTEN-3702] [VL] Add config to specify the window type in velox backend

- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameRangeSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameRangeSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDataFrameRangeSuite.scala
remove flaky unit tests, need to be fixed as next
(Fixes: #3796)
pass GHA
> [GLUTEN-3796][VL] ban flaky unit tests

- cpp/velox/benchmarks/ParquetWriteBenchmark.cc
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.h
Support s3 write for Velox backend
> [VL] Support s3 write

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/proto/CMakeLists.txt
> [GLUTEN-1632][Gluten-3769][CH]Daily Update Clickhouse Version (20231122)

- tools/workload/tpcds/run_tpcds/run_tpcds.sh
- tools/workload/tpcds/run_tpcds/tpcds_parquet.scala
Add tpcds benchmarking scripts and refine the relevant scala file.
> [VL] Add tpcds benchmarking scripts

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
Count native iterator build duration in common code path.
GHA
> [CORE] Count native iterator build duration into pipeline metric

- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
> [GLUTEN-3826][CH] Fixed data lost in shuffle

- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.h
Previously, is_null filter was separated into remaining filter. With this PR, it can be pushed down into subfield filter.
Before:
> TableScan[table: hive_table, range filters: [(ss_item_sk, Filter(IsNotNull, deterministic, null not allowed))], remaining filter: (isnull("ss_addr_sk"))] -> n0_0:INTEGER, n0_1:INTEGER, n0_2:DECIMAL(7,2), n0_3:INTEGER
After:
> TableScan[table: hive_table, range filters: [(ss_item_sk, Filter(IsNotNull, deterministic, null not allowed)), (ss_store_sk, Filter(IsNull, deterministic, null allowed))]] -> n2_0:INTEGER, n2_1:INTEGER, n2_2:DECIMAL(7, 2), n2_3:INTEGER
Verified with TPC-DS q76.
> [VL] Support IsNull filter pushdown

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-data/src/main/java/io/glutenproject/metrics/Metrics.java
- gluten-data/src/main/java/io/glutenproject/metrics/OperatorMetrics.java
- gluten-data/src/main/scala/io/glutenproject/metrics/BatchScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/FileSourceScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/HiveTableScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
> [GLUTTEN-3851][VL] Add remaining filter time metric

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
> [GLUTEN-3879][CH] salt 1% of TPCH-1 data to NULL instead of 10%

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Operator/DefaultHashAggregateResult.cpp
- cpp-ch/local-engine/Operator/DefaultHashAggregateResult.h
- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-3865][CH] Refactor aggregating without keys

- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-3824][CH]Bug fix hdfs path contains space

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Functions/FunctionsBloomFilter.h
- cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
- cpp-ch/local-engine/Parser/RelParser.cpp
- cpp-ch/local-engine/Parser/TypeParser.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20231201)

- gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
Fix SparkShimLoader not found.
Pass CI
> [GLUTEN-3917][FOLLOWUP] Add back SparkShimLoader import

- .github/workflows/stale.yml
This is a follow-up to https://github.com/oap-project/gluten/pull/3888
> [VL] Fix syntax error in stale.yml

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/trunc.cpp
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-3948][CH] Fix exception and diff of trunc function

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/jni/VeloxJniWrapper.cc
Dependency https://github.com/zhztheplayer/velox/tree/wip-rebase-231211
> [VL] Daily Update Velox Version (20231211)

- cpp/velox/benchmarks/common/BenchmarkUtils.cc
Fix a CI error introduced by #3996
> [VL] Following #3996, fix CI error "Runtime factory already registered"

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/metrics/HashAggregateMetricsUpdater.scala
- backends-clickhouse/src/main/scala/io/glutenproject/metrics/InputIteratorMetricsUpdater.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
Update InputIteratorTransformer metrics for the CH backend.
Close #4002.
(Fixes: #4002)
> [GLUTEN-4002][CH] Update InputIteratorTransformer metrics

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-data/src/main/java/io/glutenproject/metrics/Metrics.java
- gluten-data/src/main/java/io/glutenproject/metrics/OperatorMetrics.java
- gluten-data/src/main/scala/io/glutenproject/metrics/BatchScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/FileSourceScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/HiveTableScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
add io wait time metric in scan
> [VL] add io wait time metric in scan

- .github/workflows/velox_be.yml
- dev/builddeps-veloxbe.sh
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
- ep/build-velox/src/modify_velox.patch
Manual test & CI verification.
> [VL] Fix git version conflict issue in build script

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
UT change, these test cases should be fixed by https://github.com/oap-project/gluten/pull/3842
> [VL] Enable repartition ut 24940, 40407 and 40660

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
- gluten-delta/src/test/scala/io/glutenproject/execution/VeloxTPCHDeltaSuite.scala
- gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxTPCHIcebergSuite.scala
All current TPCH tests are on non-partitioned tables. Some issues only become apparent with partitioned tables, therefore it is necessary to add test cases for partitioned tables.
Add `VeloxPartitionedTableTPCHSuite`.
> [VL] Add VeloxPartitionedTableTPCHSuite test case

- cpp-ch/local-engine/Operator/ExpandStep.cpp
- cpp-ch/local-engine/Parser/ExpandRelParser.cpp
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2805][CH] Fix ExpandStep duplicated col name

- gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala
Wrapper reason with Option instead of Some to avoid reason is null
Close #4055 
CI
> [GLUTEN-4055][CORE] Wrapper reason with Option instead of Some to avoid reason is null

- gluten-core/src/main/scala/io/glutenproject/extension/CollapseProjectExecTransformer.scala
Fix wrong plan if failed to collapse project
obvious bug
> [CORE] Fix wrong plan if failed to collapse project

- gluten-core/src/main/scala/io/glutenproject/execution/ScanTransformerFactory.scala
- gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
- gluten-delta/src/main/scala/io/glutenproject/execution/DeltaScanTransformer.scala
- gluten-delta/src/main/scala/io/glutenproject/execution/DeltaScanTransformerProvider.scala
- gluten-delta/src/main/scala/io/glutenproject/extension/DeltaRewriteTransformerRules.scala
- gluten-delta/src/test/scala/io/glutenproject/execution/VeloxDeltaSuite.scala
> [Delta] fix and refine Delta UTs

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/GlutenSignalHandler.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20231219)

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/utils/ConfigExtractor.cc
- cpp/velox/utils/ConfigExtractor.h
Use velox Config to extract values for `QueryContextConf`
CI/CD
> [VL]Use velox Config to extract QueryContextConf

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
> [GLUTEN-4092][CH] Disable streaming aggregating before bugs fixed

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-data/src/main/java/io/glutenproject/metrics/Metrics.java
- gluten-data/src/main/java/io/glutenproject/metrics/OperatorMetrics.java
- gluten-data/src/main/scala/io/glutenproject/metrics/BatchScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/FileSourceScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/HiveTableScanMetricsUpdater.scala
- gluten-data/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
> [GLUTEN-4125][VL] add scan preload splits metric

- .github/workflows/velox_be.yml
- gluten-delta/src/test/scala/io/glutenproject/execution/VeloxDeltaSuite.scala
- pom.xml
Add time travel and partition filter UT for delta and enable in CI
UT
> [VL][Delta]add more UT for delta lake and enable in CI

- cpp/velox/CMakeLists.txt
- ep/build-velox/src/get_velox.sh
clean up on aws_sdk install script to use the help function from Velox
pass jenkins
> [MINOR][VL] clean up aws sdk install script

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
> [GLUTEN-4032][CH] Fix shuffle read core after union

- .github/workflows/velox_be.yml
split the ubuntu 2204 job
pass GHA
> [VL] CI: split ubuntu 2204 job to speed up 

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.cc
- cpp/velox/utils/ConfigExtractor.cc
- cpp/velox/utils/ConfigExtractor.h
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
This PR aims to initialize s3 filesystem with hive configuration in native write. With configuration, s3 client can visit all distributed storage systems that support s3 protocol.
(Fixes: \#4121)
manual tests
> [GLUTEN-4121][VL] Initialize s3 filesystem with hive configuration in native write

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ListenerApiImpl.scala
- backends-velox/src/main/scala/io/glutenproject/utils/SharedLibraryLoaderDebian11.scala
- dev/package.sh
- dev/vcpkg/setup-build-depends.sh
Adds Support for building Gluten in Debian 11
(Fixes: #4141)
Manually built and tested in a Debian 11 environment
> [GLUTEN-4141][VL] Support Gluten Build in Debian 11

- gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
Define gluten ui enabled key in GlutenConfig
minor fix
> [MINOR] Define gluten ui enabled key in GlutenConfig

- cpp/velox/CMakeLists.txt
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- ep/build-velox/src/get_velox.sh
```
c5bcc33e9 (upstream/main) Improve the capacity management in memory arbitrator (#8110)
a1e5c346d Add support for multiple S3FileSystems (#7388)
50187434e Add write file create config to hive config (#8133)
9d7d4e8a5 Allow marking an argument as constant in the simple function API (#7901)
8948b9e94 Add TypeSignature Parser using Flex and Bison (#7590)
b93dd31c9 Add Status class (#8084)
e87462633 Register abfs filesystem during Hive Connector registration (#8144)
32e21c9f8 Fix reading MAP_KEY_VALUE Parquet SchemaElement (#7966)
```
> [VL] Daily Update Velox Version (2023-12-25)

- .github/workflows/velox_be.yml
- .github/workflows/velox_tpch_bench.yml
- .github/workflows/velox_tpch_merge.yml
Change proxy to see if it helps for CI stability. Especially `centos7-test`.
> [VL] Change proxy for CI network failures
