gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

UT change. Complex type support for map functions is added in https://github.com/facebookincubator/velox/pull/7560.
```
-- Project[expressions: (n1_1:MAP<INTEGER,ROW<b:INTEGER,a:VARCHAR>>, map(1,row_constructor(try_cast "n0_0" as INTEGER,"a")))] -> n1_1:MAP<INTEGER,ROW<b:INTEGER,a:VARCHAR>>
-- ValueStream[] -> n0_0:BIGINT
```

[VL] enable test 'as map of case class - reorder fields by name'

---

cpp/velox/substrait/SubstraitParser.cc

[GLUTEN-4044] [VL] Pass asLowerCase for complex types parsing

---

gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarBatchSerializer.scala

[GLUTEN-4036][CH] Lazy intialize the `CHStreamReader` in shuffle read, avoid OOM

---

cpp/velox/compute/VeloxBackend.cc
docs/get-started/VeloxS3.md
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This PR add new configuration `spark.gluten.velox.awsSdkLogLevel` to set AWS C++ SDK Log Level in gluten.
(Fixes: \#4018)
manual tests

[GLUTEN-4018][VL] set AWS C++ SDK Log Level in gluten to avoid recompile velox

---

gluten-ui/src/main/scala/org/apache/spark/sql/execution/ui/GlutenAllExecutionsPage.scala

`Gluten Build Information` is not very important, we can collapse it by default.
before:
after:

[UI] Collapse the collapse table arrow of gluten build information

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc

After my tests, I have found that the Velox backend does support the explode function for Literal inputs of both array and map types. We can lift the restrictions on validation.
Add a test case in `TestOperator`.

[VL] Explode support Literal array and map

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ShuffledColumnarBatchRDD.scala
gluten-core/src/main/scala/org/apache/spark/sql/metric/SQLColumnarShuffleMetricsReporter.scala

As discussed in https://github.com/oap-project/gluten/issues/3799#issuecomment-1822832054, the current shuffle records metirc shows read batches.
This PR fixes `records read` metric for columnar shuffle and adds a new `batches read` metric.
Fixes: #3799
After this pr (tpcds q1.sql):

[GLUTEN-3799][CORE] Fix records read metric for columnar shuffle

---

gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala

Disable both spark ui and gluten ui in `GlutenSQLTestsBaseTrait`
Close #4053 
CI

[GLUTEN-4053][TEST] Disable both spark ui and gluten ui for running sql test

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/memory/VeloxMemoryManager.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This will fix some core dump issues in the case of turning on split preloading, and to query for remote data source like S3 or remote HDFS cluster.

[VL] Increase async wait time to 30s when stopping tasks

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-iceberg/src/main/scala/io/glutenproject/execution/IcebergScanTransformer.scala
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/TypeUtil.scala
gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxTPCHIcebergSuite.scala

Velox support specifying `partitionColumns` in the split info, which improves efficiency when reading partition columns as there's no need to read from the parquet file.

[GLUTEN-3378][VL] Iceberg support set partition columns in split info

---

cpp/velox/compute/VeloxBackend.cc

```
23/12/17 20:54:26 WARN TaskSetManager: Lost task 0.1 in stage 32.0 (TID 11949) (sr270 executor 10): io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxUserError
Error Code: UNSUPPORTED
Reason: Mutable config cannot return unprotected reference to values.
Context: Split [Hive: s3a://tpcds/t_tpcds_part_1_stringdate/store/part-00000-3502e042-fa34-42ed-bf8e-cb5f60cfebf0-c000.snappy.parquet 0 - 9653] Task Gluten_Stage_32_TID_11949
Top-Level Context: Same as context.
Function: values
File: ../.././velox/core/Config.h
Line: 114
Stack trace:
```
This might be related to https://github.com/facebookincubator/velox/pull/8083

[VL] Error "Mutable config cannot return unprotected reference to values" when reading from S3

---

.gitignore

As the .DS_Store files (DS stands for Desktop Services) are automatically generated in macOS.
Following the practice of other open source communities(etc. Apache Spark), this should be added to the gitIgnore file
Close: #4097
Local Test

[GLUTEN-4097][INFRA] Add .DS_Store into gitIgnore

---

cpp/velox/substrait/SubstraitParser.cc

`collect_set` is a agg func in Spark, `array_distinct` is a array func not agg func.
So we can't simply use array_distinct instead of collect_set.
Close: #4100 
CI

[GLUTEN-4100][VL] Should not simply apply `collect_set` to `array_distinct`

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxColumnarCacheSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpandFallbackPolicy.scala

Since https://github.com/apache/spark/pull/43484 Spark supports cache columnar batch, then outputsColumnar of AQE can be true. It breaks the assumption that the output is always row-based. This pr makes fallback policy compaible with this behavior.
add test

[CORE] Fix miss RowToColumnar with columnar table cache in AQE

---

shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Mark SplitPreloadPerDriver conf as dynamic config, then it can be passed down to native in `getNativeSessionConf`. Now this config is consumed in [getQueryContextConf](https://github.com/oap-project/gluten/blob/main/cpp/velox/compute/WholeStageResultIterator.cc#L404).

[VL] Mark SplitPreloadPerDriver conf as dynamic config

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ListenerApiImpl.scala

`ListenerApiImpl#initialize` should not return early when libPath is empty.

[VL] Avoid early return when spark.gluten.sql.columnar.libpath is not blank

---

cpp/velox/compute/VeloxBackend.cc

[GLUTEN-4106][VL] Initialize velox global memory manager

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

"SPARK-36797: Union should resolve nested columns as top-level columns"
"SPARK-34165: Add count_distinct to summary"
These two UT should be fixed before by https://github.com/oap-project/gluten/pull/1676 and https://github.com/facebookincubator/velox/pull/7560 .

[VL] enable spark ut 36797, 34165

---

dev/vcpkg/vcpkg.json
ep/build-velox/src/get_velox.sh

Current aws-sdk-cpp version(1.11.4) in static build has [deadlock](https://github.com/microsoft/vcpkg/issues/31090) and [memory [](leak](https://github.com/aws/aws-sdk-cpp/issues/2331)) issues, so update to 1.11.169.
CI/CD

[VL] update aws-sdk-cpp version to 1.11.169

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-iceberg/src/main/scala/io/glutenproject/execution/IcebergScanTransformer.scala

Remove the override method that is consistent with the parent to keep code clean
1. As unSupport `doExecuteColumnar` methods, let SparkPlan throw exception to keep output same
Close #4060
CI

[GLUTEN-4060][MINOR] Remove the override method that is consistent with the parent

---

cpp/velox/operators/writer/VeloxParquetDatasource.cc
cpp/velox/operators/writer/VeloxParquetDatasource.h

This PR aims to support other object store server scheme in native write.
ref: https://facebookincubator.github.io/velox/develop/connectors.html#storage-adapters
(Fixes: \#4116)
manual tests

[GLUTEN-4116][VL] Support other object store server scheme in native write

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/TransformerApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
gluten-core/src/main/java/io/glutenproject/substrait/rel/ExtensionTableNode.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/JoinUtils.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/python/EvalPythonExecTransformer.scala

Use `BackendsApiManager.getTransformerApiInstance.packPBMessage` instead of `Any.pack` directly.
(Fixes: \#4105)

[GLUTEN-4105][VL] Fix parse substrait plan to json plan error when validation

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

TransformPreOverrides.replaceWithTransformerPlan only tranform ShuffleExchangeExec, which is a case class, meaning I can't extend it.
This PR changes it to support ShuffleExchangeLike.
Partially fix the #3942
Existing tests

[GLUTEN-3942][CORE]fix: Change columnar overrides to accept ShuffleExchangeLike

---

cpp/velox/compute/WholeStageResultIterator.cc

Although the metrics of the omitted filter are useless, it still needs to be initialized as 0. Otherwise, incorrect metrics information will be displayed in the UI.
N/A

[VL] Fix corrupted metrics data in the filter transformer

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/metrics/GenerateMetricsUpdater.scala
backends-clickhouse/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala

[GLUTEN-4012][CH] Add metrics for GenerateExecTransformer

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDecimalSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetColumnarShuffleSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
cpp-ch/local-engine/Parser/TypeParser.cpp
cpp-ch/local-engine/Rewriter/ExpressionRewriter.h
gluten-core/src/main/scala/io/glutenproject/extension/CommonSubexpressionEliminateRule.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

(Fixes: \#4000) 
Background: in spark, CSE(common subexpression eliminate) is implemented based on codegen instead of logical plan, which makes it impossible for gluten to utilize spark built-in CSE optimization, whether the backend is CH or Velox. So we need to implement CSE based on spark logical plan. 
Implementation: for logical operators like project/sort/aggregate/window, if it contains common subexpressions, firstly a pre-project operator is generated as current operator's child to evaluate the common subexpressions. Then expressions in current operator need to be rewritten to replace common subexprs to attributes refering to pre-project operator's output.   
Notice that not every common subexpressions should be extract into pre-project operator.
- Common subexpressions which …

[GLUTEN-4000][CORE] Apply Basic Common Subexpression Elimination for Spark Logical Plan

---

ep/build-velox/src/get_velox.sh

No updates yet from Velox upstream.
Just to test targeting to OAP Velox's tag rather than branch in `get_velox.sh`.
https://github.com/oap-project/velox/tree/231226

[VL] Daily Update Velox Version (2023-12-26) 

---

cpp/velox/CMakeLists.txt
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/utils/HdfsUtils.cc
cpp/velox/utils/HdfsUtils.h

`updateHdfsTokens` may lead to race condition since `spark.gluten.ugi.tokens` / `spark.gluten.ugi.username` are both resettable in Spark session while Velox `hdfsSetDefautUserName` and `hdfsSetTokenForDefaultUser` are global static API.
The patch adds a check to prevent user from resetting the two options in the same session.
Also, we will call Velox's relevant APIs mentioned above only once in the same session after the patch. This will fix the severe performance issue #4182.
Related to https://github.com/oap-project/gluten/pull/1706

[GLUTEN-4182][VL] Disallow resetting HDFS client credential to fix performance issue / to avoid race condition

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala

Before
```
(6) Scan parquet xxx: Not supported file format or complex type for scan: ParquetReadFormat
```
After
```
(1) Scan parquet xxx: Found unsupported data type in ParquetReadFormat: StructType as element in ArrayType.
```

[VL] Refine fallback msg in scan type validation

---

gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This pr removes the unused config `spark.gluten.memory.conservative.offHeap.size.in.bytes` and related code to make code clear.
PASS CI

[CORE] Remove conservativeOffHeapSize config

---

cpp/velox/operators/writer/VeloxParquetDatasource.cc

The WriteFileSink is not the API Velox supposed to expose, we need to initialize local&hdfs file write sink with FileSink::create function.
(Fixes: \#4151)
Original unit test in GA.

[GLUTEN-4151][VL] initialize local&hdfs file write sink with FileSink::create function

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala

An exception occurred when I disabled broadcasthashjoin，I expect it to work fine after I fallback broadcasthashjoin and broadcastExchange. here's how to make it happen, run tpcds q31 with the following configuration
--conf spark.gluten.sql.columnar.broadcastJoin=false
--conf spark.gluten.sql.columnar.broadcastExchange=false
```bash
Caused by: java.lang.ClassCastException: org.apache.spark.sql.execution.joins.LongHashedRelation cannot be cast to org.apache.spark.sql.execution.joins.BuildSideRelation
at org.apache.spark.sql.execution.ColumnarSubqueryBroadcastExec.$anonfun$relationFuture$3(ColumnarSubqueryBroadcastExec.scala:89)
at io.glutenproject.utils.Arm$.withResource(Arm.scala:25)
at io.glutenproject.metrics.GlutenTimeMetric$.millis(GlutenTimeMetric.scala:37)
at …
```

[GLUTEN-4160][CORE] Fix ClassCastException occurred when fallback broadcast join and broadcast exchange

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarWriteFilesExec.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetDataTypeValidationSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
docs/developers/SubstraitModifications.md
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/WriteRelNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/WriteFilesExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-ut/common/pom.xml
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenSQLQuerySuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala

Since the introduction of the `WriteFilesExec` operator in Spark 3.4 to facilitate write operations ([SPARK-41708](https://issues.apache.org/jira/browse/SPARK-41708)), we can now utilize this operator to enable native Parquet write. This PR introduces the `WriteFilesExecTransformer` to delegate the process to the Velox `TableWriteNode`, and `ColumnarWriteFilesExec` is added to implement the `doExecuteWrite()` method by converting `RDD[ColumnarBatch]` to `RDD[WriterCommitMessage]`。
Due to the differences between vanilla Spark and Velox, this PR has dependencies on the following three upstream Velox PRs:
https://github.com/facebookincubator/velox/pull/8089
https://github.com/facebookincubator/velox/pull/8090
https://github.com/facebookincubator/velox/pull/8091
Limitations and failed unit …

[GLUTEN-3547][CORE] [VL] Add native parquet writer in spark 3.4

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxColumnarCacheSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxHashJoinSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxOrcDataTypeValidationSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetDataTypeValidationSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-delta/src/test/scala/io/glutenproject/execution/VeloxTPCHDeltaSuite.scala
gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxTPCHIcebergSuite.scala

In the `WholeStageTransformerSuite`, the variable names `TPCHTable` and `TPCHTables` are very confusing and need to be renamed. Additionally, if a class that inherits from `WholeStageTransformerSuite` overrides the `createTPCHNotNullTables` and `afterAll` methods, there is no need to construct `TPCHTableDataFrames` if they don't require using dataframe. Furthermore, an `afterAll` method has been added to `VeloxTPCHDeltaSuite` because the parent class's `afterAll` method cleans up views, whereas Delta creates tables.
Exists CI.

[VL] Code refactoring of variable names related to TPCH in Velox UTs

---

cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

(Fixes: \#4041)
If performance is better than mulitiIf, so we use if function if we have only on condition.
CI
Function `if` has better performance than `mulitiIf` when there is only one condition, especially after PR:
https://github.com/ClickHouse/ClickHouse/pull/57885
On SQL 7954_0
Before:
After PR https://github.com/ClickHouse/ClickHouse/pull/57745
Still if is faster than multiIf:

[CH] Use if function if condition size is 1

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/expression/CHExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala

Separate the implements for PosExplodeTransformer, as CH/VL backend requires different function name and argument list.
Existing test.

[CORE] Separate backend-specific PosExplodeTransformer

---

gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

Clarify fallback reason when columnar filter is disabled.
(Fixes: #4194)

[GLUTEN-4194][CORE] Clarify fallback reason when columnar filter is disabled

---

cpp/velox/tests/CMakeLists.txt

Local test shows it is unnecessary to link installed simdjson.
Existing test.

[VL] Remove linking installed simdjson when building gluten cpp test

---

dev/builddeps-veloxbe.sh
ep/build-velox/src/build_velox.sh

1. Remove `VELOX_BUILD_BENCHMARKS` as it was removed in upstream velox. Use `VELOX_ENABLE_BENCHMARKS` instead.
2. Decouple building gluten cpp benchmark & building velox benchmark. There is no dependency between them. Added a new option `--build_velox_benchmarks` to control whether to build velox benchmark.
3. Decouple building gluten cpp tests & building velox tests. Also, there is no dependency between them. Added a new build option `--build_velox_tests` to control whether to build velox tests.

[VL] Decouple velox benchmarks/tests build from gluten cpp benchmarks/tests build

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/StorageJoinBuilder.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/joins/ClickHouseBuildSideRelation.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHHashBuildBenchmark.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHStorageJoinBenchmark.scala
cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
cpp-ch/local-engine/Join/BroadCastJoinBuilder.h
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
cpp-ch/local-engine/Shuffle/ShuffleReader.h
cpp-ch/local-engine/local_engine_jni.cpp

This PR has two improvements:
1. Instead of utilizing the `ShuffleInputStream`, it is advantageous to directly copy memory from the Java array for small broadcast scenarios.
2. For larger broadcasts, it is beneficial to allocate hashmap size based on the broadcast size. 
However, there is no significant enhancement observed in end-to-end performance. Nevertheless, let us merge as it did the appropriate work.
Before this pr
```
OpenJDK 64-Bit Server VM 1.8.0_392-8u392-ga-1~20.04-b08 on Linux 5.15.0-91-generic
13th Gen Intel(R) Core(TM) i9-13900KF
Build Broadcast Hash Table with 1000000 rows:          Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------ …
```

[GLUTEN-2723][CH] Improve Broadcast Join performance -- Part 3

---

dev/builddeps-veloxbe.sh
docs/developers/docker_centos7.md
docs/get-started/Velox.md
ep/build-velox/src/build_velox.sh
pom.xml

To fix a bug where invalid Pointers appear when running on centos7, it was found to have occurred while loading libarrow_cdata_jni.so. The arrow java module needs to be recompiled in the local environment.
notice: `This configuration is OFF by default. The test is enabled temporarily to test the CI flow`
(Fixes: \#3283)
./dev/builddeps-veloxbe.sh --compile_arrow_java=ON
```bash
*** Error in `/usr/local/jdk1.8.0_381/bin/java': free(): invalid pointer: 0x00007f36cb5cec80 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d1fd)[0x7f38c29da1fd]
/lib64/libstdc++.so.6(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7f36cb3370d2]
/lib64/libstdc++.so.6(_ZNSt6locale5_ImplC1Em+0x1e3)[0x7f36cb337523]
/lib64/libstdc++.so.6(+0x71495)[0x7f36cb338495] …
```

[GLUTEN-3283][VL] Upgrade arrow version to 14.0.1 and add compile arrow java module.

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHFilterExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/FilterExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala

The logic of `flattenCondition` and `getLeftFilters` has already been implemented in Spark, no need to implement the method again in Gluten.
N/A

[CORE] Code refactoring by using splitConjunctivePredicates and ExpressionSet

---

cpp/velox/shuffle/VeloxShuffleWriter.cc

Fix Invalid write reported by valgrind
```
/usr/bin/valgrind gluten/cpp/build/velox/tests/velox_shuffle_writer_test --gtest_filter=VeloxShuffleWriterMemoryTest.resizeBinaryBufferTriggerSpill
[ RUN      ] VeloxShuffleWriterMemoryTest.resizeBinaryBufferTriggerSpill
I1225 19:09:26.151989 714619 VeloxShuffleWriter.cc:1227] Evicted all cached payloads. 0 bytes released
==714619== Invalid write of size 4
==714619==    at 0xF9D664D: gluten::VeloxShuffleWriter::splitBinaryType(unsigned int, facebook::velox::FlatVector<facebook::velox::StringView> const&, std::vector<gluten::VeloxShuffleWriter::BinaryBuf, std::allocator<gluten::VeloxShuffleWriter::BinaryBuf> >&) (VeloxShuffleWriter.cc:746)
==714619==    by 0xF9D6A78: gluten::VeloxShuffleWriter::splitBinaryArray(facebook::velox::RowVector const&) …
```

[VL] Fix shuffle writer invalid write

---

cpp/CMake/BuildMemkind.cmake
cpp/velox/memory/VeloxMemoryManager.cc
ep/build-velox/src/get_velox.sh

```
e907a8001 (upstream/main) Remove the legacy memory allocator code (#8208)
523e561d3 Enable VELOX_ENABLE_PARSE with VELOX_BUILD_TEST_UTILS (#8206)
79bd41051 Fix slow scale writer in Prestissimo (#8172)
aae50540f Guard against AppendWindow destructor throw (#8203)
7c961b25d Fix join spill under split group execution mode (#8178)
da76973af Fix estimateRowSize with wrapper (#8199)
0c02963d8 Add VectorFuzzer::Options in VectorTestBase::createVectors (#8197)
6080a6a69 Memory allocator management refactor (#8094)
```
As the API has changed, this PR removed HBM allocator for Velox. Currently, HBM is mainly used for shuffle (arrow allocator). We should clean up the HBM memory allocator and use [autoHBW](https://manpages.debian.org/experimental/libmemkind-dev/autohbw.7.en.html) in the future.

[VL] Daily Update Velox Version (2024-01-02)

---

cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/Functions/SparkFunctionFloor.h
cpp-ch/local-engine/Shuffle/ShuffleSplitter.h
cpp-ch/local-engine/tests/benchmark_local_engine.cpp
cpp-ch/local-engine/tests/benchmark_spark_floor_function.cpp

(Please fill in changes proposed in this fix)   
Fixes: \#4243    cc @KevinyhZou 
``` bash
./build_gcc/utils/extern-local-engine/tests/benchmark_local_engine --benchmark_filter="BM.*Floor.*Float64"               
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
BM_CHFloorFunction_For_Float64         36547 ns        36547 ns        18987
BM_SparkFloorFunction_For_Float64     134542 ns       134537 ns         5219
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations …
```

[GLUTEN-4243][CH] Improve sparkFloor function performance with avx2

---

gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/csv/GlutenCSVSuite.scala

This PR fixes the following suites:
GlutenCSVv1Suite
GlutenCSVv2Suite
GlutenCSVLegacyTimeParserSuite
(Fixes: \#3559)
Ran these UTs to confirm the fix

[GLUTEN-3559][VL] Fix unit tests in GlutenCSV* suites

---

.github/workflows/velox_be.yml
dev/builddeps-veloxbe.sh
ep/build-velox/src/build_velox.sh

This is a follow-up work for https://github.com/oap-project/gluten/pull/4153. There are some dependencies lacked for gluten cpp test build after that PR. Here, we turn on VELOX_BUILD_TEST_UTILS when gluten cpp build test is on. Maybe, we can deprecate `build_velox_test`, `build_velox_benchmark` in the future.
Pass CI build and local build.

[VL] Follow-up: decouple velox test build from gluten cpp test build and use VELOX_BUILD_TEST_UTILS instead

---

ep/build-velox/src/modify_velox.patch

Velox disables system curl to build cpr to avoid any conflicts from pr: https://github.com/facebookincubator/velox/pull/7718
But it introduce other tests issues like https://github.com/facebookincubator/velox/pull/7718#issuecomment-1850056124
Which is being resolved in https://github.com/facebookincubator/velox/pull/7965
So it would be nice we can disable system curl also to avoid conflicts.
Existing tests

[VL] Disable system curl to build cpr

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHFilterExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/FilterExecTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxScanSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ScanTransformerFactory.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-iceberg/src/main/scala/io/glutenproject/execution/IcebergScanTransformer.scala

Before #3843 the filters pushdown was incorporated into the `runtimeFilters` of `BatchScanExecTransformer`, which was ineffective. Hence, #3843 removed this logic. Now, the logic to pushdown filters in `BatchScanExecTransformer` has been restored and correctly set into a new `pushdownFilters` variable. This will be accessed when the `filterExprs `method is called, and afterwards, it can be pushdown into Velox's `TableScan`.
Add new `VeloxScanSuite` test case to test subquery filter pushdown in tpch q22.

[CORE][VL] Fix BatchScanExec filter pushdown logic

---

cpp/velox/benchmarks/ParquetWriteBenchmark.cc
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/operators/writer/VeloxParquetDatasource.cc
cpp/velox/operators/writer/VeloxParquetDatasource.h

This change adds support to write parquet files to GCS.
It is based on the support already present to write S3.
Fixes #3976

[VL] Add support to write parquet files to GCS

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/SparkWriteFilesCommitProtocol.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarWriteFilesExec.scala
cpp/core/compute/Runtime.h
cpp/core/jni/JniWrapper.cc
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/VeloxRuntime.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
cpp/velox/tests/RuntimeTest.cc
cpp/velox/tests/Substrait2VeloxValuesNodeConversionTest.cc
cpp/velox/tests/VeloxSubstraitRoundTripTest.cc
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/WriteRelNode.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/WriteFilesExecTransformer.scala
gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java
gluten-data/src/main/java/io/glutenproject/vectorized/PlanEvaluatorJniWrapper.java
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala

This pr adds file commit protocol for native write files, to preverse the same behavior with vanilla Spark. E.g.,
- the staging file will be removed if some task success but the job is failed at the end
- won't produce double file in specualtion mode
To achieve the goal, this pr decopules the staging write path and write files transformer. We transform plan at driver side, and generate staging write path at executor side. Then we inject the staging write path before we initialize native plan and do execute.
add tests

[VL] Support spark file commit protocol

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh

```
fefd586a9 (upstream/main) Fix PrestoQueryRunner::toSql to honor sortingKeys for Aggregates. (#8233)
c1ce705a2 Remove unused exception parameter from velox/expression/SimpleFunctionAdapter.h (#8234)
48127fa01 Document hash table (#8167)
fdb3b3c8a Rename system and spill memory pool (#8239)
f057a461b Refactor and move aggregation arbitration test into AggregationTest (#8242)
b76a9edbb Extend conversion options of tmToString (#8165)
2a463b790 Add .parquet suffix to the file name (#8090)
55343d4bd Unify compareInputs and compareResults in ExpressionVerifier and move it to FuzzerToolKit. (#7990)
551e82f3f Refactor and move arbitration test into OrderByTest (#8212)
552c259fe Change cpu driver slicing limit to 1 second by default (#8228)
9dece1aa9 Remove unused exception parameter from files …
```

[VL] Daily Update Velox Version (2024-01-04)

---

README.md
dev/builddeps-veloxbe.sh
docs/get-started/GlutenUsage.md
docs/get-started/Velox.md
docs/get-started/build-guide.md
ep/build-velox/src/build_velox.sh

Velox build summary is helpful to track last build. Thus, velox build cache can be reused when enable_ep_cache=ON. Recently added new build options should be covered in the build summary. Also updated glute build guide.

[GLUTEN-4260][VL] Fix velox build summary by covering new build options

---

.github/workflows/velox_be.yml
pom.xml
tools/gluten-it/pom.xml
tools/gluten-te/ubuntu/dockerfile-buildenv

We have made spark-3.4.2 the official support version at https://github.com/oap-project/gluten/commit/8d46bec8105ac02bbcdb05ff21e1c57c3fab1365. Therefore, we need to build & install spark-3.4.2 inside docker for test to use.
Exiting tests.

[VL] Build & install spark-3.4.2 in docker and correct spark version in pom.xml

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/RemoveNativeWriteFilesSortAndProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This pr adds a new rule to remove the V1Writes added sort and Empty2Null in project. The reason is that:
- Velox table write does not require the data is ordered by partition columns
- Velox table write treats empty string as the `__HIVE_DEFAULT_PARTITION__`, so we do not need `Empty2Null`
After this pr, we can transform the whole write files for dynamic partition write.
add tests

[VL] Remove native write files sort and project

---

gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala

`sortOrders` may come from `FileFormatWriter`, in which case, they are `BoundReference`. 
```
val orderingExpr = bindReferences(
requiredOrdering.map(SortOrder(_, Ascending)),
finalOutputSpec.outputColumns)
val sortPlan = SortExec(orderingExpr, global = false, child = empty2NullPlan)
```
Pass CI

[CORE] Minor fix needProjection in SortExecTransformer

---

cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

This is added before because timestamp is not fully supported, now looks we can remove this check.
Existing UT.

[VL] remove validate for timestamp in sortRel

---

gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala

Window and agg are similar, and in Velox, they also do not support input that contains expressions. The input must be an attribute. Therefore, if there are non-attribute columns in the input for window, we need to add a preProjection to execute them. And similar to the approach in `SortExecTransformer`, the output of the window, which is `child.output ++ windowExpr`, requires a postProjection to remove any extra columns from child.output in the final output (where child refers to the added preProjection).
```sql
SELECT
c_custkey,
row_number() OVER (
PARTITION BY c_nationkey,
"a"
ORDER BY
c_custkey,
"a"
) AS row_num
FROM
customer
ORDER BY 1, 2;
```
Before this PR, the window in above query will fallback due to the reason "native validation failed due to: Only field is supported in window …

[CORE] Add preProjection and postProjection in WindowExecTransformer

---

dev/vcpkg/vcpkg.json

This PR fixes below two build issues:
1. While building gluten cpp with vcpkg, build is breaking with below error:
Adding "thrift" to dev/vcpkg/vcpkg.json dependencies resolves the issue.
(Fixes: \#4218)
Build passes after the fixes

 [GLUTEN-4218] fix: Fix Gluten CPP build breaks 

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteDateTimestampComparisonRule.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Fixes: #4302
1. Fixed: rewrite rule not is applied as expected
2. Fixed: rewrite date equal comparison incorrectly
unit tests

[GLUTEN-4302][CH] Fixed bugs about rewriting date comparison

---

backends-velox/src/main/scala/io/glutenproject/execution/ShuffledHashJoinExecTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/utils/SubstraitUtil.scala

Added cross join type in hash and merge join:
Cross join type will only get converted to hash or merge join when there are equi join conditions. Cross join with equi join conditions is actually inner join only. Ideally, users should not even write such queries.
Currently, queries like `select * from TBL1 cross join TBL2 on TBL1.c1 == TBL2.c1` falls back to Spark. which can easily be supported by Gluten by converting cross join substrait inner join type.
(Fixes: \#4266)
Tested using dummy unit tests

[GLUTEN-4266][VL] Support cross join type with Merge join and Hash join

---

cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h

Fixes: #4314 
set `spark.gluten.sql.columnar.backend.ch.runtime_config.dump_pipeline=true` to enable this log
unit tests

[GLUTEN-4314][CH]Dump pipeline's details upon completion

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/SparkWriteFilesCommitProtocol.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarWriteFilesExec.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/GlutenFileFormatWriter.scala

This pr makes native write support write empty rdd and empty iterator. Vanilla Spark will generate an empty file for metadata only if write empty. Gluten should respect the behavior.
Enable related spark tests

[VL] Support write empty rdd and empty iterator

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxMetricsSuite.scala
cpp/core/jni/JniWrapper.cc
cpp/core/utils/metrics.h
cpp/velox/compute/WholeStageResultIterator.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/MetricsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/WriteFilesExecTransformer.scala
gluten-data/src/main/java/io/glutenproject/metrics/Metrics.java
gluten-data/src/main/java/io/glutenproject/metrics/OperatorMetrics.java
gluten-data/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
gluten-data/src/main/scala/io/glutenproject/metrics/WriteFilesMetricsUpdater.scala

Add the `physicalWrittenBytes `and `numWrittenFiles  `metrics for WriteFilesExecTransformer. 
Adding Unit test and UI locally check.

[VL] Add the metrics for WriteFilesExecTransformer

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenReadSchemaSuite.scala

Velox doesn't support nested type encoding when converting the rowVector to arrow data https://github.com/facebookincubator/velox/blob/main/velox/vector/arrow/Bridge.cpp#L795. So we fallback nested type in native write.
existing tests.

[VL]Fallback complex type in native write

---

tools/gluten-te/centos/gha/gha-checkout/checkout.sh
tools/gluten-te/centos/gha/gha-checkout/clean.sh
tools/gluten-te/centos/gha/gha-checkout/exec.sh
tools/gluten-te/ubuntu/gha/gha-checkout/checkout.sh
tools/gluten-te/ubuntu/gha/gha-checkout/clean.sh
tools/gluten-te/ubuntu/gha/gha-checkout/exec.sh

Modifications to https://github.com/oap-project/gluten/pull/3998
Use the $GITHUB_JOB variable in GitHub Actions to distinguish the containers of different job tests

[VL] Modifications to GHA CI scripts

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/WriteFilesExecTransformer.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

If people set maxRecordsPerFile, then we should fallback to vanilla Spark write files. This pr also moves the write files transformer validation to velox backend.
enable test

[VL] Improve native write files fallback

---

cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.cpp
cpp-ch/local-engine/Operator/StreamingAggregatingStep.cpp
cpp-ch/local-engine/Parser/AggregateRelParser.cpp

[GLUTEN-4327][CH] Avoid generating a lot of small blocks in `StreamingAggregatingTransform`

---

docs/velox-backend-limitations.md

parquet and dwrf now both use https://github.com/oap-project/velox/blob/2024_01_09/velox/dwio/common/compression/Compression.cpp#L644-L727 to decompress data
fixes: #4336

[GLUTEN-4336][VL][DOC] Remove unsupported codecs of reader

---

gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala

This PR enables following tests in the suite GlutenParquetV2FilterSuite: 
- Gluten - filter pushdown - date
(Fixes: \#3559)
Ran this UT to confirm the fix
Changes are based on https://github.com/apache/spark/commit/fa8d93676941f1009837b5bea74a5586118c3a7e

[GLUTEN-3559][VL] Fix unit tests in GlutenParquetV2FilterSuite

---

cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.cpp
cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.h
cpp-ch/local-engine/Operator/StreamingAggregatingStep.cpp
cpp-ch/local-engine/Operator/StreamingAggregatingStep.h

[GLUTEN-4364][CH] Remove memory reserving for new hash tables in the new aggregation implementation

---

.github/workflows/velox_be.yml
backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarBatchSerializer.scala
gluten-core/src/main/scala/org/apache/spark/util/TaskResources.scala
gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManagers.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala

Following #4276:
1. In resources' priority table, replace `PriorityQueue` with `LinkedHashSet` for efficient removing operation; (`PriorityQueue` was good until we added API to remove a single instance in #4276)
2. Make `DeserializationStream` a resource type to replace advanced use case of `addRecycler`
3. Mirror relevant changes to `VeloxCelebornColumnarBatchSerializer`
Update:
The patch will also add restriction to user defined `release()` method to disallow it from accessing task registry recursively, which may cause internal inconsistency leading to invalid state or memory leak.

[VL] A couple of code optimizations to TaskResources

---

gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/connector/GlutenKeyGroupedPartitioningSuite.scala

Enables UTs failing with spark 3.4 due to wrong spark.test.home set earlier in pipeline.
(Fixes: \#3559)
Ran tests locally

[GLUTEN-3559][VL] Enable UTs failing due to wrong spark.test.home set earlier

---

cpp/velox/CMakeLists.txt

This PR fix the following issue in debug  mode.
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java: symbol lookup error: /tmp/gluten-ddf328f6-b6a9-4680-aad9-ceda1856c540/jni/66f083cf-d76e-4b90-8b68-2ac9d756fc84/gluten-1328822599404309800/libvelox.so: undefined symbol: _ZN8facebook5velox6common8testutil14ScopedTestTime20getCurrentTestTimeMsEv
locally verified.

[VL] Fix undefined symbol issue in debug mode

---

gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/ExpandOutputPartitioningShim.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/ExpandOutputPartitioningShim.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/ExpandOutputPartitioningShim.scala

As part of this ticket https://issues.apache.org/jira/browse/SPARK-31869 an improvement was added which can decrease the number of exchanges. As output partitioning is overridden in gluten, the test was failing as extra exchange was coming.
(Fixes: \#3559)
Ran UT locally.

[GLUTEN-3559][CORE] Fix output partitioning of Hash join

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
cpp/velox/compute/WholeStageResultIterator.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala

This pr enables native write files by default for Spark3.4 with Velox backend.
Pass CI
enable tests:
```
GlutenStatisticsCollectionSuite
column stats collection for null columns
store and retrieve column stats in different time zones
"SPARK-38140: describe column stats (min, max) for timestamp column: desc results should be consistent with the written value if writing and desc happen in the same time zone")
"SPARK-38140: describe column stats (min, max) for timestamp column: desc should show different results if writing in UTC and desc in other time zones
Gluten - store and retrieve column stats in different time zones
GlutenSQLQuerySuite
SPARK-26709: OptimizeMetadataOnlyQuery does not handle empty records correctly
GlutenFileSourceSQLInsertTestSuite
SPARK-30844: static partition should …
```

[VL] Enable native write files by default for Spark3.4

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala

Add `simpleString` for `InputIteratorTransformer`. This facilitates tracking of inputs when viewing the plan in the Spark UI.
Just UI info, no tests.

[CORE] Add simpleString for InputIteratorTransformer

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

This issue has already been fixed by us in upstream velox: https://github.com/facebookincubator/velox/pull/8349.
N/A.

[VL] Enable a spark test: handle am-pm timestamp parsing when hour is missing

---

backends-velox/pom.xml
backends-velox/src/test/java/io/glutenproject/tags/FuzzerTest.java
backends-velox/src/test/scala/io/glutenproject/benchmarks/ShuffleWriterFuzzerTest.scala
gluten-core/pom.xml
gluten-core/src/test/scala/io/glutenproject/benchmarks/RandomParquetDataGenerator.scala

Add `ShuffleWriterFuzzerTest`  which utilize `RandomParquetDataGenerator` to generate random schema, input batch size and data for shuffle. This test aims to evaluate the shuffle module's accuracy and spill behavior. Developers should first pass C++ unit tests and then manually execute this specific test after any modifications that could impact the shuffle module.
By default, each test will run with 10 iterations. Failed iterations will be printed as `Failed to run test 'testname' with seed: xxxxx, ...`. Developers can pick up the SQL query corresponding to the test name as well as the seeds from log and modify the `reproduce` test to reproduce. It's recommended to build cpp as Debug build type before running this test.
If any iterations are failed because of OOM, they will be printed as …

[Core][VL] Add random parquet data generator and ShuffleWriterFuzzerTest

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh

```
0b4876 Improve error message in check-function-signatures CI job (8316)
72c795 Fix a crash in conv Spark function (8046)
a0146d migrate from nested-name WriteHolder (8243)
373eda Fix ParquetReaderBenchmark (8274)
281dbf Avoid throwing in OutputBufferManager::updateNumDrivers(). (8357)
912897 Refactor common code in RowContainer::equalWithNulls and equalNoNulls (8323)
5e3816 Expand push_back for arrayWriter support to generics and strings. (8334)
d345e3 Delete the flag declaration of 'velox_use_malloc' (7041)
34607d Fix emptyOutput in trimUnicodeWhiteSpace (8368)
ef1b38f Assert addressable range in bits::scatterBits (8353)
96d701 Refactor thriftCodecToCompressionKind() as an utility function (7643)
3cb4ec Move velox/external/date to vendored namespace (8332)
```

[VL] Daily Update Velox Version (2024-01-15)

---

gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDataFrameSuite.scala

`String. getBytes()` would convert a String into a sequence of bytes in the platform's default charset. While inside spark `String` is internally held as `UTF8String`, so if the platform's default charset is not `UTF-8`, this test could fail. We need to explicitly use `UTF-8` here.
```java
- Gluten - Allow leading/trailing whitespace in string before casting *** FAILED ***
== Results ==
!== Correct Answer - 7 ==                     == Gluten Answer - 7 ==
!struct<>                                     struct<col1:binary>
[WrappedArray(97, 98, 99, 12)]               [WrappedArray(97, 98, 99, 12)]
[WrappedArray(97, 98, 99, 12, 12, 12)]       [WrappedArray(97, 98, 99, 12, 12, 12)]
[WrappedArray(97, 98, 99, 13, 13, 13)]       [WrappedArray(97, 98, 99, 13, 13, 13)]
[WrappedArray(97, 98, 99, …
```

[GLUTEN-1551][VL][FOLLOW-UP] Explicitly set Charset to UTF-8 for leading/trailing whitespace string cast test

---

gluten-core/src/main/scala/io/glutenproject/expression/PredicateExpressionTransformer.scala

#4405
Spark has a declaration logic for In Set functions that keeps the output in a consistent order, so let's make input array sorted when we call transformer.
https://github.com/apache/spark/blob/1bdb81b2b5473793697083fdd9ec1a07ae605528/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/predicates.scala#L605-L612
None

[GLUTEN-4405][CORE] Sort values of In/InSet transformer for deterministic behavior

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

Reverts oap-project/gluten#4167
My initial understanding was that ColumnarShuffleExchangeExec would preserve the behavior of ShuffleExchangeExec/ShuffleExchangeLike, but it actually replaces it.
In this case I think my change is incorrect, and the `case plan: ShuffleExchangeLike` in `replaceWithTransformerPlan` should be `case plan: ShuffleExchangeExec` as before. Because ColumnarShuffleExchangeExec is made specifically to replace ShuffleExchangeExec and not any ShuffleExchangeLike.

Revert "[GLUTEN-3942][CORE]fix: Change columnar overrides to accept ShuffleExchangeLike"

---

cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/common/BenchmarkUtils.cc
cpp/velox/benchmarks/common/BenchmarkUtils.h
cpp/velox/benchmarks/common/ParquetReaderIterator.h

The input batch size of micro benchmark uses arrow default value 64k. This PR fix it by using the command line argument `--batch-size`
issue: #4386

[VL] Fix MicroBenchmark input batch size

---

tools/gluten-te/centos/dockerfile-build
tools/gluten-te/ubuntu/dockerfile-build

Shift the Maven build process from GHA to the Docker image building stage. The specific change involves adding the mvn clean install -Piceberg -Pdelta command to the Dockerfile. This modification allows dependencies installation and project building to be completed during the Docker image construction

[VL][CI] Optimization of Docker Build: Integrating Maven Commands into Dockerfile

---

backends-velox/src/main/java/io/glutenproject/utils/GlutenURLDecoder.java
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala

When constructing Spark `PartitionedFile`, the path used is the not the original encoded path so the decoded path in `IteratorApiImpl` is not correct in some cases. Current we observed the case for '+'.  It's encoded to `%2B` in `URLEncoder.encode` but it becomes `+` when passed into `PartitionedFile` and finally becomes ` ` after decode. This PR tries to fix this issue with UT added.
Test in customer S3 environment.

[VL] Fix incorrect url path caused by decoding on non-original encoded path in PartitionedFile

---

.github/workflows/velox_be.yml

Close #4416
Enable Spark AQE when running Gluten TPC-H IT
Exist CI

[GLUTEN-4416][VL][CI] Enable AQE for TPC-H test in some CI jobs

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/CommonSubexpressionEliminateRule.scala

(Fixes: \#4333)
changes:
- only optimize for exprs in aggregate operator which contains `AggregateExpression` 
- gluten config spark.gluten.sql.commonSubexpressionEliminate is only used in CommonSubexpressionEliminateRule

[GLUTEN-4333][CH] Fix CSE issue in aggregate operator

---

cpp/velox/CMakeLists.txt
ep/build-velox/src/get_velox.sh

```
4e3684 Refactor HiveDataSource (8104)
1bf01e Setup AggregationFuzzer to use Presto as source of truth in experimental jobs. (8314)
31caef Create the parent path if not exist when writing data in HDFS filesystem (8343)
95b436 Update rawInputPositions for Exchange operator (8370)
21cb99 Fix shadowed variable in velox/expression/ExprCompiler.cpp (8393)
fa432b Fix shadowed variable in velox/common/caching/CachedFactory.h (8394)
87ec92 Move ngrams registration to its separate registration file for faster compilation time. (8383)
9c1b76 Fix shadowed variable in velox/exec/Aggregate.cpp (8392)
65b967 Fix shadowed variable in velox/tpch/gen/dbgen/bm_utils.cpp (8391)
e7cb79 Fix shadowed variable in velox/functions/prestosql/ArrayConstructor.cpp (8384)
8353f7 Fix shadowed variable in …
```

[VL] Daily Update Velox Version (2024-01-17)

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h

```
(0 to 3).toDF("x").write.parquet("time_x")
spark.read.parquet("time_x").createOrReplaceTempView("timestamps")
spark.sql("SELECT x FROM timestamps WHERE cast(x as timestamp) IN ('1970-01-01 08:00:01','1970-01-01 08:00:02')").collect
```
Because timestamp cast is not fallback, wrong result is generated.
```
(1) Scan parquet 
Output [1]: [x#0]
Batched: true
Location: InMemoryFileIndex [file:/var/git/time_x]
ReadSchema: struct<x:int>
(2) FilterExecTransformer
Input [1]: [x#0]
Arguments: cast(x#0 as timestamp) IN (1970-01-01 08:00:01,1970-01-01 08:00:02)
```
UT.

[VL] add missed validation for in expr and pushdown filter

---

cpp/velox/tests/RuntimeTest.cc

If we build debug velox version, `TestRuntime.GetResultIterator` could fail since it passes an empty columns with an int schema(arrow has a debug check here):
```c++
DCHECK_EQ(schema->num_fields(), static_cast<int>(columns.size()));
```
We can simply call `gluten::createZeroColumnBatch(1)` to avoid it.
manually test it with Debug Velox version

[VL] Fix failed tests TestRuntime.GetResultIterator

---

cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/utils/VeloxArrowUtils.cc

Use upstream `facebook::velox::BaseVector::flattenVector` to avoid unnecessary copy.

[VL] Optimize ensureFlattened

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriter.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

`spark.gluten.sql.columnar.maxBatchSize` and `spark.gluten.shuffleWriter.bufferSize` are both used by CH and Velox. This patch move the 32K limitation into Velox module.

[Core] Fix batch size limit

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Velox ORC scan is leading to data correctness check failures. While ORC scan is fixed, this PR makes enabling of velox ORC scans configurable and turn it off by default.
Local build.

[VL] Make velox orc scan configurable and keep it on by default.

---

.github/workflows/velox_be.yml
backends-velox/src/main/scala/org/apache/spark/sql/catalyst/FlushableHashAggregateRule.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala

If child output already partitioned by aggregation keys (this function returns true), we should avoid the optimization converting to flushable aggregation.
For example, if input is hash-partitioned by keys (a, b) and aggregate node requests "group by a, b, c", then the aggregate should NOT flush as the grouping set (a, b, c) will be created only on a single partition among the whole cluster. Spark's planner may use this information to perform optimizations like doing "partial_count(a, b, c)" directly on the output data.
This fixes #4421

[GLUTEN-4421][VL] Disable flushable aggregate when input is already partitioned by grouping keys

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLInsertTestSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetPartitionDiscoverySuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenSQLInsertTestSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenSQLInsertTestSuite.scala

```
de2f01 Fix aggregation over all-null keys with ignoreNullKeys = true (8422)
ec3bb6 Use same max-output-buffer-size config for all types of output buffers (8426)
a0dc74 Presto serializer code cleanup (8420)
f6a14d Document setNoCopy and setEmpty Simple Function APIs (8382)
0a2267 Clear hash table for each spilled partition in RowNumber (8413)
f62ac7 Add kPartitionPathAsLowerCase to control whether make the partition path as lower case (8409)
3486c7 Add hour Spark Function (8237)
d05045 Add new config API in AssertQueryBuilder (8431)
a33890 Extract the task utilities to ArbitratorTestUtil (8417)
e09a92 Treat timestamp partition value as local time (8432)
44cdc9 Fix simd::gatherBits for Mac M1 or when AVX2 is disabled (8415)
ccd54d Remove unused variables in …
```

[VL] Daily Update Velox Version (2024-01-19)

---

gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala

Related to #4342, make code clearer

[CORE] Make it clear that expand-partitioning only involves in inner-like joins

---

backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

Remove ConverterUtils.getFileFormat and setDataSchema.

[MINOR] Code clean for ConverterUtils.getFileFormat

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/StorageJoinBuilder.java
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala

1. We should move `aggregateFunction` validation to `doValidateInternal`.
2. For `getAttrForAggregateExprs`, we can use simpler implementation to get the correct attributes from `aggregateExpressions`.
3. For `ConverterUtils.getAttrFromExpr`, we can use the `Expression.references` method to obtain the desired Attribute. In the original implementation, when iterating over `BinaryLike` types, the left child is used for iteration. We can use `reference.head` to get the same Attribute.
Due to the inclusion of custom agg in ClickHouse, the original logic has been retained, and the `getAttrForAggregateExprs` has been abstracted as an interface to accommodate different logics implemented by Velox and ClickHouse.
Exists CI.

[CORE] Optimize some code in HashAggregateExecBaseTransformer

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHValidatorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/execution/RowToVeloxColumnarExec.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxOrcDataTypeValidationSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetDataTypeValidationSuite.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ValidatorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

This pr does two things
- propagate fallback reason to union and shuffle exchange during validation
- rename UnionExecTransformer to ColumnarUnionExec since we do not transform union in fact 
Pass CI

[CORE] Propagate fallback reason to union and shuffle exchange

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala

1. Remove unused variable `buildRelationBatchHolder`
2. In C++, consolidate `WholeStageResultIteratorMiddleStage` and `WholeStageResultIteratorFirstStage`
3. TBD in next PR

[VL] Code cleanups against whole stage transform: Consolidate C++ iterator stage types

---

cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitParser.h
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc

This change moves `getLiteralValue` logic to `SubstraitParser`. then they can be used by `SubstraitToVeloxPlanConverter` also.
This is a refactor change to reduce duplicate logic.

[VL] Refactor 'getLiteralValue' logic

---

cpp/velox/CMakeLists.txt
ep/build-velox/src/get_velox.sh

```
d9f0f1719 Remove static from anonymous namespace in HiveDataSink.cpp (8466)
228745f15 Collect the information about long operator calls on task (8474)
f98fc9917 Back out "Scatter struct nulls when deserializing Presto wire format" (8463)
43bad4e2a Change spill to use iobuf API of WriteFile (8473)
f0be1565c Rename max_arbitrary_buffer_size (part 1) (8472)
3f617ee15 Add TableScan::curStatus_ to track down where TableScan is stuck. (8457)
d747ac331 Fix min/max(x, n) (8311)
ce18fe489 Test side-effect-free of Aggregate::extractXxx (8399)
9397755a6 Use Status as return type for rescaleWithRoundUp (8465)
0b2b07382 Fix json_parse for large number (8455)
6f6c1a843 Skip empty row groups in parquet reader (8000)
713a66a96 Fix flaky test `DecimalUtilTest.divideWithRoundUp` (8380)
5e5684316 Remove …
```

[VL] Daily Update Velox Version (2024-01-23)

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ValidatorApi.scala

Clean up some legacy code for expression validation.
Existing UT.

[VL] Clean up some legacy code for expression validation

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala

Some "spilled bytes" metrics are using wrong type so displayed with wrong unit on SQL UI. This patch fixes the issue.

[VL] Correct unit displayed on SQL UI for spill-related metrics

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala

Introduce two new macros in native to enhance validation log: `LOG_VALIDATION_MSG_FROM_EXCEPTION`, `LOG_VALIDATION_MSG`, then help developer check root cause easily.
Before:
```
(4) SortAggregate: Found unsupported data type in aggregation expression,MapType(StringType,IntegerType,true), BooleanType
(9) SortAggregate: Found unsupported data type in aggregation expression,MapType(StringType,IntegerType,true), BooleanType
(4) SortAggregate: native check failure:native validation failed due to: Validation failed for input type in AggregateRel function due to:Substrait type signature conversion to Velox type not supported for list., native validation failed due to: Validation failed for ProjectRel input.
(9) SortAggregate: native check failure:native validation failed due to: Validation …
```

[VL] Pretty log native fallback reason

---

docs/velox-backend-limitations.md

Update velox backend limitation docs since we have improved the related behavior for Spark3.4.
- We do not need overwrite spark class any more
- We support both static and dynamic table write and won't raise exception if not support
N/A

[VL] Update velox backend limitation docs for Spark3.4

---

cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/tests/JsonToProtoConverter.cc
ep/build-velox/src/get_velox.sh

```
71bb6d0f9 Fix hash join spill issue caused by new internal state (#8520)
147ff3032 Signal timeout when locking task in getLongRunningOpCalls (#8511)
54e87d8eb Refactor TableWriter arbitration test (#8504)
077fd735d Add CAST(varchar as decimal) (#5307)
4cd32e367 Fix ExchangeBenchmark and PrefixSortAlgorithmBenchmark (#8493)
5fa64970f Refactor ParquetReader header to prevent including thrift headers (#8484)
b03643eac Add from_unixtime Spark function (#7532)
ef8783fa0 Avoid creating BlockingState for a yield driver thread (#8490)
1deb0368b Upgrade fmt to 10.1.1 (from 8.0.1) (#7941)
aa6bc30ea Add memory arbitration time runtime stats for operator (#8482)
```

[VL] Daily Update Velox Version (2024-01-25)

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

Currently if the input to filter node contains any timestamp column, it fallbacks to Spark even though filter predicate may not be on timestamp column. Current check is very strict.
Unit tests in PR

[VL] Fix Filter node falling back to Spark whenever there is Timestamp column in input (child node)

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala

[GLUTEN-4510][CORE] DatasetTransformer should skip collect `ReusedExchangeExec` node fallback info

---

dev/vcpkg/vcpkg.json

I note fmt is already statically linked to velox libs. And gluten cpp doesn't depend on it.
Static build test in CI.

[VL] Remove fmt lib from vcpkg.json

---

cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala

Make from_unixtime expression transformed through generic path, no need to specially handle timezone by passing it to substrait as function arg. Because timezone has been passed to backend config and will be acquired in function's processing. Refer to: https://github.com/oap-project/gluten/issues/2804
Spark UT.

[CORE][VL] Enable from_unixtime function and fix test failure

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc

In validationMode, we should also respect the iterator index, otherwise the native plan string will always be `TableScan`.
add test

[VL] Fix wrong native plan string

---

gluten-delta/src/main/scala/io/glutenproject/extension/DeltaRewriteTransformerRules.scala
gluten-delta/src/test/scala/io/glutenproject/execution/VeloxDeltaSuite.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala

We only handles column mapping for top layers, if there are struct type columns, then it would cause wrong result (null for struct type columns). This change leverage delta API to map the schema and attributes to solve the above issue.
Repro:
```
import org.apache.spark.sql.{AnalysisException, DataFrame, Row}
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types.{ArrayType, IntegerType, MapType, StringType, StructType}
import scala.collection.JavaConverters._
val simpleNestedSchema = new StructType().add("a", StringType, true).add("b",new StructType().add("c", StringType, true).add("d", IntegerType, true)).add("map", MapType(StringType, StringType), true).add("arr", ArrayType(IntegerType), true)
val simpleNestedData = spark.createDataFrame(Seq(Row("str1", Row("str1.1", …
```

[VL] fix delta column mapping for struct type columns

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala

Offload byte data type in parquet scan. It's already supported in velox parquet scan as tinyint.

[VL] Offload byte type scan

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

```
7df715557 Deprecate toJonString() methods (8543)
860e35b56 Combine `testComplexCast` with `testCast` (8254)
ec3b082f2 Optimize LIKE for more relaxed patterns (8050)
62fff838b Remove extra isNullAt check in cast (8557)
bd4679167 Fix build error introduced by D53063554 (8541)
2de240a8c Tune down the print frequency of SharedArbitrator reclaim (8556)
ab113266 migrate from FOLLY_FALLTHROUGH to [[fallthrough]] (assorted) (8555)
26b8ca559 Add memory reclaim stats in TaskStats (8497)
f1dfd52ab Skip load data into an inactive destination buffer with notify installed (8532)
2905de79e Randomize fetch data from exchange sources (8480)
23d412f06 Use dedicated timeout thread for LocalExchangeSource (8293)
dd58ab10f Track average buffer time for data stored in OutputBuffer (8534)
0f96c1c26 Back out …
```

[VL] Daily Update Velox Version (2024-01-26)

---

cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
cpp-ch/local-engine/Shuffle/ShuffleReader.h
cpp-ch/local-engine/Storages/IO/NativeReader.cpp
cpp-ch/local-engine/Storages/IO/NativeReader.h

Fixes: #4350 
After this modification. 
unit tests

[GLUTEN-4350][CH] Improve `NativeReader`'s performance for small blocks

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitParser.cc
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Velox has a dedicated remainder function for spark sql, so we should better to use it instead of presto function.
enable related test

[GLUTEN-3559][VL] Fix "cannot divide by 0" exception for remainder function

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
backends-clickhouse/src/main/java/org/apache/spark/sql/execution/datasources/CHDatasourceJniWrapper.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/NativeFileScanColumnarRDD.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHMergeTreeWriterInjects.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseMetricsUTUtils.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
cpp-ch/local-engine/Parser/MergeTreeRelParser.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
cpp-ch/local-engine/local_engine_jni.cpp
gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

Applied for CH backend following velox does  https://github.com/oap-project/gluten/pull/4177
The time taken to generate the substrait plan has decreased from `249938ms` to `4486ms` for `163180` partitions after this pach.
(Fixes: \#4480)
Pass CI

[GLUTEN-4480][CH] Decouple LocalFiles from plan to improve driver generating substrait plan

---

.github/workflows/velox_be.yml
cpp/velox/memory/VeloxColumnarBatch.cc
tools/gluten-te/ubuntu/dockerfile-buildenv

Celeborn is not correctly installed, which causes CI test actually falls back to columnar shuffle.
CI verification.

[VL][CI] Fix fallback to columnar shuffle in celeborn test

---

pom.xml

Dataproc now uses Hadoop 3.3.6
Tested with this version of hadoop locally

[CORE] Change Hadoop Version for DP 2.2

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala

After Velox support https://github.com/facebookincubator/velox/pull/8237 HOUR function, we should not fail HOUR function with native validation.
Close #4475
Local test
Run Spark Local Shell with Gluten(add this PR)
```scala
scala> spark.sql("CREATE TABLE t1(c1 int, c2 timestamp) USING parquet")
res0: org.apache.spark.sql.DataFrame = []
scala> spark.sql("INSERT INTO t1 VALUES(1, NOW())")
res1: org.apache.spark.sql.DataFrame = []
scala> spark.sql("SELECT c1, HOUR(c2) from t1 LIMIT 1").show
+---+--------+
| c1|hour(c2)|
+---+--------+
|  1|      10|
+---+--------+
```

[GLUTEN-4475][VL] Allow offloading Spark hour function

---

dev/vcpkg/vcpkg.json

Add fmt lib back to vcpkg.json to let vcpkg build the static lib. In velox, fmt_SOURCE=AUTO, so the lib will be firstly searched from system. If not found, velox will build from SOURCE. With fmt managed by vcpkg, velox will directly use the pre-built  lib found from vcpkg installation path. This pr also bumped the version to align with velox.
Compile pass.

[VL] Put fmt lib back to vcpkg.json and bump the version

---

README.md
dev/package.sh
docs/developers/NewToGluten.md
docs/get-started/Velox.md
package/pom.xml
tools/workload/tpcds/run_tpcds/run_tpcds.sh

Add arch suffix for package jar and thridparty-lib.jar
See https://github.com/trustin/os-maven-plugin/blob/master/README.md#property-osdetectedarch

[CORE] Add arch suffix for package jar

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/execution/CartesianProductExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
gluten-data/src/main/scala/io/glutenproject/metrics/InputIteratorMetricsUpdater.scala

This pr refactors the code of `CartesianProductExecTransformer` to fix some issues, e.g., before the `CartesianProductExecTransformer` work with other join together would fail.
This pr adds a bridge `ColumnarCartesianProductBridge` connect left/right children and `CartesianProductExecTransformer` to avoid wrapping  them into one `WholeStageTransformer`. The reason is that, `WholeStageTransformer` always assume the input partitions are same, but it is not true for `CartesianProductExec`. The dag after this pr would like.
add tests

[VL][CORE] Refactor and fix the columnar cartesian product

---

gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala

Now `LocalFilesNode` have been completely decoupled from `RealRel` for both velox and ch backend, we can cleanup unnecessary `splitInfo` in `SubstraitContext` and `ReadRel`.
Pass CI

[CORE] Cleanup unnecessary splitInfo in SubstraitContext and ReadRel

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ListenerApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/utils/SharedLibraryLoaderDebian12.scala
dev/package.sh

Support Gluten Build in Debian 12 environment
(Fixes: #4141)
All the unit tests were run and manually checked that the build works with Spark running in Debian 23

[GLUTEN-4141][VL] Support Gluten Build in Debian 12

---

backends-velox/pom.xml
gluten-ut/spark33/pom.xml
gluten-ut/spark34/pom.xml

See https://www.scalatest.org/user_guide/using_the_scalatest_maven_plugin, it helps CI tools collect UT results.

[CORE] Add junitxml path of scalatest-maven-plugin for backends-velox, spark33 and spark34

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHFilterExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/FilterExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala

This pr cleanup the FilterExecTransformerBase to remove some dead code, e.g., `fallbackFilterWithoutConjunctiveScan`, and unify the velox and ch backends implementation.
Pass CI

[CORE] Extract common code into FilterExecTransformerBase

---

ep/build-velox/src/get_velox.sh

```
7bca88a87  Fix GCC OOM when building by reducing parallelism. (#8592)
25e2a7ef9  Fix CI MacOS build (#8601)
8bbec59db  Remove unnecessary check in BooleanMix#getFlatBool (#8595)
e68d5020f  Seperate prefix-sort encoder testing methods into test utils (#8494)
5b8b4bdfe  Optimize count(distinct <complex type>) (#8560)
a113acf8e  Fix flaky test reclaimFromNonReclaimableSortTableWriter (#8591)
7eeb28a5b  Parquet writer tests for supported compression kinds (#7332)
64ed66058  Fix arrow include guards (#8217)
```
Existing unit test

[VL] Daily Update Velox Version (2024-01-31)

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ScanTransformerFactory.scala
gluten-iceberg/src/main/scala/io/glutenproject/execution/IcebergScanTransformer.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala

Vanilla spark just push down part of filter condition into scan, however gluten can push down all filters in some cases, it was done in #4132. But, Clickhouse backend can not do this in parquet file format. we can add this later
This PR add `postProcessPushDownFilter` in `SparkPlanExecApi`,  `CHSparkPlanExecApi` overwrite this funtion to add its own logic.
Consider TPCH 22 `c_acctbal > (select avg(c_acctbal) from customer where ...)`.   it can be push down before this PR.  I disable it for ch backend, since I want to make push down functionality same as vanilla spark first.
Before this PR, `createxxxTransformer` assume pass the extra ilters, after this PR, we pass all push down filters, this is because we may remove unsupported filters  
```scala 
def createFileSourceScanTransformer( …
```

[GLUTEN-3582][CORE][VL][CH] Refactor filter pushdown logic

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriter.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala

Since columnar shuffle writer changes to use arrow buffer size as the dataSize, this pr makes the change to the celeborn. Also, this pr removes `uncompressedDataSize` as it is duplicated now.
Pass CI

[CORE][CELEBORN] Sync the columnar and celeborn shuffle writer

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/execution/RowToVeloxColumnarExec.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Follows https://github.com/oap-project/gluten/pull/4544#discussion_r1470601260 in https://github.com/oap-project/gluten/pull/4544, fix the following error thrown in Spark UT:
```
Input schema contains unsupported type when convert row to columnar for StructType(StructField(window,StructType(StructField(start,TimestampNTZType,true),StructField(end,TimestampNTZType,true)),false),StructField(othervalue,IntegerType,false)) due to do not support data type: TimestampNTZType
java.lang.UnsupportedOperationException: Input schema contains unsupported type when convert row to columnar for StructType(StructField(window,StructType(StructField(start,TimestampNTZType,true),StructField(end,TimestampNTZType,true)),false),StructField(othervalue,IntegerType,false)) due to do not support data type: …
```

[CORE] Add schema validation for broadcast exchange

---

dev/vcpkg/ports/folly/portfile.cmake
dev/vcpkg/ports/folly/vcpkg.json

See velox PR: https://github.com/facebookincubator/velox/pull/7700.
CI build & existing tests.

[VL] Upgrade folly version in vcpkg to align with velox

---

ep/build-velox/src/get_velox.sh

```
3004e3494  Add a blog post for LIKE optimizations (#8576)
f9e94644f  Allow offline pre-compilation of 'xsimd' dependency (#8308)
e0cf6e906  Add TraceHistory (#8603)
6399f1779  Add TraceContext to various system calls that can block (#8583)
12ed56bfe  Add ThreadLocalRegistry (#8623)
e9301cb74  Update README for dependencies (#8607)
52ccd86a5  Deprecate spillDiskWrites (#8565)
fc0645545  Optimize LIKE for more relaxed patterns (#8594)
790d6bda3  Make MultiFragmentTest.partitionedOutputWithLargeInput run faster (#8610)
0579f974c  Add InitGoogleTest to ExchangeFuzzer (#8612)
1c40485bd  Minor fix for typo (#8628)
887b12ef4  Refactor ParquetData and PageReader to use FileMetaDataPtr (#8525)
92f380b4d  Eliminate redundant Expr::addNulls calls (#8616)
09d07d3e7  Fix doc-gen-job so that it has …
```

[VL] Daily Update Velox Version (2024-02-02)

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/PushDownUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQEConcurrentSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseMetricsUTUtils.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/gluten/parquet/GlutenParquetFilterSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/gluten/test/GlutenSQLTestUtils.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/gluten/test/GlutenTPCBase.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/gluten/test/GlutenTPCHBase.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala

This is followup of #4582,  this PR removes unsupported  parquet filters for Clickhouse backend. I also refactor `WholeStageTransformerSuite` for adding `GlutenParquetFilterSuite`
1. Introduce `Arm.withResource` to close file for fixing resource leak.
2. Introduce `withDataframe` for dry run sql.
3. Introduce `tpchSQL` to simpilfy getting tpch sql from resources
(Fixes: \#3582)
Adding new UT.

[GLUTEN-3582][CH] Remove Not Support PushDownFilters

---

cpp/velox/compute/WholeStageResultIterator.cc
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Enable the following two suite:
```
enableSuite[GlutenFileIndexSuite]
.include("SPARK-20367 - properly unescape column names in inferPartitioning")
enableSuite[GlutenFileSourceSQLInsertTestSuite]
.include(
"SPARK-34556: checking duplicate static partition columns should respect case sensitive conf")
```
unit test

[VL] Enable partition path lower unit test

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ScanTransformerFactory.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

We have a check on `isAdaptive` when replacing reusable (broadcast) sub-queries in the case of AQE is on.
```scala
case a: AdaptiveSparkPlanExec if (isAdaptiveContext && conf.subqueryReuseEnabled) =>
// cache the subquery
```
It's an attempt to replace the code with
```scala
case a: AdaptiveSparkPlanExec if (conf.subqueryReuseEnabled) =>
// cache the subquery
```
Since ideally `case a: AdaptiveSparkPlanExec` should imply `isAdaptiveContext == true`.
Related to https://github.com/oap-project/gluten/pull/1851

[CORE] Remove a redundant is-adaptive check

---

gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxSQLQueryTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala

We should pass the specified offset in global limit to the native operator,  since Spark3.4 supports offset feature. Native topK does not offset, so this pr add fallback if topK offset is not 0.
Enable some tests

[CORE] Fix limit with offset for Spark3.4

---

ep/build-velox/src/get_velox.sh

```
6a8f16f37  Use Config::get(name, defaultValue) in HiveConfig (#8633)
b8871b1f2  Introduce BatchVectorSerializer to better support preserving encodings when serializing Vectors (#8567)
e8da62741  Back out D53198236 and D53146503 (#8661)
ec1066e42  Add monthly update for January 2024 (#8656)
0d4e619c3  Add null support to PrefixSortEncoder (#8350)
fcd16994e  Disable pyvelox wheels build in macos temporarily. (#8636)
3c2b74a79  Add ignore_missing_files Hive config (#8615)
2082743d8  Use glog version 0.6.0 in setup-centos8 script (#8614)
806d581c7  Fix folly::dynamic mismatch in driverObj (#8625)
2b0d6425a  Specify 'xsimd_SOURCE' to BUNDLED in linux-presto-fuzzer-run CI (#8655)
78aa78251  Support date-type partition column (#7084)
b236bfbdd  Add VELOX_DCHECK_NULL macro (#8644)
f15732133 …
```

[VL] Daily Update Velox Version (2024-02-04)

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenFormatWriterInjectsBase.scala

It is a better choice to modify the `SparkPlan` only when `SparkPlan` itself supports execution by Gluten, so that the fallback `SparkPlan` remains unchanged.
For agg, we found that there are some corner cases that cannot be executed correctly when codegen is enabled after pulling out the project, therefore, we will put the pulling out process after `AddTransformHintRule`, perform the validation process first, and then pull out the `SparkPlan` that has passed validation.
Exists CI.

[CORE] Move PullOutPreProject after AddTransformHintRule

---

gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala

it's not correct to override `otherCopyArgs`, it may cause:
```
java.lang.IllegalStateException: Failed to copy node
Is otherCopyArgs specified correctly for BatchScanExecTransformer.
Exception message: wrong number of arguments
ctor: public io.glutenproject.execution.BatchScanExecTransformer(scala.collection.Seq,org.apache.spark.sql.connector.read.Scan,scala.collection.Seq,scala.Option,scala.Option,org.apache.spark.sql.connector.catalog.Table,scala.Option,boolean,boolean)
types: class scala.collection.immutable.$colon$colon, class org.apache.spark.sql.execution.datasources.v2.orc.OrcScan, class scala.collection.immutable.Nil$, class scala.None$
args: List(id#1385304L), OrcScan(org.apache.spark.sql.test.TestSparkSession@3a411bd7,Configuration: core-default.xml, core-site.xml, …
```

[GLUTEN-4650][CORE] Fix BatchScanExecShim otherCopyArgs

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/expression/DecimalRoundTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala

Spark 3.2 provides different result type with Spark 3.3 and 3.4 for decimal round. To make them work, a result type check in Velox was disabled. This PR changes to use the same result type for decimal round.
Verified unit tests with https://github.com/oap-project/velox/pull/476.

[VL] Use the same result type for decimal round

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-clickhouse/src/main/scala/io/glutenproject/metrics/HashAggregateMetricsUpdater.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCDSMetricsSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteMultiChildrenCount.scala
gluten-core/src/main/scala/io/glutenproject/extension/ValidationApplyRule.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPostProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenFormatWriterInjectsBase.scala
gluten-data/src/main/scala/io/glutenproject/metrics/HashAggregateMetricsUpdater.scala

Separating https://github.com/oap-project/gluten/pull/4245 into several smaller PRs. The current PR aims to refactor the process of pre/post-projects in `HashAggregateExecBaseTransformer`.
This PR introduces a new `PullOutPostProject` rule to add post-project to agg, in order to correct the output of aggregate after native execution.
Example: `SELECT sum(c1 + 1) + 1 FROM t GROUP BY c2`
Before this rule:
```
Aggregate(keys=[c2], functions=[sum((c1 + 1))])
+- Exchange
+- Aggregate(keys=[c2], functions=[partial_sum((c1 + 1))])
+- Scan [c1, c2]
```
After this rule:
```
Project [(sum((_pre_1)) + 1) AS (sum((c1 + 1)) + 1)]
+- Aggregate(keys=[c2], functions=[sum((_pre_1))])
+- Exchange
+- Aggregate(keys=[c2], functions=[partial_sum(_pre_1)])
+- Project [c2, (c1 + 1) AS _pre_1]
+- Scan [c1, c2] …
```

[GLUTEN-4213][CORE] Refactoring pull out project in HashAggregateExecTransformer

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala

When parsing partition values, Velox regards decimal string is formatted with unscaled value ([link](https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/SplitReader.cpp#L280)). This PR aligns the string format with that assumption.
under test

[VL] Use unscaled value as partition value for decimal type

---

.github/workflows/velox_be.yml
backends-velox/src/test/scala/io/glutenproject/benchmarks/NativeBenchmarkPlanGenerator.scala
cpp/core/compute/ProtobufUtils.cc
cpp/core/compute/ProtobufUtils.h
cpp/core/compute/Runtime.h
cpp/core/config/GlutenConfig.h
cpp/core/jni/JniWrapper.cc
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/data/generic_q5/q5_first_stage_0.json
cpp/velox/benchmarks/data/generic_q5/q5_first_stage_0_split.json
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/VeloxRuntime.h
cpp/velox/jni/VeloxJniWrapper.cc
cpp/velox/tests/RuntimeTest.cc
docs/developers/MicroBenchmarks.md
gluten-core/src/main/scala/io/glutenproject/utils/DebugUtil.scala

Save configurations/substrait plan/input data into the same directory `spark.gluten.saveDir`. User can use the saved files for micro benchmark and no longer need to manually save dumped substrait plan from executor's log. Updated doc for the new usage.

[VL] Save and load configurations for micro benchmark

---

ep/build-velox/src/get_velox.sh
ep/build-velox/src/modify_velox.patch

`2024-02-13 17:20:26 -0800 5d1d2a3fa by Ankita Victor, Fix install_conda in setup-ubuntu.sh to consider the CPU architecture `([#8706](https://github.com/facebookincubator/velox/pull/8706))
`2024-02-13 17:18:10 -0800 793222bf5 by Masha Basmanova, Report rawInputPositions stat for MergeExchange `([#8742](https://github.com/facebookincubator/velox/pull/8742))
`2024-02-13 16:18:19 -0800 dec4c446f by Masha Basmanova, Fix 'out of range in dynamic array' error in Task::toJson `([#8735](https://github.com/facebookincubator/velox/pull/8735))
`2024-02-13 15:49:47 -0800 f0583e76b by Pedro Pedreira, Add `VELOX_BUILD_MINIMAL_WITH_DWIO` compilation option` ([#8682](https://github.com/facebookincubator/velox/pull/8682))
`2024-02-13 15:26:54 -0800 76a5fd0ce by Bikramjeet Vig, Add FieldReference …

[VL] Daily Update Velox Version (2024-02-14)

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/VeloxSubstraitSignature.cc
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

We need to pass elementType in ArrayType to Substrait signature.
Add test case in `TestOperator`.

[GLUTEN-4695][VL] Fix array type Substrait signature

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala

When `aggregateExpressions` includes a subquery, Spark's `PlanAdaptiveSubqueries` Rule will transform the subquery within the final aggregation. The `aggregateFunction` in the `aggregateExpressions` of the final aggregation will be cloned, resulting in creating new `aggregateFunction` objects. The `inputAggBufferAttributes` will also generate new `AttributeReference` instances with larger `exprId`, which leads to a failure in binding with the output of the partial aggregation. We need to adapt to this situation; when encountering a failure to bind, it is necessary to allow the binding of `inputAggBufferAttribute` with the same name but different `exprId`.
Add a test case in `VeloxAggregateFunctionsSuite`.

[VL] Adapting the bind reference of agg that contains subquery in agg expressions

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenFormatWriterInjectsBase.scala

This pr adda a new interface `genColumnarShuffleExchange` in `SparkPlanExecApi` for different backends. To make the core code clear.
Pass CI

[CORE] Add gen columnar shuffle exchange interface

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCDSSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpandFallbackPolicy.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala

This patch reworks `TransformPostOverrides` which converts C2R / R2C to native version to simplify code. Will pull out 2 rules from `TransformPostOverrides`:
* RemoveTopmostColumnarToRow
* RemoveGlutenTableCacheColumnarToRow
Current UTs should be able to cover the change:
1. GlutenFallbackSuite
2. VeloxAdaptiveQueryExecSuite
3. VeloxColumnarCacheSuite

[CORE] Untangle C2R / R2C transforming code

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

These functions should have been supported: array_repeat, array_except, arrray_distinct, array_position. Two of them only need few code to get them correctly mapped to velox function. Also added tests to verify they are offoaded. 
Spark UT & new test.

[VL] Enable array_repeat & array_except function

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala

As the HashAggregate transformer code has been gradually modified, many of the originally defined interfaces have diversified into implementations across different backends, and many that are only used in subclasses no longer need to be abstracted as interfaces. It is necessary to clean them up.
No logic changing, only moving codes.
Exists CI.

[CORE] Code refactoring for HashAggregateExecBaseTransformer

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseColumnarShuffleAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDSV2ColumnarShuffleSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseNativeWriteTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHBucketSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetBucketSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickhouseFunctionSuite.scala
cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.cpp
cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.h
cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
cpp-ch/local-engine/Parser/AggregateFunctionParser.h
cpp-ch/local-engine/Parser/AggregateRelParser.cpp
cpp-ch/local-engine/Parser/AggregateRelParser.h
cpp-ch/local-engine/Parser/TypeParser.cpp
cpp-ch/local-engine/Parser/TypeParser.h
cpp-ch/local-engine/Parser/WindowRelParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/BloomFilterAggParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/CollectListParser.h
gluten-core/src/main/java/io/glutenproject/substrait/expression/AggregateFunctionNode.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/MergeTwoPhasesHashAggregate.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenReplaceHashWithSortAggSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

Merge two phase hash-based aggregate into one aggregate in the spark plan when there is no shuffle between them:
Examples:
```
HashAggregate(t1.i, SUM, final)
|                  =>    HashAggregate(t1.i, SUM, complete)
HashAggregate(t1.i, SUM, partial)
```
For example:
TPCH Q18 with bucket tables, before this pr:
there are two `HashAggregateTransformer` in one whole stage;
after this pr:
there is only one `HashAggregateTransformer` in one whole stage, and will reduce the time for the second `HashAggregateTransformer`.
**Now this feature only support for CH backend.**
Close #4668.
(Fixes: #4668)

[GLUTEN-4668][CH] Merge two phase hash-based aggregate into one aggregate in the spark plan when there is no shuffle

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
cpp/velox/substrait/SubstraitToVeloxExpr.cc
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

These two functions have been supported in Velox recently.
Spark UTs.

[VL] Enable weekday & date_from_unix_date Spark functions

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPostProject.scala
gluten-core/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala

Fix #4713.
Exists CI. Test 1T TPCDS q23b.

[GLUTEN-4713][CORE] Not trim the Alias from resultExpressions when determining whether a post-project is needed

---

backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteMultiChildrenCount.scala

Since we have pulled out pre-project, the conflict of pre-project and row constrcut is resolved. This pr enables rewrite multi-children count even if aggregate has row construct.
add test

[VL] Support multi-children count with row construct

---

cpp/core/config/GlutenConfig.h
cpp/velox/compute/WholeStageResultIterator.cc
docs/velox-backend-limitations.md
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenFileBasedDataSourceSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenFileBasedDataSourceSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenFileBasedDataSourceSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Fixes: #4585 
Upstream PR: https://github.com/facebookincubator/velox/pull/8615, https://github.com/facebookincubator/velox/pull/8662
UT.

[Gluten-4585][VL] Support spark.sql.files.ignoreMissingFiles=true

---

cpp/velox/utils/HdfsUtils.cc

Allow update native hdfs credential if the new credential is different with before.
Related to https://github.com/oap-project/gluten/pull/4184
Pass CI

[VL] Allow updating native hdfs credential

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionToDate.cpp
cpp-ch/local-engine/Functions/SparkFunctionToDateTime.cpp
cpp-ch/local-engine/Functions/SparkFunctionToDateTime.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/tests/CMakeLists.txt
cpp-ch/local-engine/tests/benchmark_to_datetime_function.cpp

(Fixes: \#4279)
test by UT
对比原生Spark测试
3000W 行正常日期时间格式数据，表定义：test_tbl(d string) 测试sql `select count(1) from test_tbl where hour(d) > 1`
原生spark 耗时：18.302s 18.508s 16.208s
PR改动前耗时：5.18s 5.665s  5.164s
PR 改动后耗时：5.705s 5.926s 6.108s
PR改动后相对于改动之前约有10% ～20%的性能回退，但是相对于spark 而言，仍然有3倍左右的提升
通过开发的benchmark_to_datetime_function.cpp 测试， 结果如下
```
2024-01-09T20:28:11+08:00
Running ./benchmark_local_engine
Run on (32 X 2100 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x16)
L1 Instruction 32 KiB (x16)
L2 Unified 1024 KiB (x16)
L3 Unified 11264 KiB (x2)
Load Average: 25.19, 35.96, 41.70
--------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations …
```

[GLUTEN-4279][CH]Bug fix hour diff

---

gluten-core/src/main/scala/io/glutenproject/execution/WriteFilesExecTransformer.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This pr adds a new config `spark.gluten.sql.native.writeFilesColumnMetadataWhiteList` to allow native write files even if there are some metadata. By default, set with `comment` which is quite common if the source table column has comment and the write files column reference it directly. 
add test

[CORE] Add metadata exclusion list for native write

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala

Keep `ProjectExecTransformer` print the same verbose schema with Spark [`ProjectExec`](https://github.com/apache/spark/blob/a87015efb5cf36103bc4eb82ae8613874e2eb408/sql/core/src/main/scala/org/apache/spark/sql/execution/basicPhysicalOperators.scala#L109-L115)
```diff
$formattedNodeName
+Output: $projectList
Input: $child.output
-Arguments: $argumentString
```
Close #4741
Local manual

[GLUTEN-4741][CORE] Align the ProjectExecTransformer#verboseStringWithOperatorId of Gluten with the ProjectExec of Spark

---

gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala

In Spark project expression list always be idempotent, after we do some pull out operation in Gluten, we may add some project expressions in an uncertain order.
You can find this we pass map values to this function cause uncertain order.
https://github.com/oap-project/gluten/blob/9ceade94a061c190bf4f0d5fd6aa7d37d845f29e/gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala#L147-L149
We should make this always return the same order.
Close #4754
manual tests
In local, run tpc-h test q14:
We can see output(project list) always print in order.
```
(14) ProjectExecTransformer
Output [5]: [l_extendedprice#X, l_discount#X, p_type#X, CASE WHEN StartsWith(p_type#X, PROMO) THEN CheckOverflow((promote_precision(cast(l_extendedprice#X as decimal(13,2))) * …
```

[GLUTEN-4754][CORE] Let PullOutProjectHelper#eliminateProjectList return idempotent results

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
cpp/velox/operators/plannodes/RowVectorStream.h
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPostProject.scala

In #4713, we discovered that executing q23b on large scale TPCDS dataset would result in a core dump. After investigation, we concluded that an optimization introduced in #4628, which removed some unnecessary post-projects, led to the occurrence of the core dump. However, we believe that this is only a symptom and not the root cause of the problem. In #4726, we restored the post-project and continued to investigate the reason behind the core dump that was triggered by the absence of the post-project.
We ultimately identified the root cause of the issue to be that the `next` method of `RowVectorStream` moves away the children of `RowVector`, leaving the `RowVector`'s children in an indeterminate state. Since the aggregation operation reuses the output `RowVector`, accessing a child that …

[GLUTEN-4713][CORE] Fix invalid children caused by std::move in RowVectorStream

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseSparkCatalog.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/table/ClickHouseTableV2.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteSuite.scala

Now when executing drop table command, it can not delete mergetree data from a external table, so support command `drop table xxx purge` to delete mergetree data from the external table when dropping table.
Close #4749.
(Fixes: #4749)

[GLUTEN-4749][CH] Support to purge mergetree data for CH backend

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/softaffinity/SoftAffinityManager.scala
gluten-core/src/main/scala/io/glutenproject/softaffinity/scheduler/SoftAffinityListener.scala
gluten-core/src/main/scala/org/apache/spark/listener/GlutenListenerFactory.scala
gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinity.scala
gluten-core/src/test/scala/org/apache/spark/softaffinity/SoftAffinityWithRDDInfoSuite.scala
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala

We add two APIs in Soft Affinity to implement the optimization of handling duplicate data reads by preferentially scheduling them on the same executor. This differs from the hash-based method in that it only sets the prefer location during repeated reads; the initial read is not affected by this. This approach reduces the observed uneven distribution of tasks caused by hash conflicts.
With the new APIs and spark events consumption, we obtain information about the relationships between partitions, RDDs, tasks, and executors. Eventually, we simplify this information into a mapping of partitions to executors. This allows us to determine which partition has been read on which executor. When duplicate partitions arrive, we can then allocate the corresponding tasks to the executor where the …

[Velox] soft affinity support placing duplicate reading to same executors

---

gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala

Additional support was added in Spark-3.4 for default values in parquet file scans.  
https://issues.apache.org/jira/browse/SPARK-39265
While scanning the files if the column with default value does not have any value then reader appends the default value to it. So, even if the column with default value was added later, file scan still provides values for all records (existing as well as new ones).
Velox does not support back filling the existing records while scan. So, if the column with default value was added later then it will provide null as column value for existing records.  
This is a behavior difference and not an inconsistent behavior. Users can update the existing data by running DML commands.
This PR, rewrites those testcases with default value in Gluten.
(Fixes:  #3559)
Unit …

[GLUTEN-3559][VL] Rewrite GlutenInsertSuite test cases with default values

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHStreamReader.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
cpp-ch/local-engine/Shuffle/ShuffleReader.h
cpp-ch/local-engine/Storages/IO/NativeReader.cpp
cpp-ch/local-engine/Storages/IO/NativeReader.h
cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
cpp-ch/local-engine/local_engine_jni.cpp

This reverts commit bf528b30ceb5393b2bab6b81c30a53c5284b93d6.
Revert #4664, due to performance issue

Revert "[GLUTEN-4660][CH]Asynchronous shuffle read (#4664)"

---

backends-clickhouse/src/main/java/io/glutenproject/extension/FallbackBroadcaseHashJoinRules.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteSparkPlanRulesManager.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenFallbackReporter.scala
gluten-delta/src/main/scala/io/glutenproject/extension/DeltaRewriteTransformerRules.scala

Since we now introduced a set of validation rules and backend-specific validation rules that all tend to add transform-hint tags to plan nodes, it more or less becomes confusing to tag a plan as `TRANSFORM_SUPPORTED`. Before the plan is finally implemented within Gluten transformers, a plan node can be turned from `TRANSFORM_SUPPORTED` to `TRANSFORM_UNSUPPORTED` in any particular validation rule. So if a plan is tagged as `TRANSFORM_SUPPORTED`, it's never guaranteed to be executed natively by Gluten.
To eliminate this confusing state and ease understanding, the PR (and next PR as phase 2) targets to remove tag `TRANSFORM_SUPPORTED` and rename the term `transform-hint` to `fallback-hint`. When a plan is tagged with the hint, then it's considered a plan to be fallback and being run in …

[CORE] Remove tag TRANSFORM_SUPPORTED and rename transform-hint to fallback-hint: Phase 1

---

cpp/core/config/GlutenConfig.cc
cpp/core/config/GlutenConfig.h
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/velox/jni/VeloxJniWrapper.cc

This fixes #4748
Introduce a set of `gluten::get<primitive-type>ArrayElementsSafe` functions that would release the gotten array elements while the returned object is destructed. So user would not need to manually release the array elements which can be easily forgotten during programming.

[GLUTEN-4748][VL] Fix JNI array elements memory leak

---

.github/workflows/velox_be.yml

We observed frequent `git clone` errors leading to Velox CI failures. The patch fixes CI scripts to reuse the existing Velox repo in docker image to avoid downloading the whole repo.
The new way would do the following:
```bash
cd <path-to-velox>
git checkout <velox-commit>
```
Previously:
```bash
git clone <velox-branch>
```

[VL] CI: Use existing Velox repo for building

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxIntermediateData.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteTypedImperativeAggregate.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenReplaceHashWithSortAggSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/GlutenReplaceHashWithSortAggSuite.scala

For some typed imperative aggregate functions, like `collect_list`/`collect_set`, Spark will make agg buffer stored as `BinaryType` in partial/ partial merge phase, even though these two functions' output is` ArrayType`. Gluten has no such special handling. For Velox backend, agg function's raw data type is used for agg buffer in partial/partial merge. Thus, there will be a type mismatch issue in the latter shuffle operator, as Gluten plan inherits attributes from its corresponding Spark plan. For `collect_list`/`collect_set`, shuffle expects `BinaryType`, but gets `ArrayType`.
So, we need a rule `RewriteTypedImperativeAggregate` to rewrite `collect_list` and `collect_set` for Velox backend. Referenced the implementation in https://github.com/oap-project/gluten/pull/2669.
Velox does not …

[GLUTEN-4763][VL] Add RewriteTypedImperativeAggregate rule for collect_list

---

.github/workflows/velox_be.yml
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/TypeUtil.scala
gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxIcebergSuite.scala

The original code had a typo when retrieving the partition value of the iceberg table. The reason why the tpch partitioned table tests did not catch this is mainly because the tpch table's partition column type is primarily date, which did not trigger the `case _` code.
Add new test case for partition key type of string and integer.

[VL] Fix Iceberg getPartitionValueString

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxWindowExpressionSuite.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
gluten-core/src/main/java/io/glutenproject/substrait/expression/WindowFunctionNode.java

The convert logic in `WindowFuncitonNode.java`  make the assumption that the lower bound of a row/range frame are always `preceding offset`, and the upper bound are always `following offset`,  which is not the case.
https://github.com/oap-project/gluten/blob/6acd1b367a669bcca8af3708c00328cc3e707d2a/gluten-core/src/main/java/io/glutenproject/substrait/expression/WindowFunctionNode.java#L80
For example, following case is also a valid row frame.
```
select max(l_suppkey) over  (partition by l_suppkey order by l_orderkey rows between 2 preceding and 1 preceding) from lineitem
```
In fact, the spark row frame will convert preceding offset A to -A, so that the lower and upper bound params in `SpecifiedWindowFrame` are always **following offset**. 
Since Velox requires the input offset must be …

[GLUTEN-4789] [VL] Wrong preceding/following convert in window function node

---

gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteSparkPlanRulesManager.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPostProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala

* Pulling out pre/post-project for `WindowExec`.
* `Expression` in `WindowExpression` will no longer cause a fallback.
Enable `Expression in WindowExpression that will fallback` test case in `GlutenSQLWindowFunctionSuite` as not fallback case.

[CORE] Support pull out project for WindowExec

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

Support lag window function.
Spark UT.

[GLUTEN-2031][VL] Enable lag window function

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHBucketSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetBucketSuite.scala
cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
cpp-ch/local-engine/Parser/AggregateRelParser.cpp

When merging hash aggregate with the bloom filter agg, there is the 'Unsupported phase for state function' error throwing.
Close #4807.
(Fixes: #4807)

[GLUTEN-4807][CH] Fix 'Unsupported phase for state function' error when merging hash aggregate with the bloom filter agg

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxOrcDataTypeValidationSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetDataTypeValidationSuite.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Currently Complex type support in Parquet Scan still have much issues. Like nested datatype not supported yet. Result mismatch issues listed here: https://github.com/oap-project/gluten/issues/4587
So now let's add a config to fallback all the complex data types until velox support is mature.
Customer workload

[GLUTEN-4587][VL] Add config to force fallback on scan of complex type

---

backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/1.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/10.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/11.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/12.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/14.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/15.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/19.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/3.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/5.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/6.txt
backends-velox/src/test/resources/tpch-approved-plan/v1-bhj/spark322/8.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/1.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/10.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/11.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/12.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/14.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/15.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/19.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/3.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/5.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/6.txt
backends-velox/src/test/resources/tpch-approved-plan/v1/spark322/8.txt
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala

As title, try mask _pre_123 as _pre_X, _post_123 as _post_X
unit tests

[GLUTEN-4398][FOLLOW] Mask PullOutPostProject and PullOutPreProject id

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/execution/VeloxColumnarToRowExec.scala
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/substrait/SubstraitParser.cc
ep/build-velox/src/get_velox.sh
gluten-data/src/main/scala/org/apache/spark/sql/utils/SparkArrowUtil.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Spark's NullType can be mapped to substrait's nothing type and velox's UnknownType. And we also need some code changes in Velox to support this type.
(Fixes: \#2956)
Existing Spark UTs & new UTs to be added.

[GLUTEN-2956][VL] Support Spark NullType

---

cpp/velox/tests/FunctionTest.cc
ep/build-velox/src/get_velox.sh

This is a followup for velox code rebase 2024_03_04.
Internal Jenkins job.

[VL] Fix boost installation issue and remove useless QueryCtx

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxLiteralSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxExpr.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/VeloxToSubstraitExpr.cc
cpp/velox/substrait/VeloxToSubstraitExpr.h
gluten-core/src/main/java/io/glutenproject/substrait/expression/ListLiteralNode.java
gluten-core/src/main/java/io/glutenproject/substrait/expression/MapLiteralNode.java

Support array or map literal without value.
For example
```
create table map_table(a map<bigint, string>) using parquet;
insert into table map_table select map(1, 'hello');
select size(coalesce(a, map())) from map_table;
```
Added UT

[GLUTEN-4772][VL] Support empty map/array literal

---

.github/workflows/velox_be.yml

The pre-installed celeborn under /opt/ is removed in docker image, which causes CI failure when stopping celeborn master/worker.

[VL][CI] Fix CI failure related to Celeborn 

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickhouseFunctionSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/PredicateExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteIn.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteSparkPlanRulesManager.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala

This pr adds a rule to rewrite `In` if the list option contain non-foldable value. A rewrite example:
```
SELECT * FROM t WHERE c in (1, 2, c2)
=>
SELECT * FROM t WHERE c in (1, 2) or c = c2
```
add test

[CORE] Support In list option contains non-foldable expression

---

backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHAggAndShuffleBenchmark.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark35/src/main/scala/io/glutenproject/sql/shims/spark35/Spark35Shims.scala

Add `def getShuffleAdvisoryPartitionSize(shuffle: ShuffleExchangeLike): Option[Long] = None` in Spark shim to be compatible with Spark 3.5.
Pass CI and in coming 3.5 tests

[CORE] ColumnarShuffleExchangeExec should respect advisoryPartitionSize for Spark3.5

---

gluten-delta/src/test/scala/io/glutenproject/execution/VeloxDeltaSuite.scala

Avoid some annoying errors in local runs.
```
- column mapping mode = name *** FAILED ***
org.apache.spark.sql.delta.DeltaAnalysisException: Cannot create table ('`default`.`delta_cm2`'). The associated location ('file:/var/gluten/gluten-delta/spark-warehouse/io.glutenproject.execution.VeloxDeltaSuite/delta_cm2') is not empty and also not a Delta table.
```

[VL] minor change for delta ut

---

backends-velox/src/main/scala/io/glutenproject/utils/SharedLibraryLoaderCentos8.scala
dev/package.sh

The following exception will occur when testing a CentOS8 cluster that does not contain libsodium.so.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError:/libvelox.so: libsodium.so.23: cannot open shared object file: No such file or directory
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
at java.lang.Runtime.load0(Runtime.java:782)
at java.lang.System.load(System.java:1100)
at io.glutenproject.vectorized.JniLibLoader.loadFromPath0(JniLibLoader.java:89)
at io.glutenproject.vectorized.JniLibLoader.access$300(JniLibLoader.java:57)
at io.glutenproject.vectorized.JniLibLoader$JniLoadTransaction.loadWithLink(JniLibLoader.java:311)
at …
```

[VL] Add libsodium.so to thirdparty lib for CentOS8

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala

Support StructType in HashAggregate
(Fixes: \#4831)

[GLUTEN-4831][VL] Support StructType in HashAggregate

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala

Partial port Spark code to Gluten ExplainUtils processPlan. See https://github.com/apache/spark/pull/45282.
Pass CI

[CORE] Add synchronized for ExplainUtils processPlan

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
cpp/velox/substrait/SubstraitParser.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteCollect.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

- Add `IsNotNull(partial_in)` to skip null value before going to native collect_set
- Add `If(IsNull(result), CreateArray(Seq.empty), result)` to replace null to empty array
add test
pass `SPARK-17641: collect functions should not collect null values`

[VL] Rewrite collect_set and collect_list aggregate function

---

cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/memory/VeloxColumnarBatch.h
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc

This patch re-enables the flattern vector optimizations.
The flattenVector optimization firstly landed in https://github.com/oap-project/gluten/pull/4415
but partially reverted in https://github.com/oap-project/gluten/pull/4474 due to some bugs on Celeborn code path.
Celeborn integration tests should check the code.

[VL] Fix and use flattenVector

---

backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala

Merge `Partial` and `PartialMerge` logic in `generateMergeCompanionNode`.
Exists CI.

[VL] Merge Partial and PartialMerge logic in generateMergeCompanionNode

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala
shims/spark35/src/main/scala/io/glutenproject/sql/shims/spark35/Spark35Shims.scala

Spark3.5 uses job tag to cancel broadcast exchange job. This pr adds two shim methods to be compatible with that:
```
setJobDescriptionOrTagForBroadcastExchange
cancelJobGroupForBroadcastExchange
```
See https://github.com/apache/spark/pull/41440
Pass CI

[CORE] ColumnarBroadcastExchangeExec should set/cancel with job tag for Spark3.5

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
cpp/velox/benchmarks/PlanValidatorUtil.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/jni/VeloxJniWrapper.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java

Pass partition id to velox functions.
UT.

[VL] Pass partition id to velox functions

---

ep/build-velox/src/get_velox.sh

Velox already has install_protobuf in [setup-centos8.sh](https://github.com/facebookincubator/velox/blob/02ca9b0b4f554868b533d2f6526a480ea1e7d035/scripts/setup-centos8.sh#L107-L116), we should only use sed to modify the configure arguments.
N/A

[VL] Fix protobuf configure arguments in get_velox.sh

---

gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java

`CelebornShuffleManager` removes `shuffleId` from `columnarShuffleIds` after unregistering shuffle.
Fixes: #4926 
integration tests.

[GLUTEN-4926][CELEBORN] `CelebornShuffleManager` should remove `shuffleId` from `columnarShuffleIds` after unregistering shuffle

---

cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

Refine log plan/split json into one line, it helps filter json output quickly when multi task running.
Before
```
I0312 12:32:11.865212 1787198 VeloxRuntime.cc:57] ################################################## received substrait::Plan:
I0312 12:32:11.865226 1787198 VeloxRuntime.cc:58] [Stage: 0 TID: 0]
{"relations":[{"root":{"input":{"read":{"common":{"direct":{}},"baseSchema":{"names":["id","dt"],"struct":{"types":[{"i32":{"nullability":"NULLABILITY_NULLABLE"}},{"string":{"nullability":"NULLABILITY_NULLABLE"}}]},"columnTypes":["NORMAL_COL","NORMAL_COL"]},"advancedExtension":{"optimization":{"@type":"/google.protobuf.StringValue","value":"isMergeTree=0\n"}}}},"names":["id#0","dt#1","id#0","dt#1"]}}]}
```
After
```
I0312 15:25:13.993911 3130302 VeloxRuntime.cc:57] …
```

[VL] Refine log plan/split json into one line

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/MiscColumnarRules.scala

1. Break `TransformPreOverrides` into 3. The rules are still in `TransformPreOverrides` as its sub rules.
- FilterTransformRule()
- RegularTransformRule()
- AggregationTransformRule()
3.  `RegularTransformRule`: This rule implements a single node as Gluten's transformer without checking it's children. While the other two rules conditionally implements filter and aggregate by checking its children. In future we'd put corresponding logics to validation phase, to gain some flexibility during implementation to choose whether to transform one single node or not.

[VL] Untangle code of TransformPreOverrides

---

backends-velox/src/test/scala/io/glutenproject/benchmarks/NativeBenchmarkPlanGenerator.scala
backends-velox/src/test/scala/io/glutenproject/benchmarks/ShuffleWriterFuzzerTest.scala

Currently, in the Velox backend, the configuration of glog is reused at the process level. If the glog level is set in a test case, it will cause all subsequent test cases to run with glog=0, generating a large amount of redundant log information. The glog level should not be set in test cases unless necessary.
N/A

[VL] Remove glog level config in unit test

---

cpp/velox/CMakeLists.txt
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/compute/iceberg/IcebergPlanConverter.cc
cpp/velox/compute/iceberg/IcebergPlanConverter.h
cpp/velox/substrait/SubstraitToVeloxPlan.h
gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-iceberg/src/main/java/io/glutenproject/substrait/rel/IcebergLocalFilesNode.java
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxIcebergSuite.scala

Velox add iceberg mor table read support in https://github.com/facebookincubator/velox/pull/7847. This PR supports read iceberg mor table for Velox backend.
Add mor table read test case "iceberg read mor table".

[GLUTEN-3378][VL] Feat: Support read iceberg mor table for Velox backend

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala

Since ClickHouse has an optimizer rule `MergeTwoPhasesHashBaseAggregate` which will merge two aggregates and change the aggregate mode to `Complete`. `PullOutPreProject` rule should also match `Complete` mode.
Exists CI.

[CORE] Add Complete case match in PullOutPreProject

---

.github/workflows/velox_be.yml
docs/get-started/ClickHouse.md
docs/get-started/Velox.md
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornHashBasedColumnarShuffleWriterFactory.scala
gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleWriterFactory.java
gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornUtils.java
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/pom.xml
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriterFactory.scala
pom.xml
tools/gluten-it/package/pom.xml
tools/gluten-it/pom.xml

Support multiple versions of Celeborn
#4903 
CI

[GLUTEN-4903][CELEBORN] Support multiple versions of Celeborn

---

backends-velox/src/main/scala/io/glutenproject/utils/SharedLibraryLoaderCentos8.scala
dev/package.sh

#4870 Add libsodium.so in `SharedLibraryLoaderCentos8`. However, it should not link `libsodium.so` to `libsodium.so`, as this would cause the shared object to fail to load at runtime. I discovered the following warning while using GDB to debug:
```
warning: Could not load shared library symbols for /tmp/gluten-81e940a2-74ff-4c8d-8098-112e930af733/jni/5d511fe8-1801-4338-86dc-8b7e31613bac/gluten-9058260266840333844/libsodium.so.
```
We should load and create link for `libsodium.so.23` to `libsodium.so` or `libsodium.so.23.3.0` to `libsodium.so`.
N/A

[VL] Copy the libsodium.so with version number in dynamic packaging

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenImplicitsTest.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenReplaceHashWithSortAggSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/GlutenReplaceHashWithSortAggSuite.scala

Spark introduced `spark.sql.execution.sortBeforeRepartition` config in https://issues.apache.org/jira/browse/SPARK-23207 to keep the result correct, and we should do the same thing in gluten plan to achieve the same affact.
(Fixes: https://github.com/oap-project/gluten/issues/4875)
* Added ut to verify the executed plan is as expected.

[GLUTEN-4875][VL]Support spark sql conf sortBeforeRepartition to avoid stage partial retry casuing result mismatch

---

cpp/velox/benchmarks/GenericBenchmark.cc
docs/developers/MicroBenchmarks.md

This patch fixes the generic benchmark usage when simulate stage which contain scan task and shuffle read task at same time, e.g. BHJ.

[VL] Fix generic benchmark usage when both split and data exists

---

cpp-ch/local-engine/Functions/SparkFunctionDateToUnixTimestamp.cpp
cpp-ch/local-engine/Functions/SparkFunctionDateToUnixTimestamp.h
cpp-ch/local-engine/Functions/SparkFunctionToDate.cpp
cpp-ch/local-engine/Functions/SparkFunctionToDateTime.h
cpp-ch/local-engine/Parser/scalar_function_parser/unixTimestamp.cpp
cpp-ch/local-engine/tests/benchmark_to_datetime_function.cpp
cpp-ch/local-engine/tests/benchmark_unix_timestamp_function.cpp

[GLUTEN-4994][CH]Fix function conversions

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala

When the input decimal precision is very large, the precision of sum and avg may exceed 38, and we should not infer the intermediate type based on the result type in decimal sum/avg functions, we should always infer the intermediate type and result type based on the raw input type.
For example, in average aggregate function:
input = decimal(p, s)
intermediate = row(decimal(min(38, p + 10), s), bigint)
result = decimal(min(38, p + 4), min(38, s + 4))
We should not infer intermediate type by using result precision + 6, it is not correct when p > 34.
Add some test cases with large precision to prevent future modifications to decimal avg sum from introducing errors.
Add large precision test cases in avg and sum `VeloxAggregateFunctionsSuite`.

[VL] Add velox decimal avg sum large precision test case

---

.github/workflows/code_style.yml
cpp/velox/substrait/SubstraitToVeloxExpr.cc

jidicula/clang-format-action@v3.5.1 doesn't meet Apache criteria and will cause following error. So we upgrade to v4.11.0 which is also used by CH backend.
CI

[VL] Update clang-format version to v4.11.0 for Velox backend

---

cpp-ch/local-engine/Common/AggregateUtil.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp

1. https://github.com/ClickHouse/ClickHouse/pull/61211 remove following declaration from `Aggregator.h`, let's declare it our unit
```c++
namespace ErrorCodes
{
extern const int UNKNOWN_AGGREGATED_DATA_VARIANT;
}
```
2. https://github.com/ClickHouse/ClickHouse/pull/61003 remove `namespace fs = std::filesystem;` in [src/Interpreters/DatabaseCatalog.h](https://github.com/ClickHouse/ClickHouse/pull/61003/files#diff-ffc50ad8fde8d1f6f16044bd86c640f2f6097b9ab1d9d1a4b1f4c6653c0f0b7d), let's fix it
Using existed UT

[CH][Build][Minor] Fix Build Due to Clickhouse refactor

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala

…etter to be transformed to PartitionerAwareUnionRDD than UnionRDD when they has same partitioner. #4999
For example:
select * from test a
union all
select * from test b
union all
select * from test c
They have the same partitioner.
In ColumnarUnionExec, they will be transformed to rdd1.union(rdd2).union(rdd3).
After this pr,
In ColumnarUnionExec, they will be transformed to PartitionerAwareUnionRDD(sc, Seq(rdd1, rdd2, rdd3)) if they have the same partitioner.
(Fixes: \#4999)

[GLUTEN-4999] Fix ColumnarUnionExec to get PartitionerAwareUnionRDD used if child RDDs share same partitioner

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala

This is a follow-up to use the newly introduced GlutenNotSupportException in plan validation. The `Exception` caught in GlutenPlan validation is too general, which makes some exceptions that require us to handle hidden in fall back behavior.

[CORE] Catch more specific exceptions in Gluten plan validation

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveUDFTransformer.scala

Support HiveGenericUDF when mapping to native function
(Fixes: \#5001)

[GLUTEN-5001][CORE] Support mapping to native function for HiveGenericUDF

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/expression/CHExpressionTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxStringFunctionsSuite.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/StringExpressionTransformer.scala

In the main code, gluten will make regexp_replace fall back if its last `pos` arg is specified by user with a non-default value.  We note upstream velox has a fix for this function. So we are removing such fallback for velox backend.
This PR depends on a velox PR which fixes newly found issues: https://github.com/facebookincubator/velox/pull/8387
Existing spark UTs.

[VL] Support regexp_replace function with position argument

---

gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
gluten-iceberg/src/main/java/io/glutenproject/substrait/rel/IcebergLocalFilesBuilder.java
gluten-iceberg/src/main/java/io/glutenproject/substrait/rel/IcebergLocalFilesNode.java
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala

The file information such as `paths` and `starts` stored in `LocalFilesNode` is organized and stored using `List`. Iceberg delete files should also use this form to make the code structure more unified.
Exists CI.

[GLUTEN-3378][VL][FOLLOWUP] Use List to store Iceberg delete files

---

ep/build-velox/src/build_velox.sh

Add sudo for macOS related commands, without it installing xsimd and gtest will fail.
Fixes: #5020
Manual tested on macOS.

[GLUTEN-5020][VL] Add sudo for macOS related commands

---

cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/operators/writer/VeloxParquetDatasource.cc
ep/build-velox/src/get_velox.sh

Velox Upstream New Commits:
```
0b4b6e84a by wypb, Add more test cases for cast(string as float) (#9148)
9c7eb6c17 by Masha Basmanova, Add support for DECIMAL types to Simple Function API (#9096)
a942ac836 by rui-mo, Support different timestamp units in arrow bridge (#7625)
0ad627ab6 by Ubuntu, Wave Table Scan Infrastructure (#9131)
c571bcd69 by Masha Basmanova, Speedup PrefixSortTest::fuzzMulti (#9151)
ff346f2ac by joey.ljy, Allow setting variables for intermediateType in AggregateFunctionSignature (#9106)
813c4b4e5 by xiaoxmeng, Fix flaky MultiFragmentTest.partitionedOutputWithLargeInput (#9147)
3e13ff56b by Jacob Wujciak-Jens, Disable sanitizer check in cpr build (#9139)
3055f4a2b by Masha Basmanova, Decouple UDFHolder from SimpleFunctionMetadata (#9143)
0e94ab554 by InitialZJ, Update …
```

[VL] Daily Update Velox Version (2024_03_20)

---

docs/developers/HowTo.md

1. Fixed some typos.
2. Changed `gluten_home` to `${GLUTEN_HOME}`, so the code in this doc is actually executable.
3. Some other polishing.

[GLUTEN-5051][Core] Optimize document: HowTo.md

---

cpp/CMakeLists.txt

Currently when unsupported compiler is detected, the build is not failed, just a message is logged, causing strange errors thrown later. By fail fast, it gives user a clear message what is going on.
Fixes: #5027
Manual tested on macOS.

[GLUTEN-5027][VL] Fail fast for unsupported compilers

---

pom.xml

Update iceberg version to 1.4.3 for Spark 3.3 and above, as v1.3.1 is not compatible with Spark 3.5.
Note that iceberg's latest version is 1.5.0 but as it's not available in mirror repo, we use 1.4.3 instead. So the version mapping is:
```
Spark 3.2 : v1.3.1
Spark 3.3 : v1.3.1
Spark 3.4 : v1.4.3
Spark 3.5 : v1.4.3  
```
Existing UTs

[GLUTEN-4933][VL] Update iceberg version to 1.4.3 for Spark 3.4 and above

---

cpp-ch/local-engine/Common/DebugUtils.cpp
cpp-ch/local-engine/Shuffle/SelectorBuilder.h
cpp-ch/local-engine/Storages/Parquet/ColumnIndexFilter.cpp

https://github.com/ClickHouse/ClickHouse/pull/61604 reduce header dependencies and hence cause our build failed.
1. `DatabaseCatalog.h` remove `#include <Databases/IDatabase.h>`,  and `ColumnIndexFilter.cpp`  needs
include `Common/logger_useful.h`
2. `IDataType.h` remove `#include <DataTypes/Serializations/SerializationInfo.h>` and `SelectorBuilder.h`  needs incldue `Poco/JSON/Array.h`
3. Also `DebugUtils.cpp` needs inculde `iostream`  becasue of 2
We can avoid upgrading clickhouse backend by this PR.
Using existed UT

[CH][Minor] Fix build due to Clickhouse Refactor

---

cpp/velox/compute/VeloxRuntime.cc

It's a quick bug fix.
unordered_map::merge removes the duplicated items from source.
https://en.cppreference.com/w/cpp/container/unordered_map/merge

[VL] Fix bug where session config is lost when benchmark is enabled

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteSuite.scala

The below writing mergetree data sql will throw the assert error:
```
insert into table lineitem_mergetree
select * from lineitem **limit 10**
```
RC:
with limit n, there is a wrong wrapper logical with the FakeRowAdaptor for the query plan.
Close #5061.
(Fixes: #5061)

[GLUTEN-5061][CH] Fix assert error when writing mergetree data with select * from table limit n

---

cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/common/BenchmarkUtils.cc
cpp/velox/benchmarks/common/BenchmarkUtils.h
cpp/velox/compute/VeloxRuntime.cc
docs/developers/MicroBenchmarks.md

1. Fix typos in the document and reformat the max length of lines.
2. Rename option `--write-file` to `--save-output` for saving the output from micro benchmark. The former one can get easily mixed up with another option `--write-path`, which is used to specify the absolute output directory for the parquet write tasks.

[VL][Minor] Update micro benchmark

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteSuite.scala

Add a UT to ensure that IN filtering can apply on CH primary key
Close #5062.
(Fixes: #5062)

[GLUTEN-5062][CH] Add a UT to ensure that IN filtering can apply on CH primary key

---

ep/build-velox/src/get_velox.sh

CI test take a lot of time to git clone boost source code. We could consider directly downloading the source code, similar to what setup-centos8.sh does.
N/A

[VL] Replace "git clone" by downloading tar package for boost in setup-ubuntu.sh

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/VeloxSubstraitSignature.cc
cpp/velox/tests/VeloxSubstraitSignatureTest.cc
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala

Support MapType substrait signature
(Fixes: \#4830)

[GLUTEN-4830][VL] Support MapType substrait signature

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

A test added & the imported Spark tests.

[CORE] Enable bit_length Spark function

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHNullableSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/MiscColumnarRules.scala

[GLUTEN-5016][CH] Fix exchange fallback in simple aggregation sql if spark.gluten.sql.columnar.preferColumnar=false

---

.github/workflows/velox_be.yml

Celeborn 0.3.2 & 0.4.0 have been pre-installed in CI docker.

[VL][CI] Use pre-installed celeborn to avoid download failure

---

gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala

Velox has fixed this issue, so it would be better to remove the workaround.
Pass CI

[VL] Remove lead/lag ignoreNulls workaround

---

ep/build-velox/src/get_velox.sh

function `install_openssl` is not actually used as `openssl-devel` is already installed in previous step in the script.
CI

[VL] Remove unused openssl setup script change for centos8

---

backends-velox/src/main/java/io/glutenproject/udf/UdfJniWrapper.java
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
backends-velox/src/test/scala/io/glutenproject/expression/VeloxUdfSuite.scala
cpp/velox/jni/JniUdf.cc
cpp/velox/jni/JniUdf.h
cpp/velox/jni/VeloxJniWrapper.cc
docs/get-started/Velox.md

1.  Remove `driverUdfLibPath` and retain only `udfLibPath`, as there is no need to differentiate between the driver and executor. The method used to access the file is determined by whether --master=yarn is specified.
> For more details on the reason, refer to Issue link #5074 
3. The UDF is loaded by `VeloxBackend::initUdf` in both the driver and the executor. `UdfResolver` does not load the UDF repeatedly; it only retrieves the function signatures.
(Fixes: \#5074)
I tested with and without the --files/--archives arguments in local, yarn-client, and yarn-cluster modes.

[GLUTEN-5074][VL] fix: UDF load error in yarn-cluster mode

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxLiteralSuite.scala
cpp/velox/substrait/SubstraitToVeloxExpr.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformerBase.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPostProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/RewriteSparkPlanRulesManager.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala

A follow-up of https://github.com/apache/incubator-gluten/pull/4901
Pullout pre/post project for `GenerateExec`. The added projections are moved into Backends API. With this approach, `Literal` and `CreateArray` for `Inline` are also supported as they can be directly constructed by the expression transformer in the project.
Other fixes: 1. Fix coredump on array of null Struct Literal; fallback this case. 2. Add field name for constructing struct literal in `SubstratiToVeloxExpr` to avoid the downstream Velox operator from referencing unexpected struct fields by name.

[CORE] Pullout pre/post project for generate

---

.github/workflows/build_bundle_package.yml

This PR adds a new workflow to support build bundle package through github action:
(Fixes: #5112)
Manual tests: https://github.com/wangyum/incubator-gluten/actions/runs/8421684818

[GLUTEN-5112] Support build bundle package through github action

---

backends-clickhouse/pom.xml
gluten-celeborn/clickhouse/pom.xml

Fix the classes in the hadoop-common conflict when running ut local.
Env: Idea + Spark 3.3 + Hadoop 3.3.1
UT: GlutenClickHouseMergeTreeWriteOnS3Suite / GlutenClickHouseMergeTreeWriteOnHDFSSuite Error:
```
java.lang.NoClassDefFoundError: xxxxx
at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:634)
at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
at …
```

[GLUTEN-5108][CH] Fix the classes in the hadoop-common conflict when running ut local

---

dev/vcpkg/ports/folly/fix-deps.patch

This fixes error "Compression type 2 not supported" when spilling kicks in, in static build mode.
https://github.com/apache/incubator-gluten/issues/4263

[GLUTEN-4263][VL] Fix compression type 2 not supported in static build

---

cpp/velox/operators/functions/RegistrationAllFunctions.cc
cpp/velox/operators/functions/RowConstructorWithNull.cc
cpp/velox/operators/functions/RowFunctionWithNull.h
ep/build-velox/src/get_velox.sh

```
3aa020dff (upstream/main) Fix fbthrift build in setup-*.sh (#9204)
c4f322526 Replace test methods with lambdas in sparksql/tests/StringTest.cpp (#9066)
5c67de403 Fix multiple files spilled for the distinct hash table (#9230)
f5dbf1ea5 Record pause time and off thread time per driver (#9199)
835b88e04 Fix build error in ArrowBridgeArrayTest (#9243)
b842c14fe Move scalar function metadata to the registry (#9209)
049cf2021 Add nightly runs of Aggregation fuzzer using Presto as source of truth. (#9087)
05cede5ea Fix allocation calls where requested size is covered by the collateral (#9145)
700ce6d41 Ensure memory reservation before shrinking cache and allocating (#9136)
e955b4be2 Fix incorrect std::move in ExprCompiler.cpp (#9237)
fe49b3733 Rewrite GenericInPredicate as simple function …
```

[VL] Daily Update Velox Version (2024_03_26)

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseWholeStageTransformerSuite.scala
backends-velox/src/test/scala/io/glutenproject/benchmarks/NativeBenchmarkPlanGenerator.scala
backends-velox/src/test/scala/io/glutenproject/benchmarks/ShuffleWriterFuzzerTest.scala
backends-velox/src/test/scala/io/glutenproject/execution/FallbackSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/FunctionsValidateTest.scala
backends-velox/src/test/scala/io/glutenproject/execution/ScalarFunctionsValidateSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxColumnarCacheSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxHashJoinSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxLiteralSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxMetricsSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxOrcDataTypeValidationSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetDataTypeValidationSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxScanSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxStringFunctionsSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCDSSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxWindowExpressionSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/WindowFunctionsValidateSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-delta/src/test/scala/io/glutenproject/execution/VeloxDeltaSuite.scala
gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxIcebergSuite.scala

1. Remove the below useless method from some test classes.
`protected val backend: String`
2. Rename `VeloxFunctionSValidateSuite` to `ScalarFunctionsValidateSuite`, and create `WindowFunctionsValidateSuite` to let them respectively hold scalar function tests & window function tests.
3. Move some scalar function tests in `TestOperator.scala` to `ScalarFunctionsValidateSuite.scala`.

[VL][MINOR] Refactor operator/function tests

---

ep/build-velox/src/get_velox.sh

For the background of this, please refer to https://github.com/apache/incubator-gluten/blob/main/docs/velox-backend-troubleshooting.md#fatal-error-after-native-exception-is-thrown
In future we may need to improve the patching code by at least by throwing some errors when failing to find a match.

[VL] Velox patch to avoid installing libunwind-dev no longer works

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/Backend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendsApiManager.scala

The `BackendBuildInfo` case class seemed more appropriate in `Backend` class file, so I moved it.

[CORE] Move BackendBuildInfo case class from GlutenPlugin to Backend class file

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Remove exclude for SPARK-10634 timestamp written and read as INT64 - truncation
SPARK-10634 timestamp written and read as INT64 - truncation

[VL] Enable SPARK-10634 timestamp test case

---

cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.cpp
cpp-ch/local-engine/Operator/StreamingAggregatingStep.cpp
cpp-ch/local-engine/Parser/AggregateRelParser.cpp

[GLUTEN-5083][CH] Invalid result with `mergeTwoPhasesHashBaseAggregateIfNeed` enable

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/BroadcastUtils.scala

https://github.com/apache/incubator-gluten/issues/5136
Will be tested by https://github.com/apache/incubator-gluten/pull/5058. It's probably not a trivial code path and may delay adding dedicated UTs.

[GLUTEN-5136][VL] Duplicated output from Spark-to-Velox broadcast relation conversion

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala
shims/spark35/src/main/scala/io/glutenproject/sql/shims/spark35/Spark35Shims.scala

Spark 3.4 introduce some new aggregate functions, we need to introduce `aggregateExpressionMappings` for these new aggregate functions. 
Also rename original `expressionMappings` to `scalarExpressionMappings`.
N/A

[CORE] Introduce aggregateExpressionMappings interface in SparkShims

---

.github/workflows/build_bundle_package.yml

Set up java and maven according to os in build_bundle_package.yml
(Fixes: \#5123)
Pass the build bundle package in github action.
Manual test:  
* centos7: https://github.com/dcoliversun/gluten/actions/runs/8436722430
* ubuntu: https://github.com/dcoliversun/gluten/actions/runs/8438294441
* centos8: https://github.com/dcoliversun/gluten/actions/runs/8439025928

[GLUTEN-5123][INFRA]set up java and maven according to os in build_bundle_package.yml

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/io/glutenproject/execution/VeloxColumnarToRowExec.scala
backends-velox/src/test/scala/io/glutenproject/execution/ScalarFunctionsValidateSuite.scala
cpp/core/shuffle/Utils.cc
cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/java/io/glutenproject/substrait/type/IntervalYearTypeNode.java
gluten-core/src/main/java/io/glutenproject/substrait/type/TypeBuilder.java
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala
gluten-data/src/main/scala/org/apache/spark/sql/utils/SparkArrowUtil.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

Limitation: Cast from/to INTERVAL_YEAR_MONTH is not supported in Velox.

[VL] Support YearMonthIntervalType and enable make_ym_interval

---

gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala

`eliminateProjectList` removed the project function, like below:
`HashAggregate(keys=[knownfloatingpointnormalized(normalizenanandzero(f#38)) AS f#38], functions=[partial_count(1)], output=[f#38, count#46L])`
-->
```
+- ^(5) FlushableHashAggregateTransformer(keys=[f#38], functions=[partial_count(1)], output=[f#38, count#46L])
+- ^(5) ProjectExecTransformer [f#38]
```
`knownfloatingpointnormalized(normalizenanandzero` are removed after the transfer. This is found when doing the change https://github.com/facebookincubator/velox/pull/9272, it can be reproduced by the query:
`Seq(0.0f, -0.0f, 0.0f/0.0f, Float.NaN).toDF("f").groupBy("f").count().collect`

[Core] minor change for eliminateProjectList

---

cpp/velox/shuffle/VeloxShuffleWriter.cc

Null Stringview may have an arbitrary size. Avoid copying the StringView if it's null.

[VL] Fix Shuffle split get wrong binary length

---

cpp/core/compute/Runtime.h
cpp/core/jni/JniWrapper.cc
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/VeloxRuntime.h
cpp/velox/tests/RuntimeTest.cc

Extract TaskInfo param from `parsePlan` to a new method `setSparkTaskInfo`.

[VL] Fix wrong task info when log split info

---

backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala

It is already ensured in the `extractStructNeeded` method that only `Partial` and `PartialMerge` will enter `applyExtractStruct`. There is no need to check again.
N/A

[VL] Remove useless agg mode check in applyExtractStruct

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
cpp-ch/local-engine/Operator/DefaultHashAggregateResult.h
cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
cpp-ch/local-engine/Parser/AggregateFunctionParser.h
cpp-ch/local-engine/Parser/AggregateRelParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/TypeParser.cpp
cpp-ch/local-engine/Parser/TypeParser.h
cpp-ch/local-engine/Parser/WindowRelParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/ApproxPercentileParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/ApproxPercentileParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/BloomFilterAggParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/CollectListParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/CountParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/CountParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/LeadLagParser.h
cpp-ch/local-engine/Storages/IO/NativeReader.cpp
cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
cpp-ch/local-engine/Storages/SourceFromJavaIter.h
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
cpp-ch/local-engine/compile_commands.json
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

(Fixes: \#2163)
vanilla takes 2.665 seconds 
gluten takes 1.502 seconds

[GLUTEN-2163][CH] support aggregate function approx_percentile 

---

gluten-ut/spark32/src/test/resources/sql-tests/inputs/group-by.sql
gluten-ut/spark32/src/test/resources/sql-tests/inputs/udf/udf-group-by.sql
gluten-ut/spark32/src/test/resources/sql-tests/results/group-by.sql.out
gluten-ut/spark32/src/test/resources/sql-tests/results/udf/udf-group-by.sql.out
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxSQLQueryTestSettings.scala
gluten-ut/spark33/src/test/resources/sql-tests/inputs/group-by.sql
gluten-ut/spark33/src/test/resources/sql-tests/inputs/udf/udf-group-by.sql
gluten-ut/spark33/src/test/resources/sql-tests/results/group-by.sql.out
gluten-ut/spark33/src/test/resources/sql-tests/results/udf/udf-group-by.sql.out
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxSQLQueryTestSettings.scala
gluten-ut/spark34/src/test/resources/sql-tests/inputs/group-by.sql
gluten-ut/spark34/src/test/resources/sql-tests/inputs/udf/udf-group-by.sql
gluten-ut/spark34/src/test/resources/sql-tests/results/group-by.sql.out
gluten-ut/spark34/src/test/resources/sql-tests/results/udf/udf-group-by.sql.out
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxSQLQueryTestSettings.scala

The calculation formula of `corr` in Velox is slightly different from that in Spark, which causes some differences in the accuracy of the final calculation results, but these differences are within the allowed precision range. Previously, the inconsistent test cases were deleted, but now it has been found that other statistics-related agg functions such as `skewness`, `stddev`, and `variance` also have differences in calculation accuracy. We cannot delete all of these test cases that have differences. A better approach is to modify the content in the result file.
In this PR, we restore the `corr` test cases in group-by.sql and udf-group-by.sql, and modify the correct results in .out file.
Exists CI.

[VL] Restore the test cases for corr in group-by.sql and udf-group-by.sql

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala

Since the rewrite logic is currently specialized to CH backend. ACBO would require for this fix to make sure a node's metadata doesn't get changed after applying rule (although it's not a MUST for ACBO, it's better to keep metadata not changed after applying rules).

[CH] Move project transformer rewriting code to CH backend

---

gluten-core/src/main/scala/io/glutenproject/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/io/glutenproject/utils/PullOutProjectHelper.scala

Because we still need to append the pulled-out `NamedExpression`s after the child output, it would be more appropriate to revert back to the original function signature.
Exists CI tests.

[CORE] Restore the function signature for eliminateProjectList

---

tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/TpcRunner.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/QueryRunner.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkSessionSwitcher.scala

Mainly to compact "Creating catalog table" logs into one line.
Before:
```
Running query: q65...
Switching to SessionDesc(SessionToken(baseline),Vanilla Spark TPC-DS q65) session... 
Successfully switched to SessionDesc(SessionToken(baseline),Vanilla Spark TPC-DS q65) session. 
Creating catalog table: customer
Creating catalog table: catalog_page
Creating catalog table: catalog_returns
Creating catalog table: item
Creating catalog table: web_page
Creating catalog table: web_sales
Creating catalog table: web_returns
Creating catalog table: warehouse
Creating catalog table: store_returns
Creating catalog table: customer_demographics
Creating catalog table: income_band
Creating catalog table: date_dim
Creating catalog table: web_site
Creating catalog table: promotion
Creating catalog table: …
```

[VL] gluten-it: Shorten table creation and query runner logs

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala

After renaming domain, there are some issues when running the MergeTree write on hdfs/s3 ut, ignore these ut first, will fix them after.
Issue #5229

[HOTFIX][CH] Ignore MergeTree write on hdfs/s3 ut

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/ClickhouseSnapshot.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
cpp-ch/local-engine/Operator/ExpandTransform.cpp
cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
cpp-ch/local-engine/Storages/StorageMergeTreeFactory.cpp

When testing querying and optimizing with TPCH 100 data with 30 core,
we may encounter core dump issues, this PR fixes it.
Also fix some potential memory leak.

[Gluten-5152][CH] fix core dump issues when running in parallel

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/MetricsApiImpl.scala

Fix `preProjection` to `rowConstruction` in `HashAggregateTransformerMetrics`.
N/A

[VL] Correct preProjection to rowConstruction for hash aggregate metrics

---

cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h

Exception handling logic for GenerateExec is missed, so error is not properly caught. We may move the exception handling to common place to avoid such case.
Issue query:
`spark.sql("SELECT explode(array(struct(1, 'a'), null))").collect`
Query sould fallback but fail with below error:
```
java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Code: NOT_IMPLEMENTED
Reason: NULL for struct type is not supported.
Function: literalsToRowVector
File: /var/git/gluten/cpp/velox/substrait/SubstraitToVeloxExpr.cc
Line: 494
Stack trace:
at io.glutenproject.vectorized.PlanEvaluatorJniWrapper.nativeValidateWithFailureReason(Native Method)
at io.glutenproject.vectorized.NativePlanEvaluator.doNativeValidateWithFailureReason(NativePlanEvaluator.java:54)
at …
```

[VL] Refactor native validation exception handling

---

ep/build-velox/src/get_velox.sh

This reverts commit 6ecbb31bdf05c12a2b419f540417ba4fa7ee3962.
We found openssl's static libs (e.g., libcrypto.a) are required when S3 is enabled. But seems they cannot be installed from package. Let's keep the code of building from source. We may need to put it into upstream velox.

[GLUTEN-5178][VL] Revert "[VL] Remove installing openssl in centos8 setup script (#5087)"

---

ep/build-velox/src/get_velox.sh

Due to the change made by https://github.com/facebookincubator/velox/commit/8a1d22556c8c5435218faed95227c7449550eafb, we need this patch to install yasm when enable_hdfs=ON.

[VL] Fix yasm installation

---

dev/package.sh

This PR aims to correct `.so` file path:
* /usr/lib64/libglog.so.0 -> /usr/local/lib64/libglog.so.1
* /usr/lib64/libgflags.so.2.2 -> /usr/local/lib64/libgflags.so.2.2
(Fixes: \#5264)
Build test in github action https://github.com/dcoliversun/gluten/actions/runs/8521763988

[GLUTEN-5264][VL] Correct libglog.so.0 & libglog.so.1 path when building third-lib package on centos-8

---

cpp/velox/compute/WholeStageResultIterator.cc
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

The 3 configs are missing in Gluten.
```
val COLUMNAR_VELOX_MAX_SPILL_RUN_ROWS =
buildConf("spark.gluten.sql.columnar.backend.velox.MaxSpillRunRows")
.internal()
.doc("The maximum row size of a single spill run")
.bytesConf(ByteUnit.BYTE)
.createWithDefaultString("12M")
val COLUMNAR_VELOX_MAX_SPILL_BYTES =
buildConf("spark.gluten.sql.columnar.backend.velox.MaxSpillBytes")
.internal()
.doc("The maximum file size of a query")
.bytesConf(ByteUnit.BYTE)
.createWithDefaultString("100G")
val COLUMNAR_VELOX_MAX_SPILL_WRITE_BUFFER_SIZE =
buildConf("spark.gluten.sql.columnar.backend.velox.spillWriteBufferSize")
.internal()
.doc("The maximum write buffer size")
.bytesConf(ByteUnit.BYTE)
.createWithDefaultString("4M")
```

[VL] Add 3 configs of spill

---

backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos8.scala

https://github.com/apache/incubator-gluten/pull/5265 fixed the `libglog.so.0` to `libglog.so.1`, but forgot to modify the load and link in `SharedLibraryLoaderCentos8`. This will cause the gluten to fail to start.
N/A

[VL] Fix load and link libglog.so.1 in SharedLibraryLoaderCentos8

---

.github/workflows/velox_docker.yml

This is a follow-up to https://github.com/apache/incubator-gluten/pull/4936

[VL] Re-enable some failed CI jobs

---

cpp/velox/substrait/SubstraitParser.cc
gluten-core/src/main/scala/org/apache/gluten/extension/RewriteCollect.scala

https://github.com/facebookincubator/velox/pull/9231 implemented a new `collect_list` aggregate function based on the semantics of Spark. Gluten can switch to use this new aggregate function without the need to rewrite the `collect_list` function in Spark.
Exists CI tests.

[VL] Use collect_list aggregate function in velox

---

.github/workflows/velox_nightly.yml
ep/build-velox/src/get_velox.sh

This PR proposes a nightly job to verify gluten build script from a clean environment.
1. Gluten's existing CI jobs are using docker images with pre-installed dependencies to accelerate validation process, but it is possible the code doesn't work in a clean environment.
E.g., Gluten changes velox's setup script by using "sed" command to match some code, then modifying it. The expected change sometimes doesn't happen due to upstream's code changes.
2. dev/package.sh is still necessary to some users, even though static build is recommended. It lacks CI verification. 
To avoid slowing down PR verification process, this job will be triggered only if the added yml file is changed or scheduled nightly test time comes.
N/A

[VL][CI] Add a nightly build job

---

gluten-core/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
gluten-delta/src/test/scala/org/apache/gluten/execution/VeloxDeltaSuite.scala
gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala

`isSparkVersionAtleast` is duplicated with testWithSpecifiedSparkVersion, should remove it.
CI/CD

[GLUTEN-5301] Remove unnecessary test util method 'isSparkVersionAtleast'

---

.github/workflows/velox_docker.yml
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/Memo.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/RasSuite.scala

Support adding RAS rule to reduce from plan tree to group. This could be useful when a rule just removes a unary node from the input plan.

[VL] RAS: Group reduction support

---

gluten-ras/common/src/main/scala/org/apache/gluten/ras/Ras.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/RasNode.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/best/BestFinder.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/best/GroupBasedBestFinder.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpPlanner.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpZipperAlgo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/exaustive/ExhaustivePlanner.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/ForwardMemoTable.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/Memo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/MemoTable.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/OutputFilter.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/OutputWizard.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/PathFinder.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/Pattern.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/rule/RuleApplier.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/rule/Shape.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/PropertySuite.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/RasSuite.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/RasSuiteBase.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/mock/MockMemoState.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/mock/MockRasPath.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/path/PathFinderSuite.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/path/WizardSuite.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/specific/DistributedSuite.scala

Group expansion is useful for writing simple enforcer rule that adds unary node (e.g., sort, exchange, c2r, r2c). Prior to this, we had to operate on at least one non-group node in rule. The fix adds support of group expansion so the path finding effort can be minimized during applying such rules.

[CORE][VL] RAS: Group expansion support

---

gluten-core/src/main/java/org/apache/gluten/memory/memtarget/TreeMemoryTargets.java
gluten-core/src/main/java/org/apache/gluten/substrait/rel/ExtensionTableNode.java
gluten-core/src/main/java/org/apache/gluten/substrait/rel/LocalFilesNode.java
gluten-data/src/main/java/org/apache/gluten/vectorized/ArrowWritableColumnVector.java

This PR aims to Mark overridden methods with `@Override` annotation. Meanwhile, once the method signature in the abstract class is changed, the implementation class will report a compile-time error immediately.
(Fixes: \#5316)
No need to add unit test. Need to ensure existing unit tests pass.

[GLUTEN-5316][CORE] Add @Override annotation for some methods

---

ep/build-velox/src/get_velox.sh

When building Velox, use the Alinux3 built-in gcc and python3
CI

[VL] Fix Alinux3 velox compilation exception

---

docs/get-started/Velox.md

Update the doc of Build Gluten with Velox Backend
The script buildbundle-veloxbe.sh will build 3.2.2, 3.3.1, 3.4.2, and 3.5.1, and the current description is not accurate.
(Fixes: \#5331)

[GLUTEN-5331]Update the doc of Build Gluten with Velox Backend #5331

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
cpp/velox/substrait/SubstraitToVeloxExpr.cc
docs/velox-backend-support-progress.md
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala

Add partial support of `filter` function for velox backend. This PR leverages existing `filter` function in velox which supports filter with lambda function<T, boolean>.
While [SPARK-28962](https://issues.apache.org/jira/browse/SPARK-28962) introduced support for lambda with index as argument (function<T, int, boolean>), it is not implemented in velox yet. To fully support the filter function, will add the implementation in velox.
UT added.

[GLUTEN-4039][VL] Add array filter function support

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/operators/functions/RegistrationAllFunctions.cc
cpp/velox/substrait/SubstraitParser.cc

`velox::functions::sparksql::hashMetadata()` was missing from previous rebase. Added UT.

[VL] Fix wrong result caused by missing metadata in hash registration 

---

gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpClusterAlgo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpPlanner.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/ForwardMemoTable.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/Memo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/MemoTable.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/Pattern.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/rule/Shape.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/vis/GraphvizVisualizer.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/rule/PatternSuite.scala

1. Allow rule pattern matching for node classes. This simplifies writing rules that matches on a tree in which developer is only interested in the node types.
2. Minor refactors to memo table, to hide the dummy group id logics (which starts from -1) from outer caller.

[CORE][VL] RAS: Pattern matching by node classes

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/ListenerApiImpl.scala
gluten-data/src/main/scala/org/apache/gluten/exec/Runtime.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
shims/common/src/main/scala/org/apache/spark/sql/internal/GlutenConfigUtil.scala

Allow parse config like `spark.gluten.sql.columnar.backend.velox.loadQuantum=8m`.

[CORE] Enhance gluten config parsing

---

gluten-ras/common/src/main/scala/org/apache/gluten/ras/Ras.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/RasCluster.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/RasNode.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/RasPlanner.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/best/BestFinder.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpClusterAlgo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpGroupAlgo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpPlanner.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/Memo.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/OutputFilter.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/rule/EnforcerRule.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/rule/RuleApplier.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/vis/GraphvizVisualizer.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/RasSuite.scala

Use DP cache to store the "explored" state for nodes in memo. Previously the exploration work for a single node may be duplicated since DpPlanner always re-explore a cluster exhaustively when it is not explored or gets changed.
After the patch, only enforcer rules will be applied exhaustively in the above condition.
Test shown ~10% faster in 9 way left-deep join reorder.

[CORE][VL] RAS: Avoid re-exploring explored nodes in DpPlanner

---

.github/workflows/velox_docker.yml
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxColumnarCacheSuite.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala
backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
gluten-delta/pom.xml
gluten-delta/src/test/scala/org/apache/gluten/execution/VeloxDeltaSuite.scala
gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala
gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxTPCHIcebergSuite.scala
gluten-ut/pom.xml
gluten-ut/spark35/pom.xml
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/test/src/test/scala/org/apache/gluten/expressions/GlutenExpressionMappingSuite.scala
pom.xml

Enable Spark 3.5 UTs in CI/CD with failed ones skipped.
CI/CD

[GLUTEN-5309][VL] Enable Spark3.5 UTs with failed ones excluded

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeOptimizeSuite.scala
cpp-ch/clickhouse.version
cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
cpp-ch/local-engine/Storages/CustomStorageMergeTree.h
cpp-ch/local-engine/Storages/Mergetree/MergeSparkMergeTreeTask.cpp
cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.cpp
cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.h
cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.cpp
cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.h
cpp-ch/local-engine/local_engine_jni.cpp

fix multiple bugs for optimizing tables on s3, including:
1. take care of metadata.gluten
2. race condition bug when two tasks are performing restoreMetadata on same executor at same time.
3. avoid creating tmp folder because it's problematic to rename on S3
(Fixes: \#5152)

[Gluten-5152][CH] fix bugs for optimizing tables on s3

---

cpp/velox/shuffle/VeloxShuffleWriter.cc

Flatten buffer doesn't update vector<stringbuffers>, so we can't use the vector to calculate the string buffer size. Instead to get the strlength from stringview and nullbit.

[VL] fix bug of string buffer size calculation in shuffle

---

backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
gluten-delta/src/test/scala/org/apache/gluten/execution/VeloxDeltaSuite.scala

Currently in the test method testWithSpecifiedSparkVersion, it uses SPARK_VERSION_SHORT for comparison directly which with value like 3.3.1, thus in test case like testWithSpecifiedSparkVersion(XXX, Some("3.3"), Some("3.3") will be ignored but it's expected to run. We'd better use major version 3.3 for comparison.
CI

[GLUTEN-5381] Refine testWithSpecifiedSparkVersion to compare major version

---

gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala

Enable some spark 35 uts
(Fixes: \#5341)
local manually run

[GLUTEN-5341][VL] Fix and enable some uts of spark 3.5

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.h
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

By default `PrestoVectorSerde` use millisecond precision for timestamp data. We observed timestamp prescision loseing when doing broadcast serialization. We need to fix this by setting `useLosslessTimestamp` for `PrestoVectorSerde`.
```
import org.apache.spark.sql.functions.expr
import org.apache.spark.sql.catalyst.expressions._
spark.range(0, 5).toDF("id").createOrReplaceTempView("target")
spark.range(0, 10)
.toDF("id")
.withColumn("timestampOne", expr("timestamp_micros(id)"))
.createOrReplaceTempView("source")
spark.sql("SELECT unix_micros(source.timestampOne) FROM source RIGHT OUTER JOIN target ON target.id = source.id").show(false)
```
Wrong result:
```
+-------------------------+
|unix_micros(timestampOne)|
+-------------------------+
|0                        |
|0 …
```

[VL] Fix timestamp precision loss in serializer

---

cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/Functions/SparkFunctionDivide.cpp
cpp-ch/local-engine/Functions/SparkFunctionDivide.h
cpp-ch/local-engine/Parser/scalar_function_parser/divide.cpp
cpp-ch/local-engine/tests/CMakeLists.txt
cpp-ch/local-engine/tests/benchmark_spark_divide_function.cpp

(Fixes: \#4483)
性能测试
端到端性能测试：test_tbl(a float, b float) 数据量6000W行，其中b取值全部为0 测试SQL: `select count(1) from test_tbl where a/b is NULL`， 测试三次：
该PR 优化前：1.381s 1.343s 1.35s;
该PR优化后：1.073s 1.127s 1.137s
通过开发完成的 benchmark_spark_divide_function.cpp 测试 新的divide 函数， 对比CH 的divide函数，以及过去使用FunctionParser的divide 的性能差异，如下
```
2024-01-22 16:51:29.252 <Warning> SignalHandler: LD_PRELOAD is not set, SignalHandler is disabled
2024-01-22T16:51:29+08:00
Running ./benchmark_local_engine
Run on (32 X 2100 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x16)
L1 Instruction 32 KiB (x16)
L2 Unified 1024 KiB (x16)
L3 Unified 11264 KiB (x2)
Load Average: 13.31, 24.04, 42.68 …
```

[GLUTEN-4483][CH]Improve divide

---

.github/workflows/build_bundle_package.yml
.github/workflows/velox_docker.yml
cpp/core/CMakeLists.txt
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/Options.h
cpp/core/shuffle/rss/RssPartitionWriter.cc
cpp/core/shuffle/rss/RssPartitionWriter.h
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/tests/VeloxShuffleWriterTest.cc
cpp/velox/utils/tests/VeloxShuffleWriterTestBase.h
dev/buildbundle-veloxbe.sh
dev/package-vcpkg.sh
dev/package.sh
docs/developers/HowTo.md
docs/developers/MicroBenchmarks.md
docs/developers/NewToGluten.md
docs/get-started/Velox.md
ep/build-clickhouse/src/package.sh
gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/gluten/uniffle/UniffleShuffleManager.java
package/pom.xml
pom.xml
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
tools/gluten-it/package/pom.xml
tools/gluten-te/centos/dockerfile-build
tools/gluten-te/ubuntu/dockerfile-build
tools/gluten-te/ubuntu/examples/buildhere-veloxbe-dev/scripts/all.sh
tools/gluten-te/ubuntu/examples/buildhere-veloxbe/run.sh

https://github.com/apache/incubator-gluten/issues/5335
integration test

[GLUTEN-5335][VL] Use common name for both celeborn and uniffle

---

gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenCachedTableSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetCompressionCodecPrecedenceSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala

(Fixes: https://github.com/apache/incubator-gluten/issues/5341)
GlutenParquetCompressionCodecPrecedenceSuite
GlutenParquetV1QuerySuite
GlutenParquetV2QuerySuite
GlutenJsonReadSchemaSuite
GlutenCoalesceShufflePartitionsSuite
GlutenInsertSuite
GlutenPartitionedWriteSuite
GlutenCachedTableSuite
manually test

[GLUTEN-5341][VL][Part 3] Fix and enable some uts of spark 3.5

---

gluten-core/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuiteBase.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuiteBase.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuiteBase.scala

This pr fix that when NativeScan contains two same columns in schema, it may throw Unexpected empty column when reading csv file.
(Fixes: \#5249)
This patch was tested by unit tests.

[GLUTEN-5249] [CH] fix throw Unexpected empty column when reading csv file

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/org/apache/gluten/execution/TopNTransformer.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
docs/developers/SubstraitModifications.md
gluten-core/src/main/java/org/apache/gluten/substrait/rel/RelBuilder.java
gluten-core/src/main/java/org/apache/gluten/substrait/rel/TopNNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/execution/LimitTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/execution/TakeOrderedAndProjectExecTransformer.scala

This PR adds a new physical operator TopNTransformer in Velox backend mapping to Velox's `core::TopNNode`.
By doing this, we can remove the hacky limit + sort coherent validation code, and the proxied executed plan used by `TakeOrderedAndProjectExecTransformer` will correctly map to the actual physical plan in Velox task.
This PR is a phase 1 because the actual Velox plan is still hidden by `TakeOrderedAndProjectExecTransformer` although limit+sort was replaced by top-n. We may eventually deprecate `TakeOrderedAndProjectExecTransformer` and expose more execution details to query planner.

[VL] Add independent operator for top-n processing in TakeOrderedAndProjectExecTransformer

---

backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/DeltaLog.scala
backends-clickhouse/src/main/delta-22/org/apache/spark/sql/delta/DeltaLog.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseConfig.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseDataSource.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeOptimizeSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseWholeStageTransformerSuite.scala
cpp-ch/local-engine/Storages/StorageMergeTreeFactory.cpp

Support writing and reading the mergetree data by the path based table:
write the mergetree data to the path directly:
```
sourceDF.write
.format("clickhouse")
.mode(SaveMode.Append)
.partitionBy("l_shipdate")
.option("clickhouse.orderByKey", "l_orderkey")
.option("clickhouse.primaryKey", "l_orderkey")
.option("clickhouse.lowCardKey", "l_returnflag,l_linestatus")
.save(dataPath)
```
read the mergetree data from the path directly:
```
val result = spark.read
.format("clickhouse")
.load(dataPath)
.count()
```
Close #5419.
(Fixes: #5419)

[GLUTEN-5419][CH] Support writing and reading the mergetree data by the path based table

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala

The Velox Window operator does not support range frames with literal values, such as 'RANGE BETWEEN CURRENT ROW AND 2 FOLLOWING'.  And it will throw the  following issue. This PR fallback window operator to vanilla spark for this case.
```
Reason: (4294967295 vs. 4294967295) Window frame of type RANGE does not support constant arguments
Expression: frameChannel != kConstantChannel
Function: operator()
File: /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/exec/Window.cpp
Line: 93
Stack trace:
```
Add new unit testing.

[VL] Fallback window operator when the range frame contain literal

---

gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenBloomFilterAggregateQuerySuite.scala

So far the case fails with error
```
org.apache.gluten.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxUserError
Reason: (1 vs. 0)
Expression: kBloomFilterV1 == version
Function: merge
File: ../.././velox/common/base/BloomFilter.h
Line: 67
Stack trace:
at org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
at org.apache.gluten.utils.IteratorCompleter.hasNext(Iterators.scala:69)
at org.apache.gluten.utils.PayloadCloser.hasNext(Iterators.scala:35)
at org.apache.gluten.utils.PipelineTimeAccumulator.hasNext(Iterators.scala:98)
at scala.collection.Iterator.isEmpty(Iterator.scala:387)
at …
```

[VL] Add a bad test case when bloom_filter_agg is fallen back while might_contain is not

---

gluten-ut/spark35/src/test/resources/sql-tests/inputs/subquery/scalar-subquery/scalar-subquery-select.sql
gluten-ut/spark35/src/test/resources/sql-tests/results/subquery/scalar-subquery/scalar-subquery-select.sql.out
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala

Currently in the gluten-ut of spark35, `scalar-subquery-select.sql` and `scalar-subquery-select.sql.out` were directly copied from spark34. However, these two files have changed in spark 3.5 version and cannot be used as-is from spark34. They need to be modified to match the spark 3.5 version.
N/A

[VL][UT] Fix scalar-subquery-select.sql in spark35

---

backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala

The buffer size may overflow before convert to Long.
We got an error in `RowToVeloxColumnarExec`,
```
io.glutenproject.exception.GlutenException: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Code: INVALID_STATE
Reason: Operator::getOutput failed for [operator: ValueStream, plan node ID: 0]: Error during calling Java code from native code: java.lang.IllegalArgumentException: the requested size must be non-negative
at io.glutenproject.shaded.org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:136)
at io.glutenproject.shaded.org.apache.arrow.memory.BaseAllocator.buffer(BaseAllocator.java:291)
at io.glutenproject.shaded.org.apache.arrow.memory.RootAllocator.buffer(RootAllocator.java:29)
at …
```

[CORE] Fix negative buffer size

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
cpp/velox/shuffle/VeloxShuffleWriter.cc

Remove the batch size limitation as Velox pipeline can produce large outputs against the configured batch size.
See issue https://github.com/apache/incubator-gluten/issues/5307 and PR #5326 
Velox issue: https://github.com/facebookincubator/velox/issues/9540

[VL] Remove batch size limit

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHNullableSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHOptimizeRuleBenchmark.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-core/src/main/scala/org/apache/gluten/expression/TimestampAddTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/extension/RewriteToDateExpresstionRule.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

If users query data through BI tools.
The BI tools may generate SQL similar to
```
to_date(
from_unixtime(
unix_timestamp(stringType, 'yyyyMMdd')
)
)
```
to convert string strings to dates.
Under ch backend, the StringType can be directly converted into DateType,
and the functions `from_unixtime` and `unix_timestamp` can be optimized here.
Optimized result is `to_date(stringType)` by use
```
spark.gluten.sql.rewrite.dateConversion=true
```
Notice:
When this parameter is turned on, there may be inconsistent results, because ch is compatible with a lot of date parsing, and when format is yyyy-MM-dd , spark returns null, but ch parses normally.
(Fixes: \#5405)
Test by ut
| OptimizeRuleBenchmark    | Best Time(ms) | Avg Time(ms) | Stdev(ms) | Rate(M/s) | Per Row(ns) | Relative |
| -------- | …

[GLUTEN-5405][CH] Add rewrite todate function

---

backends-velox/src/test/scala/org/apache/gluten/execution/VeloxColumnarCacheSuite.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala

[GLUTEN-5341] Fix some Spark 3.5 UTs

---

cpp-ch/local-engine/Storages/Mergetree/MergeSparkMergeTreeTask.cpp

Fix merge cause an error log when use mergetree
(Fixes: \#5457)
By `GlutenClickHouseMergeTreeOptimizeSuite`

[GLUTEN-5457][CH] Fix merge cause an error log when use mergetree

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh

```
d44a23e9d (upstream/main) Fix build failure in Meta internal test (#9556)
53f6bf761 Add execution mode enforcement (#9489)
09efd20ac Add reserved memory capacity pool in arbitrator (#9504)
c320923d4 Fix writer extended tests quality (#9552)
4ac07c8df Build fixes in fedora (clang 16) (#9550)
ea96074ef Make CallbackOnLastSignal more readable (#9548)
cb87bc8b3 Rename UnitLoaderTestToolsTests to UnitLoaderToolsTests (#9547)
d727293f2 Clear paged output stream buffers at flush time (#9546)
85393d519 Set up nightly run of window fuzzer (#9133)
52b80a7b5 Support UNKNOWN type in array_distinct (#9500)
c240cf36d Fix setup-centos8 script to use pip3.9 (#9536)
13d56e6a4 DwrfReader Refactor: DwrfReader accepts a UnitLoaderFactory (#9534)
61181013f Build boost without python in setup script …
```

[VL] Daily Update Velox Version (2024_04_21)

---

backends-clickhouse/src/main/java/org/apache/spark/sql/execution/datasources/CHDatasourceJniWrapper.java
backends-clickhouse/src/main/java/org/apache/spark/sql/execution/datasources/clickhouse/MergeTreePartFilterReturnedRange.java
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHTransformerApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/GlutenMergeTreePartition.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/TransformerApiImpl.scala
cpp-ch/local-engine/Common/MergeTreeTool.cpp
cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
cpp-ch/local-engine/Parser/MergeTreeRelParser.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
cpp-ch/local-engine/Storages/CustomStorageMergeTree.h
cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.h
cpp-ch/local-engine/local_engine_jni.cpp
gluten-core/src/main/java/org/apache/gluten/substrait/rel/ExtensionTableNode.java
gluten-core/src/main/scala/org/apache/gluten/backendsapi/TransformerApi.scala
gluten-core/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

By changing the parameter 
`spark.gluten.sql.columnar.backend.ch.runtime_settings.enabled_driver_filter_mergetree_index`
, you can control whether to filter the primary index on the driver side.
Why do this?
When the mergetree part is too large, dividing tasks by continuous ranges may cause some  tasks to be empty. If filtered on the driver side and then split, it can be guaranteed that each task has an actual task.
(Fixes: \#5225)
Test BY ui
</meta><style> td {white-space:nowrap;border:1px solid #dee0e3;font-size:10pt;font-style:normal;font-weight:normal;vertical-align:middle;word-break:normal;word-wrap:normal;}</style><byte-sheet-html-origin data-id="1713757667107" data-version="4" data-is-embed="true" data-grid-line-hidden="false" data-copy-type="col">
name | 改动前 | 改动后 | DIFF | DIFF
-- …

[GLUTEN-5225][CH] Add mergetree index filter on driver

---

backends-clickhouse/src/main/java/org/apache/gluten/vectorized/CHShuffleSplitterJniWrapper.java
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseColumnarSortShuffleAQESuite.scala
cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
cpp-ch/local-engine/Shuffle/CachedShuffleWriter.h
cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
cpp-ch/local-engine/Shuffle/PartitionWriter.h
cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
cpp-ch/local-engine/Shuffle/SelectorBuilder.h
cpp-ch/local-engine/Shuffle/ShuffleSplitter.h
cpp-ch/local-engine/Shuffle/SortedPartitionDataMerger.cpp
cpp-ch/local-engine/Shuffle/SortedPartitionDataMerger.h
cpp-ch/local-engine/local_engine_jni.cpp
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

add external sort shuffle writer
unit tests
Three new configurations are introduced
```
spark.gluten.sql.columnar.backend.ch.maxSortBufferSize
```
The maximum size of sort shuffle buffer in CH backend.
```
spark.gluten.sql.columnar.backend.ch.spillFirstlyBeforeStop
```
Whether to spill the sort buffers before stopping the shuffle writer.
```
spark.gluten.sql.columnar.backend.ch.forceSortShuffle
```
Whether to force to use sort shuffle in CH backend. Sort shuffle disabled by default

[CH]feat: Support external sort shuffle, reduce shuffle memory usage when the number of partitions is high

---

backends-velox/src/main/java/org/apache/spark/util/sketch/VeloxBloomFilter.java
backends-velox/src/main/java/org/apache/spark/util/sketch/VeloxBloomFilterJniWrapper.java
backends-velox/src/main/scala/org/apache/spark/sql/catalyst/BloomFilterMightContainJointRewriteRule.scala
backends-velox/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/VeloxBloomFilterAggregate.scala
backends-velox/src/test/java/org/apache/spark/util/sketch/VeloxBloomFilterTest.java
cpp/velox/jni/VeloxJniWrapper.cc
gluten-data/src/main/java/org/apache/gluten/exec/RuntimeAware.java
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenBloomFilterAggregateQuerySuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenBloomFilterAggregateQuerySuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenBloomFilterAggregateQuerySuite.scala

Support fallback row-based processing of agg function `velox_bloom_filter_agg`. Which means we will always use Velox's bloom-filter implementation not matter the resident operators of bloom filter functions are fallen back / disabled or not, so long as Gluten plugin + Velox backend is enabled. So we will get rid of all possible bloom-filter compatibility issues in Velox backend once and for all.

[VL] Support fallback processing of velox_bloom_filter_agg

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/ListenerApiImpl.scala
backends-velox/src/test/java/org/apache/spark/util/sketch/VeloxBloomFilterTest.java
gluten-core/src/main/java/org/apache/gluten/vectorized/JniWorkspace.java
gluten-core/src/main/scala/org/apache/spark/util/SparkDirectoryUtil.scala
gluten-data/src/main/java/org/apache/gluten/vectorized/NativePlanEvaluator.java
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala

This is a minor fix to let VeloxBloomFilterTest use regular code path to get JniWorkspace, with some minor refactors.

[VL] Avoid using debug instance of JniWorkspace in VeloxBloomFilterTest

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala

There is a CI error related to https://github.com/apache/incubator-gluten/pull/5482 but was not detected since CH CI was broken at that time. The patch fixes the error..

[CH] Fix CH CI

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/SparkPlanExecApiImpl.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarWriteFilesExec.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/spark/util/SparkDirectoryUtil.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenV1WriteCommandSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenV1WriteCommandSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala

Currently in code, class `VeloxColumnarWriteFilesExec` extends case class `WriteFilesExec` which is bad practice speaking of Scala.

[VL] Fix case-class inheritance for VeloxColumnarWriteFilesExec 

---

backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala

UnsafeProjection is only constructed once when converting rows to columns;
If the schema contains fields structured as maps, constructing UnsafeProjection will be time-consuming.
[(Fixes: \#5502)](https://github.com/apache/incubator-gluten/issues/5502)
through exist uts

[GLUTEN-5502][VL] UnsafeProjection is only constructed once when converting rows to columns

---

gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenHigherOrderFunctionsSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenHigherOrderFunctionsSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenHigherOrderFunctionsSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenHigherOrderFunctionsSuite.scala

[GLUTEN-5499][VL] Enable HighOrderFunctionSuites

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
gluten-core/src/main/java/org/apache/gluten/substrait/rel/RelBuilder.java
gluten-core/src/main/java/org/apache/gluten/substrait/rel/WindowGroupLimitRelNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/org/apache/gluten/execution/WindowGroupLimitExecTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/PullOutPreProject.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/RewriteSparkPlanRulesManager.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformSingleNode.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
shims/common/src/main/scala/org/apache/spark/sql/execution/datasources/WindowGroupLimitExecShim.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/window/WindowGroupLimitExecShim.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/window/WindowGroupLimitExecShim.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/window/WindowGroupLimitExecShim.scala
shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
shims/spark35/src/main/scala/org/apache/spark/sql/execution/window/WindowGroupLimitExecShim.scala

There is a new operator named WindowGroupLimitExec introduced in spark 3.5 for optimizing window with rank like function with filter on it. https://github.com/apache/spark/pull/38799. This PR maps this operator with row number function to TopNRowNumberNode in velox. Currently velox doesn't support TopN for rank and dense_rank. There is an issue opened in velox for it https://github.com/facebookincubator/velox/discussions/9404. Once that support gets added in velox this new operator in Gluten can be extended to support those.
(Partially Fixes: \#4836)
Added new UT

[GLUTEN-4836][VL]Add support for WindowGroupLimitExec in gluten

---

.github/workflows/velox_docker.yml
backends-velox/src/main/java/org/apache/gluten/utils/VeloxBloomFilter.java
backends-velox/src/main/java/org/apache/gluten/utils/VeloxBloomFilterJniWrapper.java
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/expression/VeloxBloomFilterMightContain.scala
backends-velox/src/main/scala/org/apache/gluten/expression/aggregate/VeloxBloomFilterAggregate.scala
backends-velox/src/main/scala/org/apache/gluten/extension/BloomFilterMightContainJointRewriteRule.scala
backends-velox/src/test/java/org/apache/gluten/utils/VeloxBloomFilterTest.java
cpp/velox/jni/VeloxJniWrapper.cc
cpp/velox/symbols.map

As title, add a CI job for SF30, Spark 3.4. This could be able to test against possible regressions on larger scale factors and newer Spark versions, e.g., issues related to SHJ, or runtime filter, etc.

[VL] CI: Add TPC-H / TPC-DS job at SF30 with Spark 3.4

---

.github/workflows/velox_docker_cache.yml

1. Do not cancel cache job when new job are submitted. Which may cause a job that is about to finish to be aborted and renewed so waste time.
2. Check existing cache before building cache. Build only when it's not built yet.

[VL] CI: Minor optimizations for cache build settings

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHBucketSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
cpp-ch/local-engine/Functions/SparkFunctionRoundHalfUp.h
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala

[CH] Fix the incorrect transformer for the round function with the decimal data type.
When transforming the round function with the decimal data type, it only transformers the `child` expression, but missing the `scale` expression, which will lead to the incorrect results when executing the `round(decimal_data, x)`.
Close #5512.
(Fixes: #5512)

[GLUTEN-5512][CH] Fix the incorrect transformer for the round function with the decimal data type

---

cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
cpp-ch/local-engine/Shuffle/CachedShuffleWriter.h
cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
cpp-ch/local-engine/Shuffle/PartitionWriter.h
gluten-celeborn/clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseRSSColumnarSortShuffleAQESuite.scala

now we can use external sort shuffle with celeborn, relate to #5279 
new configuration
`spark.gluten.sql.columnar.backend.ch.runtime_config.spill_memory_overhead`, type int, default value 50MB
The new configuration item is used to control the amount of additional memory overhead when spilling. There are some stages where it is not allowed to enter the spill again. Need to prevent this from happening by adding a certain amount of spill_memory_overhead.
unit tests

[CH] Support celeborn on external sort shuffle

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

(Fixes: \#4914)
`func_parser->getCHFunctionName()` still gets function name from `SCALAR_FUNCTIONS` and will parse error when get function implemented by `FunctionParser`.
Add UT

[GLUTEN-4914][CH][FOLLOWUP] Fix exceptions in ASTParser

---

backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala

Currently, there is no verification on whether used native write in VeloxParquetWriteForHiveSuite on spark3.4+, this PR improves it.
VeloxParquetWriteForHiveSuite case

[VL] Improve checkNativeWrite in VeloxParquetWriteForHiveSuite

---

docs/velox-backend-limitations.md
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenJsonFunctionsSuite.scala

Fixes get_json_object test introduced in spark 3.5 to check compatibility with hive. * character is not supported in velox in json queries.
(Fixes: \#5341)
Ran in local

[GLUTEN-5341][VL] Fix SPARK-42782: Hive compatibility check for get_json_object

---

cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/tests/CMakeLists.txt
cpp/velox/tests/VeloxColumnarBatchTest.cc

The children of input RowVector, can reference same BaseVector before and after flattening. e.g. `select explode(a), a from ...`, which a is of map type  will output 3 columns: col_0: a.mapKeys col_1: a.mapValues and col_2: a. In this case, col_0/co_1 is referencing the same BaseVector as the mapKeys/mapValues in col_2. Resizing col_0/col_1 will cause expected failure in accessing col_2.

[VL] Use slice instead of resize in ensureFlattened

---

backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
cpp/velox/jni/JniUdf.cc
cpp/velox/udf/Udaf.h
cpp/velox/udf/UdfLoader.cc
cpp/velox/udf/UdfLoader.h
cpp/velox/udf/examples/MyUDF.cc
shims/spark32/src/main/scala/org/apache/spark/sql/catalyst/types/DataTypeUtils.scala
shims/spark33/src/main/scala/org/apache/spark/sql/catalyst/types/DataTypeUtils.scala
shims/spark34/src/main/scala/org/apache/spark/sql/catalyst/types/DataTypeUtils.scala

Fixes: https://github.com/apache/incubator-gluten/issues/5197
Reorganize the code structure of "MyUDF.cc" to be more friendly to large language model code generation, making it easier to interpret and generate related code snippets. This is experimental and the final goal is to train the LLM to generate structured code based on very simple description, e.g.
```
// name: testudf
// signatures:
//     integer -> date
//     bigint, [integer,] ... -> date
//     date, [bigint,] ... -> date
//     integer, integer, bigint -> date
//     date, integer -> integer
//     date, bigint, integer, [integer,] ... -> bigint
// type: VectorFunction and VectorFunction with variable arity
```

[VL] UDF: Support variable arity in function sigatures

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
cpp/core/jni/JniWrapper.cc
gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala

Currently, the iterator is designed to close once the hasNext() method returns false. Therefore, if `hasNext()` is called a second time, it will throw exception [here](https://github.com/apache/incubator-gluten/blob/8ade7a9cb50910021a2c0cb6977aaaeb9a17b5ce/cpp/core/jni/JniWrapper.cc#L452). This PR adds a `protectInvocationFlow()` method to ensure that the iterator's `hasNext()` can be safely called multiple times without causing an exception.
locally test.

[VL] [BUG fix] Make the hasNext method can be called multi times

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxParquetDataTypeValidationSuite.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

To resolve #5547. 
Velox does not currently support read int64 timestamp in parquet files, so add config to force fallback for parquet timestamp type scan, default false.
Unit test.

[GLUTEN-5547][VL] Add config to force fallback scan for timestamp type

---

backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformSingleNode.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/ConditionedRule.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/ImplementAggregate.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/ImplementFilter.scala
gluten-core/src/main/scala/org/apache/gluten/planner/cost/GlutenCostModel.scala

RAS planner doesn't need tag to mark whether a vanilla Spark plan is offload-able . It just does every essential checks whenever it tries to generate offloaded plan.
The patch does some optimizations to code to remove AddTransformHintRule from EnumeratedApplier and leave the pre-validation work to RAS planner.

[VL] RAS: Remove AddTransformHintRule route from EnumeratedApplier

---

pom.xml
shims/pom.xml

Fix issue #5525
Run following command locally:
- `mvn clean`
- `mvn clean install -DskipTests`
- `mvn clean -Pbackends-velox -DskipTests`

[GLUTEN-5525][BUILD] Run `mvn clean` fails if a spark profile is not specified

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala

This is simply a follow-up fix for https://github.com/apache/incubator-gluten/pull/5431. For constant preceding, Spark will combine the original literal bound with `Minus` expression. So we need to check whether it's foldable instead of checking whether it's literal.
New UT and existing UTs.

[VL] Fix literal bound fallback for window range frame

---

cpp/compile.sh

Use different commands in `incubator-gluten/cpp/compile.sh` script to get the number of available processing unit in MacOS
(Fixes: \#5559)
I test this in my MacOS computer and it works fine.

[GLUTEN-5559][VL] Fix threads number setting for building gluten cpp on MacOS

---

ep/build-velox/src/get_velox.sh

Fixes: #5565
Manually compared velox_ep/scripts/setup-macos.sh before and after this PR:

[GLUTEN-5565][VL][BUILD] Fix setup-macos.sh: folly is installed twice

---

backends-clickhouse/pom.xml
gluten-celeborn/clickhouse/pom.xml
pom.xml

The `delta.package.name` of Spark3.5 is `delta-spark`, we should use property to specify the delta artifactId.
Pass `mvn spotless:apply -Pspark-3.2,spark-3.3,spark-3.4,spark-3.5 -Pbackends-velox -Pbackends-clickhouse -Prss -Pspark-ut`

[CORE] Fix delta.package.name error

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala

Vanilla Spark build HashRelation at driver side, so it is build keys sensitive. But we broadcast byte array and build HashRelation at executor side, the build keys are actually meaningless for the broadcast value.
This pr erases the HashedRelationBroadcastMode build keys when do canonicalize. This change allows us reuse broadcast exchange for different build keys with same table.
add test

[CORE] Reuse broadcast exchange for different build keys with same table

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc

Fix https://github.com/apache/incubator-gluten/issues/5534
Calculating the maximum number of rows (maxBatchSize) in a batch based on the memory limit of the previous batch and the number of pre-allocated rows. If row count of current batch larger than maxBatchSize, slice it into small ones

fix shuffle OOM if input batch is extremely large

---

docs/developers/docker_centos7.md

Build error:
```
--2024-04-29 09:21:36--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.191.158, 104.16.32.241, 2606:4700::6810:bf9e, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.191.158|:443... connected.
ERROR: cannot verify repo.anaconda.com's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=E1':
Issued certificate has expired.
To connect to repo.anaconda.com insecurely, use `--no-check-certificate'.
```
Local test.
Execute within container：wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

[VL][DOC] Fix certificate expired when build on CentOS 7

---

backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetReadSuite.scala
shims/common/src/main/scala/org/apache/spark/sql/internal/GlutenConfigUtil.scala

`OptionalConfigEntry.readFrom(reader).toString` would return `Some(xxx)` rather than `xxx`. It affects the gluten config which use `createOptional`.
manually test

[CORE] Fix gluten createOptional config contains Some

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
gluten-core/src/main/scala/org/apache/gluten/execution/GenerateExecTransformerBase.scala

After adding the pull-out pre project for `GenerateExecTransformer`, the child expression name can be changed. Therefore should use exprId while matching the output from child.

[GLUTEN-5586] Fix multiple generate functions failure

---

tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Parameterized.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Queries.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/QueriesCompare.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/TableFormatter.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/QueryRunner.scala

`gluten-it`'s test report now includes field `planning time` for measuring planner performance.
E.g,
Before:
```
Test report: 
Summary: 5 out of 5 queries passed. 
|       Query ID|     Was Passed|            Expected Row Count|              Actual Row Count|  Baseline Query Time (Millis)|           Query Time (Millis)|          Query Time Variation|
|             q1|           true|                             4|                             4|                        102925|                          9510|                       982.28%|
|             q2|           true|                           100|                           100|                         10414|                          5918|                        75.97%|
|             q3|           true|                            10| …
```

[VL] CI: Gluten-it: Print planning time as well as execution time in test report

---

cpp/velox/memory/VeloxMemoryManager.cc

[GLUTEN-5611] [VL] Avoid trigger Spark memory listener when native memory request can be handled internally

---

gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenBitmapExpressionsQuerySuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenEmptyInSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenRuntimeNullChecksV2Writes.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenTableOptionsConstantFoldingSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/connector/GlutenDeltaBasedMergeIntoTableSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/connector/GlutenDeltaBasedMergeIntoTableUpdateAsDeleteAndInsertSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/connector/GlutenDeltaBasedUpdateAsDeleteAndInsertTableSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/connector/GlutenDeltaBasedUpdateTableSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/connector/GlutenGroupBasedMergeIntoTableSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/GlutenRemoveRedundantWindowGroupLimitsSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenFileSourceCustomMetadataStructSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenTableLocationSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFileMetadataStructRowIndexSuite.scala

In Spark 3.5, there are some new added UTs vs Spark3.4 which haven't been added in Gluten yet. In this PR, we ported the ones under spark/sql but excluding folders like streaming, execution/command, execution/benchmark.
(Fixes: \#5622)
CI

[GLUTEN-5622] Add new added Spark3.5 UTs in Gluten

---

backends-velox/src/test/scala/org/apache/gluten/execution/FallbackSuite.scala

With whole stage fallback enabled, we can manage to create a plan (AE=on) like:
```
Exchange SinglePartition, ENSURE_REQUIREMENTS, [plan_id=393]
+- HashAggregate(keys=[], functions=[partial_sum(ele#42L)], output=[sum#48L])
+- ObjectHashAggregate(keys=[c1#14], functions=[collect_list(c2#15L, 0, 0)], output=[ele#42L])
+- VeloxColumnarToRowExec
+- AQEShuffleRead coalesced
+- ShuffleQueryStage 0
+- ColumnarExchange hashpartitioning(c1#14, 5), ENSURE_REQUIREMENTS, [c1#14, buf#50], [plan_id=315], [id=#315], [OUTPUT] List(c1:IntegerType, buf:ArrayType(LongType,false)), [OUTPUT] List(c1:IntegerType, buf:ArrayType(LongType,false))
+- ^(3) ProjectExecTransformer [hash(c1#14, 42) AS hash_partition_key#56, c1#14, buf#50]
+- ^(3) FlushableHashAggregateTransformer(keys=[c1#14], …
```

[VL] Add a bad test case that final aggregate of collect_list is fallen back while partial aggregate is not

---

.github/workflows/code_style.yml
CONTRIBUTING.md
dev/formatcppcode.sh
docs/developers/CppCodingStyle.md
docs/developers/NewToGluten.md

~clang-format-12 is recommended to use according to Gluten doc, but the version used by CI is 15.
See:
https://github.com/apache/incubator-gluten/blob/main/dev/formatcppcode.sh~
Fix inconsistency in script and doc.

[VL] Fix clang-format version

---

cpp/core/jni/JniCommon.h
cpp/core/memory/AllocationListener.h
cpp/core/memory/HbwAllocator.cc
cpp/core/memory/HbwAllocator.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/velox/memory/VeloxMemoryManager.cc

After this PR, the peak memory usage decreased from 1.1G to 816M, and add ListenableMemoryAllocator into memory usage dump.
```
24/05/07 16:56:14 WARN [Executor task launch worker for task 1.0 in stage 7.0 (TID 1025)] NativeMemoryManager: About to release memory manager, usage dump:
ShuffleWriter:                    Current used bytes: 1024.0 KiB, peak bytes:  212.3 MiB
+- ShuffleWriter_root:            Current used bytes:      0.0 B, peak bytes: 1024.0 KiB
|  \- ShuffleWriter_default_leaf: Current used bytes:      0.0 B, peak bytes:   1408.0 B
\- gluten_allocator:              Current used bytes:      0.0 B, peak bytes:  211.3 MiB
```
(Fixes: \#5630)

[GLUTEN-5630][VL] Decrease peak memory by taking freeBytes into account 

---

cpp/velox/substrait/VeloxSubstraitSignature.cc
cpp/velox/tests/VeloxSubstraitSignatureTest.cc

There is a bug occurs when parsing Substrait nested complex type signature.
For example:
Signature:
```
struct<fp32,struct<struct<i8,dec<19,2>,list<i32>,map<i16,i32>>>>
```
Error:
```
unknown file: Failure
C++ exception with description "Exception: VeloxUserError
Error Code: UNSUPPORTED
Reason: Substrait type signature conversion to Velox type not supported for i32>,map<i16,i32>>.
```
The bug also causes **unexpected fallbacks** on some operators that are actually capable to offload, for example when delta lake initializes its metadata queries, the aggregate operator may be fallen back due to this issue:
```
ColumnarExchange SinglePartition, ENSURE_REQUIREMENTS, [plan_id=299], [id=#299], [OUTPUT] List(set:ArrayType(StructType(StructField(appId,StringType,true),StructFiel …
```

[VL] Substrait-to-Velox: Support nested complex type signature parsing

---

docs/get-started/Work-with-pyspark.ipynb

Removing the config `spark.gluten.sql.columnar.backend.lib` from sample notebook since it is no longer used to set the backend engine.

[VL][Doc] Remove spark.gluten.sql.columnar.backend.lib config from example

---

backends-velox/src/test/scala/org/apache/gluten/execution/VeloxLiteralSuite.scala
cpp/velox/substrait/SubstraitToVeloxExpr.cc

Fixes: #5662 
UT added.
Without the fix, the new added UTs would fail as:
```
== Results ==
!== Correct Answer - 1 ==                            == Gluten Answer - 1 ==
struct<>                                            struct<>
== Results ==
!== Correct Answer - 1 ==              == Gluten Answer - 1 ==
struct<>                              struct<>
```

[GLUTEN-5662][VL] Fix literal array conversion with nested empty array/map ahead of non-empty

---

ep/build-velox/src/get_velox.sh

Use the default pip3.6 from the alinux3 in the build of velox
CI

[VL] Use the default pip3.6 from the alinux3 in the build of velox

---

cpp/velox/memory/VeloxMemoryManager.cc

Connector IO thread executor is enabled by default and be used in DirectBufferedInput, which bring concurrent memory request issue when do arbitration.
One possible scenario: 
T1: thread 1 enter arbitration, get freeBytes and find it's ok to grow without capacity increment.
T2: thread 2 enter maybeIncrementReservation and increase reservationBytes with a small bytes requests successfully.
T3: thread 1 invoke mempool#grow() but current freeBytes is insufficient.
Solution:
try grow without capacity increment first, if failed, then shrink pool to prevent following memory request and do real grow. 
(Fixes: \#5673)

[GLUTEN-5673][VL] Fix arbitrator grow logic when exist concurrent memory request

---

ep/build-velox/src/modify_arrow.patch
gluten-data/src/main/scala/org/apache/gluten/utils/ArrowUtil.scala

Before this patch, will throw exception
```
/__w/incubator-gluten/incubator-gluten/ep/build-velox/build/velox_ep/_build/release/third_party/arrow_ep/src/arrow_ep/java/dataset/src/main/cpp/jni_util.cc:79: Failed to update reservation while freeing bytes: JNIEnv was not attached to current thread
```
Fixed by arrow patch `AttachCurrentThread`

[GLUTEN-5414] [VL] Fix and enable arrow native memory pool track in CSV scan

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h

Fix the bug founded in issue (Fixes: \#5682)
Add ut to cover the change!

[GLUTEN-5682][VL] Fix incorrect result when isNull & isNotNull coexist in filter

---

gluten-data/pom.xml

Remove duplicated arrow-dataset dependency from gluten-data/pom.xml
Passed current CI

[BUILD] Remove duplicated arrow-dataset dependency from gluten-data/pom.xml

---

backends-clickhouse/src/main/scala/org/apache/spark/shuffle/HashPartitioningWrapper.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/metadata/AddFileTags.scala
pom.xml

This uses Scala linter `wartremover` and its maven plugin. And I wrote a custom wart for this.
The jar including the custom wart:
https://central.sonatype.com/artifact/io.github.zhztheplayer.scalawarts/scalawarts
Source code:
https://github.com/zhztheplayer/scalawarts
Wartremover:
https://github.com/wartremover/wartremover
After this patch, once a class tends to inherit a case class, compiler will raise an error:
```
error: [wartremover:InheritFromCaseClass] case class is not inheritable: MyClass is trying to inherit List(class CaseClazz)
```
To suppress that error, add an annotation before the class definition:
```
@SuppressWarnings(Array("io.github.zhztheplayer.scalawarts.InheritFromCaseClass"))
class MyClass extends CaseClazz{...}
```
In the other hand, I'll try upstreaming the code of …

[CORE] Add a compilation-time check to forbid case-class inheritance 

---

gluten-data/src/main/java/org/apache/gluten/vectorized/ShuffleReaderMetrics.java

(Fixes: \#5739)
Fix ShuffleReaderMetrics deserializeTime always is zero
no need

[GLUTEN-5739][VL] Fix ShuffleReaderMetrics deserializeTime always is zero

---

cpp/core/shuffle/rss/RssPartitionWriter.cc

Change the logic to calculate the shuffle write time. Shuffle write time is currently composed of splitResult.getTotalWriteTime + splitResult.getTotalPushTime
And TotalWriteTime in the current implementation is added twice into the final shuffle write time metric. 
(Fixes: \#5731)
E2e manual test.

[GLUTEN-5731][CORE] Fix the logic to calculate rss shuffle write time

---

cpp/core/config/GlutenConfig.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/config/VeloxConfig.h

Move velox related configs to VeloxConfig.h, thus these configs can be used by include VeloxConfig.h

[VL] Move velox related configs to VeloxConfig.h

---

gluten-core/src/main/scala/org/apache/gluten/extension/StrategyOverrides.scala

`ExtractEquiJoinKeysShim.unapply` calls `ExtractEquiJoinKeys`, `ExtractEquiJoinKeys` determines that there must have an equal condition.
Unnecessary.

[CORE] Remove wrong comment for JoinSelectionOverrides

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/execution/python/ColumnarArrowEvalPythonExec.scala
backends-velox/src/test/scala/org/apache/gluten/execution/python/ArrowEvalPythonExecSuite.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/rewrite/PullOutPreProject.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/rewrite/RewriteSparkPlanRulesManager.scala

Add preprojection support for ArrowEvalPythonExec
Fixes: \#5696)
New UTs added

[GLUTEN-5696] Add preprojection support for ArrowEvalPythonExec

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/datasource/ArrowCSVFileFormat.scala
backends-velox/src/main/scala/org/apache/gluten/datasource/ArrowConvertorRule.scala
backends-velox/src/main/scala/org/apache/gluten/datasource/v2/ArrowCSVPartitionReaderFactory.scala
backends-velox/src/main/scala/org/apache/gluten/datasource/v2/ArrowCSVScan.scala
backends-velox/src/main/scala/org/apache/gluten/datasource/v2/ArrowCSVScanBuilder.scala
backends-velox/src/main/scala/org/apache/gluten/datasource/v2/ArrowCSVTable.scala
backends-velox/src/main/scala/org/apache/gluten/execution/datasource/v2/ArrowBatchScanExec.scala
backends-velox/src/main/scala/org/apache/gluten/extension/ArrowScanReplaceRule.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
gluten-data/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatches.java
gluten-data/src/main/scala/org/apache/gluten/utils/ArrowUtil.scala
gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/csv/GlutenCSVSuite.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
shims/spark35/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala

Add SparkPlan `ArrowBatchScanExec` to let other rule know it is outputNativeColumnarSparkCompatibleData to not introduce  VeloxColumnarToRow, and `isVanillaOp` return false to not introduce extra c2r and r2c.
Implement Spark datasource V2 interfaces such as `FileScan`.
Plan:
```
VeloxColumnarToRowExec
+- ^(2) FilterExecTransformer (isnotnull(Name#139) AND (Name#139 = Peter))
+- ^(2) InputIteratorTransformer[Name#139, Language#140]
+- ^(2) InputAdapter
+- ^(2) ArrowBatchScan arrowcsv file:/mnt/DP_disk1/code/incubator-gluten/backends-velox/target/scala-2.12/test-classes/datasource/csv/student.csv[Name#139, Language#140] ArrowCSVScan DataFilters: [], Format: arrowcsv, Location: InMemoryFileIndex(1 paths)[file:/mnt/DP_disk1/code/incubator-gluten/backends-velox/target/scala-2..., …
```

[GLUTEN-5414] [VL] Support datasource v2 scan csv

---

dev/buildbundle-veloxbe.sh
dev/builddeps-veloxbe.sh
docs/get-started/build-guide.md

Support a new option: --spark_version for buildbundle-veloxbe.sh and builddeps-veloxbe.sh. By default the version is `ALL` which keeps the same behaviour as now.

[GLUTEN-5777][VL] Supporting specify spark version when build

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/VeloxRuntime.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/operators/writer/VeloxParquetDatasourceABFS.h
cpp/velox/operators/writer/VeloxParquetDatasourceHDFS.h
cpp/velox/operators/writer/VeloxParquetDatasourceS3.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/utils/ConfigExtractor.cc
cpp/velox/utils/ConfigExtractor.h

Currently, in the Gluten code, once `velox::core::MemConfigMutable` is initialized, the key-value pairs are not modified anymore. This scenario is better suited for using `velox::core::MemConfig`. `MemConfigMutable` is suitable for scenarios where key-value pairs are modified by multiple threads.
existed ci

[VL] Use MemConfig to replace MemConfigMutable, which makes the code cleaner and may also lead to some performance improvements.

---

cpp/velox/shuffle/VeloxSortBasedShuffleWriter.cc
cpp/velox/shuffle/VeloxSortBasedShuffleWriter.h

A follow-up PR of https://github.com/apache/incubator-gluten/pull/5675
Remove the mapping from input vector to row index ranges. The process can be done in one loop.
Also addresses some code clean up.

[VL] Refine evict logic in sort shuffle writer

---

cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
ep/build-velox/src/get_velox.sh

```
4bde4b03e by Masha Basmanova, Do not return dictionaries with large alphabet from Unnest (#9843)
adb47bc1c by xiaoxmeng, Let driver go off-thread waiting for memory arbitration (#9766)
2b94547ea by xiaoxmeng, Optimize the shared leaf memory pool locking (#9830)
79956c2a4 by yingsu00, Fix the issue that the splits cannot be skipped for some special case (#9707)
acb7e4235 by Giuseppe Ottaviano, Implement unlocked fast path in MemoryManager::getInstance() (#9808)
954f53c30 by Masha Basmanova, Refactor Unnest operator for readability (#9841)
2c2f8e444 by aditi-pandit, Compute updateMode HiveWriterParameter only once for the HiveDataSink (#9812)
e2c0014b2 by yanngyoung, Remove allowInputShuffle_ flag in AggregationTestBase::testReadFromFiles (#9482)
7b8e41ffc …
```

[VL] Daily Update Velox Version (2024_05_17)

---

.asf.yaml

`required_signatures:true` blocks a couple of PRs from merging. Let's disable this rule at the moment, until we come up with a BKM about signing PR commits.

[CORE] ASF repo config: Set required_signatures to false

---

cpp-ch/local-engine/local_engine_jni.cpp
gluten-core/src/main/java/org/apache/gluten/vectorized/JniLibLoader.java

(Fixes: \#5741 #5744)
https://github.com/apache/incubator-gluten/blob/10182a52d409cb659169cbfe1d7f1869d9205dce/gluten-core/src/main/java/org/apache/gluten/vectorized/JniLibLoader.java#L131
When running on yarn cluster, `libPath` is a symbolic link existed on the working directory of yarn container, like `/data5/hadoop/yarn/local/usercache/xumingyong/appcache/application_1710462985812_777680/container_e57_1710462985812_777680_01_000321/./libch.so`. It's an `APPLICATION` level resource and will be removed when container exits. So it may have been removed here when reading real path, which causes `Files.isSymbolicLink(Paths.get(libPath))` return false in that the library (e.g. libch.so) cannot be unload and the method `JNI_OnUnload` cannot be invoked (which casuses core dump). As a …

[GLUTEN-5741][CH] Fix core dump when executor exits

---

backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/execution/HashAggregateExecTransformer.scala
backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
gluten-core/src/main/scala/org/apache/gluten/expression/AggregateFunctionsBuilder.scala
shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala

Unify the special aggregate function name mapping to reduce the duplicated code, e.g., fisrt/last with ignoreNulls.
Pass CI

[CORE] Unify the aggregate function name mapping

---

cpp/core/config/GlutenConfig.h
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/memory/AllocationListener.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/velox/benchmarks/common/BenchmarkUtils.cc
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/memory/VeloxMemoryManager.h
cpp/velox/tests/CMakeLists.txt
cpp/velox/tests/FunctionTest.cc
cpp/velox/tests/MemoryManagerTest.cc
cpp/velox/tests/Substrait2VeloxPlanConversionTest.cc
cpp/velox/tests/Substrait2VeloxPlanValidatorTest.cc
cpp/velox/tests/VeloxColumnarBatchSerializerTest.cc
cpp/velox/tests/VeloxColumnarBatchTest.cc
cpp/velox/tests/VeloxColumnarToRowTest.cc
cpp/velox/tests/VeloxRowToColumnarTest.cc
gluten-data/src/main/java/org/apache/gluten/memory/nmm/NativeMemoryManager.java

Changes:
1. set memoryPoolTransferCapacity_ with spark.gluten.memory.reservationBlockSize which used when grow capacity.
2. add BlockAllocationListener for block reservation logic, it's safe to keep AllocationListener be non-thread safe since it will be invoked by whether ListenableAllocator or ListenableArbitrator at same time.
Add MemoryManagerTest.cc

[VL] Move memory reservation block computation logic into ListenableAllocator

---

cpp/velox/substrait/SubstraitToVeloxPlan.cc

Fix warnings caused by -Wunused-but-set-variable
```
/root/gluten-ups/cpp/velox/substrait/SubstraitToVeloxPlan.cc:2224:90:   required from here
/root/gluten-ups/cpp/velox/substrait/SubstraitToVeloxPlan.cc:2161:10: warning: variable ‘lowerUnbounded’ set but not used [-Wunused-but-set-variable]
2161 |     bool lowerUnbounded = true;
|          ^~~~~~~~~~~~~~        
/root/gluten-ups/cpp/velox/substrait/SubstraitToVeloxPlan.cc:2162:10: warning: variable ‘upperUnbounded’ set but not used [-Wunused-but-set-variable]
2162 |     bool upperUnbounded = true;
|          ^~~~~~~~~~~~~~
```
Existed CI

[VL][Minor] Fix warnings caused by -Wunused-but-set-variable

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHExpressionTransformer.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ArrayExpressionTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala

Support get(GetArrayItem) function with native implementation in Velox backend, and move original implementation to CH module.

[VL] Ensure get(GetArrayItem) function is offloaded

---

shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
shims/spark35/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala

This PR do small changes:
1. Add `isRowIndexMetadataColumn` function in shim layer to check if one column is row index or not.
2.  Small change of spark 35  `datafilters` in `native scan` to support filter based on file metadata columns since velox backend support that.
3.  Don't push down `row index` column filter to scan since velox not support that.
(Fixes: \#5047)
It's dependency PR of https://github.com/apache/incubator-gluten/pull/5351
UT test && manually run.

[VL] Refactor data filter in scan transformer

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala

WholeStageIterator's build time has been accounted in RDD's compute method by `GlutenTimeMetric.millis(pipelineTime)`.

[CORE] Remove duplicate pipeline metrics measurement

---

backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
cpp/velox/config/VeloxConfig.h
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/tests/MemoryManagerTest.cc
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

Add new config `spark.gluten.sql.columnar.backend.velox.memInitCapacity` to reduce memory arbitration times, default value is 8M.

[VL] Add config for memory pool init capacity to reduce arbitration times

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeOptimizeSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseNativeWriteTableSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTableAfterRestart.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/s3/S3AuthSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHAggAndShuffleBenchmark.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala
gluten-core/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExtensionSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExtensionSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExtensionSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExtensionSuite.scala

The "spark.gluten.enabled" configuration was hardcoded across the Gluten codebase. I refactored it to consistently utilize the "GlutenConfig.GLUTEN_ENABLED.key" instead.
(Fixes: \#5844)
UTs.

[GLUTEN-5844][CORE] Refactor the usage of spark.gluten.enabled

---

gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala

A bunch of commits are added in Velox upstream to fix the semantics of NaN in array functions, where NaNs are changed to be treated as equal, which becomes aligned with Spark semantics. Tests on corresponding array functions could be enabled with these modifications.

[VL] Enable NaN tests for array functions

---

dev/ci-velox-buildstatic.sh
gluten-core/src/main/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumers.java
gluten-core/src/test/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumerTest.java

The factory objects are already globally static. Its inner map doesn't need to be static. Make it non-static to take better encapsulation.
Also add some basic tests for `TreeMemoryConsumer`.

[CORE] Remove static modifier on TreeMemoryConsumers.Factory.map

---

cpp/velox/utils/ConfigExtractor.cc
docs/get-started/VeloxGCS.md

The Velox GCS connector was recently added a couple of properties:
- HiveConfig::kGCSMaxRetryCount: Retry until a number of transient errors is detected.
- HiveConfig::kGCSMaxRetryTime: Retry until a time elapses.
This properties are useful to allow a client to either fail immediately or keep retring for several minutes.
If none of them is set, then it will use the defaults set by GCS.
This change was tested manually, by entering an unnaccesible GCS bucket then verifying that the properties are honored.

[GLUTEN-5859][VL] Add support for GCS retry properties

---

cpp-ch/clickhouse.version
cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.cpp
cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.h
cpp-ch/local-engine/Disks/ObjectStorages/registerGlutenDiskObjectStorage.cpp
cpp-ch/local-engine/Storages/Output/WriteBufferBuilder.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp

[GLUTEN-1632][CH]Daily Update Clickhouse Version (20240526)

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
backends-velox/src/test/scala/org/apache/gluten/fuzzer/FuzzerTestBase.scala
backends-velox/src/test/scala/org/apache/gluten/fuzzer/ShuffleWriterFuzzerTest.scala

fixes #5206 
Pick up velox upstream PR to enable hashing complex types

[VL] Allow hash on map for round robin repartitioning

---

backends-velox/src/main/scala/org/apache/gluten/extension/HLLRewriteRule.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala

Velox's `approx_distinct` supports decimal type, we can add the support for decimal type in the `HLLRewriteRule`.
Add a new test case for approx_count_distinct decimal type.

[VL] Support DecimalType for approx_count_distinct

---

gluten-core/src/main/java/org/apache/gluten/substrait/expression/BinaryLiteralNode.java

The serialized bloom filter is binary node, it may be very large, then affect the performance.

[CORE] Avoid copy in ByteLiteralNode

---

cpp/velox/operators/writer/VeloxParquetDatasource.cc
cpp/velox/operators/writer/VeloxParquetDatasource.h
cpp/velox/operators/writer/VeloxParquetDatasourceABFS.h
cpp/velox/operators/writer/VeloxParquetDatasourceGCS.h
cpp/velox/operators/writer/VeloxParquetDatasourceHDFS.h
cpp/velox/operators/writer/VeloxParquetDatasourceS3.h

[GLUTEN-5314][VL] Separate FileSink instantiation for different file systems

---

cpp/core/jni/JniWrapper.cc
gluten-data/src/main/java/org/apache/gluten/vectorized/ColumnarBatchOutIterator.java

There is a chance that `nativeSpill` is called after iterator is closed.  We can ignore this.
(Fixes: \#4422)

[GLUTEN-4422][CORE] Fix core dump caused by spill on closed iterator

---

tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Parameterized.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/TableRender.scala
tools/gluten-it/common/src/test/java/org/apache/gluten/integration/action/TableRenderTest.scala

The patch just corrects the identing algorithm of #5889.

[VL] Following #5889, correct / simplify the table indenting algorithm

---

backends-velox/src/main/scala/org/apache/gluten/expression/ExpressionTransformer.scala

After #5658 , we met validation failed with q24a ad q24b while using bloomFilter.
manul test

[GLUTEN-5656][CORE][FOLLOWUP] Support GetStructField with NullLiteralNode as subqueries not executing during validation

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
cpp-ch/local-engine/Parser/scalar_function_parser/regexp_extract.cpp

select regexp_extract('1-A', '([0-9][[.][0-9]]*)', 1)
Spark behavior:
1
actual behavior:
``
(Fixes: \#5898)
Test by ut

[GLUTEN-5898][CH] Fix regexp_extract function use bracket has diff behaver with spark

---

gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala

After https://github.com/facebookincubator/velox/issues/9778 is fixed, add unit test for from_unixtime with overflowed argument and query config setted time zone
Fixes: https://github.com/apache/incubator-gluten/issues/5701
Passed unit tests

 [GLUTEN-5701][VL] Add overflow test case for from_unixtime function

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala

We should validate the project before sort rather than using ProjectExecTransformer directly. The hash expression may not support offload to native, e.g., the child output contains null type or something else.
The following query would fail:
```sql
spark.sql("select 1 as c, null as x").repartition().collect
```
add test

[VL] Fix shuffle with round robin partitioning fail

---

backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

https://github.com/apache/incubator-gluten/issues/4763#issuecomment-2138401401
```
Caused by: java.lang.RuntimeException: Exception: VeloxUserError
Reason: ROW comparison not supported for values that contain nulls
Expression: !decoded.base()->containsNullAt(indices[index])
Function: checkNestedNulls
File: /var/git/gluten/ep/build-velox/build/velox_ep/velox/functions/lib/CheckNestedNulls.cpp
Line: 34
```
Now we use Presto Velox impl for these 3 functions, there is behavior mismatch between Presto and Spark for complex types, we should disable them before implementing them separately for Spark in Velox.
UT.

[VL] Fall back collect_set, min and max when input is complex type

---

backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/commands/VacuumCommand.scala
backends-clickhouse/src/main/delta-23/org/apache/spark/sql/delta/commands/VacuumCommand.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDeltaParquetWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeOptimizeSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTableAfterRestart.scala

Fallback to run delta vacuum command:
When AQE is on, now gluten CH backend + Delta ran delta vacuum command failed, fallback to run it first.
Close #5944.
(Fixes: #5944)

[GLUTEN-5944][CH] Fallback to run delta vacuum command

---

dev/ci-velox-buildstatic.sh
dev/vcpkg/ports/simdjson/portfile.cmake
dev/vcpkg/ports/simdjson/vcpkg.json
dev/vcpkg/vcpkg.json
ep/build-velox/src/build_velox.sh

See velox commit:
https://github.com/facebookincubator/velox/commit/f9ae45acbfe2ae742c46bcb39f77ef3824f95c84
CI build.

[VL] Upgrade simdjson to  3.9.3 in vcpkg build

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHSortMergeJoinExecTransformer.scala
backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHJoinValidateUtil.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSParquetGraceHashJoinSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSParquetSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
cpp-ch/local-engine/Parser/JoinRelParser.cpp
cpp-ch/local-engine/Parser/JoinRelParser.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

[GLUTEN-5668][CH] Support mixed conditions in shuffle hash join

---

backends-velox/src/main/scala/org/apache/gluten/execution/ShuffledHashJoinExecTransformer.scala

After #5750 , velox backend supported use the smaller table to build hashmap in shuffled hash join ,`preferredBuildSide` in `ShuffledHashJoinExecTransformer` is unnecessary and not as accurate as AQE, so remove it.
TPC-DS

[VL] Remove reselect build side in ShuffledHashJoinExecTransformer

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/arithmetic.cpp

This is follow up of https://github.com/apache/incubator-gluten/pull/5621,  I just support `+, -, *, /` in that PR. Let's support `%` in this PR
(Fixes: \#5620)
New UTs

[GLUTEN-5620][CH] Simplify Decimal process for Remainder(%) operator

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/core/shuffle/Payload.cc
cpp/velox/shuffle/VeloxHashBasedShuffleWriter.cc

The query would fail if the shuffle partition > 1:
```
spark.sql("select c1 , null as c2 from t1").repartition($"c1').collect
```
the reason is that, before shuffle writer does not write anything for null type but the shuffle read try to read buffer which is an invalid memory address, then it causes oom.
```
Caused by: java.lang.RuntimeException: Error during calling Java code from native code: org.apache.gluten.memory.memtarget.ThrowOnOomMemoryTarget$OutOfMemoryException: Not enough spark off-heap execution memory. Acquired: 127.4 TiB, granted: 864.0 MiB. Try tweaking config option spark.memory.offHeap.size to get larger space to run this application (if spark.gluten.memory.dynamic.offHeap.sizing.enabled is not enabled).
Current config settings: …
```

[VL] Fix shuffle with null type failure

---

gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ExpandFallbackPolicy.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala

This pr makes ExpandFallbackPolicy propagate fallback reason to vanilla SparkPlan. The real fallback reason should not be overwritten by ExpandFallbackPolicy's fallback reason.
add test

[CORE] ExpandFallbackPolicy should propagate fallback reason to vanilla SparkPlan

---

backends-clickhouse/src/main/scala/org/apache/gluten/metrics/HashAggregateMetricsUpdater.scala
backends-clickhouse/src/main/scala/org/apache/gluten/metrics/HashJoinMetricsUpdater.scala
backends-clickhouse/src/main/scala/org/apache/gluten/metrics/MetricsUtil.scala
backends-velox/src/main/scala/org/apache/gluten/execution/TopNTransformer.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxMetricsSuite.scala
gluten-core/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RemoveFilter.scala
gluten-core/src/main/scala/org/apache/gluten/metrics/MetricsUpdater.scala
gluten-data/src/main/scala/org/apache/gluten/metrics/MetricsUtil.scala

This is mainly for fixing bug appearing only when RAS is enabled but could be generalized to all potential cases like NoopFilter in RAS.
Before:
After:

[VL] Do not skip updating children's metrics while visiting an operator with NoopMetricsUpdater

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseHiveTableSuite.scala
cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
cpp-ch/local-engine/tests/gtest_parquet_read.cpp

We introduce `VectorizedParquetBlockInputFormat` in https://github.com/apache/incubator-gluten/pull/4634, which onlu support primitive type, for complex type we fallback to `ParquetBlockInputFormat`
(Fixes: \#3582)
`GlutenClickHouseHiveTableSuite` includes test on complex type parquet,  setting `spark.gluten.sql.columnar.backend.ch.runtime_config.use_local_format`  to true

[GLUTEN-3582][CH] Using ParquetBlockInputFormat instead of VectorizedParquetBlockInputFormat for complex type

---

gluten-core/src/main/scala/org/apache/gluten/execution/ColumnarCoalesceExec.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala

This pr renames CoalesceExecTransformer to ColumnarCoalesceExec. 
- xxxTransformer is used for operator which support offload to native
- ColumnarXXX is used for operator which support columnar but not native
Pass CI

[CORE] Rename CoalesceExecTransformer to ColumnarCoalesceExec

---

cpp/core/jni/JniWrapper.cc
cpp/core/memory/ColumnarBatch.cc
cpp/core/memory/ColumnarBatch.h
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/memory/VeloxColumnarBatch.h

To make member function ColumnarBatch::getRowBytes safe in terms of memory leak.
And essential code cleanups.

[VL] Make ColumnarBatch::getRowBytes leak-safe

---

dev/formatcppcode.sh

Update formatcppcode.sh to install clang 15 if not present.
The current version of the script returns `find: ‘clang-format-15’: No such file or directory` and exits.

Update CPP Formatting Script

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

This pr based on https://github.com/ClickHouse/ClickHouse/pull/64562, Type of Literal DateTime32 will be lost during parsing plan of CH as it will be convert to Int16.
(Fixes: \#5910)
This patch was tested manually.

[GLUTEN-5910] [CH] add custom type to ASTLiteral

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.h

[GLUTEN-5981][CH] Make the result be null when the queried field in `get_json_object` is `null`

---

gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala

This is a minor fix for RAS extracted from PR https://github.com/apache/incubator-gluten/pull/5927.
E.g., if a shuffle exchange is going to be offloaded into velox project + velox shuffle exchange, the project node will be validated by RAS no matter the offload rule did it or not, after applying this patch. This could guard against any cases that developer didn't do native validations in the offload rule.

[VL] RAS: Validate against all offloaded plan nodes to decide whether to do this offload

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/java/org/apache/gluten/utils/VeloxBatchAppender.java
backends-velox/src/main/java/org/apache/gluten/utils/VeloxBatchAppenderJniWrapper.java
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/execution/VeloxAppendBatchesExec.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/core/jni/JniCommon.cc
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/velox/CMakeLists.txt
cpp/velox/jni/VeloxJniWrapper.cc
cpp/velox/shuffle/VeloxHashBasedShuffleWriter.cc
cpp/velox/shuffle/VeloxHashBasedShuffleWriter.h
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/utils/VeloxBatchAppender.cc
cpp/velox/utils/VeloxBatchAppender.h
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
gluten-core/src/main/scala/org/apache/gluten/utils/Iterators.scala
gluten-data/src/main/java/org/apache/gluten/vectorized/ColumnarBatchOutIterator.java
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

It's observed that Velox hash-based shuffle is slowed down by small input batches.
The patch:
1. Adds two options:
- `spark.gluten.sql.columnar.backend.velox.coalesceBatchesBeforeShuffle`
(Default: false) Set to true to combine small batches with minimal batch size determined by `spark.gluten.sql.columnar.maxBatchSize`. (Note the misnaming of `maxBatchSize` in Gluten, it might tend to be `minBatchSize` or just `batchSize`)
- `spark.gluten.sql.columnar.backend.velox.minBatchSizeForShuffle`
(Optional) Set to override the minimal batch size used by `coalesceBatchesBeforeShuffle`.
2. Does essential code refactors and cleanups. 
(spark.gluten.sql.columnar.backend.velox.coalesceBatchesBeforeShuffle=false/true)
Q31 total time, before and after (SF1000 partitioned table, scan partitions 112, …

[VL] Provide options to combine small batches before sending to shuffle

---

docs/get-started/Velox.md
gluten-iceberg/pom.xml
package/pom.xml

[VL] Add gluten iceberg jar to bundle package

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp

Fix can't not load part after restart spark session after enable enabled_driver_filter_mergetree_index
(Fixes: \#6040)
Test by ut

[GLUTEN-6040][CH] Fix can't not load part after restart spark session

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
docs/developers/SubstraitModifications.md
gluten-core/src/main/java/org/apache/gluten/substrait/expression/ExpressionBuilder.java
gluten-core/src/main/java/org/apache/gluten/substrait/expression/WindowFunctionNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/rewrite/PullOutPreProject.scala
gluten-core/src/main/scala/org/apache/gluten/utils/PullOutProjectHelper.scala
gluten-core/src/main/scala/org/apache/spark/sql/catalyst/expressions/PreComputeRangeFrameBound.scala

Support window range frame by pre-project frame offset for non-SpecialFrameBoundary, based on the discussion https://github.com/facebookincubator/velox/issues/7557
(Fixes: \#5625)
UT

[GLUTEN-5625][VL] Support window range frame

---

cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskHDFS.cpp
cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskHDFS.h

Add a write speed limit to HDFS to avoid TCP port exhaustion due to too many small files and too fast write rate.
unit tests， manual test

[CH] add throttler to GlutenHDFSDisk

---

gluten-core/src/main/scala/org/apache/gluten/execution/DataSourceScanTransformerRegister.scala
gluten-core/src/main/scala/org/apache/gluten/execution/ScanTransformerFactory.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/MiscColumnarRules.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarSubqueryBroadcastExec.scala
gluten-delta/src/main/scala/org/apache/gluten/execution/DeltaScanTransformer.scala
gluten-delta/src/main/scala/org/apache/gluten/execution/DeltaScanTransformerProvider.scala
gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergTransformerProvider.scala

Goals:
1. Fix hash relation type incompatible errors because of `ColumnarSubqueryBroadcastExec` or its resident filter/scan's fallback (by ras or by expanded-fallback[1]).
2. Simplify DPP code
Changes:
1. Remove DPP (`ColumnarSubqueryBroadcastExec`) handling code from ExpressionConverter
2. Remove all invocations on`ColumnarSubqueryBroadcastExec#transformDynamicPruningExpr`
3. Add rule `RewriteSubqueryBroadcast` which runs before regular columnar rules to replace `SubqueryBroadcastExec` with `ColumnarSubqueryBroadcastExec`
Tested by existing UTs (legacy plannner) and locally (RAS).
[1] Not confirmed. The issue was found when enabling RAS.

[CORE] Rework Gluten + DPP compatibility

---

cpp-ch/local-engine/Functions/FunctionGetDateData.h
cpp-ch/local-engine/Functions/SparkFunctionToDateTime.h

[GLUTEN-6042][CH]Fix to_date function result type nullable check

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
cpp/velox/udf/Udaf.h
cpp/velox/udf/Udf.h

Fixes:
```
24/06/12 11:15:14 ERROR SparkContext: Error initializing SparkContext.
java.lang.AssertionError: assertion failed: Default instance of SparkDirectoryUtil was not set yet
at scala.Predef$.assert(Predef.scala:223)
at org.apache.spark.util.SparkDirectoryUtil$.get(SparkDirectoryUtil.scala:90)
at org.apache.spark.util.SparkDirectoryUtil.get(SparkDirectoryUtil.scala)
at org.apache.gluten.vectorized.JniWorkspace.createDefault(JniWorkspace.java:68)
at org.apache.gluten.vectorized.JniWorkspace.getDefault(JniWorkspace.java:123)
at org.apache.spark.sql.expression.UDFResolver$.$anonfun$getAllLibraries$1(UDFResolver.scala:299)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at …
```

[VL] Fix load udf library for spark local mode

---

tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Parameterized.java
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Parameterized.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Queries.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/QueriesCompare.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/TableRender.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/package.scala
tools/gluten-it/common/src/test/java/org/apache/gluten/integration/action/TableRenderTest.scala

Just changes the table format to a compacter view for gluten-it option `parameterized` for easier analysis on the test result.
Before:
```
| Query ID | Succeeded | SHUFFLE_PARTITIONS | GLUTEN | Row Count | Planning Time (Millis) | Query Time (Millis) |
|----------|-----------|--------------------|--------|-----------|------------------------|---------------------|
|        q1|       true|                  30|     OFF|          4|                     427|                 7945|
|        q2|       true|                  30|     OFF|        100|                     356|                 1265|
|        q1|       true|                  30|      ON|          4|                      42|                 1504|
|        q2|       true|                  30|      ON|        100| …
```

[VL] Gluten-it: Improve test report table format for parameterized test

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHMetricsApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHGenerateExecTransformer.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxMetricsApi.scala
backends-velox/src/main/scala/org/apache/gluten/execution/GenerateExecTransformer.scala

These metrics look tedious on SQL UI since Spark adds a "total" automatically on the tail.
The patch rewords "totaltime" to "time".

[CORE] Rephrase metric names using "totaltime" as prefix

---

cpp/velox/shuffle/VeloxHashBasedShuffleWriter.cc

Even if FLAGS_v is set to a small value, the VLOG with large verbosity is still initialized and taking lots of time.
After:

[VL] Change VLOG to DLOG in shuffle to fix performance issue in corner cases

---

ep/build-velox/src/build_velox.sh

Most of arrow modules are not needed in gluten, thus we can remove them in mvn install. Besides, we don't need the `arrow-with-dependencies.jar`, thus we remove it too.
GA

[VL][BUILD] Improve compilation speed for Arrow

---

cpp/velox/shuffle/VeloxShuffleWriter.h
ep/build-velox/src/get_velox.sh

```
7646e70a3 by Zac Wen, Prevent cache write from exceeding IOV_MAX (10142)
9ab5e27ac by Jimmy Lu, Lazy materialization of RowType::parameters (10144)
f9f6d8228 by Deepak Majeti, Add support for Centos9 Stream + GCC12 (9903)
c5814c96a by Deepak Majeti, Keep DuckDB re2 headers private (10161)
9cc123f49 by Zac Wen, Specify data type in test for tsan (10153)
73fb02e27 by Jialiang Tan, Fix writer OOM by reducing initial flush buffer reservation (10147)
4a8591348 by xiaoxmeng, Free memory from stale cache entry early (10143)
b2bab6fd7 by xiaoxmeng, Add task deletion wait support (10124)
```

[VL] Daily Update Velox Version (2024_06_13)

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeOptimizeSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTableAfterRestart.scala

Don't know the reason, but this [PR](https://github.com/ClickHouse/ClickHouse/pull/64427) changed the `input_format_parquet_max_block_size` to `DEFAULT_block_size`, which is 65409, causing the MergeTree related tests to fail.  Let's set `input_format_parquet_max_block_size` to 8192, which reverts 7445f02c9414c98956d1ad4d9318f6e545e1740c (this fix looks unstable)
Also I use `assertResult` instead of `assert`, so we can know the actual result once failed.
Existed UTs

[CH][UT] Fix UT due to https://github.com/ClickHouse/ClickHouse/pull/64427

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h

Support pushdown `not in` to scan node
(Fixes: \#5965)
UT

[GLUTEN-5965][VL] Support pushdown "not in" to scan node

---

cpp/CMake/BuildQATzip.cmake

Below linking error is found with latest QAT driver. Use "-Wl,--no-as-needed" to force link libudev.so

[VL] Fix undefined symbol with qat

---

backends-velox/src/test/java/org/apache/gluten/utils/VeloxBloomFilterTest.java
cpp/velox/compute/VeloxBackend.cc
gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Parameterized.scala

`COLUMNAR_VELOX_CONNECTOR_IO_THREADS.defaultValueString` is not accurate enough when it's used in backend initialization because:
1. SQLConf may not be initialized at that time
2. N in `local[N]` mode is not counted

[VL] Fix inaccurate calculation of task slot number used by s.g.s.c.b.v.IOThreads

---

gluten-core/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

getPartitionFilters API not use any more

[Core] Remove getPartitionFilters from scanTransformer

---

gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ColumnarRuleApplier.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkQueryRunner.scala

1. Reuse more code between `HeuristicApplier` and `EnumeratedApplier`
2. Extract columnar rule logging code out into `LoggedRule`
3. Refine columnar rule log messages
4. Adopt Spark's `RuleExecutor`, which means user could measure on columnar rules' execution time by setting a tracker in driver code.
5. `Planning Time` in gluten-it's test report is made more accurate when AQE is on by leveraging 4's method.

[VL] Minor refactors on ColumnarRuleApplier

---

cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Functions/CMakeLists.txt

(Fixes: \#6091)
See #6091 for issue description. This PR does 2 things:
1. unset `LD_PRELOAD` 
2. add missing gwp_asan dependency for `gluten_spark_functions` to avoid mering https://github.com/apache/incubator-gluten/pull/6083
Using existed UTs

[GLUTEN-6091][CH] Avoid using LD_PRELOAD in child process

---

docs/get-started/Velox.md

[VL] Doc update since Spark 3.5.1 has been fully supported

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala

[GLUTEN-6082][CH]Fix lag diff

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala

```
e29f59803 by Deepak Majeti, Fix LZO decompression (#10123)
b37ceb456 by Kevin Wilfong, Run preliminary checks in Docker container built for them (#10234)
718c8e907 by Jimmy Lu, Implement bucket conversion in HiveDataSource (#10228)
c84aa68b4 by wypb, Fix incorrect type conversion for ORC short_decimal. (#10212)
6b32339c9 by Jia Ke, Correctly record the RawBytesRead and scan time metric in DirectBufferedInput (#9801)
2b94eaa9e by Pedro Pedreira, Add list of components and maintainers (#10180)
32c7f6e60 by Jimmy Lu, Fix flaky test TableScanTest.statsBasedSkippingNulls (#10233)
92b31efb6 by Jimmy Lu, Enhance DWRF reader string column size estimation (#10227)
44a86baba by xiaoxmeng, Add metrics to track shuffle data and transfer times (#10226)
2cfd17459 by …
```

[VL] Daily Update Velox Version (2024_06_18)

---

.github/workflows/velox_docker.yml
tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Parameterized.java
tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Queries.java
tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/QueriesCompare.java
tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/QueriesMixin.java
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/QueryRunner.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Parameterized.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Queries.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/QueriesCompare.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/SparkShell.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/package.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/clickbench/ClickBenchDataGen.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkSessionSwitcher.scala

Reuse sessions with same configuration for better support of large scale / long run integration testing.
Reusing the session would avoid reloading the libraries if Gluten is enabled, and would avoid recreating table catalogs again and again.
Add `--no-session-reuse` which is enabled in `random kill task` CI job. Otherwise the job would fail by `no space on disk` since too many temporary files are created in the same session.

[VL] Gluten-it: Reuse Spark sessions that share same configuration

---

ep/build-velox/src/modify_arrow.patch

Fix the [bug](https://github.com/apache/arrow/issues/39919) in arrow-15.0.0, which has already been fixed in 16.0.0 or higher version.
See https://github.com/apache/arrow/pull/40015.
GA

[VL] Support linking system libprotobuf.a when building arrow

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala

Prefer to use `path.getFileSystem` instead of `FileSystem.get` to create `FileSystem`, this can always default to the path's schema to get fs which handle the path.
exist tests and manual tests

[VL] Prefer to use `path.getFileSystem` instead of `FileSystem.get` to create `FileSystem`

---

gluten-core/src/main/scala/org/apache/spark/shuffle/sort/ColumnarShuffleManager.scala

Revert ColumnarShuffleManager changes in https://github.com/apache/incubator-gluten/pull/6022 to mitigate issue #6140

Revert SortShuffleManager changes in ColumnarShuffleManager 

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarWriteFilesExec.scala

`WriteFilesSpec` is not serializable, we should not use it in RDDS
GA

[VL] Avoid using WriteFilesSpec which is not serialzable

---

gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
shims/common/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCost.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCostEvaluator.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCostEvaluator.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCostEvaluator.scala
shims/spark35/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCostEvaluator.scala

Split from #6093 .
Add custom cost evaluator for use the smaller table to build hashmap in shuffled hash join.

[CORE] Add custom cost evaluator for optimize buildSide of shuffled hash join

---

ep/build-velox/src/get_velox.sh

Fixes: #6168
Run `./dev/builddeps-veloxbe.sh --enable_s3=ON` locally.

[BUILD] Syntax error when run `./dev/builddeps-veloxbe.sh --enable_s3=ON` on Ubuntu

---

.github/workflows/build_bundle_package.yml

This patch fixes the build package script by 1) adding the arrow jar 2) use the latest docker image 
local verified

[VL] Fix build package script on GHA

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala

In parquet write, we use several local properties to pass the status in session. We need reset them after finishing write operator.

[GLUTEN-6151] Reset  local property after finishing write operator

---

gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RemoveFilter.scala
gluten-core/src/main/scala/org/apache/gluten/planner/metadata/GlutenMetadata.scala
gluten-core/src/main/scala/org/apache/gluten/planner/metadata/GlutenMetadataModel.scala
gluten-core/src/main/scala/org/apache/gluten/planner/metadata/LogicalLink.scala
gluten-core/src/main/scala/org/apache/gluten/planner/metadata/Schema.scala
gluten-core/src/main/scala/org/apache/gluten/planner/property/Conv.scala
gluten-ras/common/src/main/scala/org/apache/gluten/ras/best/GroupBasedBestFinder.scala
gluten-ras/common/src/test/scala/org/apache/gluten/ras/OperationSuite.scala

This is a concept work to add logical link to RAS metadata. To:
1. Make sure plans in the same group/cluster share the same logical link thus be logically identical (if query plans in the same group/cluster differ on their logical links, planner will throw an error)
3. Prove it possible to obtain Spark statistics from cost model
And with other minor improvements.

[VL] RAS: Incorporate query plan's logical link into metadata model

---

gluten-core/src/main/scala/org/apache/spark/HdfsConfGenerator.scala

The first level of `sc.addedFiles` changed to session, so this pr changes to use ` sc.listFiles` to be compatible  with Spark3.5 and later.
To be compatible with Spark3.5 and later

[CORE] Use sc.listFiles instead of addedFiles.keys

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseNativeWriteTableSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/gluten/NativeWriteChecker.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/local_engine_jni.cpp
cpp-ch/local-engine/tests/benchmark_local_engine.cpp
cpp-ch/local-engine/tests/gluten_test_util.h
cpp-ch/local-engine/tests/gtest_local_engine.cpp
cpp-ch/local-engine/tests/gtest_parser.cpp
cpp-ch/local-engine/tests/json/clickhouse_pr_65234.json
cpp-ch/local-engine/tests/json/gtest_local_engine_config.json
cpp-ch/local-engine/tests/json/read_student_option_schema.csv.json
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/utils/SubstraitPlanPrinterUtil.scala

We refactor the codes for the following purpose:
1. Calling `SparkShim::genExtendedColumnarPostRules`, so we can fallback write to vanilla spark in case of spark 3.5
2. Add `NativeWriteCheck`，Make UT failed in spark 3.5
3. Refactor `LocalExecutor`, moving pipeline building to `SerializedPlanParser`, because we can not add sink transform in this class. 
4. Reducing duplcate codes, i.e. `CHIteratorApi` and  `SubstraitPlanPrinterUtil`
(Fixes: \#6067)
Existed UTs

[GLUTEN-6067][CH] [Part 2] Support CH backend with Spark3.5 - Prepare for supporting sink transform

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
cpp-ch/local-engine/AggregateFunctions/AggregateFunctionSparkAvg.cpp
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Common/GlutenDecimalUtils.h
cpp-ch/local-engine/Parser/RelParser.cpp
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

[GLUTEN-6176][CH] Support aggreate avg return decimal

---

cpp/velox/utils/ConfigExtractor.cc
docs/Configuration.md
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

Add more configs for AWS s3
spark.gluten.velox.fs.s3a.retry.mode
spark.gluten.velox.fs.s3a.connect.timeout
spark.hadoop.fs.s3a.retry.limit
spark.hadoop.fs.s3a.connection.maximum
CI

[GLUTEN-5659][VL] Add more configs for AWS s3

---

gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargets.java
gluten-data/src/main/java/org/apache/gluten/memory/arrow/alloc/ArrowBufferAllocators.java
gluten-data/src/main/java/org/apache/gluten/memory/nmm/NativeMemoryManagers.java
gluten-data/src/main/java/org/apache/gluten/vectorized/NativePlanEvaluator.java

An initial reservation for Velox task memory pool was introduced in https://github.com/apache/incubator-gluten/pull/5815. However that reservation doesn't work correctly with spilling facilities so may lead to NPE.
The patch fixes the issue with some minor refactors.
Tested with existing integration tests to avoid regression.

[GLUTEN-6180][VL] Fix NPE if spilling is requested during task creation

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/expression/DummyExpression.scala
backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala

Currently, if GenerateExec needs a pre-project, only ProjectNode is allowed in the native substrait -> Velox PlanNode transformation. Query would fail if the pre-project of GenerateExec falls back due to native validation failure. We should consider `ValueStreamNode` as valid in case of pre-project fallback.
Introduce `VeloxDummyExpression` for test purpose. An expression wrapped by `VeloxDummyExpression` can mock the case when a certain expression is supported by Gluten, but it fails on native validation.

[GLUTEN-5643] Fix the failure when the pre-project of GenerateExec falls back

---

backends-velox/src/main/java/org/apache/gluten/udf/UdfJniWrapper.java
backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala

In the previous implementation, Yarn AM container only gets the relative filename. e.g. "libmyudf.so", not a full path. The full path should be constructed using the current working directory.

[VL][Minor] Fix udf jni signature mismatch

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
gluten-core/src/main/java/org/apache/gluten/vectorized/JniWorkspace.java
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

Add new config `spark.gluten.sql.debug.keepJniWorkspaceDir` to store libraries, and decouple the functionality from `spark.gluten.sql.debug`

[VL] Make jni debug workspace configurable

---

cpp/velox/operators/functions/RegistrationAllFunctions.cc
cpp/velox/substrait/SubstraitParser.cc

Currently, Gluten registers Velox's prestosql scalar functions. Thus, some of them can be used for Spark SQL if there is no semantic difference. However, there are some conflict issues, which makes unexpected function calling. See below links. We plan to register used presto scalar functions (see below list) in sparksql registry.
https://github.com/apache/incubator-gluten/discussions/4759
https://github.com/apache/incubator-gluten/pull/5150
Function list:
url_decode/url_encode
array_distinct
array_except
array_position
map_entries
map_keys
map_values
reverse
crc32
regexp_extract_all
like
abs (for long/short decimal)
asin
atan
cos
degrees

[VL] Remove the registry for Velox's prestosql scalar functions

---

.github/workflows/velox_docker.yml
docs/get-started/ClickHouse.md
gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornUtils.java
pom.xml
tools/gluten-it/pom.xml

Upgrade celeborn to 0.4.1 to support scala 2.13-based compilation
CI

[CELEBORN] Upgrade celeborn to 0.4.1 to support scala 2.13-based compilation

---

gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Constants.scala

Add config to control celeborn fallback for CI
CI

[CELEBORN] Add config to control celeborn fallback for CI

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseHiveTableSuite.scala
cpp-ch/local-engine/Operator/ExpandTransform.cpp
gluten-core/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
shims/spark32/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
shims/spark34/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
shims/spark35/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala

The pr https://github.com/apache/incubator-gluten/pull/5254 would filter redundant attribute when transforming to substraint plan in order to fix `Unexpected empty column` exception when reading hive text table. This introduces a new issue, for example:
```
(1) NativeScan hive tmp.testxmy_expand
Output [11]: [a1#4, a2#5, a3#6, a4#7, a5#8, a6#9, a7#10, a8#11, a3#6, a4#7, a9#12]
Arguments: [a1#4, a2#5, a3#6, a4#7, a5#8, a6#9, a7#10, a8#11, a3#6, a4#7, a9#12], HiveTableRelation [`tmp`.`testxmy_expand`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, Data Cols: [a1#4, a2#5, a3#6, a4#7, a5#8, a6#9, a7#10, a8#11, a9#12], Partition Cols: []]
(2) ExpandExecTransformer
Input [11]: [a1#4, a2#5, a3#6, a4#7, a5#8, a6#9, a7#10, a8#11, a3#6, a4#7, a9#12]
Arguments: [[a1#4, a2#5, a3#6, a4#7, a5#8, …
```

[GLUTEN-6235][CH] Fix crash on ExpandTransform::work()

---

cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h

Support use dynamic disk path
spark.gluten.sql.columnar.backend.ch.runtime_config.use_current_directory_as_tmp=true
disk.metadata_path and cache.path are automatically mapped to the current directory
spark.gluten.sql.columnar.backend.ch.runtime_config.reuse_disk_cache=false
Add the current pid number to disk.metadata_path and cache.path
unit tests

[CH] Support use dynamic disk path

---

gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsBaseTrait.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsCommonTrait.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/GlutenSortShuffleSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/GlutenSortShuffleSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/GlutenSortShuffleSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/GlutenSortShuffleSuite.scala

[GLUTEN-6251][CH] Disable GlutenSortShuffleSuite in clickhouse backend

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
cpp/velox/config/VeloxConfig.h

The current implementation sets `spark.gluten.sql.columnar.backend.velox.udfLibraryPaths` on driver side after resolving the library paths. This approach can overwrite the original settings with a local file path on the driver node before sending the SparkConf to all executors, and the executors on different nodes will fail while accessing that path.
This PR sets the resolved library paths to an internal config to avoid the conflicts.
Manually verified on a multi-node cluster.

[GLUTEN-6253] Use internal udf config to avoid modify the original one

---

gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java

`CelebornShuffleManager#getWriter` should avoid adding shuffle id repeatedly to `columnarShuffleIds`. `CelebornShuffleManager#registerShuffle` adds shuffle id to `columnarShuffleIds` which should not add shuffle id to `columnarShuffleIds` repeatedly in `CelebornShuffleManager#getWriter`.
Backport https://github.com/apache/celeborn/pull/2503.
CI.

[CELEBORN] Avoid CelebornShuffleManager#getWriter adding shuffle id repeatedly to columnarShuffleIds

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.h
gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala

[CH] Support bit_get/bit_count function

---

backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/Parser/scalar_function_parser/bitLength.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/length.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/octetLength.cpp
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenStringFunctionsSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenStringFunctionsSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenStringFunctionsSuite.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenStringFunctionsSuite.scala
shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala

* support `bit_length/octet_length` function
* move `length` impl to `funciton parser`
These three functions may receive `int` type argument in spark ut, add a `cast to string`.
PASS CI

[CH] Support bit_length/octet_length function

---

docs/get-started/ClickHouse.md
docs/get-started/Velox.md
docs/get-started/build-guide.md

Fix `Celeborn support` of get-started document including:
1. Use `-Pceleborn` to fix the profile of celeborn in `Maven build parameters` for `build-guide.md`.
2. Use `-Pceleborn` to fix the profile of compiling the Gluten Java module in `Celeborn support` for `Velox.md`.
3. Fix and improvement `Celeborn support` of clickhouse backend for `ClickHouse.md`.
No.

[CELEBORN] Fix Celeborn support of get-started document

---

dev/builddeps-veloxbe.sh
docs/get-started/build-guide.md
ep/build-velox/src/get_velox.sh

Disable protobuf by default as it is not required for each build.
Also removed the build protobuf option from get_velox.sh since it is confusing and unnecessary. This option just controls whether to change velox's setup script. So it depends on the enabling of --run_setup_script.
CI.

[VL] Disable protobuf build by default

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHExpressionTransformer.scala
backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala

Spark Size function's legacySizeOfNull is determined either by other functions like `ArraySize` to specify a value or by Spark's configuration. Just depending on configuration will cause result mismatch issue for `ArraySize` function.
With the fix in velox: https://github.com/facebookincubator/velox/pull/10100, we need to directly pass this value of instantiated `Size` to native function. 
Depends on a fix in velox:
https://github.com/facebookincubator/velox/pull/10100
Fixes #5248.
Added test.

[GLUTEN-5248][VL] Directly pass legacySizeOfNull to native size function

---

.github/workflows/velox_docker.yml

1. Run Q23A/Q23B + isolation anyway although failures were ignored
2. Enable Q97 as "invalid pointer" bug has disappeared

[VL] CI: Update job `run-tpc-test-ubuntu-oom` for latest memory usage status

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
cpp/CMake/ConfigArrow.cmake
cpp/core/CMakeLists.txt
cpp/velox/CMakeLists.txt
dev/build_arrow.sh
dev/builddeps-veloxbe.sh
ep/build-velox/src/modify_velox.patch

1. Removes linking libvelox.so with arrow libs, which is useless.
2. With static arrow libs linked, no need to keep lib arrow & lib parquet in Gluten Jar.

[VL] Link lib gluten to arrow's static libraries

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/Parser/scalar_function_parser/arrayHighOrderFunctions.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/lambdaFunction.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/lambdaFunction.h

Fixes: #6159
support following array functions
- filter
- transform
- aggregate
unit tests

[GLUTEN-6159][CH] Support array functions with lambda functions

---

backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxBlockStripes.java
backends-velox/src/test/java/org/apache/gluten/columnarbatch/ColumnarBatchTest.java
backends-velox/src/test/java/org/apache/gluten/test/VeloxBackendTestBase.java
backends-velox/src/test/java/org/apache/gluten/utils/VeloxBloomFilterTest.java
cpp/core/jni/JniWrapper.cc
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriter.scala
gluten-core/src/main/java/org/apache/gluten/memory/memtarget/Spillers.java
gluten-data/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatchJniWrapper.java
gluten-data/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatches.java
gluten-data/src/main/java/org/apache/gluten/columnarbatch/IndicatorVector.java
gluten-data/src/main/java/org/apache/gluten/columnarbatch/IndicatorVectorBase.java
gluten-data/src/main/java/org/apache/gluten/columnarbatch/IndicatorVectorPool.java
gluten-data/src/main/java/org/apache/gluten/vectorized/ColumnarBatchOutIterator.java
gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala
gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java

Goals:
1. Avoid sharing native columnar batch instance in different indicator vectors from Java side, to avoid any possible reference re-counting or lifecycle leak issues caused by the apporach
2. To make it easier to track native columnar batch's life cycle from Java side
Changes:
1. Remove `ColumnarBatchJniWrapper#obtainOwnership`
2. Add `IndicatorVectorPool` to map native columnar batch to Java indicator vector by exact 1:1 criteria
3. Another irrelevant code cleanup against Spiller

[VL] IndicatorVectorPool to avoid sharing native columnar batches' ownerships among runtime instances

---

gluten-core/src/main/scala/org/apache/gluten/execution/HashAggregateExecBaseTransformer.scala

Add isStreamingAgg info to the toString method of HashAggregateBaseTransformer, so that we can easily determine the current type of the Aggregate.
N/A.

[VL] Add isStreamingAgg info to HashAggregateTransformer

---

backends-clickhouse/src/main/java/org/apache/gluten/vectorized/BatchIterator.java
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Parser/RelMetric.cpp
cpp-ch/local-engine/Parser/RelMetric.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/jni/jni_common.cpp
cpp-ch/local-engine/jni/jni_common.h
cpp-ch/local-engine/local_engine_jni.cpp

To fix memory leak, I Inroduce JNI safe array to avoid call  `ReleaseByteArrayElements` manually
(Fixes: \#6279)
Using existed UTs

[GLUTEN-6279][CH] Inroduce JNI safe array

---

cpp/velox/compute/VeloxPlanConverter.cc

Velox s3FileSystem use -1 as default file size. Gluten wrongly passed 0 if file size isn't gotten from Spark. 
https://github.com/facebookincubator/velox/blob/f5bfd1eed38780597b3b13eff1370207f67f0838/velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp#L92

[VL] bug fix for S3 read

---

cpp-ch/clickhouse.version
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
cpp-ch/local-engine/Parser/JoinRelParser.cpp
cpp-ch/local-engine/tests/benchmark_local_engine.cpp
cpp-ch/local-engine/tests/gtest_ch_join.cpp
cpp-ch/local-engine/tests/gtest_parser.cpp

[GLUTEN-1632][CH]Daily Update Clickhouse Version (20240703)

---

.github/workflows/velox_docker.yml
docs/get-started/ClickHouse.md
docs/get-started/Velox.md
tools/gluten-it/pom.xml

Apache celeborn was released on June 24th, you can see also [release notes](https://celeborn.apache.org/community/release_notes/release_note_0.5.0/#improvement) for more details. This PR amins to support celeborn 0.5.0.
GA it tests

[CELEBORN] Support celeborn 0.5.0

---

ep/build-velox/src/build_velox.sh

Fix build Velox script incorrectly judged as successful when run make.
(Fixes: \#6330)
munally.

[VL] Fix build Velox script incorrectly judged as successful when run make

---

gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RemoveFilter.scala

[VL] RAS: Remove NoopFilter if has same output with child

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxColumnarBatchIterator.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxWriteQueue.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

This PR aims to make velox writer queue size is configurable to avoid oom from being caused by too many batches.
GA

[VL] Make velox writer queue size configurable

---

cpp/core/jni/JniWrapper.cc
cpp/velox/jni/VeloxJniWrapper.cc

Fix cpp compile warning isssue due to unused variable definitation 'ctx'

[VL] Remove useless ctx variable

---

ep/build-velox/src/get_velox.sh

Velox moved `third_party/CMakeLists.txt` to `CMake/resolve_dependency_modules/arrow/CMakeLists.txt`. The original `sed` command will give an error. Upon verification, it is now confirmed that there is no need to modify `${CMAKE_INSTALL_LIBDIR}`, as its value is already set to `lib64`.
N/A

[VL] Fix process_setup_alinux3 arrow CMakeLists.txt path

---

gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java

`CelebornShuffleManager#stop` should stop non-null `_vanillaCelebornShuffleManager`. Meanwhile, stopping `_columnarShuffleManager` should check whether `_columnarShuffleManager` is null instead of `columnarShuffleManager()` which could not return null.
CI.

[CELEBORN] CelebornShuffleManager#stop should stop non-null _vanillaCelebornShuffleManager

---

docs/developers/docker_ubuntu22.04.md

Since the velox needs cmake version > 3.28, we better update the doc to align this change

[VL] Update ubuntu docker to use cmake 3.28

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/metadata/AddFileTags.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHBucketSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHParquetBucketSuite.scala

[CH] Support delta count optimizer for the MergeTree format:
In Delta, it will use the rule PrepareDeltaScan to optimize the count command, which will directly use the delta meta to response the sql select count(*) from table, now support this optimizer for the MergeTree format.
Close #6378.
(Fixes: #6378)

[GLUTEN-6378][CH] Support delta count optimizer for the MergeTree format

---

cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/operators/plannodes/RowVectorStream.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h

Refactor ValueStream node construction logic and add finished flag for it.

[VL] Minor refactor for ValueStream node construction and usage

---

gluten-celeborn/clickhouse/src/main/resources/META-INF/services/org.apache.spark.shuffle.gluten.celeborn.CelebornShuffleWriterFactory
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriter.scala
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriterFactory.scala
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/resources/META-INF/services/org.apache.spark.shuffle.gluten.celeborn.CelebornShuffleWriterFactory
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarShuffleWriterFactory.scala

Rename CelebornHashBasedColumnarShuffleWriter to CelebornColumnarShuffleWriter
CI

[CELEBORN] Rename CelebornHashBasedColumnarShuffleWriter to CelebornColumnarShuffleWriter

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala

Before this PR , the E function would fallback if 
1) The spark.sql.optimizer.excludedRules has  `ConstantFolding.ruleName`
2) The schema is empty
This PR address above 2 cases.

[VL] Fix E function fallback issue in some condition

---

gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java

When using ```CelebornShuffleManager```, columnar shuffle data is typically compressed on the Gluten side and sent directly to Celeborn, so compression is not needed on the Celeborn side. Therefore, ```spark.celeborn.client.shuffle.compression.codec``` is set to none. However, when row-based shuffle occurs, this configuration causes Celeborn to skip compression, leading to data bloat.
CI

[CELEBORN] Add compression for row-based shuffle

---

backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala
backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
gluten-core/src/main/scala/org/apache/gluten/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/execution/ColumnarCoalesceExec.scala
gluten-core/src/main/scala/org/apache/gluten/extension/GlutenPlan.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala

This PR fixed the failure below.
```
val data = "2019-09-09 01:02:03.456789"
val df = Seq(data).toDF("strTs").selectExpr(s"CAST(strTs AS TIMESTAMP_NTZ) AS ts")
df.coalesce(1).write.format("parquet").save("/tmp/test")
```
```
org.apache.gluten.exception.GlutenException: Input schema contains unsupported type when convert row to columnar for StructType(StructField(ts,TimestampNTZType,true)) due to Schema / data type not supported: TimestampNTZType
at org.apache.gluten.execution.RowToVeloxColumnarExec.$anonfun$doExecuteColumnarInternal$1(RowToVeloxColumnarExec.scala:54)
at scala.Option.foreach(Option.scala:407)
at org.apache.gluten.execution.RowToVeloxColumnarExec.doExecuteColumnarInternal(RowToVeloxColumnarExec.scala:51)
at org.apache.gluten.execution.RowToColumnarExecBase.doExecuteColumnar( …
```

[VL] Add schema validation for all operators

---

cpp/CMake/ConfigArrow.cmake

We expect cmake's find_library function always finds lib from specified PATHS firstly, then system paths. But local build shows it isn't true. This pr is proposed to make sure that.

[VL] Try to find arrow libs from velox bundled path firstly

---

gluten-ut/test/src/test/scala/org/apache/spark/sql/GlutenExpressionDataTypesValidation.scala

There are a few functions that are only partially supported, e.g., some input types are not supported. This PR is just for helping us to know the gaps.
This PR gets expression list and registered expression builders from Spark. In the validation process, the expression's input data doesn't really matter, but input type does. So we can use literal NULL child with specific type to build an expression instance. After this, we simply construct a Gluten plan with a dummy child node. Then, go into GlutenPlan's validation code path.
This is just the first patch for project function validation. Will have more PRs for other functions, like binary expressions, aggregate functions, etc.
See partial output:
```
!! cast validation fails: cast from ByteType to TimestampType
!! cast validation fails: …
```

[UT] Add a tool to validate any unary expression with all its accepted types 

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala

1.The spark.sql.optimizer.excludedRules has ConstantFolding.ruleName
2. The schema is empty

[VL] Fix Pi function fallback issue in some condition

---

cpp/velox/shuffle/VeloxHashBasedShuffleWriter.cc
cpp/velox/shuffle/VeloxHashBasedShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc
cpp/velox/utils/tests/VeloxShuffleWriterTestBase.h

In VeloxHashBasedShuffleWriter::stop, evict partition buffers can allocating extra memory and triggers spill. In this case the target partition buffer should not get shrunk.
Can be reproduced by the added UT.
---------------------
Java stack:
```
org.apache.gluten.exception.GlutenException: Error during calling Java code from native code: org.apache.gluten.exception.GlutenException: (shuffle) nativeEvict: evict failed - Invalid: Value buffer of fixed-width array is null.
at org.apache.gluten.vectorized.ShuffleWriterJniWrapper.nativeEvict(Native Method)
at org.apache.spark.shuffle.ColumnarShuffleWriter$$anon$1.spill(ColumnarShuffleWriter.scala:170)
at org.apache.gluten.memory.memtarget.Spillers$AppendableSpillerList.spill(Spillers.java:86)
at …
```

[VL] Fix shuffle spill triggered by evicting buffers during stop

---

ep/build-velox/src/get_velox.sh

change oap's velox version to branch-1.2 for gluten v1.2.0 release
tested in local

change velox branch to branch-1.2 for gluten v1.2.0 release

---

cpp/CMake/ConfigArrow.cmake
dev/build_arrow.sh
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh

Depends on the fix in https://github.com/facebookincubator/velox/pull/10355.
CI.

[VL] Set Arrow_SOURCE to AUTO to allow using system arrow libs

---

gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriter.scala
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarShuffleWriter.scala

1. `CHCelebornColumnarShuffleWriter` supports `celeborn.client.spark.shuffle.writer` to use memory sort shuffle in ClickHouse backend.
2. `CHCelebornColumnarShuffleWriter` initializes `nativeShuffleWriter` without skipping `ColumnarBatch` in `internalWrite` to avoid unnecessary creation of `nativeShuffleWriter` for skipping `ColumnarBatch`.
3. Extracts the same writing records code of `CHCelebornColumnarShuffleWriter` and `VeloxCelebornColumnarShuffleWriter` into `CelebornColumnarShuffleWriter`.
CI.

[CELEBORN] CHCelebornColumnarShuffleWriter supports celeborn.client.spark.shuffle.writer to use memory sort shuffle in ClickHouse backend

---

cpp/velox/CMakeLists.txt
ep/build-velox/src/modify_velox.patch

This could fix the crash issue mentioned in https://github.com/apache/incubator-gluten/issues/6411.

[VL] Make sure the same thrift lib bundled in arrow build is used for building Velox

---

cpp/velox/CMakeLists.txt
ep/build-velox/src/modify_velox.patch

Port https://github.com/apache/incubator-gluten/pull/6431 to release 1.2

[VL] Branch 1.2: Make sure the same thrift lib bundled in arrow build is used for building Velox

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

Enable right and anti join in smj
Adding new unit tests.

[VL] Enable right and anti join in smj

---

gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarBatchSerializer.scala

`CHCelebornColumnarBatchSerializer` should use `AtomicBoolean` to identify whether to call `close()` to avoid calling `close()` twice situation which causes the replication of metrics like `readBatchNumRows`, `numOutputRows`.
CI.

[CH][CELEBORN] CHCelebornColumnarBatchSerializer uses AtomicBoolean to identify whether to call close() to avoid calling close() twice situation

---

.github/workflows/velox_weekly.yml
dev/builddeps-veloxbe.sh
ep/build-velox/src/get_velox.sh

This is to make sure no build issue in Gluten + Velox. Other CI jobs use dockers with dependencies pre-installed, which doesn't uncover some build issues sometimes.
This job is scheduled to be triggered per week. Also fixes some issues found by this job.
Depends on https://github.com/apache/incubator-gluten/pull/6444.

[CI][VL] Re-enable a build job running on clean dockers weekly

---

LICENSE-binary
NOTICE
NOTICE-binary

Update LICENSE, NOTICE, LICENSE-binary, NOTICE-binary
LICENSE: Remove most, only keep Apache 2.0 for Gluten source code.
NOTICE: Modify NOTICE
LICENSE-binary: List the dependency libraries used in Gluten.
NOTICE-binary: List the licenses used with the dependency libraries in Gluten.
n/a

[CORE] Update LICENSE, NOTICE, LICENSE-binary, NOTICE-binary

---

ep/build-velox/src/get_velox.sh

Protobuf needs to be built and installed prior to HDFS, then HDFS build can use it. CMake version needs to be upgraded to meet velox's requirement.
The code change comes from https://github.com/apache/incubator-gluten/pull/6424.
CI.

[VL] Branch-1.2: Port some fix for velox build from PR 6424

---

.github/workflows/clickhouse_be_trigger.yml
.github/workflows/velox_docker.yml
tools/gluten-te/centos/dockerfile-buildenv
tools/gluten-te/ubuntu/defaults.conf
tools/gluten-te/ubuntu/dockerfile-buildenv
tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs/README.md
tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs/run.sh
tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs/scripts/all.sh

Part of https://github.com/apache/incubator-gluten/issues/6265.
See [README](https://github.com/apache/incubator-gluten/blob/32f10318afbb818605bb626f045af38a3e6b96ba/tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs/README.md) for details.

[VL] Add a way to create static build with docker container and gluten-te

---

cpp-ch/local-engine/AggregateFunctions/AggregateFunctionGroupBloomFilter.h
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Common/GlutenSignalHandler.cpp
cpp-ch/local-engine/Disks/ObjectStorages/registerGlutenDiskObjectStorage.cpp
cpp-ch/local-engine/Functions/FunctionsBloomFilter.h
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
cpp-ch/local-engine/Parser/JoinRelParser.h
cpp-ch/local-engine/Shuffle/PartitionWriter.h
cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
cpp-ch/local-engine/tests/gtest_ch_join.cpp
cpp-ch/local-engine/tests/gtest_clickhouse_54881.cpp
cpp-ch/local-engine/tests/gtest_parquet_columnindex.cpp
cpp-ch/local-engine/tests/gtest_parser.cpp

Fix build due to https://github.com/ClickHouse/ClickHouse/pull/66404 to avoid merge https://github.com/apache/incubator-gluten/pull/6459
(Fixes: \#6467)
Existed UTs

[GLUTEN-6467][CH] Minor Fix Build

---

tools/gluten-it/common/src/main/java/org/apache/gluten/integration/BaseMixin.java
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/clickbench/ClickBenchSuite.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/ds/TpcdsSuite.scala
tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/h/TpchSuite.scala
tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs/scripts/all.sh

1. New gluten-it option `--data-dir`
2. A minor follow up to https://github.com/apache/incubator-gluten/pull/6457

[VL] Minor improvements and fixes for gluten-it and gluten-te

---

backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala

The project with `input_file_name` expression may have multiple data source by union all, reference:
https://github.com/apache/spark/blob/e459674127e7b21e2767cc62d10ea6f1f941936c/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/rules.scala#L519
For example, pulls the protocol and metadata of the delta lake table from the files
https://github.com/delta-io/delta/blob/074ce173bb070ed60f10e98d3ef7dcc04cc2a744/core/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala#L209
UT.

[VL] Fix offload input_file_name assert error

---

dev/builddeps-veloxbe.sh

Function setup_macos of build_helper_functions.sh need variable `ARCH`.
Local test.

[BUILD] Fix unbound variable

---

dev/vcpkg/setup-build-depends.sh

Replace the mirrorlist repository of centos with vault.
(Fixes: \#6437)
Test the vcpkd setup scripty on the centos7/8 container:
```bash
podman run --name wechar_gluten --cap-add=SYS_PTRACE --cap-add=AUDIT_WRITE --pids-limit 0 -it --rm  -w /root/workspace --network host --entrypoint bash centos:7
gluten/dev/vcpkg/setup-build-depends.sh
```

[GLUTEN-6437][BUILD] Fix vcpkg setup-build-dependens.sh for centos

---

backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
backends-clickhouse/src/main/delta-23/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteTaskNotSerializableSuite.scala
gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinity.scala

When inserting mergetree data, it occurs the Task not serializable error in some cases.
RC:
In the Delta, the options of the `DeltaOptions` is a `CaseInsensitiveMap`, if calling the api `filterKeys()` of the `CaseInsensitiveMap`, it may become not serializable, so lead to this error.
Close #6470.
(Fixes: #6470)

[GLUTEN-6470][CH]Fix Task not serializable error when inserting mergetree data

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/expression/DateAddTransformer.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
cpp-ch/local-engine/Parser/scalar_function_parser/timestampAdd.cpp
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala

[GLUTEN-6425][CH] Support day time internval

---

cpp/velox/operators/writer/VeloxParquetDatasource.cc
cpp/velox/operators/writer/VeloxParquetDatasource.h

Remove the redundant code in file VeloxParquetDatasource.cc to avoid  memory  leakage
#6430
CI.

[VL] remove redundant code in parquet datasource to avoid memory leakage PR6430

---

backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala

[VL] Branch-1.2: Fix offload input_file_name assert error

---

cpp-ch/local-engine/Parser/AdvancedParametersParseUtil.cpp
cpp-ch/local-engine/Parser/AdvancedParametersParseUtil.h
cpp-ch/local-engine/Parser/CrossRelParser.cpp
cpp-ch/local-engine/Parser/JoinRelParser.cpp

Fixes: #6463
part of to support `CartesianProductExec`
unit tests

[GLUTEN-6463][CH]refactor the code of parsing join parameters

---

backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
gluten-core/src/main/scala/org/apache/gluten/planner/cost/GlutenCostModel.scala
tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs/README.md

This is to align the default cost model in RAS as much as possible with the heuristic query planner. To make RAS be able to pass more UTs with the minimal impact from default cost model.
Also do some minor code improvements.

[VL] RAS: Make default rough cost model exhaustively offload computations

---

gluten-data/src/main/java/org/apache/gluten/memory/listener/ManagedReservationListener.java

Print the error early to log to avoid further error handling/reporting issues.

[VL] Print exception early when raised from ManagedReservationListener#unreserve

---

backends-clickhouse/src/main/java/org/apache/gluten/vectorized/CHNativeExpressionEvaluator.java
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxBackendWrite.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/gluten/execution/CartesianProductExecTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/execution/JoinUtils.scala
gluten-core/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
gluten-core/src/main/scala/org/apache/gluten/utils/SubstraitUtil.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenColumnarWriteFilesExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/SparkWriteFilesCommitProtocol.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/GlutenV1WriteCommandSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
gluten-ut/spark35/src/test/backends-velox/org/apache/gluten/GlutenColumnarWriteTestSupport.scala

(Fixes: \#6067)
This PR Refactors Velox side code,  rename `VeloxColumnarWriteFilesExec` to `GlutenColumnarWriteFilesExec`, move it to gluten-core, so that Clickhouse backend can use the same SparkPlan in the followup PR.
By supporting spark 3.4, Velox supports whole stage native write pipeline which is better than old implementation, clickhouse backend also adopt such implementation.
The only major difference between velox and clichouse is how to parse native metrics. which I introduce a new trait called `BackendWrite`, it only has one member now. Once native write pipeline is compeleted,  we get it by `BackendsApiManager.getSparkPlanExecApiInstance.createBackendWrite`, Please see `VeloxBackendWrite` for details
``` scala
trait BackendWrite {
def collectNativeWriteFilesMetrics(batch: …
```

[GLUTEN-6067][VL] [Part 3-1] Refactor: Rename VeloxColumnarWriteFilesExec to ColumnarWriteFilesExec

---

ep/build-velox/src/get_velox.sh

sed doesn't report error if given pattern is not matched. It's possible our expected changes are not applied to velox setup script due to upstream's code change. Here, simply run grep command to ensure pattern matched.
Only do the check for setup-ubuntu.sh, since other scripts like setup-centos7.sh, setup-centos8.sh are not maintained in upstream velox now.
CI/local.

[VL] Ensure sed pattern can be matched when modifying velox setup scripts

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHBroadcastNestedLoopJoinExecTransformer.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSParquetSortMergeJoinSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
cpp-ch/local-engine/Parser/CrossRelParser.cpp
cpp-ch/local-engine/Parser/JoinRelParser.cpp

[GLUTEN-6463][CH] Enable cartesion product

---

ep/build-velox/src/get_velox.sh

Remove the fix for stringop-overflow warning as this has been fixed on the Velox side.
Also, ADDITIONAL_FLAGS is no longer present inside `scripts/setup-helper-functions.sh`
Resolves #6523

[GLUTEN-6523][VL] fix: Remove fix for stringop-overflow warning in alinux3

---

cpp/CMake/ConfigArrow.cmake

[GLUTEN-6529][VL] Branch-1.2: Port #6530 to fix build error on macOS caused by ConfigArrow.cmake

---

docs/get-started/Velox.md

[VL][DOC] Branch-1.2: Port #6533 to add uniffle doc

---

gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala

current bug when partitioned column type contains timestamptz.
```
Caused by: org.apache.spark.sql.catalyst.parser.ParseException:
DataType timestamptz is not supported.(line 1, pos 0)
== SQL ==
timestamptz
^^^
at org.apache.spark.sql.errors.QueryParsingErrors$.dataTypeUnsupportedError(QueryParsingErrors.scala:239)
at org.apache.spark.sql.catalyst.parser.AstBuilder.$anonfun$visitPrimitiveDataType$1(AstBuilder.scala:2692)
at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:157)
at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:2662)
at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:58)
at org.apache.spark.sql.catalyst.parser.SqlBaseParser$PrimitiveDataTypeContext.accept(SqlBasePar …
```

[GLUTEN-6509] enable read iceberg table with timestamptz as partitioned column.

---

cpp/core/jni/JniCommon.h
cpp/core/memory/AllocationListener.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/velox/memory/VeloxMemoryManager.h

fix #6525
VeloxRuntime is shared by many threads, like task threads or parquet writter threads. We must make sure the objects hold by VeloxRuntime are thread safe.

[VL] Add thread_safe to several VeloxRuntime classes

---

.gitignore

Add `ep/_ep/` to `.gitignore`, it is arrow build directory.
https://github.com/apache/incubator-gluten/blob/9bbeb9f81397f03465a6b44982e4924d8c6c51b1/dev/build_arrow.sh#L21
manual Test

[MINOR] Add ep/_ep/ to .gitignore

---

dev/package-vcpkg.sh

The mvn package commands have been executed in `buildbundle-veloxbe.sh`, so we need to remove the duplicate mvn package commands in `package-vcpkg.sh`.
manual test

[MINOR][VL] Remove duplicate mvn packages

---

cpp/core/jni/JniCommon.h
cpp/core/memory/AllocationListener.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h

A follow-up to #6526
1. Use the old way before https://github.com/apache/incubator-gluten/pull/5770 for block reservation because
* It uses same algorithm for `diff < 0` and `diff > 0` so simplifies code
* It reduces code branches
2. Code `peakBytes_.store(std::max(peakBytes_.load(), usedBytes_.load()))` is still not atomic so needs to be locked

[VL] Following #6526, minor fixes and improvements

---

cpp/CMakeLists.txt
cpp/velox/tests/CMakeLists.txt
cpp/velox/tests/MemoryManagerTest.cc

Building Gluten tests [depends on gluten benchmark ](https://github.com/apache/incubator-gluten/blob/main/cpp/velox/tests/CMakeLists.txt#L32), this pr decouples them.
Fixes: #6562 
I successfully built gluten tests with `./compile.sh --build_velox_backend=ON --build_tests=ON --build_examples=ON` that BUILD_BENCHMARKS is not enabled

[GLUTEN-6562][VL] Decouple BUILD_BENCHMARKS and BUILD_TESTS build options

---

cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/config/VeloxConfig.h
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

Add config `spark.gluten.sql.columnar.backend.velox.showTaskMetricsWhenFinished` for show velox task metrics when finished, it helps debug task level execution.

[VL] Add config for show velox task metrics when finished

---

cpp/velox/compute/WholeStageResultIterator.cc

Fixes https://github.com/apache/incubator-gluten/issues/6477

[GLUTEN-6477][VL] Fix occasional dead lock during spilling

---

.github/workflows/velox_weekly.yml
dev/build_helper_functions.sh
dev/builddeps-veloxbe.sh
ep/build-velox/src/get_velox.sh
ep/build-velox/src/setup-centos7.sh
ep/build-velox/src/setup-centos8.sh

These two scripts are not kept in upstream velox now.
CI/Weekly build job.

[VL] Move setup-centos7.sh & setup-centos8.sh into Gluten and clean up some script code

---

ep/build-velox/src/get_velox.sh

```
1c0cfac50 (upstream/main) Fix build of remote function target in monolithic build (#10557)
eee69d75a Move timezone conversion under velox_type_tz (#10547)
82bde6ddb Add Spark json_object_keys function (#10449)
e5671c09c Add min, max Spark aggregate functions (#9868)
709dab2dc Fix MultiRange filter to correctly handle NaN input (#10535)
01a9df46b Remove unused code in bm_utils.cpp (#10493)
ba35860b2 Fix the state.data == nullptr exception in smj (#10509)
40122c6a9 Extract reusable functions for SQL generation in fuzzer test (#10545)
ed9e5b636 Use orderable type in Spark max_by and min_by (#10525)
d30b16c14 Add support for sse on MacOS (#10519)
d187346e0 Document the choice between simple function and vector function (#10528)
698a969b6 Fix memory leak in HashBuild operator (#10513) …
```

[VL] Daily Update Velox Version (2024_07_25) 

---

.github/workflows/velox_weekly.yml

To add Centos9 also to weekly builds.

[VL] Update to add centos9 for weekly build

---

backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxParquetDataTypeValidationSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala

Pending https://github.com/facebookincubator/velox/pull/10474

[VL] Enable timestamp in parquet write

---

gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQuerySuite.scala
gluten-ut/test/src/test/scala/org/apache/gluten/sql/SQLQuerySuite.scala

This is a test for gluten core code which makes correct transition nodes are added when vanilla spark columnar scan is used. Should be placed in a common test module to ensure the relevant core code is still tested after spark-3.2 test is removed in the future.
CI.

[Minor] Move a test from spark-3.2 module to a common test module

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/clickhouse/MergeTreeFileFormatDataWriter.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala

修复mergetree的分区带空格时报错
(Fixes: \#6604)
UT

[GLUTEN-6604][CH] Fix mergetree partition with whitespace error

---

cpp/velox/shuffle/VeloxSortShuffleWriter.cc
cpp/velox/shuffle/VeloxSortShuffleWriter.h

Bug fix
```
/Users/zml/Desktop/git_hub/incubator-gluten/cpp/velox/shuffle/VeloxSortShuffleWriter.cc:281:24: error: no matching function for call to 'min'
auto size = std::max(std::min((uint64_t)memLimit >> 2, 64UL * 1024 * 1024), minSizeRequired);
```
Local test.

[VL] Fix std::min params type mismatch in Apple clang 15

---

backends-clickhouse/src/main/java/org/apache/gluten/vectorized/StorageJoinBuilder.java
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHBroadcastNestedLoopJoinExecTransformer.scala
backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHJoinValidateUtil.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSParquetSortMergeJoinSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHHashBuildBenchmark.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
cpp-ch/local-engine/Join/BroadCastJoinBuilder.h
cpp-ch/local-engine/Parser/JoinRelParser.cpp
cpp-ch/local-engine/Parser/JoinRelParser.h
cpp-ch/local-engine/local_engine_jni.cpp

[GLUTEN-6544][CH] Support existence join

---

dev/build-thirdparty.sh
dev/package-vcpkg.sh
dev/package.sh

Improve package scripts:
+ Extract `build-thirdparty.sh` script
+ Set `PROMPT_ALWAYS_RESPOND=y` for package scripts
+ Pass package arguments to `buildbundle-veloxbe.sh`
+ Add build thirdparty for `package-vcpkg.sh`
Manual package test

[VL] Improve package scripts

---

gluten-data/pom.xml
pom.xml

There are some unnecessary dependencies in the `gluten-velox-bundle-spark3.5` jar.
`jackson-datatype-jsr310`:
`commons-codec`:

[MINOR] Reduce unnecessary dependencies

---

.github/workflows/velox_docker.yml
docs/get-started/ClickHouse.md
docs/get-started/Velox.md
pom.xml
tools/gluten-it/pom.xml

Celeborn 0.4.2 and 0.5.1 version have already been released, which release note refer to [Apache Celeborn™ 0.4.2 Release Notes](https://celeborn.apache.org/community/release_notes/release_note_0.4.2/) [Apache Celeborn™ 0.5.1 Release Notes](https://celeborn.apache.org/community/release_notes/release_note_0.5.1/) for more details. Therefore, celeborn module bumps 0.4.2 and 0.5.1 version.
Fixes: \#6632
CI.

[GLUTEN-6632] Bump Celeborn 0.4.2 and 0.5.1

---

cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/LocalPartitionWriter.h
cpp/core/shuffle/Spill.cc
cpp/core/shuffle/Spill.h
cpp/velox/shuffle/VeloxSortShuffleWriter.cc
cpp/velox/shuffle/VeloxSortShuffleWriter.h

TPCH SF3T 40000 shuffle partitions: 1794s -> 1612s (vs hash 2023s)
Before:
After:

[VL] Reduce spill in sort-based shuffle

---

backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
backends-clickhouse/src/main/delta-23/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/orc/OrcFileFormat.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
shims/spark32/src/main/scala/org/apache/spark/sql/hive/execution/HiveFileFormat.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/orc/OrcFileFormat.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/HiveFileFormat.scala

* Fix typo: isNativeAppliable -> isNativeApplicable.
* Use == for null-safe comparing the value of local properties.
* Remove the check of this local property in `supportBatch` method. `supportBatch` is only called in read path, which shouldn't be impacted by that property used for native write.
* Reset local properties used for native write before next setting.
Fix https://github.com/apache/incubator-gluten/issues/6612, which shows inconsistent query behavior caused by historical property setting.
CI/local test.

[GLUTEN-6612] Fix ParquetFileFormat issue caused by the setting of local property isNativeApplicable

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseNativeWriteTableSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHBucketSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseWholeStageTransformerSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseCountDistinctSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/parquet/GlutenParquetFilterSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetAQESuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetColumnarShuffleAQESuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetColumnarShuffleSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetGraceHashJoinSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetRFSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSortMergeJoinSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseDatetimeExpressionSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetAQEConcurrentSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetAQESuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetBucketSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetRFSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/gluten/NativeWriteChecker.scala

Move tpch/tpcds parquet test to tpch/tpcds package, so that we can run these tests in spark-3.5 ut
(Fixes: \#6067)
Using Existed UTs

[GLUTEN-6067][CH][MINOR][UT] Pass backends-clickhouse ut in Spark 3.5

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitParser.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc

Supports the push-down of IsNull and IsNotNull filter for row type.
Filter on subfield cannot be pushed-down, and we put them in the remaining filter.
With unit test.

[VL] Support row type and fix subfield in filter push-down

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Disks/ObjectStorages/CompactObjectStorageDiskTransaction.cpp
cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskS3.cpp
cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskS3.h
cpp-ch/local-engine/Disks/registerGlutenDisks.cpp
cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.cpp

[GLUTEN-6590][CH] Support compact mergetree file on s3

---

backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala
cpp-ch/local-engine/Common/ConcurrentMap.h
cpp-ch/local-engine/Common/QueryContext.cpp

optimize lock in queryContextManager, fix some test cases too slow 
unit tests

[CH] Fix some test cases too slow 

---

gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriter.scala
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarShuffleWriter.scala

After https://github.com/apache/incubator-gluten/pull/6432, if all of the ColumnarBatch have empty rows in `CHCelebornColumnarShuffleWriter`, the `nativeShuffleWriter` won't be initialized and causes `assertion failed`. The `VeloxCelebornColumnarShuffleWriter ` also has the same issue even without https://github.com/apache/incubator-gluten/pull/6432.
(Fixes: \#6656)
PASS CI

[GLUTEN-6656][CELEBORN] Fix CelebornColumnarShuffleWriter assertion failed

---

backends-velox/src/test/java/org/apache/gluten/test/VeloxBackendTestBase.java
gluten-core/src/main/scala/org/apache/gluten/planner/plan/GlutenPlanModel.scala
gluten-core/src/main/scala/org/apache/spark/util/SparkTaskUtil.scala
gluten-core/src/main/scala/org/apache/spark/util/TaskResources.scala
gluten-core/src/test/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumerTest.java
gluten-core/src/test/scala/org/apache/gluten/utils/TaskResourceSuite.scala
gluten-data/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatches.java
shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
shims/spark32/src/main/scala/org/apache/spark/TaskContextUtils.scala
shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
shims/spark33/src/main/scala/org/apache/spark/TaskContextUtils.scala
shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
shims/spark34/src/main/scala/org/apache/spark/TaskContextUtils.scala
shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
shims/spark35/src/main/scala/org/apache/spark/TaskContextUtils.scala
tools/gluten-it/sbin/gluten-it.sh

This could fix some issues like debug configurations not taking effect in native validation or similar issues. Generally we should pass all SQL configurations to code block of `TaskResources.runUnsafe` as if it's a real Spark task but is running on Driver.

[CORE] Propagate SQLConf to code block of TaskResources.runUnsafe

---

.github/workflows/velox_docker.yml
gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/gluten/uniffle/UniffleShuffleManager.java
gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java
pom.xml
tools/gluten-it/pom.xml

Apache Uniffle has released v0.9.0, of which release note could refer to [v0.9.0](https://github.com/apache/incubator-uniffle/releases/tag/v0.9.0) for more details. This pull request is aimed to support v0.9.0 of Uniffle.
Fixes: #6483.
CI.

[GLUTEN-6483] Support Uniffle 0.9.0

---

shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

Set default validation log level from `INFO` to `WARN`.
N/A

[VL] Set default validation log level to WARN

---

docs/get-started/Velox.md

Upgrade supported Uniffle version to 0.9.0 in `Velox.md`.
Follow up #6533.
No.

[GLUTEN-6483][VL][DOC] Upgrade Uniffle version to 0.9.0 in Velox.md

---

cpp/core/jni/JniWrapper.cc
cpp/core/memory/AllocationListener.cc
cpp/core/memory/AllocationListener.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/config/VeloxConfig.h
docs/developers/HowTo.md
shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala

`spark.gluten.backtrace.allocation` was added in https://github.com/apache/incubator-gluten/pull/3069 to print backtrace of large memory allocations into log.
The option was broken for a while and the PR is to recover the logic of it.
Additionally, option key `spark.gluten.backtrace.allocation` will be changed to `spark.gluten.memory.backtrace.allocation`.

[VL] Recover broken memory-trace option spark.gluten.backtrace.allocation

---

backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/EliminateLocalSort.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala

Follow up #6653 .
Offload date type range frame window rewrite orderSpec, it will produce new local sort. Pre local sort is unnecessary, so remove it.
```
sql("select max(l_partkey) over" +
" (partition by l_suppkey order by l_commitdate" +
" RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) from lineitem ").collect()
```
before PR
```
+- == Final Plan ==
VeloxColumnarToRowExec (15)
+- ^ ProjectExecTransformer (13)
+- ^ WindowExecTransformer (12)
+- ^ SortExecTransformer (11)
+- ^ ProjectExecTransformer (10)
+- ^ SortExecTransformer (9)
+- ^ InputIteratorTransformer (8)
+- ShuffleQueryStage (6), Statistics(sizeInBytes=1175.3 KiB, rowCount=6.02E+4)
+- ColumnarExchange (5)
+- VeloxAppendBatches (4)
+- ^ ProjectExecTransformer (2)
+- ^ Scan parquet  (1)
```
after pr
```
+- == Final Plan == …
```

[VL] Eliminate pre local sort after offload date type range frame window

---

cpp-ch/local-engine/Shuffle/PartitionWriter.cpp

Revert https://github.com/apache/incubator-gluten/pull/6677
(Fixes: \#6701)

[GLUTEN-6701][CH] fix: Performace regression at 20240802 daily build

---

backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHMetricsApi.scala
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriter.scala

`VeloxCelebornColumnarShuffleWriter` supports `shuffleWallTime` metric of `VeloxMetricsApi` to calculate the overall shuffle write time for columnar shuffle exchange metrics in #6579. Therefore, `CHCelebornColumnarShuffleWriter` should also support `shuffleWallTime` to calculate the overall shuffle write time.
(Fixes: \#6695)
CI.

[GLUTEN-6695][CH] Introduce shuffleWallTime in CHMetricsApi to calculate the overall shuffle write time

---

cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

Here we check the corresbonding Velox function name, which is `hash_with_seed` now, and support the complex data type

[VL] Remove redundant hash function in substrait function validation

---

gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java

When all of the ColumnarBatch have empty rows in `VeloxUniffleColumnarShuffleWriter`, the `nativeShuffleWriter` is not initialized and causes `IllegalStateException`. `VeloxUniffleColumnarShuffleWriter` should send commit for all `ColumnBatch` with empty rows.
Follow up #6657.
(Fixes: \#6656)
CI.

[GLUTEN-6656][UNIFFLE] VeloxUniffleColumnarShuffleWriter should send commit for all ColumnBatch with empty rows

---

.github/workflows/velox_docker_cache.yml

Following changes in https://github.com/apache/incubator-gluten/pull/6616, update the image for caching.

[VL] Fix out-of-date centos 7 image in velox_docker_cache.yml

---

cpp-ch/clickhouse.version
cpp-ch/local-engine/Functions/SparkFunctionPositionUTF8.cpp
cpp-ch/local-engine/Storages/Output/OutputFormatFile.cpp
cpp-ch/local-engine/tests/benchmark_local_engine.cpp
cpp-ch/local-engine/tests/gtest_ch_join.cpp
cpp-ch/local-engine/tests/gtest_ch_storages.cpp
cpp-ch/local-engine/tests/gtest_local_engine.cpp

[GLUTEN-1632][CH]Daily Update Clickhouse Version (20240806)
