- gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
As title and mentioned in #4119
Close #4119
Add new Unit Test
> [GLUTEN-4119][VL] Skip report fallback operator: ReusedExchange, AdaptiveSparkPlan

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-4190][CH] Crush on flattening a const null column

- ep/build-velox/src/get_velox.sh
```
79c9754bc (upstream/main) Add to log reference count of active root pools (#8180)
601b98812 Add max_spill_bytes config (#8171)
75617ae1a Fix memory reservation in hash join spill (#8174)
```
> [VL] Daily Update Velox Version (2023-12-27) 

- backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Operator/DefaultHashAggregateResult.cpp
- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/RelParser.cpp
- cpp-ch/local-engine/Parser/RelParser.h
- cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
Fixes: #4115
For aggregate without any aggregate functions, CH needs to know in which aggregate stage it is.
unit tests
> [GLUTEN-4115][CH] Identify the final aggregate stage of aggregating without aggregate functions

- ep/build-velox/src/get_velox.sh
```
59f6a091f (upstream/main) Refactor spiller constructors (#8184)
ab15325df Add more e2e max spill bytes test (#8182)
b9f801c18 Add log when checkpointing a ssd shard (#8183)
```
> [VL] Daily Update Velox Version (2023-12-28)

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
> [GLUTEN-4202][CH] HashSelectorBuilder: null rows may have different nested values

- docs/get-started/Velox.md
fix typo related to markdown grammar.
no need to test, just doc
> [VL][DOC] Fix the package name in Velox.md

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20231229)

- ep/build-velox/src/get_velox.sh
```
4e86285bd (upstream/main) Register memory reclaimers for parquet writer mem pools (#8166)
e6f84e8ac Make spillPool a member of MemoryManager (#8191)
4452585c0 Fix SharedArbitrator.taskWaitTimeout (#8195)
```
> [VL] Daily Update Velox Version (2023-12-29)

- .github/workflows/velox_tpch_merge.yml
> [VL] Minor fix for CI

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Shuffle/NativeSplitter.h
- cpp-ch/local-engine/Shuffle/ShuffleSplitter.h
- cpp-ch/local-engine/Storages/IO/CompressedWriteBuffer.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
- cpp-ch/local-engine/local_engine_jni.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240102)

- backends-clickhouse/pom.xml
- backends-velox/pom.xml
- gluten-celeborn/clickhouse/pom.xml
- gluten-celeborn/common/pom.xml
- gluten-celeborn/package/pom.xml
- gluten-celeborn/pom.xml
- gluten-celeborn/velox/pom.xml
- gluten-core/pom.xml
- gluten-data/pom.xml
- gluten-delta/pom.xml
- gluten-iceberg/pom.xml
- gluten-ui/pom.xml
- gluten-ut/common/pom.xml
- gluten-ut/pom.xml
- gluten-ut/spark32/pom.xml
- gluten-ut/spark33/pom.xml
- gluten-ut/spark34/pom.xml
- package/pom.xml
- pom.xml
- shims/common/pom.xml
- shims/pom.xml
- shims/spark32/pom.xml
- shims/spark33/pom.xml
- shims/spark34/pom.xml
- substrait/substrait-spark/pom.xml
- tools/gluten-it/common/pom.xml
- tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/SparkRunModes.java
- tools/gluten-it/package/pom.xml
- tools/gluten-it/pom.xml
- tools/workload/tpcds/run_tpcds/run_tpcds.sh
> [CORE] Version bump to 1.2.0-SNAPSHOT

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenFormatWriterInjectsBase.scala
- shims/common/src/main/scala/io/glutenproject/execution/datasource/GlutenFormatWriterInjects.scala
- shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala
Follow up https://github.com/oap-project/gluten/pull/3690 to resolve the [comment](https://github.com/oap-project/gluten/pull/3690#discussion_r1436860178).
> [VL]Move getExtendedColumnarPostRules method into shim layer

- ep/build-velox/src/get_velox.sh
```
8252a15ca (upstream/main) Remove unused exception parameter from files inc velox/exec/Task.cpp (#8227)
10050193b Fix typos and comments in inputStream related classes (#8185)
7f9ec965f Remove unused exception parameter from velox/common/base/VeloxException.cpp (#8224)
24a3623d0 Remove unused exception parameter from velox/common/caching/CachedFactory.h (#8223)
eeb693936 Remove unused exception parameter from velox/common/memory/MmapAllocator.cpp (#8226)
b60f8ad8a Remove unused exception parameter from velox/vector/arrow/Bridge.cpp (#8225)
fd2d2be78 Fix error message in map_values Presto function (#8210)
1a6b49de8 Update GCC minimum version to 9 (#8215)
```
> [VL] Daily Update Velox Version (2024-01-03)

- cpp/velox/substrait/SubstraitToVeloxPlan.cc
The check logic seems doing nothing actually.
> [VL] Remove file format check for pushed down filters

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionHashingExtended.h
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala
Fixes: \#3943, also close https://github.com/oap-project/gluten/issues/2341
> [GLUTEN-3943][CH] Support complex input arguments for sparkMurmurHash3_32, and switch default hash algorithm to sparkMurmurHash3_32 

- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- pom.xml
Upgrade spark 34 version to 342.
> [CORE] Upgrade spark 34 version to 342

- gluten-core/src/main/scala/org/apache/spark/util/TaskResources.scala
- gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
Below code can cause heavy GC, especially when AQE is on with large number of coalesced partitions.
Assuming 8000 shuffle mapper tasks, 8000 shuffle partitions and 200 reducer tasks (mapper output coalesced, each reducer reads 8000/200 = 40 partitions from each mapper), 8 tasks per executor.
There will be ~ 40 partitions * 8000 mappers * 8 tasks = 2560000 objects being added to `TaskResource` per executor JVM.
```
TaskResources.addRecycler(s"ShuffleReaderDeserializationStream_${wrappedOut.getId}", 50) {
this.close()
}
```
> [VL] Remove DeserializationStream from TaskResource when close() is called

- substrait/substrait-spark/src/test/scala/io/substrait/spark/TPCDSPlan.scala
Reverts oap-project/gluten#4282
> Revert "[GLUTEN-3559][VL] Fix TPCDS Plan Suite"

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
Currently velox does not support the char type of orc.
```
Error Code: UNKNOWN
Reason: {} not supported yet.CHAR
Context: Split [Hive: oss:///user/hive/warehouse/tpcds_1000.db/customer/000003_0 64101152 - 7199294] Task Gluten stage-3 task-2073
Top-Level Context: Same as context.
Function: kind
File: ../../velox/dwio/dwrf/common/FileMetadata.cpp
Line: 100
```
> [VL] Add orc char type validation

- ep/build-velox/src/get_velox.sh
```
8321b3e03 (upstream/main) Add error log in ~MemoryManager (#8262)
8ff2246f6 Add December 2023 monthly update (#8264)
b35147702 Support fuzzing expressions with specific output type in ExpressionFuzzer. (#7976)
3589be95c Remove tests of debug time checks (#8261)
ff6a31fe5 Use string output stream from flex scanners (#8244)
c9878702b Fix flaky AggregationTest.reclaimFromAggregation (#8255)
4cd534b0d Fix GA scheduled job of spark fuzzers (#8251)
8e59fa1fb Optimize casting generic writer to primitives. (#8193)
0616e4ccc Optimizing casting GenericView to primitives. (#8192)
a289ac7eb Improve tmToString and relating document (#8250)
0e25d474c Fix approx_distinct for TIMESTAMP inputs (#8164)
b42ace1a5 Back out "Change cpu driver slicing limit to 1 second by default" (#8248)
4c90d8bc2 Minor …
```
> [VL] Daily Update Velox Version (2024-01-05)

- cpp-ch/local-engine/Functions/SparkFunctionFloor.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
This reverts commit 026e67f2de2e6c8318d5dc060f47b36ee1501dc6.
Please see #4306 for details
> Revert "[GLUTEN-4249][CH]Improve cast (#4250)"

- ep/build-velox/src/get_velox.sh
fix boost download, the jfrog repo is invalid since last weekend
pass GHA
> [VL] CI: fix boost download

- ep/build-velox/src/get_velox.sh
```
75a5dca57 (upstream/main) Remove Wshadow warning for velox/dwio/common/FilterNode.h (#8266)
c5aa05ff4 Add config of DirectInputBuffer to Connector (#7978)
76e603ab2 Update TaskTest to verify executionEndTimeMs and terminationTimeMs (#7546)
dc0a28d7a Bound the size of Expr's sharedSubexprResults_ to prevent OOMs (#8128)
1f0f59461 Add benchmarks-build target to Makefile (#8162)
191ecf65b Simplify the calculation of the number of pages (#8256)
dd9a34d39 Remove unused exception parameter from files inc velox/common/caching/AsyncDataCache.cpp (#8246)
338e2da75 Support timezone offsets in timezone_hour/minute (#8269)
b5c78f962 Add documentation for memory management (#8271)
e5355f366 Add physicalWrittenBytes to PlanNodeStats (#8213)
7376fb29f Fix LocalExchangeSource timeout (#8101)
```
> [VL] Daily Update Velox Version (2024-01-08)

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxLiteralSuite.scala
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Add binary,struct,decimal support for array lit. And do code refactor to reduce duplicate logic to match scalar types literals.
UT.
> [VL] Add binary, struct, decimal support for array literal

- .github/workflows/velox_be.yml
- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
- backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
- backends-velox/src/main/scala/org/apache/spark/sql/catalyst/FlushableHashAggregateRule.scala
- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
- cpp/velox/compute/WholeStageResultIterator.cc
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
A follow-up to https://github.com/oap-project/gluten/pull/4130
Enable FlushableHashAggregateRule to convert eligible hash agg to flushable agg.
> [VL] Enable FlushableHashAggregateRule

- ep/build-velox/src/get_velox.sh
```
a1368a29c (upstream/main) Mark constant arguments of regexp_replace and empty_approx_set Presto functions (#8283)
4fd818691 Optimize add_items for strings. (#8200)
b78dd54e4 Add flat fast path for add_items for primitives. (#8201)
11185951a Add support for allocations that exceed the PageRun limit (#8298)
020cb8270 Honor distinct in Aggregates in QueryRunner (#8284)
f9e2782d7 Remove redundant flag set in CMake (#8306)
87b06fbd5 Disable build ZLIB when building cpr (#8257)
fd920aa07 Add support for aggregation fuzzer to call Presto java and setup CI run. (#7947)
005e5457d Add replace SparkSQL function (#4922)
3ac35c987 Do not use session based file create config in datasink (#8294)
b82b7f822 Make ScopedTestTime compile outside of debug mode (#8130)
cb1dd4393 Optimize add_items with out …
```
> [VL] Daily Update Velox Version (2024-01-10)

- .github/workflows/velox_be.yml
Use new docker image in GHA workflow
pass GHA
> [VL] Use new docker image in GHA workflow

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240111)

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-4376][CH] Fix parse exception when parsing post_join_filter in JoinRelParser

- gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
Currently, the node fallback reasons for subqueries are missing from the `Fallback Summary`, this pr will supplement it.
before:
atfer
> [CORE] Add fallback summary for subqueries

- ep/build-velox/src/get_velox.sh
```
8f0dd8 Remove partition columns before writing partitioned file (8089)
5dc23c Add ngrams Presto function. (8209)
```
> [VL] Daily Update Velox Version (2024-01-16)

- .github/workflows/velox_be.yml
Increase maven downnload retry count to 3
pass GHA
> [VL][CI] increase maven download retry count

- tools/gluten-te/centos/dockerfile-build
- tools/gluten-te/ubuntu/dockerfile-build
This PR was raised to address [this comment](https://github.com/oap-project/gluten/pull/4397#issuecomment-1891340664)
I am attempting to resolve this problem by enabling ABFS (Azure Blob FileSystem).
> [VL][CI] Enable abfs in building velox to install its dependencies in docker image

- dev/builddeps-veloxbe.sh
- ep/build-velox/src/build_velox.sh
Add NUM_THREADS argument to limit compilation parallelism
Fixes: #4122
> [GLUTEN-4122][VL] Add num_threads option to limit build threads for velox

- ep/build-velox/src/get_velox.sh
```
cea6a5 Fix shadowed variable in velox/expression/CastExpr-inl.h (8400)
842803 Reduce link parallelism to fix compilation OOM's (8403)
1ea0ff Fix format of documentation in SimpleAggregateAdapter.h (8402)
1ca874 Optimize computation of partition start rows in SortWindowBuild (7580)
2f9be0 Refactor HashBuild arbitration test (8376)
e2af9d Rename getDataType and getDataChannels funcs in HiveDataSink (8404)
82bcd3 Fix creation of DuckDB tables with arrays of boolean, tinyint and smallint (8408)
eb09be Actually ensure deterministic order of map keys in multimap_from_entries Presto function (8407)
587b5e Run Join Fuzzer on PRs (8414)
5a3c7f Extract initializeVerifiers and compareEquivalentPlanResults in AggregationFuzzer (8361)
d3f7b3 Refactor simdjson utilities (8397)
45d9f8 Use simdjson …
```
> [VL] Daily Update Velox Version (2024-01-18)

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala
- gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
- gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
This pr unifies order direction transform code and cleanup duplicate code
Pass CI
> [CORE] Unify order direction transform

- cpp/velox/shuffle/VeloxShuffleWriter.cc
`VeloxShuffleWriter.cc` has an unclosed braces in "PROCESSAVX".
> [VL][Minor] Fix a format issue of unclosed braces

- ep/build-velox/src/get_velox.sh
```
063f2b Mismatch tags take 2 (8461)
5db9d8 Preserve recursive encodings while serializing PrestoPage (8249)
063f2b Refactor struct Converter and reduce template parameters (7915)
```
> [VL] Daily Update Velox Version (2024-01-22)

- ep/build-velox/src/get_velox.sh
```
a0fc4225b Fix documentation for HiveConfig hive.s3.use-instance-credentials (8309)
fce32e4d0 Make nulls initialValue to false in EvalCtx#ensureErrorsVectorSize (8479)
892375631 Fix invalid write in ensureWritable (8450)
8c74d3e99 Add find_in_set Spark function (8358)
38f0b560f Fix int64::max() to double conversion issue (8177)
8bfebb3d1 Add support for tinyint/smallint inputs for date_add/sub Spark functions (8379)
3949a3bb3 Remove Wshadow warning for velox/type/Filter.h (8267)
a94ed0e1d Add SingleThreadedTaskCursor (8406)
```
> [VL] Daily Update Velox Version (2024-01-24)

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Operator/GraceMergingAggregatedStep.cpp
> [GLUTEN-4521][CH] Fixed bugs in `GraceMergingAggregatedTransform` which makes data lost

- backends-velox/src/main/scala/io/glutenproject/utils/SharedLibraryLoaderDebian11.scala
- dev/package.sh
This PR fixes the issues which causes hdfs reads to fail on debian 11
(Fixes: #4141)
Manual testing with HDFS reads.
> [GLUTEN-4141][VL] Fix HDFS not working in debian 11

- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Enable working UTs for Gluten Cast Suites
(Fixes: #3559 )
Enabled UT run successfully
> [GLUTEN-3559][VL] Enable passing tests in Gluten Cast Suites for Spark 3.3, 3.4

- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
The Gluten String Functions Suite run successfully
(Fixes: #3559 )
Ran the tests locally
> [GLUTEN-3559][VL] Enable GlutenStringFunctionsSuite

- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
> [GLUTEN-4542][CH]Remove PullingPipelineExecutor in SubstraitFileSource

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCollectionExpressionsSuite.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCollectionExpressionsSuite.scala
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCollectionExpressionsSuite.scala
Fixes GlutenCollectionExpressionsSuite
(Fixes: #3559)
Tests ran locally
> [GLUTEN-3559][VL] Fix GlutenCollectionExpressionSuite

- dev/vcpkg/setup-build-depends.sh
This change adds support for Ubuntu 18 builds by adding the necessary setup steps in `dev/vcpkg/setup-build-depends.sh`
(Fixes: \#4548)
This was tested by running the setup script and a full build with vcpkg enabled on Ubuntu 18.
> [GLUTEN-4548][VL] Ubuntu 18 Support

- gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
When the plan contains SortAggregateExec, Gluten will tag the plan as not transformable if replaceSortAggWithHashAgg is disabled or columnarHashAgg is disabled. Even when the plan is marked as not transformable, Gluten will try to generateHashAggregateExecTransformer which is redundant in this case since plan is already marked as not transformable.
> [Core][Minor] Do not transform SortAggExec if columnar hashagg is disabled

- cpp/core/CMakeLists.txt
> [VL] Remove some legacy code in a CMakeLists.txt

- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenStringExpressionsSuite.scala
- gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenStringExpressionsSuite.scala
- gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenStringExpressionsSuite.scala
Fixes GlutenStringExpressionSuite
(Fixes: #3559)
Locally ran UTs
> [GLUTEN-3559][VL] Fix GlutenStringExpressionsSuite

- cpp-ch/local-engine/Storages/IO/NativeReader.h
> [GLUTEN-4596][CH] Clear unused codes

- cpp/velox/operators/functions/RegistrationAllFunctions.cc
- ep/build-velox/src/get_velox.sh
```
92f380b4d  Eliminate redundant Expr::addNulls calls (#8616)
09d07d3e7  Fix doc-gen-job so that it has 3 retries before failing. (#7706)
f4c326d7e  Add flag for registering Presto compatible signatures for Bitwise_*_agg functions (#8491)
eb6b585bb  Cleanup circleci script (#8618)
37ba7cb4c  Break up AllTypes.nonSortedSpillFunctions test (#8621)
d66b18f1d  Change cast(double as json) to pad 0 and use scientific notation (#8498)
a94509425  Make DuckDbQueryRunner.createTable flush once after all rows are written instead of after every row (#8611)
3beff35f3  Optimize copying primitive type vectors (#8617)
fbbeb5664  PyVelox implementation for Array Vector (#6100)
280fc8611  Add fmt::format_as for SpillStats and MemoryArbitrator::Stats (#8608)
a65afdb43  Make LocalExchangeSource.stop_ …
```
> [VL] Daily Update Velox Version (2024-02-01)

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Storages/IO/NativeReader.cpp
> [GLUTEN-4603][CH]Handle complex type in native reader

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecApiImpl.scala
- backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
- gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
Support map_entries function in Gluten)
UT
> [VL]Support map_entries function in Gluten

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- gluten-core/src/main/scala/io/glutenproject/extension/RewriteDateTimestampComparisonRule.scala
> [GLUTEN-4615][CH] Cover more cases in `RewriteDateTimestampComparisonRule `

- ep/build-velox/src/get_velox.sh
This is simply a follow-up for https://github.com/oap-project/gluten/pull/4606, as we found the program on ubuntu is also broken when hdfs is enabled.
Local test.
> [VL] Fix setup script for Velox dependencies

- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-4632][CH] Support asynchronous reading of hdfs

- gluten-ut/common/src/test/scala/io/glutenproject/utils/BackendTestSettings.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsCommonTrait.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
Close #4594
1. Replace logging ignore info with using scala test ignore function.
2. Improve test function name, ref to https://github.com/oap-project/gluten/pull/4581#pullrequestreview-1861276240
CI Unit Test
> [GLUTEN-4560][SUB-4] Let test framework track ignored tests and revise test function name

- dev/builddeps-veloxbe.sh
use hw.physicalcpu instead of nproc on MacOS
(Fixes: \#4636)
> [GLUTEN-4636][VL] Fix build script for Velox on MacOS

- ep/build-velox/src/get_velox.sh
```
b5d6982e6  Add 'opCall' member to OpCallInfo. (#8649)
3c5d8647a  Throw kFileNotFound in all storage adapters (#8662)
985d1debd  Delete unused max_arbitrary_buffer_size config (#8675)
f04cbb70a  Add support for aggregations over distinct inputs to StreamingAggregation (#8176)
0b79da99b  Fix wrong cast in DecimalUtil::divideWithRoundUp() (#8599)
7f9914bcf  Add support for deserialization of all-null columns serialized as UNKNOWN type (#8355)
f0885cd69  Add support for deserializing a single column in presto page format (#8354)
327677edc  migrate from nested-name ReadHolder (assorted) (#8659)
c30fa9d26  Measure Stripe count (#8542)
735b8f4c0  Use Microseconds for decoding time (#8589)
```
Existing unit tests
> [VL] Daily Update Velox Version (2024-02-06)

- ep/build-velox/src/get_velox.sh
```
e4a2ce2e8  Document regexp_extract_all(string, pattern) Presto function (#8689)
5f57033e4  Add TraceHistory and beef up TraceContext usages (#8677)
18c170103  Add test coverage for PrestoSerializer de/serializing Arrays/Maps with encoded elements/values (#8588)
7a07e9894  Optimize LikeGeneric (#8686)
8488251ab  Fix ExchangeQueue::dequeueLocked (#8685)
a3f4dcbec  Fix compile issue when building test (#8674)
5940dd377  Handle timezone in timstamp to varchar cast (#8563)
```
Existing unit tests
> [VL] Daily Update Velox Version (2024-02-07) 

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240208)

- docs/developers/docker_ubuntu22.04.md
- ep/build-velox/src/get_velox.sh
```
a3a57cbf5 (HEAD -> upstream_main, upstream/main) Add date_from_unix_date Spark function (#8672)
080b78571 Fix min_by/max_by(x, y, n) (#8566)
320f578ce Created an expression runner for Spark functions (#8341)
c51abe36b Fix incorrect result of first_value/last_value functions (#8626)
7830d641d Support UNKNOWN type in exporting to Arrow array (#8724)
76b5d0e92 Remove deprecated ExchangeSource::request(maxBytes) API (#8727)
7b68a8263 Passing 'skip.header.line.count' to SerDeOptions::nullString. (#8722)
9cf0ef0f5 Fix HashBuild unspilling stuck (#8715)
6a4048810 Add array_repeat Spark function (#8630)
9838c7e10 Remove deprecated ExchangeSource::supportsFlowControlV2 API (#8714)
d1d4f1e1d Refactor Parquet Statistics (#8658)
cfa113317 Make special form names case insensitive (#8709)
98c805a71 …
```
> [VL] Daily Update Velox Version (2024-02-12) 

- ep/build-velox/src/get_velox.sh
2024-02-15 16:29:43 -0800 9c79ef96f by Jimmy Lu, Return remaining bytes from exchange sources (#8758)
2024-02-15 14:21:55 -0800 20379570e by Orri Erling, Scatter struct nulls when deserializing Presto wire format (#8526)
2024-02-15 11:45:58 -0800 ec6741c94 by Ankita Victor, Add weekday Spark function (#8721)
2024-02-15 11:24:18 -0800 27bbff5a8 by Pramod, Split window aggregate tests (#8056)
2024-02-15 08:06:02 -0800 615af5158 by rrando901, Add Decimal support to set_agg and set_union (#7936)
2024-02-15 08:05:20 -0800 36071eb3b by lingbin, Fix typos in Memory Management documentation (#8756)
> [VL] Daily Update Velox Version (2024-02-16)

- ep/build-velox/src/get_velox.sh
```
76848b589 Remove unused variables in velox/expression/ComplexWriterTypes.h (#8781)
9ddbb9aeb Remove unused variables in velox/tpch/gen/dbgen/text.cpp (#8783)
164903523 Remove unused variables in velox/expression/CastExpr-inl.h (#8773)
c85058167 Remove unused variables in velox/dwio/common/ReaderFactory.cpp (#8774)
4243a7190 Move header & format check to Github Actions (#8546)
9882fdd85 Add support for proxy in S3FileSystem (#8574)
e3ec8bbad Add window function tests with decimal inputs (#7243)
dadade0d4 Remove unused exception parameter from velox/functions/lib/SubscriptUtil.cpp (#8767)
641f5587f Remove unused exception parameter from velox/functions/prestosql/FindFirst.cpp (#8766)
ad0baf0ce Remove unused exception parameter from velox/common/caching/AsyncDataCache.cpp (#8768) …
```
>  [VL] Daily Update Velox Version (2024-02-18) 

- gluten-core/src/main/java/io/glutenproject/vectorized/SplitResult.java
> [GLUTEN-4670][VL] Fix split time metric for celeborn

- backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHStreamReader.java
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
- cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
- cpp-ch/local-engine/Shuffle/ShuffleReader.h
- cpp-ch/local-engine/Storages/IO/NativeReader.cpp
- cpp-ch/local-engine/Storages/IO/NativeReader.h
- cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
- cpp-ch/local-engine/Storages/SourceFromJavaIter.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
> [GLUTEN-4660][CH]asynchronous shuffle read

- ep/build-velox/src/get_velox.sh
```
2024-02-22 19:02:50 -0800 0d02c8f9f by Pedro Eugenio Rocha Pedreira, Convert Arrow REE arrays to Velox Vectors (#8777)
2024-02-22 17:42:12 -0800 f951ddc18 by Krishna Pai, Fix Presto aggregate function 'avg' bug when counts are zero (#8719)
2024-02-22 14:11:30 -0800 577d85292 by Bikramjeet Vig, Fix data races flagged by tsan in ProfilerTest
2024-02-22 13:43:49 -0800 5355ef0cb by Jimmy Lu, Add MapVector::update (#8801)
2024-02-22 13:11:12 -0800 97465b2a2 by Orri Erling, Scatter struct nulls when deserializing Presto wire format (#8152)
2024-02-22 12:27:58 -0800 860df27f1 by Christian Zentgraf, Fix dependencies for iceberg reader (#8808)
2024-02-22 12:19:45 -0800 1dadf4136 by Bikramjeet Vig, Update website dependencies (#8833)
2024-02-21 22:11:35 -0800 ffd136fdc by Orri Erling, Add …
```
> [VL] Daily Update Velox Version (2024_02_23) 

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- gluten-core/src/main/scala/io/glutenproject/extension/CommonSubexpressionEliminateRule.scala
> [GLUTEN-4642][CH]Fix cse issue in aggregate

- gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
No need to compare all the agg mode in checkAggFuncModeSupport.
Exists CI.
> [CORE] No need to compare all the agg mode in checkAggFuncModeSupport

- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
There are some warnings when compiling cpp, we can fix these warnings by remove some unnecessary codes.
Exists CI.
> [VL] Fix Gluten cpp compile warning

- backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionUtils.scala
- gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
- gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
See #4506
(Fixes: #4506)
Will add a test.
> [GLUTEN-4506][CORE] Fallback filter/project if nested expressions number reaches a configured threshold

- README.md
Add OpenSSF Badge in README
N/A
> Add OpenSSF Badge in README

- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/compute/VeloxRuntime.h
- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/utils/ConfigExtractor.cc
- cpp/velox/utils/ConfigExtractor.h
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
After this patch, user can change glog config and debug config in one session more easily.
> [VL] Make glog config be session level

- ep/build-velox/src/get_velox.sh
To fix a failure when building docker image from cache.
Manual test & internal docker build verification.
> [VL] Allow replacing installed minio package

- cpp-ch/local-engine/Functions/SparkFunctionMakeDecimal.cpp
- cpp-ch/local-engine/Functions/SparkFunctionRegexpExtractAll.cpp
- cpp-ch/local-engine/Functions/SparkFunctionReinterpretAsString.cpp
- cpp-ch/local-engine/Functions/SparkFunctionRoundHalfUp.h
- cpp-ch/local-engine/Functions/SparkFunctionTrim.cpp
- cpp-ch/local-engine/Functions/SparkParseURL.cpp
- cpp-ch/local-engine/Storages/IO/AggregateSerializationUtils.cpp
- cpp-ch/local-engine/Storages/IO/CompressedWriteBuffer.cpp
- cpp-ch/local-engine/Storages/IO/NativeReader.cpp
- cpp-ch/local-engine/tests/benchmark_local_engine.cpp
> [GLUTEN-4813] Replace resize/reserve to resize_extact/reserve_exact to reduce memory

- .github/workflows/velox_be.yml
- docs/get-started/ClickHouse.md
> [GLUTEN-4860][CELEBORN] Replace celeborn link

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
Add flushable decimal sum test case.
Add new test case.
> [VL] Add flushable decimal sum test case

- .github/workflows/velox_be.yml
- shims/spark35/src/main/scala/io/glutenproject/sql/shims/spark35/Spark35Shims.scala
- tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/ShimUtils.scala
- tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/ds/TpcdsDataGen.scala
- tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/h/TpchDataGen.scala
- tools/gluten-it/pom.xml
The current Spark3.5 gluten-it actually runs Spark3.2.2, this pr adds Spark3.5 profile for it. Besides, this pr fixes Spark3.5 compilation issue.
Pass CI
> [CORE] Fix Spark-3.5 CI

- dev/buildbundle-veloxbe.sh
- dev/package.sh
- gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
- shims/spark32/src/main/scala/io/glutenproject/execution/GenerateTreeStringShim.scala
- shims/spark33/src/main/scala/io/glutenproject/execution/GenerateTreeStringShim.scala
- shims/spark34/src/main/scala/io/glutenproject/execution/GenerateTreeStringShim.scala
- shims/spark35/src/main/scala/io/glutenproject/execution/GenerateTreeStringShim.scala
- tools/gluten-te/ubuntu/dockerfile-buildenv
Resolve the comments https://github.com/oap-project/gluten/pull/4822#discussion_r1510657909.
Add spark 35 compile command in scripts.
Existing unit tests
> [GLUTEN-4424][CORE]  Follow up upgrading spark version to 3.5.1

- .asf.yaml
An Infra step for GitHub asf settings
N/A
> Add .asf.yml

- DISCLAIMER
https://incubator.apache.org/policy/incubation.html#standard_disclaimer
N/A
> Add Incubation Standard Disclaimer

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionToDate.cpp
- cpp-ch/local-engine/Functions/SparkFunctionToDateTime.h
- cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
(Fixes: \#4898)
1. Fix diff problem of to_date function;
2. Fix exception throws from `parseDateTimeBestEffort` of SparkFunctionToDateTime;
3. simplify substring function code
TEST BY UT
> [GLUTEN-4898][CH]Bug fix to date diff

- cpp-ch/local-engine/Parser/FunctionParser.h
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- cpp-ch/local-engine/Parser/RelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-4914][CH] Fix exceptions in ASTParser

- shims/spark32/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AbstractBatchScanExec.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AbstractBatchScanExec.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AbstractBatchScanExec.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AbstractBatchScanExec.scala
This should be merged as an individual commit before merging https://github.com/apache/incubator-gluten/pull/4893.
To keep the git history then further developers would know how much of changes we applied to the source files.
The relevant Spark tags to refer to:
https://github.com/apache/spark/tree/v3.2.2
https://github.com/apache/spark/tree/v3.3.1
https://github.com/apache/spark/tree/v3.4.2
https://github.com/apache/spark/tree/v3.5.1
> [CORE] Prior to #4893, add vanilla Spark's original scan source code to keep git history

- gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
- gluten-iceberg/src/main/scala/io/glutenproject/execution/IcebergScanTransformer.scala
- gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxIcebergSuite.scala
- shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark35/src/main/scala/io/glutenproject/sql/shims/spark35/Spark35Shims.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
Bucket join support for Iceberg tables for Spark 3.4+
Added unit tests. Also, had run some tests on private cluster with a custom build and ensured shuffles are avoided where applicable and results are valid.
> [VL]Bucket join support for Iceberg tables

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240314)

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240315)

- .gitignore
> [GLUTEN-4981] Add MacOS specific .DS_Store file to .gitignore

- ep/build-velox/src/get_velox.sh
Because upstream velox has covered this fix recently:
https://github.com/facebookincubator/velox/pull/8988
CI building.
> [VL] Remove a fix for installing boost from get_velox.sh

- backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
- gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
issue #4796 
The issue resolved in #4259  dealt with the exception that occurred when a char column was included in the select statement. This issue fixes the exception that occurs when the char column is not included in the select statement.
unit tests
> [GLUTEN-4796][VL] Force fallback for orc char type scan

- cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
- cpp-ch/local-engine/Shuffle/ShuffleReader.h
> [GLUTEN-4943][CH] Reserved padding area in DB::Memory should never be read or written

- backends-velox/src/test/scala/io/glutenproject/execution/VeloxLiteralSuite.scala
- cpp/velox/substrait/SubstraitParser.cc
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
- cpp/velox/substrait/SubstraitToVeloxExpr.h
Fix NULL literal fallback unexpectly
(Fixes: \#5003)
existing UT
> [GLUTEN-5003][VL] Fix Null literal fallback

- README.md
> [DOC] adding mail list / wechat group / slack channel

- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
> [GLUTEN-5009][CH] Fix TPCDS q9 failed with debug build

- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
This change will fix the spark 3.5 build issue with -Pspark-ut
(Fixes: \#4899)
Built locally
> [GLUTEN-4899][VL]Fix 3.5 build issue with -Pspark-ut 

- backends-clickhouse/src/main/java/io/glutenproject/metrics/MetricsStep.java
- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
- backends-clickhouse/src/main/scala/io/glutenproject/metrics/FileSourceScanMetricsUpdater.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteSuite.scala
- cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Parser/RelMetric.cpp
> [GLUTEN-5041][CH] Fix primary not used when query with filter

- cpp-ch/local-engine/Parser/scalar_function_parser/substring.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-5049][CH] Clean code in substring function parser and fix s3 building issue

- dev/builddeps-veloxbe.sh
buildbundle-veloxbe.sh is composed of at least two steps:
- Get and build Velox
- Build Gluten CPP code
Currently it is not smooth to run on some platforms such as MacOS, we might need to run this script multiple times to fix a build issue, e.g. `Get and build Velox` succeed, but `Build Gluten CPP code` failed, in this PR we introduced the ability to specify the commands to run rather than run the whole script every time. By default we still run all the steps. Usage samples are the following:
```bash
-- Run all the steps
./dev/buildbundle-veloxbe.sh --build_type=RelWithDebInfo
-- Only run build_gluten_cpp
./dev/buildbundle-veloxbe.sh --build_type=RelWithDebInfo build_gluten_cpp
```
Fixes: #5024
> [GLUTEN-5024][VL] Enhance buildbundle-veloxbe.sh to run single step

- cpp/CMakeLists.txt
- cpp/core/CMakeLists.txt
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Payload.h
- cpp/core/shuffle/Spill.cc
- cpp/core/shuffle/Spill.h
- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
Fixes: #5039
Manual tested on Apple M1.
> [GLUTEN-5039][VL] Add support for AppleClang compiler

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionToDate.cpp
> [GLUTEN-4997][CH]Fix year diff

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteSuite.scala
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
- cpp-ch/local-engine/Shuffle/ShuffleSplitter.cpp
- cpp-ch/local-engine/tests/benchmark_local_engine.cpp
> [Gluten-4912][CH] fix bug when a query has no shuffle

- backends-clickhouse/pom.xml
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteOnObjectStorageAbstractSuite.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Common/MergeTreeTool.cpp
- cpp-ch/local-engine/Common/MergeTreeTool.h
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskHDFS.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskHDFS.h
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.h
- cpp-ch/local-engine/Disks/ObjectStorages/registerGlutenDiskObjectStorage.cpp
- cpp-ch/local-engine/Disks/registerGlutenDisks.cpp
- cpp-ch/local-engine/Disks/registerGlutenDisks.h
- cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Parser/MergeTreeRelParser.h
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
- cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.cpp
- cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.h
- cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.cpp
- cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.h
- cpp-ch/local-engine/local_engine_jni.cpp
- gluten-core/src/main/java/io/glutenproject/substrait/rel/ExtensionTableNode.java
> [GLUTEN-4675][CH] Support write mergetree to s3

- backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/catalyst/CHAggregateFunctionRewriteRule.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
- shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
cast avg input type to double when type is integer types: bigint/int/short...
Fixes: \#4946
unit tests
> [GLUTEN-4946][CH] Fix avg(bigint) overflow

- gluten-iceberg/src/test/scala/io/glutenproject/execution/VeloxIcebergSuite.scala
Add timetravel and partition filter UTs for Iceberg scan
CI
> [VL] Add timetravel and partition filter UTs for Iceberg scan

- pom.xml
fix this build issue https://github.com/apache/incubator-gluten/issues/5116
manually test
> [Gluten][Spark 3.5] Fix spark35 ut build

- gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
Minor fix: remove redundant string format
no need
> [MINOR] Remove redundant string format

- docs/get-started/ClickHouse.md
- docs/get-started/Velox.md
The ASF board has approved a resolution to graduate Celeborn into a full Top Level Project. Remove Incubating of Celeborn from reference with https://github.com/apache/celeborn/issues/2415.
Fixes: #5142 
No.
> [GLUTEN-5142][CELEBORN] Remove Incubating of Celeborn from reference

- ep/build-velox/src/get_velox.sh
revert thrift build options change as it's fixed in upstream velox by [commit](https://github.com/facebookincubator/velox/pull/9204).
CI
> [VL]Revert thrift build options change

- ep/build-velox/src/get_velox.sh
```
7fc09667d (upstream/main) Add estimateSerializedSize to BatchVectorSerializer (#8712)
c354c31f1 Reuse result vector in Alpha reader (#9226)
3fbb4754f Create UnitLoader (#9259)
6ec8f26d9 Remove logical types in min_by and max_by tests (#8999)
494b8881b Add support for kurtosis Spark aggregate function (#9233)
2d832eef4 Delete unused ExpressionFuzzer::generateXxxArgs methods (#9256)
0618c7f69 Fix integer overflow for window ROWS frame (#8870)
4f3d32fd5 Clean up FOLLY nullable annotation (#9247)
```
> [VL] Daily Update Velox Version (2024_03_27)

- docs/developers/NewToGluten.md
- docs/get-started/Velox.md
Some jars info is outdated or not enough detailed. The PR provides more details.
N/A
> [VL] Update gluten related jars info in docs

- .github/workflows/velox_docker.yml
Add back upload golden files for velox CI
Pass CI
> [VL][CI] Add back upload golden files

- ep/build-velox/src/get_velox.sh
```
0dac069ca (upstream/main) Add hash build wall time stats (#9234)
174e5effc Document the hash table runtime stats (#9255)
7e77201de Add design philosophy page (#9249)
```
> [VL] Daily Update Velox Version (2024_03_28)

- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/regexp_extract.cpp
> [GLUTEN-5096][CH]Bug fix regex extract diff

- dev/package.sh
> [GLUTEN-5189][VL] Correct boost lib path

- backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/io/glutenproject/execution/ScalarFunctionsValidateSuite.scala
- gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
- shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
Support `url_encode` function
closes #5203
added new unit test
> [GLUTEN-5203][VL] Support url_encode function

- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/commands/OptimizeTableCommandBase.scala
- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/commands/OptimizeTableCommandOverwrites.scala
- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/commands/VacuumCommand.scala
- backends-clickhouse/src/main/delta-22/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
- backends-clickhouse/src/main/delta-22/org/apache/spark/sql/delta/commands/OptimizeTableCommandOverwrites.scala
- backends-clickhouse/src/main/delta-22/org/apache/spark/sql/delta/commands/VacuumCommand.scala
- backends-clickhouse/src/main/java/org/apache/spark/sql/execution/datasources/CHDatasourceJniWrapper.java
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHMergeTreeWriterInjects.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/clickhouse/MergeTreeFileFormatWriter.scala
- backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseMergeTreeOptimizeSuite.scala
- cpp-ch/local-engine/Operator/ExpandTransform.cpp
- cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Parser/MergeTreeRelParser.h
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.h
- cpp-ch/local-engine/Storages/Mergetree/MergeSparkMergeTreeTask.cpp
- cpp-ch/local-engine/Storages/Mergetree/MergeSparkMergeTreeTask.h
- cpp-ch/local-engine/Storages/StorageMergeTreeFactory.cpp
- cpp-ch/local-engine/Storages/StorageMergeTreeFactory.h
- cpp-ch/local-engine/local_engine_jni.cpp
> [Gluten-5152][CH]Support Optimize and VACUUM command for clickhouse tables

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/QueriesCompare.scala
Try directly remove the hacky code to see if jobs can pass.
> [VL] gluten-it: Remove specific result matching code for Q65

- backends-velox/pom.xml
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/SparkPlanExecApiImpl.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/HashAggregateExecTransformer.scala
- backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
- cpp/velox/jni/JniUdf.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/udf/Udaf.h
- cpp/velox/udf/UdfLoader.cc
- cpp/velox/udf/UdfLoader.h
- cpp/velox/udf/examples/CMakeLists.txt
- cpp/velox/udf/examples/MyUDAF.cc
- cpp/velox/udf/examples/MyUDF.cc
- cpp/velox/udf/examples/TestMyUDF.cc
- docs/get-started/Velox.md
Add `UserDefinedAggregateFunction` as wrapper for all native udaf.
User should define and register UDAFs in the same way as UDFs. Gluten framework will handle the differences.
issue: #5110
> [VL] Support native UDAF

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/TpcRunner.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/QueryRunner.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkSessionSwitcher.scala
Reverts apache/incubator-gluten#5227
Need to revert this PR since it may lead to some malformed log outputs. Optimizations needed.
> Revert "[VL] gluten-it: Shorten table creation and query runner logs"

- README.md
highlight the contributors in readme
> [DOC] highlight contributors in Readme

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHSortMergeJoinExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHJoinValidateUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSParquetSortMergeJoinSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/SparkPlanExecApiImpl.scala
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/SortMergeJoinExecTransformer.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transform/ImplementSingleNode.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/connector/GlutenKeyGroupedPartitioningSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/adaptive/clickhouse/ClickHouseAdaptiveQueryExecSuite.scala
Support inner and outer joins
(Fixes: #GLUTEN-4745)
unit tests and integration tests
> [GLUTEN-4745][CH] support Sort Merge Join

- .github/workflows/velox_docker.yml
Simply a follow-up for https://github.com/apache/incubator-gluten/pull/4936.
> [GLUTEN-4917][VL][CI] Enable Gluten CPP tests

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/fuzzer/ShuffleWriterFuzzerTest.scala
> [VL] Hot-fix for checkOperator

- cpp-ch/local-engine/Parser/scalar_function_parser/regexp_extract.cpp
(Fixes: \#5196)
Fix comments mentioned in pr： https://github.com/apache/incubator-gluten/pull/5100
> [GLUTEN-5196][CH]Fix comments regexp extract

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/nanvl.cpp
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
Support nanvl function
PASS CI
> [CH] Support nanvl function

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
Use `checkGlutenOperatorMatch`
N/A
> [CH] Hot fix for checkOperatorMatch

- README.md
This PR fixes some minor typos in the README file.
NA
> [DOC] Fix minor typos in README

- .github/workflows/velox_docker.yml
Enable celeborn test in CI.
N/A
> [GLUTEN-4917][VL] Enable celeborn test in CI

- docs/get-started/Work-with-pyspark.ipynb
Add example notebook for Gluten usage in PySpark
N/A
> [GLUTEN-5277] Add a notebook example for enabling Gluten in PySpark

- ep/build-velox/src/get_velox.sh
```
628b4e8ba (upstream/main) Add initialized bit for aggregates in RowContainer (#9067)
80ea6a1f7 Fix setup-ubuntu.sh to explicitly install package manager dependencies when sourcing (#9341)
f91ae0cfd Wire OOM Injection into ExchangeFuzzer (#9329)
ece3961b8 Add support for Aggregate signatures in PyVelox and Signatures.py (#9104)
bfa151864 Fix integer overflow in Entropy aggregate when argument is constant (#9332)
1ba16a962 Add support for collect_list Spark aggregate function (#9231)
a79e5eaef Update Presto functions coverage map (#9309)
85aa8bd70 Refactor SimpleAggregateAdapter to move is_aligned_ flag into AccumulatorType (#9268)
d92f1f6a7 Fix memory regression of 3-arg min_by/max_by (#9307)
0fdf6082b Fix window operation with kRange frames with column boundary (#9257)
f64795f55 …
```
> [VL] Daily Update Velox Version (2024_04_03)

- .github/workflows/velox_docker.yml
- gluten-core/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-core/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
- gluten-delta/src/test/scala/org/apache/gluten/execution/VeloxDeltaSuite.scala
- gluten-delta/src/test/scala/org/apache/gluten/execution/VeloxTPCHDeltaSuite.scala
- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
- gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala
- gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxTPCHIcebergSuite.scala
Fix broken inheritance of `IcebergScanTransformer` cause by [commit](https://github.com/apache/incubator-gluten/commit/23048fb6a3d1520dd1336371dc67ec6dc5fbd55a), tracked by [issue](https://github.com/apache/incubator-gluten/issues/5250). 
Re-enable iceberg and delta UTs in CI.
CI
> [GLUTEN-4917][VL] Enable iceberg/delta in new CI

- .github/workflows/build_bundle_package.yml
- .github/workflows/velox_docker.yml
This patch updated the GHA to use the docker image from apache/gluten account
pass GHA
> [GLUTEN-4917][VL][CI] update to use apache/gluten docker

- backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
This PR aims to support cast date as timestamp in velox. After this, we can run `cast(date as timestamp)` with velox.
(Fixes: \#5102)
Add new unit test.
> [GLUTEN-5102][VL] Support cast date as timestamp in velox

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
Enable unix_date Spark function
Added a UT.
> [VL] Enable unix_date Spark function

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/VeloxIntermediateData.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
Support `regr_sxy` aggregate function.
Add `VeloxAggregateFunctionsSuite.regr_sxy` test case.
> [VL] Support regr_sxy aggregate function

- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
This pr fix the bug that may fail to parse post join filter if contains complex expressions.
(Fixes: \#5182)
This patch was tested by ut.
> [GLUTEN-5182] [CH] fix fail to parse post join filter

- gluten-core/src/main/scala/org/apache/gluten/execution/GlutenWholeStageColumnarRDD.scala
> [CORE] Remove useless GlutenFilePartition

- ep/build-velox/src/get_velox.sh
```
9c83ef958 (upstream/main) Fix server crash caused by memory pool abort race (#9408)
fa177d33c Disable approx_distinct result verifier in window fuzzer test (#9407)
e29cde7b2 Refactor greatest and least Presto functions using simple function API (#9308)
```
> [VL] Daily Update Velox Version (2024_04_09)

- .github/workflows/velox_docker.yml
https://github.com/facebookincubator/velox/pull/9025
Existing tests
> [VL] Enable Window oom in  ci job

- dev/package-vcpkg.sh
- dev/vcpkg/Makefile
- dev/vcpkg/docker/Dockerfile.gha
- dev/vcpkg/ports/duckdb/portfile.cmake
- dev/vcpkg/ports/duckdb/vcpkg.json
- dev/vcpkg/vcpkg-configuration.json
- dev/vcpkg/vcpkg.json
Update dependencies in CI
pass GHA
> [GLUTEN-4917][VL] Update dependencies in static packaging

- cpp-ch/local-engine/Parser/JoinRelParser.cpp
After https://github.com/ClickHouse/ClickHouse/pull/61216, We will failed at [`tryPushDownFilter()` in filterPushDown.cpp](https://github.com/ClickHouse/ClickHouse/blob/db46866db749018466da2de114c4a6e21b853900/src/Processors/QueryPlan/Optimizations/filterPushDown.cpp#L272)
Here is a workaround, refer to `chooseJoinAlgorithm()` in PlannerJoins.cpp, it always call `TableJoin::setRename` to create aliases for columns in the right table. By using right table header name sets, so `TableJoin::deduplicateAndQualifyColumnNames` can do same thing as `chooseJoinAlgorithm()`
ffected UT fixed bh this workaround:
- GlutenClickHouseTPCHParquetRFSuite:TPCH Q17, Q19, Q20, Q21
Using existed UT
> [CH] [Minor] fix ut due to https://github.com/ClickHouse/ClickHouse/pull/61216

- docs/developers/NewToGluten.md
this PR is fixing broken link for `build-gluten-with-velox-backend` in the NewToGluten.md file.
NA
> [DOC] Fix broken link in NewToGluten.md

- ep/build-clickhouse/src/package.sh
> [GLUTEN-5403][CH] Fix build error due to delta.package.name not set by default

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
Move case test 'order by limit' to VeloxTPCHMiscSuite.
> [VL] Move out a non-common test case from VeloxTPCHSuite

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionBin.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-5380][CH] Support bin function

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxWindowExpressionSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Support collect_list in window.
Add new test case.
> [VL] Support collect_list in window

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/catalyst/EqualToRewrite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
> [GLUTEN-5391][CH] Fix equalTo NaN issue

- ep/build-clickhouse/src/package.sh
> [GLUTEN-5417][CH] Fix CH backend build error due to uniffle not supported

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
Velox already supports ByteType
pass GHA
> [VL] Fix ORC reader for ByteType

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
Move memory off-heap conf checks to driver plugin to fail quickly when misconfigured
> [CORE] Move memory off-heap conf checks to driver plugin

- gluten-ut/test/pom.xml
- gluten-ut/test/src/test/scala/org/apache/gluten/expressions/GlutenExpressionMappingSuite.scala
https://github.com/apache/incubator-gluten/issues/5341
manually local run
> [GLUTEN-5341][VL] Enable UT of GlutenExpressionMappingSuite

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
Fixes the tests in VeloxParquetWriteForHiveSuite.scala
(Fixes: \#5341)
Ran UTs locally
> [GLUTEN-5341] Fix VeloxParquetWriteForHiveSuite.scala

- cpp/core/shuffle/FallbackRangePartitioner.cc
- cpp/core/shuffle/FallbackRangePartitioner.h
- cpp/core/shuffle/HashPartitioner.cc
- cpp/core/shuffle/HashPartitioner.h
- cpp/core/shuffle/Partitioner.h
- cpp/core/shuffle/RoundRobinPartitioner.cc
- cpp/core/shuffle/RoundRobinPartitioner.h
- cpp/core/shuffle/SinglePartitioner.cc
- cpp/core/shuffle/SinglePartitioner.h
- cpp/core/tests/RoundRobinPartitionerTest.cc
- cpp/velox/shuffle/VeloxShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleWriter.h
> [GLUTEN-5307][VL] Fix Potential Overflow Issue in VeloxShuffleWriter Due to Mismatched Data Types of RowNumber

- cpp-ch/local-engine/Parser/scalar_function_parser/expm1.cpp
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
> [CH] Support expm1 function

- gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxTPCHIcebergSuite.scala
> [VL][GLUTEN-5362] Enable iceberg tpch partitioned table test

- dev/builddeps-veloxbe.sh
- ep/build-velox/src/build_velox.sh
Just add sudo command to the clean step to make sure all of those files removed
mannual test in local build and find it can work well
> [GLUTEN-5448][VL] Fix the issue of cleaning when left with previous build in velox-backends part

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitParser.cc
Fix negative function mapping.
UT.
> [VL] Fix negative function mapping

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/SparkPlanExecApiImpl.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
Array transform does not support the usage that lambda function contains index variable for now.
> [VL] Support array transform function

- cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.cpp
Speed up mergetree metadata reloading. The principle is to increase the writing speed of metadata through the thread pool.
The default thread pool size is minimum 10, which can be specified through `spark.gluten.sql.columnar.backend.ch.runtimesettings.max_threads`
```
2000+parts
before:
runTPCHQueryBySQL cost time: 136886 ms
after:
runTPCHQueryBySQL cost time: 12017 ms
```
manual tests
> [CH] Speed up mergetree metadata reloading

- cpp/velox/benchmarks/ParquetWriteBenchmark.cc
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.h
- cpp/velox/operators/writer/VeloxParquetDatasourceGCS.h
- cpp/velox/operators/writer/VeloxParquetDatasourceHDFS.h
- cpp/velox/operators/writer/VeloxParquetDatasourceS3.h
The PR to extend the class to VeloxParquetDatsourceS3, VeloxParquetDatsourceGCS and VeloxParquetDatsourceABFS, insted of puting all of them in the same file as to address this comment https://github.com/apache/incubator-gluten/pull/3978#discussion_r1419928243
and it is also a pre-PR for onboarding **ABFS write part** code change.
> [VL] Refactor VeloxParquetDatasource 

- gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
This PR provides bucket joins support for Spark3.5 to fix corresponding UT failures.
UT
> [GLUTEN-5341] Support iceberg bucket join for Spark3.5

- docs/get-started/Velox.md
- docs/get-started/VeloxABFS.md
Add documentation for ABFS with Gluten using Velox backend.
> [VL][DOC] Add ABFS doc

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxParquetDataTypeValidationSuite.scala
> [VL] Fix Velox Parquet Write UT

- .github/workflows/velox_docker.yml
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/tpc/command/Parameterized.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/tpc/command/Queries.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/tpc/command/QueriesCompare.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/tpc/command/QueriesMixin.java
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/TpcSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Actions.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Parameterized.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Queries.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/QueriesCompare.scala
Added a new `gluten-it` option `--shard` to achieve this.
> [VL] CI: Split SF30 job to 4 jobs to speed up execution

- cpp/velox/jni/VeloxJniWrapper.cc
cpp build unused variable warn.
N/A
> [VL] Remove unused variable in VeloxJniWrapper

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
Clean up `SparkConfImplicits` in `GlutenPlugin` as it's not used.
Pass CI.
> [GLUTEN-5532] Clean up some dead code in GlutenPlugin

- docs/get-started/VeloxABFS.md
- docs/get-started/VeloxLocalCache.md
- docs/get-started/VeloxS3.md
A follow up PR to remove duplicate  content from doc after PR https://github.com/apache/incubator-gluten/pull/5479
> [VL][Doc] Remove duplicate content for local cache part

- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-core/src/main/java/org/apache/gluten/substrait/expression/ExpressionBuilder.java
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenPlan.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala
- gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsCommonTrait.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/adaptive/velox/VeloxAdaptiveQueryExecSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
Add a util method to ignore test whose name is prefixed with "Gluten - ".
> [UT] Add ignoreGluten method

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
Correct the function name mapping for year_of_week function.
> [VL] Fix year_of_week function

- docs/get-started/Velox.md
Update Velox build info 
(Fixes: \#5571)
> [GLUTEN-5571][DOC] Update Velox build info #5571

- backends-velox/src/main/scala/org/apache/gluten/execution/GenerateExecTransformer.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxMetricsSuite.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/GenerateMetricsUpdater.scala
This pr adds more metrics for generate.
add test
> [VL] Add more metrics for generate

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/Constants.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/DataGen.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/ShimUtils.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/TpcRunner.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/TpcSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Parameterized.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Queries.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/QueriesCompare.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/ds/TpcdsDataGen.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/ds/TpcdsSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/h/TpchDataGen.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/h/TpchSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/deploy/history/GlutenItHistoryServerPlugin.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/deploy/history/HistoryServerHelper.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/ConfUtils.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/QueryRunner.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/TestUtils.scala
As title. The patch reformats gluten-it's code with Spark331's scalafmt configuration.
> [VL] CI: Reformat gluten-it code with Spark331's scalafmt configuration

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionCastFloatToInt.cpp
- cpp-ch/local-engine/Functions/SparkFunctionCastFloatToInt.h
> [GLUTEN-5580][CH]Fix cast to int exceed max

- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/operators/writer/VeloxParquetDatasource.h
- cpp/velox/operators/writer/VeloxParquetDatasourceABFS.h
> [GLUTEN-4811][VL] Abfs FileSink Onboard

- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
> [VL] Enable split preloading by default

- .github/workflows/velox_velox_ut.yml
remove miniconda folder to save disk space
pass GHA
> [GLUTEN-4917][CI] remove miniconda folder in image

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240508)

- cpp-ch/local-engine/Functions/SparkFunctionCheckDecimalOverflow.cpp
(Fixes: \#5613)
Test by history ut
> [GLUTEN-5613][CH] Fix CH function SparkCheckoverflow return type not equals with spark

- gluten-core/src/main/scala/org/apache/gluten/expression/ScalarSubqueryTransformer.scala
Fixes https://github.com/apache/incubator-gluten/issues/5656
> [GLUTEN-5656][CORE] Avoid executing subqueries with complex data type during validation

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240509)

- ep/build-velox/src/get_velox.sh
Add -Wno-stringop-overflow for alinux3
CI
> [VL] Add -Wno-stringop-overflow for alinux3

- .github/workflows/velox_docker_cache.yml
- .github/workflows/velox_tpch_bench.yml
Adding TPCDS benchmarks on comment
pass GHA
> [GLUTEN-4917][VL] CI adding TPCDS benchmark

- backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
- gluten-core/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
Add a new test case of `InsertIntoHadoopFsRelationCommand` for csv format.
Add `insert into select from csv` test case.
> [VL] Add InsertIntoHadoopFsRelationCommand test case for csv format

- docs/developers/NewToGluten.md
> [GLUTEN-5708][VL] Minor wording polishing for NewToGluten.md

- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/metadata/AddFileTags.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/HashPartitioningWrapper.scala
- pom.xml
Reverts apache/incubator-gluten#5723
Intellij doesn't pick the custom wart's code. Investigating.
> Revert "[CORE] Add a compilation-time check to forbid case-class inheritance "

- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/DeltaLog.scala
- backends-clickhouse/src/main/delta-22/org/apache/spark/sql/delta/DeltaLog.scala
- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/HashPartitioningWrapper.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/metadata/AddFileTags.scala
- pom.xml
This reopens https://github.com/apache/incubator-gluten/pull/5723 with a fix for building with Intellij Idea.
Ref: https://www.scala-lang.org/2021/01/12/configuring-and-suppressing-warnings.html
> [CORE] Add a compilation-time check to forbid case-class inheritance

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240514)

- backends-velox/src/test/scala/org/apache/gluten/execution/FallbackSuite.scala
Follow up of https://github.com/apache/incubator-gluten/pull/5655 to drop new added test table after all.
N/A
> [VL] Drop the test table after all tests in FallbackSuite

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/Queries.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/QueriesCompare.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/tpc/action/TableFormatter.scala
1. Avoid exception during test reporting if no query was passed;
2. Avoid swallowing console output with query failures;
Tested locally.
> [VL] CI: Gluten-it: Fix unreadable test reporting when there are query failures

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Enable length function for binary type.
UT.
> [VL] Enable length function for binary type

- gluten-core/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
> [GLUTEN-5759][CORE] Optimze checkGlutenOperatorMatch to show clearer error message

- cpp/CMakeLists.txt
- cpp/core/CMakeLists.txt
- cpp/velox/CMakeLists.txt
Modify CMAKE_CXX_FLAGS generation logic for each native module, and make it clearly to see all the CMAKE_CXX_FLAGS.
> [VL] Refine CMAKE_CXX_FLAGS setting logic

- gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
Fix invoke celebornShuffleId exception.
(Fixes: https://github.com/apache/incubator-gluten/issues/5775)
Manual test.
> [GLUTEN-5775][CELEBORN] Fix invoke celebornShuffleId exception

- cpp/velox/CMakeLists.txt
- cpp/velox/memory/BufferOutputStream.cc
- cpp/velox/memory/BufferOutputStream.h
- cpp/velox/shuffle/VeloxSortBasedShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortBasedShuffleWriter.h
- cpp/velox/tests/BufferOutputStreamTest.cc
- cpp/velox/tests/CMakeLists.txt
A follow-up PR of https://github.com/apache/incubator-gluten/pull/5675
Discussion: https://github.com/apache/incubator-gluten/pull/5675#discussion_r1602744985
> [VL] Add BufferedOutputStream to track the memory usage in PrestoSerializer

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
> [CORE] Unify the transforming for shuffle expression

- .asf.yaml
Add branch protection rule with at least 1 review pass.
N/A
> [CORE]Add branch protection rule

- cpp/CMakeLists.txt
- cpp/core/CMakeLists.txt
- cpp/core/shuffle/HashPartitioner.cc
- cpp/core/shuffle/Partitioner.h
> [GLUTEN-5792][CORE] Fix build on macOS

- .github/workflows/velox_docker.yml
disable SF30 tpc tests on GHA
#5765
> [VL][CI] disable SF30 tpc tests on GHA

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
> [VL] Not fallback for function spark_partition_id

- .github/workflows/velox_docker.yml
- dev/ci-velox-buildstatic.sh
- dev/vcpkg/init.sh
update CI images for GHA
upgrade cmake to 3.28.3
pass GHA
> [VL] CI image update

- .github/workflows/velox_docker.yml
- .github/workflows/velox_docker_cache.yml
- ep/build-velox/src/get_velox.sh
```
96c51ae1b by Pedro Eugenio Rocha Pedreira, Re-enable alternative plans in join fuzzer (#9898)
8f5d3466f by Kk Pulla, Add APIs to get simple and vector function signatures in function registry (#9884)
80235488b by Wei He, Fix timeout of SharedArbitrationTest.skipNonReclaimableTaskTest (#9894)
ffc781e93 by Bikramjeet Vig, Fix build failure due to clashing of std and folly's versions of identity functor (#9891)
47fc3dda4 by NEUpanning, Add allowOverflow flag to Timestamp::toTimezone (#9836)
675b6dd76 by Bikramjeet Vig, Fix NaN handling for array_position (#9832)
2058231e3 by Bikramjeet Vig, Fix NaN handling for array_remove and contains UDFs (#9807)
fbb357807 by Masha Basmanova, Introduce velox::Expected (#9858)
890c0b457 by Masha Basmanova, Optimize …
```
> [VL] Daily Update Velox Version (2024_05_23)

- .github/workflows/velox_docker_cache.yml
update the image in cache job
pass GHA
> [GLUTEN-4917][VL][CI] update the docker image in nightly cache job

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Storages/IO/NativeReader.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240524)

- .asf.yaml
Some comments are used to highlight the key change or something else to help recall in future.
N/A
> [INFRA] Do not require all conversations resolved

- backends-clickhouse/src/test/scala/org/apache/spark/sql/gluten/compatibility/GlutenFunctionSuite.scala
This PR add UTs which failed at internal tests, let's fix them one by one with follow up PRs.
> [CH] Add Compatibility test found by internal

- backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
- cpp/velox/udf/examples/MyUDAF.cc
- cpp/velox/udf/examples/MyUDF.cc
- cpp/velox/udf/examples/UdfCommon.h
- docs/developers/VeloxUDF.md
fixes #5840 
Refined UDAF example and add test
> [GLUTEN-5840][VL] Fix udaf register simple intermediate type

- gluten-core/src/main/scala/org/apache/gluten/execution/SampleExecTransformer.scala
https://github.com/apache/incubator-gluten/actions/runs/9265491297/job/25487751879?pr=5754
> [VL] Fix build error

- package/pom.xml
> [VL] Keep gluten fat jar built out previously for other Spark versions

- .github/workflows/velox_docker.yml
- .github/workflows/velox_docker_cache.yml
- dev/ci-velox-buildstatic.sh
update GHA docker image to add folly changes
https://github.com/apache/incubator-gluten/pull/5314
pass GHA
> [GLUTEN-4917][VL] CI: update GHA docker image

- dev/package-vcpkg.sh
- dev/vcpkg/Makefile
this patch refines the vcpkg package script 
> [GLUTEN-4942][VL] refine vcpkg package script

- tools/gluten-it/common/pom.xml
- tools/gluten-it/package/pom.xml
- tools/gluten-it/pom.xml
As title. Optimize Maven dependency list, clarify dependency scopes and visibilities.
> [VL] Gluten-it: Optimize Maven dependency list

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionTrim.cpp
> [GLUTEN-5921][CH] Function trim of trim_character support value from column

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionGreatest.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-5896][CH]Fix greatest diff

- backends-clickhouse/src/test/scala/org/apache/spark/sql/gluten/parquet/GlutenParquetColumnIndexSuite.scala
- cpp-ch/local-engine/Storages/Parquet/ColumnIndexFilter.cpp
- cpp-ch/local-engine/Storages/Parquet/ParquetConverter.h
- cpp-ch/local-engine/tests/gtest_parquet_columnindex.cpp
Support `FLBAType` and `BOOLEAN`
(Fixes: \#3582)
new UTs
> [GLUTEN-3582] Support FLBAType and BOOLEAN

- .github/workflows/velox_docker.yml
update cent8 mirror due to EOL
pass gha
> [VL] update mirror for Centos8

- backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Support left  and right semi join in SMJ.
Adding new unit test.
> [GLUTEN-5720][VL] Enable left and right semi join type in smj

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/FilterRelParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Rewriter/ExpressionRewriter.h
> [GLUTEN-5957][CH]Fix get_json_object on filter condition

- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/StorageJoinBuilder.java
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHHashBuildBenchmark.scala
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.h
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
- cpp-ch/local-engine/local_engine_jni.cpp
> [GLUTEN-5996][CH] Fixed missing columns in join with mixed conditions

- cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
Disable automatic switching of sort shuffle
unit tests
> [CH] Disable automatic switching of sort shuffle

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseNativeLibSuite.scala
> [GLUTEN-5979][CH] Fix CHListenerApi initialize twice on spark local mode

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
> [VL] Support PreciseTimestampConversion function

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Fix the invalid adding int to string in log.
GA
> [GLUTEN-5720][VL][FOLLOWUP][MIRROR] Fix invalid adding int to string

- ep/build-velox/src/get_velox.sh
Fixes: #6072 
Run `./dev/package.sh` with a non-root user locally.
> [GLUTEN-6072][BUILD] Permission denied error run ./dev/package.sh

- backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala
next() expires whole stage time
> [VL] Fix RowToColumn metric convert time

- cpp/velox/compute/WholeStageResultIterator.cc
- ep/build-velox/src/get_velox.sh
```
bca2f1cc1 by Masha Basmanova, Mark UNKNOWN type as orderable and comparable (#10213)
f2ce4a51f by Masha Basmanova, Enable truncate Presto function for REAL inputs (#10214)
d9315cbd7 by Pedro Eugenio Rocha Pedreira, Fix date_add() semantic on daylight savings boundaries (#10188)
53b07f063 by Krishna Pai, Fix map_top_n on empty values. (#10207)
8c3630b35 by yan ma, Add RetryStrategy for S3 file system (#9736)
c98e7def9 by Masha Basmanova, Fix bitwise_xxx_shift Presto functions (#10208)
f2afb70bf by Masha Basmanova, Add support for VARBINARY input to concat Presto function (#10201)
b5502cfd7 by soumyaduriseti, Add binary lpad and rpad Presto functions (#7329)
ab7f1884c by Masha Basmanova, Add support for complex type inputs to array_distinct Presto function …
```
> [VL] Daily Update Velox Version (2024_06_17)

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
> [GLUTEN-6053][CH] Move collect native metrics from last hasNext to close and cancel

- .github/ISSUE_TEMPLATE/bug.yml
> [MINOR] Add spark 3.4.x and 3.5.x options in Github issue

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- cpp-ch/local-engine/Functions/SparkFunctionRint.cpp
- cpp-ch/local-engine/Functions/SparkFunctionRint.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
support function rint
unit tests
> [CH] support function rint

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
(Fixes: \#6016)
Notice: must be merged before: https://github.com/Kyligence/ClickHouse/pull/494
> [GLUTEN-6016][CH] Add uts for decimal convert to int overflow case

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Parser/FilterRelParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
Rollback header if changed in FilterTransform
(Fixes: \#4451)
This patch was tested by integration tests.
> [GLUTEN-4451] [CH] fix header maybe changed by FilterTransform

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskHDFS.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskHDFS.h
- cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.cpp
- cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.h
> [GLUTEN-6178][CH] Add config to insert remote file system directly

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
https://github.com/apache/incubator-gluten/pull/6036#issuecomment-2185510139 
UT.
> [VL] Support KnownNullable for Spark 3.5

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Functions/SparkArrayFlatten.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameFunctionsSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameFunctionsSuite.scala
Support function flatten
unit tests
> [CH] Support flatten

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
> [VL] Fix greatest and least function tests

- .github/workflows/velox_docker.yml
- ep/build-velox/src/get_velox.sh
```
1225f773f by joey.ljy, Add session timezone to Parquet PageReader (#9781)
33cdf0a97 by Wei He, Add custom input generator for lead, lag, nth_value, and ntile in WindowFuzzerTest (#8360)
82a12e165 by Deepak Majeti, Remove setup-centos8.sh (#10249)
7be328cac by Zhenyuan Zhao, Make dwrf support taking custom column reader factory (#10267)
1f981ae8f by Orri Erling, Add more size classes (#10139)
dc533655f by Masha Basmanova, Add from_unixtime(epoch, hours, minutes) Presto function (#10215)
7f547dbca by Wei He, Add custom result verifiers for min_by and max_by (#9070)
9974a3339 by Wei He, Allow logging input vectors in aggregation fuzzer (#10229)
```
> [VL] Daily Update Velox Version (2024_06_25)

- gluten-core/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
> [GLUTEN-6219] Fix some code style issue for BasicScanExecTransformer

- gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornUtils.java
Fix potential ClassNotFoundException
CI
> [CELEBORN] Fix potential ClassNotFoundException

- ep/build-velox/src/get_velox.sh
```
deb978412 by Kevin Wilfong, Fix race condition in ProfilerTest (#10313)
ee596b6d1 by Kevin Wilfong, Fix some race conditions in PeriodicStatsReporterTest (#10310)
f514bc12d by Kevin Wilfong, Fix race condition in CachedFactoryTest.fuzzer (#10311)
06c8a0c63 by Deepak Majeti, Fix reading empty Parquet DataPage (#10121)
483c7baac by lingbin, Remove unused 'SetMemoryReclaimer' alias (#10122)
4661b6147 by PHILO-HE, Register re-usable Presto map/array functions for Spark (#10298)
29704a658 by Jimmy Lu, Fix double counting of lazy loading time (#10305)
28238cd55 by Ke, Add session property for sorted table write fuzzer (#10299)
4ed96b5db by Kevin Wilfong, Disable some flaky tests (#10307)
a19721c3d by xiaoxmeng, Remove duplicate runtime stats and fix naming (#10300)
7f56d77ec by …
```
> [VL] Daily Update Velox Version (2024_06_26)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-6124][CH]Fix json output diff

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/FunctionGreatestLeast.h
- cpp-ch/local-engine/Functions/SparkFunctionLeast.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
> [GLUTEN-6156][CH]Fix least diff

- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/Parser/scalar_function_parser/chr.cpp
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-2790][CH] Fix diff between ch char and spark chr

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/TransformHintRule.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/rewrite/RewriteSparkPlanRulesManager.scala
> [Core] Rename isTransformable API to maybeTransformable

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionArrayDistinct.cpp
fix core dump when arrayDistinct(Array(Nullable(Decimal)))
unit tests
> [CH] Fix array distinct core dump 

- cpp-ch/local-engine/Parser/JoinRelParser.cpp
> [GLUTEN-6257][CH] Mismatched headers in broadcast join

- ep/build-velox/src/get_velox.sh
```
cc6ac918c by yanngyoung, Memory Arbitration Fuzzer test enable global arbitration (#10333)
a34e7cd3f by zhli1142015, Support complex types for Spark EqualTo and EqualNullSafe functions (#10156)
bb3520277 by Kevin Wilfong, Don't run plans with LocalPartition in Aggregation and Window Fuzzers when TSAN is enabled (#10340)
a9fa01ff3 by Daniel Hunte, Add map_top_n_keys Presto function (#10271)
81b848499 by Kevin Wilfong, Speed up ApproxPercentileResultVerifier >100x (#10329)
cf655ff01 by Andrii Rosa, Reduce number of explicit OutputBuffer#acknowledge calls (#9468)
a83839960 by Andrii Rosa, Increase exchange client long pool delay to 10 seconds (#10287)
91f3aec1c by Masha Basmanova, Add partial support for split_to_map Presto lambda function (#10334)
c3f2158a9 by Masha Basmanova, Add …
```
> [VL] Daily Update Velox Version (2024_06_28)

- cpp-ch/local-engine/Functions/SparkFunctionHashingExtended.h
> [GLUTEN-6300][CH] Ensure same hash results from NaN

- NOTICE
> [MINOR] ADD NOTICE

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Operator/ReplicateRowsStep.cpp
- cpp-ch/local-engine/Operator/ReplicateRowsStep.h
- cpp-ch/local-engine/Parser/ProjectRelParser.cpp
- cpp-ch/local-engine/Parser/ProjectRelParser.h
- cpp-ch/local-engine/Parser/RelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
Support expression ReplicateRows in spark
unit tests
> [CH] Support replicaterows

- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/local_engine_jni.cpp
(Fixes: \#6272)
Using existed UT.
> [GLUTEN-6272] Revert #6130 

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Functions/SparkFunctionRegexpExtractAll.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240704)

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- cpp-ch/local-engine/Functions/SparkFunctionArraySort.cpp
- cpp-ch/local-engine/Functions/SparkFunctionSortArray.cpp
- cpp-ch/local-engine/Functions/SparkFunctionSortArray.h
- cpp-ch/local-engine/Parser/scalar_function_parser/arrayHighOrderFunctions.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/sortArray.cpp
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
> [GLUTEN-6159][CH] Support `array_sort`

- .github/workflows/velox_docker.yml
https://github.com/dawidd6/action-download-artifact/issues/262#issuecomment-2208590951
> [CI] Hotfix centos7 CI failure

- backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.h
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/GlutenSQLWindowFunctionSuite.scala
Deduplicate sorting keys before going to Velox.
add test & pass exist tests
> [VL] Deduplicate sorting keys

- dev/ci-velox-buildstatic.sh
- dev/vcpkg/vcpkg-configuration.json
- dev/vcpkg/vcpkg.json
> Fix gcs build issue when vcpkg build is enabled

- pom.xml
Add apache release profile
test pass in local server with apache release profile, require more testing by using "mvn deploy" in v1.2.0-rc1 tag
> [CORE]update profile for apache release

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Operator/DefaultHashAggregateResult.cpp
- cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.cpp
- cpp-ch/local-engine/Storages/Mergetree/SparkMergeTreeWriter.h
- cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/tests/gtest_parser.cpp
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240706)

- .github/workflows/build_bundle_package.yml
fix the build bundle package tool due toe node version update
locally verified
> [VL] fix build bundle package

- dev/vcpkg/setup-build-depends.sh
Add debian 10 support in vcpkg depends.
#6285 
> [GLUTEN-6285][VL] Add debian10 vcpkg depends

- tools/gluten-it/package/pom.xml
Use project version rather than Gluten version in Gluten it .
Pass CI
> [TEST] Use project version rather than Gluten version in Gluten it

- dev/package-vcpkg.sh
(Fixes: https://github.com/apache/incubator-gluten/issues/6394)
> [GLUTEN-6394][VL] Fix the vcpkg package script

- .github/workflows/velox_docker_cache.yml
Same failure as in https://github.com/apache/incubator-gluten/pull/6340
> [CI] Fix centos7 failure

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/RelMetric.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240711)

- gluten-ut/test/src/test/scala/org/apache/spark/sql/GlutenExpressionDataTypesValidation.scala
It's like:
1. Commit https://github.com/apache/incubator-gluten/commit/2f35c63488b3449bd4c4f2d024c46fb1e519a2f0 and https://github.com/apache/incubator-gluten/commit/86e5f9d84a73da4c46f6221e42abf52eb4f499ac has conflict that causes build failure
2. Commit https://github.com/apache/incubator-gluten/commit/86e5f9d84a73da4c46f6221e42abf52eb4f499ac and https://github.com/apache/incubator-gluten/commit/1cc4ef43e325fe62436fc86a332454d629e55b18 has conflict that causes UT failure
The patch is a quick fix for the issues.
> [VL] Quick fix for commit conflicts

- cpp/CMake/ConfigArrow.cmake
- dev/build_arrow.sh
- ep/build-velox/src/build_velox.sh
- ep/build-velox/src/get_velox.sh
Original patch: https://github.com/apache/incubator-gluten/pull/6325. Can be merged after that pr is merged.
> [VL] Port to branch-1.2: Set Arrow_SOURCE to AUTO to allow using system arrow libs

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffloadProject.scala
Remove an unused code line, and add a TODO comment.
> [VL] RAS: Minor code cleanup for offloading project

- .github/workflows/velox_docker_cache.yml
update docker image for cache-native-lib job
CI
> [VL] update docker image for cache-native-lib job

- .github/workflows/velox_docker.yml
- dev/build_arrow.sh
- dev/builddeps-veloxbe.sh
> [GLUTEN-6495][VL] Fix build issue: --build_arrow=ON wipes --build_type=<TYPE> setting silently

- gluten-ut/spark32/pom.xml
- gluten-ut/spark33/pom.xml
- gluten-ut/spark34/pom.xml
- gluten-ut/spark35/pom.xml
- gluten-ut/test/pom.xml
Related to https://github.com/apache/incubator-gluten/issues/6489
> [CORE] Prevent CH backend from referencing arrow-gluten Jars

- .github/workflows/velox_docker_cache.yml
@PHILO-HE 
https://github.com/apache/incubator-gluten/pull/6497
> [VL] Oops, a minor follow-up to #6497

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- gluten-core/src/main/java/org/apache/gluten/substrait/rel/LocalFilesBuilder.java
- gluten-core/src/main/java/org/apache/gluten/substrait/rel/LocalFilesNode.java
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-iceberg/src/main/java/org/apache/gluten/substrait/rel/IcebergLocalFilesNode.java
> [GLUTEN-6501][VL] Fix the missing fileReadProperties when constructing a LocalFilesNode

- docs/get-started/Velox.md
> [VL][DOC] Add uniffle doc

- cpp/CMake/ConfigArrow.cmake
> [GLUTEN-6529] Fix build error on macOS caused by ConfigArrow.cmake

- cpp/core/utils/ObjectStore.cc
- cpp/core/utils/ObjectStore.h
- cpp/core/utils/ResourceMap.h
> [GLUTEN-6534] [VL] Fix ObjectStore::stores initialized twice issue

- dev/package-vcpkg.sh
> [GLUTEN-6394][VL] Branch-1.2: Port #6395 Fix the vcpkg package script

- ep/build-velox/src/get_velox.sh
Today's 2nd Velox update
https://github.com/oap-project/velox/tree/2024_07_25-1
> [VL] Update Velox Version (2024_07_25-1)

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- cpp/core/jni/JniCommon.h
- cpp/core/memory/AllocationListener.h
- cpp/core/memory/MemoryAllocator.cc
- cpp/core/memory/MemoryAllocator.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/memory/VeloxMemoryManager.h
- gluten-core/src/main/java/org/apache/gluten/substrait/rel/LocalFilesBuilder.java
- gluten-core/src/main/java/org/apache/gluten/substrait/rel/LocalFilesNode.java
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-iceberg/src/main/java/org/apache/gluten/substrait/rel/IcebergLocalFilesNode.java
Add three PRs #6503 #6515 #6554 to branch-1.2 for critical bug fix.
Passed in main
> [VL] Branch-1.2: port PR #6503 PR #6515 PR #6554

- .github/workflows/velox_be.yml.deprecated
- .github/workflows/velox_docker.yml
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/DataGenMixin.java
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/DataGenOnly.scala
As title, also replace previous option `--skip-data-gen` with `--data-gen-strategy=skip`.
> [VL] Gluten-it: --data-gen-strategy=once to skip generating data when it already exists

- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2Base.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreeDeltaUtil.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHMergeTreeWriterInjects.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ConverterUtils.scala
> [GLUTEN-6589][CH] Mergetree supported spark.sql.caseSensitive

- cpp/velox/tests/CMakeLists.txt
- cpp/velox/tests/MyUdfTest.cc
This PR adds unit tests like [Velox functions test](https://facebookincubator.github.io/velox/develop/scalar-functions.html#testing) for udf examples
(Fixes: \#6195)
Passed unit tests.
> [GLUTEN-6195][VL]Add unit tests for udf

- backends-velox/src/main/scala/org/apache/gluten/extension/HLLRewriteRule.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
> [VL] Enable timestamp and binary type for HLL agg function

- gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
Untangle the code a little bit to allow developer use something like 
```
println(SparkMemoryUtil.dumpMemoryManagerStats(context.taskMemoryManager()))
```
in Spark task code to get the memory usage tree at any fixed point.
> [VL] Expose API `SparkMemoryUtil.dumpMemoryManagerStats(tmm: TaskMemoryManager)` for debugging purpose

- ep/build-velox/src/get_velox.sh
- ep/build-velox/src/setup-centos7.sh
- ep/build-velox/src/setup-centos8.sh
```
8e0181ef7 (upstream/main) Fix handling of NaN input for min_by/max_by aggregate (#10586)
de21ce6c9 Fix NaN handling for min/max aggreates pushed down to scan (#10583)
3fb96576e Fix hash build memory over use (#10534)
256d7002b Simdize stringCore::isAscii (#10582)
368c912eb Modify pad function to handle invalid unicode string for padString (#10549)
db11b69c9 Add support for time zone offsets to TimeZone (#10577)
237ff4149 Fix security issues from code scan (#10558)
b5713efcc Download source code archive directly for ubuntu and macos setup (#9198)
cf5aa68b9 Fix timezone handling in to_iso8601(timestamp) (#10576)
75020ec26 Fix logic right shift for negative numbers (#10575)
```
> [VL] Daily Update Velox Version (2024_07_29)

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
- cpp/velox/substrait/SubstraitParser.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Follow up for https://github.com/apache/incubator-gluten/pull/5934
UT.
> [VL] Enable collect_set, min, max for complex types

- backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/rewrite/PullOutPreProject.scala
- gluten-core/src/main/scala/org/apache/gluten/utils/PullOutProjectHelper.scala
Support date type in window range frame by rewrite orderSpecs to IntType.
(Fixes: #6600 )
UT
> [GLUTEN-6600][VL] Support date type in window range frame

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Parser/CrossRelParser.cpp
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Shuffle/PartitionWriter.h
- cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
- cpp-ch/local-engine/tests/benchmark_local_engine.cpp
- cpp-ch/local-engine/tests/gtest_ch_join.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240801)

- .github/labeler.yml
- .github/workflows/labeler.yml
Support automatically label new pull requests. Help reviewer easy to see the goal of pull request.
N/A
> [INFRA] Support automatically label new pull requests

- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
Hotfix a configuration bug in shuffle writer
unit tests
> [CH] Hotfix a configuration bug in shuffle writer

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RewriteSortMergeJoinToHashJoinRule.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHJoinValidateUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCDSAbstractSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSortMergeJoinSuite.scala
> [GLUTEN-6557][CH] Try to replace sort merge join with hash join when cannot offload it

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Disks/ObjectStorages/CompactObjectStorageDiskTransaction.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.h
- cpp-ch/local-engine/Storages/Mergetree/MetaDataHelper.cpp
- cpp-ch/local-engine/tests/benchmark_local_engine.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240803)

- cpp-ch/local-engine/Storages/Output/ORCOutputFormatFile.cpp
- cpp-ch/local-engine/Storages/Output/OutputFormatFile.cpp
- cpp-ch/local-engine/Storages/Output/OutputFormatFile.h
- cpp-ch/local-engine/Storages/Output/ParquetOutputFormatFile.cpp
Fix debug building error 
Manually tested.
> [CH] Fix debug building error

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-6669][CH] Fix diff of cast string to boolean

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxMetricsApi.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/MetricsUtil.scala
> [GLUTEN-6531] Minor polish for metrics code

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
> [GLUTEN-6686][CH] Disable percent_rank

- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2Base.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseHiveTableSuite.scala
> [GLUTEN-6589][CH] Mergetree supported spark.sql.caseSensitive[Part.2]

- gluten-celeborn/common/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
> [CELEBORN][FOLLOWUP] Add compression for row-based shuffle

- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- ep/build-velox/src/get_velox.sh
> [VL] Daily update velox version 08-08

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
A new test case derived from discussion in issue https://github.com/apache/incubator-gluten/issues/6630. Note the PR doesn't fix anything yet.
The case gets [this code](https://github.com/apache/incubator-gluten/blob/1ec37bd04709db5fc09001aef9bcc5099b4a225f/backends-velox/src/main/scala/org/apache/gluten/extension/FlushableHashAggregateRule.scala#L64-L67) covered.
> [VL] Add a new test case for FlushableHashAggregateRule's coverage

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- cpp-ch/local-engine/local_engine_jni.cpp
> [GLUTEN-6750][CH] Fix optimize error if file mappings not loaded

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
> [GLUTEN-6778][CH] Enable percent_rank again

- ep/build-velox/src/get_velox.sh
Update OAP Velox to gluten-1.2.0
local server
> [VL][1.2] Update OAP Velox to gluten-1.2.0

- gluten-ut/test/src/test/scala/org/apache/spark/sql/GlutenExpressionDataTypesValidation.scala
> [VL] Validate binary expressions with their accepted types

- cpp-ch/local-engine/Common/QueryContext.cpp
- cpp-ch/local-engine/Parser/TypeParser.cpp
- cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
- cpp-ch/local-engine/Storages/SourceFromJavaIter.h
(Fixes: \#6819)
original uts introduced in  
- https://github.com/apache/incubator-gluten/pull/4317 
- https://github.com/apache/incubator-gluten/pull/4829
> [GLUTEN-6819][CH] Refactor source from jave iter &&  make casting happens before materializing

- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
- cpp/velox/utils/tests/VeloxShuffleWriterTestBase.h
Fix issue #6822, add UT.
Fix sort time metrics. The sort time should exclude evict time.
> [GLUTEN-6822][VL] Fix wrong maxRowsToInsert and sort time metrics

- cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
> [GLUTEN-6819][CH] HOTFIX variable shadow in source from jave iter

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Common/GlutenStringUtils.cpp
- cpp-ch/local-engine/Common/GlutenStringUtils.h
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
(Fixes: \#6879)
by adding new uts
> [GLUTEN-6879][CH] Fix partition value diff when it contains blank spaces

- .github/workflows/dev_cron.yml
Test permission issue in github action workflow.
N/A
> [GLUTEN-6915][MISC]Fix workflow permission issue.

- .github/workflows/dev_cron.yml
- .github/workflows/dev_cron/issues_link.js
- .github/workflows/dev_cron/title_check.js
Fix github action script v7's listComments TypeError issue
n/a
> [GLUTEN-6915][CORE]Fix listComments TypeError

- .github/workflows/clickhouse_be_trigger.yml
> [GLUTEN-6915][CH] Follow VL, fix github issue comment

- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.cpp
- cpp-ch/local-engine/Storages/CustomStorageMergeTree.h
- cpp-ch/local-engine/Storages/StorageMergeTreeFactory.cpp
- cpp-ch/local-engine/Storages/StorageMergeTreeFactory.h
Added cleanup logic for expiration mergetree part cache
unit tests, manual tests
> [CH] Added cleanup logic for expiration mergetree part cache

- gluten-data/src/main/scala/org/apache/gluten/runtime/Runtime.scala
A follow-up of #6959, fix for the wrong dump message.
> [VL] Following #6959, leak memory dump is not correctly printed

- README.md
This PR aims to fix command error with spark-shell.
Fix #6987
manual tests
> [GLUTEN-6987][DOC] fix: add shell newline character after spark-shell

- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-data/src/main/java/org/apache/gluten/metrics/Metrics.java
- gluten-data/src/main/java/org/apache/gluten/metrics/OperatorMetrics.java
- gluten-data/src/main/scala/org/apache/gluten/metrics/HashAggregateMetricsUpdater.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/JoinMetricsUpdater.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/MetricsUtil.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/SortMetricsUpdater.scala
- gluten-data/src/main/scala/org/apache/spark/sql/utils/SparkMetricsUtil.scala
> [GLUTEN-7008][VL] Report spill metrics from Velox operators to Spark task

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/arrayExcept.cpp
> [GLUTEN-4724][CH] Support function array_except

- cpp/velox/CMakeLists.txt
- dev/vcpkg/ports/libstemmer/CMakeLists.txt
- dev/vcpkg/ports/libstemmer/portfile.cmake
- dev/vcpkg/ports/libstemmer/vcpkg.json
- dev/vcpkg/vcpkg.json
This is a dependency required by velox. We are trying to remove bundled build from velox for this lib.
Fix #7049.
CI.
> [GLUTEN-7049][VL] Install lib stemmer through vcpkg

- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/StorageJoinBuilder.java
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseColumnarMemorySortShuffleSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseColumnarShuffleAQESuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDSV2ColumnarShuffleSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDSV2Suite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHNullableColumnarShuffleSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHNullableSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetAQESuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.h
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
- cpp-ch/local-engine/Operator/EarlyStopStep.cpp
- cpp-ch/local-engine/Operator/EarlyStopStep.h
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
- gluten-celeborn/clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseRSSColumnarMemorySortShuffleSuite.scala
- gluten-celeborn/clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseRSSColumnarShuffleAQESuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
Support BHJ + isNullAwareAntiJoin for the CH backend, for example: TPCH Q16
Close #341.
(Fixes: #341)
> [GLUTEN-341][CH] Support BHJ + isNullAwareAntiJoin for the CH backend

- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2Base.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/clickhouse/MergeTreeFileFormatWriter.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
> [GLUTEN-6589][CH] Fix alias name cause caseSensitive error on mergetree create

- ep/build-clickhouse/src/package.sh
Package with spark 3.5
Test by ci package
https://opencicd.kyligence.com/job/gluten/job/gluten-package/1699/
> [CH] Add package with spark 3.5

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/MiscColumnarRules.scala
(Fixes: \#7148)
Test plan change log locally.
> [GLUTEN-7148][CORE] Remove duplicated plan change log on TransformPreOverrides rule

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/clickhouse/MergeTreeFileFormatWriter.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
> [GLUTEN-7155][CH] Fix bucket table create error by mergetree

- backends-clickhouse/pom.xml
- docs/get-started/ClickHouse.md
- ep/build-clickhouse/src/package.sh
Shade clickhouse backend dependency jars
Fixes: \#7023
Manual verification by running basic queries.
> [GLUTEN-7023][CH] Shade dependency jars

- ep/build-clickhouse/src/package.sh
> [CH] Minor, update package.sh

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/CommonScalarFunctionParser.cpp
> [GLUTEN-6808][CH] support function arrays_zip

- .github/workflows/velox_backend.yml
- backends-velox/src/test/java/org/apache/gluten/test/VeloxBackendTestBase.java
- cpp/velox/compute/VeloxBackend.cc
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
See issue #7164 .
This option is impacting Gluten's stability. Should turn it off by default until the issues get resolved or some kind of new design is made.
> [GLUTEN-7164][VL] Disable background IO threads by default

- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-7177][CH] Fix read hdfs performance issue

- cpp-ch/local-engine/Storages/Parquet/ColumnIndexFilter.cpp
- cpp-ch/local-engine/tests/gtest_parquet_columnindex.cpp
> [GLUTEN-7179][CH] Fix infinite loop with parquet column index reader

- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCHCacheDataCommand.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeCacheDataSuite.scala
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/ExtensionTableBuilder.java
Fix MergeTree cache load failed when column name is upper case
unit tests
> [CH] Fix load cache missing columns

- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicPhysicalOperatorTransformer.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/DummyFilterColmnarHelper.scala
> [MINOR] Duplicate extends SparkPlan

- cpp-ch/local-engine/Parser/LocalExecutor.cpp
> [GLUTEN-7202][CH] Fix: local executor cannot dump pipeline stats

- ep/build-velox/src/get_velox.sh
```txt
98bbb73ec by kevincmchen, Add support for smallint to PrefixSort (#10946)
741876fe2 by Orri Erling, Add status return and fixes for nulls (#10954)
baaf559ba by Deepak Majeti, Fix S3FileSystem CRC32 checksum on AWS S3 (#10918)
9e62de72c by Jimmy Lu, Add config to use selective Nimble reader (#10990)
4ba2066b6 by Xiaoxuan Meng, Add to recover SSD cache space on server restart (#10967)
aa006bb2f by Xiaoxuan Meng, dwio integer decoder code cleanup (#10961)
a665891b4 by Xiaoxuan Meng, Fix recursive memory arbitration caused by parallel spill (#10975)
d1ac07936 by wypb, Disable fastpath reading for some data types in ORC (#10939)
```
> [GLUTEN-6887][VL] Daily Update Velox Version (2024_09_13)

- cpp-ch/local-engine/docker/build.sh
- cpp-ch/local-engine/docker/image/Dockerfile
- cpp-ch/local-engine/docker/image/build.sh
- docs/get-started/ClickHouse.md
> [GLUTEN-7224][CH]Update doc for compiling ch backend

- docs/get-started/ClickHouse.md
> [GLUTEN-7224][CH] update doc for compiling ch backend

- cpp-ch/local-engine/Parser/RelParsers/RelParser.cpp
> [GLUTEN-7222][CH] Fail to compile ch backend

- .github/workflows/velox_backend.yml
- cpp/velox/compute/WholeStageResultIterator.cc
- ep/build-velox/src/get_velox.sh
#7243 
Rely on https://github.com/oap-project/velox/tree/2024_09_14-2
> [GLUTEN-7243][VL] Fix Q97 cross-task spilling hangs

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/shuffle/VeloxRssSortShuffleWriter.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/VeloxSubstraitSignature.cc
- cpp/velox/substrait/VeloxToSubstraitPlan.cc
- ep/build-velox/src/get_velox.sh
```
66b5b0d34 Improve dependency install and build (#10920)
a8a21a483 Require semicolon after velox macros, avoid triggering `-Wextra-semi`
8a6ab1569 Support UNSUPPORTED_INPUT_UNCATCHABLE VeloxRuntimeError in expression fuzzer (#10993)
648ae8974 Parquet LazyVector support (#11010)
a8bd2dea2 Ignore time zones that are not recognizable by OS when building time zone database (#10654)
```
> [GLUTEN-6887][VL] Daily Update Velox Version (2024_09_19)

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCacheFilesCommand.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeCacheDataSuite.scala
> [GLUTEN-7262][CH] Fix cache file commond run normal with config disabled

- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/SparkRunModes.java
In gluten-it's auto cluster mode, the ratio between on-heap memory and off-heap memory is 1:2. The patch makes this ratio configurable.
> [VL] Gluten-it: In auto cluster mode, add option `--off-heap-ratio` for adjusting memory shares of off-heap and on-heap

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
> [GLUTEN-6768][CH] Clear unused configures after refactor reordering hash join tables

- .github/workflows/velox_docker.yml
Upgrade GHA artifacts version to 3
n/a
> [VL][1.2] Upgrade GHA artifacts version to 3

- dev/package-vcpkg.sh
> [VL] fix vcpkg package script #7052

- .github/workflows/util/install_spark_resources.sh
- .github/workflows/util/setup_helper.sh
- .github/workflows/velox_backend.yml
- dev/ci-velox-buildshared-centos-8.sh
- dev/ci-velox-buildstatic-centos-7.sh
- dev/vcpkg/ports/simdjson/vcpkg.json
For accelerating CI validation for PR targeting to branch-1.2. Also included json related fix, which is necessary to 1.2 branch.
> [VL] Port CI changes to branch-1.2 and pick simdjson related fix

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- gluten-arrow/pom.xml
- gluten-arrow/src/main/scala/org/apache/spark/sql/utils/SparkArrowUtil.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ConverterUtils.scala
> [GLUTEN-7178][VL] Fix field not found error when struct field name contains upper case

- gluten-substrait/src/main/scala/org/apache/gluten/execution/ScanTransformerFactory.scala
After #7215, allPushDownFilters param of `createBatchScanTransformer` and `createFileSourceScanTransformer` is unused. 
In addition, batchScan's runtimeFilters will not change.
CI.
> [CORE] Remove unused allPushDownFilters param

- .github/workflows/velox_backend.yml
This issue causes the test too time-consuming (near 4 hours). After this fix, the test time is reduced to ~46min.
> [VL] Follow-up fix for #7314 on branch-1.2: skip data gen in oom test

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionDecimalBinaryArithmetic.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-6975][CH] Fix decimal cast overflow exception

- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.cpp
(Fixes: \#7348)
Test by old ut
> [GLUTEN-7348][CH] Move function calculateColumnAndSecondaryIndexSizesImpl outside

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
https://github.com/facebookincubator/velox/pull/10508
> [VL] Enable AtLeastNNonNulls function

- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
Fixes: \#[7376](https://github.com/apache/incubator-gluten/issues/7376)
through exits uts
> [GLUTEN-7376][ICEBERG]Avoid retrieving the partition schema of Iceberg

- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.cpp
This reverts commit dc8a91ce337a2e8f20bbee12a38ca946ebdff06f.
(Fixes: \#7427)
Existed UT
> [GLUTEN-7427][CH]Revert "fix (#7349)"

- cpp/core/jni/JniCommon.cc
- cpp/core/jni/JniError.cc
- cpp/core/memory/MemoryAllocator.cc
- cpp/velox/jni/JniFileSystem.cc
- cpp/velox/shuffle/VeloxShuffleReader.cc
- cpp/velox/udf/UdfLoader.cc
Add checks for allocation failures and initialize variables
Fixes: 7418
Build locally and on CI.
> [GLUTEN-7418][VL] Add checks for allocation failures and initialize variables

- gluten-core/src/main/scala/org/apache/gluten/backend/Backend.scala
This PR proposes to make `Backend` follows the Scala code style.
This PR also simplify the code.
> [GLUTEN-7400][CORE] Scala code style clean up for Backend.scala

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
This PR proposes to make code cleanup for `GlutenPlugin`.
> [GLUTEN-7402][CORE] Code cleanup for GlutenPlugin

- cpp/velox/CMakeLists.txt
- cpp/velox/operators/writer/VeloxParquetDatasource.h
- cpp/velox/tests/Substrait2VeloxPlanConversionTest.cc
This is another part of work to reduce dependencies on velox build directory.
CI build.
> [VL] Remove VELOX_BUILD_PATH from include directories if build test is disabled

- ep/build-velox/src/get_velox.sh
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
https://github.com/apache/incubator-gluten/issues/7440
With unit test.
> [GLUTEN-7440][VL] Enable unit tests on missing all struct fields

- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
Add test after resolved #6784 and #6828.
> [GLUTEN-6784][GLUTEN-6828][VL] Add tests for weekOfYear and cast string as date

- ep/build-velox/src/get_velox.sh
As required changes for upstream velox have been merged, see https://github.com/facebookincubator/velox/pull/11219, this pr removes some useless code in Gluten.
CI.
> [GLUTEN-7480][VL] Clean up some code for protobuf

- gluten-delta/src/main/scala/org/apache/gluten/extension/DeltaRewriteTransformerRules.scala
- gluten-delta/src/test/scala/org/apache/gluten/execution/VeloxDeltaSuite.scala
This PR aims to push down input_file_name expression to transformer scan in delta.
(Fixes: \#7291)
Add new unit test.
> [GLUTEN-7291][DELTA] fix: push down input_file_name expression to transformer scan in delta

- shims/spark32/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
Code cleanup for https://github.com/facebookincubator/velox/commit/0758d04da316f28b77f359a0cb45fc5a4a0aaf3f
> [GLUTEN-6887][VL] Code clean for hasUnsupportedColumns function

- cpp/core/CMakeLists.txt
- cpp/velox/CMakeLists.txt
Fixes: \#7495
Local build test.
> [GLUTEN-7495][BUILD] Fix macOS does not support version-script

- docs/get-started/Velox.md
As mentioned in https://github.com/apache/incubator-gluten/issues/7439#issuecomment-2407492656, the guide is outdated.
Fixes #7493.
N/A
> [GLUTEN-7493][VL] Update Velox.md to clarify dependency deployment

- cpp-ch/local-engine/Parser/scalar_function_parser/elementAt.cpp
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-7484][CH]Fix element_at diff

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.h
> [GLUTEN-7432][CH] Exception when the result of get_json_object is an array

- backends-velox/src/main/scala/org/apache/gluten/expression/aggregate/VeloxCollect.scala
This PR proposes to make `VeloxCollect` follows up the Scala code style.
> [GLUTEN-7526][VL] Scala code style for VeloxCollect

- ep/build-clickhouse/src/package.sh
> [GLUTEN-7517][CH] Support build gluten package with scala213

- ep/build-velox/src/modify_velox.patch
These patches are not required now, maybe since we make Gluten link unified lib: libvelox.a.
CI.
> [GLUTEN-7539][VL] Remove some unnecessary Velox code changes from modify_velox.patch

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseHDFSSuite.scala
- cpp-ch/local-engine/Common/FileCacheConcurrentMap.h
- cpp-ch/local-engine/Storages/Cache/CacheManager.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
> [GLUTEN-7542][CH] Fix cache not refresh

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCacheFilesCommand.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseHDFSSuite.scala
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
(Fixes: \#7482)
Also recode function `set_read_util_position`
Test by ut
> [GLUTEN-7482][CH] Remove redundant head object operation of s3

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.h
Fixes: #7563 
Just replace the too large number by "Infinity" at present.
unit tests
> [GLUTEN-7563][CH] Fix failure on too large double number

- gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/gluten/uniffle/UniffleShuffleManager.java
> [GLUTEN-7559][VL][UNIFFLE] Set rss.enabled to true in UniffleShuffleManager

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarPartialProjectExec.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/UDFPartialProjectSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionUtils.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/cost/LegacyCostModel.scala
Following #7360, enable the feature in RAS.
> [GLUTEN-7359][VL] Enable partial project in RAS

- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ColumnarBatchOutIterator.java
- gluten-core/src/main/java/org/apache/gluten/iterator/ClosableIterator.java
Check if closed in `ColumnarBatchOutIterator.hasNext`
closes #7572
minor fix
> [GLUTEN-7572][CORE] Check if iterator has been closed

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/tests/benchmark_parquet_read.cpp
- cpp-ch/local-engine/tests/benchmark_spark_row.cpp
- cpp-ch/local-engine/tests/gtest_parquet_read.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20241018)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.h
> [GLUTEN-7591][CH]Fix: fail to normalize json text with empty object in it

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetRFSuite.scala
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
> [GLUTEN-7596][CH] Fix bnlj empty join error

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseStringFunctionsSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/repeat.cpp
> [GLUTEN-7621][CH] Fix repeat function reports an error when times is a negative number

- backends-velox/src/main/scala/org/apache/gluten/extension/BloomFilterMightContainJointRewriteRule.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/CollectRewriteRule.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/FlushableHashAggregateRule.scala
> [GLUTEN-7577][VL] Add pattern match for extension rules

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ColumnarRuleApplier.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ColumnarRuleExecutor.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala
This PR proposes to give a suitable name for columnar rule executor.
This PR also contains some minor improvement.
> [GLUTEN-7604][CORE] Code refactors against ColumnarRuleApplier.Executor

- backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHExpressionTransformer.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
> [GLUTEN-7545][CH] Fix regexp_replace group catching syntax diff

- backends-clickhouse/src/main/java/org/apache/gluten/execution/CacheResult.java
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCacheBase.scala
(Fixes: \#7623)
Test by Manual
> [GLUTEN-7623][CH] Fix running cache command with error when executor add and removed.

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetAQESuite.scala
- cpp-ch/local-engine/Parser/RelParsers/JoinRelParser.cpp
> [GLUTEN-7673][CH] Fix substrait infinite loop

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos7.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos8.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos9.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderDebian11.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderDebian12.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderUbuntu2004.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderUbuntu2204.scala
- cpp/velox/CMakeLists.txt
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/utils/HdfsUtils.h
- ep/build-velox/src/get_velox.sh
- ep/build-velox/src/modify_velox.patch
- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
- gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
Reverts apache/incubator-gluten#6172
> Revert "[GLUTEN-5103][VL] Use jvm libhdfs replace c++ libhdfs3"

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/tests/gtest_write_pipeline_mergetree.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20241026)

- cpp-ch/local-engine/Functions/SparkFunctionFloor.h
fix compile error under ARM.
(Fixes: \#GLUTEN-7681)
by CI.
> [GLUTEN-7681][CH][ARM] Fix compile issue for SparkFunctionFloor

- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicPhysicalOperatorTransformer.scala
> [VL] Code clean for BasicPhysicalOperatorTransformer

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CommonSubexpressionEliminateRule.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RewriteDateTimestampComparisonRule.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RewriteToDateExpresstionRule.scala
This PR proposes to simplify Rule constructor.
> [GLUTEN-7709][CH] Rule constructor simplifications

- cpp-ch/local-engine/Functions/SparkFunctionRoundHalfUp.h
fix compile error under ARM.
(Fixes: \#7717)
by CI.
> [GLUTEN-7717][CH] [ARM]fix compile issue for SparkFunctionRoundHalfUp

- backends-velox/src/test/scala/org/apache/gluten/execution/FallbackSuite.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Part of #7143 
Following https://github.com/apache/incubator-gluten/pull/7701, fix a test case "test ignore row to columnar" when RAS=ON 
And with other follow-up cleanups.
> [GLUTEN-7143][VL] RAS: Fix test case "test ignore row to columnar" when RAS=ON

- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.cpp
- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/examples/CMakeLists.txt
- cpp-ch/local-engine/examples/splittable_bzip2_read_buffer.cpp
> [GLUTEN-7714][CH]Fix issue caused by incomplete line if there is only one line in last bzip2 block

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/clickhouse/utils/MergeTreePartsPartitionsUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
> [GLUTEN-7670][CH] Fix enable 'files.per.partition.threshold' bug

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHValidatorApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxValidatorApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/ValidatorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
Part of https://github.com/apache/incubator-gluten/issues/7143
Fix the following test cases in `GlutenSQLQueryTestSuite` when RAS=ON:
* typeCoercion/native/windowFrameCoercion.sql
* postgreSQL/window_part3.sql
* postgreSQL/window_part2.sql
> [VL] RAS: Fix failed UTs in GlutenSQLQueryTestSuite

- cpp-ch/local-engine/Functions/SparkFunctionHashingExtended.h
> [GLUTEN-7747][CH] Fix murmur3hash on arm

- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.cpp
- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.h
> [GLUTEN-7771][CH]Fix crc32 failure in bzip2

- pom.xml
See https://maven.apache.org/enforcer/enforcer-rules/requireOS.html
Fixes: #7782
local test.
> [GLUTEN-7782] Fix profile Darwin-x86 os.arch error

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionSplitByRegexp.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/split.cpp
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-7780][CH] Fix split diff

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseWholeStageTransformerSuite.scala
> [GLUTEN-7792][CH] Set default minio ak/sk to minioadmin

- .github/workflows/util/install_spark_resources.sh
- docs/release.md
updates for release plan
docs update only
> [DOC] Update release plan for Velox backend

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/FallbackBroadcastHashJoinRules.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/MergeTwoPhasesHashBaseAggregate.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ColumnarRuleApplier.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/FallbackRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenFallbackReporter.scala
This PR proposes to unify the the variable name of `GlutenConfig` with `glutenConf`.
Fixes: https://github.com/apache/incubator-gluten/issues/7727
> [GLUTEN-7727][CORE] Unify the variable name of GlutenConfig with glutenConf

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Storages/Output/WriteBufferBuilder.cpp
> [GLUTEN-7700][CH] Fix issue when partition values contain space

- .github/workflows/velox_weekly.yml
- ep/build-velox/src/setup-centos7.sh
Fix #7797.
Existing scheduled job.
> [GLUTEN-7797][VL] Fix lacking icu lib on centos-7

- .github/workflows/clickhouse_be_trigger.yml
> [GLUTEN-7814][CH] Support trigger Gluten ClickHouse CI on ARM

- cpp-ch/local-engine/Functions/SparkFunctionRoundHalfUp.h
> [GLUTEN-7654][CH] Fix round on arm

- backends-clickhouse/src/main/java/org/apache/gluten/memory/CHThreadGroup.java
- cpp-ch/local-engine/Common/QueryContext.cpp
- cpp-ch/local-engine/Common/QueryContext.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
- cpp-ch/local-engine/local_engine_jni.cpp
(Fixes: \#7795)
Test by local log
> [GLUTEN-7795][CH] Add backend task id log

- cpp/velox/compute/WholeStageResultIterator.cc
Just remove some useless code.
CI.
> [VL] Remove one legacy Velox config used for Spark collect_list function

- gluten-substrait/pom.xml
> [CORE] Remove unused dependencies of gluten-substrait

- cpp/velox/config/VeloxConfig.h
- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/shuffle/VeloxRssSortShuffleWriter.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Reverts apache/incubator-gluten#7799
Due to https://github.com/apache/incubator-gluten/pull/7799#issuecomment-2461091637
> Revert "[GLUTEN-7800][VL] Add config for max reclaim wait time to avoid dead lock when memory arbitration"

- cpp-ch/local-engine/Common/DebugUtils.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.h
(Fixes: #7795)
Test by log trace
> [GLUTEN-7795][CH] Remove duplicate log object

- dev/docker/Dockerfile.centos7-static-build
EPEL repository should be enabled before the installation. 
Local test.
> [VL] Fix ccache installation in docker

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxOrcDataTypeValidationSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxParquetDataTypeValidationSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/LimitExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/TakeOrderedAndProjectExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/FallbackRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
As title, a minor code cleanup.
> [CORE] Minor: Rename LimitTransformer to LimitExecTransformer

- dev/docker/Dockerfile.centos7-static-build
Follow-up fix for #7848.
Local test.
> [VL] Follow-up fix for PR #7848 to install ccache

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/PushdownAggregatePreProjectionAheadExpand.scala
> [GLUTEN-7862][CH]fix pre-projection in aggregate not take effect

- .github/workflows/build_bundle_package.yml
- .github/workflows/velox_backend.yml
- .github/workflows/velox_backend_cache.yml
- dev/ci-velox-buildshared-centos-8.sh
- dev/ci-velox-buildstatic-centos-7.sh
- dev/vcpkg/README.md
- docs/developers/NewToGluten.md
- ep/build-velox/src/get_velox.sh
> [VL] Clean up some legacy code and correct minimum GCC version

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/LazyAggregateExpandRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
Fixes: #7647
After #7811, we could enable `avg` and `sum(decimal)` now.
unit tests
> [GLUTEN-7647][CH]  Enable lazy expand for `avg` and `sum(decimal)`

- .gitignore
minor change, exclude metastore_db from git.
>  [MINOR][INFRA] Exclude metastore_db from git

- backends-velox/src/main/scala/org/apache/spark/sql/hive/VeloxHiveUDFTransformer.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
- docs/developers/VeloxUDF.md
- gluten-substrait/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
- gluten-substrait/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
1. Fix udf implicit type conversion not working, refine the UT.
2. Update the hive udf example in UDF document
3. Moved some general utility functions from `WholeStageTransformerSuite` into `GlutenQueryTest`
> [GLUTEN-7760] Fix udf implicit cast & update doc

- gluten-ui/src/main/scala/org/apache/spark/sql/execution/ui/GlutenSQLAppStatusListener.scala
> [GLUTEN-7890][UI] Optimize cleanup gluten sql executions ui data

- backends-velox/src/test/scala/org/apache/gluten/execution/FallbackSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxMetricsSuite.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/benchmark/StreamingAggregateBenchmark.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/joins/GlutenInnerJoinSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/joins/GlutenOuterJoinSuite.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
> [Minor] Fix a typo in Gluten config

- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/shuffle/VeloxRssSortShuffleWriter.cc
Clean up unused variables to avoid compilation warnings.
With existing unit tests.
> [VL] Clean up unused variables in cpp source files

- cpp-ch/local-engine/local_engine_jni.cpp
replace jstring2string implementation, avoid SIGSEGV on getObjectClass
manual tests
> [CH] Fix SIGSEGV on jstring2string

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/LazyAggregateExpandRule.scala
Fixes: #7647
unit tests,  manual tests
> [GLUTEN-7647][CH] Fixed a bug in finding attributes in replacement map

- .github/workflows/velox_backend.yml
#7328 cause back upload golden files missing, fix it.
https://github.com/apache/incubator-gluten/actions/runs/11754657570?pr=7877 No golden files are generated.
https://github.com/apache/incubator-gluten/actions/runs/11755452070?pr=7879 golden files are generated.
> [VL][CI] Fix back upload golden files

- .github/workflows/clickhouse_be_trigger.yml
Support trigger CK Backend CI/CD in branch1.2
n/a
> [CK][1.2] Support trigger CK Backend CI/CD in branch1.2

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionMapToString.h
(Fixes: \#7594)
This patch was tested by unit tests.
> [GLUTEN-7594] [CH] support cast const map to string

- gluten-substrait/src/main/scala/org/apache/gluten/execution/BroadcastNestedLoopJoinExecTransformer.scala
> [GLUTEN-7947][CORE] Add buildSide info for BroadcastNestedLoopJoinExecTransformer simpleStringWithNodeId

- cpp-ch/local-engine/Operator/AdvancedExpandStep.cpp
> [GLUTEN-7959][CH] `AdvancedExpandStep` generates less row than expected

- cpp-ch/local-engine/Common/AggregateUtil.cpp
- cpp-ch/local-engine/Common/AggregateUtil.h
- cpp-ch/local-engine/Operator/AdvancedExpandStep.cpp
- cpp-ch/local-engine/Parser/RelParsers/AggregateRelParser.cpp
> [GLUTEN-7962][CH] A friendly API to build aggregator params

- docs/developers/MicroBenchmarks.md
- docs/get-started/Velox.md
Usage doc about how to enable libhdfs and libhdfs3 in runtime.
No need.
> [GLUTEN-7887][VL][DOC] Add usage doc about dynamic load jvm libhdfs and native libhdfs3

- cpp/velox/config/VeloxConfig.h
- cpp/velox/memory/VeloxMemoryManager.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
> [GLUTEN-7800][VL] Add config for max reclaim wait time to avoid dead lock when memory arbitration

- dev/build-thirdparty.sh
- dev/package-vcpkg.sh
- dev/package.sh
- dev/vcpkg/Makefile
- dev/vcpkg/ports/duckdb/portfile.cmake
- dev/vcpkg/ports/duckdb/vcpkg.json
Port #6560 #6569 #6730 #7117 for vcpkg and package script installation bug fix.
local
> [VL][1.2] Port #6560 #6569 #6730 #7117 for vcpkg issue fix

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHValidatorApi.scala
- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
The API is unlikely general so remove it from backend API.
> [CORE][CH] Remove API BackendSettingsApi#supportShuffleWithProject

- cpp/CMake/Buildjemalloc.cmake
- docs/developers/HowTo.md
- docs/developers/ProfileMemoryOfGlutenWithVelox.md
- docs/get-started/build-guide.md
> [VL] Bump jemalloc version and update relevant documents

- .github/workflows/build_bundle_package.yml
- .github/workflows/velox_backend.yml
- .github/workflows/velox_backend_cache.yml
This patch fixes the cache/build script due to nodejs version update in GHA
This patch also adds centos7 tests back
fixes #8046
pass GHA
> [GLUTEN-8046][VL] CI: fix velox cache/bundle package script

- dev/vcpkg/ports/libelf/portfile.cmake
> [VL] Branch 1.2: Port #8047 to fix libelf link

- .github/workflows/velox_backend.yml
- cpp/CMakeLists.txt
- cpp/core/CMakeLists.txt
- cpp/velox/CMakeLists.txt
- dev/ci-velox-buildshared-centos-8.sh
- ep/build-velox/src/get_velox.sh
> [VL][Branch-1.2] Port #8034 & #8027 for fixing march flag setting and #8042 for fixing GHA failure on centos-7

- cpp/core/config/GlutenConfig.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/Options.h
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Spill.cc
- cpp/core/shuffle/Spill.h
- cpp/core/shuffle/Utils.cc
- cpp/core/shuffle/Utils.h
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Port #7861 to fix OOM in shuffle writer.
> [CORE][BRANCH-1.2] Port #7861 to fix OOM in shuffle writer

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDecimalSuite.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-8074][CH] Fix adjust output constant column

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHBucketSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetBucketSuite.scala
- cpp-ch/local-engine/Common/GlutenConfig.cpp
- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Operator/GraceAggregatingTransform.cpp
- cpp-ch/local-engine/Operator/GraceAggregatingTransform.h
> [GLUTEN-8096][CH] Invalid header for disk tmp file

- tools/workload/tpcds/README.md
- tools/workload/tpch/README.md
Fixed several file path hyperlink errors
(Fixes: \#8103)
no need
> [GLUTEN-8103][DOC] Fix TPC-H/DS queries link

- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/execution/FileDeltaColumnarWrite.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/RuntimeSettings.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/WriteFilesWithBucketValue.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarWrite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseNativeWriteTableSuite.scala
- cpp-ch/local-engine/Parser/RelParsers/WriteRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/WriteRelParser.h
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeSink.h
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.cpp
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.h
- cpp-ch/local-engine/Storages/Output/OutputFormatFile.cpp
- cpp-ch/local-engine/tests/gtest_write_pipeline.cpp
Support write parquet files with bucket
(Fixes: \#7028)
unit tests
> [GLUTEN-7028][CH][Part-11] Support write parquet files with bucket

- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-8130][CH] Use the actual user instead of yarn user to read hdfs file

- cpp/velox/shuffle/VeloxHashShuffleWriter.cc
- cpp/velox/shuffle/VeloxHashShuffleWriter.h
> [VL] Enhance VeloxHashShuffleWriter partition buffer size estimation by incorporating complex type columns

- docs/get-started/build-guide.md
Remove build_protobuf parameter from build-guide
> [GLUTEN-7518][FOLLOWUP] Remove build_protobuf parameter from build-guide

- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/Metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/tests/VeloxSubstraitRoundTripTest.cc
Follows https://github.com/facebookincubator/velox/commit/28c319e6eb2a8ea77718ae3d53b2f79f5fddd75e to Change C style casts to C++ style.
CI verified.
> [VL] Change C style casts to C++ style

- docs/developers/CppCodingStyle.md
- docs/developers/MicroBenchmarks.md
- docs/developers/NewToGluten.md
- docs/developers/VeloxUDF.md
- docs/get-started/ClickHouse.md
- docs/get-started/Velox.md
- docs/get-started/VeloxGCS.md
- docs/velox-backend-limitations.md
Fix typos in documentation.
None
> [DOC] Fix typos in documentation

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
- cpp-ch/local-engine/Parser/AggregateFunctionParser.h
> [GLUTEN-8148][CH] Fix corr with NaN

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BatchScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/CartesianProductExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ScanTransformerFactory.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/offload/OffloadSingleNodeRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
1. Offload scan does not need to doValidate again.
2. Remove catch of FallbackByNativeValidation.
> [CORE] Simplify code of offload scan

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RemoveDuplicatedColumns.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
> [GLUTEN-8142][CH] Duplicated columns in group by

- .github/workflows/velox_backend.yml
- docs/get-started/Velox.md
- pom.xml
- tools/gluten-it/pom.xml
Bump uniffle 0.9.1, https://uniffle.apache.org/download/release-notes-0.9.1/
CI
> [CORE][UNIFFLE] Bump uniffle 0.9.1

- .github/workflows/docker_image.yml
- .github/workflows/stale.yml
- .github/workflows/velox_weekly.yml
Enable scheduled GHAs for gluten apache repo
> Disable scheduled GHA jobs for forked repos

- cpp/core/compute/Runtime.cc
- cpp/core/utils/ObjectStore.cc
- cpp/core/utils/ObjectStore.h
- cpp/velox/jni/JniFileSystem.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
- cpp/velox/udf/UdfLoader.cc
- cpp/velox/udf/UdfLoader.h
Rename functions with number suffix to avoid miss-reading.
Existing UTs.
> [VL] Minor fix for cpp code style (part 2)

- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20241212)

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxWindowExpressionSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Support collect_set in window, after 
(Fixes: \#8206)
Add new tests
> [GLUTEN-8206][VL] Support collect_set in window

- backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseColumnarShuffleAQESuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseJoinSuite.scala
- gluten-celeborn/clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseRSSColumnarShuffleAQESuite.scala
> [GLUTEN-8216][CH] Fix OOM when cartesian product with empty data

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
We have a pr to upstream velox: https://github.com/facebookincubator/velox/pull/8854.
Existing Spark tests.
> [VL] Support concat_ws function

- docs/developers/HowTo.md
Fix broken link and update shell script location in HowTo.md
Not applicable.
> [DOC] Update HowTo.md to fix outdated link and test script location

- ep/build-clickhouse/src/package.sh
> minor, remove deprecated gluten-clickhouse-celeborn jar

- .github/workflows/util/install_spark_resources.sh
- .github/workflows/velox_backend.yml
- dev/docker/Dockerfile.centos8-dynamic-build
Recently, CI job fails frequently due to the download limit of apache archive site. This pr simply re-installed the resources into docker image.
Will create another PR to remove the download after docker image is updated with this pr.
> [GLUTEN-8266][VL][CI] Pre-install spark sources in docker image

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/metadata/LogicalLink.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/plan/GlutenPlanModel.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/property/Conv.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transition.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/RasCluster.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpGroupAlgo.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpPlanner.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpZipperAlgo.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/ForwardMemoTable.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/path/Pattern.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/util/IndexDisjointSet.scala
1. Fix `logical link mismatch` warnings
2. Comment typo cleanups
> [VL] RAS: A couple of minor fixes for RAS

- backends-velox/src/main/scala/org/apache/gluten/extension/PartialProjectRule.scala
> [VL] Simplify code for PartialProjectRule

- .github/workflows/clickhouse_be_trigger.yml
> [CH] Disable gluten arm ci

- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/tests/gtest_parquet_read.cpp
(Fixes: \#8341)
Manually tested.
> [Gluten-8341][CH] Fix code style and respect max_read_buffer_size for bzip2 read buffer

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CommonSubexpressionEliminateRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
> [GLUTEN-8354][CH] Fix cse issue in aggregate[Part2]

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
- gluten-substrait/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Following #8355
1. Fix "shuffle handle not found" when GlutenShuffleManager is set
2. Fix utility method `isUseGlutenShuffleManager`
> [VL] Add some fixes following #8355

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/Parser/ExpressionParser.h
> [GLUTEN-8283][CH] Eliminate CSE via `ExpressionParser`

- ep/build-velox/src/get_velox.sh
```
06051013c by Ke, feat: Add TextWriter (#11789)
edd8a0b2a by Orri Erling, feat: [velox][PR] Add Duck plan transformation for qualified joins and subqueries (#11930)
bfe085db7 by Jialiang Tan, fix: Fix flaky HashJoinTest.reclaimDuringOutputProcessing (#11993)
bef55f58a by Xiaoxuan Meng, fix: Fix writer reclaim failure by clearing dict chained buffers during arbitration (#11988)
e1c175bdb by Xiaoxuan Meng, fix: Fix flaky scaled scan fuzzer test (#11989)
dcccd90cc by Jimmy Lu, fix: Allow BitSet size to be larger than int32 (#11986)
c44e45b5b by Xiaoxuan Meng, feat: Support per-split fine-grained cache control (#11984)
7fdb3219e by duanmeng, feat: Add query trace TaskRunner (#11927)
7cbfce057 by rui-mo, fix(parquet): Support converted type in timestamp reader …
```
> [GLUTEN-6887][VL] Daily Update Velox Version (2025_01_02)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionArrayToString.cpp
- cpp-ch/local-engine/Functions/SparkFunctionArrayToString.h
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
> [GLUTEN-7602][CH] Add spark cast array to string

- cpp-ch/local-engine/Functions/SparkFunctionDecimalBinaryOperator.h
Fixes: \#8408  compile issue on ARM
Tested by compile on ARM machine.
> [GLUTEN-8408][CH] Fix compile failures on ARM

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitParser.cc
https://github.com/facebookincubator/velox/pull/11953.
Fix #8319.
Existing Spark test and one new test added.
> [GLUTEN-8319][VL] Support date_format Spark function

- .github/workflows/docker_image.yml
- dev/docker/Dockerfile.centos8-dynamic-build-jdk11
This patch added JDK11 based Centos 8 image
> [GLUTEN-8487][VL] adding JDK11 based Centos8 image

- ep/build-velox/src/get_velox.sh
> [1.3][VL]update oap velox to gluten-1.3.0

- cpp/core/benchmarks/CompressionBenchmark.cc
Detect and handle input/output errors
(Fixes: \#8524)
> [GLUTEN-8524][VL] Fix input output errors

- docs/get-started/Velox.md
- docs/get-started/build-guide.md
update spark version support doc 
> [1.3][DOC] update spark 3.5.2 in doc (#8543)

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/RuntimeSettings.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarWriteFilesExec.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseExcelFormatSuite.scala
- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.h
- cpp-ch/local-engine/Storages/Output/OutputFormatFile.h
- cpp-ch/local-engine/Storages/Output/ParquetOutputFormatFile.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250116)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseExcelFormatSuite.scala
> [CORE][MIRROR] Change config.defaultValue.get.toString to config.defaultValueString

- dev/docker/Dockerfile.centos8-dynamic-build
Update docker image to pre-install uniffle package. 
A new patch is required in gluten to make use of the new image
> [GLUTEN-8266][VL][CI] Pre-install uniffle in docker image

- backends-velox/src/main/java/org/apache/gluten/columnarbatch/VeloxColumnarBatches.java
- Removing unused code in VeloxColumnarBatch.
- checkNonVeloxBatch is not called anywhere, removing the same
Unit Tests
> [GLUTEN-8565][VL] Remove unused code in velox batches

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseExcelFormatSuite.scala
- cpp-ch/clickhouse.version
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250124)

- .github/workflows/docker_image.yml
rename docker image for 1.3 branch
> [1.3][VL] Rename docker image name for 1.3 branch

- .github/workflows/velox_backend.yml
- dev/docker/Dockerfile.centos8-dynamic-build
- docs/get-started/Velox.md
- pom.xml
- tools/gluten-it/pom.xml
Bump Uniffle from 0.9.1 to 0.9.2
Fixes: #8631.
GA.
> [GLUTEN-8631][UNIFFLE] Bump Uniffle to 0.9.2

- .github/workflows/velox_backend.yml
adding Spark-344 unit tests on JDK8 and adding Spark-352 unit tests on JDK17
also removed the spark-344 source download step as we already installed in the docker image
pass GHA
> [GLUTEN-8574][VL]CI: adding Spark-344 unit tests on JDK8 and adding Spark-352 unit tests on JDK17

- .github/workflows/velox_backend.yml
> [VL] Bump GHA upload/restore action

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
Enable make_date function.
UT.
> [VL] Enable make_date function

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Operator/StreamingAggregatingStep.cpp
- cpp-ch/local-engine/Parser/LocalExecutor.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeWriter.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250208)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
> [GLUTEN-8598][CH] Fix diff for cast string to long

- cpp-ch/local-engine/tests/benchmark_spark_floor_function.cpp
- cpp-ch/local-engine/tests/benchmark_sum.cpp
> [GLUEN-8696][CH] Fix arm building of benchmark

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/RelParsers/JoinRelParser.cpp
- cpp-ch/local-engine/Storages/Kafka/GlutenKafkaSource.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeMeta.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.h
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250213)

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250215)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/slice.cpp
Fix slice unexpected exception
(Fixes: \#8723)
newly added ut.
> [GLUTEN-8723][CH] Fix slice unexpected exception

- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/config/VeloxConfig.h
Add config for enable/disable window spill.
N/A
> [VL] Add config for whether to enable spill on Window

- cpp-ch/local-engine/tests/gtest_hllpp.cpp
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseSQLQueryTestSettings.scala
> [GLUTEN-8769][CH] Fix failed uts introduced by approx_count_distinct

- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/CHNativeExpressionEvaluator.java
- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/ExpressionEvaluatorJniWrapper.java
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/NativeFileScanColumnarRDD.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/metrics/GlutenClickHouseMetricsUTUtils.scala
- cpp-ch/local-engine/Functions/SparkFunctionMonotonicallyIncreasingID.cpp
- cpp-ch/local-engine/Parser/ParserContext.cpp
- cpp-ch/local-engine/Parser/ParserContext.h
- cpp-ch/local-engine/Parser/scalar_function_parser/monotonicallyIncreasingId.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
(Fixes: \#8748)
Test by ut
* GlutenColumnExpressionSuite.`monotonically_increasing_id`
* DeprecatedAPISuite.`functions.monotonicallyIncreasingId`
* DataFrameAggregateSuite.`SPARK-19471: AggregationIterator ...`
* DataFrameSuite.`copy results for sampling with replacement`
ignore ut
* GlutenDataFrameFunctionsSuite.`SPARK-14393: values ...`
because other function errors
> [GLUTEN-8748][CH] Support function monotonically_increasing_id

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxMetricsApi.scala
- backends-velox/src/main/scala/org/apache/gluten/metrics/WindowMetricsUpdater.scala
Since Velox SortWindow already supports spill, we need to add the spill metrics for window.
N/A
> [VL] Add window spill metrics

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHMetricsApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/vectorized/CHColumnarBatchSerializer.scala
Add a metric for shuffle read deserializer.
(Fixes: \#GLUTEN-8699)
Test manually by checking UI
> [GLUTEN-8699][CH]Metric for Shuffle Read Deserializer

- cpp-ch/local-engine/Functions/FunctionsBloomFilter.h
> [GLUTEN-8434][CH] Function bloomFilterContains process improvement

- cpp-ch/local-engine/Functions/SparkFunctionNextDay.cpp
(Fixes: \#8788)
Old uts introduced in https://github.com/apache/incubator-gluten/pull/2305/files
> [GLUTEN-8788][CH] Avoid unnecesssary const column materialization

- cpp-ch/CMakeLists.txt
> [CH][CI] Parallel download clickhouse submodule

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullNativeParquetSuite.scala
- cpp-ch/clickhouse.version
test new native parquet reader
> [CH] add test for new native parquet reader

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenCoalesceAggregationUnionSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenCTEInlineSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameSetOperationsSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenCTEInlineSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDataFrameSetOperationsSuite.scala
> [GLUTEN-8784][CH] Coalesce union of multiple scan-projects

- .github/workflows/util/license-header.py
- .github/workflows/util/util.py
- dev/build-thirdparty.sh
- dev/build_arrow.sh
- dev/build_helper_functions.sh
- dev/build_libhdfs3.sh
- dev/buildbundle-veloxbe.sh
- dev/builddeps-veloxbe.sh
- dev/ci-velox-buildshared-centos-8.sh
- dev/ci-velox-buildstatic-centos-7.sh
- dev/docker/Dockerfile
- dev/docker/Dockerfile.centos7-static-build
- dev/docker/Dockerfile.centos8-dynamic-build
- dev/docker/Dockerfile.centos8-dynamic-build-jdk11
- dev/docker/Dockerfile.centos8-dynamic-build-jdk17
- dev/docker/Makefile
- dev/docker/entrypoint.sh
- dev/formatcppcode.sh
- dev/package-vcpkg.sh
- dev/package.sh
- dev/setup-qat-ubuntu.sh
- dev/vcpkg/setup-build-depends.sh
- dev/vcpkg/toolchain.cmake
Add missing license header for better ASF Policy compliance
> [INFRA] Add missing license header for better ASF Policy compliance

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/RelParsers/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/WriteRelParser.cpp
- cpp-ch/local-engine/Storages/Kafka/GlutenKafkaSource.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeSink.cpp
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.cpp
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.h
- cpp-ch/local-engine/Storages/Parquet/ColumnIndexFilter.cpp
- cpp-ch/local-engine/Storages/Parquet/ParquetConverter.h
- cpp-ch/local-engine/Storages/Serializations/ExcelStringReader.cpp
- cpp-ch/local-engine/tests/gtest_parquet_columnindex.cpp
- cpp-ch/local-engine/tests/gtest_write_pipeline.cpp
- cpp-ch/local-engine/tests/utils/ReaderTestBase.cpp
- cpp-ch/local-engine/tests/utils/gluten_test_util.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250301)

- cpp-ch/local-engine/Functions/SparkFunctionArraySort.cpp
array_sort was used in our production frequently. Let's optimize it. Inspired by https://github.com/ClickHouse/ClickHouse/pull/76850
old uts
> [CH] optimize performance of sparkArraySort

- docs/get-started/Velox.md
The relative parent changes from `current dir / docs` to `..`
> [VL] Fix broken links for velox-backend-build-in-docker.md

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250304)

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
> [VL] Enable spark function map_filter

- cpp/core/jni/JniCommon.h
> [GLUTEN-8894][VL] Fix buffer overflow in jStringToCString on arm

- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
(Fixes: \#8909)
manual tests in my dev box
> [GLUTEN-8909][VL] Allow dynamic configuration for spark.gluten.auto.adjustStageResource.enabled

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxStringFunctionsSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
> [GLUTEN-8903][Function] Support btrim function

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250307)

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/RelParsers/GroupLimitRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/SortRelParser.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250308)

- .github/workflows/util/install_spark_resources.sh
> [CI] fix spark352-scala2.13 test home

- cpp-ch/local-engine/Builder/SerializedPlanBuilder.cpp
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/Parser/FunctionExecutor.cpp
- cpp-ch/local-engine/Parser/RelParsers/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/ExpandRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/GroupLimitRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/JoinRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/SortParsingUtils.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Parser/SubstraitParserUtils.cpp
- cpp-ch/local-engine/Parser/SubstraitParserUtils.h
> [CH] Simplify parsing substrait struct fields.

- backends-velox/src-delta/main/scala/org/apache/gluten/component/VeloxDeltaComponent.scala
- gluten-delta/src-delta/main/scala/org/apache/gluten/execution/OffloadDeltaFilter.scala
- gluten-delta/src-delta/main/scala/org/apache/gluten/execution/OffloadDeltaProject.scala
- gluten-delta/src-delta/main/scala/org/apache/gluten/extension/DeltaPostTransformRules.scala
- gluten-delta/src-delta/test/scala/org/apache/gluten/execution/DeltaSuite.scala
This PR aims to add offload rules for DeltaProjectExecTransformer and DeltaFilterExecTransformer to validate expression in Delta before execution phase.
(Fixes: \#8958)
Add new unit tests
> [GLUTEN-8958][VL] Add offload rules for DeltaProjectExecTransformer and DeltaFilterExecTransformer

- ep/build-velox/src/setup-centos7.sh
- ep/build-velox/src/setup-centos8.sh
> [VL] Update centos setup scripts to install new tzdata

- .github/workflows/velox_backend.yml
- dev/docker/Dockerfile.centos8-dynamic-build
- dev/docker/Dockerfile.centos8-dynamic-build-jdk11
- dev/docker/Dockerfile.centos8-dynamic-build-jdk17
- pom.xml
- tools/gluten-it/pom.xml
- bump celeborn version to 0.5.4
- Remove used of celeborn celeborn-0.3.2-incubating
GA
> [GLUTEN-8993][CELEBORN] Bump Celeborn version to 0.5.4

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionCastFloatToString.cpp
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/getTimestamp.h
> [GLUTEN-3289][CH]Fix cast float to string

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionStrToMap.cpp
> [GLUTEN-8997][CH] Support regular expression delimiters for `str_to_map`

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
This PR aims to support array_append function for Spark 3.4 and 3.5.
(Fixes: \#9015)
unit tests
> [GLUTEN-9015][VL] Support array_append function

- .github/workflows/velox_backend.yml
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Check artifact files found for build native lib job
Fixes: #9027
> [GLUTEN-9027][VL] Make CI fail fast if native build job fails

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/AggregateFunctions/GroupLimitFunctions.cpp
- cpp-ch/local-engine/Parser/RelParsers/GroupLimitRelParser.cpp
> [GLUTEN-8995][CH] Fix column not found in `row_number` query

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250318)

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/Parser/ExpressionParser.h
> [GLUTEN-9032][CH] `cast` for values built from nothing type

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/EqualityDeleteFileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/EqualityDeleteFileReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/PositionalDeleteFileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/PositionalDeleteFileReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/SimpleParquetReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/SimpleParquetReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/substrait_fwd.h
- cpp-ch/local-engine/tests/gtest_iceberge_test.cpp
> [GLUTEN-9050][CH] Remove duplicated uri decode which causes runtime exceptions

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenHDFSObjectStorage.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/timestampAdd.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/unixTimestamp.cpp
- cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/examples/splittable_bzip2_read_buffer.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250319)

- backends-velox/src/main/scala/org/apache/gluten/expression/ExpressionTransformer.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
Support GetStructField with scalar function as input
(Fixes: \#8306)
UT
> [GLUTEN-8306][VL] Support GetStructField with scalar function as input

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250320)

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
> [VL] Minor refactor for cast expression validation 

- gluten-substrait/src/main/scala/org/apache/gluten/execution/ColumnarCollectLimitBaseExec.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- Follow up to #8566.
- Removes minor duplication for fallback by backend settings.
- Allows user configurable support for CollectLimit operator.
> [GLUTEN-8565][VL] Minor refactor for Columnar CollectLimit

- gluten-core/src/test/scala/org/apache/spark/shuffle/GlutenShuffleManagerSuite.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuite.scala
- gluten-substrait/src/test/scala/org/apache/spark/softaffinity/SoftAffinitySuite.scala
- gluten-substrait/src/test/scala/org/apache/spark/softaffinity/SoftAffinityWithRDDInfoSuite.scala
- gluten-substrait/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
Avoid port conflicts and improve test performance
locally ran the related tests and checked logs
> [TESTS] Disable Spark UI in some tests

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergetreeWriteStatsSuite.scala
- cpp-ch/local-engine/Common/GlutenConfig.cpp
- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.h
> [GLUTEN-9085][CH] Add UT for mergetree write stats

- cpp/velox/shuffle/VeloxHashShuffleWriter.cc
Erase duplicate eviction counts.
> [VL] Fix reclaim size for shuffle

- cpp-ch/local-engine/Common/CHUtil.cpp
> [GLUTEN-9164][CH]Enable row group level bloom filter push down

- backends-clickhouse/src-delta-32/main/scala/org/apache/gluten/extension/DeltaExpressionExtensionTransformer.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/gluten/sql/shims/delta32/Delta32Shims.scala
- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaParquetDeletionVectorSuite.scala
- backends-clickhouse/src-delta/main/scala/org/apache/gluten/component/CHDeltaComponent.scala
- backends-clickhouse/src-delta/main/scala/org/apache/gluten/sql/shims/DeltaShims.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHExpressions.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/ExpressionExtensionTrait.scala
- cpp-ch/local-engine/AggregateFunctions/AggregateFunctionDVRoaringBitmap.cpp
- cpp-ch/local-engine/AggregateFunctions/AggregateFunctionDVRoaringBitmap.h
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/Bitmap/DeltaDVRoaringBitmapArray.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/Bitmap/DeltaDVRoaringBitmapArray.h
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Iceberg/PositionalDeleteFileReader.cpp
- cpp-ch/local-engine/tests/gtest_clickhouse_roaring_bitmap.cpp
Update as blow:
support bitmapaggregator
support multiple expression expansions at the same time
DeltaDVRoaringBitmapArray initialization no longer requires query context
(Fixes: \#9020)
test by ut
> [GLUTEN-9020][CH] Support delta DV BitmapAggregator

- .github/workflows/velox_backend.yml
> [VL][CI] Optimize celeborn ci

- .github/workflows/take.yml
auto assign issue on 'take' comment
> [CI] auto assign issue based on comments

- cpp-ch/local-engine/Common/CHUtil.cpp
> Revert "[GLUTEN-9164][CH]Enable row group level bloom filter push down"

- .github/workflows/build_bundle_package.yml
- .github/workflows/velox_backend.yml
- .github/workflows/velox_backend_cache.yml
- .github/workflows/velox_nightly.yml
ubuntu-20.04 is retiring
https://github.com/actions/runner-images/issues/11101
pass GHA
> [VL][CI] bump to use ubuntu-22.04 runner

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/AggregateUtil.cpp
- cpp-ch/local-engine/Parser/RelParsers/AggregateRelParser.cpp
- cpp-ch/local-engine/Storages/Parquet/ColumnIndexFilter.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250416)

- backends-clickhouse/src/test/scala/org/apache/gluten/utils/MinioTestHelper.scala
Fix build error with scala 2.12.
> [CH] Fix build error

- backends-velox/src/test/scala/org/apache/gluten/execution/ArrowCsvScanSuite.scala
> [GLUTEN-9379] [VL] Disable flaky ArrowCsvScanSuiteV2

- backends-clickhouse/src-delta-23/main/scala/org/apache/spark/sql/delta/rules/CHOptimizeMetadataOnlyDeltaQuery.scala
- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/CHNativeBlock.java
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHColumnarCollectLimitExec.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/BasicExpressionRewriteRule.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CommonSubexpressionEliminateRule.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/ExtendedColumnPruning.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RewriteDateTimestampComparisonRule.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RewriteToDateExpresstionRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseCollectLimitExecSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarCollectLimitExec.scala
- cpp-ch/local-engine/local_engine_jni.cpp
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ColumnarCollectLimitBaseExec.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
Support CollectLimit operator for CH backend based https://github.com/apache/incubator-gluten/pull/8914 
(Fixes: \#9137)
> [GLUTEN-9137][CH] Support CollectLimit for CH backend

- backends-velox/src/main/scala/org/apache/gluten/execution/VeloxColumnarToRowExec.scala
When `output.isEmpty` is true, metrics such as `numInputBatches` and `numOutputRows` are recorded repeatedly.
> [VL] Fix VeloxColumnarToRowExec repeatedly recorded some metrics

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- Support array cast to varchar. 
- More cast types support will be added in the upcoming PRs.
- Unit tests added
- Spark existing unit tests
> [GLUTEN-9392] [VL] Support casting array element to varchar

- .github/workflows/build_bundle_package.yml
- .github/workflows/velox_backend.yml
- .github/workflows/velox_backend_cache.yml
- .github/workflows/velox_nightly.yml
- cpp/core/shuffle/LocalPartitionWriter.cc
- docs/developers/HowTo.md
- docs/developers/NewToGluten.md
- docs/get-started/Velox.md
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
Porting PR #9200 #9320 #9368 #9209 #9262
Done in local.
> [branch-1.4] Port PR #9200 #9320 #9368 #9209 #9262

- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkSessionSwitcher.scala
testDefaults contains user specified conf
> Minor: The user specified --extra-conf has high priority

- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/BaseMixin.java
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Constants.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/DataGen.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Suite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/clickbench/ClickBenchSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/ds/TpcdsSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/h/TpchSuite.scala
Cudf does not supports decimal type because cudf table decimal lost the `precision` information, so convert to double to test.
> [VL] Support decimal as double in gluten-it

- gluten-flink/README.md
- gluten-flink/docs/Flink.md
- gluten-flink/docs/Gluten-Flink-troubleshooting.md
- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecCalc.java
- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWatermarkAssigner.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/FunctionMappings.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/RexNodeConverter.java
- gluten-flink/runtime/src/main/java/org/apache/flink/client/StreamGraphTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/flink/streaming/runtime/translators/LegacySourceTransformationTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SourceTransformationTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/streaming/api/operators/GlutenStreamSource.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenSingleInputOperator.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenSourceFunction.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/util/LogicalTypeConverter.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/util/PlanNodeIdGenerator.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/FlinkRowToVLVectorConvertor.java
This pr fix the memory leak of gluten flink POC, it can run Nexmark q0 stably. 
(Fixes: \#9445)
Referred Velox4J version: https://github.com/bigo-sg/velox4j/commits/3275df667458a494a7ba5be93907779d1b013979
https://github.com/bigo-sg/velox4j.git
This patch was tested by manual tests.
> [GLUTEN-9445][VL] Support nexmark q0 for Flink

- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/common/CommonExecSink.java
- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecCalc.java
- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWatermarkAssigner.java
- gluten-flink/runtime/src/main/java/org/apache/flink/client/StreamGraphTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/flink/runtime/taskexecutor/TaskManagerRunner.java
- gluten-flink/runtime/src/main/java/org/apache/flink/streaming/runtime/translators/LegacySourceTransformationTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SinkTransformationTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/flink/streaming/runtime/translators/SourceTransformationTranslator.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/util/PlanNodeIdGenerator.java
Refine some comments.
(Fixes: \#9538)
This pr only change comments.
> [GLUTEN-9538][Flink] Refine comments for gluten related code changes in Flink classes

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/CollectTailTransformerRule.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- Supports config driven fallbacks for CollectTail, added to user fallback options.
- Also updated the collecttail rule to rely on it instead which was previously on an incorrect config.
- Existing UTs
> [VL] Support user fallback option for CollectTail

- gluten-flink/loader/pom.xml
- gluten-flink/planner/pom.xml
- gluten-flink/pom.xml
- gluten-flink/runtime/pom.xml
- gluten-flink/ut/pom.xml
- gluten-flink/ut/src/test/java/org/apache/flink/table/runtime/stream/common/GlutenStreamingTestBase.java
- gluten-flink/ut/src/test/java/org/apache/flink/table/runtime/stream/common/Velox4jEnvironment.java
- gluten-flink/ut/src/test/java/org/apache/flink/table/runtime/stream/custom/ScanTest.java
> [GLUTEN-9448][Flink] Support UTs for flink

- backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala
Refactor RowToVeloxColumnarExec to remove some duplicate code
> [VL] Refactor RowToVeloxColumnarExec to remove some duplicate code

- gluten-substrait/src/main/scala/org/apache/gluten/execution/BatchScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
> [CORE] Support batch scan customMetrics

- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/common/GlutenStreamingTestBase.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/common/Velox4jEnvironment.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScanTest.java
> [GLUTEN-9448][Flink] Hot fix UT package path

- gluten-flink/docs/Flink.md
- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenSingleInputOperator.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenSourceFunction.java
~~This is an example work to rebase `bigo/velox4j` on to the latest `velox4j/velox4j` code.~~
~~Relying on this rebased Velox4J branch: https://github.com/zhztheplayer/velox4j/commits/wip-bigo-rebase-0507.~~
Bump Velox4J to commit [c069ca63aa3a200b49199f7dfa285f011ce6fda5](https://github.com/bigo-sg/velox4j/commits/c069ca63aa3a200b49199f7dfa285f011ce6fda5)
> [FLINK] Bump Velox4J version

- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxRuntime.cc
Before that, after the execution finished, call printplanWithStats, but if the execution failed, we can not get the plan.
> [VL] Minor: Print Velox plan before execution

- dev/formatcppcode.sh
Support format cpp code on macOS
Manually tested on macOS
> [VL] Support format cpp code on macOS

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenCoalesceAggregationUnionSuite.scala
> [GLUTEN-9581][CH] Fix: in subquery expression cannot exist in project

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
This PR aims to add validation msg for negative round scale.
(Fixes: \#9542)
Manual tests:
> [GLUTEN-9542][VL] Add validation msg for negative round scale

- ep/build-velox/src/get_velox.sh
https://github.com/oap-project/velox/commits/gluten-1.4.0-v1
> [Branch-1.4][VL] Update Velox branch to make Velox compatible with old tzdata

- gluten-flink/docs/Flink.md
- gluten-flink/planner/src/main/java/org/apache/flink/table/planner/plan/nodes/exec/stream/StreamExecWatermarkAssigner.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/FunctionMappings.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/RexNodeConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/DefaultFunctionConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/FunctionConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/SubtractFunctionConverter.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/util/LogicalTypeConverter.java
This pr support WatermarkAssginer. 
(Fixes: \#9518)
This patch was tested by manual tests.
> [GLUTEN-9518][FLINK] Support watermark assigner

- .github/workflows/docker_image.yml
fix the docker image name for 1.4 release
> [Branch-1.4][VL] update docker image name for branch-1.4

- gluten-core/pom.xml
> [TYPO] Fix arg used for java version in build info

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/JoinAggregateToAggregateUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenEliminateJoinSuite.scala
> [GLUTEN-9594][CH] Reorder join/aggregate keys, ensure keys of all clauses are in the same order

- .github/workflows/velox_backend.yml
- dev/vcpkg/ports/libelf/portfile.cmake
Just ported some critical fixes to branch 1.4.
> [Branch-1.4][VL] Port fix: Fix build failure due to libelf vcpkg unavailable files (#9550)

- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenSingleInputOperator.java
> [GLUTEN-9623][FLINK] Fix blocking queue not close may cause memory leak

- gluten-core/src/main/scala/org/apache/gluten/iterator/IteratorsV1.scala
- gluten-core/src/test/scala/org/apache/spark/iterator/IteratorBenchmark.scala
Improve performance of PayloadCloser Iterator.
Fixes: #9611
new benchmark case.
before this change:
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_431-b10 on Mac OS X 15.3.1
Apple M4
Multi Threads - recycle:                  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------------------------------
Scala Iterator                                      138            143          10        361.5           2.8       1.0X
Gluten Iterator V1                                10005          10006           0          5.0         200.1       0.0X
```
after this change:
```
Java HotSpot(TM) 64-Bit Server VM 1.8.0_431-b10 on Mac OS X 15.3.1
Apple M4
Multi Threads - recycle: …
```
> [GLUTEN-9611][CORE] Improve performance of PayloadCloser Iterator

- .github/workflows/ch_code_style.yml
> [INFRA] Add path filter to CH backend code style checks workflow

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCHCacheDataCommand.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
> [GLUTEN-9628][CH] Fix cache data on partition table with escaped value

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenCoalesceAggregationUnionSuite.scala
> [GLUTEN-9646][CH] Fix coalesce project union when has subquery

- cpp/velox/memory/VeloxMemoryManager.cc
Backport #9424 #9461 to 1.4 branch
CI
> [Branch-1.4][GLUTEN-9383][VL] Backport: fix leak when growing capacity

- .github/workflows/docker_image.yml
Follow-up for #9644.
Will trigger the workflow to verify when merged.
> [INFRA][VL] Fix wrong Dockerfile

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxStringFunctionsSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
With https://github.com/facebookincubator/velox/commit/5a359e9d0f869bb351031e5a66b57ad862d9c821, we could enable luhn_check function.
(Fixes: \#9361)
unit test.
> [GLUTEN-9361][VL] Enable luhn_check function for spark 3.5

- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/FlinkRowToVLVectorConvertor.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/common/GlutenStreamingTestBase.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScanTest.java
> [GLUTEN-9653][Flink] Support  `boolean` in `vector-to-row` conversion

- cpp-ch/local-engine/Functions/SparkFunctionStrToMap.cpp
> [GLUTEN-9679][CH] Fix: invalid address access in str_to_map

- gluten-flink/runtime/src/main/java/org/apache/gluten/streaming/api/operators/GlutenOneInputOperatorFactory.java
Implement createStreamOperator and getStreamOperatorClass for GlutenOneInputOperatorFactor
Fixes: #9573
manual tests
> [GLUTEN-9573][Flink] Implement `createStreamOperator` and `getStreamOperatorClass` for `GlutenOneInputOperatorFactor`

- backends-clickhouse/src-kafka/main/scala/org/apache/gluten/component/CHKafkaComponent.scala
- backends-clickhouse/src-kafka/test/scala/org/apache/gluten/execution/kafka/ClickhouseGlutenKafkaScanSuite.scala
- cpp-ch/local-engine/Storages/Kafka/GlutenKafkaSource.cpp
- cpp-ch/local-engine/Storages/Kafka/GlutenKafkaSource.h
> [GLUTEN-9681][CH] Fix the number of rows read by kafka is incorrect

- backends-velox/src/main/scala/org/apache/spark/sql/execution/BroadcastUtils.scala
> [GLUTEN-9475][VL][FOLLOWUP] Avoid overflow in calculation of numRows

- tools/workload/tpcds/run_tpcds/tpcds_parquet.scala
- tools/workload/tpch/run_tpch/tpch_parquet.scala
Remove try block, and df.show() may be the operator TOPN, not orderby, so changed to collectAsList()
> Fix the TPCH/DS script cannot throw exception

- gluten-substrait/src/main/scala/org/apache/gluten/execution/BroadcastNestedLoopJoinExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/JoinExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/JoinUtils.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/SortMergeJoinExecTransformer.scala
follow up #7844, minor code clean.
> [CORE] Remove createTransformContext function

- cpp/core/jni/JniWrapper.cc
- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/LocalPartitionWriter.h
- cpp/core/shuffle/Options.h
- cpp/core/shuffle/PartitionWriter.h
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Payload.h
- cpp/core/shuffle/Spill.cc
- cpp/core/shuffle/Utils.cc
- cpp/core/shuffle/Utils.h
- cpp/core/shuffle/rss/RssPartitionWriter.cc
- cpp/core/shuffle/rss/RssPartitionWriter.h
- cpp/velox/benchmarks/GenericBenchmark.cc
- cpp/velox/shuffle/VeloxHashShuffleWriter.cc
- cpp/velox/shuffle/VeloxHashShuffleWriter.h
- cpp/velox/shuffle/VeloxRssSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleReader.cc
- cpp/velox/shuffle/VeloxShuffleReader.h
- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/tests/VeloxShuffleWriterSpillTest.cc
- cpp/velox/tests/VeloxShuffleWriterTest.cc
- cpp/velox/tests/VeloxShuffleWriterTestBase.h
Code cleanup and refactoring to prepare for adding the dictionary feature. Mostly extracted from https://github.com/apache/incubator-gluten/pull/9426
> [GLUTEN-8855][VL] Columnar shuffle code cleanup

- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/ArrowVectorWriter.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/FlinkRowToVLVectorConvertor.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScanTest.java
Fixes: #9700
Also close #9702
It can support nested types now.
unit tests
> [GLUETN-9700][Flink] Refactor convertion of row to vector

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/JoinAggregateToAggregateUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenCoalesceAggregationUnionSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenEliminateJoinSuite.scala
Fix: Inconsistent result from `JoinAggregateToAggregateUnion`
Fixes: #9728 
unit tests
> [GLUTEN-9728][CH] Fix: Inconsistent result from `JoinAggregateToAggregateUnion`

- backends-velox/src/test/scala/org/apache/gluten/functions/MathFunctionsValidateSuite.scala
- ep/build-velox/src/get_velox.sh
https://github.com/facebookincubator/velox/commit/984d561b6307f412766a87f58e3576a9df02c0ad
> [VL] Add sqrt support

- dev/build_helper_functions.sh
> [GLUTEN-9764][VL] Use auto re2 source for openEuler24

- backends-clickhouse/src-delta-33/test/scala/org/apache/spark/gluten/delta/GlutenDeltaMergeTreeDeletionVectorSuite.scala
> [CH] Support deletion vector optimize for mergetree(add ut)

- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/RexNodeConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/TypeUtils.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/Utils.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/BaseRexCallConverters.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/BasicCompareOperatorConverters.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/ModRexCallConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/RexCallConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/RexCallConverterFactory.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScalarFunctionsTest.java
> [GLUTEN-9790][Flink] Support resolving different converters for Rex calls that share the same operator name

- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/ArrowVectorAccessor.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/ArrowVectorWriter.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScanTest.java
> [GLUTEN-9755][FLINK] Support null

- dev/builddeps-veloxbe.sh
Set INSTALL_PREFIX to /usr/local, align with VELOX:
https://github.com/facebookincubator/velox/blob/771e29b2d002a0a08abe2a1a1b10194d72565d2e/scripts/setup-ubuntu.sh#L35
https://github.com/facebookincubator/velox/blob/771e29b2d002a0a08abe2a1a1b10194d72565d2e/scripts/setup-centos9.sh#L38
> [VL] quick fix, INSTALL_PREFIX align with velox

- .github/workflows/velox_backend.yml
> [GLUTEN-9873][VL] Fix install pandas

- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/RexNodeConverter.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/util/LogicalTypeConverter.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScalarFunctionsTest.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScanTest.java
> [GLUIEN-9840][Flink] Support type `CHAR(N)`

- .github/workflows/nightly_sync.yml
- .github/workflows/velox_nightly.yml
- README.md
- docs/release.md
Upload nightly release jars to
https://nightlies.apache.org/gluten/
pass GHA
> [GLUTEN-9860][VL] Upload nightly releases to apache nightly site

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHTransformerApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoader.scala
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/spark/sql/internal/SparkConfigUtil.scala
- gluten-core/src/test/scala/org/apache/gluten/config/SparkConfigUtilSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/UDFMappings.scala
> Add a RichSparkConf to simplify interoperations gluten config entries

- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/LocalPartitionWriter.h
- cpp/core/shuffle/Spill.h
Some code refactoring to make the LocalPartitionWriter extendable.
> [VL] Refine LocalPartitionWriter implementation

- .github/workflows/velox_nightly.yml
enable data lake connectors in nightly package
pass GHA
> [GLUTEN-9860][VL] enable iceberg/hudi/delta in nightly release

- dev/vcpkg/setup-build-depends.sh
- tools/gluten-te/centos/centos-7-deps.sh
Follow up #9760, fix conflict with `set -e` and `$?`.
> [VL] Fix wget automake and gcc

- .github/workflows/velox_backend_cache.yml
- .github/workflows/velox_backend_x86.yml
- backends-velox/src/main/java/org/apache/gluten/config/ConfigJniWrapper.java
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- cpp/CMakeLists.txt
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/jni/VeloxJniWrapper.cc
- dev/builddeps-veloxbe.sh
- ep/build-velox/src/get_velox.sh
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
Use the temporary branch now, replace the branch when the enhanced branch is ready
> [GLUTEN-9949][VL] Enable enhanced features compile

- cpp/velox/compute/VeloxPlanConverter.cc
- cpp/velox/compute/VeloxPlanConverter.h
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.h
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
- cpp/velox/tests/FunctionTest.cc
- cpp/velox/tests/Substrait2VeloxPlanConversionTest.cc
- cpp/velox/tests/Substrait2VeloxValuesNodeConversionTest.cc
- cpp/velox/tests/VeloxSubstraitRoundTripTest.cc
Use velox conf class in plan converter and plan validator, it has more convenience method than std map.
> [VL] Use Velox config in plan converter

- gluten-core/src/main/java/org/apache/gluten/utils/ResourceUtil.java
1. Re-throw exceptions as `GlutenException` uniformly
2. Null-checking for `directory.listFiles()`
3. Fix lack of generic type of `Enumeration`
> [CORE] Some nit changes for ResourceUtil.scala

- .github/workflows/util/setup_helper.sh
- dev/docker/Dockerfile.centos8-dynamic-build
- dev/docker/Dockerfile.centos8-static-build
- dev/vcpkg/setup-build-depends.sh
> [VL] quick fix, maven3.8.8 download is 404

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/DebugUtils.cpp
- cpp-ch/local-engine/Disks/registerGlutenDisks.cpp
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
- cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.h
- cpp-ch/local-engine/Parser/RelParsers/CrossRelParser.cpp
- cpp-ch/local-engine/Storages/Parquet/VectorizedParquetRecordReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/FileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FileReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/Iceberg/IcebergReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ORCFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
- cpp-ch/local-engine/tests/gtest_parquet_read.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250629)

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/offload/OffloadSingleNodeRules.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/python/EvalPythonExecTransformer.scala
There may be some potential issue if it doesn't match declared package.
CI.
> [CORE] Fix a class's placement to match its declared package

- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/ArrowVectorAccessor.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/vectorized/ArrowVectorWriter.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScanTest.java
> [GLUTEN-10050][FLINK] Support decimal type

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenAutoAdjustStageResourceProfile.scala
See discussion: https://github.com/apache/incubator-gluten/issues/10099#issuecomment-3034219121
> [CORE] Reflect resource changes in configurations when applying new resource profile

- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/NexmarkTest.java
> [GLUTEN-10091][FLINK] Fix premature termination in NexmarkTest

- gluten-flink/docs/Flink.md
Add flink related velox4j build problem
> [DOC][Flink] Update flink build command to skip gpg and spotless check

- .github/workflows/velox_nightly.yml
This patch adds nightly jars for ARM64
pass GHA
> [GLUTEN-9860][VL] Add nightly packages for ARM

- docs/get-started/Velox.md
use a general table name in readme
> [VL] update readme, use general table name

- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/DecimalRexCallConverters.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/RexCallConverterFactory.java
- gluten-flink/ut/src/test/java/org/apache/gluten/table/runtime/stream/custom/ScalarFunctionsTest.java
> [GLUTEN-10226][Flink] Support decimal arithmetic

- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SubstraitBackend.scala
This PR proposes to remove unused code from `SubstraitBackend`.
(Fixes: \#10272)
unit tests and integration tests
> [MINOR] Remove unused code from SubstraitBackend

- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
https://github.com/facebookincubator/velox/commit/a10b8d5c9a1fa76c7bd299ee70bcd87fe0958be9 has been merged in Velox.  This PR enables the relevant abs test.
UT verified.
> [GLUTEN-10175][VL] Enable abs test

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/Parser/scalar_function_parser/mapConcat.cpp
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [CH] Support map_concat function

- docs/velox-parquet-write-configuration.md
follow up https://github.com/apache/incubator-gluten/pull/10259
> [DOC][VL] adding back Velox parquet write configuration doc

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/functions/DateFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/DateTimeExpressionsTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
https://github.com/facebookincubator/velox/pull/13535
(Fixes: \#9809)
UT
> [GLUTEN-9809][VL] Add timestampdiff support

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/package.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCostEvaluator.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkPlanUtil.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkTaskUtil.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkVersionUtil.scala
This PR proposes to share the results compare the spark version.
(Fixes: \#10334)
> [GLUTEN-10334] Share the results compare the spark version

- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Queries.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/QueriesCompare.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/QueriesMixin.java
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Queries.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/QueriesCompare.scala
Print error details in mode `--queries` and `--queries-compare`.
Specify `--suppress-failure-messages` to suppress the errors.
Example:
```
There are failed queries.
Query q18 failed by error: 
== Results ==
!== Expected Answer - 10 ==                                                                         == Actual Answer - 10 ==
Query q25 failed by error: 
== Results ==
!== Expected Answer - 10 ==                             == Actual Answer - 10 ==
[galaxy s4 zoom фильм]                                 [galaxy s4 zoom фильм]
[авом констеть ребенка краево]                         [авом констеть ребенка краево]
[анапа оперевянные волшебную]                          [анапа оперевянные волшебную]
[брита ганам котлы на шерлок]                          [брита ганам котлы на шерлок] …
```
> [VL] gluten-it: Print error details

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenCoalesceAggregationUnionSuite.scala
> [GLUTEN-10379][CH] Fix: invalid result from CoalesceAggregationUnion

- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
This PR proposes to extract immutable collection as reusable field.
(Fixes: \#10351)
> [GLUTEN-10351] Extract immutable collection as reusable field

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/functions/JsonFunctionsValidateSuite.scala
- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/substrait/SubstraitToVeloxExpr.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/tests/Substrait2VeloxPlanConversionTest.cc
- gluten-substrait/src/main/java/org/apache/gluten/substrait/expression/StructLiteralNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/StructNode.java
- gluten-substrait/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/JsonExpressionTransformer.scala
Enable `to_json` function after velox supports https://github.com/facebookincubator/velox/pull/11995.
Test `GlutenJsonExpressionsSuite` and `GlutenJsonFunctionsSuite`.
> [VL] Enable to_json function

- gluten-ui/pom.xml
- gluten-ui/src/main/scala/org/apache/spark/sql/execution/ui/GlutenAllExecutionsPage.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/ui/TypeAlias.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/ui/TypeAlias.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/ui/TypeAlias.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/ui/TypeAlias.scala
- shims/spark40/src/main/scala/org/apache/spark/sql/execution/ui/TypeAlias.scala
Just an improvement for Spark-4.0 support.
Fixes #10419.
Compilation.
> [GLUTEN-10419][CORE] Fix type compatibility for `HttpServletRequest` through alias

- tools/workload/benchmark_velox/native_sql_initialize.ipynb
> [MINOR] Remove expired config

- backends-velox/src/test/scala/org/apache/gluten/functions/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
> [VL] Enable get_array_struct_fields function

- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/BinaryTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/BooleanTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/DateTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/DecimalTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FP32TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FP64TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FixedBinaryTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FixedCharTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I16TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I32TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I64TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I8TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/IntervalYearTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/ListNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/MapNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/NothingNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/StringTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/StructNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/TimestampTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/TypeNode.java
This pr proposes to change `TypeNode` from interface to abstract class.
Fixes #10473
GA tests.
> [GLUTEN-10473] Change TypeNode from interface to abstract class

- .github/workflows/velox_backend_x86.yml
- backends-velox/src/test/scala/org/apache/spark/sql/execution/GlutenHiveUDFSuite.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
- pom.xml
- shims/spark32/src/main/scala/org/apache/spark/sql/classic/ClassicTypes.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/classic/ClassicTypes.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/classic/ClassicTypes.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/classic/ClassicTypes.scala
- shims/spark40/src/main/scala/org/apache/spark/sql/classic/ClassicTypes.scala
Also re-include the test in CI.
Local compilation passed.
> [GLUTEN-8852] Fix code compatibility issues for two tests on Spark-4.0

- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
Just a quick fix for main branch CI failure.
CI.
> [TEST] Disable a gluten test temporarily: cast string to timestamp

- gluten-arrow/src/main/scala/org/apache/gluten/runtime/Runtimes.scala
This PR proposes to make string concatenation follows scala style.
GA tests.
> [MINOR] Refactor a string concatenation by following scala style

- gluten-arrow/src/main/scala/org/apache/gluten/runtime/Runtimes.scala
This PR proposes to remove unnecessary `create` for `Runtimes`.
Fixes #10529
GA tests.
> [GLUTEN-10529] Remove unnecessary create for Runtimes

- dev/vcpkg/setup-build-depends.sh
- ep/build-velox/src/get_velox.sh
- gluten-ut/common/src/test/scala/org/apache/spark/util/DebuggableThreadUtils.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenAnsiCastSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenAnsiCastSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenTryCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenTryCastSuite.scala
backport important fixes to 1.5 
pass GHA
> [GLUTEN-10574][Branch-1.5] Back port important fixes to branch-1.5

- dev/buildbundle-veloxbe.sh
- dev/builddeps-veloxbe.sh
This patch updated the package script to support spark-400
local verified
> [GLUTEN-8852][VL] Update package script for spark-400

- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/WindowUtils.java
For q12, support processing time in TimeAttributeWindowingStrategy
This patch was tested by manually run nexmark q12.
> [GLUTEN-10630][FLINK] Support processing time for q12

- .asf.yaml
Check if collaborator can trigger CI rerun
> Add kevinwilfong as a collaborator

- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
This PR proposes to make collection operation follows Scala style.
GA tests.
> [MINOR] Refactor a collection operation to follow Scala style

- backends-velox/src-iceberg/test/scala/org/apache/gluten/execution/enhanced/VeloxIcebergSuite.scala
- backends-velox/src-iceberg/test/scala/org/apache/spark/sql/gluten/TestUtils.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/extension/RewriteCreateTableAsSelect.scala
Add RewriteCreateTableAsSelect for spark34 for DSv2 Column Write
> [GLUTEN-10625][CORE] Add RewriteCreateTableAsSelect for spark34

- backends-velox/src-delta/main/scala/org/apache/gluten/component/VeloxDeltaComponent.scala
- gluten-delta/src/main/scala/org/apache/gluten/extension/OffloadDeltaFilter.scala
- gluten-delta/src/main/scala/org/apache/gluten/extension/OffloadDeltaProject.scala
- gluten-delta/src/main/scala/org/apache/gluten/extension/OffloadDeltaScan.scala
1. Use constants over string literals
2. Move rules to `extension` package
> [CORE] Minor cleanups for Delta support code

- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
This PR proposes to improve `getAndCheckSubstraitName` for `ExpressionConverter`.
Fixes #10691
GA tests.
> [GLUTEN-10691] Improve getAndCheckSubstraitName for ExpressionConverter

- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/RexNodeConverter.java
- gluten-flink/planner/src/main/java/org/apache/gluten/rexnode/functions/RexCallConverterFactory.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenVectorSourceFunction.java
- gluten-flink/runtime/src/main/java/org/apache/gluten/util/LogicalTypeConverter.java
Some minor changes:
1. support count_char udf and extract for q14.
2. small refine for log.
3. support TinyInt and Symbol type.
This patch was tested by manually running nexmark tests.
> [GLUTEN-10629][FLINK] Support udf count_char

- gluten-core/src/main/scala/org/apache/spark/util/SparkDirectoryUtil.scala
This PR proposes to refactor `SparkDirectoryUtil` with `ConcurrentHashMap`.
Fixes #10736
GA tests.
> [GLUTEN-10736] Refactor SparkDirectoryUtil with ConcurrentHashMap

- gluten-flink/ut/src/test/resources/nexmark/q18.sql
- gluten-flink/ut/src/test/resources/nexmark/q19.sql
- gluten-flink/ut/src/test/resources/nexmark/q20.sql
- gluten-flink/ut/src/test/resources/nexmark/q21.sql
Add nexmark tests to cover q18, q19, q20, q21.
These are tests.
> [GLUTEN-10550][FLINK] Add nexmark tests for q18-q21

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
Add `array_sort` support.
Depends on https://github.com/facebookincubator/velox/commit/059cd1387074efad06598afbd21c6fa9721c77ab.
Add tests
> [VL] Add Spark array_sort support with lambda function

- .github/workflows/nightly_sync.yml
- .github/workflows/velox_backend_cache.yml
- .github/workflows/velox_nightly.yml
Some CI jobs are intended for the upstream repository and do not need to run in forked repositories. For example, it is not intended to upload docs to apache nightly in forked repo.
N/A
> [VL][MINOR] Prevent selected CI jobs from running on forks
