README.md
SECURITY.md
native-sql-engine/core/src/main/scala/com/intel/oap/extension/columnar/ColumnarGuardRule.scala
native-sql-engine/cpp/src/CMakeLists.txt
native-sql-engine/cpp/src/jni/jni_common.h
native-sql-engine/cpp/src/jni/jni_wrapper.cc
native-sql-engine/cpp/src/proto/substrait_utils.cc
native-sql-engine/cpp/src/proto/substrait_utils.h

This pr made TPC-H Q6 runnable with Velox's calculation.
- Enabled Velox's Project and Aggregate
- Added data format conversion from Velox RowVector to Arrow RecordBatch for double type data.
Fixed https://github.com/oap-project/gazelle-jni/issues/4.

[GJ-4] makeTPC-H Q6 runnable with Velox's calculation

---

cpp/src/proto/substrait_utils.cc
jvm/src/main/scala/com/intel/oap/extension/columnar/ColumnarGuardRule.scala

This pr 
- added a fake result for TPC-H Q6 for easier debug.
- fallbacked the second stage of TPC-H Q6.
For each Partition, a fake result (res = 10000) will be returned as the output the first stage. The correct final result would be equal to `numPartitions * res`.
https://github.com/oap-project/gazelle-jni/issues/18

[GJ-18] Add a fake result for TPC-H Q6

---

cpp/src/proto/substrait_utils.cc
cpp/src/proto/substrait_utils.h

This pr removed the dependency to Velox PlanBuilder. Instead, Velox PlanNode will be directly created.
Close https://github.com/oap-project/gazelle-jni/issues/21.

[GJ-21] Remove PlanBuilder dependency

---

cpp/compile.sh
jvm/pom.xml
jvm/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
jvm/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
jvm/src/main/java/com/intel/oap/vectorized/JniUtils.java
jvm/src/main/scala/com/intel/oap/GazellePluginConfig.scala
jvm/src/main/scala/com/intel/oap/execution/WholeStageTransformerExec.scala
jvm/src/main/scala/com/intel/oap/execution/WholestageColumnarRDD.scala
pom.xml

This pr:
- added an option for deciding whether to compile CPP
- added a config for the native library name
With this pr, you can disable compiling CPP code by adding "**-Dbuild_cpp=OFF**" to your mvn compiling command.
When running queries, please use below two configs:
// Setting to false will disable loading native libraries.
--conf spark.oap.sql.columnar.loadnative=false
// Config the name of the native library to load.
--conf spark.oap.sql.columnar.libname="xxx"
Closes https://github.com/oap-project/gazelle-jni/issues/23.

[GJ-23] Make CPP compilation and library name configurable

---

jvm/src/main/java/com/intel/oap/vectorized/JniUtils.java

This pr fixed the incorrect library name.
https://github.com/oap-project/gazelle-jni/issues/23

[GJ-23] Fix the incorrect library name

---

jvm/src/main/java/com/intel/oap/row/JniInstance.java
jvm/src/main/java/com/intel/oap/row/RowIterator.java
jvm/src/main/java/com/intel/oap/row/SparkRowInfo.java
jvm/src/main/java/io/kyligence/jni/engine/LocalEngine.java
jvm/src/main/scala/com/intel/oap/GazellePluginConfig.scala
jvm/src/main/scala/com/intel/oap/execution/BasicPhysicalOperatorTransformer.scala
jvm/src/main/scala/com/intel/oap/execution/BatchScanExecTransformer.scala
jvm/src/main/scala/com/intel/oap/execution/HashAggregateExecTransformer.scala
jvm/src/main/scala/com/intel/oap/execution/NativeWholestageRowRDD.scala
jvm/src/main/scala/com/intel/oap/execution/WholeStageTransformerExec.scala
jvm/src/test/scala/com/intel/oap/benchmarks/BenchmarkTest.scala

1. Support ClickHouse as native engine;
2. Support Row iterator;
3. Add config 'spark.oap.sql.columnar.iterator' to specify whether to use columnar basic iterator
Following PR:
1. JNI Interface
2. Optimise Code 
Closes https://github.com/oap-project/gazelle-jni/issues/41.

[GJ-41] Support WS Tansformer with row-based output

---

cpp/src/CMakeLists.txt
docs/Velox.md

This pr made the necessary change to use an upgraded version of Velox.
Closes https://github.com/oap-project/gazelle-jni/issues/44.

[GJ-44] Upgrade the used Velox version

---

cpp/src/CMakeLists.txt
cpp/src/compute/substrait_to_velox_plan.cc
cpp/src/operators/c2r/velox_to_row_converter.cc
docs/Velox.md

This pr updated the dependent Velox version into the latest available commit.
Closes https://github.com/oap-project/gazelle-jni/issues/69.

[GJ-69] Update Velox

---

cpp/src/compute/protobuf_utils.cc
cpp/src/compute/protobuf_utils.h
cpp/src/jni/jni_common.h
jvm/src/main/scala/com/intel/oap/expression/AggregateFunctionsBuilder.scala
jvm/src/main/scala/com/intel/oap/expression/ArithmeticTransformer.scala
jvm/src/main/scala/com/intel/oap/expression/BinaryOperatorTransformer.scala
jvm/src/main/scala/com/intel/oap/expression/ConverterUtils.scala
jvm/src/main/scala/com/intel/oap/expression/NamedExpressionsTransformer.scala
jvm/src/main/scala/com/intel/oap/expression/UnaryOperatorTransformer.scala

This pr unified the function names according to the Substrait specifications in:
https://substrait.io/extensions/.
Based on: https://github.com/substrait-io/substrait/pull/147.
Closes https://github.com/oap-project/gazelle-jni/issues/75.

[GJ-75] Unify function names

---

cpp/src/compute/substrait_to_velox_plan.cc
cpp/src/compute/substrait_to_velox_plan.h

This pr fixed the segfault caused by the early release of Arrow stream.
Closes https://github.com/oap-project/gazelle-jni/issues/92.

[GJ-92] Fix arrow stream iter

---

jvm/pom.xml
jvm/src/main/java/com/intel/oap/substrait/rel/ExtensionTableBuilder.java
jvm/src/main/java/com/intel/oap/substrait/rel/ExtensionTableNode.java
jvm/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
jvm/src/main/scala/com/intel/oap/GazelleJniConfig.scala
jvm/src/main/scala/com/intel/oap/execution/NativeWholeStageColumnarRDD.scala
jvm/src/main/scala/com/intel/oap/execution/NativeWholestageRowRDD.scala
jvm/src/main/scala/com/intel/oap/execution/WholeStageTransformerExec.scala
jvm/src/main/scala/com/intel/oap/extension/ColumnarOverrides.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseConfig.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseDataSource.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseLog.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/ClickHouseSparkCatalog.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/commands/CreateClickHouseTableCommand.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/metadata/AddFileTags.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/ClickHousePartitionReaderFactory.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/ClickHouseScan.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/ClickHouseScanBuilder.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/table/ClickHouseTableV2.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/utils/CHDataSourceUtils.scala
jvm/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/utils/ScanMergeTreePartsUtils.scala
jvm/src/test/scala/com/intel/oap/benchmarks/BenchmarkTest.scala
jvm/src/test/scala/com/intel/oap/benchmarks/DSV2BenchmarkTest.scala
jvm/src/test/scala/com/intel/oap/benchmarks/TableBenchmarkTest.scala
pom.xml

Support to use ClickHouse Spark DataSource V2 to : 
1. create ClickHouse tables;
2. refresh tables;
3. query tables (TPCH-Q6);
To enabled this feature, add this conf in spark:
spark.sql.catalog.spark_catalog=org.apache.spark.sql.execution.datasources.v2.clickhouse.ClickHouseSparkCatalog
Write ClickHouse MergeTree data with Spark DataSource V2 will be implemented on Phase two.
To enable native engine, below option should be added:
--conf spark.oap.sql.enable.native.engine=true
Closes #90

[GJ-90] Support ClickHouse DataSource V2 -- Phase one

---

cpp/src/compute/substrait_to_velox_expr.cc
cpp/src/compute/substrait_to_velox_plan.cc
cpp/src/compute/substrait_to_velox_plan.h
cpp/src/jni/jni_common.h
cpp/src/jni/jni_wrapper.cc
cpp/src/operators/c2r/velox_to_row_converter.cc
cpp/src/operators/shuffle/splitter.cc
cpp/src/operators/shuffle/splitter.h
jvm/src/main/scala/com/intel/oap/expression/UnaryOperatorTransformer.scala
jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

This pr:
- enabled hash partitioning in Coumnar Shuffle
- fixed velox to arrow format issue in string column
- refined the logic in unify node
Closes https://github.com/oap-project/gazelle-jni/issues/96.

[GJ-96] Enable hash partitioning in columnar shuffle

---

cpp/compile.sh
cpp/gazelle-cpp/CMakeLists.txt
cpp/gazelle-cpp/compute/substrait_arrow.cc
cpp/gazelle-cpp/compute/substrait_arrow.h
cpp/gazelle-cpp/jni/jni_wrapper.cc
cpp/src/CMakeLists.txt
cpp/src/compute/protobuf_utils.cc
cpp/src/compute/protobuf_utils.h
cpp/src/compute/substrait_utils.cc
cpp/src/compute/substrait_utils.h
cpp/src/jni/exec_backend.cc
cpp/src/jni/exec_backend.h
cpp/src/jni/exec_backend_test.cc
cpp/src/jni/jni_common.h
cpp/src/jni/jni_wrapper.cc
cpp/src/operators/shuffle/splitter.cc
cpp/src/utils/exception.h
jvm/pom.xml
jvm/src/main/java/com/intel/oap/execution/ColumnarNativeIterator.java
jvm/src/main/java/com/intel/oap/vectorized/ExpressionEvaluator.java
jvm/src/main/java/com/intel/oap/vectorized/ExpressionEvaluatorJniWrapper.java
jvm/src/main/java/com/intel/oap/vectorized/JniInstance.java
jvm/src/main/scala/com/intel/oap/GazelleJniConfig.scala
jvm/src/main/scala/com/intel/oap/GazellePlugin.scala
jvm/src/main/scala/com/intel/oap/execution/NativeWholeStageColumnarRDD.scala
jvm/src/test/scala/com/intel/oap/jni/TestExpressionEvaluator.java
pom.xml

Re-write the interface for the execution backend. There are two interfaces for the execution backend. One is to implement a customized backend that will parse the raw substrait plan passed down by gazelle-jni and return a result iterator, and another is to implement the customized result iterator.
The pluggable execution backend will be built into different libraries. User can choose the library to build at compile-time, and use spark conf to choose the library to load at run-time.
This PR added a dummy gazelle-cpp backend in cpp/gazelle-cpp that demonstrates how to build and run with a pluggable backend. 
- Add `-Dbuild_gazelle_cpp=ON` to the build command to build library libgazelle_cpp.so. The library will be packed into the fat jar.
e.g. `mvn clean package -P full-scala-compiler …

[GJ-77] Make execution backend pluggable

---

cpp/gazelle-cpp/CMakeLists.txt
cpp/gazelle-cpp/compute/substrait_arrow.cc
cpp/gazelle-cpp/compute/substrait_arrow.h
cpp/gazelle-cpp/jni/jni_wrapper.cc
cpp/src/jni/exec_backend.h
cpp/src/jni/jni_wrapper.cc

Depends on https://github.com/oap-project/arrow/pull/93

[GJ-98] Enable TPCH Q6 & Q1 for arrow backend

---

docs/ArrowInstallation.md

For arrow version arrow-7.0.0-oap, a checkstyle issue lead to the installation failure.
1. better to skip checkstyle in ArrowInstallation.md
2. and need to fix checkstyle issue in arrow-7.0.0-oap branch
https://github.com/oap-project/gluten/issues/13.

[GJ-13] Skip checkstyle for arrow installation

---

docs/GlutenUsage.md
docs/Velox.md

This pr refined the docs in Velox.
https://github.com/oap-project/gluten/issues/13.

[GJ-13] Refine docs on Velox

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE
.github/workflows/dev_cron.yml
.github/workflows/dev_cron/issues_link.js
.github/workflows/dev_cron/title_check.js
.github/workflows/dev_cron/title_check.md
.github/workflows/unittests.yml

This patch adds GHA for below tests:
* each PR should be prefixed with Gluten-: e.g Gluten-12
* format check on C++ code
* trigger unit tests for each PR

[Gluten-129] Adding github actions framework

---

cpp/velox/CMakeLists.txt
cpp/velox/compute/VeloxPlanConverter.cc
docs/GlutenUsage.md
docs/Velox.md
jvm/src/main/java/io/glutenproject/substrait/expression/CastNode.java
jvm/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
jvm/src/main/scala/io/glutenproject/expression/UnaryOperatorTransformer.scala
jvm/src/main/scala/io/glutenproject/extension/columnar/ColumnarGuardRule.scala
tools/build_velox.sh

- Changed the Substrait plan generation logic when an pre-project is needed in aggregation.  Unique columns will be selected by pre-projection.
- Supported cast node.
- Updated the docs.
After this change, Gluten will depend on the [Velox](https://github.com/oap-project/velox) under oap-project.
Fixed https://github.com/oap-project/gluten/issues/147.
locally verified

[Gluten-147] Made the needed changes to update Velox

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxTransformerApi.scala
cpp/gazelle-cpp/compute/substrait_arrow.cc
cpp/src/jni/exec_backend.h
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
jvm/src/main/java/io/glutenproject/substrait/rel/JoinRelNode.java
jvm/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java
jvm/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
jvm/src/main/scala/io/glutenproject/GlutenConfig.scala
jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
jvm/src/main/scala/io/glutenproject/backendsapi/ITransformerApi.scala
jvm/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/ShuffledHashJoinExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
jvm/src/main/scala/io/glutenproject/expression/UnaryOperatorTransformer.scala
jvm/src/main/scala/io/glutenproject/extension/StrategyOverrides.scala
jvm/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala
jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala
jvm/src/test/scala/io/glutenproject/backendsapi/TransformerApiImplSuite.scala

Enable the substrait conversion in `ShuffledHashJoinExecTransformer`. Enable passing multiple input RDDs to native backend.
Add below configuration to force enabling shuffled hash join:
```
--conf spark.sql.autoBroadcastJoinThreshold=-1
--conf spark.gluten.sql.columnar.forceshuffledhashjoin=true
```
Verified locally.

[OPPRO-10] Hash Join support

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/ClickHouseScan.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
jvm/src/main/scala/io/glutenproject/execution/ShuffledHashJoinExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

Currently, the strategy of inserting 'WholeStageTransformer' only meet the shuffle exchange scenario, when there is a join operator, it also needs to insert 'WholeStageTransformer' for the children of the join operator.
Please refer to : [WholeStageCodegenExec.scala](https://github.com/apache/spark/blob/66648e96e4283223003c80a1a997325bbd27f940/sql/core/src/main/scala/org/apache/spark/sql/execution/WholeStageCodegenExec.scala#L893)
Close #161 .

[Gluten-161] The children of BaseJoinExec should insert WholeStageTransformerExec separately

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala

Fallback ShuffleExchangeExec with RangePartitioning for ClickHouse backend.
Close #167 .

[Gluten-167] Fallback ShuffleExchangeExec with RangePartitioning for ClickHouse backend.

---

cpp/src/jni/jni_wrapper.cc
cpp/velox/CMakeLists.txt
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
jvm/src/main/java/io/glutenproject/substrait/expression/DateListNode.java
jvm/src/main/java/io/glutenproject/substrait/expression/DoubleListNode.java
jvm/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
jvm/src/main/java/io/glutenproject/substrait/expression/IntListNode.java
jvm/src/main/java/io/glutenproject/substrait/expression/LongListNode.java
jvm/src/main/java/io/glutenproject/substrait/expression/StringListNode.java
jvm/src/main/scala/io/glutenproject/expression/ArithmeticTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/BinaryOperatorTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
jvm/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
jvm/src/main/scala/io/glutenproject/expression/InExpressionTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/NamedExpressionsTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/TernaryOperatorTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/UnaryOperatorTransformer.scala

This PR supported below expressions to be transformed into Substrait.
```
EndsWith, EqualTo, Or, Contains, In, Not, Like, StartsWith, Substring
```
Depends on: https://github.com/oap-project/velox/pull/14.
locally tested

[OPPRO-104] support more expressions

---

.github/workflows/unittests.yml
cpp/CMake/BuildArrow.cmake
cpp/CMake/ConfigArrow.cmake
cpp/CMakeLists.txt
cpp/gazelle-cpp/CMakeLists.txt
cpp/src/CMakeLists.txt

Currently the install/find arrow libraries process is in cpp/src/CMakeLists.txt, and other cpp modules like gazelle-cpp and velox are unable to use it. We need some extraction to make it available to every module.

[OPPRO-103] Extract find arrow libraries from cmake

---

cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/jni/jni_wrapper.cc

```
E0525 22:59:05.028767   212 Exceptions.h:68] Line: ../../velox/connectors/Connector.cpp:56, Function:registerConnector, Expression: okConnector with ID 'hive-connector' is already registered, Source: RUNTIME, ErrorCode: INVALID_STATE
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
what():  Exception: VeloxRuntimeError
Error Code: INVALID_STATE
Reason: Connector with ID 'hive-connector' is already registered
Expression: ok
Function: registerConnector
File: ../../velox/connectors/Connector.cpp
Line: 56
Stack trace:
```

[OPPRO-111] "Connector with ID 'hive-connector' is already registered" reported after renewing Spark SQL session

---

cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/compute/VeloxToRowConverter.cc
cpp/velox/compute/VeloxToRowConverter.h
cpp/velox/jni/jni_wrapper.cc

Found segfault in Velox's pool free. Fixed this issue by expanding the life time of Velox's memory pool.
Register min and max.
Depends on: https://github.com/oap-project/velox/pull/14.
Verified TPC-H on Jenkins.

[OPPRO-105] Fix the early release of memory pool

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/execution/VeloxFilterExecTransformer.scala
jvm/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
jvm/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
jvm/src/main/scala/io/glutenproject/expression/ScalarSubqueryTransformer.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/io/glutenproject/extension/columnar/ColumnarGuardRule.scala
jvm/src/test/scala/io/glutenproject/backendsapi/SparkPlanExecApiImplSuite.scala

Compare and separate the filter conditions in Scan and Filter.
Manually push down the left conditions in Filter into Scan.
Verified on TPC-H.

[OPPRO-104] Separate and push down filter conditions

---

cpp/gazelle-cpp/compute/substrait_arrow.cc
cpp/gazelle-cpp/jni/jni_wrapper.cc
cpp/src/compute/substrait_utils.h
cpp/src/jni/exec_backend.h
cpp/src/jni/jni_common.h
cpp/src/jni/jni_errors.h
cpp/src/jni/jni_wrapper.cc
cpp/src/utils/exception.h
cpp/src/utils/macros.h
cpp/velox/jni/jni_wrapper.cc

Including follow:
1. Catch all std::exception at JNI entrypoints;
2. Let all modules be able to access the exception utils as well as the main module.

[OPPRO-113] Improve C++ exception handling

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxTransformerApi.scala
cpp/velox/CMakeLists.txt
cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
jvm/src/main/java/io/glutenproject/substrait/rel/LocalFilesBuilder.java
jvm/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
jvm/src/main/resources/substrait/proto/substrait/algebra.proto
jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
jvm/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala

•	Add the parquet read dependencies into Gluten.
•	Parse and store the file format when converting the Substrait plan to Velox plan and then created the corresponding Split according to the specified file format.
•	Set the specified file format to replace the dead code when converting the Spark plan to Substrait plan.
depend on [oap-project/velox PR#13](https://github.com/oap-project/velox/pull/13) 
Locally test TPCH Q1 and Q6

[OPPRO-46] Support Parquet Scan in Gluten

---

backends-clickhouse/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
backends-velox/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister

To fix error like
```
java.lang.ClassNotFoundException: Failed to find data source: parquet. Please find packages at http://spark.apache.org/third-party-projects.html
at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:689)
at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:743)
at org.apache.spark.sql.DataFrameWriter.lookupV2Provider(DataFrameWriter.scala:993)
at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:311)
at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)
at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:874)
at io.glutenproject.integration.tpc.h.TpchDataGen.generate(TpchDataGen.scala:346)
at …
```

Vanilla Spark's data source types not found when running in a boundled jar

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashAggregateExecTransformer.scala
jvm/src/main/scala/io/glutenproject/GlutenConfig.scala
jvm/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/io/glutenproject/extension/columnar/ColumnarGuardRule.scala
jvm/src/test/scala/io/glutenproject/backendsapi/SparkPlanExecApiImplSuite.scala

This PR changed the Substrait plan for avg to avoid special handling in native. Changes are:
- Used sum and count to replace partial avg in Substrait plan.
- Added a row_constructor projection before aggregation for final avg.
- Seperated module for aggregation transformer.
Depends on: https://github.com/oap-project/velox/pull/31.

[OPPRO-182] Change the Substrait plan for avg

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeBlock.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/NativeFileScanColumnarRDD.scala
backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CHColumnarBatchSerializer.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDSV2ColumnarShuffleSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDSV2Suite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
jvm/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala
jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala

Separate Scan Operator as independent node for ClickHouse Backend and add metrics.
Close #279 .

[Gluten-279] Separate Scan Operator as independent node for ClickHouse Backend and add metrics.

---

backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashAggregateExecTransformer.scala

Fixed the result type of sum. If pre-projection is conducted, the input type should be the type after pre-projection, and the result type should be the accumulated type for int-like types.

[OPPRO-196] Fix the result type of sum in partial avg

---

cpp/velox/benchmarks/BenchmarkUtils.cc
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/jni/jni_wrapper.cc
jvm/src/main/java/io/glutenproject/vectorized/ExpressionEvaluator.java
jvm/src/main/scala/io/glutenproject/GlutenConfig.scala
jvm/src/main/scala/io/glutenproject/GlutenPlugin.scala

Use below spark conf to control Velox batch size of scan, agg and join.
> spark.sql.execution.arrow.maxRecordsPerBatch
Depends on https://github.com/oap-project/velox/pull/32.
locally tested

[OPPRO-173] Set Velox batch size

---

README.md
backends-velox/pom.xml
docs/GlutenUsage.md
docs/Velox.md
pom.xml
tools/build_velox.sh

Update velox_build.sh script. If we compile gluten with an existing repo, we need apply our change and compile option of the repo.
Test this script in two ways.
one way is build gluten with option " -Dbuild_velox_from_source=ON " 
The full compiling command is 
`mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=OFF -D build_protobuf=OFF`
another is  build gluten with option " -Dvelox_home=$VELOX_HOME  "
The full compiling command is 
`mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dvelox_home=$VELOX_HOME   -Dbuild_arrow=OFF -Dbuild_protobuf=OFF  -Dcompile_velox=OFF/ON`

[OPPRO-213]update build_velox.sh

---

backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
jvm/src/main/scala/io/glutenproject/GlutenConfig.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala

Add a parameter 'spark.gluten.sql.columnar.separate.scan.rdd.for.ch' to control whether to separate scan rdd for ClickHouse Backend.
Close #302 .

[Gluten-302] Add parameter for separating ClickHouse Scan RDD

---

backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2TPCDSBenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHNullableColumnarShuffleSuite.scala

Fix 'Method getXXX is not supported for Nullable(XXX)' when executing TPCH Q9 and add ut.
Close #330 .

[Gluten-330] Fix 'Method getXXX is not supported for Nullable(XXX)' when executing TPCH Q9 and add ut

---

cpp/src/jni/jni_wrapper.cc
cpp/src/utils/metrics.h
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
jvm/src/main/java/io/glutenproject/vectorized/Metrics.java
jvm/src/main/java/io/glutenproject/vectorized/OperatorMetrics.java
jvm/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala

This PR added below three runtime metrics into scan and join operator.
```
HashProbe:
* replacedWithDynamicFilterRows - the number of rows which were passed through
without any processing after filter was pushed down
* dynamicFiltersProduced - number of dynamic filters generated (at most one per
join key)
TableScan:
* dynamicFiltersAccepted - number of dynamic filters received
```

[OPPRO-167] Add runtime metrics for dynamic filter

---

backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashAggregateExecTransformer.scala
jvm/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
jvm/src/main/java/io/glutenproject/substrait/expression/SelectionNode.java
jvm/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
jvm/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala
tools/build_velox.sh

Previously, we use sum and count to replace partial avg. But incompatible intermediate type was found for avg(int). Instead of adding a projection for casting bigint to double, we changed to use partial avg in Velox and extract the subfields from struct.
Depends on https://github.com/oap-project/velox/pull/38.

[OPPRO-223] Change to use partial avg in Velox

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala

Fix wrong results when executing avg(int), avg(long), avg(boolean) for ClickHouse backend
Close #343 .

[Gluten-343] Fix wrong results when executing avg(int), avg(long), avg(boolean) for ClickHouse backend

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/expression/VeloxAliasTransformer.scala
jvm/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
jvm/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
jvm/src/main/scala/io/glutenproject/expression/NamedExpressionsTransformer.scala
jvm/src/test/scala/io/glutenproject/backendsapi/SparkPlanExecApiImplSuite.scala

Alias is not needed for Velox backend because the plan generation is index-based.
under test

[OPPRO-159] Remove alias for Velox backend

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashJoinExecTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHNullableColumnarShuffleSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHNullableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashJoinExecTransformer.scala
jvm/src/main/java/io/glutenproject/substrait/expression/BooleanLiteralNode.java
jvm/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
jvm/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
jvm/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarQueryStagePrepRule.scala
jvm/src/main/scala/io/glutenproject/extension/columnar/ColumnarGuardRule.scala
jvm/src/test/scala/io/glutenproject/backendsapi/SparkPlanExecApiImplSuite.scala

Since Velox only supports null aware Anti join for now, this PR implements a workaround to reproduce `not exists` semantics in Velox backend. It uses left outer join with aggregation, project, filter to replace anti join.
Verified on TPC-H and TPC-DS.

[OPPRO-242] Implement a workaround for Velox Anti join

---

jvm/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
jvm/src/main/scala/io/glutenproject/expression/InSetOperatorTransformer.scala

This PR changed the way of using SingularOrList options. Instead of putting all literals into a single list, each option was changed to be a literal.
Quoted from Substrait community on how to use options in SingularOrList:
> The design is that the output type of each repeated option should be the same as the value expression. So if value expression c0 is of type i32, then each of the individual expressions' output type in the options repeated field should be the same i32.
Depends on: https://github.com/oap-project/velox/pull/48, https://github.com/oap-project/arrow/pull/170.

[OPPRO-244] Change options in SingularOrList

---

.github/workflows/unittests.yml
backends-clickhouse/pom.xml
backends-gazelle/pom.xml
backends-velox/pom.xml
backends-velox/workload/tpch/gen_data/dwrf_dataset/tpch_convert_parquet_dwrf.sh
docs/ArrowBackend.md
docs/GlutenUsage.md
gluten-ut/pom.xml
jvm/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark32/pom.xml

Maven uses upper case `SNAPSHOT` to decide if an artifact is snapshot version or not.
https://github.com/apache/maven/blob/e410a6ce1dea787258e5675e71a672144e3f0419/maven-artifact/src/main/java/org/apache/maven/artifact/Artifact.java#L47

Use capital letter SNAPSHOT in versioning

---

cpp/velox/compute/VeloxPlanConverter.cc

This PR registered SparkSql functions first. In Velox, the first registered function name and signature will be put into an unordered map, so when the name of SparkSql and PrestoSql function is the same, the firstly registered one will be used.
Depends on: https://github.com/oap-project/velox/pull/49.
Verified TPC-H locally and on Jenkins.

[OPPRO-252] Register SparkSql functions first

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
jvm/src/main/java/io/glutenproject/vectorized/ExpressionEvaluator.java
jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
jvm/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala

Fix issue: Can not get the config 'spark.gluten.sql.columnar.libpath' when executing task for ClickHouse backend
Close #410 .

[Gluten-410] Fix issue: Can not get the config 'spark.gluten.sql.columnar.libpath' when executing task for ClickHouse backend

---

gluten-ut/src/test/scala/io/glutenproject/utils/NotSupport.scala
gluten-ut/src/test/scala/io/glutenproject/utils/SystemParameters.scala
gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseNotSupport.scala
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsBaseTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenAnsiCastSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenArithmeticExpressionSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenBitwiseExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCollectionExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenComplexTypeSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenConditionalExpressionSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDecimalExpressionSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenHashExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenIntervalExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenLiteralExpressionSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMiscExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenNondeterministicSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenNullExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenPredicateSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenRandomSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenRegexpExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenStringExpressionsSuite.scala

This is for https://github.com/oap-project/gluten/issues/414
Add an abstract class `NotSupport`,  the design is quite simple, and different backend can fill its not support list. i.e.
Currently, Velox backend support all case of `NullExpressionsSuite`
``` scala
object VeloxNotSupport extends NotSupport {
override lazy val notSupportSuiteList: Map[String, Map[String, ExpressionInfo]] = Map.empty
override lazy val fullSupportSuiteList: Set[String] = Set(
simpleClassName[NullExpressionsSuite]
)
}
```
In this PR,  clickhouse only supports part of `NullExpressionsSuite`
```scala
object ClickHouseNotSupport extends NotSupport {
override lazy val notSupportSuiteList: Map[String, Map[String, ExpressionInfo]] = Map(
(simpleClassName[NullExpressionsSuite], Map(
notSupport[Coalesce]("coalesce", …
```

[Gluten-414] Manage not supported test case in a centralized way

---

cpp/velox/compute/VeloxPlanConverter.cc
docs/Velox.md
tools/build_velox.sh

Update the setup script to install the dependencies for libhdfs3
This patch introduced a env to pass HDFS URI to gluten
`VELOX_HDFS="host:port"`
This env should be exported in both Spark driver and worker.
in Spark local mode: 
`export VELOX_HDFS="sr595:9000"`
in Spark Yarn cluster mode: 
`--conf spark.executorEnv.VELOX_HDFS="sr595:9000" `
If the variable is missing, Gluten will try to connect from hdfs://localhost:9000
closes: #158
pass jenkins

[OPPRO-77] install dependency for libhdfs3

---

backends-clickhouse/src/main/resources/META-INF/services/io.glutenproject.backendsapi.IBackendsApi
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2Q1ColumnarBenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2TPCDSBenchmarkTest.scala
backends-velox/src/main/resources/META-INF/services/io.glutenproject.backendsapi.IBackendsApi
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-ut/pom.xml
gluten-ut/src/test/scala/io/glutenproject/utils/SystemParameters.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
jvm/src/main/scala/io/glutenproject/GlutenPlugin.scala
jvm/src/main/scala/io/glutenproject/backendsapi/BackendsApiManager.scala
jvm/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
pom.xml

Automatically identify which backend when starting Gluten by BackendsAPI, and don't need to config the 'spark.gluten.sql.columnar.backend.lib' manually, specially for running ut.
Issue: [CH-132](https://github.com/Kyligence/ClickHouse/issues/132)

[CH-132] Automatically identify which backend

---

cpp/src/operators/shuffle/splitter.cc

The `bufs[pid]` length may be 0
```
#6  <signal handler called>
#7  0x00007f19d92f84a4 in std::__shared_ptr<arrow::Buffer, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x0)
at /usr/include/c++/9/bits/shared_ptr_base.h:1313
#8  0x00007f19d94d7cf2 in std::operator!=<arrow::Buffer>(std::shared_ptr<arrow::Buffer> const&, decltype(nullptr)) (
__a=<error reading variable: Cannot access memory at address 0x8>) at /usr/include/c++/9/bits/shared_ptr.h:404
#9  0x00007f19d94ce123 in gluten::shuffle::Splitter::SpillPartition (this=0x7f16e828e580, partition_id=0)
at /mnt/DP_disk1/code/gluten/cpp/src/operators/shuffle/splitter.cc:836
#10 0x00007f19d94cf105 in gluten::shuffle::Splitter::DoSplit (this=0x7f16e828e580, rb=...)
at /mnt/DP_disk1/code/gluten/cpp/src/operators/shuffle/splitter.cc:1002
#11 …
```

[OPPRO-278] Fix split coredump

---

backends-clickhouse/src/main/java/io/glutenproject/memory/CHMemoryConsumer.java
backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHManagedReservationListener.java
backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHMemoryAllocatorManager.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/test/java/org/apache/spark/memory/TestTaskMemoryManagerSuite.java
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2TPCDSBenchmarkTest.scala
backends-velox/src/main/java/io/glutenproject/memory/VeloxMemoryConsumer.java
backends-velox/src/main/java/io/glutenproject/memory/alloc/VeloxManagedReservationListener.java
backends-velox/src/main/java/io/glutenproject/memory/alloc/VeloxMemoryAllocatorManager.java
backends-velox/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
jvm/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocator.java
jvm/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocatorManager.java
jvm/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocators.java
jvm/src/main/java/io/glutenproject/vectorized/ExpressionEvaluator.java
jvm/src/main/scala/io/glutenproject/GlutenPlugin.scala
jvm/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
jvm/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
jvm/src/main/scala/org/apache/spark/util/memory/TaskMemoryResourceManager.scala
jvm/src/main/scala/org/apache/spark/util/memory/TaskMemoryResources.scala
jvm/src/test/scala/io/glutenproject/backendsapi/IteratorApiImplSuite.scala
jvm/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala

Unify cross-JNI memory management for ClickHouse backends.
Refer to:
1. [PR-251](https://github.com/oap-project/gluten/pull/251);
2. [PR-311](https://github.com/oap-project/gluten/pull/311);
3. [PR-325](https://github.com/oap-project/gluten/pull/325);
4. [PR-344](https://github.com/oap-project/gluten/pull/344);
5. [PR-440](https://github.com/oap-project/gluten/pull/440);

[CH-120] Unify cross-JNI memory management for ClickHouse backends

---

gluten-ut/src/test/scala/org/apache/spark/sql/GlutenStringFunctionsSuite.scala
jvm/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
jvm/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
jvm/src/main/scala/io/glutenproject/expression/TrimOperatorTransformer.scala

Close https://github.com/Kyligence/ClickHouse/issues/158
Related PR: https://github.com/Kyligence/ClickHouse/pull/117
Support more functions 
- ltrim(when trimStr is None)
- rtrim(when trimStr is None)
ltrim: 
```
0: jdbc:hive2://localhost:10000> explain formatted select ltrim(l_comment) from lineitem where l_comment like '%sly%' 
. . . . . . . . . . . . . . . .> ;
+----------------------------------------------------+
|                        plan                        |
+----------------------------------------------------+
| == Physical Plan ==
CollectLimit (6)
+- * Project (5)
+- BlockNativeColumnarToRowExec (4)
+- * FilterExecTransformer (2)
+- Scan parquet  (1)
(1) Scan parquet 
Output [1]: [l_comment#224]
Batched: true
Location: InMemoryFileIndex …
```

[CH-158] Support functions for clickhouse backend: ltrim/rtrim

---

backends-velox/src/main/java/io/glutenproject/vectorized/ShuffleSplitterJniWrapper.java
backends-velox/src/main/scala/org/apache/spark/shuffle/VeloxColumnarShuffleWriter.scala
cpp/src/jni/jni_wrapper.cc

[OPPRO-284] Remove computing first batch compressed size in shuffle write

---

docs/Velox.md
tools/build_velox.sh

This patch fixes HDFS short-circuit reading in velox backend.
By default HAWQ libhdfs3 does not set the default hdfs domain socket path, this
patch sets a default value for hdfs short-circuit read, align with apache HDFS, so it
can read HDFS with the correct socket path.
"/var/lib/hadoop-hdfs/dn_socket"
https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/ShortCircuitLocalReads.html
pass jenkins

[OPPRO-77] enable HDFS short-circuit reading

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashJoinExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashJoinExecTransformer.scala
jvm/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
tools/build_velox.sh

Removed the workaround for anti join because Velox upstream already supported regular anti join.
Related to https://github.com/oap-project/gluten/pull/375.
verified on Jenkins

[OPPRO-242] Remove the workaround for anti join

---

cpp/velox/compute/VeloxToRowConverter.cc
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxNotSupport.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala

We found that for some literal input test case, like `_FUNC_(123)`, spark has an optimization in catalyst to statically evaluate the result and make the plan become `RES as _FUNC_(123)`, which will not actually get the original plan evaluated by gluten. So we are proposing some changes in unit test configuration to turn off such optimizations.   
UT.

[OPPRO-286] Disable two optimization rules in UT to avoid static evaluation for literal input

---

pom.xml

Fix maven build issue with default spark version
#466 
mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=ON
@zhztheplayer  @jinchengchenghh   Gluten-it compilation issue and q69 accuracy issue have been resolved.

[Gluten-466] Fix maven build issue with default spark version

---

backends-clickhouse/pom.xml
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2BenchmarkTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/benchmarks/DSV2TPCDSBenchmarkTest.scala
backends-velox/pom.xml
gluten-ut/pom.xml
jvm/pom.xml
pom.xml
shims/pom.xml

Gluten jar includes scala jars, and the version of the scala jars is different with the one of the Spark, which will lead to error 'WrappedArray$ofRef; local class incompatible: stream classdesc'.
Close #507 .
Exist UTs.

[GLUTEN-507] Fix 'WrappedArray$ofRef; local class incompatible: stream classdesc' error

---

backends-clickhouse/pom.xml
backends-velox/pom.xml
gluten-ut/pom.xml
jvm/pom.xml

A few vulnerability alerts are reported by Github, which requires us to upgrade some dependencies' version.

[OPPRO-295] Bump some dependencies' version to avoid vulnerability issues

---

backends-velox/src/main/java/io/glutenproject/columnarbatch/ArrowColumnarBatches.java
backends-velox/src/main/scala/io/glutenproject/execution/VeloxFilterExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

The code for handling filter push down should check whether scan is transformable, considering unsupported filter can be pushed down to scan.
Reproducible issue link: https://github.com/oap-project/gluten/issues/560.

[OPPRO-314] Correctly fall back scan operator with unsupported filters

---

shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShimLoader.scala

In spark, short version stands for `major_version`-`minor_version`-`patch_version`. For a spark release, there is no difference between `SPARK_VERSION` & `SPARK_VERSION_SHORT`. But according to some customers' feedback, they are using their internally maintained spark. For example, their `SPARK_VERSION` can be 3.2.2.xxx. By using `SPARK_VERSION_SHORT`, gluten can load the expected spark-3.2.2 shim by ignoring the last part.
Ref.: https://github.com/oap-project/gazelle_plugin/pull/824

[OPPRO-320] Get spark short version for loading corresponding spark shim

---

.github/workflows/unittests.yml

We should disable the shared maven cache among the CI docker containers for Velox backend. Otherwise once a build is finished the other builds might be affected by the installed jar.

[CI] Disable shared maven cache in Velox CI

---

cpp/CMakeLists.txt
cpp/src/memory/columnar_batch.h
cpp/velox/compute/DwrfDatasource.cc
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/compute/VeloxToRowConverter.cc
cpp/velox/compute/bridge.h
cpp/velox/jni/jni_wrapper.cc

there are three `bridge.h` files ignored case sensitivity and may cause compile problem.
so, I fixed this problem by specifying file location

(bug#615) Fixing compilation error caused by bridge.h including

---

backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashAggregateExecTransformer.scala
ep/build-velox/src/build_velox.sh
gluten-core/src/main/java/io/glutenproject/substrait/expression/CastNode.java
gluten-core/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
gluten-core/src/main/scala/io/glutenproject/expression/UnaryOperatorTransformer.scala

Vanilla spark's behavior on cast failure can be different, depending on the config for ANSI (`spark.sql.ansi.enabled`). If ANSI is enabled, the expected behavior is just throwing a runtime exception. And if it is disabled, the expected behavior becomes returning a null result. Substrait already has a called `FailureBehaviorValue` flag for handling cast failure, which is helpful to us in doing this impl.

[OPPRO-328] Handle cast failure differently according to the config for ANSI

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

Support running `TakeOrderedAndProjectExec` in native engine.
unit tests

[CH-223]Support `TakeOrderedAndProjectExec`

---

backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala

Disable running range partitioning in backend when the partition keys contain expressions.
unit tests

[CH-226] Fix a weird bug to handle expressions for ClickHouse Backend

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHInitializerApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/NativeFileScanColumnarRDD.scala
backends-clickhouse/src/test/scala/io/glutenproject/RunTPCHTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseSyntheticDataSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHAbstractSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHAggAndShuffleBenchmark.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala
backends-gazelle/src/main/scala/io/glutenproject/backendsapi/gazelle/GazelleInitializerApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
docs/ClickHouse.md
gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/NativeWholeStageColumnarRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/NativeWholeStageRowRDD.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Remove the unused parameter 'spark.gluten.sql.columnar.loadnative'.
Close #666 .

[GLUTEN-666] Remove the unused parameter 'spark.gluten.sql.columnar.loadnative'

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/RunTPCHTest.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxIteratorApi.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxFunctionsValidateSuite.scala
gluten-core/src/main/java/io/glutenproject/substrait/rel/ExtensionTableNode.java
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/LogLevelUtil.scala
gluten-core/src/main/scala/io/glutenproject/utils/SubstraitPlanPrinterUtil.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Log substrait plan in json format when generating GlutenPartition
Close #665 .

[GLUTEN-665] Log substrait plan in json format when generating GlutenPartition

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/utils/CHInputPartitionsUtil.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
gluten-core/src/main/scala/io/glutenproject/utils/SparkResourcesUtil.scala

Support spliting partition by files count strategy for ClickHouse Backend (experimental): When the number of data files is several times the total number of cores, merge multiple files into one partition for processing to improve performance and reduce the amount of shuffle data. Note: make sure there is enough memory for processing multiple files in one partition.
Add a parameter spark.gluten.sql.columnar.backend.ch.files.per.partition.threshold to control the number of merged files, the default value is -1, means it will not take effect.
For example:
When set the parameter spark.gluten.sql.columnar.backend.ch.files.per.partition.threshold to 5, and there are 100 data files and 10 cores, theoretically 1 core can process 10 data files, which exceeds 5, it will merge 10 files into one …

[GLUTEN-663] Support spliting partition by files count strategy for ClickHouse Backend (experimental)

---

.github/workflows/unittests.yml
cpp/compile.sh
docs/GlutenUsage.md
docs/Velox.md
ep/build-arrow/src/build_arrow_for_gazelle.sh
ep/build-arrow/src/build_arrow_for_velox.sh
ep/build-arrow/src/get_arrow.sh
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh
tools/gluten-te/dockerfile-tpc
tools/one_step_veloxbackend.sh

1. add  one_step_veloxbackend.sh
usage:
cd gluten
./tools/one_step_veloxbackend.sh
3. add back ep_cache and incremental build
4. remove --gluten_dir option.

[OPPRO-319] Fix Install script

---

backends-velox/src/main/scala/io/glutenproject/execution/VeloxHashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala

Existence join in BHJ incorrectly fallbacked into vanilla Spark due to join type was not supported. 

[OPPRO-348] Fix existence join in BHJ

---

gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala

This PR fixed below failure when updating metrics due to getChild threw exception in ExpandExecTransformer.
`
WholeStageTransformerExec: Updating native metrics failed due to null.
`
under test

[OPPRO-167] Fix updating metrics

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
gluten-core/src/main/java/io/glutenproject/substrait/rel/GenerateRelNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/java/io/glutenproject/substrait/type/ListNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ArrayExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Support generate exec. close https://github.com/Kyligence/ClickHouse/issues/191 
test by CH[[194]]

[CH-191] Support generate exec

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarQueryStagePrepOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/StrategyOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenSparkPlanExecApi.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenColumnarToRowExec.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Fallback TPC-DS Q72 to vanilla spark when smj optimization not available.

[OPPRO-354] Fallback to vanilla spark when exist multi joins

---

cpp/velox/benchmarks/BenchmarkUtils.cc
cpp/velox/benchmarks/BenchmarkUtils.h
cpp/velox/benchmarks/GenericBenchmark.cc
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-ut/pom.xml
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
pom.xml

This generated parquet file maynot distinguished by velox sometimes, but can read by spark.
So we can read and write by vanilla spark, the converted file can read by gluten/velox
```
val tableDF = spark.read.format("parquet").load("/mnt/DP_disk2/tpcds/data/result_table.parquet")
tableDF.createOrReplaceTempView("tmp_table_4")
tableDF.write.format("parquet").save("/mnt/DP_disk2/tpcds/data/result_table_convert")
```
After velox fix this problem, we can use it directly.
usage:
./generic_benchmark  --threads 1 --print-result=false --write-file=/mnt/DP_disk2/tpcds/data/result_table_2.parquet --iterations 1

Write benchmark output to parquet file

---

cpp/velox/compute/ArrowTypeUtils.cc
cpp/velox/compute/ArrowTypeUtils.h
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameTungstenSuite.scala

Enable below test cases can reproduce:
```
enableSuite[GlutenDataFrameTungstenSuite]
.include("test nested struct type")
enableSuite[GlutenDataFrameSuite]
.includeByPrefix("SPARK-37855")
```

[OPPRO-360] Fix nested struct and map to-arrow type conversion

---

ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/JoinUtils.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala

[OPPRO-308] Support SortMergeExec operator in Gluten with velox backend

---

gluten-core/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/expression/MapExpressionTransformer.scala
gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

[CH-212] support map[key] and array[index] expression

---

cpp/core/jni/JniWrapper.cc
cpp/core/utils/metrics.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
gluten-core/src/main/java/io/glutenproject/vectorized/Metrics.java
gluten-core/src/main/java/io/glutenproject/vectorized/OperatorMetrics.java
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

To avoid flushing rows in Velox partial aggregation, this PR set the max memory usage according to offheap size. Metric `flushRowCount` to illustrate flushed rows was also added to Spark UI.

[OPPRO-361] Add flush row count and set max memory

---

cpp/core/compute/Backend.h
cpp/core/compute/BackendTest.cc
cpp/core/jni/JniWrapper.cc
cpp/gazelle-cpp/compute/SubstraitArrow.cc
cpp/gazelle-cpp/compute/SubstraitArrow.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h

1. Only one `GetResultIterator()` interface is enough, delete the redundant interfaces.
2. Avoid unnecessary checks, use the normal handle if possible.
3. If defining the `copy constructors`, you may also need to define the `assignment operator`, according to the `3/5/0 rules`.
4. The `explicit` keyword is used to avoid implicit converting for a single parameter, not for parameters.

[CPP Refactor] delete redundant Interfaces and avoid special processing

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarQueryStagePrepOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSessionExtensionSuite.scala

When AQE is on, those rules which have the privilege to override transformable tag (tag a plan before AddTransformHintRule), need to be placed in QueryStagePrepRules but not ColumnarRules.

Extract rules that applied before AddTransformHintRule

---

gluten-data/src/main/java/io/glutenproject/columnarbatch/GlutenColumnarBatches.java
gluten-data/src/main/java/io/glutenproject/columnarbatch/GlutenPlaceholderVector.java

The `GlutenPlaceholderVector` is not actually used and this pr is meant to avoid create it during each offload
existing tests

share the place holder vector instance

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/CoalesceExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenIteratorApi.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenColumnarToRowExec.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/python/ArrowEvalPythonExecTransformer.scala
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningV1SuiteAEOff.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsBaseTrait.scala

In vanilla Spark this is a common practice to exclude any possible plan (XXXExec) instances from RDD / task ser/de process. Probably by following reasons:
1. to minimize the serialized task size
2. to decouple execution from planning
If we don't follow the principle sometimes an error "-1 not equal 0" can easily be found in unit testing because:
1. by default, driver-side long metric is initialized as -1.
2. [-1 will be rewritten to 0](https://github.com/apache/spark/blob/05428c218444f4864f28ed83011ebcc5c75c80ba/sql/core/src/main/scala/org/apache/spark/sql/execution/metric/SQLMetrics.scala#L56-L64) if we include the driver-side long metric in serialized task. Usually it could be because metrics are defined in the class scope of a Spark plan (XXXExec), and the plan is included in the …

Avoid referencing to Spark plan instance during task serialization

---

ep/build-velox/src/build_velox.sh

libhdfs3 seek() is not optimal, especially on parquet reading case. This patch fixed this issue by skipping reads
ported from:
https://github.com/ClickHouse/libhdfs3/pull/31/files
pass jenkins

[OPPRO-77] fix libhdfs3 seek issue

---

cpp/core/CMakeLists.txt
cpp/core/operators/shuffle/splitter.cc
cpp/gazelle-cpp/CMakeLists.txt

The C++ standard of three backends supported by Gluten is not unified.
The standard `c++17` is configured for the backend Velox, the standard `c++14` is configured for the backend GazelleCpp and for module `cpp/core`.
This difference brings a mess, let's unify to the C++ standard 17, it's also aligned with the Velox configure requirement.
Because the `register` storage class is deprecated from `c++17`, I modified the corresponding code using `register`, it does not matter.
I'm not sure if this change brings errors for `gazelle_cpp` or not, but let's make a try. unit-test will tell us.

[cpp] unify the C++ standard for all backends

---

docs/developers/docker_ubuntu22.04.md

Add the script to compile gluten + velox in the docker of ubuntu22.04
Verified to work

Add docker script for Ubuntu22.04

---

gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameJoinSuite.scala

This issue is exposed from :
```
GlutenDataFrameJoinSuite:
"SPARK-32693: Compare two dataframes with same schema except nullable property"
```
Fix the keys  check inaccuracy and enable this UT.

[GLUTEN-374] Fix hashjoin Keys check inaccuracy and SPARK-32693 UT

---

cpp/CMakeLists.txt
cpp/core/benchmarks/CompressionBenchmark.cc
cpp/core/benchmarks/ShuffleSplitBenchmark.cc
cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
cpp/core/operators/c2r/ColumnarToRow.cc
cpp/core/operators/shuffle/reader.cc
cpp/core/operators/shuffle/splitter.cc
cpp/core/operators/shuffle/splitter.h
cpp/core/operators/shuffle/utils.h
cpp/velox/compute/ArrowTypeUtils.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxToRowConverter.cc
cpp/velox/tests/ShuffleSplitTest.cc
docs/developers/HowTo.md

1. configure debug compiling settings: modify the CMakeList.txt, add `-ggdb -O0`  to `CMAKE_CXX_FLAGS_DEBUG`
2. open the warning options: add compile_options `-Wall -Werror`, and make the source files comply the rules

[CPP] Add debug compiling configurations and open the warning options `-Wall/-Werror`

---

cpp/core/compute/Backend.h
cpp/core/compute/BackendTest.cc
cpp/core/compute/ProtobufUtils.cc
cpp/core/compute/ProtobufUtils.h
cpp/core/compute/ResultIterator.h
cpp/core/jni/ConcurrentMap.h
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
cpp/core/operators/shuffle/splitter.cc
cpp/core/operators/shuffle/splitter.h
cpp/velox/CMakeLists.txt
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/compute/RegistrationAllFunctions.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h

We include too many unnecessary header files, too much `#include` will lead to longer compilation time and more dependence.
How to check whether the file `test.h` includes appropriate header files or not?
1. create a new source file named `x.cc`
2. add `#include test.h` to `x.cc`, and make sure the file `x.cc` contains the only line `#include test.h`
3. compile x.cc, if OK, then `test.h` must include all the header files required by itself
4. delete a line such as '#include a.h' from `test.h`, if recompiled successfully, then `#include a.h` is redundant including, just remove it, and repeat this step to delete all unnecessary including statements.
I did as above and then create this PR, that's also the CppCoreGuidelines required.
(Please explain how this patch was tested. E.g. unit tests, …

[Cpp Refactor] tidy up file including for cpp module

---

gluten-ut/src/test/scala/org/apache/spark/sql/GlutenDataFrameJoinSuite.scala

https://github.com/oap-project/velox/pull/105 has fixed parquet reader bugs，
So  enable remaining UTs in GlutenDataFrameJoinSuite.

[GLUTEN-374] Enable UT SPARK-24690 after Velox parquet reader fixes

---

gluten-ut/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenRegexpExpressionsSuite.scala

Using `eval` in checkEvaluation will make all test cases fallback actually, since it is not a standard method in Gluten.

Revert the code of using eval to evaluate test result

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala

https://github.com/oap-project/gluten/issues/797

 [OPPRO-797] Support to load the libparquet.so.1000 when we use Gluten with Velox backend.

---

gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenJoinSuite.scala

https://github.com/oap-project/velox/pull/106 has fixed Velox hashjoin bugs，
So  enable remaining UTs in GlutenJoinSuite.

[GLUTEN-374] Enable UT SPARK-24690 and GlutenJoinSuite after Velox hashjoin fix

---

cpp/velox/compute/VeloxBackend.cc
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Before this pr, we need set extra env variable `VELOX_HDFS` in driver or executor, but that way does not make sense, we should read it from HADOOP_CONFIG eg `core-site.xml` directly.
Spark executor's `SparkConf` is initialized from driver's `SparkConf`, so we could use DriverPlugin to inject configs of what we need to used in executor.
manual test with hadoop cluster.
I would glad to hear your opinions. :)

[Gluten-788] Pass hadoop config from driver to executor.

---

.github/workflows/unittests.yml

This patch makes GHA to use less threads when compiling velox, to avoid the OOM issue
No tests required

Fix velox compile OOM in GHA

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/StructExpressionTransformer.scala
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenComplexTypesSuite.scala

Currently, `ClickHouse` backend has supported struct type, but we cannot run queries on specified struct fields. for example
```SQL
seelct s.a from t
```
where `s` is a struct column.
In this pr, we make a change on `NamedStruct.names` based on `type.proto`'s comments. 
```
// A message for modeling name/type pairs.
//
// Useful for representing relation schemas.
//
// Notes:
//
// * The names field is in depth-first order.
//
// For example a schema such as:
//
// a: int64
// b: struct<c: float32, d: string>
//
// would have a `names` field that looks like:
//
// ["a", "b", "c", "d"]
//
// * Only struct fields are contained in this field's elements,
// * Map keys should be traversed first, then values when producing/consuming
message …
```

[CH-239]Support queries on struct fields 

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ISparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/adaptive/ColumnarCustomShuffleReaderExec.scala
gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenSparkPlanExecApi.scala
gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashJoinExecTransformer.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/GlutenColumnarShuffleWriter.scala
gluten-ut/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala

1. ColumnarShuffleWriter field mapStatus is used in several AQE rules, which should be correct
2. Fallback the file bucket scan to vanila spark
3. Add isSkewJoin in HashJoinTransformer arguments
4. Plan metrics such as shuffle write bytes are different with spark, so gluten may use BroadcastHashJoin instead of SortMergeJoin when decide buildSide
5. Some plan changed, so it may not test as aimed to, need to add gluten new test later 
6. Implement ColumnarAQEShuffleReadExec metrics and other functions
7. Repartition in AQE will check if the shuffle is supported by checking ShuffleOrigin
8. Gluten does not have EmptyRelation check, so may cause performance regression because cannot eliminate join

[OPPRO-265] Enable GlutenAdaptiveQuerySuite

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/BlockOutputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHStreamReader.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/LowCopyFileSegmentShuffleInputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/LowCopyNettyShuffleInputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/OnHeapCopyShuffleInputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/ShuffleInputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/StorageJoinBuilder.java
backends-clickhouse/src/main/java/org/apache/spark/storage/CHShuffleReadStreamFactory.java
backends-clickhouse/src/main/java/org/apache/spark/storage/CHShuffleWriteStreamFactory.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CHColumnarBatchSerializer.scala
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/joins/ClickHouseBuildSideRelation.scala
cpp/core/jni/JniWrapper.cc
gluten-data/src/main/java/io/glutenproject/vectorized/LowCopyNettyJniByteInputStream.java
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Skip memory copy between onheap and native when using columnar shuffle manager for Clickhouse backend.
test by CH[[263]]

[CH-262] Skip memory copy between onheap and native when using columnar shuffle manager for Clickhouse backend

---

docs/Configuration.md

this patch sets the default value of spark.gluten.sql.columnar.wholestagetransform to true in the configuration page, to align with the value in code.
The non wholestage transform code path is buggy and we probably do not allow uses to set this to false

Update default configurations for wholestagetransform

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

ch_backend support inset is empty
test by CH[[258]]

[Gluten-826] ch_backend support inset is empty

---

gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala

Add sql tests in the timestampNTZ and native folders for velox backend
mvn clean install -pl gluten-ut -Pspark-3.2 -Pspark-ut -Pbackends-velox -DargLine="-Dspark.test.home=/opt/spark" -Dsuites="org.apache.spark.sql.GlutenSQLQueryTestSuite" -Darrow.version=10.0.0-SNAPSHOT

[Gluten-374] Add sql tests in the timestampNTZ and native folders for velox backend

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
docs/Velox.md
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This patch enables the caching feature for Velox. Cache file(s) will be generated on Spark context initialization, based on the configurations, velox will asynchronously caching the contents when reading from hdfs/s3.  The feature should be helpful if reading from slow/remote storage. 
Below configurations are added:
```
spark.gluten.sql.columnar.backend.velox.cacheEnabled // enable or disable velox cache, default off
spark.gluten.sql.columnar.backend.velox.cachePath  // the folder to store the cache files, default to /tmp
spark.gluten.sql.columnar.backend.velox.cacheSize  // the total size of the cache, default to 1GB
spark.gluten.sql.columnar.backend.velox.cacheShards // the shards of the cache, default to 1
spark.gluten.sql.columnar.backend.velox.cacheIOThreads // the threads for cache …
```

[OPPRO-347] Enable caching for Velox data connector

---

cpp/core/jni/JniCommon.h

bug fix for convert parquet to dwrf memory double free error as describe in #349 
manual tests
1. run tpch_convert_parquet_dwrf.sh it cause the error describe in #349
2. modfiy the jni_common.h as in pr, and re-run the script, no errors, and the dwrf file was produced.

[Gluten-349] Bug fix for checkException memory double free error

---

docs/GlutenUsage.md

Options `build_arrow_from_source` `build_velox_from_source` were already removed from script `builddeps-veloxbe.sh` from an earlier patch.
Instead, developer can specify --enable_ep_cache=ON to let build script decide whether to fetch and rebuild Velox or Arrow by comparing the commit IDs between latest build folder with remote git repository.

Update docs for some removed script arguments

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
cpp/core/operators/shuffle/splitter.cc
cpp/velox/CMakeLists.txt
cpp/velox/compute/RegistrationAllFunctions.cc
docs/Configuration.md
docs/VeloxNotSupport.md
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenValidatorApi.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenBloomFilterAggregateQuerySuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/Constants.scala
tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/TpcRunner.scala

1. Implement might_contain and bloom_filter_agg, TPCDS performance gain 14% improvement(bloom ON/OFF)
2. Fix splitter prealloc_row_count is inaccurate, caused OOM
3. Fallback CH backend collect_list
4. Add config spark.gluten.sql.native.bloomFilter to let user fix might_contain fallback to vanila spark but bloom_filter_agg offload to gluten

[OPPRO-279] Implement runtime native bloom filter

---

cpp/velox/compute/VeloxBackend.h

Follow up #632, this patch dumps the cache stats on exit if cache is enabled
Here's one example:
```
AsyncDataCache: 354440788 / 214748364800 bytes
Miss: 108 Hit 83 evict 0
read pins 0 write pins 0 unused prefetch 0 Alloc Megaclocks 3892336519 allocated pages 86533 cached pages 86533
Backing: [Memory capacity 52428800 free 52342267 mapped 86565 [size 1: 65(0MB) allocated 65 mapped]
[size 2: 50(0MB) allocated 50 mapped]
[size 4: 12(0MB) allocated 12 mapped]
[size 8: 46(1MB) allocated 46 mapped]
[size 16: 58(3MB) allocated 60 mapped]
[size 32: 37(4MB) allocated 37 mapped]
[size 64: 48(12MB) allocated 48 mapped]
[size 128: 57(28MB) allocated 57 mapped]
[size 256: 287(287MB) allocated 287 mapped]
]
SSD: Ssd cache IO: Write 0MB read 0MB Size 0GB Occupied 0GB0K entries.
GroupStats: <dummy …
```

[Follow up #632] dump cache stats on exit

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala

Limit over Sort is converted to TopN node in Velox, so there is only one suite of metrics for the two transformers. This PR fixed the NPE caused by metrics missing.
Locally tested.

Fix the NPE when updating metrics

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala

Fix the following issue, 
Caused by: java.lang.ClassCastException: org.apache.spark.sql.execution.GlutenBuildSideRelation cannot be cast to org.apache.spark.sql.execution.joins.HashedRelation
at org.apache.spark.sql.execution.SubqueryBroadcastExec.$anonfun$relationFuture$2(SubqueryBroadcastExec.scala:81)
at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:139)
at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:137)
Passed UTs.

Enable GlutenDynamicPartitionPruningV1SuiteAEOn, GlutenDynamicPartitionPruningV2SuiteAEOff and GlutenDynamicPartitionPruningV2SuiteAEOn.

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCharVarcharTestSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDatasetAggregatorSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDatasetOptimizationSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDatasetPrimitiveSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDatasetSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenFileBasedDataSourceSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenFileScanSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenJsonFunctionsSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenNestedDataSourceSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenProductAggSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenReplaceNullWithFalseInPredicateEndToEndSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLInsertTestSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenXPathFunctionsSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenIntervalExpressionsSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenCoalesceShufflePartitionsSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/exchange/GlutenEnsureRequirementsSuite.scala

Imported several more tests from https://github.com/apache/spark/tree/v3.2.2/sql/core/src/test/scala/org/apache/spark/sql. Updated https://github.com/oap-project/gluten/issues/374.
Tested on CI.

Import several more tests

---

gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

This PR is aim to make gluten to distinguish -0.0 and 0.0.

Enable GlutenDatasetPrimitiveSuite.

---

gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

The aggregateFunc.inputAggBufferAttributes size is different with aggregateFunc.children size in the count distinct agg expression. This PR fix the mismatch column index issue in [preproject ](https://github.com/oap-project/gluten/blob/05421d735e0f5373c25b36a09a0c2e88e0aee7dc/gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala#L274)and [agg ](https://github.com/oap-project/gluten/blob/05421d735e0f5373c25b36a09a0c2e88e0aee7dc/gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala#L376)node by both using the aggregateFunc.inputAggBufferAttributes.
(If this patch involves UI changes, please attach a screenshot; …

Partial enable GlutenDatasetSuite

---

pom.xml
substrait/substrait-spark/src/test/scala/io/substrait/spark/expression/ArithmeticExpressionSuite.scala

Substrait didn't push to the public repo when substrait-spark is added to gluten last year.
Let's upgrade substrait-core to 0.5.0 to avoid failing download in the US.
Using existed UT

Upgrade substrait-core to 0.5.0 to avoid failing download in the US

---

dev/formatcppcode.sh

1. make executing the `format` script faster by specifying `cpp` code's subdirectories.
2. specifying the version for `clang-format`.

Imrove formatcppcode.sh

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/exchange/GlutenEnsureRequirementsSuite.scala

To enable repartition optimization by remove shuffle, update shuffle partitions to [default value](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/test/TestSQLContext.scala#L64).  
Passed UT and CI.

Enable GlutenEnsureRequirementsSuite.

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHInitializerApi.scala
backends-gazelle/src/main/scala/io/glutenproject/backendsapi/gazelle/GazelleInitializerApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala
cpp/core/CMakeLists.txt
cpp/core/compute/Backend.h
cpp/core/compute/BackendTest.cc
cpp/core/config/GlutenConfig.cc
cpp/core/config/GlutenConfig.h
cpp/core/jni/JniWrapper.cc
cpp/gazelle-cpp/compute/SubstraitArrow.cc
cpp/gazelle-cpp/compute/SubstraitArrow.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/jni/JniWrapper.cc
gluten-core/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
gluten-core/src/main/java/io/glutenproject/vectorized/NativeExpressionEvaluator.java
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Move some configs from static config to session config
Some configs in spark is not static, such as `hadoop.fs.defaultFS`,  but in gluten, it is static, because it should be used to register Hive connector which should be reused in velox

Support set spark session config to native query context

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-gazelle/src/main/scala/io/glutenproject/backendsapi/gazelle/GazelleBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ITransformerApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenTransformerApi.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Previously, the scan format validation does not take effect for datasource v2. This PR aligned the validation logic for both v1 and v2.
under test

Fix scan format validation for datasource v2

---

gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala

Just add some SQL cases into GlutenSQLQueryTestSuite for CI, because related bugfixes patches have merged: 
https://github.com/oap-project/velox/pull/106
https://github.com/oap-project/velox/pull/122
https://github.com/oap-project/gluten/pull/879

Add some sql-tests for CI, because related bugs have fixed

---

gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenColumnarToRowExec.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenCachedTableSuite.scala

In a ut, we found the missing `outputPartitioning` for C2R can get an unnecessary shuffle exchange kept in the subsequent plans, e.g, the output partition already satisfies the requirements, so no more shuffle exchange is needed.
A spark ut can cover it in testing cached table.

Add outputPartitioning & outputOrdering for C2R

---

.github/workflows/unittests.yml

1. enable maven cache to accelerate CI.
2. docker only have read permission of maven cache.

Enable maven cache from GHA CI

---

cpp/core/config/GlutenConfig.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenFileBasedDataSourceSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Add spark config case-sensitive to native query context connector config, if case-insensitive, we will convert the column to lower case in substrait plan, then velox PlanNode accepts lowercase column name, and velox will convert parquet schema to velox schema with lower case column name

Support parquet read case_sensitive option mode

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Fallback to vanilla spark when the input file path does not contain partition info.

Enable GlutenInsertSuite  

---

cpp/velox/compute/VeloxColumnarToRowConverter.cc

For velox to row conversion, the scala code already allows timestamp type in the build checking. Here, we are enabling this type in native code.

[VL] Enable serializing timestamp type for UnsafeRow

---

pom.xml
tools/gluten-it/pom.xml

There are some vulnerabilities from dependencies: [CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250). At the same time, the version of log4j-core, included in its dependencies, is 2.11.2, which also has a large number of vulnerabilities. Thus we upgrade the scala-maven-plugin version from 4.3.0 to 4.8.0.
Unit tests.

[Gluten-core] Upgrade scala-maven-plugin from 4.3.0 to 4.8.0

---

cpp/core/jni/JniWrapper.cc
cpp/core/utils/metrics.h
cpp/velox/compute/WholeStageResultIterator.cc
gluten-core/src/main/java/io/glutenproject/vectorized/Metrics.java
gluten-core/src/main/java/io/glutenproject/vectorized/OperatorMetrics.java
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala

Velox has supports to count scan IO time in this pr https://github.com/facebookincubator/velox/pull/4026.
Gluten's Scan operator lack of `scanTime` metric, this pr will fix this problem.
Use cpu nanos instead of cpu count.

[Gluten-986]Align and enrich Scan operator metrics

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/OnHeapCopyShuffleInputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/StorageJoinBuilder.java
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/joins/ClickHouseBuildSideRelation.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHAggAndShuffleBenchmark.scala

Fix memory leak for ClickHouse Backend.
There are memory leak after executing BHJ.
Close #995.

[Gluten-995] Fix memory leak for ClickHouse Backend

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala

Remove `totalTime`, fix `collectTime`, add `buildTime`.
Gluten use `BackendsApiManager.getSparkPlanExecApiInstance.createBroadcastRelation` to collect data and build relation, we don't have to separate `collectTime` and `buildTime`, cause they are almost equal.
before this pr
after this pr
spark behavior

[Gluten-986] Metric "time to collect" is always 0 in ColumnarBroadcastExchange

---

docs/Velox.md

I often get compilation failure caused by `oom`, and I always forget the environment variable name, so I added this tip for me and others.

[VL document] a simple tip for compilation oom

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

The CH Backend CD has been fixed, the latest libch.so has been released, revert this PR.
Reverts oap-project/gluten#1014

Revert "[CH][HOTFIX] Fix ch backend upgrade issue"

---

cpp/core/operators/shuffle/splitter.cc
cpp/core/tests/TestUtils.h
cpp/velox/CMakeLists.txt
cpp/velox/shuffle/VeloxSplitter.cc
cpp/velox/shuffle/VeloxSplitter.h
cpp/velox/shuffle/VeloxSplitterPartitionWriter.h
cpp/velox/tests/VeloxSplitterTest.cc

1. add VeloxSplitter to support splitting with `velox::RowVector`. when the backend is `Velox`, splitting with `RowVector` can avoid transferring from `velox::RowVector` to `arrow::RowBatch`, it's more efficient.
2. we should avoid writing `using namespace arrow` or `using namespace facebook::velox` in header files, this usage brings mess and conflict.
3. I will add `Unit test` soon, so file `cpp/velox/tests/VeloxSplitterTest.cc` is not ready now, but it will not affect others.
4. I will also add the `JNI call functions` in file `velox/jni/JniWrapper` soon.

[VL shuffle] Add VeloxSplitter to split with velox::RowVector

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenCoalesceShufflePartitionsSuite.scala

We are enabling `GlutenCoalesceShufflePartitionsSuite` for velox backend. A few tests were modified to adapt to gluten based on the original vanilla tests.

[VL] Fix test issues in GlutenCoalesceShufflePartitionsSuite

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/AdaptiveSparkPlanUtil.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala

Since spark-3.2, AQE can work for DPP. So it's not correct to exclude DPP in the check for spark-3.3. And there is no need to separate the implementation in shim layers. Some code refactor is also done here.

[Gluten-core] Unify/Correct the check for whether a spark plan supports adaptive

---

cpp/core/operators/shuffle/splitter.cc

`arrow::bit_width(bool) >> 3 ` will get 0, it's wrong.

[VL][bugfix] fix the bug of Splitter::CalculateSplitBatchSize() processing column bool

---

cpp/velox/benchmarks/BenchmarkUtils.cc
cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/ArrowTypeUtils.cc
cpp/velox/compute/DwrfDatasource.cc
cpp/velox/compute/RegistrationAllFunctions.cc
cpp/velox/compute/RowConstructor.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxColumnarToRowConverter.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/jni/JniWrapper.cc
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/memory/VeloxMemoryPool.cc

1. avoid `using namespace xxx` in the header files.
2. I think using a fully qualified name is better than `using namespace` in most cases, but `using namespace facebook` in source files is no problem because `velox` is unique and we needn't use `facebook::velox` to guard.
3. let me explain why I proposed this PR:
- the Gluten project uses many third libraries, such as `arrow、velox、Substrait、protobuf`, so using a fully qualified name can express clear intention. don't let me guess.
- `using namespace xxx` will bring conflict and mess, I remind here again.

(refactor) make the code conform to `the Gluten cpp guidelines`

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/IIteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/CoalesceExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/utils/OASPackageBridge.scala
gluten-data/src/main/java/io/glutenproject/backendsapi/glutendata/GlutenIteratorApi.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/python/ArrowEvalPythonExecTransformer.scala

Current `MetricsUpdater::updateOutputMetrics` is unnecessary and has bug, it will count twice output metrics.
Implement task input metrics, only Scan operator could update that.

[Gluten-986] Support task input metrics, fix wrong output metrics.

---

cpp/core/tests/TestUtils.h
cpp/core/utils/Print.h
cpp/velox/shuffle/VeloxSplitter.cc
cpp/velox/shuffle/VeloxSplitter.h
cpp/velox/tests/VeloxSplitterTest.cc

add unit test for VeloxSplitter according to SplitterTest.
all UT passed except `TestRoundRobinNestLargeListArraySplitter` because `importFromArrow` does not support large list

[VL] All unit test for velox splitter passed

---

gluten-core/src/main/java/io/glutenproject/substrait/expression/DecimalLiteralNode.java
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

Decimal type value is '3.14159', but backend receive '3'
because scale value is not send.
test by ut

[Gluten] Fix decimal byte value is wrong to backend

---

gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/AdaptiveSparkPlanUtil.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/exchange/GlutenEnsureRequirementsSuite.scala

According to spark source code, whether AQE will be applied eventually depends on some constraints by checking spark plan, not just according to a config. So here we are proposing to correct the logic in checking whether adaptive is supported.

[Gluten-core] Correct the judgement for whether adaptive execution is supported

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala

`stddev_samp` has been supported in `ClickHouse`
unit tests
test by CH[[350]]
close https://github.com/Kyligence/ClickHouse/issues/325

[CH-325] Enable `stddev_samp`

---

cpp/CMakeLists.txt

[Gluten-core] Following #1088, rename C++ project name from spark_columnar_plugin to gluten

---

gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/AdaptiveSparkPlanUtil.scala
gluten-core/src/main/scala/io/glutenproject/utils/ColumnarShuffleUtil.scala

Currently, there are some differences in applying columnar rule, depending on whether adaptive execution is taking effect. So it is important to check whether the current execution goes into AQE context. Previously, we achieved the check by porting a piece of spark's source code, which is not a good approach. As that code logic needs our careful maintenance, especially in supporting multiple versions of spark. On the other hand, it breaks the principle of encapsulation, as Hongze pointed out.
Here, we are proposing to get AQE context known through checking thread stack trace, assuming the stack trace is stable. This approach may be tricky, but is more reliable and easier to maintain than the current approach.

[Gluten-core] Get adaptive execution context known through checking thread stack trace

---

gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala

**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Making the transformer plan log more obvious. Plan for sql 
```sql
select count(*) from my_char where name = 'Nemon'
``` 
Now is 
```sql
CHNativeColumnarToRow
+- *(2) HashAggregateTransformer(keys=[], functions=[count(1)], output=[count(1)#7])
+- ShuffleQueryStage 0
+- ColumnarExchangeAdaptor SinglePartition, ENSURE_REQUIREMENTS, false, [plan_id=49], [id=#49], [OUTPUT] List(count:LongType), [OUTPUT] List(count:LongType)
+- *(1) HashAggregateTransformer(keys=[], functions=[partial_count(1)], output=[count#10L])
+- *(1) ProjectExecTransformer
+- *(1) FilterExecTransformer (isnotnull(name#2) AND (name#2 = Nemon))
+- FileScan orc tpcds_parquet.my_char[name#2] Batched: true, DataFilters: …
```

[Gluten-1100] Making transformer plan log more obvious#1100

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
cpp/core/CMakeLists.txt
cpp/core/benchmarks/ShuffleSplitBenchmark.cc
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/operators/shuffle/CelebornSplitter.cc
cpp/core/operators/shuffle/CelebornSplitter.h
cpp/core/operators/shuffle/SplitterBase.h
cpp/core/operators/shuffle/splitter.cc
cpp/core/operators/shuffle/splitter.h
cpp/core/operators/shuffle/type.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/shuffle/VeloxSplitter.cc
cpp/velox/shuffle/VeloxSplitter.h
gluten-core/pom.xml
gluten-core/src/main/java/io/glutenproject/vectorized/SplitResult.java
gluten-core/src/main/java/org/apache/spark/shuffle/celeborn/CelebornShuffleManager.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/org/apache/spark/shuffle/CelebornShuffleWriterWrapper.scala
gluten-data/pom.xml
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleSplitterJniWrapper.java
gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenSparkPlanExecApi.scala
gluten-data/src/main/scala/io/glutenproject/vectorized/CelebornColumnarBatchSerializer.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/utils/CelebornPartitionPusher.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/utils/GlutenShuffleUtil.scala
pom.xml
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Gluten shuffle service supports Celeborn hash based columnar Shuffle
First refer this URL(https://github.com/apache/incubator-celeborn) to create a celeborn cluster.
Then add the following configurations when starting the Spark Application.
* spark.shuffle.manager org.apache.spark.shuffle.celeborn.CelebornShuffleManager
* spark.serializer org.apache.spark.serializer.KryoSerializer
* spark.celeborn.master.endpoints clb-master:9097
* spark.celeborn.shuffle.writer hash
* spark.shuffle.service.enabled false
* spark.sql.adaptive.localShuffleReader.enabled false
* spark.dynamicAllocation.enabled false (If you want to use dynamic resource allocation, please refer to this URL (https://github.com/apache/incubator-celeborn/tree/main/assets/spark-patch) to apply the patch into your own Spark)

[Gluten-999] Gluten shuffle service supports Celeborn hash based columnar Shuffle

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHFilterExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/utils/LogLevelUtil.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Validation failure log level now is debug, which makes finding reasons of fallback difficult.
This PR try to make it configuable, just like the way to control plan log: spark.gluten.sql.transform.logLevel and spark.gluten.sql.substrait.plan.logLevel
I propose add two new flags:
spark.gluten.sql.validate.failure.logLevel
spark.gluten.sql.validate.failure.printStack
test manually by ”explain select sum(i_current_price) from item;“
Table item is a tpcds table in parquet format.
Column i_current_price data type is decimal

[Gluten-1147][Gluten-core] Make validate failure logLevel configuable

---

cpp/core/jni/JniWrapper.cc
cpp/core/operators/shuffle/splitter.cc

Spark print result in stdout, print log in stderr, we should not use std::cout explicitly.

[Gluten-core] Remove std::cout in cpp code

---

gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/CoalesceBatchesExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/CoalesceExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ColumnarInMemoryTableScanExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarSubqueryBroadcastExec.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/python/ArrowEvalPythonExecTransformer.scala

We need to have a easy check to see whether a plan is a gluten plan or not. Considering the `TransformSupport` trait cannot be extended by all gluten plan, e.g, union, etc. for some reasons, I am proposing to add a new trait for gluten plan to extend.

[Gluten-core] Add a general trait for gluten plan to extend

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala

The current implementation of IteratorOptions sets the `bufferSize` as a hard-coded number, which happens to be the same value as `shuffleSplitDefaultSize`. 
However, both variables represent the same concept and have the same intended use.

[CH] Make bufferSize of IteratorOptions configurable

---

gluten-core/src/main/scala/io/glutenproject/utils/QueryPlanSelector.scala

Avoid printing stack traces with excessive depth in QueryPlanSelector, as this will make the logs clearer.

[Gluten-core] Avoid printing stack traces with excessive depth

---

gluten-core/src/main/java/io/glutenproject/substrait/expression/BinaryLiteralNode.java
gluten-core/src/main/java/io/glutenproject/substrait/expression/BinaryStructNode.java
gluten-core/src/main/java/io/glutenproject/substrait/expression/DecimalLiteralNode.java

We meet the OOM problem when we were tring to perf TPCDS Q4 with native bloom filter enabled. Since memcp is called every time `toProtobuf` is called, most of the driver memory was occupied by ByteString, and finally coused `java.lang.OutOfMemoryError: Java heap space`.
unit tests

[Gluten-core] Reuse ByteString in ExpressionNode.toProtobuf to avoid OOM

---

gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/ColumnarShuffleUtil.scala

Some variables' name is misleading. In somewhere, we are checking the top parent plan to see whether it is exchange. So we should not name the corresponding variable with leaf plan used.

[Gluten-core] Change some variables' name

---

cpp/core/compute/Backend.h
cpp/core/tests/ColumnarToRowTest.cc
cpp/velox/benchmarks/BenchmarkUtils.cc
cpp/velox/benchmarks/BenchmarkUtils.h
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h

1. change `getVeloxPlanNode` to `toVeloxPlan`
2. change `getFileInfos` to `getSplitInfos`
3. rename several data members to express more explicit intentation 

[VL] make the VeloxBackend's data & functions more readable

---

package/pom.xml

maven clean package will automatically clean up package/target folder.
We want to keep all gluten jar for both 3.2 and 3.3.
cd $GLUTEN_DIR
mvn clean package -Pbackends-velox -Pspark-3.2 -DskipTests
mvn clean package -Pbackends-velox -Pspark-3.3 -DskipTests
The maven clean command will not delete gluten jar.
when we change some codes, and compile again.
mvn clean package -Pbackends-velox -Pspark-3.2 -DskipTests
mvn clean package -Pbackends-velox -Pspark-3.3 -DskipTests
Old jar will be overwrited by new jar.

[VL] avoid clean package/target/*.jar when call mvn clean

---

.github/workflows/velox_be.yml
cpp/compile.sh
dev/builddeps-veloxbe.sh
docs/GlutenUsage.md
docs/Velox.md
docs/developers/HowTo.md
docs/developers/MicroBenchmarks.md
docs/developers/NewToGluten.md
ep/build-arrow/src/build_arrow.sh
ep/build-arrow/src/get_arrow.sh
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh

1. To provide better encapsulation between `get_xxx.sh`  and `build_xxx.sh`
1. Move ep-caching code from `get` to `build`
2. Move after-patching code from `build` to `get`
2. Reformat the bash codes

[VL] Clean up EP build scripts

---

gluten-core/src/main/java/org/apache/spark/shuffle/celeborn/CelebornShuffleManager.java

Support using Celeborn in the scenario of switching multiple SparkContexts in the same process of Velox CI
If we switch the SparkSession in the Velxo CI, the following exception will occur.
```
[Executor task launch worker for task 0.0 in stage 8.0 (TID 8)] WARN  org.apache.celeborn.shaded.io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xca6cd07d]
java.util.concurrent.RejectedExecutionException: event executor terminated
at org.apache.celeborn.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:932) ~[celeborn-client-spark-3-shaded_2.12-0.2.0-incubating.jar:?]
at org.apache.celeborn.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecu …
```

[VL] Support using Celeborn in the scenario of switching multiple SparkContexts in the same process of Velox CI

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHShutdownApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxShutdownApi.scala
cpp/velox/jni/JniWrapper.cc
gluten-core/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
gluten-core/src/main/java/io/glutenproject/vectorized/JniLibLoader.java
gluten-core/src/main/java/io/glutenproject/vectorized/NativeExpressionEvaluator.java
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendsApiManager.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ShutdownApi.scala

Fix coredump existed in libch.so: https://github.com/Kyligence/ClickHouse/issues/364
test by CH[[377]]

[CH-364] Explicitly invoke JNI_ONUnload when spark driver or executor are shuting down

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHFilterExecTransformer.scala
gluten-core/src/main/java/io/glutenproject/substrait/expression/ExpressionBuilder.java
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/CoalesceExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformerExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ScalarSubqueryTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/TransformerState.scala
gluten-data/src/main/scala/io/glutenproject/execution/GlutenFilterExecTransformer.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/python/ArrowEvalPythonExecTransformer.scala

Please check #1201 
Test manually by explain tcpds q14-1, scale factor 0.1

[GLUTEN-1201][CORE] Skip scalar subquery execution during validation

---

cpp/core/memory/HbwAllocator.cc
cpp/core/memory/HbwAllocator.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/velox/memory/VeloxMemoryPool.cc

[VL] Include Velox non-contiguous allocations into Spark memory manager's accountation

---

cpp/velox/memory/VeloxMemoryPool.cc

Made a mistake: The previous PR https://github.com/oap-project/gluten/pull/1228 just operated on **contiguous** allocations.
This would include **non-contiguous** allocations into the routine too.

[VL] Include Velox non-contiguous allocations into Spark memory manager's accountation (patch 2)

---

cpp/core/operators/shuffle/reader.cc

first_message_ maybe null when task is killed by speculation. This pr is related to #1187 , here we only cover the npe, and left another pr to fix the exception thrown by java side.
unit tests.

[GLUTEN-1199][VL][Fix] Fix npe when task is killed by speculation

---

cpp/core/config/GlutenConfig.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/WholeStageResultIterator.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Add a configuration `spark.gluten.memory.offHeap.percent` to limit the max memory used by native engine.
unit tests

[VL] Add config to limit the max memory

---

cpp/velox/benchmarks/ColumnarToRowBenchmark.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/jni/JniWrapper.cc
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/memory/VeloxMemoryPool.cc
cpp/velox/memory/VeloxMemoryPool.h
cpp/velox/shuffle/VeloxSplitter.cc
cpp/velox/tests/ArrowToVeloxTest.cc
cpp/velox/tests/VeloxColumnarToRowTest.cc
cpp/velox/tests/VeloxSplitterTest.cc
ep/build-velox/src/build_velox.sh

1. velox change memory pool API. we need call addChild to create memory pool to allocate.
2. planFragment constructor  change a little bit.
3. setMemoryUsageTracker was removed by velox.
corresponding velox branch is https://github.com/zhejiangxiaomai/velox/tree/main_rebase_329
4. add "  cmake --install xsimd-build/  cmake --install gtest-build/" in build_velox.sh.  because velox move xsimd/gtest into resolve_dependency module.

[VL] Upgrade velox to 2023.3.29

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

remove decimal failed ut
test in ci

[VL] Remove Decimal failed SPARK-35955 ut exclude in GlutenDataFrameSuite

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Enable  `Resolve type conflicts - decimals, dates and timestamps in partition column`.
https://github.com/oap-project/velox/pull/167
https://github.com/oap-project/gluten/issues/1217
Testing on CI.

[GLUTEN-1217][VL] UT: Enable UT when partitioned column is decimal type

---

.github/PULL_REQUEST_TEMPLATE
.github/workflows/dev_cron/issues_link.js
.github/workflows/dev_cron/title_check.js
.github/workflows/dev_cron/title_check.md

- match [GLUTEN-xxxx] when automatically linking with issue
- Adding example title following the Angular git commit conventions:  `[GLUTEN-ISSUEID][COMPONENT]feat/fix: xxxx`
- also addes a "Fixes:" in the PR description area
no need to test

Minor: Update pull request template with more example inputs

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHInitializerApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala
cpp/core/config/GlutenConfig.h
cpp/velox/benchmarks/BenchmarkUtils.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxInitializer.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/memory/VeloxMemoryPool.cc
docs/Velox.md
gluten-core/src/main/java/io/glutenproject/vectorized/NativeExpressionEvaluator.java
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/GlutenColumnarShuffleWriter.scala
package/pom.xml
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
tools/gluten-it/src/main/scala/io/glutenproject/integration/tpc/TpcSuite.scala

Add following new config options:
```
// key -> default value
spark.gluten.sql.columnar.backend.velox.spillEnabled -> true
spark.gluten.sql.columnar.backend.velox.memoryCapRatio -> 0.75
spark.gluten.sql.columnar.backend.velox.kAggregationSpillEnabled -> true
spark.gluten.sql.columnar.backend.velox.kJoinSpillEnabled -> true
spark.gluten.sql.columnar.backend.velox.kOrderBySpillEnabled -> true
spark.gluten.sql.columnar.backend.velox.kAggregationSpillMemoryThreshold -> 0
spark.gluten.sql.columnar.backend.velox.kJoinSpillMemoryThreshold -> 0 // this one doesn't work for now
spark.gluten.sql.columnar.backend.velox.kOrderBySpillMemoryThreshold -> 0
```
Values for `xxxThreshold` are of unit byte.
`spark.gluten.sql.columnar.backend.velox.kJoinSpillMemoryThreshold` doesn't currently take effect - …

[VL] Add some config options for Velox spill

---

cpp/core/memory/ColumnarBatch.h

add `operator<<` for ColumnarBatch.
Fixes: Since gtest upgraded to 1.13, exec_backend_test will encounter  this problem.
```
undefined reference to `testing::internal::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::ostream*)'
```
Follow this solution to fix it. https://github.com/google/googletest/issues/3816
GHA test

[VL] Fix exec_backend_test  compile problem introduced by gtest 1.13

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetColumnarShuffleAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetColumnarShuffleSuite.scala

TPCDS SQL generated too many temporary files due to shullfer, causing the inode of CI machine to be full, resulting in CI hanging

[CH] Ignore ch backend tpcds suite

---

cpp/core/jni/JniWrapper.cc

In nativeConvertRowToColumnar, the method parameter name cSchema is the same as the local variable name, which is not standardized.

[VL] Optimize variable name in nativeConvertRowToColumnar

---

README.md
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoader.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderCentos7.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderCentos8.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderUbuntu2004.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderUbuntu2204.scala
dev/package.sh
docs/developers/NewToGluten.md
docs/developers/docker_ubuntu22.04.md

1. support package thirdparty libs for centos7 and centos8.
2. use can run on centos7/centos8 with one command.
3. package.sh is just run on clean docker. user can change the path of lib for themselves. And package.sh is only work for velox now.

[VL] package.sh support centos7 and centos8

---

.github/workflows/velox_be.yml
gluten-ut/common/src/test/java/org/apache/spark/tags/ExtendedSQLTest.java
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/orc/GlutenOrcV1SchemaPruningSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/orc/GlutenOrcV2SchemaPruningSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetSchemaPruningSuite.scala

This patch picked up those slow tests from Spark unit tests and run them in a parallel job to speed up the CI.
- GlutenSQLQueryTestSuite
- GlutenOrcV1SchemaPruningSuite
- GlutenOrcV2SchemaPruningSuite
- GlutenParquetV1FilterSuite
- GlutenParquetV2FilterSuite
- GlutenParquetV1SchemaPruningSuite
- GlutenParquetV2SchemaPruningSuite
related: #1296 
pass GHA

[GLUTEN-1296][VL][CI]fix: Speed up on running Spark unit tests

---

gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala

With Velox decimal sum fix, use bool for isEmpty in decimal sum.
https://github.com/oap-project/velox/pull/195

[VL] fix: use bool for isEmpty in decimal sum

---

cpp/velox/compute/DwrfDatasource.cc
cpp/velox/compute/DwrfDatasource.h
cpp/velox/compute/VeloxInitializer.cc
docs/Velox.md
ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

In some use cases, data is stored in multiple HDFS endpoints. In https://github.com/oap-project/velox/pull/174, we made some code changes in velox to initialize an hdfs client by need, i.e., getting endpoint info from full hdfs file path when read operation comes and do the initialization if the corresponding client is not created. Thus, there is no need to configure a single hdfs endpoint. 
Tests with multiple hdfs endpoints used.

[GLUTEN-1270][VL][Feat] Support multiple HDFS endpoints

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
cpp/velox/jni/JniWrapper.cc
ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala

Support partial merge phase on Velox backend. This PR mainly focuses on supporting the partial merge step brings by `count distinct`, and a follow-up PR will be proposed to support other distinct functions.
https://github.com/oap-project/velox/pull/193

[VL] feat: support partial merge phase in aggregation

---

cpp/velox/CMakeLists.txt

Velox is going to use CMake modules replace gitmodules, this PR add CMake xsimd search path to pass compile.
manual test.

[VL] Add xsimd search path

---

gluten-data/src/main/scala/org/apache/spark/sql/execution/GlutenBuildSideRelation.scala

This patch modifies the equality check with both name and exprId if there are at least 2 columns in the output, so that two or more keys with same name(but different exprId) are allowed in hashmap building process.
- on Q72 the issue is due to the output of build relation has two columns with same name but different exprId
- on Q5 the issue is due to a reused broadcast xchg, although there's only output column, the expr name and Id are not matching from the original plan
Fixes: #1141 
pass GHA
manually verified with TPCDS Q72 + CBO enabled

[GLUTEN-1141][VL]fix: building hashmap with new key equality check

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxInitializerApi.scala

(Fixes: \#1367)
manual tests on anolis

[GLUTEN-1367] Support running gluten on anolis

---

shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

the previous one https://github.com/oap-project/gluten/pull/1356 doesn't fix the issue

[VL] Fix broken memory limit used for Velox spilling (patch 2)

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala

Support space function for clickhouse 
the releated pr: https://github.com/Kyligence/ClickHouse/pull/321
the realted issue: https://github.com/Kyligence/ClickHouse/issues/320
by add unit test in GlutenClickHouseTPCHSUite.scala

[CH-320] Support space function

---

pom.xml

[GLUTEN-1407] Let profile control shim version

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
gluten-core/src/main/scala/io/glutenproject/utils/QueryPlanSelector.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Move the config 'spark.gluten.enabled' to GlutenConfig from QueryPlanSelector
(Fixes: #1369 )
Close #1369 .

[GLUTEN-1369][Core] Move config 'spark.gluten.enabled' to GlutenConfig from QueryPlanSelector

---

.github/workflows/clickhouse_be_trigger.yml

Enable trigger gluten Clickhouse CI on specific files change.
1. Please grant github workflow `read and write permissions` in repo settings.
2.  Once PR files change may affect Gluten Clickhouse CI,  github workflow `Clickhouse Backend Trigger` with comment this PR, like 
`Run Gluten Clickhouse CI`
3. Please set jenkins job trigger on specific comment.

[GLUTEN-1429][CH] trigger clickhouse CI job on specific files change

---

.github/workflows/clickhouse_be_trigger.yml

According to github actions doc, forked repository's GITHUB_TOKEN only has READ permission. 
see https://docs.github.com/en/actions/security-guides/automatic-token-authentication
(Fixes: \#1450)
But when we use pull_reuqest_target, forked repository's PR works.

[GLUTEN-1450] [CH] enable forked repository's GITHUB_TOKEN comment in PR

---

cpp-ch/local-engine/Common/StringUtils.cpp

This pr converts partition names get from hdfs path to lower case, as spark paritiions are in lower case.
(Fixes: \#1410)
This patch was tested manually.

[GLUTEN-1410] [CH] convert partition name to lower case

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/Config.h
cpp-ch/local-engine/Storages/ArrowParquetBlockInputFormat.cpp
cpp-ch/local-engine/Storages/ArrowParquetBlockInputFormat.h
cpp-ch/local-engine/Storages/CustomMergeTreeSink.cpp
cpp-ch/local-engine/Storages/CustomMergeTreeSink.h
cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/OrcFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/OrcFormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/OrcUtil.h
cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
cpp-ch/local-engine/Storages/ch_parquet/OptimizedArrowColumnToCHColumn.cpp
cpp-ch/local-engine/Storages/ch_parquet/OptimizedArrowColumnToCHColumn.h
cpp-ch/local-engine/Storages/ch_parquet/OptimizedParquetBlockInputFormat.cpp
cpp-ch/local-engine/Storages/ch_parquet/OptimizedParquetBlockInputFormat.h
cpp-ch/local-engine/proto/CMakeLists.txt

[GLUTEN-1389][CH] Fix ORC/Parquet column name case-insensitive matching issue

---

cpp/velox/shuffle/VeloxShuffleWriter.cc

https://github.com/oap-project/gluten/pull/1370 fixed the core dump error for decimal data. However, we found that the correctness of shuffle write is wrong. We cannot directly use SplitFixedType<uint64_t> method to handle short decimal. In velox short decimal is stored in int64, arrow always use int128 to store decimal, so we should copy int64 data to int128 dst.
Run 1T tpcds, and compare results.

[VL] Short decimal should memcpy int64 data to arrow int128

---

cpp/velox/benchmarks/ColumnarToRowBenchmark.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxColumnarToRowConverter.cc
cpp/velox/compute/VeloxParquetDatasource.cc
cpp/velox/compute/VeloxRowToColumnarConverter.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/jni/JniWrapper.cc
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/memory/VeloxMemoryPool.cc
cpp/velox/memory/VeloxMemoryPool.h
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/tests/ArrowToVeloxTest.cc
cpp/velox/tests/ColumnarToRowTest.cc
cpp/velox/tests/VeloxColumnarToRowTest.cc
cpp/velox/tests/VeloxRowToColumnarTest.cc
cpp/velox/tests/VeloxShuffleWriterTest.cc

Velox main change list:
* Refactor UnsafeRowDynamicSerializer.h/UnsafeRowSerializer.h. like remove deserializeComplex function and UnsafeRowDynamicVectorBatchDeserializer class in https://github.com/facebookincubator/velox/pull/4612 and https://github.com/facebookincubator/velox/pull/4610.
* Refactor memory pool related api.  replace `addChild` with `addAggregateChild` and `addLeafChild` in https://github.com/facebookincubator/velox/pull/4629.
* change a little for kPreferredOutputBatchSize config in  https://github.com/facebookincubator/velox/pull/4439.

[VL] Upgrade velox to 2023/4/20

---

.github/workflows/velox_be.yml

This patch adds a job for Spark 3.3 w/ Ubuntu 22.04 in Velox backend testing matrix
Fixes: #1458 
pass GHA

[GLUTEN-1458][VL][CI]feat: Adding Spark3.3 w/ Ubuntu22.04 test

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

Set a config for velox to correct the cast behavior. The config is newly introduced in a velox patch: https://github.com/oap-project/velox/pull/215
UT.

[GLUTEN-1474][VL][Fix] Align with spark's cast behavior by allowing decimal

---

cpp/core/jni/JniWrapper.cc

`HINT: Throw an exception in destructor is dangerous and you should never let the exception leave destructors. If there are two exceptions propagating, the program will terminate or yield undefined behavior.`
inside function Java_io_glutenproject_vectorized_ShuffleReaderJniWrapper_make
1. we new object of JavaInputStreamAdaptor
2. we new object of Reader, and constructor of Reader throw an exception
3. inside JNI_METHOD_END, we will catch this exception
But between step2 and step3, destructor of JavaInputStreamAdaptor is called, then we got another exception, the process terminate.
(Fixes: #1199)

[GLUTEN-1199] Avoid throwing exception from destructor of JavaInputStreamAdaptor

---

cpp/velox/compute/WholeStageResultIterator.cc

Adjust some configurations for outputBatchRows function to guarantee the return value is close to 4K.
https://github.com/oap-project/velox/blob/main/velox/exec/Operator.cpp#L291-L313
Jenkens tpch/tpcds test.
Tpch    1406.02 -> 1355.66
Tpcds  1964.01 -> 1955.21

[VL] Adjust batch size to 4096

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
docs/Configuration.md
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettings.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenRemoveRedundantSorts.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Spark will plan a sort agg for string type input. We are proposing to replace sort agg with gluten hash agg. And a config will determine whether to do the replacement.
In this pr, sort op prior to sort agg is removed, considering it is not needed for hash agg. Vanilla spark has a rule named `RemoveRedundantSorts` applied before columnar rule to remove redundant sorts. So removing sort op in columnar rule can cause some potential issues. That's why we disabled spark's `RemoveRedundantSorts` and introduced a new rule named `GlutenRemoveRedundantSorts` to be applied after columnar transform overrides.
Currently, this functionality is only enabled for velox backend.
`SELECT max(str_col) from t1`, the DAG has the below changes:
After:

[GLUTEN-1533][VL][Feat] Replace sort agg with gluten hash agg

---

cpp/core/CMakeLists.txt
cpp/core/benchmarks/CompressionBenchmark.cc
cpp/core/benchmarks/ShuffleSplitBenchmark.cc
cpp/core/compute/Backend.h
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/ArrowShuffleWriter.cc
cpp/core/shuffle/ArrowShuffleWriter.h
cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/LocalPartitionWriter.h
cpp/core/shuffle/PartitionWriterCreator.cc
cpp/core/shuffle/PartitionWriterCreator.h
cpp/core/shuffle/ShuffleWriter.h
cpp/core/shuffle/rss/CelebornPartitionWriter.cc
cpp/core/shuffle/rss/CelebornPartitionWriter.h
cpp/core/shuffle/rss/RemotePartitionWriter.cc
cpp/core/shuffle/rss/RemotePartitionWriter.h
cpp/core/shuffle/type.h
cpp/core/tests/ArrowShuffleWriterTest.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc

1. Change SplitOptions to ShuffleWriterOptions.
2. Remove num_partitions from PartitionWriter's constructor, and add NumPartitions() function in ShuffleWriter.
3. Add parent class RssClient for CelebornClient to support clients of multiple RSS engines.
4. Remove celeborn_client in ShuffleWriterOptions, and add PartitionWriterCreator to receive instantiated RssClient.

[GLUTEN-1205][VL][FOLLOWUP] Refactor shuffle partition writer

---

tools/gluten-te/centos/centos-7-deps.sh

* Change centos 7 mirror to https://mirrors.edge.kernel.org/centos
* Disable yum plugin fastestmirror because it does not work properly on our server

[VL] CI: Update mirror of CentOS 7

---

cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/libch-hide-jemalloc.map
cpp-ch/local-engine/libch.map

This is folloup of https://github.com/oap-project/gluten/pull/1517,  I use `-Wl,--exclude-libs` which is cumbersome. In this PR, I use `--version-script` to limit exported symbols. only JNI  and jemalloc symbols are exported by default.
https://github.com/oap-project/gluten/issues/1585 is fix by disabling  jeamlloc(ENABLE_JEMALLOC = OFF),  and then preload it if needed. Please node with https://github.com/ClickHouse/ClickHouse/pull/45226, we also need preload libch.so whatever jemallloc is used or not, otherwise please use `ENABLE_GWP_ASN=OFF`
using existed UT

[GLUTEN-1585][CH]feat: Use --version-script to limit export symbols

---

dev/vcpkg/setup-build-depends.sh

vcpkg setup-build-depends.sh add alinux3 support.
test in alinux3 image.

[GLUTEN-1306][FOLLOWUP]vcpkg setup script add alinux3 support

---

gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala

Some function will have same window column name, but their result are different, such as first(expr) and first(expr, true).

[GLUTEN-CORE] [VL] Avoid duplicate window column name

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHValidatorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxTransformerApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxValidatorApi.scala
ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendsApiManager.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ValidatorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/WindowFunctionsBuilder.scala
gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenValidatorApi.scala
gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala

Use Spark's function name for substrait function mapping if some function has not supported by substrait.
Each backend should add their own expression mapping by itself.
Remove validateAggregateFunction method, it could be validated in expression.
Fixes: #1543

[GLUTEN-1543] Use Spark's function name for substrait mapping if not supported by substrait

---

.github/workflows/velox_be.yml
dev/vcpkg/vcpkg.json
ep/build-arrow/src/get_arrow.sh

* vcpkg: Add xxhash for velox tests (in gluten repo)
* Patch symbols.map for parquet to hide depends
This patch closes: #1617 
``` bash
source ./dev/vcpkg/env.sh
./dev/buildbundle-veloxbe.sh --build_type=Release \
--build_tests=ON --build_benchmarks=ON --enable_s3=ON --enable_hdfs=ON \
--enable_ep_cache=ON
```

[GLUTEN-1617][VL] Fix static build cpp unit tests

---

cpp/velox/CMakeLists.txt

Set SYSTEM_LIB_MULTIARCH_PATH to /usr/lib/aarch64-linux-gnu for ARM build. If it's not set, some libraries like re2 cannot be found.

[Minor] Auto set system arch library path

---

gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

In query tests, adjust double epsilon from 0.00001 (literally) to 0.001%
In expression tests, add 0.001% as double epsilon

[VL] In unit testing, optimize diff tolerance for doubles

---

cpp/velox/CMakeLists.txt

Header Search Paths do not include the complete velox directory during development

[GLUTEN-1690][VL] Header Search Paths do not include the complete velox directory during development

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala
gluten-core/src/main/scala/io/glutenproject/utils/FallbackUtil.scala

Support judging whether the execution plan has a fallback
UT

[GLUTEN-1640] Support judging whether the execution plan has a fallback

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxSparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
gluten-core/src/main/scala/io/glutenproject/expression/ArrayExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenValidatorApi.scala
gluten-data/src/main/scala/io/glutenproject/execution/GlutenHashAggregateExecTransformer.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala

Support asinh, acosh, atanh, sec, csc math functions for Velox backend.
Extract expression constant name from ExpressionMappings to remove hardcoded name in shims.
Fixed #1623

[GLUTEN-1623] [VL] Support asinh, acosh, atanh, sec, csc math functions for Velox backend

---

ep/build-arrow/src/get_arrow.sh
ep/build-velox/src/get_velox.sh

Follow-up to https://github.com/oap-project/gluten/pull/1660
Why doing this is not over-engineering (correct me if I am wrong):
1. It makes the checkout code 100% same with the checkout code in get_velox.sh. 
2. It fixes a bug when changing to another tag (e.g `ARROW_BRANCH=apache-arrow-13.0.0`), say if we upgrade to `apache-arrow-13.0.0`, `apache-arrow-12.0.0` will be wrongly kept and used without any message reported, simple to reproduce.

[VL] Make git checkout script in get_arrow.sh use an unique local tag name

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenStringExpressionsSuite.scala

Spark has a fix for ascii function. Since it is more like a bug fix in spark, we are proposing to align the imp. Spark 3.2.2 users should expect the behavior is consistent with spark 3.2.3 for characters whose ascii is above 127. 
UT.

[GLUTEN-1714][VL][Fix] Align the implementation for ascii func with latest spark

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

dependency https://github.com/oap-project/velox/pull/263

[VL] Result mismatch with vanilla Spark SQL on atan2

---

cpp/velox/compute/WholeStageResultIterator.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Pass `spark.gluten.sql.columnar.maxBatchSize` to native.
Fixes https://github.com/oap-project/gluten/issues/1772.
under test

[GLUTEN-1772] Pass batch size to native

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Enable tests on casting from string to decimal.
Depends on: https://github.com/oap-project/velox/pull/281.
https://github.com/oap-project/gluten/issues/1478
Testing on CI.

[GLUTEN-1478][VL] Enable tests on casting from string to decimal

---

backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderUbuntu2004.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxSharedlibraryLoaderUbuntu2204.scala
dev/package.sh

This pr make `dev/package.sh` collect libthrift and load it using java.
(Fixes: \#1812)
manually test

[GLUTEN-1812][VL] package missing libthrift.so into jar on Ubuntu20/22

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

(Fixes: \#1767)
posexplode in clickhouse backend will make the convert: 
posexplode(array_or_map) -> CH: arrayJoin(map), in which map = mapFromArrays(range(length(array_or_map)), array_or_map)
But somethimes in mapFromArrays the second argument type is nullable, which can not pass the arugment check.
And when use the posexplode function to transfrom value from a map, like posexplode(split(map['key'], ',')), in clickhosue backend will  use the arrayElement function to extract the map value, and it would force the convert the key argument to UInt32, and this also will be check as illegal argument .
unit tests

[GLUTEN-1767][CH]Bug fix posexplode function argument check error

---

cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

This pr fix that if the current block is empty, it should return false for hasNext.
(Fixes: \#1682)
This patch was tested manually.

[GLUTEN-1682] [CH] fix hasNext will always be true if input is empty

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/RowToCHNativeColumnarExec.scala

Fix error convert time statistics for RowToCHNativeColumnarExec
Close #1826 .
(Fixes: #1826)

[GLUTEN-1826][CH] Fix error convert time statistics for RowToCHNativeColumnarExec

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Fix failed UTs in PredicateSuite, including LessThan, LessThanOrEqual, GreaterThan, GreaterThanOrEqual, "SPARK-32764: compare special double/float values".
UT

[GLUTEN-1478][VL][Fix] fix compare function UT in spark3.2

---

backends-clickhouse/pom.xml
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/metrics/HiveTableScanMetricsUpdater.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/hive/CHHiveTableScanExecTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/JsonFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/JsonFormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/scala/io/glutenproject/backendsapi/MetricsApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/HiveTableScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-data/src/main/scala/io/glutenproject/backendsapi/glutendata/GlutenMetricsApi.scala
gluten-data/src/main/scala/io/glutenproject/metrics/HiveTableScanMetricsUpdater.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
shims/common/src/main/scala/io/glutenproject/sql/shims/SparkShims.scala
shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala

Improve read txt/json format hive table by use native engine 
(Fixes: \#1582)
unit tests, manual tests
This is tested on clickhouse-backend. The tested query  `select l_linenumber,count(*) from linenumber_t where l_linenumber <3   group by l_linenumber limit 3` , the tested table has about 63000000 rows, and stored as textfile, which archived about 100% improvement.

[GLUTEN-1582][CH] Improve txt/json read by use native engine

---

cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Parser/SparkRowToCHColumn.cpp

Refer to https://github.com/ClickHouse/ClickHouse/pull/11668, let's initialize `GlobalThreadPool` at process startup to avoid race. 
`BackendInitializerUtil::init` is called when `Dirver` and `Worker`  initialize Plugin which is at process startup
(Fixes: \#1817)
Uisng existed UTs

[GLUTEN-1817][CH] Fix: Initialize global thread pool at backend initalization

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/expression/JsonTupleExpressionTransformer.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

Support json_tuple funtion for spark in clickhouse backend， the related pr: https://github.com/Kyligence/ClickHouse/pull/361
test by unit test

[CH] Support json_tuple function

---

cpp/core/compute/Backend.cc
cpp/core/compute/Backend.h
cpp/core/tests/BackendTest.cc
cpp/velox/benchmarks/BenchmarkUtils.cc
cpp/velox/compute/VeloxInitializer.cc
cpp/velox/compute/VeloxInitializer.h
cpp/velox/jni/JniWrapper.cc

in the function of `Java_io_glutenproject_init_InitializerJniWrapper_initialize`, we save the return value of `gluten::getConfMap()` to static global variable sparkConfs.
it's wrong because two calls will overwrite the previous `sparkConfs`.
so, `setBackendFactory` should keep the both of the factory method and sparkConfs

[VL] refactor setBackendFactory

---

cpp/CMake/BuildGTest.cmake
cpp/CMake/BuildGoogleBenchmark.cmake
cpp/CMake/ConfigArrow.cmake
cpp/CMakeLists.txt
cpp/compile.sh
cpp/velox/CMakeLists.txt
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh

In Ubuntu, thrift will be installed manually in setup scripts, but Arrow still compile thrift, then Velox use system thrift and pre-build arrow/parquet.
In Centos, Velox could not found system thrift, so it will compile Arrow and thrift twice.
Since Arrow will compile thrift in all environments, lets use these pre-build shared libs to save time and keep toolchain consistency.
Support native dependency could be overrided by env variables.

[VL][BUILD] Fix use pre-build arrow/parquet/thrift lib

---

gluten-core/src/main/java/io/glutenproject/substrait/type/StructNode.java
gluten-core/src/main/java/io/glutenproject/substrait/type/TypeBuilder.java
gluten-core/src/main/resources/substrait/proto/substrait/type.proto
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenStatisticsCollectionSuite.scala

In Velox, field names are used in native struct reader, and getStructField. This PR added names field in Substrait struct type.
Depends on: https://github.com/oap-project/velox/pull/297.
#1476
Testing on CI.

[GLUTEN-1476][CORE] Use correct field name in struct type

---

.github/workflows/velox_be.yml
dev/get_spark_env.sh

This patch moved Spark 3.3 unit tests to a seperate job to speed up GHA
Pass GHA

[GLUTEN-1336][VL] move Spark3.3 Unit tests to seperate job

---

cpp-ch/local-engine/Builder/BroadCastJoinBuilder.cpp
cpp-ch/local-engine/Storages/StorageJoinFromReadBuffer.cpp
cpp-ch/local-engine/Storages/StorageJoinFromReadBuffer.h

This PR has two purposes:
1. This is part of https://github.com/oap-project/gluten/pull/1873, that PR is quite complex, and needs some time to verify.
2. Also, we need this pr to avoid building error due to https://github.com/ClickHouse/ClickHouse/pull/50663, so that gluten can reduce dependency.
Using existed UT.

[GLUTEN-1871][CH] Refactor: StorageJoinFromReadBuffer doesn't inherit from StorageSetOrJoinBase any more.

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This pr adds a new rule `PlanOneRowRelation` which inject a fake schema for `OneRowRelation`. As gluten does not support work with empty output relation.
BTW, if we want to validate data result with vanilla spark and gluten, please disable constant folding
`set spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConstantFolding`
(Fixes: \#1858)
add test

[GLUTEN-1858][CORE] Add PlanOneRowRelation to make gluten work with OneRowRelation

---

gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala

In this MR, I proposed the following two changes to improve subquery performance. 
1.  In `WholeStageTransformerExec.doWholestageTransform`, invoke `SparkPlan.prepare` to trigger Subquery execution concurrently before we do expression transform.
2. don't trigger Subquery execution when do native validation
Currently, subquery is supported in `ScalarSubqueryTransformer.doTransform`, by invoking `ScalarSbuquery.plan.executeCollect`, which will block the whole code path before the subquery really returns.
But in vanilla spark, subquery is submitted concurrently in `SparkPlan.prepare`，so that we can fully utilize spark cores.
Take TPC-DS Q9 as an example,
vanilla spark submits subquery calculation concurrently, 
while gluten submits subquery one by one
It's tested against TPC-DS 1T Q9
before …

[CORE] Support submit subqueries concurrently to improve scalar subquery performance

---

tools/gluten-te/centos/centos-7-deps.sh
tools/gluten-te/centos/dockerfile-buildenv

This patches fixes the Centos7 job by using a new mirror from: https://mirrors.ustc.edu.cn/centos
Pass GHA

[VL] Minor: fix centos job by using new mirror

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecHandler.scala
backends-velox/src/main/scala/io/glutenproject/expression/ExpressionTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
ep/build-velox/src/get_velox.sh
gluten-core/src/main/java/io/glutenproject/substrait/expression/SelectionNode.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/expression/StructExpressionTransformer.scala

Support GetStructField on Velox backend.
https://github.com/oap-project/velox/pull/294
https://github.com/oap-project/gluten/issues/1476
under test

[GLUTEN-1476][VL] Support GetStructField

---

ep/build-arrow/src/build_arrow.sh

At present, the open source version of arrow directly used by gluten, the arrow-c-data in the maven repo only includes x86 windows/linux/macOS and aarch64 macOS lib, aarch64 linux still needs to run the arrow-c-data install process.
test in aarch64 linux

[VL]Fix aarch64 linux arrow-c-data jni lib missing

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.h
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

Fix fallback when executing window function: lead, lag, stddev and so on:
Currently, when executing window functions: lead, lag, it will fallback to vanilla spark, because the functions lead, lag miss in `ExpressionMappings`, and `WindowFunctionsBuilder.create` will return empty when getting function mappings by the lead, lag function name.
Close #1910.
(Fixes: #1910)

[GLUTEN-1910][CH] Fix fallback when executing window function: lead, lag and so on

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/BlockOutputStream.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHBlockWriterJniWrapper.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeBlock.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarToRowExec.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala

We may encounter the failure of converting ColumnarBatch to CHNativeBlock in rare cases, but we are unable to obtain more meaningful error info when it occurs. I think we can early throw exception with more meaningful info in the situation.

[CH] Early throw exception if ColumnarBatch can't convert to CHNativeBlock

---

backends-clickhouse/pom.xml
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHBroadcastBuildSideCache.scala
gluten-core/pom.xml
gluten-core/src/main/scala/org/apache/spark/rpc/GlutenDriverEndpoint.scala
gluten-ut/common/src/test/resources/log4j.properties
gluten-ut/common/src/test/resources/log4j2.properties
pom.xml

This PR follow ups https://github.com/oap-project/gluten/pull/1873.  
From https://github.com/google/guava/issues/2131, it recommends using caffine cache instead of guava cache, we meet the same issue  that `LoadingCache.getIfPresent(key) returns null` while `get` already return a vlaue.
I also add `log4j(2). properties` for dump `CHBroadcastBuildSideCache`'s debug meessage.
(Fixes: \#1918)
Using existed UT.

[GLUTEN-1918][Core]Fix: Using Caffeine cache instead of guava cache

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala
cpp/core/compute/Backend.h
cpp/core/jni/JniWrapper.cc
cpp/core/operators/c2r/ArrowColumnarToRowConverter.cc
cpp/core/operators/c2r/ArrowColumnarToRowConverter.h
cpp/core/operators/c2r/ColumnarToRow.h
cpp/velox/benchmarks/ColumnarToRowBenchmark.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxColumnarToRowConverter.cc
cpp/velox/compute/VeloxColumnarToRowConverter.h
cpp/velox/tests/ColumnarToRowTest.cc
cpp/velox/tests/VeloxColumnarToRowTest.cc
cpp/velox/tests/VeloxRowToColumnarTest.cc
gluten-data/src/main/java/io/glutenproject/vectorized/NativeColumnarToRowInfo.java
gluten-data/src/main/java/io/glutenproject/vectorized/NativeColumnarToRowJniWrapper.java
gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala

This PR make all the ColumnarBatch in one partition to use same buffer as much as possible.
https://github.com/oap-project/gluten/issues/1868

[GLUTEN-1868][VL] Optimize ColumnarToRow to reuse the allocated Buffer in native side.

---

ep/build-arrow/src/build_arrow.sh

Add quotes out side CPU_TARGET variable to avoid warining if CPU_TARGET is empty string.

[VL] Add quotes for CPU_TARGET to avoid warning

---

gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpressionExtensionTrait.scala
gluten-core/src/main/scala/org/apache/spark/sql/utils/ExpressionUtil.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/CustomerExpressionTransformer.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExpressionTransformerSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Support to add the custom expressions transformer by Spark conf: Add a spark.gluten.sql.columnar.extended.expressions.transformer to specify the extended expression transformer class;
Close #1928.
(Fixes: #1928)

[GLUTEN-1928][Core] Support to add the custom expressions transformer by Spark conf

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
cpp-ch/local-engine/Common/CHUtil.cpp
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

[GLUTEN-1897][CH] Respect hdfs-site.xml configs for clickhouse libhdfs3

---

dev/package.sh
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh

Pop!_OS is a variant of Ubuntu, it shares most of the libs and version of Ubuntu, with additional GUI-enhanced libs.
```
➜ $ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
manual tests with command `dev/buildbundle-veloxbe.sh`

[VL][BUILD] Pop!_OS as Ubuntu alias

---

cpp/core/compute/Backend.h
cpp/core/jni/JniWrapper.cc
cpp/core/memory/ArrowMemoryPool.cc
cpp/core/memory/ArrowMemoryPool.h
cpp/core/shuffle/type.h
cpp/velox/benchmarks/ColumnarToRowBenchmark.cc
cpp/velox/benchmarks/ParquetWriteBenchmark.cc
cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/ArrowTypeUtils.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxInitializer.cc
cpp/velox/compute/VeloxInitializer.h
cpp/velox/compute/VeloxParquetDatasource.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/jni/VeloxJniWrapper.cc
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/memory/VeloxMemoryPool.cc
cpp/velox/memory/VeloxMemoryPool.h
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/tests/ArrowToVeloxTest.cc
cpp/velox/tests/ColumnarToRowTest.cc
cpp/velox/tests/VeloxColumnarToRowTest.cc
cpp/velox/tests/VeloxRowToColumnarTest.cc
cpp/velox/utils/VeloxArrowUtils.cc

1. refactor WrappedVeloxMemoryPool, rename `WrappedVeloxMemoryPool` to `VeloxMemoryPool`, the class's new name is consistent with the file name.
3. rename `getDefaultVeloxAggregateMemoryPool` to `rootVeloxMemoryPool`, and replace it in the source file.
4. give the related `APIs` more meaningful names.
5. call `log()` in `VeloxInitializer::init()` to record startup information.
6. delete `resultLeafPool` of `WholeStageResultIterator`, it's unnecessary to do this. 

[VL] Refactor VeloxMemoryPool and VeloxInitializer

---

ep/build-clickhouse/src/package.sh

Add -am param in the step of maven build shim/spark33 to avoid lack of dependency.
(Fixes: \#1957)

[GLUTEN-1957][CH] Add -am param to build dependent modules of shims/spark33

---

backends-velox/src/main/java/io/glutenproject/spark/sql/execution/datasources/velox/DatasourceJniWrapper.java
backends-velox/src/main/scala/io/glutenproject/utils/DatasourceUtil.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetFileFormat.scala
backends-velox/src/main/scala/org/apache/spark/sql/hive/execution/HiveFileFormat.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetWriteSuite.scala
cpp/core/jni/JniWrapper.cc
cpp/velox/compute/VeloxParquetDatasource.cc
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-data/src/main/java/io/glutenproject/init/JniInitialized.java
gluten-data/src/main/java/io/glutenproject/init/JniUtils.java

There are some issues for parquet write:
1. the default compression codec should be snappy, but is is uncompression now
2. the compression codec does not respect the user-specified, e.g., `df.write.option('compression', 'zstd').save`
3. the parquet file name does not contain the compression codec
(Fixes: \#1947)
This pr pass the write options to native so that velox can take user-specified conf to write parquet. So far, we only support compression codec and block size.
Besides, this pr add all supported compression codec test
add tests

[GLUTEN-1947][VL] Parquet should respect user-specified write options

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpressionExtensionTrait.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/CustomerExpressionTransformer.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/GlutenCustomerExpressionTransformerSuite.scala

Support to add the custom expressions transformer by Spark conf:
Add a spark.gluten.sql.columnar.extended.expressions.transformer to specify the extended expression transformer class;
(Fixes: #1928)

[GLUTEN-1928][Core] Followup: fix the custom expressions transformer ut bug

---

cpp/velox/compute/VeloxInitializer.cc
cpp/velox/compute/VeloxInitializer.h

The conf passed in VeloxInitializer could contains some sensitive informations, such as cloud storage AK/SK, we should not print these infos by default.

[VL] Avoid print conf in default situation

---

cpp/core/memory/HbwAllocator.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/velox/memory/VeloxMemoryPool.cc

some SIMD instructions (xmovdqa...) need work at the start address of 16B aligned, otherwise, crash.
After this modification, allocating operations will keep consistency with the `velox::MallocAllocator::allocateBytes、allocateZeroFilled`.
the corresponding `oap-project/velox` [PR](https://github.com/oap-project/velox/pull/317)

[VL] fix the crash problem caused by SIMD instructions execution

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenArithmeticExpressionSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Scan on struct and map types are enabled with below limitations:
- Parquet scan of nested map with struct as key type is not supported in Velox (fallback).
- Merge schema option is not supported (fallback).
- Schema pruning is not supported in Velox struct reader (tests disabled).
Depends on: https://github.com/oap-project/velox/pull/290.
\#1476
Testing on CI.

[GLUTEN-1476][VL] Enable scan on struct and map types

---

cpp/core/memory/HbwAllocator.h
cpp/core/memory/MemoryAllocator.cc
cpp/core/memory/MemoryAllocator.h
cpp/velox/memory/VeloxMemoryPool.cc

Reverts oap-project/gluten#1990
@zuochunwei This causes 2% performance regression on a daily TPC-H job. Let's revert and investigate.
Thanks @rui-mo for doing the benchmark.

Revert "[VL] fix the crash problem caused by SIMD instructions execution"

---

dev/gluten-build-info.sh
gluten-core/pom.xml
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendsApiManager.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/BinaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/DateTimeExpressionsTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/MapExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/QuaternaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/TernaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/glutenproject.scala
gluten-core/src/main/scala/org/apache/spark/rdd/EmptyRDD.scala
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/benchmarks/ParquetReadBenchmark.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/joins/GlutenBroadcastJoinSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/joins/GlutenBroadcastJoinSuite.scala
package/pom.xml
pom.xml

The build info is important that there is no stable version now. It can help developer find the binary is from which git commit.
```
======================================
Gluten build info:
Gluten version: 0.5.0-SNAPSHOT
GCC version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Java version: 1.8.0_362
Scala version: 2.12.15
Spark version: 3.3.1
Hadoop version: 2.7.4
Build branch: build-info
Build revision: 0e21fe8a96ff16973436a1b094e5c50be7c19a52
Build revision time: 2023-06-15 20:02:22 +0800
Build date: 2023-06-15T12:03:39Z
Velox branch: main
Velox revision: f258c6f8e2b8efa7a55a811151715cadd9cf50c3
Velox revision time: 2023-05-30 11:23:21 +0800
======================================
```
(Fixes: \#1972)
manually test

[GLUTEN-1972][CORE] Log gluten build info

---

pom.xml

This patch upgrades guava to 32.0.1-jre to fix the security issue
Pass GHA

Minor: upgrade guava to 32.0.1-jre

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashJoinExecTransformer.scala
backends-clickhouse/src/main/scala/io/glutenproject/utils/CHJoinValidateUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSParquetSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/extension/StrategyOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

Is your feature request related to a problem or challenge? Please describe what you are trying to do.
In our custom JoinSelectionOverrides rule, if forceShuffledHashJoin is set to true, SortmergeJoin will be converted to ShuffledHashJoin regardless of whether the backend supports it or whether it is fallback. If it is executed in spark in the case of falllback, SortmergeJoin will be converted For ShuffledHashJoin, it will take up more memory, resulting in OOM,
Describe the solution you'd like
avoid forceShuffledHashJoin when the join condition does not supported by the backend

[GLUTEN-1985] avoid forceShuffledHashJoin when the join condition does not supported by the backend

---

backends-clickhouse/src/main/scala/org/apache/spark/sql/hive/CHHiveTableScanExecTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
cpp-ch/local-engine/Storages/SubstraitSource/JsonFormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.h
docs/get-started/ClickHouse.md
gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java

code changes: 
- support column case-insensitive matching for hive text format file
- fix bug when select complex type columns from hive text table: it is expected to fallback, but actually not as expected. 
- fix bug: select count(1) from hive text table returns wrong results
- improve function adjustFileReadStartAndEndPos
(Fixes: \#1975)
``` sql 
create table if not exists test_text (string_field string,int_field int,long_field long,float_field float,double_field double,short_field short,byte_field byte, bool_field boolean, decimal_field decimal(23, 12), date_field date, array_field array<int>, array_field_with_null array<int>, map_field map<int, long>, map_field_with_null map<int, long>) stored as textfile; 
insert into test_text select
cast(id as String), 
cast(id as int), 
cast(id as …
```

[GLUTEN-1975][CH] hive text format case-insensitive column matching  

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala

Remove the unused `VeloxColumnarToRowExec` that's causing `Task not serializable` errors.
```
Caused by: org.apache.spark.SparkException: Task not serializable
at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:444)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:416)
at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:163)
at org.apache.spark.SparkContext.clean(SparkContext.scala:2578)
at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$1(RDD.scala:860)
...
Caused by: java.io.NotSerializableException: com.palantir.sls.logging.log4j.slf4j.SlsLog4jSlf4jLogger
Serialization stack:
- object not serializable (class: com.palantir.sls.logging.log4j.slf4j.SlsLog4jSlf4jLogger, value: …
```

[GLUTEN-1983][VL] Fix serialization errors by removing unused VeloxColumnarToRowExec.LOG

---

dev/package.sh

Followup for #1943
before:
```
+ '[' ubuntu == ubuntu
./dev/package.sh: line 38: [: missing `]'
+ ubuntu == pop ']'
./dev/package.sh: line 38: ubuntu: command not found
```
after
```
+ [[ ubuntu == \u\b\u\n\t\u ]]
```
manually test

[GLUTEN-1943][FOLLOWUP] Fix package.sh

---

.github/workflows/velox_be.yml

After this PR, we only keep Spark3.2.2 and Spark3.3.1 in CI.

[VL][CI] Only keep Spark32/Spark33 CI with default version

---

.github/workflows/velox_be.yml
cpp/velox/CMakeLists.txt
cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/RegistrationAllFunctions.cc
cpp/velox/memory/VeloxMemoryPool.cc
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala

Due to the performance fallback of [PR 1732](https://github.com/oap-project/gluten/pull/1732).I decided to merge the parts that do not affect performance first.
Velox Update list
```
300370fd9 Add timezone_hour Presto function (#4520)
c12534290 Implement decimal comparisons as vector functions (#4638)
df927bd12 Updating submodules
0161d3ff1 Refine StringIdMap::makeId (#4684)
f33ba3a8e Replace find_library with find_package (#4689)
af1c49da4 Suppress errors for unused arguments of null-propagating functions (#3189)
e670ee705 Fix enable sparksql aggregate compile config in CmakeList (#4658)
185f1a40b Updating submodules
c748c8d35 Updating submodules
e2e235b8d Add "running*WallNanos" operator runtime metrics. (#4646)
0ada6a05f Updating submodules
cc6a58bd2 Fix a flaky test …
```

[VL] Update velox to 300370fd9

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetFileFormat.scala
backends-velox/src/main/scala/org/apache/spark/sql/hive/execution/HiveFileFormat.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetWriteSuite.scala
cpp/core/config/GlutenConfig.h
cpp/velox/compute/VeloxParquetDatasource.cc
cpp/velox/compute/VeloxParquetDatasource.h
ep/build-velox/src/get_velox.sh
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Velox parquet write would build row groups for each columnar batch, which causes a lot of small row groups. We can cache columnar batch to make a bigger one.
This pr adds a new option `parquet.block.rows` to control the numRows of one row group.
The velox related code change see https://github.com/oap-project/velox/pull/326
(Fixes: \#2038)
improve test and manually test:
```
spark.range(1000000).write.format("velox").mode("overwrite").option("compression","zstd").save("/opt/parquet/test")
java -cp 'parquet-tools-1.11.1.jar:spark-3.3.1/jars/*' org.apache.parquet.tools.Main meta /opt/parquet/test/part-00000-478ee552-27da-4dc9-9168-6af5303a983d-c000.zstd.parquet
file schema: schema
--------------------------------------------------------------------------------
id:          REQUIRED INT64 …
```

[GLUTEN-2038][VL] Improve parquet write using arrow chunked array

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/StorageJoinBuilder.java
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-clickhouse/src/main/scala/io/glutenproject/utils/PlanNodesUtil.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ClickHouseAppendDataExec.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala

(Fixes: \#2028)
* fix `parseNameStruct` error since there are some places where the schema does not include struct nested fields, e.g. `StorageJoinBuilder`.
* refactor the code related to `collectStructFieldNames`, because the method is implemented in multi places (`RelBuilder` and `BasicScanExecTransformer`), I unify them  in ConverterUtils.
unit tests

[GLUTEN-2028][CH] Fix `parseNameStruct` error and refactor code related to `collectStructFieldNames`

---

gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsTrait.scala

This is a minor fix, Renaming **"Spark Answer"** to **"Gluten Answer"** to avoid confusion.
Existed UT

[UT] Rename "Spark Answer" to "Gluten Answer"

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetWriteSuite.scala
docs/VeloxNotSupport.md
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenColumnarRules.scala

This pr does two things:
- Forbid velox write with ctas. It can be supported in Spark3.4
- Forbid velox dynamic partition and bucket write. As mentioned at https://github.com/oap-project/gluten/issues/2042, it would fail if we use dynamic partition write with velox. There is a lot of work need to be done. This pr just throw exception in advance when contains partition or bucket.
add test

[VL] Forbid unsupported write using velox

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

When scan a hive txt table, HiveTableScanExecTransformer would get partitions use FileIndex, In the implements, the implementation is InMemoryFileIndex. If no partition spec defined, it would inter partitions by itself, and validate the partition columns, if the partition path is illegal, such as `hdfs://testcluster/abc/_temp_day=20221106abcwda11`, the exception will throws, and the query will be failed.
So here we defined the partition spec first in InMemoryIndex, which will fiter the dirty partitons like above
(Fixes: \#1843)
unit tests

[GLUTEN-1843][CH]Bug fix for HiveScanExecTransformer infer dirty partitions

---

cpp/velox/compute/VeloxInitializer.cc

Decouple S3 endpoint/ssl.enabled/path-style-access config from AK/SK since they are common configs.
(Fixes: \#2125)
manual tests

[GLUTEN-2125][VL] Decouple S3 endpoint/ssl.enabled/path-style-access config from AK/SK

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
ep/build-velox/src/get_velox.sh
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Enable scan on array type.
Depends on: https://github.com/oap-project/velox/pull/320.
under test

[GLUTEN-1476][VL] Enable scan on array type

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
gluten-core/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala

fix compare result with partially unstable sort, like TCPH Q20, TPCDS Q31, Q71
(Fixes: \#1763)

[GLUTEN-1763] fix compare result with partially unstable sort

---

cpp/CMakeLists.txt
cpp/core/CMakeLists.txt
cpp/velox/CMakeLists.txt

Currently, gluten cpp use relative path for VELOX_HOME, ARROW_HOME and proto_directory. Doing so has no problem with cmake compilation, but it will cause some IDEs (such as Jetbrains Clion) fail to correctly obtain the include files of velox, arrow, and proto, and the absolute path must be specified manually.
if this has no other effect, can we get rid of using relative path.
test compile cpp

[VL] Use get_filename_component to set absolute path for velox arrow proto

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionReinterpretAsString.cpp
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

`cast(xxx as binary)` is implemented to `reinterpretAsStringSpark` function in CH backend, `xxx` here is either StringType or IntegerType. 
When `xxx` is IntegerType, we need output reinterpreted bytes in big-endian order to align with spark. However, when it is  StringType, this step is not necessary.
(Fixes: \#2095)
unit tests

[GLUTEN-2095][CH] Fix the incorrect result of  cast(string as binary)

---

cpp/velox/shuffle/VeloxShuffleReader.cc
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

For small size ColumnarBatch, this batch will not be compressed, the buffer which origins from netty is aligned, but the actual buffer used in RecordBatch is SliceBuffer(buffer, offset, size), this buffer cannot guarantee align. SIMD instruction `movdqa` required the address 16B aligned, so it will core dump at velox function `copyValuesAndNulls` and left potential coredump. This copy is expensive but essential.
```
BufferReader::DoReadAt(int64_t position, int64_t nbytes) {
return SliceBuffer(buffer_, position, nbytes); // buffer_ is netty buffer
}
```
For most batch which is not tiny batch and compress codec use default lz4, shuffle read will decompress the buffer to an aligned address which meets SIMD instrictions requirement.
Relevant issue: …

[GLUTEN-1434] [VL] Fix shuffle read unalign buffer which origins from netty

---

ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Velox update list:
```
038f48cb Add timestamp with timezone to diff_add signature (#5166)
9cbee26a Ignore empty frames in window rank functions (#5161)
7f43495f Add DynamicRowView and its reader (#5075)
148676b1 Support Spark bin function (#4932)
f7b75403 Add more context to std::exceptions thrown by operators (#5159)
1fc8924c Add MarkDistinct operator (#4173)
b1fd455c Updating submodules
5127680a Updating submodules
6805f4f6 Add TopNRowNumber operator (#5110)
3163f168 Fix signatures for histogram Presto aggregate function (#5144)
1d720922 Add support for TIMESTAMP input to min_by and max_by Presto aggregates (#5149)
87441250 Remove updateBroadcastBuffers from broadcast output buffer manager (#5147)
7987ca6d Add May 2023 monthly update. (#5138)
88ec29ea Add fuzzer support for feeding …
```

[VL] Update velox to 2023.6.7

---

gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala

Enable fixed UTs in Spark3.3, which are already enabled in Spark32
CI/CD

[GLUTEN-1478][VL]enable fixed UTs for Spark3.3

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/Parser/AggregateRelParser.cpp
cpp-ch/local-engine/Parser/AggregateRelParser.h
cpp-ch/local-engine/Parser/FunctionParser.cpp
cpp-ch/local-engine/Parser/FunctionParser.h
cpp-ch/local-engine/Parser/RelParser.cpp
cpp-ch/local-engine/Parser/RelParser.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/Parser/WindowRelParser.cpp
cpp-ch/local-engine/Parser/WindowRelParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/CollectListParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/CollectListParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.h
cpp-ch/local-engine/Parser/aggregate_function_parser/LeadLagParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/LeadLagParser.h
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameAsOfJoinSuite.scala

Fixes:  #2090
1. aggregate functions are used both in `window` and `aggregate` steps. The usage is common. We need codes could be shared among both steps, keep the aggregate function behavior consistent and reduce duplication of codes.
2. Implement aggregate function parsers and manage them by already existing `FunctionParserFactory`. We make some adjustment to the `FunctionParser` to support aggregate functions.
unit tests

[GLUTEN-2090][CH] Refactor aggregate function parsing 

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala

(Fixes: \#2152)
Pass existed topk test

[GLUTEN-2152][CORE] Skip local sort if child output ordering satisfies topk

---

gluten-core/src/main/scala/io/glutenproject/execution/TakeOrderedAndProjectExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/ColumnarShuffleUtil.scala

Since https://github.com/oap-project/gluten/pull/2145, we removed `CoalesceBatch`. Then the flag `isAdaptiveContextOrTopParentExchange` has no affect any more.
Pass CI

[GLUTEN-1434][CORE][FOLLOWUP] Remove isAdaptiveContextOrTopParentExchange check

---

gluten-core/src/main/scala/io/glutenproject/execution/CoalesceExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ColumnarToRowExecBase.scala
gluten-core/src/main/scala/io/glutenproject/execution/RowToColumnarExecBase.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenFallbackReporter.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/adaptive/ColumnarAQEShuffleReadExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenColumnarRules.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala

The main change in this pr is:
1. Make all gluten plan inherit `GlutenPlan`, e.g., ColumnarToRowExec, RowToColumnarExec
2. Then we can add default fallback reason for all vanilla `SparkPlan`
(Fixes: \#2139)
add test

[GLUTEN-2139][CORE] Add default fallback reason

---

gluten-core/src/main/scala/io/glutenproject/expression/ScalarSubqueryTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarQueryStagePrepOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/extension/GlutenSessionExtensionSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/extension/GlutenSessionExtensionSuite.scala

This pr corrects and simplify: 
- remove rule `FallbackOneRowRelation` which has been covered by `FallbackEmptySchemaRelation`
- only inject `FallbackBroadcastExchange` to stage prep rule so that we can remove the wrong `tagBeforeTransformHitsRules `
Pass CI

[CORE] Correct and simplify stage prep rules

---

gluten-core/src/main/scala/org/apache/spark/util/SparkDirectoryUtil.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala

Port https://github.com/oap-project/gluten/pull/2249 to main. This will align the behavior of creating/deleting spill file dirs with Spark DiskBlockManager.

[VL] Use single parent dir for shuffle spill

---

cpp/velox/operators/serializer/VeloxColumnarToRowConverter.cc
ep/build-velox/src/get_velox.sh
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetIOSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetIOSuite.scala

This PR try to remove use the getRowVector instead of getFlattenedRowVector method to avoid the copy action.

[GLUTEN-1597][VL] Remove the columnar batch copy operator in VeloxColumnarToRow

---

gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala

Related to https://github.com/oap-project/gluten/issues/1141
We can ignore the comparison of exprId when only one attribute name match is found in output.
tpcds q31 3g

[GLUTEN-1141][FOLLOWUP][VL]Fix q31 join key not found

---

backends-velox/src/main/scala/io/glutenproject/utils/SharedLibraryLoaderCentos7.scala
dev/package.sh

Add lz4 library to 3rd party library jar for centos7
(Fixes: \#1700)
Tested in centos7.3

[GLUTEN-1700][VL] Add lz4 library to 3rd party library jar file

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/ExpressionEvaluatorJniWrapper.java
backends-clickhouse/src/test/scala/io/glutenproject/s3/S3AuthSuite.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Common/QueryContext.h
cpp-ch/local-engine/Common/common.cpp
cpp-ch/local-engine/local_engine_jni.cpp

Reverts oap-project/gluten#2204 for hdfs read problem:
java.lang.RuntimeException: bad_array_new_length
0. std::bad_array_new_length::bad_array_new_length() @ 0x0000000014a2ba2a in /home/ubuntu/[libch.so](http://libch.so/)
1. std::__throw_bad_array_new_length[abi:v15000]() @ 0x0000000006777976 in /home/ubuntu/[libch.so](http://libch.so/)
2. ? @ 0x00000000067795b4 in /home/ubuntu/[libch.so](http://libch.so/)
3. std::pair, void*>*>, bool> std::__hash_table, std::__unordered_map_hasher, std::hash, std::equal_to, true>, std::__unordered_map_equal, std::equal_to, std::hash, true>, std::allocator>>::__emplace_unique_key_args const&>(String const&, std::pair const&) @ 0x00000000067799e2 in /home/ubuntu/[libch.so](http://libch.so/)
4. std::unordered_map, std::equal_to, …

Revert "[GLUTEN-2199][CH] support dynamically configure per bucket roles"

---

docs/developers/SubstraitModifications.md
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
gluten-core/src/main/resources/substrait/proto/substrait/capabilities.proto
gluten-core/src/main/resources/substrait/proto/substrait/extensions/extensions.proto
gluten-core/src/main/resources/substrait/proto/substrait/function.proto
gluten-core/src/main/resources/substrait/proto/substrait/parameterized_types.proto
gluten-core/src/main/resources/substrait/proto/substrait/plan.proto
gluten-core/src/main/resources/substrait/proto/substrait/type.proto
gluten-core/src/main/resources/substrait/proto/substrait/type_expressions.proto

Record Substrait modifications and remove arena option.
(Fixes: \#2362)
Testing on CI.

[GLUTEN-2362][CORE] Record Substrait modifications and remove arena option

---

cpp/velox/jni/JniFileSystem.cc
cpp/velox/jni/JniFileSystem.h

We will implement the priority logic in C++ by `JniFileSystem `.
Three member functions `openFileForRead` `openFileForWrite` `rmdir` are implemented first, and I added the `TODO` marks for @zhztheplayer to implement.
could you have a look for me?

[VL] Support spill-to-heap first using JniFileSystem

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxParquetWriteSuite.scala
cpp/velox/operators/writer/VeloxParquetDatasource.cc
ep/build-velox/src/get_velox.sh

This PR pass the schema from java side to velox parquet writer and ensure the written parquet file has the right schema info.
(https://github.com/oap-project/gluten/issues/2394)

[GLUTEN-2394][VL]bug: fix wrong schema issue in velox parquet writer

---

cpp/velox/compute/WholeStageResultIterator.cc

According to spark's conversion from string to timestamp type, it will do a adjusting according to the session timezone. Here, we proposed to set a velox config which controls the adjust behavior.

[GLUTEN-2306] Enable adjusting timestamp according to the configured timezone

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
cpp-ch/local-engine/Shuffle/SelectorBuilder.h

`field_value.convert<DB::Float64>()` will fail when field_value is special value like NaN/Inf.
We check it and insert the corresponding value.
(Fixes: \#2422)
UT

[GLUTEN-2422][CH] Fix parse nan/inf exception in RangeSelectorBuilder

---

cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/ShuffleWriter.h
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleWriterJniWrapper.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Spark supports fetch the contiguous shuffle blocks in batch, which is enabled by default (by conf `spark.sql.adaptive.fetchShuffleBlocksInBatch`).  This feature has a big performance improvement in our production.
However, currently, since ColumnarBatchSerializer's `supportsRelocationOfSerializedObjects` return false, so that this feature cann't take effect. 
In fact, the arrow serialization does support reloation if we don't write schema (which is default to true) and don't write EOS (which is an optional in arrow rpc serialization format)
https://wesm.github.io/arrow-site-test/format/IPC.html#streaming-format
(Fixes: \#2051)
Manually test using our internal query

[GLUTEN-2051] Make ColumnarBatchSerializer supports relocation so that continuous shuffle block fetching can be enabled

---

cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/GlutenSignalHandler.cpp
cpp-ch/local-engine/Common/GlutenSignalHandler.h
cpp-ch/local-engine/examples/CMakeLists.txt
cpp-ch/local-engine/examples/signal_demo.cpp

(Fixes: \#2217)
using exited UTs
Experimental feature.
> Codes are copied from `BaseDameon`, since I believe it's difficult to merge into the main branch.
The idea is very simple, register a single handler via [Signal Chaining](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/signals003.html), when jvm failed to handle signal, it will call ours. We create a pipe during initialization, and in our Signal handler, we collect stack info, and then write those info into pipe. ​We also create a Signal Listener to read from that pipe, and dump the stack info. 
In most cases, the method works as I tried out. However, if the original SIGSEGV issue results from a corrupted stack, such as a JNI [stack overflow](https://pangin.pro/posts/stack-overflow-handling#shadow-pages), our …

[GLUTEN-2217][CH] Introduce Signal Handler to print stack info when get `SIGSEGV`

---

pom.xml
substrait/substrait-spark/pom.xml
tools/gluten-it/common/pom.xml
tools/gluten-it/package/pom.xml
tools/gluten-it/pom.xml

It seems the only place in Gluten to use guava is `substrait-spark`, which scope is `provided`.  There is no strong reason to shade it (otherwise it would make jar size bigger), so this pr just removes it.
gluten-it is a sub-project which depends on high guava version due to Trino tpcds/tpch. This pr shades them.
Pass CI

[CORE] Correct guava version

---

backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
ep/build-velox/src/get_velox.sh

If the write data is empty, we should write a valid parquet file rather than an empty file.
```shell
val df = spark.emptyDataFrame.select(lit(1).as("i"))
df.write.format("velox").save("test3")
```
before:
after:
Add test

[VL] Support empty dataframe write

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/scalar_function_parser/arrayMaxAndMin.cpp
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

CH arrayMax is different from Spark array_max, since it cannot handle Array(String) type argument.
But we can map Spark array_max(arr) to CH arrayReduce("max", arr)
UT

[GLUTEN-2193][CH] Support functions array_max/array_min

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionArrayDistinct.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/arrayDistinct.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/arrayUnion.cpp
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

There is a major difference between Spark array_distinct and CH arrayDistinct:
Spark array_distinct can remain null value in the array but CH arrayDistinct will skip it.
e.g. `select arrayDistinct([1, null, 2, null, 3, 3])` Spark return `[1, null, 2, 3]`, CH return `[1, 2, 3]`.
We should make CH arrayDistinct align with Spark.
UT

[GLUTEN-2193][CH] Support functions array_distinct/array_union

---

backends-velox/src/main/java/io/glutenproject/fs/OnHeapFileSystem.java
cpp/velox/jni/JniFileSystem.cc
cpp/velox/jni/JniFileSystem.h

modify `isCapableForNewFile0`
rename `RemovePathProtocol` to `FileSystemWrapper`
delete useless function `registerJniFileSystem`
[PR 2481](https://github.com/oap-project/gluten/pull/2481)

[VL] Patch for JniFileSystem PR #2481

---

.github/workflows/velox_be.yml
cpp/CMakeLists.txt
cpp/compile.sh
cpp/velox/CMakeLists.txt
dev/builddeps-veloxbe.sh

This pr is a followup of https://github.com/oap-project/gluten/pull/2427 to avoid compiling example code.
(Fixes: \#2182)
test locally:
```shell
./dev/buildbundle-veloxbe.sh --skip_build_ep=ON --enable_hdfs=ON --build_type=Debug --build_examples=ON
./dev/buildbundle-veloxbe.sh --skip_build_ep=ON --enable_hdfs=ON --build_type=Debug --build_examples=OFF
```

[GLUTEN-2182][VL][FOLLOWUP] Add BUILD_EXAMPLES flag

---

.github/workflows/velox_be.yml
gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java

CELEBORN-798 was merged into Celeborn 0.3.0, but was reverted and replaced by CELEBORN-804 in 0.3.1, it changes the method signature of `ShuffleClient#get` which introduces a compatible issue on the Gluten side.
This patch aims to use reflection to tackle the issue.
```
23/08/01 15:06:06 ERROR ExecuteStatement: Error operating ExecuteStatement: 
java.lang.NoSuchMethodError: org.apache.celeborn.client.ShuffleClient.get(Ljava/lang/String;Ljava/lang/String;ILorg/apache/celeborn/common/CelebornConf;Lorg/apache/celeborn/common/identity/UserIdentifier;Z)Lorg/apache/celeborn/client/ShuffleClient;
at org.apache.spark.shuffle.gluten.celeborn.CelebornShuffleManager.initializeLifecycleManager(CelebornShuffleManager.java:97)
at org.apache.spark.shuffle.gluten.celeborn.CelebornShuffleManager.registerSh …
```

[VL] Compatible with CELEBORN-798

---

.github/workflows/velox_be.yml
.gitignore
gluten-celeborn/pom.xml
tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/Constants.scala
tools/gluten-it/package/pom.xml
tools/gluten-it/pom.xml

Change `celeborn-client-spark-3_2.12` scope from compile to provided.
It's likely that the user put the Celeborn client jar into `SPAKR_HOME/jars` when he/she uses Celeborn as Remote Shuffle Service, and the Gluten jar should not include duplicate Celeborn classes. Further, it's likely that the user maintains internal versions of Celeborn/Gluten, separating should be good than bundling them into one.
BTW, it's not a good practice to include everything in a fat jar without proper class relocation.
manual tests.
```
➜  gluten git:(main) mvn clean package -DskipTests -pl :gluten-package -am -Pbackends-velox,spark-3.3,rss
➜  gluten git:(main) ll package/target/gluten-velox-bundle-spark3.3_2.12-pop_22.04-1.1.0-SNAPSHOT.jar
-rw-rw-r-- 1 chengpan chengpan 68M Jul 31 12:33 …
```

[VL] Change celeborn-client-spark dep scope to provided

---

backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

This pr is a followup of https://github.com/oap-project/gluten/pull/2392.
Add back the file format validation and native validation. Otherwise, such query will fail:
```sql
CREATE TABLE t AS SELECT 1 as c
SELECT * FROM t
```
```
Caused by: java.lang.RuntimeException: Exception: VeloxRuntimeError
Error Code: INVALID_STATE
Reason: ReaderFactory is not registered for format unknown
```
(Fixes: \#2391)
add test

[GLUTEN-2391][FOLLOWUP] Fix hive scan miss do validation

---

docs/get-started/Velox.md

Add back libhdfs short-circuit reading introduction, which can speed up performance.  PR:https://github.com/oap-project/gluten/pull/2050 just deleted it. 
Just doc update. 

[DOC][VL] Add libhdfs short-circuit read doc back

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/utils/QueryPlanSelector.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

The filter pruning expression of hive table scan may come from DPP. We need to do the check and transform for the pruning expression, the corresponding subqueryBroadcast and the possible re-used broadcast exchange. Otherwise, a mismatched subqueryBroadcast can be used and cause hash relation cast issues.
No regression issue in spark UTs.

[CORE] Fix a potential issue in hive table scan when DPP is used

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala

Fix missing partition column when column has alias
(Fixes: \#2430)
unit tests

[GLUTEN-2430] [CH] Fix missing partition column when column has alias

---

cpp/core/jni/JniCommon.h
cpp/core/shuffle/rss/CelebornPartitionWriter.cc

This pr changes the partition lengths to use compressed byte size which follows the jvm client side behavior.
The partition lengths is very import that would affect AQE decision.
test manually
Before:
After:

[VL] Celeborn shuffle writer should use compressed byte size

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala

If binding reference fails, we should just let the exception thrown with some detailed message given from spark.
No regression issue.

[CORE] Minor code refactor for binding reference

---

cpp/velox/compute/VeloxInitializer.cc
docs/get-started/VeloxS3.md

allow s3 endpoint  set only when not use instance credentials.
(Fixes: [issue-2638](https://github.com/oap-project/gluten/issues/2638))
verified on aws s3.

[GLUTEN-2638][VL]fix s3 endpoint configuration

---

tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/Parameterized.java

After the change, '->' should be ':' in `parameterized` integration testing.
For example: 
```sh
sbin/gluten-it.sh parameterized \
--local \
--threads=8 \
--benchmark-type=ds \
-s=100 \
--queries=q95 \
--iterations=1 \
--shuffle-partitions=8 \
--enable-ui \
--enable-history \
-m=OffHeapExecutionMemory \
-d=offheap:3g,spark.memory.offHeap.size=3g \ # note ":" is used here rather than '->'
-d=offheap:4g,spark.memory.offHeap.size=4g \
--extra-conf=spark.gluten.sql.columnar.backend.velox.spillStrategy=auto \
--extra-conf=spark.gluten.sql.columnar.backend.velox.spillFileSystem=local \
--extra-conf=spark.executor.userClassPathFirst=true
```

[VL] gluten-it-parameterized: Change delimiter '->' to ':' to avoid escaping '>' in shell

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

(Fixes: \#2375) 
Current solution is falling back when some corner cases are not supported by CH. 
TODO: 
- align spark split and ch splitByRegexp when limit > 0
- align spark split and ch splitByRegexp when regexp is not literal

[GLUTEN-2375][CH] Fix split function runtime exception in CH

---

gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Temporarily disable test case "SPARK-36726: test incorrect Parquet row group file offset" in GlutenParquetIOSuite for Spark33

[GLUTEN-2684][CORE][HOTFIX]: disable Spark-36726 parquet reading tests temporarily on Spark 3.3

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/substrait/SubstraitParser.h
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxExpr.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
cpp/velox/substrait/VeloxToSubstraitExpr.h
cpp/velox/substrait/VeloxToSubstraitPlan.cc
cpp/velox/substrait/VeloxToSubstraitPlan.h
cpp/velox/tests/FunctionTest.cc
cpp/velox/tests/Substrait2VeloxPlanConversionTest.cc
cpp/velox/tests/Substrait2VeloxPlanValidatorTest.cc
cpp/velox/tests/Substrait2VeloxValuesNodeConversionTest.cc
cpp/velox/tests/VeloxSubstraitRoundTripTest.cc

1. prefer to use local objects than dynamic new objects
2. prefer unique_ptr to shared_ptr, shared_ptr should be used to represent shared semantic
3. prefer using general member data than smart pointer member data unless we need support copy semantic

[VL] Making resource management conform to our cpp CodingGuideLines

---

gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

enable test case - aggregate push down - different data types for all parquet/orc/v1/v2 AggregatePushDownSuite
#2169

[GLUTEN-2169][VL] enable aggregate push down - different data types test case

---

shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This is a hot fix to disable spill truncating to avoid possible performance regression by too many small files.

[VL] Disable Velox spill file truncating by default

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

[GLUTEN-2673][CH] Fallback when lpad/rpad third arg is non-literal

---

cpp/core/jni/JniCommon.h
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/operators/functions/RegistrationAllFunctions.cc
cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitParser.h
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxExpr.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
cpp/velox/tests/FunctionTest.cc
cpp/velox/tests/VeloxToSubstraitTypeTest.cc

the `SubstraitParser` takes only read-only two map members, so we can change them to `static` data members, and make the member methods as static members.

[VL](Refactor) Making SubstraitParser's methods as static members 

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.h

[GLUTEN-2703][CH] get_json_object result's format is wrong when there is only one result

---

cpp-ch/local-engine/jni/jni_error.cpp

In this PR https://github.com/ClickHouse/ClickHouse/pull/53180,  clickhouse remove redundant `<iostream>` for improving building speed.
In `jni_error.cpp`, we use std::cerr incorrlectly, let's remove it

[CH] Minor fix : fix build issue due to https://github.com/ClickHouse/ClickHouse/pull/53180

---

tools/gluten-it/README.md
tools/gluten-it/pom.xml

Fix dependabot alert
```
Apache Spark vulnerable to Improper Privilege Management
Upgrade org.apache.spark:spark-core_2.12 to fix [1 Dependabot alert](https://github.com/oap-project/gluten/security/dependabot?q=is%3Aopen+package%3Aorg.apache.spark%3Aspark-core_2.12+manifest%3Atools%2Fgluten-it%2Fpom.xml+has%3Apatch) in [tools/gluten-it/pom.xml](https://github.com/oap-project/gluten/blob/-/tools/gluten-it/pom.xml)
Upgrade org.apache.spark:spark-core_2.12 to version 3.4.0 or later.
In Apache Spark versions prior to 3.4.0, applications using spark-submit can specify a proxy-user to run as, limiting privileges. The application can execute code with the privileges of the submitting user, however, by providing malicious configuration-related classes on the classpath. This affects architectures …
```

[GLUTEN-2604][VL] Fix github dependabot alert for Spark version

---

.github/workflows/velox_be.yml
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
backends-velox/src/test/scala/io/glutenproject/expression/VeloxUdfSuite.scala
cpp/core/utils/StringUtil.cc
docs/get-started/Velox.md
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-data/src/main/java/io/glutenproject/init/JniInitialized.java

This patch improves the native UDF support by allowing users to upload UDF libs via two Spark methods:
- `--files`
```
--files /path/to/gluten/cpp/build/velox/udf/examples/libmyudf.so
--conf spark.gluten.sql.columnar.backend.velox.udfLibraryPaths=libmyudf.so
```
- `--archives`
```
--archives /path/to/udf_archives.zip#udf_archives
--conf spark.gluten.sql.columnar.backend.velox.udfLibraryPaths=udf_archives
```
The documents are also updated with more detailed instrutions.

[GLUTEN-2504][VL] Support upload UDF libraries via --files and --archives

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/NativeFileScanColumnarRDD.scala
backends-clickhouse/src/main/scala/io/glutenproject/vectorized/CloseableCHColumnBatchIterator.scala
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarToRowExec.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/RowToCHNativeColumnarExec.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/metrics/GlutenTimeMetric.scala
gluten-core/src/main/scala/io/glutenproject/utils/Arm.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarBroadcastExchangeExec.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarSubqueryBroadcastExec.scala

This PR impelments automatic-resource-management pattern. For `SQLMetric`, we can use the following code to reduce duplicated codes:
```scala
val result = GlutenTimeMetric.millis(longMetric("collectTime")) { _ => 
...
}
```
I also implement a convenient utility `GlutenTimeMetric.withMillisTime` and `GlutenTimeMetric.withNanoTime`
I removed duplicate codes of `postColumnarTransitions` and `preColumnarTransitions`, extracting into a common method `transformPlan`, rewriting the following `foreach`
```scala
preOverrides().foreach {
r =>
overridden = r(session)(overridden)
planChangeLogger.logRule(r(session).ruleName, plan, overridden)
}
```
Actually, The above `foreach`  is `fold`
```scala
val overridden = getRules.foldLeft(plan) {
(p, getRule) =>
val rule = getRule(session)
val newPlan = …
```

[GLUTEN-2733][CORE][CH] Implementation of the automatic-resource-management pattern

---

backends-clickhouse/src/main/scala/io/glutenproject/utils/CHExpressionUtil.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
shims/common/src/main/scala/io/glutenproject/expression/ExpressionNames.scala

[VL] support array_join

---

gluten-core/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala

The Gluten endpoint address should be constructed using Spark buildin `RpcEndpointAddress` constructor, so that it can work on ipv6 env.
(Fixes: \#2740)

[GLUTEN-2740][CORE] Gluten endpoint should supports ipv6

---

cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxExpr.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h

this PR mainly contains two changes:
1. Add process for `SubstraitToVeloxPlanConverter::setFilterMap` in case of `TypeKind::HUGEINT`. The validation will fail if the field is `Decimal<4,20>` before this change, and the validation will be OK after this PR.
2. Refactor `SubstraitToVeloxPlanConverter` and related code, such as marking member function `static` if it doesn't operate member data. prefer stack objects to heap objects, and avoid using smart pointers if possible.  

[VL] Refactor Substrait to Velox plan conversion

---

gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala

The plan `SortMergeJoinExec` is converted to `MergeJoin` in velox only when the param `isSMJ=1` instead of `0`
https://github.com/oap-project/velox/blob/8cffafc01fbd8ea453022540fea6df97aebd2c32/velox/substrait/SubstraitToVeloxPlan.cpp#L319

[VL] Fix insistent SMJ params

---

cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
cpp/velox/operators/writer/VeloxParquetDatasource.cc
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/utils/ArrowTypeUtils.cc
cpp/velox/utils/ArrowTypeUtils.h
cpp/velox/utils/VeloxArrowUtils.cc

This patch fixed the memory leaks: the arrow schema is not correctly released on shuffle reader.
This resolves #2625

[GLUTEN-2625][VL] Fix: Velox shuffle reader / Velox Parquet data-source memory leak 

---

backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/GlutenPlan.scala

We shouldn't catch Java/Scala errors during validation since:
1. Errors can lead to invalid state (e.g. load shared library failed, load class failed)
2. All errors should be addressed in development phase, catching them hides potential code bugs
Instead, we should only catch exceptions (although Exception is still too general for indicating a validation failure) at the moment.

[CORE] Do not catch errors during plan validation

---

backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHNativeMemoryAllocators.java
backends-clickhouse/src/test/java/org/apache/spark/memory/TestTaskMemoryManagerSuite.java
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecHandler.scala
backends-velox/src/main/scala/io/glutenproject/execution/RowToVeloxColumnarExec.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarToRowExec.scala
gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornColumnarBatchSerializer.scala
gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/GlutenMemoryConsumer.java
gluten-data/src/main/java/io/glutenproject/memory/alloc/NativeMemoryAllocators.java
gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
gluten-data/src/main/scala/org/apache/spark/sql/execution/utils/ExecUtil.scala

When call TaskMemoryManager#showMemoryUsage, it will print all memory consumer's used memory, use caller's name would helpful to debug.
Before
```
TaskMemoryManager: Memory used in task 87
TaskMemoryManager: Acquired by io.glutenproject.memory.memtarget.spark.GlutenMemoryConsumer@39c93f4e: 478.0 MiB
TaskMemoryManager: Acquired by io.glutenproject.memory.memtarget.spark.GlutenMemoryConsumer@27db450c: 23.6 MiB
TaskMemoryManager: Acquired by io.glutenproject.memory.memtarget.spark.GlutenMemoryConsumer@1b80a18a: 8.0 MiB
```
After
```
TaskMemoryManager: Memory used in task 88
TaskMemoryManager: Acquired by GlutenMemoryConsumer-ContextInstance: 478.0 MiB
TaskMemoryManager: Acquired by GlutenMemoryConsumer-WholeStageIterator: 23.6 MiB
TaskMemoryManager: Acquired by …
```

[CORE] Pass caller name to GlutenMemoryConsumer to identify fine-grained memory usage

---

cpp/core/memory/ArrowMemoryPool.cc
cpp/velox/shuffle/VeloxShuffleReader.cc

We found some query has high task peek memory usage after integrate memory arbitrator, e.g. before this patch, TPCDS sf1000 q4 use 2.4GiB peek memory in its biggest stage, after this patch, it use 384MiB instead.
And this patch only fix shuffle reader memory usage which is the most huge part, there still some memory consumers need release early to decrease peek usage, will fix these in followup patches.
(Fixes: #2762)

[GLUTEN-2762] [VL] Release shuffle reader memory early to decrease peek memory usage

---

cpp/velox/operators/functions/Arithmetic.h
cpp/velox/operators/functions/RegistrationAllFunctions.cc
cpp/velox/operators/functions/RegistrationAllFunctions.h
cpp/velox/tests/CMakeLists.txt
cpp/velox/tests/SparkFunctionTest.cc
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala

std::round will get 0.57 for round(0.575,2).
But in spark, we should get 0.58 in default mode.
The main reason is that double type "0.575 * 100" is actually "57.499999999999996". So we need use nextafter function to get real value.

[VL] Add spark round function

---

.github/ISSUE_TEMPLATE/bug.yml

The supported spark versions are limited, so use dropdown instead.
A script's location is wrongly described.

[MINOR]Refine github issue template

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecHandler.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala

we will create two range filters for `createNotEqualFilter`, the `lowerFilter` and the `upperFilter`, the`NotEqual` will be transferred to `[minLower, value) || (value, maxUpper]`.
the `lowerFilter` represents the range `(value, maxUpper]`, and the `upperFilter` represents the range `[minLower, value)`.
then add `lowerFilter` first and add `upperFilter` second, which makes the multi-range filters violate the check rules in `BigintMultiRange::BigintMultiRange()`.
we can swap the adding to fix it.

[VL] Fix the issue of SubstraitToVeloxPlanConverter::createNotEqualFilter

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

Complex types of data will only be released when the shufflewriter is released, even if this part of the data has been stored in a RecordBatch This change allows each partition to have a StreamArena, so that after converting to RecordBatch, the memory in StreamArena can be freed immediately

[GLUTEN-2836][VL] Fix: memory usage problems caused by complex type

---

cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h

two advantages of using `vector` in this situation:
1. vector is faster and more efficient than unordered_map
2. vector doesn't need to use a loop to construct

[VL] Refactor SubstraitToVeloxPlanConverter by using vector instead of unordered_map

---

cpp/core/compute/Backend.h
cpp/core/compute/ResultIterator.h
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/reader.cc
cpp/core/shuffle/reader.h
cpp/velox/compute/VeloxBackend.h
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleReader.h
gluten-celeborn/src/main/scala/org/apache/spark/shuffle/CelebornColumnarBatchSerializer.scala
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleReaderJniWrapper.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala

A single shuffle reader instance in Gluten could hold one Velox memory pool that may reserve at least several MiBs data until Spark task ends. This could be a memory leak source in the case of large read amount.
In the patch we'll expand the shuffle reader scope to let one task create only a single shuffle reader instead of creating the reader per shuffle read fetch (which by default 48MiB).
Ideally this will decrease Gluten's overall Spark off-heap memory occupation.
A simple calculation:
Assuming shuffle read size is 1TiB, with 10 available Spark CPUs, read batch / buffer size is 4096 rows, 100 Byte per row:
Then the peak off-heap memory from shuffle reader (which could cause unnecessary spills even OOM when high):
Before:
1T / 48M * 4096 * 100B = 8.95 GiB
After:
10 * 4096 * 100B = 4 …

[GLUTEN-2803][VL] Use a single native shuffle reader instance per Spark reducer task

---

cpp/velox/substrait/SubstraitToVeloxPlan.cc

1. add case TINYINT/SMALLINT for `setFilterInfo`
2. make error messages different

[VL] Fix falllback caused by filter of TinyInt or SmallInt column type

---

cpp/core/config/GlutenConfig.h
cpp/velox/compute/WholeStageResultIterator.cc
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

In this PR, we introduced a gluten config key to hold default session time zone, which will be used if spark config (spark.sql.session.timeZone) is not explicitly set by user (this handling is quite consistent with spark's).
(Fixes: \#2796)
Will refactor native config by introducing a dedicated class to hold properties. Will then add native tests for validation.

[GLUTEN-2796][VL] Set default session time zone if not explicitly set by user

---

cpp/CMakeLists.txt
cpp/velox/substrait/SubstraitToVeloxExpr.cc

Fixes validation failure due to DATE IN expression.
>native check failure:native validation failed due to: validation fails for FilterRel expression, Scalar function in not registered with arguments: (DATE, ARRAY<INTEGER>).
Before:
After:

[VL] Fix TPCDS Q83 fallback

---

.github/workflows/velox_be.yml
cpp/velox/tests/OrcTest.cc

Skip broken test and modify CI, after this patch, we can run `ctest -V` with no concern.
(Fixes: #2862)

[GLUTEN-2862] [VL] Skip broken orc test

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseS3SourceSuite.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Common/FileCacheConcurrentMap.h
cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp

Support to remove files cache by the specified cache time, which will be passed through parameter 'spark.gluten.sql.columnar.backend.ch.runtime_settings.spark.kylin.local-cache.accept-cache-time'.
Close #2860.
(Fixes: #2860)

[GLUTEN-2860][CH] Support removing files cache for CH Backend

---

backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/LocalPartitionWriter.h
cpp/core/shuffle/ShuffleWriter.h
cpp/core/shuffle/reader.cc
cpp/velox/benchmarks/ShuffleSplitBenchmark.cc
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleReader.h
cpp/velox/tests/VeloxShuffleWriterTest.cc
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleWriterJniWrapper.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This option is default false, the true mode is only used in test code, and not suggest to change to the true mode.
If switch to true mode, shuffle will write serialized schema firstly, for some small batch, it is a high load. And we can get correct schema from spark plan when constructing ShuffleReader.
Refactor the test code to remove write_schema option.

[VL] Remove shuffle write schema option

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxAggregateFunctionsSuite.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala

This pr fixes the bug that in native validation, when we check the aggregate signatures, we will return true once one of the aggregate functions matches. This pr changes to return ture only if all aggregate functions signatures match.
```sql
select c1, collect_set(c2), max(c2) from t group by c1;
```
```
23/08/24 13:27:45 ERROR TaskSetManager: Task 1 in stage 9.0 failed 1 times; aborting job
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 9.0 failed 1 times, most recent failure: Lost task 1.0 in stage 9.0 (TID 23) (10.221.106.37 executor driver): java.lang.RuntimeException: Exception: VeloxUserError
Reason: Aggregate function 'array_distinct' not registered
Function: intermediateType
File: …
```

[VL] Fix hash aggregate fail with mixed supported and unsupported aggregate functions

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/PredicateExpressionTransformer.scala
gluten-core/src/main/scala/io/glutenproject/utils/DecimalArithmeticUtil.scala

Fix the incorrect result type when decimal arithmetic expressions are nested. For example, in below case the input type got from divide is decimal(35, 20), which is not correct because cast was intentionally removed. Since the input types of divide are decimal(17, 2), the correct result type should be calculated from them.
> promote_precision(CheckOverflow((promote_precision(cast(promotions#850 as decimal(15,4))) / promote_precision(cast(total#851 as decimal(15,4)))), DecimalType(35,20))) * 100.00000000000000000000

[VL] Fix the incorrect result type when decimal arithmetic expressions are nested

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDecimalExpressionSuite.scala

On Gluten's main branch, `CheckOverflowExpression` is transformed into `CheckOverflowExpressionTransformer`, and is used to change the precision of a decimal value. But after rebase, the `CheckOverflowExpressionTransformer` is removed and the native computation will directly use the original scale/precision to avoid precision loss. Therefore after rebase, the UT failed because the `CheckOverflow` is nolonger used to change the precision of a decimal, and it should use `Cast` instead.
Reference:
Gluten main: https://github.com/oap-project/gluten/blob/0891942447560b26ad4374ad533b05b53bbb65c2/gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala#L159-L183
Gluten rebase: https://github.com/oap-project/gluten/blob/647bdb611eb1d81ac1269658d42f201911972723/gluten …

[VL] Fix UT: CheckOverflow

---

cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h

At present, the orc filter of velox does not support decimal and timestamp. If the filter of decimal and timestamp is pushed down to scan, the task will directly fail. If scan fallback is set, serious performance regression will be caused. Therefore, it is currently necessary to push down only the types supported by the orc filter.
TPCDS  q33

[VL] Move orc decimal filters to the remaining filter list in native scan

---

cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp

1. S3 ReadSetting 从全局参数中复制来
2. 修改remotebuffer    use_external_buffer=true
arrow读取parquet footer时,当footsize小于metalength，重新读取metaleng
```
if (footer_read_size >= (metadata_len + kFooterSize)) {
metadata_buffer = SliceBuffer(
footer_buffer, footer_read_size - metadata_len - kFooterSize, metadata_len);
} else {
PARQUET_ASSIGN_OR_THROW(metadata_buffer,
source_->ReadAt(metadata_start, metadata_len));
}
```
读取时会先将bufer seek到metadata pos
```
std::lock_guard<std::mutex> lock(interface_impl_->lock_);
RETURN_NOT_OK(Seek(position));
return Read(nbytes);
```
当use_external_buffer=false时，cachebufer无法完成seek，但是最后readsize=0
(Fixes: \#2929)

[GLUTEN-2929][CH] Read s3 file using global ch readsetting

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-ut/common/src/test/scala/io/glutenproject/utils/BackendTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

ORC test suites are blocked by Velox upstream PR. Temporarily disable the failed UT. Add "disableAll" to clear all exclusions and add one dummy case to inclusions to make sure no suites match. So that we can simply remove the "disableAll" line once it's supported.
Passed suites:
GlutenOrcColumnarBatchReaderSuite
GlutenOrcFilterSuite
GlutenOrcV1FilterSuite
The rests failed.

[VL] Temporarily disable all failed ORC UT

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala

https://github.com/oap-project/gluten/issues/2978
pass the existing test

[GLUTEN-2978][VL]fix: GlutenConfig.getConf should not be called before SQLConf initialize

---

cpp/core/jni/JniWrapper.cc
cpp/core/memory/ArrowMemoryPool.cc
cpp/core/memory/ArrowMemoryPool.h
cpp/core/memory/MemoryManager.h
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/memory/VeloxMemoryManager.h

Expose shared ptr getter API in MemoryManager for arrow memory pool, partial fix #2853. Will refactor getter API to raw pointer after consider memory_pool and ipc_writer_pool in ShuffleWriterOptions.

[GLUTEN-2853] [VL] Move native arrow memory pool to MemoryManager

---

cpp/velox/memory/VeloxMemoryManager.cc

Arrow memory pool will be shown in the OOM error message as a sub leaf node of Gluten's memory consumer.
For example:
```
23/08/31 13:25:53 ERROR ManagedReservationListener: Error reserving memory from target
io.glutenproject.memory.memtarget.ThrowOnOomMemoryTarget$OutOfMemoryException: Not enough spark off-heap execution memory. Acquired: 8388608, granted: 0. Try tweaking config option spark.memory.offHeap.size to get larger space to run this application. 
Current config settings: 
spark.gluten.memory.offHeap.size.in.bytes=4.0 GiB
spark.gluten.memory.task.offHeap.size.in.bytes=512.0 MiB
Memory consumer stats:
GlutenMemoryConsumer/WholeStageIterator@57eaa45b:                Current used bytes:  408.0 MiB, peak bytes:  408.0 MiB
+- velox: …
```

[VL] Include Arrow memory pool in OOM error message

---

dev/vcpkg/setup-build-depends.sh

Version 3.9.2 is not available from  https://downloads.apache.org/maven/maven-3/ which has been archived.
manual tests

[VL] Download maven from archive site

---

cpp-ch/local-engine/CMakeLists.txt
cpp-ch/local-engine/Columns/DecodedJSONColumn.h
cpp-ch/local-engine/Columns/FormattedColumn.h
cpp-ch/local-engine/Functions/DecodeJSONStringFunction.cpp
cpp-ch/local-engine/Functions/SparkFunctionGetJsonObject.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/GetJSONObjectParser.cpp

Extracting fields out from the same string is normal case. 
```SQL
select get_json_object(a, '$.a'), get_json_object(a, '$.b') from t
```
At present, `CH`  parse the original string repeatly for each field extracting. The parsing phase's overhead is high
We try to reuse the intermediate data from json parsing in thi PR

[CH] optimize `get_json_object` by reusing intermediate data

---

backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHNativeMemoryAllocatorManagerImpl.java
gluten-core/src/main/scala/org/apache/spark/util/TaskResource.scala
gluten-core/src/main/scala/org/apache/spark/util/TaskResources.scala
gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManager.java

This pr uses `PriorityQueue` to replace `java.util.HashMap[Long, java.util.List[TaskResource]]()` to simplify the code. And changes priority from long to int, as it seems the int type is enough.
PASS CI

[CORE] Use PriorityQueue to hold task resource

---

backends-velox/src/main/scala/io/glutenproject/execution/RowToVeloxColumnarExec.scala

Before, when cancel the follow query, it would cause memory leak due to arrow buffer not released.
```
val sql = "select /*+ repartition(10) */ * from (select *, java_method('java.lang.Thread', 'sleep', 1000 * cast(spark_partition_id() as long)) from range(100))"
sc.setJobGroup("g1", sql, true)
spark.sql(sql).collect
```
```
23/09/01 15:26:58 WARN ArrowBufferAllocators$ArrowBufferAllocatorManager: Detected leaked Arrow allocator, size: 2097152, process accumulated leaked size: 6291456...
23/09/01 15:26:58 WARN ArrowBufferAllocators$ArrowBufferAllocatorManager: Leaked allocator stack Allocator(ROOT) 0/2097152/2097152/9223372036854775807 (res/actual/peak/limit)
```
manually test

[VL] Fix Row to Columnar memory leak when cancel task

---

cpp/core/shuffle/utils.h

The current judgement of whether a new filename of local shuffle spill has already been created is wrong. Should use "O_EXCL" in the read flag to judge if the file has been created.

[VL] Fix generated spilled file already created

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Parser/RelMetric.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/local_engine_jni.cpp

(Fixes: \#2970)
How to enable ch query plan optimization? 
By default ch query plan optimization is disabled, you can use `--conf spark.gluten.sql.columnar.backend.ch.runtime_settings.query_plan_enable_optimizations=true` to enable it.

[GLUTEN-2970][CH] respect clickhouse settings: query_plan_enable_optimizations

---

tools/gluten-it/pom.xml

FIXES https://github.com/oap-project/gluten/security/dependabot/37
Verify via local maven build.

[CORE] Switch default Maven dependency scope of Spark to provided (by default) in gluten-it

---

tools/gluten-it/common/src/main/resources/META-INF/services/org.apache.spark.status.AppHistoryServerPlugin
tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/TpcSuite.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/deploy/history/GlutenItHistoryServerPlugin.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/deploy/history/HistoryServerHelper.scala

Executor log view in gluten-it was broken when `local-cluster` mode is selected. This is to fix the issue.

[VL] Gluten-it: Fix broken executor log view on history server web UI

---

cpp/core/jni/JniWrapper.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/memory/VeloxMemoryManager.h
gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/Spillers.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManager.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManagers.java

So far we only adopt Velox reclaim/shrink APIs to plan execution pools.
We should extend the usage to all Velox pools using a common path.
https://github.com/oap-project/gluten/issues/2808

[GLUTEN-2808][VL] All managed Velox memory pools should be shrinkable

---

cpp/velox/operators/writer/VeloxParquetDatasource.cc

Pass the parquet write suite except parquet write with empty dataframe, which need https://github.com/oap-project/velox/pull/370. 

[GLUTEN][VL] Enable velox parquet write suite

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h

Velox's addXXXPool only hold weak ptr in parent pool, returned shared ptr should be managed by caller.
Before this patch, WholeStageIter hold the shared pool and will release pool when we release iterator, but in some cases, there still some unused/unreleased batches before release iterator, so we may get bad memory usage error from Velox.
Since we implement MemoryManager to hold the shared ptr of memory pool, use getXXXPool of VeloxMemoryManager directly is more safe.

[VL] Avoid hold unmanaged velox memory pool for caller

---

cpp/velox/compute/WholeStageResultIterator.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

HashAggregation will check these four config value to decide whether abandon partial aggregation or not. We may need fine-tune these config value to avoid OOM in Large-scale Spark job.

[VL] Add partial hash aggregation memory configurations to avoid OOM

---

cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/memory/AllocationListener.cc
cpp/core/memory/AllocationListener.h
cpp/velox/compute/VeloxInitializer.cc
docs/developers/HowTo.md

We designed a new class `BacktraceAllocationListener` derived from `gluten::AllocationListener`, It may be useful when we encounter a memory issue.
We use `SparkAllocationListener` by default, but we can use a wrapper class `BacktraceAllocationListener` to dump the allocation call stack by config `spark.gluten.backtrace.allocation = true`.

[VL] Add backtrace for memory allocation tracking

---

tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/Queries.java
tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/TpcRunner.scala
tools/gluten-it/common/src/main/scala/io/glutenproject/integration/tpc/action/Queries.scala
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/QueryRunner.scala

Umbrella: https://github.com/oap-project/gluten/issues/3048
To simulate speculative execution's task killing actions in local test, even using more aggressive kills.

[VL] Gluten-it: Add option --random-kill-tasks to emulate the case that tasks are frequently killed and retried

---

cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/LocalPartitionWriter.h
cpp/core/shuffle/ShuffleWriter.cc
cpp/core/shuffle/ShuffleWriter.h
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc

The stop function performs several tasks:
1. Opens the final data file.
2. Iterates over each partition ID (pid) to:
a. Record the offset for each partition in the final file.
b. Merge data from spilled files and write to the final file.
c. Write cached payloads to the final file.
d. Create the last payload from split buffer, and write to the final file.
e. Optionally, write End of Stream (EOS) if any payload has been written.
3. Closes and deletes all the spilled files.
4. Records various metrics such as total write time, bytes evicted, and bytes written.
5. Clears any buffered resources and closes the final file.
Spill handling:
Spill is allowed during stop(). If OOM happens during stop(), it will first shrink the split buffers and then perform spill if necessary.
Among above steps, 1. …

[GLUTEN-2941] Enable spill support during shuffle splitter stop

---

cpp/core/shuffle/FallbackRangePartitioner.cc
cpp/core/shuffle/FallbackRangePartitioner.h
cpp/core/shuffle/HashPartitioner.cc
cpp/core/shuffle/HashPartitioner.h
cpp/core/shuffle/Partitioner.h
cpp/core/shuffle/RoundRobinPartitioner.cc
cpp/core/shuffle/RoundRobinPartitioner.h
cpp/core/shuffle/SinglePartPartitioner.cc
cpp/core/shuffle/SinglePartPartitioner.h

Why we make this change?
We made vs. benchmark in https://quick-bench.com/, And the result shows the speed of the improved Partitioner::computer is 2x faster than the old implementation.

[WIP][CORE] Optimize shuffle partitioner algorithm to take advantage of  auto-vectorization in GCC

---

cpp/core/memory/ColumnarBatch.cc
cpp/core/memory/ColumnarBatch.h

This pr refines the `CompositeColumnarBatch`, inlcuding:
- use  std::move to pass vector batch to avoid data copy
- use int32_t to replace long to avoid implicat conversion
- use underlying batch to get numBytes if exists
PASS CI

[VL] Refine CompositeColumnarBatch

---

shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Quick fix naming format typo introduced from https://github.com/oap-project/gluten/pull/2950

[VL] Fix config key naming format in  GlutenConfig.scala

---

cpp-ch/local-engine/local_engine_jni.cpp

We should call `ReleaseByteArrayElements`  before returning to JVM
Usigin Existed UT

[CH] Fix memory leak

---

cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/velox/jni/JniFileSystem.cc
cpp/velox/jni/JniUdf.cc

May fix https://github.com/oap-project/gluten/issues/3062, still in testing
After the patch, we should abide by the rule that any C++ to Java invocations should be followed by a `checkException()` guard.
`checkException()` prevents its guarding code from running into undefined state and throw immediately if an Java exception was thrown.
For Java to C++, we have JNI_METHOD_START and JNI_METHOD_END to do the similar guarding job.
In future we may want to use macros to ease the manual `checkException` calls.

[GLUTEN-3062][VL] Check Java exception immediately when a call from C++ to Java ended

---

cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitParser.h
cpp/velox/substrait/SubstraitToVeloxExpr.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/TypeUtils.cc
cpp/velox/substrait/TypeUtils.h
cpp/velox/substrait/VeloxToSubstraitType.cc
cpp/velox/tests/VeloxToSubstraitTypeTest.cc

Why I made this change and what's the benefit?
1. Return `SubstraitType` instead of `std::shared_ptr<SubstraitType>`, and this change may avoid unnecessary dynamic `new` because most calling sides don't need a heap allocation object.  Returning a stack object is more effective.
2. Providing a new interface `fromSubstraitTypeToVeloxType` implemented with `toVeloxType(SubstraitParser::parseType(substraitType).type)` will make code simpler and clearer.

[VL] Refactor parseType for the cpp substrait module

---

cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp

Spark has the log: `FileScanRDD: Reading File path: xxx, range: 134217728-216861174, partition values: [empty row]
`
We should add similar log: ` FormatFile: Reading File path: xxx, format: kOrc, range: 0-268435456, partition_index: 31, partition_values: [day=2023-08-31, hour=01]
`
manual tests

[CH] Add log for native read file

---

cpp/velox/compute/VeloxBackend.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Related to https://github.com/oap-project/gluten/issues/3048.
We observed some rare crashes in library `libunwind` when Velox is trying to handle exceptions.
After this patch, set both `spark.gluten.sql.columnar.backend.velox.enableSystemExceptionStacktrace=false` and `spark.gluten.sql.columnar.backend.velox.enableUserExceptionStacktrace=false` to workaround the crash issue to let the exceptions throw normally.

[VL] Add config option spark.gluten.sql.columnar.backend.velox.enableSystemExceptionStacktrace

---

.github/workflows/velox_be.yml
tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/Queries.java
tools/gluten-it/common/src/main/scala/org/apache/spark/sql/QueryRunner.scala

Using gluten-it `--random-kill-tasks` to emulate random task kills/retries on a complete TPC-H + TPC-DS run.
Within `--random-kill-tasks`, each task gets some chance to be killed after running for several seconds.
Temporarily, failures from this test will be ignored so doesn't block CI. We'll make it blocking after fixing all the relevant crash issues caused by task kill. See also https://github.com/oap-project/gluten/issues/3048.

[VL] Set a GHA workflow run to emulate random task kills/retries

---

gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala

Fix https://github.com/oap-project/gluten/issues/3154
Spark will try to get reused queryStage based on plan.canonicalized.
https://github.com/apache/spark/blob/822f58f0d26b7d760469151a65eaf9ee863a07a1/sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala#L523-L523

[GLUTEN-3154][CORE] Override doCanonicalize in scan operators

---

cpp/core/jni/JniWrapper.cc
cpp/velox/jni/VeloxJniWrapper.cc

Summary:
1. add `jniCastOrThrow` method to wrap reinterpret_cast and reduce duplicate codes.
2. move `create/releaseExecutionCtx` from VeloxJniWrapper.cc to JniWrapper.cc, `initializeBackend` will be refactored in spilt JniWrapper patch.

[GLUTEN-3077][VL] followup: add jniCastOrThrow method and codes clean up

---

cpp/core/benchmarks/CompressionBenchmark.cc

very little change, just fix a compilation warning.

[VL] Suppress a compilation warning from CompressionBenchmark.cc

---

gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala

Fix Spark-3.3 BatchScanExecTransformer makeCopy error after removing pushdownFilters parameter in BatchScanExecTransformer.
```
Exception in thread "main" java.lang.IllegalStateException:
Failed to copy node.
Is otherCopyArgs specified correctly for BatchScanExecTransformer.
Exception message: wrong number of arguments
ctor: public io.glutenproject.execution.BatchScanExecTransformer(scala.collection.Seq,org.apache.spark.sql.connector.read.Scan,scala.collection.Seq)?
types: class scala.collection.immutable.$colon$colon, class org.apache.iceberg.spark.source.SparkBatchQueryScan, class scala.collection.immutable.$colon$colon, class scala.None$
args: List(xxxxx#10037, xxxxx#10046, xxxxx#10047L, xxxxx#10048L, xxxxx#10079, xxxxx#10080, xxxxx#10081), …
```

[GLUTEN-3154][FOLLOWUP] Add keyGroupedPartitioning in BatchScanExecTransformer for spark-3.3

---

cpp/core/compute/ExecutionCtx.h
cpp/core/tests/CMakeLists.txt
cpp/velox/compute/VeloxExecutionCtx.cc
cpp/velox/compute/VeloxExecutionCtx.h
cpp/velox/tests/CMakeLists.txt
cpp/velox/tests/ExecutionCtxTest.cc
cpp/velox/utils/ResourceMap.h

Since ExecutionCtx does not expected to use in concurrent context, we can remove Concurrent which has mutex for each methods.
Added ResourceMap is backed by folly::F14FastMap.

[GLUTEN-3077][VL] Use ResourceMap to replace ConcurrentMap in VeloxExecutionCtx

---

ep/build-clickhouse/src/package.sh

[GLUTEN-3201][CH] rename spark-shims.jar to gluten-spark-shims.jar for consistent class loading order

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

calculating once on init step to avoid repetitive calculating

[VL] Avoid repetitively calculating fixed-size columns' bytes in calculatePartitionBufferSize

---

cpp/core/shuffle/ShuffleWriter.h
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc

This patch fixes several cases:
1. If the buffer size after shrink is 0, do not shrink but reset the buffers.
2. If the buffer size before shrink is 0 or no space to shrink, skip shrink.
3. Fix split after spill wrong result.
Added several C++ UT to cover above cases.

[GLUTEN-3189] Fix shuffle spill failure and wrong result

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/ProjectRelParser.cpp
cpp-ch/local-engine/Parser/ProjectRelParser.h
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

Notice that arrayJoin function and array join step are executing in different places. The former is in `ExpressionActions::execute`,  and latter is in `ArrayJoinAction::execute`. `max_block_size` is currently only valid in array join step, so we must transform arrayJoin function to array join step to apply max_block_size.  
Notice: This pr relies on https://github.com/ClickHouse/ClickHouse/pull/54664, but it can be merge firstly. 
(Fixes: \#3143)

[GLUTEN-3143][CH] Transform arrayJoin function to array join step to apply max_block_size

---

cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h

When multiple Cores execute tasks on an Executor at the same time, the following exception will occur.
```
*** Error in `/usr/jdk64/current/bin/java': double free or corruption (fasttop): 0x000055b1677232d0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f9634f1d329]
/data04/hadoop/yarn/local/usercache/op/appcache/application_1685359810729_0140/gluten-daf0d89c-a915-4270-aaa2-a0dc27e7789f/jni/bb70bf12-76bb-4989-bfb2-5dd76859d4da/gluten-2748809769443381838/libhdfs3.so.1(hdfsSetDefautUserName+0x10d)[0x7f95f62ae99d]
/data04/hadoop/yarn/local/usercache/op/appcache/application_1685359810729_0140/gluten-daf0d89c-a915-4270-aaa2-a0dc27e7789f/jni/bb70bf12-76bb-4989-bfb2-5dd76859d4da/gluten-2748809769443381838/libvelox.so(_ZN6gluten24WholeStageResultIterator16updateHdfsTokensEv+0x65)[0 …
```

[GLUTEN-2612][VL] Fix updateHdfsTokens double free or corruption

---

cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/ShuffleWriter.h
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/ShuffleSplitBenchmark.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedVeloxColumnarShuffleWriter.scala
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleWriterJniWrapper.java
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala

Rely on https://github.com/oap-project/gluten/pull/2982
Without the PR, we pass available off-heap memory size to shuffle writer when it's created. The problem is sometimes the shuffle writer is created before operators allocating large block memory like hash agg. Then the split buffer is preallocated according to whole off-heap memory instead of available memory when shuffle writer really works.
The PR pass the available memory to shuffle write with each batches, so we can recalculate the buffer size on each batch.

[VL] Get avaliable off-heap memory for split buffer calculation everytime split() is called

---

cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
ep/build-velox/src/get_velox.sh
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala

This patch implements `GenerateExec` for Velox backend. 
it does not support below cases:
- explode with outer option
- posexplode
- MapType as the input
(Partially Fixes: #2943 )
existing UT

[GLUTEN-2943][VL] implement `GenerateExec`

---

cpp/velox/memory/VeloxMemoryManager.cc

The leak check may throw exception from MemoryPool's destructor which could not be caught by user code.
The leak check should either be done by Spark's memory manager.
Enable the random kill tasks CI job to see if it could pass.

[GLUTEN-3048][VL] Disable Velox memory pool's own leak check since it may cause process crashes

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQEConcurrentSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala

[GLUTEN-3252][CH] fix race condition at the global variable of isAdaptiveContext in ColumnarOverrideRules
test  GlutenClickHouseTPCHParquetAQEConcurrentSuite  can  reproduce

[GLUTEN-3252][CH] fix race condition at the global variable of isAdaptiveContext in ColumnarOverrideRules

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsHandler.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/SparkPlanExecHandler.scala
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/ShuffleReader.cc
cpp/core/shuffle/ShuffleReader.h
cpp/velox/compute/VeloxBackend.cc
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleReader.h
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleReaderMetrics.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala

Some jobs of ours consume most of their time for the operator of `ColumnarExchange`, and the metrics of VeloxShuffleReader don't contain `IO(IPC read)` and `deserialize` steps.
So I proposed this PR to complement these missing metrics. 

[VL] Add timing for velox shuffle reader

---

tools/gluten-it/pom.xml

In #2605 , we by default set -P spark-3.4 for gluten-it to fix the dependent bot alert. However it was more or less a deceit to go around dep bot's code scanning without actually fixing the issue.
Let's use spark-3.2 to avoid mismatching with gluten's main code until we came up with a better fix.

[VL] Gluten-it: By default use -P spark-3.2

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala

Due to some code change for `HiveTableScanExecTransformer`, like [PR](https://github.com/oap-project/gluten/pull/2773) and [PR](https://github.com/oap-project/gluten/pull/2558), etc, scan offloading behavior becomes incorrect, such as ORC format scan can't be offloaded anymore. The root cause is that some  ClickHouse format/datatype check logic is added in this Op which is supposed to add in CKBackend API instead. This PR intends to fix it.
UT

[GLUTEN-2919][VL]Fix incorrect hive scan fallback or offload for velox

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala

[GLUTEN-3241][CH] Disable conversion of ColumnarToRowExec to CHColumnarToRowExec when operator of SourceScan fallback vilina spark
Disable conversion of ColumnarToRowExec to CHColumnarToRowExec when operator of SourceScan fallback vilina spark

[GLUTEN-3241][CORE] Use vanilla ColumnarToRowExec if scan operator falls back

---

ep/build-velox/src/get_velox.sh

fix velox_ep/scripts/setup-macos.sh
folly needs to be installed after install_double_conversion
https://github.com/oap-project/velox/blob/1910a1722dcb5e7dde83e84defdc33f21327be84/scripts/setup-macos.sh#L116-L124
manual tests

[VL] Update get_velox.sh for macos

---

cpp/core/jni/JniWrapper.cc
gluten-data/src/main/java/io/glutenproject/exec/ExecutionCtxJniWrapper.java
gluten-data/src/main/java/io/glutenproject/init/BackendJniWrapper.java

BackendJniWrapper extend JniInitialized and JniInitializer invoke BackendJniWrapper#initializeBackend static method too, it will cause dead lock on static object lock.
PR #3929 change BackendJniWrapper#createExecutionCtx usage and let BackendJniWrapper init first in some case trigger this issue. Before 3929, JniInitializer's static lock was hold by other JniWrapper initialization which extend JniInitializer, it's safe to hold BackendJniWrapper static lock.
(Fixes: \#3302)

[GLUTEN-3302][VL] Fix dead lock of BackendJniWrapper static loading

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsHandler.scala
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala

`data size` collects the raw size of input rowvectors.
Add `uncompressed data size` to show the partition buffer data size before compression.

[VL] Show uncompressed data size for ColumnarExchange

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHContextApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ContextInitializer.scala
gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ContextApi.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Supports configuring the spark.yarn.dist.files configuration to allow yarn to automatically upload and load the libch.so package
Avoid having to manually distribute packages in the hadoop cluster for each deployment
Supports configuring the spark.yarn.dist.files configuration to allow yarn to automatically upload and load the libch.so package.
In this way, you can allow libch.so to be loaded on the executor by configuring xx as follows:
spark.gluten.sql.columnar.libpath=/your/path/to/libch.so
spark.yarn.dist.files=/your/path/to/libch.so
spark.gluten.sql.columnar.executor.libpath=libch.so
spark.executorEnv.LD_PRELOAD=$PWD/libch.so

[Gluten-3296] Supports configuring the spark.yarn.dist.files configuration to allow yarn to automatically upload and load the libch.so package

---

backends-clickhouse/src/main/java/io/glutenproject/memory/alloc/CHNativeMemoryAllocators.java
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-clickhouse/src/test/java/org/apache/spark/memory/TestTaskMemoryManagerSuite.java
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedCHColumnarShuffleWriter.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedVeloxColumnarShuffleWriter.scala
gluten-core/src/main/java/io/glutenproject/memory/memtarget/KnownNameAndStats.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/MemoryTargetVisitor.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/MemoryTargets.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/OverAcquire.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/Spiller.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/Spillers.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/ThrowOnOomMemoryTarget.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/TreeMemoryTarget.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/TreeMemoryTargets.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/IsolatedMemoryConsumers.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/RegularMemoryConsumer.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/spark/TreeMemoryConsumer.java
gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
gluten-data/src/main/java/io/glutenproject/memory/arrowalloc/ArrowBufferAllocators.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManagers.java
gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala

Within this patch, interface `TaskMemoryTarget` will be removed, then the memory target API, including the common decorator implementations will no longer directly rely on any of Spark's API.
By doing this we could have opportunity to replace Spark's memory manager with our own implementation within minimum effort. So far the patch is just code refactor in advance of the further actions.

[VL] Decouple Spark's memory manager from Gluten's memory target API

---

cpp/core/compute/ExecutionCtx.h
cpp/core/jni/JniWrapper.cc
cpp/core/memory/MemoryManager.h
cpp/core/operators/serializer/ColumnarBatchSerializer.h
cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/ShuffleReader.cc
cpp/core/shuffle/ShuffleReader.h
cpp/core/shuffle/ShuffleWriter.h
cpp/core/shuffle/rss/CelebornPartitionWriter.cc
cpp/velox/benchmarks/ShuffleSplitBenchmark.cc
cpp/velox/compute/VeloxExecutionCtx.cc
cpp/velox/compute/VeloxExecutionCtx.h
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/memory/VeloxMemoryManager.h
cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.h
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleReader.h
cpp/velox/tests/ExecutionCtxTest.cc
cpp/velox/tests/VeloxColumnarBatchSerializerTest.cc
cpp/velox/tests/VeloxShuffleWriterTest.cc

Fix exist TODO, caller was not expected to care memory pool's ownership, just get raw pointer for use, like Arrow style.

[VL] Refactor MemoryManager#getArrowMemoryPool to return raw pointer

---

cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
gluten-core/src/main/resources/substrait/proto/substrait/algebra.proto
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

add the configuration spark.gluten.sql.text.input.empty.as.default representing the meaning of treat empty fields in CSV input as default values

[Gluten-3312][CH] Introduce a config to control empty as default for CSV

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxColumnarCacheSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-data/src/main/java/io/glutenproject/columnarbatch/ColumnarBatches.java

Supports columnar `df.cache.count`. It is a special case that the selected schema is empty.
add test

[VL] Support columnar table cache with count(1)

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala

`ColumnarOverrideRules` will be instanced per Spark session rather than per query, so better to use thread local to hold variable to make it thread safe. Including `oringalPlan` and `isAdaptiveContext`.
The local property of SparkContext is a little bit heavy that it would post it to executor side, so we should cleanup it before execution.
Pass CI

[CORE] Use thread local to hold original plan in ColumnarOverrideRules

---

.github/workflows/velox_be.yml
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHousePreferSpillColumnarShuffleAQESuite.scala
cpp/CMakeLists.txt
cpp/core/CMakeLists.txt
cpp/core/jni/JniCommon.h
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/LocalPartitionWriter.h
cpp/core/shuffle/ShuffleWriter.cc
cpp/core/shuffle/ShuffleWriter.h
cpp/core/shuffle/Utils.cc
cpp/core/shuffle/Utils.h
cpp/core/shuffle/rss/CelebornPartitionWriter.cc
cpp/core/shuffle/rss/CelebornPartitionWriter.h
cpp/core/shuffle/rss/RssClient.h
cpp/core/utils/DebugOut.h
cpp/core/utils/Timer.h
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/ShuffleSplitBenchmark.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc
docs/get-started/ClickHouse.md
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleWriterJniWrapper.java
gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

PreferSpill=true strategy can cause small file issue. After preferSpill=false has been implemented in Velox backend, the codepath of preferSpill=true is deprecated and no longer being tested and used for a long time.
This PR removes the preferSpill=true for LocalPartitionWriter in Velox backend. But keep the option for CH backend, and partially refactored CelebornPartitionWriter to keep the "evict immediately" behavior for Velox backend.
renamed `spark.gluten.sql.columnar.shuffle.preferSpill` -> `spark.gluten.sql.columnar.backend.ch.shuffle.preferSpill`
After this change, the spill will rely on the memory management and only be triggered by the Gluten Spiller. To make the allocated partition buffers reclaimable, it maintains a `SplitState` to help decide whether/when to shrink and the …

[VL] Remove preferSpill=true for VeloxShuffleWriter

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxColumnarBatchIterator.scala
cpp/velox/utils/ResourceMap.h

- Velox Parquet write operation now utilizes asynchronous writing for improved performance.  The batch will be placed into the VeloxWriteQueue in spark task. And a new thread will be spawned to retrieve the batch data, write it to the file, and close the batch after writing. Hence, we need to incorporate a locking mechanism in ResourceMap.
- Remove the twice close batch logic.
existing unit tests and jenkins tests.

[GLUTEN-3328][VL]Add mutex for ResourceMap operators

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
cpp/core/compute/ExecutionCtx.h
cpp/core/jni/JniWrapper.cc
cpp/core/memory/ColumnarBatch.cc
cpp/core/memory/ColumnarBatch.h
cpp/velox/compute/VeloxExecutionCtx.cc
cpp/velox/compute/VeloxExecutionCtx.h
cpp/velox/compute/VeloxPlanConverter.cc
cpp/velox/compute/VeloxPlanConverter.h
cpp/velox/operators/plannodes/RowVectorStream.h
cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
cpp/velox/operators/serializer/VeloxColumnarToRowConverter.cc
cpp/velox/operators/writer/VeloxParquetDatasource.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/tests/ExecutionCtxTest.cc
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala
gluten-data/src/main/java/io/glutenproject/columnarbatch/ColumnarBatchJniWrapper.java
gluten-data/src/main/java/io/glutenproject/columnarbatch/ColumnarBatches.java
gluten-data/src/main/java/io/glutenproject/vectorized/ColumnarBatchInIterator.java

This will be a follow-up to https://github.com/oap-project/gluten/pull/3290, discussion https://github.com/oap-project/gluten/pull/3290#discussion_r1336963596.
Current method to offload zero-column batch doesn't result in real issues in tests, but it can still be risky since conflicted states about column count are created on the offloaded columnar batches.
The PR removes the risky code by adding a per-task cache for the zero-column batches to let the batch-offloading procedure pick instances directly from it. The cache will be released after task ends.

[VL] Wrong #numCols() result for offloaded columnar batch whose vector count is zero

---

cpp/velox/compute/WholeStageResultIterator.cc

Add warn log when spill-to-disk configuration is not configured.
No need

[VL] Add warn log when spill config not configured

---

backends-velox/src/main/scala/io/glutenproject/utils/DatasourceUtil.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxColumnarBatchIterator.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxWriteQueue.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
cpp/core/jni/JniWrapper.cc
gluten-data/src/main/java/io/glutenproject/datasource/velox/DatasourceJniWrapper.java

Previously we mixed the use of Velox-related code in common JNI wrapper code. This is to clean up the code to make write API backend-independent.

[VL] Pull data-source JNI wrapper up to common module

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

The `numPartitions_` is set to `4096` for many jobs in our environment(`Meituan`), and the number of rows in a batch is also `4096`. 
The above configuration will result in some partitions not having rows, we need not iterate for all partitions(4096) but only the used partitions.
In order to avoid unnecessary iteration, I added a member data `partitionUsed` representing the partitions having values and then changed the loop based on all partitions to based on `partitionUsed`.
The performance will not be influenced if the `numPartitions_` configured a small value because the number of valid partitions will never be larger than the number of all partitions.
wait for a test under `meituan`'s environment, I will add the test result later.
(Fixes: …

[VL] Improving VeloxShuffleWriter performance by just iterating valid partitions

---

cpp/velox/shuffle/VeloxShuffleWriter.cc

this is a patch for [PR#3344](https://github.com/oap-project/gluten/pull/3344)
I am sorry for missing this loop-based `numPartitions`. 

[VL] Refine velox shuffle writer iteration using partitionUsed instead of all partitions

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsHandler.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/MetricsApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-data/src/main/scala/io/glutenproject/metrics/GenerateMetricsUpdater.scala

This pr adds output row metric for generate to align with vanilla Spark.

[VL] Add generate metrics

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsHandler.scala
cpp/core/shuffle/ShuffleWriter.h
cpp/core/shuffle/Utils.cc
cpp/core/shuffle/Utils.h
cpp/velox/shuffle/VeloxShuffleWriter.cc

After the refactor of split partition buffer compression, the buffers are compressed before creating IPC payload. Therefore, using IpcPayload's `raw_body_length` to count uncompressed buffer size is not correct.

[VL] Fix uncompressed size metrics

---

gluten-core/src/main/scala/io/glutenproject/GlutenPlugin.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Some configs should not allow users to change them during the session. We should make them static. And when getting session configs, static configs should be excluded.
(Fixes: \#1283)
Existing UTs.

[GLUTEN-1283][VL] Distinguish static/dynamic configs introduced for backend

---

backends-velox/src/main/scala/io/glutenproject/utils/DatasourceUtil.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/VeloxWriteQueue.scala
backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
cpp/core/jni/JniWrapper.cc
gluten-data/src/main/java/io/glutenproject/datasource/DatasourceJniWrapper.java

#3343 
The PR removes "velox" in data-source JNI wrapper's package name.

[VL] Following #3343, fix wrong package name for data-source JNI wrapper

---

cpp/velox/substrait/SubstraitParser.cc

Will be merged when velox code is aligned with upstream.
Fixes: #3388

[GLUTEN-3388][VL] Remove datediff function name mapping

---

cpp/core/jni/JniWrapper.cc
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/utils/Common.h

[VL] Improving performance by using xsimd::memcpy

---

cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

(Fixes: \#3400)
Test by UT and gluten-perf
name | before | after | diff
-- | -- | -- | --
q01 | 5126.00 | 5048.71 | 1.02
q02 | 3309.43 | 3183.57 | 1.04
q03 | 7167.43 | 6660.57 | 1.08
q04 | 4204.00 | 4163.43 | 1.01
q05 | 10623.43 | 10472.57 | 1.01
q06 | 2022.14 | 2023.71 | 1.00
q07 | 6966.29 | 6862.14 | 1.02
q08 | 12116.86 | 7194.57 | 1.68
q09 | 17585.71 | 11460.57 | 1.53
q10 | 7336.57 | 7024.86 | 1.04
q11 | 2416.29 | 2475.29 | 0.98
q12 | 4678.14 | 4663.57 | 1.00
q13 | 4614.57 | 4492.00 | 1.03
q14 | 3590.43 | 3589.43 | 1.00
q15 | 6266.29 | 6291.14 | 1.00
q16 | 6313.57 | 6100.00 | 1.04
q17 | 18222.00 | 12309.71 | 1.48
q18 | 19538.14 | 19063.71 | 1.02
q19 | 4779.86 | 4795.29 | 1.00
q20 | 12642.86 | 5918.00 | 2.14
q22 | 1494.57 | 1417.57 | 1.05
Total | 161014.57 | 135234.59 | 1.19
</body> …

[GLUTEN-3400][CH] Update backend named literal code

---

cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

Issue: #3267 
If the data to compress has lots of duplicated values, both LZ4 and ZSTD perform high compression ratio( ~10 - 20). If no duplicated values, LZ4 can result in no compression and ZSTD compression ratio is ~2.
For fixed-length binary types, Spark UnsafeRow stores its value, offset in UnsafeRow and length. If the data schema consists of several columns of fixed-width data type and fixed-length string types, the offsets and lengths of a string field are identical for all rows. But currently, Gluten use arrow-like format for shuffle output, which stores value offsets in the string column and is considered unfriendly for data compression.
The metrics below compares the data size of splitting 2 columns of fixed-length binary type and 1 column of integer type. Before this PR, Gluten …

[VL] Shuffle splitter store string length instead of offset

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxColumnarCacheSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpandFallbackPolicy.scala

Remove unnecessary ColumnarToRow for table cache, as it is internally supported. Mentioned at https://github.com/oap-project/gluten/pull/3368#discussion_r1354339248. Also includes some small code refactor.
New UT.

[VL] Remove ColumnarToRow for Gluten columnar table cache

---

cpp/core/CMakeLists.txt
cpp/core/compute/ExecutionCtx.h
cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/ShuffleReader.cc
cpp/core/shuffle/ShuffleReader.h
cpp/core/shuffle/ShuffleWriter.cc
cpp/core/shuffle/ShuffleWriter.h
cpp/core/shuffle/options.cc
cpp/core/shuffle/options.h
cpp/velox/compute/VeloxExecutionCtx.cc
cpp/velox/compute/VeloxExecutionCtx.h
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleReader.h
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/tests/ExecutionCtxTest.cc
cpp/velox/tests/VeloxShuffleWriterTest.cc
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarBatchSerializer.scala
gluten-data/src/main/java/io/glutenproject/vectorized/ShuffleReaderJniWrapper.java
gluten-data/src/main/scala/io/glutenproject/vectorized/ColumnarBatchSerializer.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenCoalesceShufflePartitionsSuite.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

1. Currently, buffer size < 1024B (default threshold) will not be compressed. If partition buffers are small (e.g. < 100 rows), it's likely that the data is not compressed and result in the shuffle data size larger than Vanilla spark. This PR change the default threshold unit and make the default threshold value 100 rows. Partition buffers that fall below the threshold will be copied into one buffer and compress.
2. Change Columnar shuffle metrics "data size total" from collecting input Velox RowVector size to uncompressed size and remove the "uncompressed size" metric.

[VL] Copy compress small partition buffer

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala

When Gluten calls the Velox Parquet writer to write a Parquet file, the temporary path obtained from Spark may not have been created yet. While writing a local file, Velox automatically creates the necessary file path if it does not exist. However, this is not the case for HDFS paths. We attempted to create the HDFS path on the Velox side, but the community was not receptive to this approach. As a result, we decided to create the HDFS path on the Gluten side.
manual local test

[GLUTEN-3425] Create not existing Hdfs folder in gluten side when writing hdfs file.

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/execution/CHFilterExecTransformer.scala
backends-clickhouse/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
backends-velox/src/main/scala/io/glutenproject/execution/FilterExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/BatchScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/SortMergeJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WindowExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/metrics/MetricsUpdater.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/python/EvalPythonExecTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
gluten-data/src/main/scala/io/glutenproject/metrics/MetricsUtil.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BatchScanExecShim.scala

1. Removes unused methods `getBuildPlans` and `getStreamedLeafPlan`
2. Add new triat `LeafTransformSupport` and `UnaryTransformSupport` to simplify `columnarInputRDDs`
3. Pull out `doExecute` and `supportsColumnar` to `TransformSupport`
4. remove `COLUMNAR_ITERATOR_ENABLED` config
Pass CI

[CORE] Simplify TransformSupport

---

cpp/velox/compute/WholeStageResultIterator.cc

To avoid partial aggreagation flushing on a low cardinality case.
Verified on TPC-DS.

[VL] Increase kAbandonPartialAggregationMinRows

---

docs/velox-backend-limitations.md

Refine the document about parquet write.
No need.

[VL][DOC] Refine the document about parquet write

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHMetricsApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/metrics/HashAggregateMetricsUpdater.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala

Fix incorrect metrics values for ch backend:
1. When there is a r2c operation, it will call iter.hasNext more than once, so the native metrics will be added more than once;
2. Add the resize metrics for ch agg operation.
Close #3480.
(Fixes: #3480)

[GLUTEN-3480] Fix incorrect metrics values for ch backend

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala

When there is a `MergeScalarSubqueries` which will create the named_struct with the same name,
looks like `{'bloomFilter', BF1, 'bloomFilter', BF2} or {'count(1)', count(1)#111L, 'avg(a)', avg(a)#222L, 'count(1)', count(1)#333L}`, 
it will cause problem for some backends, e.g. ClickHouse, which cannot tolerate duplicate type names in struct type, so we need to rename 'nameExpr' in the named_struct to make them unique after executing the `MergeScalarSubqueries`.
Close #3467.
(Fixes: #3467 )

[GLUTEN-3467] Fix 'Names of tuple elements must be unique' error for ch backend

---

gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala
shims/spark32/src/main/scala/io/glutenproject/sql/shims/spark32/Spark32Shims.scala
shims/spark33/src/main/scala/io/glutenproject/sql/shims/spark33/Spark33Shims.scala
shims/spark34/src/main/scala/io/glutenproject/sql/shims/spark34/Spark34Shims.scala
shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala

Fix the following compile issue when using `mvn clean install -Pbackends-velox -Prss -Pspark-3.4 -DskipTests ` command.
`[ERROR] /home/sparkuser/workspace/workspace/Gluten_Perf_ICX/gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala:28: error: value Empty2Null is not a member of object org.apache.spark.sql.execution.datasources.FileFormatWriter
[ERROR] import org.apache.spark.sql.execution.datasources.FileFormatWriter.Empty2Null
[ERROR]        ^
[WARNING] /home/sparkuser/workspace/workspace/Gluten_Perf_ICX/gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala:28: warning: Unused import
[WARNING] import org.apache.spark.sql.execution.datasources.FileFormatWriter.Empty2Null
[WARNING] …

[GLUTEN-3361]Fix the compile issue caused by wrong Empty2Null package in spark 3.4

---

package/pom.xml
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/InsertIntoHadoopFsRelationCommand.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/InsertIntoHadoopFsRelationCommand.scala

[GLUTEN-3459] Skip unnecessary local sort for static partition write

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionRoundHalfUp.h

[GLUTEN-3462][CH] Fix round mismatch 

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/jni/VeloxJniWrapper.cc
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Add new config `spark.gluten.sql.columnar.backend.velox.glogVerboseLevel` to control native glog verbose level and `spark.gluten.sql.columnar.backend.velox.glogSeverityLevel` to control native glog severity, default value is same as glog, [doc](https://github.com/google/glog).
By this config, user can easily control both Gluten and Velox log level at runtime.
Also change DLOG to VLOG to enable such logs without recompile, more bigger number in VLOG means more detailed message.

[VL] Add config for glog verbose level and severity level

---

cpp/velox/CMakeLists.txt
cpp/velox/operators/functions/RegistrationAllFunctions.cc
cpp/velox/operators/functions/RowConstructorWithNull.cc
cpp/velox/operators/functions/RowConstructorWithNull.h
cpp/velox/operators/functions/RowFunctionWithNull.h
ep/build-velox/src/get_velox.sh

Removes https://github.com/oap-project/velox/commit/556839d927ca77f4288ca89977dab70a7f9493d7 by registering `row_constructor_with_null` in Gluten.
https://github.com/oap-project/velox/pull/420

[VL] Register row_constructor_with_null

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDecimalSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHAbstractSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala

[GLUTEN-3450][CH] Support allowPrecisionLoss=false

---

cpp/core/compute/Runtime.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h

Overload `<<` operator for SparkTaskInfo, after that, it can be used as `LOG(INFO) << taskInfo;`, hence, build mapping between java log and native log.
```
I1020 10:07:57.491497 2704501 VeloxExecutionCtx.cc:82] [Stage: 9 TID: 9]
23/10/20 10:07:57 WARN [Executor task launch worker for task 0.0 in stage 9.0 (TID 9)] xxx
```
Also pass it to WholeStageIterator as member variable.

[VL] Add stream insertion operator for SparkTaskInfo on native side

---

cpp/velox/compute/VeloxBackend.cc

```
W1019 12:38:42.899380 996562 Connector.cpp:39] ConnectorFactory with name hive is already registered.
```

[VL] Remove unnecessary registerConnectorFactory for HiveConnector

---

cpp/velox/substrait/SubstraitToVeloxPlan.cc

Use existing constructor for `BigintRange` and `MultiRange` in Velox.
Revert constructor changes with https://github.com/oap-project/velox/pull/423.
under test

[VL] Use existing constructor for BigintRange and MultiRange

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
backends-velox/src/test/scala/io/glutenproject/execution/VeloxColumnarCacheSuite.scala

This pr fixes a bug when the consumer side selects the different ordering attributes with the original cached plan. We should reorganize the columnar batch.
add test

[VL] Fix cache output if selectedAttributes has wrong ordering with cacheAttributes

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseNativeWriteTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseSyntheticDataSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCDSAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHAbstractSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickhouseFunctionSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/CustomAggExpressionTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/GlutenCustomAggExpressionSuite.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/catalyst/expressions/aggregate/CustomSum.scala
cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.cpp
cpp-ch/local-engine/Parser/aggregate_function_parser/CommonAggregateFunctionParser.h
cpp-ch/local-engine/Parser/example_udf/customSum.cpp
docs/get-started/ClickHouse.md
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpressionExtensionTrait.scala

When transforming HashAggregateExec, it needs to get attributes from the aggregate function, but if there are some custom aggregate functions, it can not handle these custom aggregate functions when transforming.
Reuse ExpressionExtensionTrait to support this feature, add a new function called getAttrsForExtensionAggregateExpr to handle this.
Close #3511.
(Fixes: #3511)

[GLUTEN-3511][CORE] Support to add custom aggregate functions for extension

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxDataTypeValidationSuite.scala
cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh

Fixed issues when using latest rebased velox (10/25).
1. Latest velox doesn't allow redundant or overlapped partition/sort keys. Considering this is not a common use case, just modified a UT to skip this case. Also filed an issue: https://github.com/oap-project/gluten/issues/3528
2. As a deprecated constructor for `QueryCtx` is removed, fixed a native compile issue caused by it.

[VL] Adapt to latest rebased velox (10/25)

---

cpp/core/shuffle/LocalPartitionWriter.cc

Make the configured directories in random order, to avoid each task creating local spilled files in the same directory.

[Core] Shuffle the configured directories before use

---

ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh
ep/build-velox/src/modify_arrow.patch
ep/build-velox/src/modify_velox.patch

Removes build script changes to Velox by applying patch from Gluten to Velox.
https://github.com/oap-project/velox/pull/425
under test

[VL] Apply patch to Velox for compilation

---

cpp/core/memory/Evictable.h
cpp/core/shuffle/ShuffleWriter.h
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/tests/VeloxShuffleWriterTest.cc
cpp/velox/tests/utils/SelfEvictedMemoryPool.h

For single partitioning, the SplitState is always `kInit` during split. Therefore, the check of whether cached payloads are clear should not be applied to single partitioning.
This PR also adds `Evictable` interface and `SelfEvictedMemoryPool`, which can be used in unit test to mock the behavior of invoking the `evictFixedSize` API by Spark's memory management during memory allocation failure.
Below code demonstrates how to use in UT:
```
auto pool = defaultArrowPool().get();
auto mockingPool = SelfEvictedMemoryPool(pool);
auto evictable = Evictable(&mockingPool);
mockingPool.setEvictable(&evictable);
mockingPool.setCapcity(100); // When trying to allocate > 100 bytes, it will call evictable->evictFixedSize to trigger self-evict
```

[VL] Fix single partitioning evict error

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

ShuffleWriter supports spilling initiated both internally and by other operators. However, it shouldn't self-trigger a spill during the spilling process. Because during a spill, it can invoke memory allocation APIs that triggers another spill, like when resizing the partition buffers."
This PR prevents the following call stack:
[Spill triggered by some op] -> ShuffleWriter.spill -> reserveMemory -> trigger spill another time -> ShuffleWriter.spill

[VL] Add EvictGuard to avoid spilling recursively in ShuffleWriter

---

gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornPartitionPusher.scala
gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriter.scala

Optimize the performance of Celeborn's pushPartitionData
Observing from the flame graph, it can be seen that the celebornConf.clientPushBufferMaxSize parameter in the pushPartitionData method is causing significant performance overhead.

[CELEBORN] Optimize the performance of Celeborn's pushPartitionData

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HivePartitionConverter.scala

Support hivetransform use `mapreduce.input.fileinputformat.input.dir.recursive`
(Fixes: \#3535)
Test by ut

[GLUTEN-3535][CH] Support hive transform dirs recursive

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala

Currently when judging whether supports pre-project for the shuffle, it only check whether is Cast expression. It must check whether is the supported expression.
Close #3534.
(Fixes: #3534)

[GLUTEN-3534][CH] Fix incorrect logic of judging whether supports pre-project for the shuffle

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala

This pull request fix the issue of incorrectly creating an HDFS path when writing a Parquet file into the HDFS directory.
Local jenkins test.

[GLUTEN-3425] [VL] Fix the issue of incorrectly creating an HDFS path when writing a Parquet file into the HDFS directory

---

cpp/core/shuffle/ShuffleWriter.h
cpp/velox/CMakeLists.txt
cpp/velox/shuffle/VeloxShuffleReader.cc
cpp/velox/shuffle/VeloxShuffleUtils.cc
cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc
cpp/velox/utils/Common.h
cpp/velox/utils/VeloxArrowUtils.cc
cpp/velox/utils/VeloxArrowUtils.h

Currently, there are inconsistencies in the shuffle writer code related to namespaces and return types.
1. **Namespace Usage:** In some instances, the prefix velox:: is used, such as `velox::RowVector`. In others, there is no prefixed namespace, simply using `RowVector`. It would be better to consistently use the full namespace: `facebook::velox::RowVector`.
2. **Return Types:** Some parts of the code return `arrow::Status` or `arrow::Result`, while others throw exceptions. This inconsistency complicates our C++ unit tests, making it unclear whether to check for exceptions or inspect the returned status code. A uniform approach should be adopted, returning `arrow::Status` and `arrow::Result` where applicable.

[VL] Refine shuffle writer return types and namespace

---

backends-velox/src/test/scala/io/glutenproject/execution/FallbackSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpandFallbackPolicy.scala

It has no meaning to add ColumnarToRow eagerly if we will add it finally. So we ignore the ColumnarToRow to avoid fallback eagerly. It is useful if people set fallback threshold to 1.
For example: 1 is better than 2
```
1. We first run native operator then add ColumnarToRow
ColumnarExchange
|
HashAggregateTransformer
|
ColumnarToRow
2. We first add ColumnarToRow then run vanilla Spark operator
ColumnarExchange
|
ColumnarToRow
|
HashAggregate
```
add test

[CORE] Do not fallback eagerly with ColumnarToRowExec

---

cpp/velox/compute/WholeStageResultIterator.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Use Spark's existing option `spark.io.compression.codec` as Velox backend's spill codec.

[VL] Use value of spark.io.compression.codec as Velox's spill codec

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BroadcastBuildSideRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashJoinExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageZippedPartitionsRDD.scala

In WholeStageTransformer, the columnarInputRDDs would contain BroadcastBuildSideRDD, but the dependency and partition of BroadcastBuildSideRDD is meaningless. BroadcastBuildSideRDD should only be used to hold the broadcast value and generate iterator for hash join.
PASS CI

[CORE] Simplify WholeStageTransformer and BroadcastBuildSideRDD

---

gluten-core/src/main/scala/io/glutenproject/extension/ExpandFallbackPolicy.scala

When making a stage fallback, an extra ColumnarToRow may be required to adapt to the columnar output of last query stage(s). So this cost may need to be considered to get a net fallback number.
An existing UT covers it.

[CORE] Consider the cost when applying stage fallback policy

---

cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/VeloxRuntime.h
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/compute/WholeStageResultIterator.h
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/memory/VeloxMemoryManager.h
ep/build-velox/src/get_velox.sh
gluten-data/src/main/java/io/glutenproject/memory/nmm/LoggingReservationListener.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManager.java

I've done some work to minimize the for-pick PR https://github.com/facebookincubator/velox/pull/5790, the change included in this patch would be needed for Gluten then.

[VL] In OAP Velox fork, simplify shrinking/spilling code for Velox memory pool

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHNativeExpressionEvaluator.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
gluten-core/src/main/java/io/glutenproject/substrait/plan/PlanBuilder.java
gluten-core/src/main/scala/io/glutenproject/execution/GlutenWholeStageColumnarRDD.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/test/scala/org/apache/spark/softaffinity/SoftAffinitySuite.scala
gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java

(Fixes: \#3590)
manual tests
Before: These 132785 GlutenPartitions will consume over 30 GB of memory.
After: They only consume over 1 GB of memory.

[GLUTEN-3590][CORE] Reduce driver memory usage by using serialized bytes for substrait plan in GlutenPartition

---

cpp/velox/memory/VeloxColumnarBatch.cc

Reset the buffer before calling the serialize API when getting the first row bytes.
https://github.com/oap-project/gluten/issues/3596
S3 env test

[GLUTEN-3596][VL] Clear the buffer before calling UnsafeRowFast.serialize API

---

tools/gluten-it/common/src/main/java/io/glutenproject/integration/tpc/command/Parameterized.java

The bug is trivial and was not covered by testing.

[VL] Gluten-it: Fix a trivial cli parameter parsing bug

---

cpp/core/jni/JniWrapper.cc
cpp/core/shuffle/LocalPartitionWriter.cc
cpp/core/shuffle/Utils.cc
cpp/core/shuffle/Utils.h
cpp/core/shuffle/options.h
cpp/core/utils/StringUtil.cc
cpp/core/utils/StringUtil.h
cpp/core/utils/macros.h
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/ShuffleSplitBenchmark.cc
cpp/velox/benchmarks/common/BenchmarkUtils.cc
cpp/velox/benchmarks/common/BenchmarkUtils.h
cpp/velox/udf/UdfLoader.cc
cpp/velox/utils/tests/VeloxShuffleWriterTestBase.h

Currently, shuffle writer local directories are setting through environment variable "GLUTEN_SPARK_LOCAL_DIRS", which is a historical issue and should be refined.
This PR removes setting/getting local directories through environment variable from JNI code path and keep the environment variable "GLUTEN_SPARK_LOCAL_DIRS" only for generic benchmark simulating spilling multiple disks.

[VL] Refine setting shuffle writer local directories

---

backends-clickhouse/src/main/java/io/glutenproject/vectorized/BlockSplitIterator.java
backends-clickhouse/src/main/java/io/glutenproject/vectorized/CHShuffleSplitterJniWrapper.java
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/main/scala/org/apache/spark/shuffle/CHColumnarShuffleWriter.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala
cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
cpp-ch/local-engine/Shuffle/NativeSplitter.cpp
cpp-ch/local-engine/Shuffle/NativeSplitter.h
cpp-ch/local-engine/Shuffle/ShuffleSplitter.cpp
cpp-ch/local-engine/Shuffle/ShuffleSplitter.h
cpp-ch/local-engine/local_engine_jni.cpp
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornHashBasedColumnarShuffleWriter.scala

Now the hash algorithm of the ch shuffle hash partitioner is cityHash64, which is different from vanilla spark, when there is one side shuffle of the join fallbacking, the hash id are different between the ch and vanilla spark, so add a configuration to control the hash algorithm for the ch shuffle hash partitioner.
Close #3598.
(Fixes: #3598)

[GLUTEN-3598][CH] Support to config the hash algorithm for the ch shuffle hash partitioner

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetAQESuite.scala

The ch murmurHash3_32 function is not compatible of the vanilla spark function, using sparkMurmurHash3_32 function instead of it.

[HOTFIX][CH] Using sparkMurmurHash3_32 function instead of the murmurHash3_32 for the shuffle hash algorithm

---

cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxPlan.cc

Use aligned function names with Velox upstream.
under test

[VL] Align names of decimal compare functions

---

docs/get-started/Velox.md
gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornHashBasedColumnarShuffleWriter.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenImplicitsTest.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala

This pr adds a a helper class to get the Gluten fallback summary from a Spark Dataset. If AQE is enabled, but the query is not materialized, then this method will re-plan the query execution with disabled AQE. It is a workaround to get the final plan, and it may cause inconsistent results with a materialized query. However, we have no choice.
For example:
```scala
import org.apache.spark.sql.execution.GlutenImplicits._
val df = spark.sql("SELECT  FROM t")
df.fallbackSummary
```
add test

[CORE] Add GlutenImplicits to get FallbackSummary easily

---

backends-clickhouse/src/test/resources/text-data/field_whitespaces/data.txt
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
cpp-ch/local-engine/Common/CHUtil.cpp

[GLUTEN-3552][CH] Bug fix csv read field whitespaces

---

.github/workflows/velox_be.yml

To test Q23A/Q23B within 3 different partial aggregation modes:
1. PARTIAL_MODE:ABANDONED
Abandons partial aggregation immediately
2. PARTIAL_MODE:CACHED
Do full partial aggregation, use as much of memory as possible
3. PARTIAL_MODE:FLUSHED
Partial flushes data when reaching 0.1 * executor off-heap memory limit
Q97 is basically for testing distinct aggregation.
The failures are ignored until the related OOM issues are fixed.

[VL] GHA CI: Add cases for aggregation within limited memory

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/CustomAggExpressionTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpressionExtensionTrait.scala

There are many processes in the `getAttrForAggregateExprs` method that construct aggregateAttr and index for specific aggFuncs. In fact, the patterns of these processes are consistent. They iterate over `inputAggBufferAttributes` of aggFunc, transform them, and insert them into `aggregateAttr`. Then, they increase the count in index for each insertion. The logic for validating the supported modes of different aggFuncs is the only specific part, which can be extracted separately.
Exists CI

[CORE] Remove unnecessary case match in getAttrForAggregateExpr

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenFunctionValidateSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/RewriteDateTimestampComparisonRule.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Fixes: #3141
Test result is given as following.
data set
```sql
CREATE TABLE default.test_time_cmp (ts INT, val INT) USING parquet;
insert into test_time_cmp select 1693497600 + (rand() * 1000000000) % 2592000 as ts, id as val from range(0, 10000000);
```
performance comparison
| condition   |      before      |  after |
|----------|:-------------:|:------:|
| from_unixtime(ts, 'yyyy-MM-dd') > '2023-09-15' |   0.862 seconds | 0.367 seconds |
| from_unixtime(ts, 'yyyy-MM-dd') >= '2023-09-15' |    0.879 seconds  |   0.347 seconds |
| from_unixtime(ts, 'yyyy-MM-dd') < '2023-09-15' | 0.887 seconds |    0.334 seconds |
| from_unixtime(ts, 'yyyy-MM-dd') < '2023-09-15' |  0.919 seconds |     0.319 seconds |
| from_unixtime(ts, 'yyyy-MM-dd') = …

[GLUTEN-3141][CH] Rewrite date comparison expression into a more efficient way

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala

The native Parquet writer may call `hasNext `more than once. However, in the current code, when the first `hasNext `call returns false, the resources are released. As a result, when the second `hasNext `call is made, it throws the following exception. This PR adds protection to allow multiple hasNext calls on the Scala side.
```
o.glutenproject.exception.GlutenException: java.lang.RuntimeException: failed to get batch iterator
at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:39)
at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
at io.glutenproject.utils.IteratorCompleter.hasNext(Iterators.scala:68)
at io.glutenproject.utils.PayloadCloser.hasNext(Iterators.scala:34)
at …
```

[VL] Fix failed to get iterator exception

---

backends-clickhouse/pom.xml
backends-velox/pom.xml
gluten-celeborn/clickhouse/pom.xml
gluten-celeborn/package/pom.xml
gluten-core/pom.xml
gluten-ut/pom.xml
package/pom.xml
pom.xml
shims/common/pom.xml
shims/pom.xml
shims/spark32/pom.xml
shims/spark33/pom.xml
shims/spark34/pom.xml

- Remove the profile in shim and ut module, so when we add a new Spark version, we do not need change these two modules. Instead, add spark.shim.module and spark.test.module.
- Remove spark32, spark33, spark34 properties, we only need spark.version and change it in each spark version profile
- Remove the spark-hive-thriftserver dependency
PASS CI

[CORE] Refine maven Spark dependency

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/clickhouse.version
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

[GLUTEN-1632][CH]Daily Update Clickhouse Version (20231108)

---

docs/developers/UsingGperftoolsInCH.md

[CH] Add using gperftools doc for CH

---

gluten-ut/pom.xml
pom.xml
shims/pom.xml

Fix IDEA load module issue
manually test

[GLUTEN-3625][FOLLOWUP] Fix IDEA load module issue

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/CustomAggExpressionTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/GlutenCustomAggExpressionSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpressionExtensionTrait.scala

In PR #3629, it removes the logic to support the custom aggregate functions, must be reverted.
Close #3644.
(Fixes: #3644)

[GLUTEN-3644][CH] Revert the logic to support the custom aggregate functions

---

.github/workflows/velox_be.yml
cpp/CMakeLists.txt
cpp/compile.sh
docs/get-started/GlutenUsage.md
docs/get-started/Velox.md

- After this PR #3341 , Arrow will be used from Velox and will not be compiled separately. So, removed the `--arrow_home` flag which is not needed anymore.
- Updated documentation.
Tested manually by running the script

[GLUTEN-3572][VL] Remove --arrow_home option and fix "libarrow not found" in debug mode

---

cpp/velox/substrait/SubstraitToVeloxPlan.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

In the upstream Velox, it is ensured that the sorting key is unique in TopNode [here](https://github.com/facebookincubator/velox/pull/7172). Therefore, we add a check for this in this PR.
Pass CI.

[VL] [Test] Test rebasing upstream velox 11_8

---

.github/workflows/stale.yml

Auto close stale pull request after 45 days
not tests required

[CI] Improve CI to auto close stale patch

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h

Extract the duplicated logic in both `resizePartitionBuffer` and `allocatePartitionBuffer`.
In prealloc partition buffer, use `resizePartitionBuffer` instead of `allocatePartitionBuffer` if need to preserve buffer data for the next split, and remove the resize branch in `allocate PartitionBuffer`.

[VL] Refactor split buffer allocation

---

gluten-core/src/main/scala/io/glutenproject/utils/Iterators.scala

[GLUTEN-3637][VL] Fix whole stage pipeline metric

---

cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/execution/LimitTransformer.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

The `TakeOrderedAndProjectExec `will be transformed into either a sort + limit or directly into a limit operation. If it is a sort + limit case, Velox will convert it into a `TopNNode`. Here, we need to do some validation on the `TopNNode`.
Pass Jenkins test

[GLUTEN-3654][VL]Fix the duplicated key exception in TopN

---

gluten-ut/pom.xml
pom.xml
shims/pom.xml

Before this pr the follow cmd can not change the project version for sub-module. It seems the maven plugin compatibility is not very good for using property value module name. So this pr reverts the change and go back to use the profile to specify the sub-module to avoid potential issue.
```
mvn versions:set -DgenerateBackupPoms=false \
-DnewVersion="1.0.x" \
-Pspark-3.2,spark-3.3,spark-3.4 -Pbackends-velox -Pspark-ut -Prss
```
manully test

[GLUTEN-3625][FOLLOWUP] Always use the hardcode module name

---

cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

Use `spark.gluten.sql.columnar.backend.ch.runtime_settings.max_block_size` controller read mergetree bolck size. Defalut is `DEFAULT_BLOCK_SIZE`=65409
(Fixes: \#3667)
Test by UT.

[CH-3667] Use `max_block_size` controller read mergetree block size

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

PR #3169 add some functions to convert string to date, which leads to performance regression serious. Will be reverted first and raise another pr to fix the issue later.
Test case, 2000W records:
before PR #3169 : 3s
after PR #3169: 3.6m
Related PR: #3169, #3563;

[GLUTEN-3668][CH] Performance regresses seriously after PR 3169 merge when executing convert string to date

---

gluten-core/src/main/scala/io/glutenproject/execution/ExpandExecTransformer.scala

Before this pr, the ExpandExecTransformer would miss input. It does not affect the result for now, but better to avoid potential issue in future.
Pass CI

[CORE] Fix ExpandExecTransformer miss input

---

backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala

We should not use intermediate types' size to distinguish between different agg functions, it is not rigorous. Different agg functions may have the same number of intermediate types, but these types may be completely different.
Exists CI.

[VL] Declare IntermediateTypes for specific agg function

---

cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala

including translate, add_months, date_format, array_min, array_max.
These are already enabled in Velox, need to be removed from blacklist
Spark UTs covers the tests.

[VL] Enable Spark functions for `translate`, `add_months`, `array_min`, `array_max`

---

pom.xml

new security issue reported by github:
In FasterXML jackson-databind 2.4.0-rc1 until 2.12.7.1 and in 2.13.x before 2.13.4.2 resource exhaustion can occur because of a lack of a check in primitive value deserializers to avoid deep wrapper array nesting, when the UNWRAP_SINGLE_VALUE_ARRAYS feature is enabled. This was patched in 2.12.7.1, 2.13.4.2, and 2.14.0.
pass GHA

[VL] bump faster xml version to 2.13.5

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala

1. Fix the validate check for Generate operator while parsing substrait to velox;
2. Fix the missing validate check for ifthen, such as `select explode(case a is null then array('test') else array(a) end) from test_string`;
3. Fix the validate failed while passing a `Alias` to Generate, such as `select all, a from (select split(a, '2') as al, a from test_string) lateral view explode(al) as all;`;
4. [mirror] add `from_json` to black_list since it is not support now;
unit and manul tests

[VL] Fix: add validate check for Generate

---

cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp

[GLUTEN-3689][CH]use s3 file last modified time as cache update line

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/CustomAggExpressionTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/GlutenCustomAggExpressionSuite.scala
cpp-ch/local-engine/Parser/example_udf/customSum.cpp
gluten-core/src/main/scala/io/glutenproject/expression/AggregateFunctionsBuilder.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpressionExtensionTrait.scala

Support mapping one custom aggregate function to more than one backend functions, like first/last function, they will be mapped to two backend function names according to the ignoreNulls parameter.
Close #3705 .
(Fixes: #3705)

[GLUTEN-3705][CORE] Support mapping one custom aggregate function to more than one backend functions

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h

Closes https://github.com/oap-project/gluten/issues/3711
Compilation fails with:
```
VeloxBackend.cc:204:13: error: cannot convert ‘const facebook::velox::Config*’ to ‘const std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&’
204 |   printConf(veloxcfg);
|             ^~~~~~~~
|             |
|             const facebook::velox::Config*
```
Fix by modifying the method to take a `facebook::velox::Config` instead.

[GLUTEN-3711][VL] Fix `printConf` to Support Velox Config 

---

.github/workflows/velox_tpch_merge.yml
docs/developers/HowTo.md
docs/developers/NewToGluten.md

As in https://github.com/oap-project/gluten/issues/3635, gluten currently relies on arrow in Velox. This means the build-arrow stuff has been removed.
Most of the necessary docs changes were covered in https://github.com/oap-project/gluten/pull/3573/files but a couple small details were missed. 
Docs have been updated here to remove reference to the build-arrow paths.

[GLUTEN-3635][VL] Clean up docs related to `build-arrow` paths 

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/CustomAggExpressionTransformer.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/extension/GlutenCustomAggExpressionSuite.scala

With CH backend, in the final stage, the agg schema names must be the `agg_function#exprId#Partial#custom_sum`, after mapping the agg function to the other name, it does not modify according to the new one.
(Fixes: \#3705)

[GLUTEN-3705][FOLLOW][CH] Set the correct agg schema names after mapping one agg function to the other name

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
gluten-data/src/main/java/io/glutenproject/vectorized/NativePlanEvaluator.java

Fix the runtime  handle leak on driver side when we do native validation.
Pass CI

[CORE] Fix validation runtime handle leak

---

cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
cpp/velox/shuffle/VeloxShuffleReader.cc
ep/build-velox/src/get_velox.sh

rebase velox to 20231114
ByteStream is replaced by ByteInputStream. Velox PR: https://github.com/facebookincubator/velox/pull/7541

[VL] rebase velox to 20231114

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
cpp-ch/local-engine/Builder/SerializedPlanBuilder.cpp
cpp-ch/local-engine/Join/StorageJoinFromReadBuffer.cpp
cpp-ch/local-engine/Shuffle/CachedShuffleWriter.cpp
cpp-ch/local-engine/Shuffle/NativeSplitter.cpp
cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
cpp-ch/local-engine/Shuffle/PartitionWriter.h
cpp-ch/local-engine/Shuffle/ShuffleReader.cpp
cpp-ch/local-engine/Shuffle/ShuffleReader.h
cpp-ch/local-engine/Shuffle/ShuffleSplitter.cpp
cpp-ch/local-engine/Shuffle/ShuffleSplitter.h
cpp-ch/local-engine/Shuffle/ShuffleWriter.cpp
cpp-ch/local-engine/Shuffle/ShuffleWriter.h
cpp-ch/local-engine/Storages/IO/AggregateSerializationUtils.cpp
cpp-ch/local-engine/Storages/IO/AggregateSerializationUtils.h
cpp-ch/local-engine/Storages/IO/NativeReader.cpp
cpp-ch/local-engine/Storages/IO/NativeReader.h
cpp-ch/local-engine/Storages/IO/NativeWriter.cpp
cpp-ch/local-engine/Storages/IO/NativeWriter.h
cpp-ch/local-engine/Storages/SourceFromJavaIter.cpp
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/adaptive/GlutenAdaptiveQueryExecSuite.scala

Optimize aggregate state serialization performance, convert fixed size agg state to fixed string,  
convert variable size aggregation state to string.

[CH] Optimize aggregate state serialization performance 

---

.github/workflows/stale.yml

follow up #3634 
Increase the operations per run to 300 
The default value is 30, which seems too small for gluten project

[CI] increase operations per run for stale action

---

pom.xml

Set the default `spark.version` to 3.4.1 to fix the security issues reported by local code scan 
Note this will be overwrite in each profile
pass GHA

[CORE] set default spark.version to 3.4.1

---

cpp/velox/substrait/SubstraitToVeloxPlan.cc
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetColumnIndexSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetColumnIndexSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetColumnIndexSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala

Gluten tried to do a filter binding against subfield but actually not all subfields have corresponding filter. For example, `select * from table where a > 0` where `table` has cols `a` and `b`, so there is no need to do filter binding for `b` at all.
UT added

[VL]Avoid unnecessary filter binding for subfield

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala
backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ClickHouseAppendDataExec.scala
backends-clickhouse/src/test/scala/org/apache/spark/sql/execution/benchmarks/CHParquetReadBenchmark.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
gluten-core/src/main/java/io/glutenproject/substrait/rel/ExtensionTableNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesBuilder.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/LocalFilesNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadRelNode.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/ReadSplit.java
gluten-core/src/main/java/io/glutenproject/substrait/rel/SplitInfo.java
gluten-core/src/main/scala/io/glutenproject/backendsapi/IteratorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/BasicScanExecTransformer.scala
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
gluten-core/src/main/scala/io/glutenproject/substrait/SubstraitContext.scala
gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinityUtil.scala
gluten-core/src/test/scala/org/apache/spark/softaffinity/SoftAffinitySuite.scala

The Lake format has its own custom partition type, with a processing logic that is different from the existing `FilePartition` and `GlutenMergeTreePartition`. In the unified design, the Lake format will have its own scan transformer. In order to ensure that the injection of the Lake format does not affect gluten-core, the process of generating `LocalFilesNode` from handling partitions needs to be moved to the scan transformer, allowing the Lake format's scan transformer to customize the processing logic of the partitions.
Introduce ReadSplit interface for ExtensionTableNode and LocalFileNode, so that we can get rid of using java.io.Serializable.
Exists CI.

[GLUTEN-3378][CORE] Move getLocalFilesNode logic to scan transformer

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Functions/SparkFunctionToDate.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

(Fixes: \#3668)
TEST BY UT
性能测试数据
3000W 行正常数据 
测试SQL: `select count(1) from $test_tbl where to_date($col) > '1990-01-01'`
PR改动前耗时： 2.983s， 2.686s,   2.804s
PR改动后耗时： 2.94s，2.861s，2.842s；
3000W行数据 (其中2500W行是NULL，500W是正常数据)
测试SQL:  `select count(1) from $test_tbl where to_date($col) > '1990-01-01'`
PR改动前耗时：0.621s， 0.614s,  0.677s
PR改动后耗时：0.631s，0.641s，0.692s；
3000W行数据 (其中2500W数据是不符合日期格式的随机字符串，500W行是正常数据) 
测试SQL: `select count(1) from $test_tbl where to_date($col) > '1990-01-01'`
PR改动前耗时：6.148s，6.018s，5.845s
PR改动后耗时：3.188s，3.055s，3.08s
对比发现，正常数据测试情况下性能接近，在某些异常场景下性能有所提升

[GLUTEN-3668][CH]Fix to_date function performance

---

ep/build-velox/src/build_velox.sh

remove redundant velox build
(Fixes: #3749)
pass GHA

[GLUTEN-3749][VL] fix redundant Velox build

---

.github/workflows/velox_be.yml

Enable random-kill-task job to avoid stability regressions, e.g. core dump on task-killing.
The random-kill-task job: Use gluten-it's random task killing feature to emulate task kill requests randomly when a query is running. The query still has to succeed, without crashes or fatal errors since the killed tasks will be rescheduled by Spark's task scheduler.

[VL] Activate random kill tasks GHA CI job

---

cpp/velox/compute/VeloxBackend.cc

Fix the following compile error in debug mode.
```
/mnt/DP_disk1/sparkuser/projects/gluten/cpp/velox/compute/VeloxBackend.cc: In member function ‘void gluten::VeloxBackend::init(const std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)’:
/mnt/DP_disk1/sparkuser/projects/gluten/cpp/velox/compute/VeloxBackend.cc:204:13: error: cannot convert ‘const facebook::velox::Config*’ to ‘const facebook::velox::Config&’
204 |   printConf(veloxcfg);
|             ^~~~~~~~
|             |
|             const facebook::velox::Config*
/mnt/DP_disk1/sparkuser/projects/gluten/cpp/velox/compute/VeloxBackend.cc:111:61: note:   initializing argument 1 of ‘void gluten::VeloxBackend::printConf(const facebook::velox::Config&)’
111 | void VeloxBackend::printConf(const …
```

[VL] [Minor] Fix compile error in debug mode

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetRFSuite.scala
cpp-ch/local-engine/AggregateFunctions/AggregateFunctionGroupBloomFilter.h

When there are more than one input row in the final stage with the bloom_filter_agg, it will be core dump for the CH backend.
The RC is: when merging values in the final stage, the input data maybe a non-init AggregateFunctionGroupBloomFilterData, it will use the wrong filter size and filter_hashes values to init the first AggregateFunctionGroupBloomFilterData, which leads to set the wrong filter size when merging values.
Close #3779.
(Fixes: #3779)

[GLUTEN-3779][CH] Fix core dump when executing sql with runtime filter

---

dev/package.sh

update pacakge.sh to cover spark34

[VL] update pacakge.sh for spark34

---

cpp/core/compute/Runtime.h
cpp/core/config/GlutenConfig.cc
cpp/core/config/GlutenConfig.h
cpp/core/jni/JniWrapper.cc
cpp/velox/benchmarks/GenericBenchmark.cc
cpp/velox/benchmarks/QueryBenchmark.cc
cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/VeloxRuntime.h
cpp/velox/tests/RuntimeTest.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Use spark.gluten.sql.debug to enable print static/session config, print json plan.

[VL] Respect spark.gluten.sql.debug in native side

---

cpp/velox/operators/writer/VeloxParquetDatasource.cc

When specifying row group options, "parquet.block.size" was not respected, e.g.
```
df.write.format("parquet")
.mode("overwrite")
.option("parquet.block.rows",1048576)
.option("parquet.block.size", 1000000000)
.save(s"{outputPath}")
```
Verified locally.

[VL] Minor - Fix parquet writer passing wrong param

---

cpp/velox/compute/VeloxRuntime.cc
cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/utils/ConfigExtractor.cc
cpp/velox/utils/ConfigExtractor.h
docs/get-started/Velox.md
gluten-core/src/main/scala/io/glutenproject/execution/WholeStageTransformer.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

This pr adds two things:
1. Support inject native plan string to Spark explain, e.g.,
`--conf spark.gluten.sql.injectNativePlanStringToExplain=true`
```
(9) WholeStageCodegenTransformer (2)
Input [6]: [c1#0L, c2#1L, c3#2L, c1#3L, c2#4L, c3#5L]
Arguments: false
Native Plan:
-- Project[expressions: (n3_6:BIGINT, "n0_0"), (n3_7:BIGINT, "n0_1"), (n3_8:BIGINT, "n0_2"), (n3_9:BIGINT, "n1_0"), (n3_10:BIGINT, "n1_1"), (n3_11:BIGINT, "n1_2")] -> n3_6:BIGINT, n3_7:BIGINT, n3_8:BIGINT, n3_9:BIGINT, n3_10:BIGINT, n3_11:BIGINT
-- HashJoin[INNER n1_1=n0_1] -> n1_0:BIGINT, n1_1:BIGINT, n1_2:BIGINT, n0_0:BIGINT, n0_1:BIGINT, n0_2:BIGINT
-- TableScan[table: hive_table, range filters: [(c2, Filter(IsNotNull, deterministic, null not allowed))]] -> n1_0:BIGINT, n1_1:BIGINT, n1_2:BIGINT
-- ValueStream[] -> …
```

[CORE][VL] Add naitve plan string and plan with stats

---

backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetWriterInjects.scala
cpp/core/config/GlutenConfig.h
cpp/velox/operators/writer/VeloxParquetDatasource.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

The default window size for gzip compression is 32k. To generate a gzip parquet file with a 4k window size, set the writer option `parquet.gzip.windowSize` to 4096. Any other values will be ignored, and the default value of 32k will be used.
```
df.write.format("parquet")
.mode("overwrite")
.option("compression", "gzip")
.option("parquet.gzip.windowSize", 4096)
.option("parquet.block.rows",1048576)
.option("parquet.block.size", 1000000000)
.save(f"file:///mnt/DP_disk2/parquet_write_result/lineitem")
```

[VL] Add configuation for generating 4k window size gzip parquet file

---

.github/workflows/velox_be.yml
backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala

We had added a low memory CI job for TPC-DS q97 which was failing because at the time spilling support was not added for distinct aggregation. Enable it now to make sure the newly added spilling support could work.
Update: The job is still failing due to some other reasons although distinct spilling is functional. Adding a independent UT instead.

[VL] Activate CI test for distinct aggregation spill

---

cpp/velox/compute/WholeStageResultIterator.cc

The Velox TableWrite node generates the write file name based on the task ID name. However, in this case, Gluten passed the task ID name as `Gluten [Stage: 3 TID: 3]`, which contains a space in the file name. Spark cannot read files with spaces in their names. This pull request resolves the issue by removing the space in the task ID. And the taskid name will changed from `Gluten [Stage: 3 TID: 3]` to `Gluten_StageId_3_TaskId_3`.
no need

[GLUTEN-3547][VL] [Minor] Remove the space in taskid name

---

gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala
gluten-delta/src/test/scala/io/glutenproject/execution/VeloxDeltaSuite.scala

[GLUTEN-3801][VL] Fix isAdaptiveContext null value for ColumnarOverrideRules

---

.github/workflows/velox_be.yml
dev/vcpkg/init.sh
dev/vcpkg/vcpkg.json
ep/build-velox/src/get_velox.sh
tools/gluten-te/centos/dockerfile-buildenv

add GCS support on Centos7, also removed the unnecessary arrow components in static build job
pass GHA

[GLUTEN-3715][VL] followup to add CentOS7 support for GCS

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/IteratorApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/MetricsApi.scala
gluten-core/src/main/scala/io/glutenproject/utils/Iterators.scala

Spark measure pipeline time since the iterator was created, but Gluten measure it in each call.
```
/**
* Returns the elapsed time since this object is created. This object represents a pipeline so
* this is a measure of how long the pipeline has been running.
*/
public long durationMs() {
return (System.nanoTime() - startTimeNs) / (1000 * 1000);
}
```
Following patch will add another metric to reflect native task execution time.

[VL] Align whole stage pipeline metric with Spark

---

cpp/velox/compute/VeloxBackend.cc
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Set the default value of the glog severity level to 1. This will help to remove some redundant glog information.
```
I1123 15:37:56.429041 103986 Task.cpp:1714] Terminating task Gluten_Stage_32_TID_107 with state Finished after running for 438 ms.
I1123 15:37:56.449131 103990 Task.cpp:1030] All drivers (6) finished for task Gluten_Stage_32_TID_123 after running for 472 ms.
I1123 15:37:56.449167 103990 Task.cpp:1714] Terminating task Gluten_Stage_32_TID_123 with state Finished after running for 472 ms.
I1123 15:37:56.466111 103971 Task.cpp:1030] All drivers (6) finished for task Gluten_Stage_32_TID_120 after running for 468 ms.
I1123 15:37:56.466140 103971 Task.cpp:1714] Terminating task Gluten_Stage_32_TID_120 with state Finished after running for 468 ms.
I1123 15:37:56.471377 103999 …
```

[VL] Set the default value of the glog severity level to 1

---

cpp-ch/local-engine/Parser/TypeParser.h
cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.h
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.cpp
cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSourceStep.h
cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp

(Fixes: \#3704)
related prs: 
- https://github.com/ClickHouse/ClickHouse/pull/56117
- https://github.com/ClickHouse/ClickHouse/pull/56122

[GLUTEN-3704][CH]Enable orc/parquet subcolumn pruning

---

cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp/velox/substrait/SubstraitParser.cc
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

Remove the extra argument `toTypeNodes` from make_decimal function.

[CORE] Remove an extra argument of make_decimal function

---

cpp/velox/CMakeLists.txt
cpp/velox/compute/VeloxBackend.cc
cpp/velox/operators/functions/SparkTokenizer.cc
cpp/velox/operators/functions/SparkTokenizer.h
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc

To fix affected unit tests in https://github.com/oap-project/velox, register Spark tokenizer instead of changing Velox one.
Depends on: https://github.com/oap-project/velox/pull/444.
under test

[VL] Register Spark tokenizer

---

backends-clickhouse/pom.xml
backends-velox/pom.xml
gluten-celeborn/pom.xml
gluten-core/pom.xml
gluten-data/pom.xml
package/pom.xml
pom.xml
substrait/substrait-spark/pom.xml

Protobuf has a hard-code limit (100) for recursion depth and runtime exception can occur when exceeding the limit. This PR proposes a custom protobuf dependency which has a much larger limit (100, 000, see source [here](https://github.com/oap-project/protobuf/tree/v3.23.4-0)). Thanks to @weiting-chen, the dependency jar has been published in maven repo (see [link](https://repo1.maven.org/maven2/io/glutenproject/protobuf-java/3.23.4-0/)).
Fixes: #1727, #2414. 

[CORE] Introduce custom protobuf dependency with recursion limit enlarged

---

cpp/velox/compute/VeloxBackend.cc
cpp/velox/compute/VeloxBackend.h
cpp/velox/memory/VeloxMemoryManager.cc
cpp/velox/memory/VeloxMemoryManager.h
gluten-core/src/main/java/io/glutenproject/memory/memtarget/LoggingMemoryTarget.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/NoopMemoryTarget.java
gluten-core/src/main/java/io/glutenproject/memory/memtarget/ThrowOnOomMemoryTarget.java
gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
gluten-data/src/main/java/io/glutenproject/memory/nmm/ManagedReservationListener.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManager.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/NativeMemoryManagers.java
gluten-data/src/main/java/io/glutenproject/memory/nmm/ReservationListener.java

This fixes issue #3364.
~~After applying the patch, global memory pool will be used when IO threads > 0 for memory allocations in Hive connector. However side-effect that the allocations will be out-of-track by Spark memory manager will be brought.~~
Update: Switching to global memory pool doesn't help since the async executor holds task's memory pool anyway. Added a wait strategy (up to 1.5s) until async allocations are released. Some minor cleanups to connector initialization procedure.

[GLUTEN-3364][VL] SplitPreloadPerDriver (SplitPreloadPerDriver = true, IOThreads > 0) causes unexpected crashes

---

cpp/core/utils/qat/QatCodec.cc

Some of the inner structures of `qzSession_` are not released without calling `qzTeardownSession`.

[VL] Fix QAT codec not closed

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHSparkPlanExecApi.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala
gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala
gluten-core/src/main/scala/io/glutenproject/expression/UnaryExpressionTransformer.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDataFrameAggregateSuite.scala

This PR proposes the support for rand function, only considering the usage with no user-specified seed, i.e., `rand()`.
There will be a separate PR to support `rand(seed)`. It requires combing user-specified seed with partition index to serve as the final seed for random generator in native lib. Thus, we can achieve global cross-partitions random distribution. If only user-specified seed is used, same random sequence will be generated for each partition.
See [spark source code](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/randomExpressions.scala#L45).
Spark UTs.

[GLUTEN-2031][VL] Support rand function

---

cpp/velox/shuffle/VeloxShuffleWriter.cc
cpp/velox/shuffle/VeloxShuffleWriter.h
cpp/velox/tests/VeloxShuffleWriterTest.cc
cpp/velox/utils/tests/MemoryPoolUtils.cc
cpp/velox/utils/tests/MemoryPoolUtils.h
cpp/velox/utils/tests/VeloxShuffleWriterTestBase.h

If spill is triggered by resizing binary partition buffer, should avoid shrinking itself during reclaiming memory from shrinking partition buffers. Because shrinking the buffer can possibly invalid the original underlying `ptr`.

[VL] Avoid shrinking the binary buffer which triggers spill

---

backends-clickhouse/src/main/scala/io/glutenproject/execution/CHHashAggregateExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
backends-velox/src/test/scala/org/apache/spark/sql/execution/benchmark/StreamingAggregateBenchmark.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/java/io/glutenproject/substrait/rel/RelBuilder.java
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

If the child output ordering satisfies the grouping keys then the grouping keys are pregrouped, we can choose to use `StreamingAggregate`. Velox supports `StreamingAggregate` which requires the input is pregrouped, so `StreamingAggregate` could use less memory to do aggregate as it does not need to hold all groups in memory and it could avoid spill.
For example, the query can hit this optimization if the join is SMJ:
```
SELECT c1, count(*), sum(c2) FROM (
SELECT t1.c1, t2.c2 FROM t1 t1 JOIN t1 t2 ON t1.c1 = t2.c1
)
GROUP BY c1;
```
manually benchmark
```
OpenJDK 64-Bit Server VM 1.8.0_292-b10 on Linux 5.10.0-21-amd64
Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
streaming aggregate:                      Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative …
```

[VL] Support StreamingAggregate if child output ordering is satisfied

---

dev/package.sh

In some scenarios, we need to build our own thirdparty-lib jar on **Arm64** when `spark.gluten.loadLibFromJar=true`
Build package:
`./dev/package.sh`

[GLUTEN-3695][VL] Support building 3rd-party libs on Arm64

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala

Before:
> scan time total (min, med, max (stageId: taskId))
0 ms (0 ms, 0 ms, 0 ms (stage 8.0: task 74))
After:
> scan time total (min, med, max (stageId: taskId))
13.1 s (117 ms, 192 ms, 289 ms (stage 8.0: task 44))
Depends on: https://github.com/oap-project/velox/pull/443.
under test

[VL] Fix scan time metrics 

---

backends-velox/src/main/scala/io/glutenproject/execution/HashAggregateExecTransformer.scala
backends-velox/src/main/scala/io/glutenproject/utils/VeloxIntermediateData.scala

Same as https://github.com/oap-project/gluten/pull/3721
Exists CI.

[GLUTEN-3719][VL] Optimize agg func match in getAggRelWithRowConstruct

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

Fix ORC related failed UT, below two tests were not fixed - will fix them in following commits 
```
.exclude("SPARK-37965: Spark support read/write orc file with invalid char in field name")
.exclude("SPARK-38173: Quoted column cannot be recognized correctly when quotedRegexColumnNames is true")
```
pass GHA

[GLUTEN-3855][VL] Fix ORC related failed UT

---

docs/velox-backend-limitations.md
docs/velox-backend-support-progress.md

update velox limitation documents

[VL] Update velox-backend-limitations.md

---

gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/exchange/GlutenEnsureRequirementsSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/exchange/GlutenEnsureRequirementsSuite.scala

Enable spark 3,3 and 3.4 unit test
```
enableSuite[GlutenEnsureRequirementsSuite]
// FIXME: yan
.exclude("reorder should handle PartitioningCollection")
```

[GLUTEN-2169][VL] Enable GlutenEnsureRequirementsSuite in unit tests

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc
cpp/velox/substrait/SubstraitToVeloxPlan.h
gluten-core/src/main/scala/io/glutenproject/backendsapi/SparkPlanExecApi.scala

[VL] Support ignoreNulls for NthValue window function

---

cpp/CMake/BuildQATZstd.cmake
cpp/CMake/BuildQATzip.cmake
cpp/CMake/FindZstd.cmake
dev/vcpkg/vcpkg.json

For reference, the steps below show how to install Gluten with QAT on an Ubuntu 22.04 Docker image. I will put these commands into a Dockerfile later.
1. Install basic dependencies
`apt install zip tar wget curl git gcc g++ pkg-config autoconf automake libtool flex bison openjdk-8-jdk maven make autoconf-archive cmake vim sudo`
2. Install dependencies for QAT driver
`apt-get install -y zlib1g-dev libudev-dev yasm libboost-all-dev linux-headers-$(uname -r)`
3. Build QAT driver and setup `ICP_ROOT`
4. Add "qat" to vcpkg default-features
```
diff --git a/dev/vcpkg/vcpkg.json b/dev/vcpkg/vcpkg.json
index 91cb430f..13ba43c5 100644
--- a/dev/vcpkg/vcpkg.json
+++ b/dev/vcpkg/vcpkg.json
@@ -2,7 +2,7 @@
"$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json", …
```

[VL] Enable using static link for QAT

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh

Depends on https://github.com/oap-project/velox/pull/453

[VL] Fix assertion failures when mixing use of partial aggregation spilling and flushing 

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDataFrameRangeSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDataFrameRangeSuite.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDataFrameRangeSuite.scala

1. Match all test startWith `Cancelling stage in a query with Range`
2. As we mentioned, ban those flaky tests on VL, we should exclude those tests in `VeloxTestSettings`
Fixes: #3796
CI

[GLUTEN-3796][VL][FOLLOW_UP] Correct test name match and move black list to exclude in `VeloxTestSettings`

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlan.cc

To meet Velox's requirement, this PR proposes constructing unique & non-overlapping partition/sort keys for window operator.
Fix #3528.
Added test cases.

[GLUTEN-3528][VL] Construct unique & non-overlapping partition/sort keys for window operator

---

cpp/velox/substrait/SubstraitParser.cc
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxSQLQueryTestSettings.scala
gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala
gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenDateExpressionsSuite.scala

Change date_format function mapping.
A previous modified Spark UT covers it.

[VL] Map date_format to a Velox function name

---

backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala
backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHValidatorApi.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/TransformerApiImpl.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/ValidatorApiImpl.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/TransformerApi.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/ValidatorApi.scala
gluten-core/src/main/scala/io/glutenproject/execution/GenerateExecTransformer.scala
gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala

[CORE] Move validate methods from TransformerApi to ValidatorApi

---

.github/workflows/stale.yml

1. ~~Leave comments on issues as well as on PRs.~~ Disable auto-close on issues.
2. Note user to feel free to reopen.

[VL] Minor improvements for CI stale bot

---

dev/builddeps-veloxbe.sh
docs/get-started/GlutenUsage.md
docs/get-started/Velox.md
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh

This is to fix error "Failed to apply compilation fixes to Velox: ..." when running build scripts with `ENABLE_EP_CACHE=ON`.
Also, remove option SKIP_BUILD_EP since its functionality overlaps ENABLE_EP_CACHE. One can use `ENABLE_EP_CACHE=ON` to skip building external projects which were already built earlier.

[VL] Avoid reapplying code patches for external projects when ENABLE_EP_CACHE=ON

---

ep/build-velox/src/build_velox.sh

Prior to this fix, ENABLE_EP_CACHE=ON only uses the target commit hash as cache key, which means for example, when we change BUILD_TYPE from `Debug` to `Release`, the cached debug build is still used as cached build incorrectly.
This patch is a fix for the bug.

[VL] ENABLE_EP_CACHE=ON still uses cached Velox build although the build arguments were changed

---

.github/workflows/velox_be.yml
ep/build-velox/src/get_velox.sh
tools/gluten-te/centos/build.sh
tools/gluten-te/centos/centos-7-deps.sh
tools/gluten-te/centos/dockerfile-build
tools/gluten-te/ubuntu/dockerfile-build
tools/gluten-te/ubuntu/dockerfile-buildenv

this patch updates the docker build script for ubuntu/centos.
do not run setup scripts on centos 7 for static build, which is not necessary.
pass GHA

[VL][CI] update docker build script

---

backends-velox/src/test/scala/io/glutenproject/execution/VeloxTPCHSuite.scala

V1 should set spark.sql.sources.useV1SourceList="parquet"
V2 should set spark.sql.sources.useV1SourceList=""
Exists CI.

[VL] Fix VeloxTPCHV1BhjSuite and VeloxTPCHV2Suite useV1SourceList

---

gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala

This pr is followup fix of https://github.com/oap-project/gluten/pull/3854. We can not remove `ColumnarInputAdapter`, otherwise the UI graph would be broken.
before:
after:

[GLUTEN-3854][CORE][FOLLOWUP] Add ColumnarInputAdapter back to recover UI graph

---

backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/MetricsApiImpl.scala
gluten-data/src/main/scala/io/glutenproject/metrics/InputIteratorMetricsUpdater.scala

After this patch, we can check average row count of a vector.

[VL] Add output row metric for InputIteratorTransformer

---

cpp-ch/local-engine/Shuffle/ShuffleSplitter.cpp

(Fixes: \#3908)
d_10267_0 部分测试数据
使用该PR 优化前，打印shufflewrite 各阶段耗时：
```
xxx CHShuffleSplitterJniWrapper_top end, using time(ms): 702 , compute_pid_time: 673108959, write time: 598128235, spill time: 4335076848, compress_time: 2657002019, bytes_writen:209895520, bytes_spilled: 61
1560616, serialize_time: 4335074129, partition_len: 1000, split_time:7045147620
```
使用该PR 优化后，打印shuffle write 各阶段耗时
```
xxx CHShuffleSplitterJniWrapper_top end, using time(ms): 656 , compute_pid_time: 693334189, write time: 593510681, spill time: 4424348215, compress_time: 2726385185, bytes_writen:214243801, bytes_spilled: 62
4202520, serialize_time: 4424346782, partition_len: 1000, split_time:2549022952
```
可见split 耗时从 优化前的7s 降低到了2.55s左右，有2倍左右的减少
同时shuffle write …

[GLUTEN-3908][CH] Improve shuffle split for clickhouse backend by remove ColumnNullable's `memcmp` 

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseHiveTableSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/FunctionParser.h
cpp-ch/local-engine/tests/gtest_parquet_write.cpp
gluten-core/src/main/scala/io/glutenproject/expression/UDFMappings.scala
gluten-core/src/main/scala/org/apache/spark/sql/hive/HiveSimpleUDFTransformer.scala

[GLUTEN-3924][CORE] Match hive UDF name in case-insensitive mode during expression transformation

---

gluten-core/src/main/scala/io/glutenproject/execution/ScanTransformerFactory.scala

[GLUTEN-3958] Use getDeclaredConstructor().newInstance() in ScanTransformerFactory

---

tools/gluten-te/centos/dockerfile-build
tools/gluten-te/ubuntu/dockerfile-build

In case of debugging in the docker. libvelox.so will find symbol sources in `/opt/gluten/ep/build-velox/build/velox_ep` so we'd preserve the directory.

[VL] gluten-te: In dockerfiles, use symbolic link for /opt/velox

---

cpp/velox/compute/WholeStageResultIterator.cc
cpp/velox/memory/VeloxColumnarBatch.cc
cpp/velox/tests/VeloxColumnarBatchSerializerTest.cc
cpp/velox/utils/VeloxArrowUtils.cc
cpp/velox/utils/VeloxArrowUtils.h

**Rebase velox with following changes:**
commit 075cc92f8312184a96d870fe6ce7c5c23fab9246
Author: Jimmy Lu <jimmylu@meta.com>
Date:   Tue Dec 5 15:35:32 2023 -0800
Back out "Add support for decimals in approx_distinct aggregate function" (#7889)
Summary:
Pull Request resolved: https://github.com/facebookincubator/velox/pull/7889
Original commit changeset: 7b9cead380c5
Original Phabricator Diff: D51811791
Aggregate fuzzer is not able to resolve decimal types, back it out to unbreak the test
Reviewed By: mbasmanova
Differential Revision: D51863784
fbshipit-source-id: a822065d7c4b7cc7002bbb3dfb1bd121686da8f0
commit 8a9ae28e6633d74bacad207fc89ff9bb66885fd4
Author: yangchuan <yangchuan.zy@alibaba-inc.com>
Date:   Tue Dec 5 15:34:11 2023 -0800
Fix memory leak of HdfsBuilder (#7579)
Summary:
ASAN …

[VL]Daily Update Velox Version (20231206)

---

cpp-ch/local-engine/Shuffle/ShuffleSplitter.cpp

Reverts oap-project/gluten#3909 it is already included in https://github.com/Kyligence/ClickHouse/pull/472

Revert "[GLUTEN-3908][CH] Improve shuffle split for clickhouse backend by remove ColumnNullable's `memcmp` "

---

backends-velox/src/test/scala/io/glutenproject/execution/FallbackSuite.scala
gluten-core/src/main/scala/io/glutenproject/extension/ExpandFallbackPolicy.scala

Since we have removed AQE columnar shuffle read, so it's possible the gluten plan and query stage are not adjacent. This pr changes to collect leaves for gluten plan to make code robust.
add test

[CORE] Fix wrong fallback cost

---

gluten-core/src/main/scala/io/glutenproject/extension/StrategyOverrides.scala
gluten-core/src/main/scala/io/glutenproject/extension/columnar/TransformHintRule.scala

(Fixes: \#3979)
Origin unit test

[GLUTEN-3979][CORE] Use exists() instead of map().exists() to improve code readability

---

gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala
gluten-ut/spark34/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala

**[VL]Daily Update Velox Version (20231208) with following updates.**
```
b908e7794 Add curl.cmake dependency for cpr (#7853)
af0d9ae93 Improve scheduled fuzzer workflow (#7842)
ddc347188 Add OderBy output stage spill (#7759)
61ab60ddc Ensure we only use subgroups if they are matched in url_extract_* presto functions (#7866)
db64f6fa8 Fix fuzz different output types for generated expression sets in expression fuzzer (#7910)
8374e669b Updating submodules
730dd5343 Extract toAggregateInfo(AggregationNode) helper function (#7859)
13d54c49d Set task wait timeout to 5 mins by default and docs fixes (#7911)
debe03c17 Fix function signature of approx_distinct(DECIMAL(a_precision,a_scale)) (#7905)
00c742213 Put back "[velox][PR] Add support for decimals in approx_distinct aggregate function" …
```

[VL]Daily Update Velox Version (20231208)

---

.github/workflows/velox_be.yml
cpp/CMakeLists.txt
cpp/compile.sh
cpp/velox/CMakeLists.txt
cpp/velox/compute/VeloxBackend.cc
dev/builddeps-veloxbe.sh
dev/vcpkg/vcpkg.json
ep/build-velox/src/build_velox.sh
ep/build-velox/src/get_velox.sh
shims/common/src/main/scala/io/glutenproject/GlutenConfig.scala

Fixes: https://github.com/oap-project/gluten/issues/3580
test maunally end to end

[GLUTEN-3580][VL] support read data from abfs with account key

---

backends-clickhouse/src/main/delta-20/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/DeltaMergeTreeFileFormat.scala
backends-clickhouse/src/main/delta-22/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/DeltaMergeTreeFileFormat.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHSuite.scala
gluten-core/src/main/scala/io/glutenproject/execution/FileSourceScanExecTransformer.scala

The mergetree file format must show the message in the plan tree: `NativeFileScan mergetree xxxx`.
Close #3991.
(Fixes: #3991)

[GLUTEN-3991][CH] Fix the incorrect display name for the mergetree file format

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala
cpp-ch/local-engine/Parser/JoinRelParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp

[GLUTEN-3861][CH] Fix parse exception when join postJoinFilter contains singularOrList

---

backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseFileFormatSuite.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
backends-velox/src/main/scala/io/glutenproject/backendsapi/velox/VeloxBackend.scala
gluten-core/src/main/scala/io/glutenproject/backendsapi/BackendSettingsApi.scala
gluten-core/src/main/scala/io/glutenproject/utils/FallbackUtil.scala

[CH] enable replaceSortAggWithHashAgg

---

package/pom.xml
pom.xml

Shaded Guava in gluten-package
Fixs: #3983 
Local Package Test
```shell
mvn clean package -Pbackends-velox -Pspark-3.3 -Prss -DskipTests
```

[GLUTEN-3983][CORE] Shade Guava dependency

---

docs/developers/MicroBenchmarks.md
gluten-core/src/main/scala/io/glutenproject/execution/HashAggregateExecBaseTransformer.scala

Fix below error when try to dump the json plan:
```
132 W20231207 01:54:01.932435 4101830 VeloxRuntime.cc:46] Error converting Substrait plan to JSON: BinaryToJsonStream returned INTERNAL:Invalid type URL, type URLs must be of the form '/<typename>', got: type.googleapis.com/google.protobuf.StringValue
```

[VL] Fix aggregation dumpped as json string

---

cpp/velox/compute/WholeStageResultIterator.cc
ep/build-velox/src/get_velox.sh

Dependency https://github.com/zhztheplayer/velox/tree/wip-rebase-231212

[VL] Daily Update Velox Version (20231212)

---

backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala
cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
gluten-core/src/main/scala/io/glutenproject/expression/ConverterUtils.scala

Respect parsed attribute name from Spark, `sum(a)` is a valid attr name in Spark.
Remove column name validate logic safely since SparkTokenizer already added.
(Fixes: \#3962)
added UT.

[GLUTEN-3962][VL] Respect parsed attribute name and remove column name validate logic

---

cpp/CMake/BuildGTest.cmake
cpp/velox/benchmarks/CMakeLists.txt
cpp/velox/benchmarks/PlanValidatorUtil.cc
cpp/velox/jni/VeloxJniWrapper.cc
docs/developers/HowTo.md

Add plan_validation_util executable for debugging validate process in native side, and refine docs.

[VL] Add plan validation util for debugging validate process

---

backends-clickhouse/src/main/scala/org/apache/spark/shuffle/utils/RangePartitionerBoundsGenerator.scala
backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseDecimalSuite.scala
cpp-ch/local-engine/Common/CHUtil.cpp
cpp-ch/local-engine/Common/CHUtil.h
cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
cpp-ch/local-engine/Parser/SerializedPlanParser.h
cpp-ch/local-engine/Parser/TypeParser.cpp
cpp-ch/local-engine/Parser/scalar_function_parser/divide.cpp
cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
gluten-core/src/test/scala/io/glutenproject/execution/WholeStageTransformerSuite.scala
gluten-ut/spark33/src/test/scala/io/glutenproject/utils/clickhouse/ClickHouseTestSettings.scala

[GLUTEN-3676][CH] Enable TPCH Deicmal Test
