- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Payload.h
- cpp/velox/benchmarks/GenericBenchmark.cc
- cpp/velox/benchmarks/common/BenchmarkUtils.cc
- cpp/velox/shuffle/VeloxHashShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleReader.cc
- docs/developers/MicroBenchmarks.md
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
- Add `--run-shuffle-read` command line flag to add shuffle read process after write. Only takes effect when `--run-shuffle` is set.
- Add `--debug-mode` command line flag to enable debug mode (same as `spark.gluten.sql.debug`)
- Refined log printing. Fixed coredump when using `--help`.
> [VL] Add reader process to shuffle benchmark

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
- cpp/velox/jni/JniUdf.cc
- cpp/velox/udf/Udaf.h
- cpp/velox/udf/Udf.h
- cpp/velox/udf/UdfLoader.cc
- cpp/velox/udf/UdfLoader.h
- cpp/velox/udf/examples/MyUDF.cc
- docs/developers/VeloxUDF.md
1. set `allowTypeConversion=true` when creating the UDF function to inject possible `Cast` if the sql datatype doesn't match any of the registered ones.
2. Or set `spark.gluten.sql.columnar.backend.velox.udfAllowTypeConversion=true` and the implicit type conversion will take effect to all udf functions. 
UDF developers can decide whether to allow type conversion for a specific udf with the first approach, but need to modify/update existing udf libraries. The second approach doesn't modify existing UDF libraries, but user need to set this option for the application.
> [VL] Allow udf type conversion

- ep/build-velox/src/setup-centos7.sh
- ep/build-velox/src/setup-centos8.sh
The user may customize `VELOX_HOME`, or they may use the default directory `ep/build-velox/build/velox_ep`. However, in the current `setup-centos7.sh` and `setup-centos8.sh`, only the default `VELOX_HOME` path will be used.
In fact, before calling `setup-centos7.sh` or `setup-centos8.sh`, `builddeps-veloxbe.sh` has already changed the directory to `VELOX_HOME`, so we can directly use the `scripts` dir in the current path.
N/A
> [VL] Use the scripts dir in the current path as SCRIPTDIR

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
Fix exception when mapFromArrays accepts its first argument with type Array(Nullable(T))
(Fixes: \#6561)
related to ch pr:  https://github.com/ClickHouse/ClickHouse/pull/67103/files
> [GLUTEN-6561][CH] Fix exception when mapFromArrays accepts its first argument with type Array(Nullable(T))

- docs/get-started/Velox.md
> [VL] Doc: Update RSS docs

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- ep/build-velox/src/modify_velox.patch
See discussion: https://github.com/apache/incubator-gluten/issues/5253#issuecomment-2251845672
By default, simdjson lib enables UTF-8 validation to check input json string. However, Spark always disregards the UTF-8 encoding invalidity of input.
> [VL] Skip UTF-8 validation in JSON parsing

- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
fix memory config spill_mem_ratio always zero
unit tests
> [CH] Fix memory config spill_mem_ratio always zero

- dev/build_arrow.sh
- ep/build-velox/src/get_velox.sh
Gluten will install arrow libs with some patches applied and some different options used. A conflict version can be installed by Velox's setup-centos9.sh.
Local verification.
> [VL] Fix arrow lib conflict on centos-9

- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.h
During sort-based shuffle c2r conversion, 64M buffers are allocated to hold the row data. A new 64M buffer will be allocated when the rest space is not enough to hold one more row. However, when allocating a Velox buffer, the capacity can be 1.5x larger than the size, leading to huge memory waste.
```
W0806 09:47:47.876497 526671 VeloxSortShuffleWriter.cc:323] acquire new buffer. current capacity: 100663200, size: 67108864, pageCursor: 67108861, unused: 33554339
```
This PR eliminates the buffer size amplification when memory is sufficient (allocates exact 64M buffer), and sets the allocated buffer size to its capacity to minimize memory waste in other cases:
```
W0807 04:20:18.974953 604449 VeloxSortShuffleWriter.cc:319] Acquire new buffer. current capacity: 67108768, size: 67108768, …
```
> [VL] Reduce memory waste in sort based shuffle

- gluten-core/src/main/java/org/apache/gluten/substrait/rel/LocalFilesNode.java
The field names of baseSchema in the ReadRelNode and the field names of schema in the LocalFilesNode may mismatch, which we have met. The reason is that gluten converts the field names of the baseSchema in the ReadRelNode to lower case but does not convert the field names of the schema in the LocalFilesNode.
The bug will result the reader can't deserialize the column data correctly.
> [CORE] Fix schema mismatch between ReadRelNode and LocalFilesNode

- .github/workflows/velox_weekly.yml
- dev/package.sh
Address https://github.com/apache/incubator-gluten/pull/6569#issuecomment-2268061246
`Velox backend weekly job` GA
> [GLUTEN-6569][FOLLOWUP][VL] Delete unnecessary gcc9 enable of package script

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
> [GLUTEN-6681] [CH]fix array(decimal32) in CH columnar to row

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/package.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ColumnarRuleApplier.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/ConventionFunc.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
- shims/common/src/main/scala/org/apache/gluten/metrics/GlutenTimeMetric.scala
This PR avoids c2r and r2c transition by returning `Convention` which ouputs both `VanillaRow` and `BatchType` for `ColumnarWriteFilesExec`.
```scala
/**
* ColumnarWriteFilesExec neither output Row nor columnar data. We output both row and columnar to
* avoid c2r and r2c transitions. Please note, [[GlutenPlan]] already implement batchType()
*/
sealed trait ExecuteWriteCompatible extends KnownChildrenConventions with KnownRowType {
// ...
override def requiredChildrenConventions(): Seq[ConventionReq] = {
List(ConventionReq.backendBatch)
}
override def rowType(): RowType = {
RowType.VanillaRow
}
}
```
`ColumnarWriteFilesExec` neither outputs Columnar batch data nor `InternalRow`, and hence we can't add c2r or r2c on top of it, otherwise it would be am internal error.
1. In the normal code …
> [GLUTEN-6705] [CORE] [Part 1] Avoid adding c2r for ColumnarWriteFilesExec, since it neither output Columnar batch data nor InternalRow

- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/orc/OrcFileFormat.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/orc/OrcFileFormat.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
There is a if-branch for infer schema always unreachable before, we can remove it and just use vanilla spark's infer schema. 
See https://github.com/apache/incubator-gluten/issues/6649.
> [Minor] Clean up useless code in ParquetFileFormat/OrcFileFormat

- docs/get-started/Velox.md
- gluten-delta/pom.xml
- package/pom.xml
Currently, gluten supports packaging iceberg into a bundle jar, and it’s best for us to maintain consistent behavior on the delta side. This brings several benefits:
1. Consistent behavior avoids increasing the learning burden;
2. Simplifies deployment;
3. Aligns better with users' expectations for manually specified configurations.
(Fixes: \#6737)
manual tests
> [GLUTEN-6737]package delta into bundle jar when specify delta profile

- cpp/core/jni/JniWrapper.cc
- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/LocalPartitionWriter.h
- cpp/core/shuffle/Options.h
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Payload.h
- cpp/core/shuffle/ShuffleWriter.cc
- cpp/core/shuffle/ShuffleWriter.h
- cpp/core/shuffle/Spill.cc
- cpp/core/shuffle/Spill.h
- cpp/core/shuffle/rss/RssPartitionWriter.cc
- cpp/velox/shuffle/VeloxHashShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.h
- gluten-data/src/main/java/org/apache/gluten/vectorized/GlutenSplitResult.java
- gluten-data/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
Will have `Spill (Memory)` and `Spill (Disk)` shown on UI
> [VL] Fix shuffle spill not reported to spark metric

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/CommonSubexpressionEliminateRule.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/RewriteDateTimestampComparisonRule.scala
Make the package paths of `CommonSubexpressionEliminateRule` and `RewriteDateTimestampComparisonRule` consistent with the real paths.
> [MINOR][CH] Rename package of some extension rules

- dev/vcpkg/setup-build-depends.sh
When starting a brand new ubuntu 22.04 container and run `setup-build-depends.sh` directly, it can not locate packages to be installed because the repository is not updated.
Test in local.
> [MINOR] update repository first in setup-ubuntu envs

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
`RasOffload.validators` is now initialized only once in the same process when the first time it's accessed. This causes bug that RAS planner never respond to validation-related session configuration changes.
Issue is found in PR https://github.com/apache/incubator-gluten/pull/6756
> [VL] RAS: Renew validator instance for each rule applier call

- cpp-ch/local-engine/Parser/JoinRelParser.cpp
Fixes: #6768
The mixed join condition doesn't clear the unused input columns, this will cause uneccessary data copy during joining.
It's one of the issues which are noticed in #6768
unit tests
> [GLUTEN-6768][CH] Clear mixed join contition to avoid uneccessary data copy

- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/tests/MemoryManagerTest.cc
Phase 2 of the task fixing #6736 . The new code avoids the client side lock in `ListenableArbitrator` from being acquired when the arbitrator is calling / is called by the delegated listener. This together with https://github.com/apache/incubator-gluten/pull/6741 should fix #6736 .
> [GLUTEN-6736][VL] Phase 2: Minimize lock scope in ListenableArbitrator

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHMetricsApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/SortMergeJoinMetricsUpdater.scala
`CHMetricsApi#genSortMergeJoinTransformerMetrics` and `SortMergeJoinMetricsUpdater` do not support sort merge join metrics, which causes that `CHSortMergeJoinExecTransformer` misses the sort merge join metrics. Metrics of `CHSortMergeJoinExecTransformer` are introduced to provide sort merge join metrics.
(Fixes: \#6674)
CI.
> [GLUTEN-6674][CH] Support sort merge join metrics

- gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
The patch mainly moves the `KnownChildrenConventions` / `KnownRowType` up to `ColumnarWriteFilesExec` as its direct dependency to keep trait class `ExecuteWriteCompatible` minimal.
And some minors.
Link #6745
> [CORE] Following #6745, append some minor code cleanups

- package/pom.xml
- shims/spark32/src/main/java/org/apache/spark/memory/MemoryConsumer.java
- shims/spark32/src/main/java/org/apache/spark/memory/TaskMemoryManager.java
- shims/spark32/src/main/java/org/apache/spark/util/collection/unsafe/sort/UnsafeExternalSorter.java
In spark 3.2, parquet write invokes UnsafeSort, this exception occurs. HashAgg may also spill by gluten consumer and then OOM. We relax the constraint when the same task request spill.
For other thread request spill, we could not allow spill, it will cause insert and sort at the same time.
To fix this exception.
```
org.apache.gluten.memory.memtarget.ThrowOnOomMemoryTarget$OutOfMemoryException: Not enough spark off-heap execution memory. Acquired: 40.0 MiB, granted: 8.0 MiB. Try tweaking config option spark.memory.offHeap.size to get larger space to run this application. 
Current config settings: 
spark.gluten.memory.offHeap.size.in.bytes=50.0 GiB
spark.gluten.memory.task.offHeap.size.in.bytes=12.5 GiB
spark.gluten.memory.conservative.task.offHeap.size.in.bytes=6.3 GiB
Memory consumer …
```
> [VL] Fix parquet write sort spill OOM

- .github/workflows/velox_docker.yml
The disabled CI test case `TPC-DS SF30.0 Parquet local spark3.2 Q23A/Q23B low memory, memory isolation on` have already been passing for some time. Enable it to avoid regression.
> [VL] Enable an integration test case in CI OOM tests

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/ReorderJoinTablesRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseColumnarShuffleAQESuite.scala
Fixes: #6768
If the gap of two tables‘ sizes is too large, try to reorder the tables, make sure the smaller table is used to build the hash table.
With AQE, we could get the row number from `ShuffleQueryStageExec`
unit tests
> [GLUTEN-6768][CH] Try to reorder hash join tables based on AQE statistics

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
When running the following sql in yarn client mode, we got the following exception:
```
spark.sql("create temporary view d233 using parquet options ( path 'file:///home/jk/d233.parquet')")
spark.sql("select sum(impression_count_last7days ) from (     SELECT sum(impression_count) OVER (         PARTITION BY user_id,         surface         ORDER BY date RANGE BETWEEN 6 preceding AND CURRENT ROW       ) AS impression_count_last7days     from d233 )").show()
```
```
24/08/12 16:13:26 WARN TaskSetManager: Lost task 86.1 in stage 3.0 (TID 263) (sr246 executor 8): TaskKilled (Stage cancelled: Job aborted due to stage failure: Task 90 in stage 3.0 failed 4 times, most recent failure: Lost task 90.3 in stage 3.0 (TID 254) (sr246 executor 6): java.lang.NullPointerException
at …
```
> [GLUTEN-6600]Fix NPE issue when running window sql

- gluten-ut/common/pom.xml
We now use variable `java.version` to support multiple Java versions. No need to keep the fix version options.
This is a minor change.
> [CORE] Remove the fix 1.8 Java compiler version in module gluten-ut-common

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/gluten/expression/ExpressionTransformer.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxStringFunctionsSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
Regex delimiter, limit parameter and non-constant input have been supported in Velox Spark split function. This PR removes the fallback for cases that were not previously supported.
> [VL] Enable full functionality of split function

- cpp/velox/memory/VeloxMemoryManager.cc
`mm->arbitrator()->shrinkCapacity` should return the shrunken bytes
> [VL] No need to obtain old shrunken memory

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/compute/VeloxRuntime.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/jni/JniFileSystem.cc
- cpp/velox/operators/writer/VeloxParquetDatasourceABFS.h
- cpp/velox/operators/writer/VeloxParquetDatasourceHDFS.h
- cpp/velox/operators/writer/VeloxParquetDatasourceS3.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/utils/ConfigExtractor.cc
- cpp/velox/utils/ConfigExtractor.h
- cpp/velox/utils/HdfsUtils.cc
- cpp/velox/utils/HdfsUtils.h
- ep/build-velox/src/get_velox.sh
> [VL] Daily Update Velox Version(2024_08_15)

- cpp/velox/compute/WholeStageResultIterator.cc
Suspension is not needed during Velox updates. Remove it to minimize code.
> [VL] Remove suspend section when spilling Velox task

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- cpp/core/config/GlutenConfig.h
- cpp/core/jni/JniWrapper.cc
- gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarBatchSerializer.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
The warning is 
> 2024-08-15T08:25:09.6082390Z I20240815 08:25:09.607668 13612 JniWrapper.cc:544] Because the spark.gluten.sql.columnarToRowMemoryThreshold configuration item is invalid, the kColumnarToRowMemoryDefaultThreshold default value is used, which is 67108864 byte
It's because default value of spark.gluten.sql.columnarToRowMemoryThreshold is not correctly passing to native code (malformed). The patch fixes the issue by doing some minor refactors.
> [VL] Fix warning when spark.gluten.sql.columnarToRowMemoryThreshold is not set

- cpp-ch/local-engine/Parser/AggregateRelParser.cpp
Fixes: #6878
This should be an issue that is triggered when merging two-stage aggregation into one stage，like #4669, we cannot find a simple sql that could reproduce this issue.
manual tests
> [GLUTEN-6878][CH] Avoid name collisions in naming aggregate result

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseWholeStageTransformerSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseCountDistinctSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseNativeWriteTableSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseTableAfterRestart.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/ReCreateHiveSession.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/parquet/GlutenParquetFilterSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/test/AllDataTypesWithComplexType.scala
- gluten-celeborn/clickhouse/pom.xml
- gluten-core/src/test/scala/org/apache/gluten/test/FallbackUtil.scala
- gluten-ut/pom.xml
- gluten-ut/spark35/pom.xml
- gluten-ut/test/pom.xml
Before this PR,  we only run `GlutenClickHouseNativeWriteTableSuite`, `tpcds parquet` and  `tpch parquet`, after this PR, we can run full backends-clickhouse UTs
(Fixes: \#6067)
existed UT
> [GLUTEN-6067][CH][MINOR][UT] Followup 6623,  fix backends-clickhouse ut issse in CI

- backends-velox/src/test/scala/org/apache/gluten/execution/TestOperator.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenMathExpressionsSuite.scala
A new test case found in https://github.com/apache/incubator-gluten/issues/6827.
After fix, we can uncomment it.
> [GLUTEN-6827][VL] Add a new test case for Round's coverage

- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
For more consistent naming of the test classes.
> [GLUTEN-6889][VL] Rename test class `TestOperator` to `MiscOperatorSuite`

- .github/workflows/docker_image.yml
Github secrets are not passed to workflows that are triggered by a pull request from a fork. So change to use push event.
> [VL][CI] Change to use push event to trigger docker build workflow

- cpp/core/config/GlutenConfig.cc
- cpp/core/config/GlutenConfig.h
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
- Currently Spark supports `spark.redaction.regex` which allows redacting sensitive info like passwords, tokens etc.
- However gluten does not enforce this and logs in plaintext when debug mode is enabled.
- Added support to redact in printconfig which is being used in the codebase to log the config at various places.
- User can provide a regex which will be matched and a redacted string will be visitble.
Fixes: #6368
- Local Spark shell
Before:
After: (Additional regex was supplied to match `spark.gluten.ugi.tokens`)
> [GLUTEN-6368] Redact sensitive configs when calling `gluten::printConfig`

- backends-clickhouse/src/main/java/org/apache/gluten/execution/CHNativeCacheManager.java
- backends-clickhouse/src/main/java/org/apache/gluten/execution/CacheResult.java
- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala
- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenRpcMessages.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCHCacheDataCommand.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/ConcurrentMap.h
- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Storages/Cache/CacheManager.cpp
- cpp-ch/local-engine/Storages/Cache/CacheManager.h
- cpp-ch/local-engine/Storages/Cache/JobScheduler.cpp
- cpp-ch/local-engine/Storages/Cache/JobScheduler.h
- cpp-ch/local-engine/local_engine_jni.cpp
When the cache is loaded synchronously, the time consumed may be greater than the timeout of the spark rpc. A new asynchronous task mechanism is introduced to implement cache synchronous loading through polling, and a unified exception handling is added.
unit tests
> [CH] A simple job scheduler for merge tree cache sync load

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Join/BroadCastJoinBuilder.cpp
> [CH]duplicate column name case support in broadcast join #6926

- cpp/velox/compute/VeloxBackend.cc
Rely on Velox rebase https://github.com/apache/incubator-gluten/pull/6928.
Fixes https://github.com/apache/incubator-gluten/issues/6864.
> [GLUTEN-6864][VL] Set a Velox gflag to allow growing buffer created in another Velox task

- .github/workflows/dev_cron.yml
- .github/workflows/dev_cron/issues_link.js
- .github/workflows/dev_cron/title_check.js
Port PR #6911 #6919 to Branch-1.2
Fix in main
> [VL][1.2] Port 6911 6919 for github workflow resource not accessible issue fix

- gluten-data/src/main/scala/org/apache/gluten/runtime/Runtime.scala
As title. This could help on troubleshooting https://github.com/apache/incubator-gluten/issues/6930 which isn't trivial to repeat locally.
> [VL] Print memory statistics during task ending when leak is found

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- cpp-ch/local-engine/Shuffle/PartitionWriter.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
Fixes: #6923
AQE has dependency on shuffle written bytes to generate a proper plan. 
manual tests
> [GLUTEN-6923][CH] `total_bytes_written` is not updated in celeborn partition writers

- ep/build-velox/src/get_velox.sh
- package/pom.xml
- package/src/main/resources/META-INF/LICENSE
- package/src/main/resources/META-INF/NOTICE
Fix LICENSE and NOTICE issue in binary jar for Branch-1.2
* Update to copy new LICENSE, NOTICE into jar
* exclude more files
local
>  [VL][1.2]Port PR #6901 for license and notice issue in binary jar and upgrade OAP Velox version to gluten-1.2.1

- .github/workflows/velox_docker.yml
- dev/ci-velox-buildshared-centos-8.sh
1. Rename the UT job for consistency
2. ~~Fix `/__w/_temp/06ddeeec-4ccc-421b-91f8-8dad1d79e7b5.sh: line 1: mvn: command not found` in UT job when centos 8 cache is hit~~ (moving to [another thread](https://github.com/apache/incubator-gluten/issues/6957))
> [VL] Malformed CI job name

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseHDFSSuite.scala
Because the HDFS service of CI is not very stable, this UT has a small probability.
> [CH] Ignore cache file with hdfs suite

- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/utils/CHExecUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseStringFunctionsSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/parquet/GlutenParquetFilterSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/test/GlutenTPCHBase.scala
- cpp-ch/local-engine/Shuffle/SelectorBuilder.cpp
- cpp-ch/local-engine/Shuffle/SelectorBuilder.h
For Range Partition, we need build range bounds blocks,  the input blocks would be `ColumnConst` in the following sql:
```sql
select * from (
select 1 as x, r_name as y from region
union all
select 2 as x, n_name as y from nation
) order by y,x
```
When compare input blocks and range bounds blocks, without this pr, core dump occurs:
```
9. gluten_backend/src/Columns/IColumn.h:354: DB::IColumn::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const @ 0x000000000dc5d22a
10. gluten_backend/utils/extern-local-engine/Shuffle/SelectorBuilder.cpp:382: local_engine::RangeSelectorBuilder::compareRow(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, std::vector<unsigned long, std::allocator<unsigned long>> …
```
> [GLUTEN-6938][CH] Fix core dump when range partition include literal

- .github/workflows/util/install_spark_resources.sh
- .github/workflows/util/setup_helper.sh
- .github/workflows/velox_backend.yml
- .github/workflows/velox_backend_cache.yml
- dev/ci-velox-buildshared-centos-8.sh
* Fixed the missing mvn.
* Maven setup is assigned to newly created setup_helper.sh to reduce repeat code.
> [GLUTEN-6957][VL] Fix missing mvn when CI cache is hit

- .github/workflows/velox_backend_cache.yml
In GitHub Actions, when we set an environment variable using echo "VARNAME=value" >> $GITHUB_ENV, the variable is not immediately available in the current step. It will be available in subsequent steps.
> [GLUTEN-6957][VL] Fix mvn not found in cache job

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSuite.scala
In some cases, the child node of broadcast is TakeOrderedAndProjectExecTransformer, which is not supported by now.
Add TakeOrderedAndProjectExecTransformer node case support for broadcast . 
please refer to #6981 for more details
Fixes: \#6981
by UT
> [GLUTEN-6981][CH]Not supported operator TakeOrderedAndProjectExecTransformer for BroadcastRelation

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSortMergeJoinSuite.scala
https://github.com/apache/incubator-gluten/pull/6913 supports leftsemi/lestanti with inequal join condition, don't know why it cause CI pipeline unstable with merge join sutie q72.
Evidence:
1. https://opencicd.kyligence.com/job/gluten/job/gluten-ci/11744/
2. https://opencicd.kyligence.com/job/gluten/job/gluten-ci/11740/
Let's ignore first.
(Fixes: \#6877)
Existed UTs
> [GLUTEN-6877][CH][UT] HotFix: Exclude unstable merge join q72

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/VeloxBackend.cc
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/ThrowOnOomMemoryTarget.java
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkResourceUtil.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Limit Velox's global memory manager's usage to 0.75 * Spark overhead memory by default. The overhead memory is calculated by same manner with vanilla Spark.
Velox's global memory manager is used for some global allocations that don't belong to a specific query or task. These allocations are not tracked by Spark task memory manager.
After the patch, `spark.memory.offHeap.size` and `spark.executor.memoryOverhead` (with `spark.executor.memoryOverheadFactor` / `spark.executor.minMemoryOverhead` for higher version Spark, probably) will co-work for Velox backend's memory management.
1. `spark.memory.offHeap.size` limits major of the memory allocations happened during Velox query execution, e.g., hash tables, sort buffers, shuffle buffers, etc.
2. `spark.executor.memoryOverhead` limits the …
> [GLUTEN-6960][VL] Limit Velox untracked global memory manager's usage 

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
Follow-up of #6988
The warning message doesn't need to be shown in CH backend.
> [VL] Following #6988, move a warning from core to Velox backend

- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
There are 5 tests failed occasionally, all in GlutenInsertSuite.scala.
```
Gluten - do not remove non-v1writes sort and project *** FAILED ***
2024-08-21T09:05:09.0801992Z   org.apache.spark.SparkRuntimeException: [LOCATION_ALREADY_EXISTS] Cannot name the managed table as `spark_catalog`.`default`.`t`, as its associated location 'file:/__w/incubator-gluten/incubator-gluten/gluten-ut/spark35/target/scala-2.13/test-classes/unit-tests-working-home/spark-warehouse/t' already exists. Please pick a different table name, or remove the existing location first.
```
> [GLUTEN-6997][VL] Ignore a test: cleanup file if job failed

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/BatchScanMetricsUpdater.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/FileSourceScanMetricsUpdater.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/HiveTableScanMetricsUpdater.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- gluten-core/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/GlutenWholeStageColumnarRDD.scala
- gluten-core/src/main/scala/org/apache/gluten/metrics/MetricsUpdater.scala
- gluten-core/src/main/scala/org/apache/spark/sql/utils/SparkInputMetricsUtil.scala
- gluten-data/src/main/java/org/apache/gluten/vectorized/JniByteInputStreams.java
- gluten-data/src/main/scala/org/apache/gluten/metrics/BatchScanMetricsUpdater.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/FileSourceScanMetricsUpdater.scala
- gluten-data/src/main/scala/org/apache/gluten/metrics/HiveTableScanMetricsUpdater.scala
- gluten-data/src/main/scala/org/apache/spark/storage/SparkInputStreamUtil.scala
We used to name classes that are simply a bridge to Spark package-private APIs as `OASPackageBridge`. But we haven't strictly follow that criteria for naming. Now we just rename the classes and drop this rule.
> [CORE] Rename OASPackageBridges

- ep/build-velox/src/get_velox.sh
Get head for target_build_commit
Fixes: #7035
> [GLUTEN-7035][VL] Use first line of `ls-remote`'s output as build's target commit

- backends-clickhouse/src/test/scala/org/apache/gluten/affinity/CHUTAffinity.scala
- gluten-core/src/main/scala/org/apache/gluten/softaffinity/SoftAffinityManager.scala
- gluten-core/src/test/scala/org/apache/spark/softaffinity/SoftAffinityWithRDDInfoSuite.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
> [GLUTEN-6995][Core] Limit soft affinity duplicate reading detection max cache items

- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/utils/DecimalArithmeticUtil.scala
For SQL as follows:
```
select (col0 / (col1 + 0.00000001)) from table;
```
In this case, col0 and col1 are 0.
The result may be NULL. The reason is that the result of `Decimal(0.00000001).toString()` is "1E-8", which will make the new precision be 4.
Therefore, we use `toPlainString` here to prevent scientific notation.
> [CORE] Fix incorrect precision of decimal literal

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/test/java/org/apache/gluten/test/VeloxBackendTestBase.java
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkResourceUtil.scala
In vanilla Spark, the option `spark.executor.memoryOverhead` is by default calculated by `max(0.1 * on-heap size, 384m)`. The patch makes it `max(0.1 * off-heap size, 384m)` to gain better compatibility with Velox's memory management system.
If user does configure the memory overhead options, Velox backend will raise a warning when it's smaller than the recommended size during initialization.
> [VL] Set Spark memory overhead automatically according to off-heap size when it's not explicitly configured

- cpp/velox/CMakeLists.txt
As xsmid is installed in build_velox.sh, system include path has covered it.
> [VL] Remove including xsimd headers coming from velox build path 

- dev/vcpkg/ports/folly/vcpkg.json
fix issue : https://github.com/apache/incubator-gluten/issues/7037
Adding libdwarf dependency in folly vcpkg.json manifest to enable velox to get symbol from address when throw exception.
> [GLUTEN-7037][VL] Add dwarf dependency to folly when building with vcpkg

- dev/vcpkg/docker/Dockerfile
Improve vcpkg docker file:
+ remove unnecessary repo replacement
+ closes #7033 : add user/group for non-root
Manually build `gluten-vcpkg-builder` image
> [GLUTEN-7033][VL] Improve vcpkg docker file

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/package.scala
Fix ambiguous variable name
manual tests
> [CORE] Fix a variable name typo

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseStringFunctionsSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionTrim.cpp
> [GLUTEN-6989][CH] Support RTrim with const source column

- tools/gluten-it/package/pom.xml
The module name is auto-generated by my IDE and not needed to be in code base. Remove it.
> [VL] Gluten-it: Remove a IDE-generated maven module name

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxWindowExpressionSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
This PR aims to fix `number of sorting keys must be greater than zero`.
(Fixes: \#7090)
Add new unit tests
> [GLUTEN-7090][VL] fix: Number of sorting keys must be greater than zero

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CommonSubexpressionEliminateRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
(Fixes: \#https://github.com/apache/incubator-gluten/issues/7054)
> [GLUTEN-7054][CH] Fix cse alias issues

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/clickhouse.version
> [GLUTEN-7077][CH]`have_compressed` is lost in `HashJoin::reuseJoinedData`

- backends-velox/src/test/scala/org/apache/gluten/execution/FallbackSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/ExpandFallbackPolicy.scala
Currently, Gluten allows that BroadcastExchange is offloaded, but BHJ falls back. So we can remove the limit.
An added test.
> [VL] Remove a limit for BHJ in stage fallback policy

- dev/package-vcpkg.sh
- dev/vcpkg/Makefile
- dev/vcpkg/ports/duckdb/portfile.cmake
- dev/vcpkg/ports/duckdb/vcpkg.json
Fix #7118.
duckdb target is required when `build_tests=ON`.
We need to use `vcpkg_cmake_config_fixup` for duckdb to corrects issues like absolute paths and incorrectly placed binaries.
Local test with docker.
> [GLUTEN-7118][VL] Fix duckdb target issue when vcpkg is enabled

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/sources/GlutenInsertSuite.scala
As title
Fixes: #5880
added unit test and manual test:
```
create table wz_test_20240904 (a int) STORED AS PARQUET;
insert into wz_test_20240904 values (1);
```
before:
after this:
> [GLUTEN-5880][CORE] Ignore fallback for ColumnarWriteFilesExec children

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/util/AdaptiveContext.scala
It's not robust to locate trace element with given empirical index, then check class name. Just changed to use searching.
CI.
> [GLUTEN-6748][CORE] Search stack trace to infer adaptive execution context

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
Skip command execution when collect qe fallback summary
Fixes: #7130
> [GLUTEN-7130][CORE] Skip command execution when collect qe fallback summary

- .github/workflows/velox_backend.yml
Q97 OOM test in GHA CI failed since [this Velox rebase](https://github.com/apache/incubator-gluten/pull/7085).
Let's still run it in each PR but ignore that failure temporarily, to audit on possible impacts on this job by future daily Velox rebases.
> [VL] CI: Run Q97 oom test but ignore the failure

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
Add support of `array_insert` function for velox backend.
Velox side changes: https://github.com/facebookincubator/velox/pull/9851
New UT added.
> [GLUTEN-4039][VL] Support array insert function for spark 3.4+

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/MiscColumnarRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/PushDownInputFileExpression.scala
The Spark implementations of input_file_name/input_file_block_start/input_file_block_length uses a thread local to stash the file name and retrieve it from the function. If there is a transformer node between project input_file_function and scan, the result of input_file_name is an empty string. So we should push down input_file_function to transformer scan or add fallback project of input_file_function before fallback scan.
The processing logic is as follows:
1.Before offload, add new project before leaf node and push down input file expression to the new project
2.Normal offload project and scan
3.After offload, if scan be offloaded, push down input file expression into scan and remove project
UT
> [VL] Fix function `input_file_name()` outputs empty string in certain query plan patterns

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseMergeTreeCacheDataSSuite.scala
- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Storages/Cache/CacheManager.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeMeta.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.h
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20240906)

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffloadProject.scala
> [GLUTEN-7144][VL][RAS] Spark input file function support

- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/ShuffledHashJoinExecTransformer.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Parser/JoinRelParser.cpp
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-substrait/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-substrait/src/main/scala/org/apache/gluten/execution/SortMergeJoinExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/utils/SubstraitUtil.scala
Adds the join types currently defined in Substrait to the Gluten copy.  This is one of a vast set of changes aimed at reducing the differences from the official version in hope that one day there would be no differences.
> [GLUTEN-6834][CORE] feat: add other join types from the official Substrait

- gluten-data/src/main/scala/org/apache/gluten/runtime/Runtime.scala
This reverts https://github.com/apache/incubator-gluten/pull/6959 which could cause core dump when memory leak is found.
> Revert "[GLUTEN-6930][VL] Print memory statistics during task ending when leak is found"

- .github/workflows/velox_backend.yml
The job currently has potential to hang. Try setting a timeout on it so we can still run this job to observe on its output.
Closes https://github.com/apache/incubator-gluten/pull/7160
> [VL] CI: In GHA CI, set timeout for Q97 OOM job

- .github/workflows/velox_weekly.yml
- cpp/velox/tests/VeloxShuffleWriterTest.cc
- dev/package.sh
Fix the below error on ubuntu-20.04.
```
gluten::VeloxHashShuffleWriterMemoryTest_kStop_Test::TestBody()':
2024-09-09T04:14:59.2589597Z /__w/incubator-gluten/incubator-gluten/cpp/velox/tests/VeloxShuffleWriterTest.cc:610:5: error: 'ASSERT' was not declared in this scope; did you mean 'ASSERT_EQ'?
2024-09-09T04:14:59.2591325Z   610 |     ASSERT(reclaimed >= 2000);
2024-09-09T04:14:59.2591918Z       |     ^~~~~~
2024-09-09T04:14:59.2592344Z       |     ASSERT_EQ
2024-09-09T04:14:59.2594088Z /__w/incubator-gluten/incubator-gluten/cpp/velox/tests/VeloxShuffleWriterTest.cc:593:19: warning: unused variable 'partitioning' [-Wunused-variable]
2024-09-09T04:14:59.2596113Z   593 |   for (const auto partitioning : {Partitioning::kSingle, Partitioning::kRoundRobin}) {
2024-09-09T04:14:59.2597049Z …
```
> [VL] Fix weekly build job failure

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/PushdownAggregatePreProjectionAheadExpand.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
Fixes: #7112
The pre-prejction is added in `PullOutProjectHelper.scala`, we should not change this strategy. So adding a new rule to make this should be OK.
unit tests
> [GLUTEN-7112][CH] Pushdown aggregation's pre-projection ahead expand node

- .github/workflows/velox_backend.yml
Fix GHA action failure due to deprecated version v2 is used.
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
When using v4 on centos-7, the below error is reported. So the version is bumped to v3.
```
Run actions/upload-artifact@v4
/usr/bin/docker exec  90f457712a7cde646e9206b33ad2d053585766a30aee065ffef96e158fb7aa2f sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: …
```
> [VL][CI] Upgrade GHA upload/download artifacts

- dev/gluten-build-info.sh
Read the gcc version from generated `libgluten.so` file instead of use `gcc --version` directly.
We may compile cpp codes and scala codes in different bash, if multiple versions of GCC are installed on the system and the GCC version used by C++ is not correctly sourced during Scala code compilation, the generated GCC version by `gcc --version` may be inaccurate in `gluten-build-info.properties`.
Manually test on local by comparing the generated `gluten-build-info.properties` files.
> [MINOR][BUILD] Extract gcc version from libgluten.so

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/FallbackRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/OffloadSingleNode.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/rewrite/RewriteJoin.scala
Currently when `s.g.s.c.shuffledHashJoin.optimizeBuildSide==false` and `s.g.s.c.forceShuffledHashJoin=true`, SMJ will be converted to SHJ with a randomly chosen build side. This PR fixes the issue by choosing a smaller one in `RewriteJoin` rule.
> [VL] Make conf option `s.g.s.c.shuffledHashJoin.optimizeBuildSide` work correctly with option `s.g.s.c.forceShuffledHashJoin`

- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/joins/GlutenInnerJoinSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/joins/GlutenOuterJoinSuite.scala
Add `GlutenInnerJoinSuiteForceShjOff` and `GlutenOuterJoinSuiteForceShjOff` for testing Veox SMJ.
A couple of cases in `GlutenOuterJoinSuiteForceShjOff` cannot pass due to result mismatches. Added to exclusions.
The tests are added only in Spark 3.5 UTs for maintenance consideration.
> [VL] Add tests for Velox SMJ's coverage

- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.h
Optimize current deserialize data one by one to batch deserialization, the performance will improve more than 3 times.
Relevant Velox PR: https://github.com/facebookincubator/velox/pull/10797
> [GLUTEN-7205] [VL] Optimize row to column for scalar type

- cpp/core/CMakeLists.txt
> [GLUTEN-7208][VL]fix: loading libvelox.so failed when using static glog

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxRoughCostModelSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/cost/LegacyCostModel.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/cost/RoughCostModel.scala
It's observed Velox R2C becomes expensive when containing complex data types as input. Add a coster in rough cost model to address the issue.
To enable rough cost model:
```
spark.gluten.ras.enabled=true
spark.gluten.ras.costModel=rough
```
> [VL] RAS: Avoid adding R2C whose schema contains complex data types

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHGenerateExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHExpressionTransformer.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/GenerateExecTransformer.scala
- cpp-ch/local-engine/Parser/RelParsers/ProjectRelParser.cpp
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/GenerateRelNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/RelBuilder.java
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
Support lateral view outer explode
(Fixes: \#7116)
This patch was tested by unit tests
> [GLUTEN-7116] [CH] support outer explode

- backends-velox/src/main/scala/org/apache/gluten/expression/ExpressionTransformer.scala
Make fallback reason for GetStructField clearer
Fixes: #7276
Reproduced SQLs
```
create table test_20240919(a array<struct<b: string>>);
insert into test_20240919 values (array(named_struct('b', '1'), named_struct('b', '2')));
select a[1].b from test_20240919;
```
Fallback reason before this:
```
org.apache.gluten.substrait.expression.ScalarFunctionNode@9693f3e is not supported.
```
after this:
```
Unsupported child expression of GetStructField: a#13[1].b.
```
> [GLUTEN-7276][VL] Make fallback reason for GetStructField clearer

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
The default byte unit is MB for spark.executor.memoryOverhead, so can not set  value in byte without byte suffix
> [VL] Fix bug when setting Spark memory overhead automatically

- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/BatchIterator.java
- backends-velox/src/main/java/org/apache/gluten/metrics/IteratorMetricsJniWrapper.java
- backends-velox/src/main/java/org/apache/gluten/utils/VeloxBatchResizerJniWrapper.java
- backends-velox/src/main/java/org/apache/gluten/utils/VeloxBloomFilterJniWrapper.java
- backends-velox/src/main/scala/org/apache/gluten/execution/VeloxResizeBatchesExec.scala
- cpp/core/jni/JniCommon.cc
- gluten-arrow/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatchJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/datasource/DatasourceJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/runtime/RuntimeAware.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ColumnarBatchOutIterator.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ColumnarBatchSerializerJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/NativeColumnarToRowJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/NativeRowToColumnarJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/PlanEvaluatorJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ShuffleReaderJniWrapper.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ShuffleWriterJniWrapper.java
- gluten-core/src/main/java/org/apache/gluten/iterator/ClosableIterator.java
1. (core) Remove unused method `ClosableIterator#id()`
2. (velox) Rename method `RuntimeAware#handle()` to `RuntimeAware#rtHandle()` to avoid colliding with implementations' own `handle()` methods.
> [CORE][VL] Minor code cleanups

- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
> [VL] Fix columns added to `outNames` twice when building Substrait plan

- .github/workflows/velox_backend.yml
The case started to pass due to the merge of:
1. Fix https://github.com/apache/incubator-gluten/pull/7244
2. Rebase https://github.com/apache/incubator-gluten/pull/7259 (investigating)
The case used to fail by [error](https://github.com/apache/incubator-gluten/actions/runs/10861275683/job/30144831318):
```
org.apache.gluten.memory.memtarget.ThrowOnOomMemoryTarget$OutOfMemoryException: Not enough spark off-heap execution memory. Acquired: 8.0 MiB, granted: 5.8 MiB. Try tweaking config option spark.memory.offHeap.size to get larger space to run this application (if spark.gluten.memory.dynamic.offHeap.sizing.enabled is not enabled). 
Current config settings: 
spark.gluten.memory.offHeap.size.in.bytes=1024.0 MiB
spark.gluten.memory.task.offHeap.size.in.bytes=85.3 MiB …
```
> [VL] CI: Q97 OOM test passed, stop ignoring its return code in CI

- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Remove unused config VELOX_FORCE_COMPLEX_TYPE_SCAN_FALLBACK.
The last usage was removed at https://github.com/apache/incubator-gluten/commit/4533c725129c1c89096beadcdb540306a7c259a8
CI unit tests
> [VL] Remove unused config VELOX_FORCE_COMPLEX_TYPE_SCAN_FALLBACK

- .github/labeler.yml
This PR aims to label gluten-hudi as `DATA_LAKE`
> [INFRA] Label gluten-hudi as DATA_LAKE

- dev/vcpkg/env.sh
- dev/vcpkg/init.sh
- dev/vcpkg/toolchain.cmake
Some fixes following PR https://github.com/apache/incubator-gluten/pull/7052
1. Fix [bug](https://github.com/apache/incubator-gluten/pull/7052#issuecomment-2367282032) when `--enable_vcpkg=ON --build_arrow=ON`
2. Restore broken logic to use CMake bin installed by vcpkg
3. Fix check on `$GLUTEN_VCPKG_ENABLED` to skip vcpkg config (do we really need this?)
4. Remove meaningless `eval "$init_vcpkg_env"`
5. Fix malformed env `PKG_CONFIG_PATH`
> [VL] Minor follow-ups for #7052

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/columnarbatch/CHBatch.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/columnarbatch/VeloxBatch.scala
- backends-velox/src/test/java/org/apache/gluten/test/MockVeloxBackend.java
- backends-velox/src/test/java/org/apache/gluten/test/VeloxBackendTestBase.java
- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/transition/VeloxTransitionSuite.scala
- dev/vcpkg/toolchain.cmake
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuite.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuiteBase.scala
Part of https://github.com/apache/incubator-gluten/issues/7313.
1. Move packages for batch type objects
2. Add `VeloxTransitionSuite` to cover the procedure adding regular transitions in Gluten query planner, e.g., Velox / Arrow C2R / R2C, Velox-to-Arrow, Arrow-to-Velox, etc.
3. Refactor relevant test code
> [VL] Add VeloxTransitionSuite

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHAggUtil.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenSQLAggregateFunctionSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQueryCHSuite.scala
This pr fix two problems, one is that when group by has same names, the duplicated names will be remove by distinct in genHashAggregateExecTransformer, and cause Missmatch result columns size exception. The other is that when group by has same names but with different qualifier due to alias table name, the same names are passed to clickhouse, and cause Mismatch output schema exception.
The solution is that we distinct the groupings in Agg by ignoring qualifier, and insert a Project if has same names.
(Fixes: \#7096)
This patch was tested by unit tests.
> [GLUTEN-7096] [CH] fix exception when same names in group by

- .github/workflows/build_bundle_package.yml
- dev/vcpkg/README.md
- dev/vcpkg/docker/Dockerfile.gha
Since #7052, we need to enable all vcpkg features to generate binary cache in docker image, which can save CI build time.
Local test.
> [VL] Fix vcpkg binary caching in docker image

- .github/workflows/test_report.yml
- .github/workflows/velox_backend.yml
- pom.xml
This PR aims to use action-surefire-report to publish the test reports. With this feature, we can quickly see the failed tests and the information in the PR.
(Fixes: \#7327)
> [GLUTEN-7327][INFRA] Publish Velox Backend Test Result Report in Github Action

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- gluten-arrow/pom.xml
- gluten-arrow/src/main/scala/org/apache/spark/sql/utils/SparkArrowUtil.scala
Follow-ups for #7304
To keep the new module dependency graph defined in https://github.com/apache/incubator-gluten/issues/7264.
cc @zml1206 @PHILO-HE
> [VL] Follow-ups for #7304

- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2Base.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
Fix the error default database name and table name for the mergetree file format when using path based
Close #7344.
(Fixes: #7344)
> [GLUTEN-7344][CH] Fix the error default database name and table name for the mergetree file format when using path based

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenSessionExtensions.scala
This PR proposes to remove `SPARK_SESSION_EXTS_KEY` and `Objects.requireNonNull`.
This PR also update comments with more rigorous content.
> [GLUTEN-7351][CORE] Code cleanup for Gluten session extensions

- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
Override nodename for IcebergScanTransformer to distinguish the nodename of BatchScanExecTransformer
> [VL] Override nodename for IcebergScanTransformer

- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDynamicPartitionPruningSuite.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
Support DynamicPruningExpression conversion
Fixes: #7283
> [GLUTEN-7283][CORE] Support DynamicPruningExpression conversion

- cpp/velox/memory/VeloxMemoryManager.cc
- ep/build-velox/src/get_velox.sh
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
```
9e1280a72 Provide custom comparison functions in TimestampWithTimezone (#11025)
50784a5a5 Fix skip custom escape (#11091)
5a6a7443c Make concat function throw when there are less than 2 arguments (#11076)
451825e47 Support custom comparison in VectorHasher (#11051)
cb6c262a1 Change locaton of TableScan::getOutput() 'should exit' check. (#11085)
367faf8e7 Support custom comparison in RowContainer (#11024)
50ee5223b Support custom comparison in ContainerRowSerde (#11023)
78b6c77db Fix ParquetReader initialize schema failed for ARRAY/MAP colum (#10681)
0dd3a5db4 Fix fast_float installation problems (#11056)
a59538ca3 CMake: Make the env variable precedence by default in set_with_default (#11070)
d20ca4bd2 Fix the issue of inaccurate statistical data for …
```
> [GLUTEN-6887][VL] Daily Update Velox Version (2024_09_26) 

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriterFactory.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
After https://github.com/apache/incubator-gluten/pull/7265 and https://github.com/apache/incubator-gluten/pull/7279, we can make `GlutenConfig.GLUTEN_CONFIG_PREFIX` private to force use `GlutenConfig.prefixOf()`
In Clickhouse backend, please use `CHConf.prefixOf()`, `CHConf.runtimeConfig()` and `CHConf.runtimeSettings()`, I also remove `CHBackend.BACKEND_NAME` and use `Backend.get().name()` per #7265
(Fixes: \#7356)
Using existed UTs.
> [GLUTEN-7356][CORE] Make GlutenConfig.GLUTEN_CONFIG_PREFIX private

- dev/vcpkg/ports/krb5/portfile.cmake
Use new krb5 download url when enable vcpkg, because the web site of krb5 has moved to https://www.kerberos.org/
> [VL] Use new krb5 download url when enable vcpkg

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHInputPartitionsUtil.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/utils/MergeTreePartsPartitionsUtil.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetColumnarShuffleAQESuite.scala
Optimize the strategy of the partition split according to the files count
Close #7358.
(Fixes: #7358)
> [GLUTEN-7358][CH] Optimize the strategy of the partition split according to the files count

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/columnarbatch/CHBatch.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/main/scala/org/apache/spark/api/python/ColumnarArrowEvalPythonExec.scala
- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/transition/VeloxTransitionSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/backend/Backend.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/ConventionFunc.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/ConventionReq.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/FloydWarshallGraph.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transition.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/TransitionGraph.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/package.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkReflectionUtil.scala
- gluten-core/src/test/scala/org/apache/gluten/extension/columnar/transition/FloydWarshallGraphSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/GlutenPlan.scala
- gluten-substrait/src/main/scala/org/apache/gluten/utils/PlanUtil.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
Employs [new algorithm](https://en.wikipedia.org/wiki/Floyd%E2%80%93Warshall_algorithm) to look for suitable transition between two adjacent plan nodes.
This could:
1. Create transitions that are non-trivial to define due to large number of hops or complicated code module hierarchy. E.g., `RowToVeloxColumn -> VeloxToArrowNative -> ArrowNativeToArrowJava` (R2C2C2C)
2. Improve performance finding transitions.
3. Minimize transition definition code.
> [GLUTEN-7313][VL] Explicit Arrow transitions, part 2: new algorithm to find optimal transition

- backends-clickhouse/src/main/scala/org/apache/gluten/columnarbatch/CHBatch.scala
- backends-velox/src/main/scala/org/apache/gluten/columnarbatch/VeloxBatch.scala
- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/transition/VeloxTransitionSuite.scala
- gluten-arrow/src/main/java/org/apache/gluten/columnarbatch/ArrowBatches.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transition.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuite.scala
1. Remove unnecessary transition definitions since the algorithm introduced in https://github.com/apache/incubator-gluten/pull/7372 can find long transition paths.
2. Remove class `TransitionDef` to simplify code.
> [GLUTEN-7313][VL] Explicit Arrow transitions, part 3: code cleanups

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/ClickhouseSnapshot.scala
Add some config parameters to constrol the cache size for the mergetree parts：
- spark.gluten.sql.columnar.backend.ch.deltascan.cache.size
- spark.gluten.sql.columnar.backend.ch.addfiles.to.mtps.cache.size
- spark.gluten.sql.columnar.backend.ch.table.path.to.mtps.cache.size
Close #7385.
(Fixes: #7385)
> [GLUTEN-7385][CH] Add some config parameters to constrol the cache size for the mergetree parts

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenSessionExtensions.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/GlutenInjector.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/RuleInjector.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/SparkInjector.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/RuleApi.scala
This PR proposes to simplify the `RuleInjector`.
The change increases the readability. There are two change.
1. Avoid copy code from `SparkSessionExtensions` and simplify the `SparkInjector`.  The related `RuleApi` also updated. In fact, we can remove the `SparkInjector`, but I suspect it already became the public API.
2. Simplify the `GlutenInjector`.
> [GLUTEN-7364][CORE] Simplify the RuleInjector

- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/TreeMemoryTargets.java
Currently recursive invocation of spillTree calls ` spillTree(TreeMemoryTarget node, final long bytes)`, which always process `SPILL` phase.
> [VL] pass phase in recusive invocation of spillTree

- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/DeltaMergeTreeFileFormat.scala
- backends-clickhouse/src/main/delta-23/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
- backends-clickhouse/src/main/delta-23/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/DeltaMergeTreeFileFormat.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/DeltaLog.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/execution/datasources/v2/clickhouse/source/DeltaMergeTreeFileFormat.scala
- backends-clickhouse/src/main/java/org/apache/spark/sql/execution/datasources/clickhouse/ExtensionTableBuilder.java
- backends-clickhouse/src/main/java/org/apache/spark/sql/execution/datasources/clickhouse/ExtensionTableNode.java
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/ClickhouseSnapshot.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/catalog/ClickHouseTableV2Base.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCHCacheDataCommand.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/clickhouse/ClickhouseMetaSerializer.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/clickhouse/utils/MergeTreeDeltaUtil.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/clickhouse/utils/MergeTreePartsPartitionsUtil.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/mergetree/DeltaMetaReader.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/mergetree/StorageMeta.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/mergetree/TableProperties.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHFormatWriterInjects.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/CHMergeTreeWriterInjects.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v1/clickhouse/MergeTreeOutputWriter.scala
- backends-clickhouse/src/main/spark32/org/apache/gluten/backendsapi/clickhouse/CHExtendRule.scala
- backends-clickhouse/src/main/spark33/org/apache/gluten/backendsapi/clickhouse/CHExtendRule.scala
- backends-clickhouse/src/main/spark35/org/apache/gluten/backendsapi/clickhouse/CHExtendRule.scala
- backends-clickhouse/src/main/spark35/org/apache/spark/sql/catalyst/AddStorageInfo.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickhouseMergetreeSoftAffinitySuite.scala
`DeltaMergeTreeFileFormat` has lots of members which could be placed into metadata's configration. This PR move most of configurations into metadat‘s configuration except `sanpshotid`.
We now create `ReadRel.ExtensionTable` by `DeltaMergeTreeFileFormat`,  see `prepareWrite()`,
```scala
@transient val deltaMetaReader = DeltaMetaReader(metadata)
val database = deltaMetaReader.storageDB
val tableName = deltaMetaReader.storageTable
val deltaPath = deltaMetaReader.storagePath
val extensionTableBC = sparkSession.sparkContext.broadcast(
ClickhouseMetaSerializer
.forWrite(deltaMetaReader, metadata.schema)
.toByteArray)
```
(Fixes: \#7028)
Existed UTs
> [GLUTEN-7028][CH][Part-4] Refactor `DeltaMergeTreeFileFormat` to read table configuration from deltalog's metadata

- gluten-core/src/main/scala/org/apache/gluten/GlutenBuildInfo.scala
- gluten-ui/src/main/scala/org/apache/spark/sql/execution/ui/GlutenSQLAppStatusListener.scala
Fixes import and renamed SQLExecutionEnd to proper name. Also refactors Gluten Build Info to remove warnings.
CI
> [CORE] Minor: Fix warnings and rename event handler better

- .asf.yaml
As title. This is to loose our branch protection restrictions.
Here is the discussion: https://github.com/apache/incubator-gluten/discussions/7431, please kindly reply to that thread if having any thoughts. Thanks!
@apache/gluten-committers
> [CORE] Infra: Do not dismiss stale reviews

- .asf.yaml
As title. forward GitHub discussions to commits@gluten.apache.org
> [CORE] Infra: Forward GitHub discussions to Apache mailing list

- ep/build-velox/src/setup-centos8.sh
https://github.com/facebookincubator/velox/pull/10920 modified the `wget_and_untar` to download the source code to the `deps-download` directory by default, and introduced a new method `cmake_install_dir` to adapt this modification. `setup-centos8.sh` will source the `scripts/setup-helper-functions.sh` in `VELOX_HOME`, so we need to adapt this modification. 
Test offline.
> [VL] Adapt setup-centos8.sh to latest velox helper functions

- dev/info.sh
This script is used by issue reporter to present environment info.
Just some minor fix here: use Gluten version instead of velox version; remove conda info as conda is not supported by Gluten. 
N/A.
> Minor fix for info.sh

- .github/workflows/velox_weekly.yml
- cpp/velox/memory/VeloxMemoryManager.cc
- ep/build-velox/src/get_velox.sh
We need this fix to fit upstream change: https://github.com/facebookincubator/velox/pull/10920.
Also fix one compile failure by using uniform initialization to avoid most vexing parsing.
Weekly GHA job.
> [VL] Fix dependencies setup

- cpp/core/memory/MemoryAllocator.cc
We should update AllocationListener usage after successfully releasing memory to avoid exceeding the usage limit.
code refactor
> [CORE] Update AllocationListener usage after successfully releasing memory

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
[SPARK-48610](https://issues.apache.org/jira/browse/SPARK-48610) removes `QueryPlan.OP_ID_TAG` which is used by `GlutenExplainUtils` (introduced in #2247), the PR prepares shim code for the change.
As prerequisite of https://github.com/apache/incubator-gluten/pull/7138.
> [VL] Prepare shim API for breaking change in SPARK-48610

- .github/workflows/docker/Dockerfile.gha
- .github/workflows/docker_image.yml
In current GHA workflow, we are using one centos-8 docker image coming from Velox community. That image is no longer updated since centos-8 support is deprecated by the community.
The new docker image will be auto periodically updated with a few dependencies including arrow libs pre-installed. With this one used, the workflow will be accelerated (will create a separate pr to use it).
N/A
> [GLUTEN-7480][VL] Build centos-8 docker image for GHA workflow

- .github/workflows/test_report.yml
This PR aims to set `allow_forks` as true in `Report test results` workflow.
(Fixes: \#7489)
> [GLUTEN-7489][INFRA] fix: allow to fetch artifacts from workflow `Velox backend Github Runner` in upstream repo

- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/WholeStageResultIterator.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
[Velox#10966](https://github.com/facebookincubator/velox/pull/10966) introduced simple date time formatter that aligns with Spark legacy date parsing/formatting behavior. This PR enables Velox simple date time formatter if `spark.sql.legacy.timeParserPolicy` is set to `LEGACY`.
Relates Velox issue: [#10354](https://github.com/facebookincubator/velox/issues/10354)
Integration tests with Spark
> [VL] Enable Spark legacy date formatter if spark.sql.legacy.timeParserPolicy is set to 'LEGACY'

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- cpp/core/compute/Runtime.cc
- cpp/core/compute/Runtime.h
- cpp/core/jni/JniWrapper.cc
- cpp/velox/benchmarks/GenericBenchmark.cc
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/compute/VeloxRuntime.h
- cpp/velox/tests/RuntimeTest.cc
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/NativePlanEvaluator.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/PlanEvaluatorJniWrapper.java
As a follow-up of https://github.com/apache/incubator-gluten/pull/7244 cause https://github.com/apache/incubator-gluten/issues/7243 was not completely fixed.
The patch is to create different root Velox memory pools for different Velox tasks by assigning isolated Velox runtimes to the tasks.
Hang stack:
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f044de29e3e in folly::detail::(anonymous namespace)::nativeFutexWaitImpl (waitMask=4294967295, absSteadyTime=0x0, absSystemTime=0x0, expected=4294967293, addr=0x7f05d4d037f8)
at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex.cpp:126
#2  folly::detail::futexWaitImpl (futex=futex@entry=0x7f05d4d037f8, expected=expected@entry=4294967293, …
```
> [GLUTEN-7243][VL] Fix hanging by cross-task spilling

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionMapToString.cpp
- cpp-ch/local-engine/Functions/SparkFunctionMapToString.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
For `cast(map("a", 1, "b", 2) as string)`, gluten ouputs `{"a":1,"b":2}` while spark outputs `{a -> 1, b -> 2}`.
(Fixes: \#7389)
This patch was tested by unit tests.
> [GLUTEN-7389] [CH] fix cast map to string diff with spark

- .github/workflows/velox_backend.yml
- cpp/velox/compute/WholeStageResultIterator.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
It's observed in CI `Q67/Q95 OOM` test that large global spill pool usage is causing overhead memory OOM. The PR tries to tweak on default config option of Velox spill run size to fix the issue.
The OOM message was like:
```
"allocateNonContiguous failed with 2 pages from Memory Pool[__sys_spilling__ LEAF root[__sys_root__] parent[__sys_root__] MALLOC no-usage-track thread-safe]<unlimited max capacity unlimited capacity used 0B available 0B reservation [used 0B, reserved 0B, min 0B] counters [allocs 149202, frees 121609, reserves 0, releases 0, collisions 0])> Exceeded memory allocator limit when allocating 2 new pages, the memory allocator capacity is 1.35GB"
```
> [VL] Lower default spill run size to reduce overhead memory usage

- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/MergeTwoPhasesHashBaseAggregate.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/HashAggregateMetricsUpdater.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickhouseCountDistinctSuite.scala
- cpp-ch/clickhouse.version
- cpp-ch/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.h
- cpp-ch/local-engine/Common/DebugUtils.cpp
- cpp-ch/local-engine/Common/DebugUtils.h
- cpp-ch/local-engine/Operator/GraceAggregatingStep.cpp
- cpp-ch/local-engine/Operator/GraceAggregatingStep.h
- cpp-ch/local-engine/Operator/GraceAggregatingTransform.cpp
- cpp-ch/local-engine/Operator/GraceAggregatingTransform.h
- cpp-ch/local-engine/Parser/AdvancedParametersParseUtil.cpp
- cpp-ch/local-engine/Parser/AdvancedParametersParseUtil.h
- cpp-ch/local-engine/Parser/RelParsers/AggregateRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/AggregateRelParser.h
- cpp-ch/local-engine/Parser/RelParsers/RelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/RelParser.h
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
Fixes: #7311 
For aggregations involve `distinct`, use grace aggregate algorithm in partial aggregating stages, instead of streaming aggregating algorithm.
Following changes are made
1. introduce `GraceAggregatingStep`. It bases on codes of `GraceMergingAggregatedStep`, and supports to generate intermediate result.
2. Make `Aggregator` to support multiple aggregate phases, change is in https://github.com/Kyligence/ClickHouse/pull/504
3. Override `AggregateFunctionPartialMerge::getBaseAggregateFunctionWithSameStateRepresentation`, resolve the failure of checking columns structure equality in aggregate phase `INTERMEDIATE_TO_INTERMEDIATE`
4. Keep `requiredChildDistributionExpressions` in `MergeTwoPhasesHashBaseAggregate` that we can determine …
> [GLUTEN-7311][CH] Support grace aggregate algorithm in partial aggregating stages

- cpp/velox/utils/ConfigExtractor.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
We must directly set the gcs credential path in the config.
Add GCS configs to the backend config if present.
Fixes: #7420
Tested locally.
> [GLUTEN-7420][VL] Fix GCS configuration

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Rewriter/ExpressionRewriter.h
Fixes: #7550
The query plan is updated to
```
Expression (Rename Output)
Header: s#0 Nullable(String)
#18 Nullable(UInt8)
Positions:
Expression (Project)
Header: s Nullable(String)
in(sparkTupleElement(scalar_function { function_reference: 1000000 output_type { struct { types { string { nullability: NULLABILITY_NULLABLE } } names: "$.a" } } arguments { value { selection { direct_reference { struct_field { } } } } } arguments { value { literal { string: "$.a" } } } },$.a_7),__set_8) Nullable(UInt8)
Positions:
SubstraitFileSourceStep (read local files)
Header: s Nullable(String)
```
unit tests
(If this patch involves UI changes, please attach a …
> [GLUTEN-7550][CH] Rewrite `get_json_object` in `singular_or_list`

- tools/gluten-te/centos/centos-7-deps.sh
When extra FS options are turned on like `--enable_s3=ON --enable_gcs=ON --enable_hdfs=ON --enable_abfs=ON` then build will fail by an automake version error. The patch fixes the issue.
> [GLUTEN-7535][VL] CentOS 7 containerized build: Fix for automake version error

- .github/workflows/velox_backend.yml
- .github/workflows/velox_backend_cache.yml
We are [migrating to shared ccache](https://github.com/apache/incubator-gluten/pull/7546) in GHA CI, so ideally we can remove the legacy way that caches the C++ binaries. Since the part of legacy code is not trivial to maintain.
> [GLUTEN-7499][VL] CI: Remove GHA binary cache

- backends-velox/src/main/scala/org/apache/gluten/extension/CollectRewriteRule.scala
This PR proposes to improve `CollectRewriteRule` for Velox. These optimal points show below.
1. Short circuiting of `CollectRewriteRule` in advance.
2. Use tree traversal with pruning instead of full traversal.
3. Remove ensureNonNull since `CollectSet` override the `defaultResult`.
4. Unify the replacement for `CollectSet` and `CollectList`.
5. Use more meaningful variable names. e.g. `coalesce`.
6. Use correct variable names. e.g. `aggExpr`.
7. Other simplifications.
> [GLUTEN-7450][VL] Improve CollectRewriteRule for Velox

- backends-velox/src/main/scala/org/apache/gluten/expression/aggregate/VeloxCollect.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/CollectRewriteRule.scala
Following https://github.com/apache/incubator-gluten/pull/7451
Since https://github.com/facebookincubator/velox/pull/10737 was merged to Velox, the previous code for aligning Velox's `collect_set` with vanilla Spark's semantic in query planner is not needed now. Removing them.
> [VL] Remove unnecessary vanilla Spark compatibility code for VeloxCollectSet function

- .github/workflows/velox_backend_cache.yml
- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarPartialProjectExec.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/VeloxColumnarToRowExec.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/EmptySchemaWorkaround.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- cpp/velox/compute/VeloxRuntime.h
- gluten-arrow/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatches.java
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenColumnarRule.scala
Part of #7600 
Add a unit test to guard against the removal of special handling code in query planner for empty schema batches. E.g., `EmptySchemaWorkaround` and `OffloadHashAggregate`.
Also with some code cleanups against some other unrelated PRs recently merged to main.
> [GLUTEN-7600][VL] Prepare test case for the removal of workaround code for empty schema batches

- gluten-core/src/main/java/org/apache/gluten/softaffinity/SoftAffinityManager.scala
- gluten-core/src/main/java/org/apache/spark/softaffinity/SoftAffinity.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/ColumnarRuleApplier.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/GlutenPlan.scala
Spark provides the ability to modify configuration items during runtime. This is very useful for interactive queries around SparkSession or Spark Connect sessions. For example, users want observe the perf with enabled the `spark.sql.optimizer.dynamicPartitionPruning.enabled` or not.
Gluten configuration dependencies the Spark configuration. e.g. SQLConf but declared many constants for configuration items. This lead to the interactive queries can't change the config value during runtime.
This PR proposes to fix the bug that Gluten cannot change configuration during runtime.
> [GLUTEN-7609][CORE] Fix the bug that Gluten cannot change logging level

- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenColumnarRule.scala
This PR proposes to make code cleanup for `GlutenColumnarRule`.
> [GLUTEN-7581][CORE] Code cleanup for GlutenColumnarRule

- .github/workflows/util/install_spark_resources.sh
- .github/workflows/velox_backend.yml
- pom.xml
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/SparkShimProvider.scala
- tools/gluten-it/pom.xml
Summary:
1. bump spark version to 3.5.3
2. disable hudi tests in GHA, https://github.com/apache/incubator-gluten/issues/7571
3. bump delta version to 3.2.1
Fixes: #7336
> [GLUTEN-7336][CORE] Bump Spark version to v3.5.3

- dev/builddeps-veloxbe.sh
`VELOX_HOME` should be passed as a parameter to the `build_velox.sh` script in builddeps-veloxbe.sh.
N/A
> [VL] Fix missing VELOX_HOME in builddeps-veloxbe.sh

- .github/workflows/build_bundle_package.yml
- .github/workflows/velox_weekly.yml
- dev/build_helper_functions.sh
- dev/ci-velox-buildshared-centos-8.sh
- dev/ci-velox-buildstatic-centos-7.sh
- dev/docker/Dockerfile.centos7-static-build
- dev/docker/Dockerfile.centos8-dynamic-build
- dev/docker/entrypoint.sh
- dev/package-vcpkg.sh
- dev/vcpkg/README.md
- dev/vcpkg/setup-build-depends.sh
- ep/build-velox/src/get_velox.sh
- ep/build-velox/src/setup-centos7.sh
- ep/build-velox/src/setup-centos8.sh
- tools/gluten-te/centos/centos-7-deps.sh
- tools/gluten-te/centos/centos-8-deps.sh
- tools/gluten-te/centos/examples/buildhere-veloxbe-portable-libs/scripts/all.sh
Since the recently upgraded folly in Velox requires GCC >=10, we need to upgrade it for OSes whose default gcc package doesn't meet this requirement, such as centos-7/8 and ubuntu-20.04.
Also remove build tool setup for ubuntu-18.04 from `setup-build-depends.sh`, as it is not officially supported now.
CI.
> [GLUTEN-7458][VL] Upgrade to GCC-11 for centos-7/8 and ubuntu-20.04

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHValidatorApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxValidatorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/ValidatorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/utils/QueryPlanSelector.scala
As Velox backend is not relying on this global interceptor, move the related logics to CH backend code.
> [CORE][CH] Remove ValidatorApi.doSparkPlanValidate

- dev/docker/Dockerfile.centos8-dynamic-build
Follow-up fix for https://github.com/apache/incubator-gluten/pull/7578.
ccache is available to install after epel-release is installed.
Local test.
> [VL] Follow-up fix for gcc upgrade PR

- dev/vcpkg/ports/folly/portfile.cmake
- dev/vcpkg/ports/folly/vcpkg.json
- ep/build-velox/src/setup-centos7.sh
- ep/build-velox/src/setup-centos8.sh
This is for aligning with upstream velox, despite no build error is found because the upgrading doesn't change any API used by Velox.
CI.
> [VL] Upgrade FB_OS_VERSION to v2024.07.01.00

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHValidatorApi.scala
- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Common/GlutenConfig.cpp
- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Functions/SparkFunctionDecimalBinaryArithmetic.cpp
- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.cpp
- cpp-ch/local-engine/IO/SplittableBzip2ReadBuffer.h
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.h
- cpp-ch/local-engine/Storages/SubstraitSource/ExcelTextFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/JSONFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
- cpp-ch/local-engine/Storages/SubstraitSource/TextFormatFile.cpp
(Fixes: \#7659)
Manual test
``` sql 
CREATE TABLE json_table (
cc STRING,
ip_cc STRING,
rtime BIGINT,
data STRING,
ip STRING,
anti_udid STRING,
anti_sdk_id STRING,
_region STRING,
ssid STRING,
full_user_agent STRING,
uid STRING,
hour INT,
phone STRING,
action STRING,
shard BIGINT,
udid STRING,
iat STRING,
day DATE,
user_agent STRING,
timestamp BIGINT
)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
STORED AS TEXTFILE
LOCATION  '/data1/liyang/cppproject/spark/spark-3.3.2-bin-hadoop3/large_bzip2'
TBLPROPERTIES ('compression'='bzip2');
select count(1) from json_table; 
+-----------+
| count(1)  |
+-----------+
| 13273717  |
+-----------+
```
``` bash
$ wc -l large.json 
13273717 large.json 
```
> [GLUTEN-7659][CH] Implement splittable bzip2 decompression

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Validate all ifThen sub-expressions
Fixes: #7661
After this:
> [GLUTEN-7661][VL] Fix validate native IfThen expr

- ep/build-velox/src/get_velox.sh
```
a1d923ed1 by NEUpanning, Add support for "week of month" in SimpleDateTimeFormatter (#11103)
40493627a by Jialiang Tan, Let HashJoinBridge be able to reclaim memory in the middle state (#11324)
9784f22d8 by Wei He, Allow ExpressionRunnerTest to run with PrestoQueryRunner (#11254)
b2c7446bc by Pedro Eugenio Rocha Pedreira, Updates to README file (#11349)
```
> [GLUTEN-6887][VL] Daily Update Velox Version (2024_10_28)

- .github/workflows/velox_backend.yml
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/GlutenInjector.scala
Part of #7143 
Use test system property `spark.gluten.ras.enabled` to enable RAS globally for verifying RAS=ON in UTs. Spark will pick the system property to set the corresponding config option automatically.
Add two CI jobs with `spark.gluten.ras.enabled=true`:
* run-spark-test-spark35-ras
* run-spark-test-spark35-slow-ras
The tests cannot pass so far and the outputs will be ignored. We should fix the failed tests one by one then can move on with #7143.
And with other cleanups in passing.
> [GLUTEN-7143][VL] CI: Add GHA job for running all UTs with RAS=ON

- dev/vcpkg/ports/folly/vcpkg.json
(cherry picked from commit 65cdf22c07ff681c991c89ad30d34efda7ab1f01)
Backport #7038 to branch 1.2
> [GLUTEN-7037][VL][1.2] Add dwarf dependency to folly when building with vcpkg

- backends-velox/src/test/scala/org/apache/gluten/execution/FallbackSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/planner/VeloxRasSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenSessionExtensions.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/InjectorControl.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/cost/LegacyCostModel.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/cost/RoughCostModel.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/plan/GlutenPlanModel.scala
- gluten-substrait/src/main/scala/org/apache/gluten/planner/property/Conv.scala
- gluten-substrait/src/main/scala/org/apache/gluten/utils/PlanUtil.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Part of #7143
Fix following UTs when RAS=ON:
```
Line  3111: 2024-10-28T03:45:33.5270060Z - fallback final aggregate of collect_list *** FAILED ***
Line  3272: 2024-10-28T03:45:44.0086490Z - count(1) on csv scan *** FAILED ***
Line  4403: 2024-10-28T03:47:23.3298481Z - Date type *** FAILED ***
Line  4794: 2024-10-28T03:47:41.5650328Z - Date type *** FAILED ***
Line  5030: 2024-10-28T03:47:50.0627363Z - count(1) on csv scan *** FAILED ***
Line  5129: 2024-10-28T03:47:50.4155755Z - Struct Literal *** FAILED ***
Line  5131: 2024-10-28T03:47:50.4905146Z - Array Literal *** FAILED ***
Line  5133: 2024-10-28T03:47:50.5682606Z - Map Literal *** FAILED ***
Line  5135: 2024-10-28T03:47:50.6383717Z - Null Literal *** FAILED ***
Line  5137: 2024-10-28T03:47:50.7036012Z - Scalar Type Literal *** …
```
> [GLUTEN-7143][VL] Fix several UTs for RAS

- .github/workflows/velox_backend.yml
Job name: `TPC-DS SF30.0 Parquet local spark3.2 Q95 low memory, memory isolation on`
Stop ignoring its result to make it be able to fail CI.
> [VL] CI: One OOM GHA job has passed, stop ignoring its result

- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
- gluten-ut/test/src/test/scala/org/apache/gluten/expressions/GlutenExpressionMappingSuite.scala
Part of #7143
This fixes UT `GlutenExpressionMappingSuite.GLUTEN-7213: Check fallback reason with CheckOverflowInTableInsert` in RAS.
> [VL] RAS: Fix fallen back plan nodes are not tagged with meaningful fallback reasons

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
The `VeloxParquetWriteSuite` currently checks the compression codec based on the file extension, which is no longer applicable starting from Spark 3.4.
We could check the compression codec using Parquet metadata, making it compatible across all Spark versions.
Unit test:
```bash
mvn test -Phadoop-3.3 -Pscala-2.12 -Pbackends-velox -Pceleborn -Pudf -Dsuites="org.apache.spark.sql.execution.VeloxParquetWriteSuite" -pl :backends-velox -Pspark-3.4
```
> [VL] Enhance write parquet with compression codec test

- backends-velox/src/main/java/org/apache/gluten/metrics/Metrics.java
- backends-velox/src/main/java/org/apache/gluten/metrics/OperatorMetrics.java
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxMetricsApi.scala
- backends-velox/src/main/scala/org/apache/gluten/metrics/HashAggregateMetricsUpdater.scala
- backends-velox/src/main/scala/org/apache/gluten/metrics/MetricsUtil.scala
- cpp/core/jni/JniWrapper.cc
- cpp/core/utils/Metrics.h
- cpp/velox/compute/WholeStageResultIterator.cc
Related Velox code:
https://github.com/facebookincubator/velox/blob/main/velox/vector/LazyVector.cpp#L72
> [VL] Add metric to indicate aggregation pushdown

- gluten-ras/common/src/main/scala/org/apache/gluten/ras/memo/Memo.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/test/src/test/scala/org/apache/gluten/expressions/GlutenExpressionMappingSuite.scala
Part of #7143 
This reverts #7731
See #7763, RAS doesn't support detailed fallback report yet. Leave the feature as TODO.
This also fixes two UTs:
GlutenFallbackSuite | Gluten - test fallback logging
GlutenFallbackSuite | Gluten - Add logical link to rewritten spark plan
> [GLUTEN-7143][VL] RAS: Revert #7731, disable the relevant test cases since RAS doesn't report fallback details due to #7763

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/rewrite/RewriteSparkPlanRulesManager.scala
Part of https://github.com/apache/incubator-gluten/issues/7143
Catch the exceptions to align with legacy planner.
Moving forward, should fix https://github.com/apache/incubator-gluten/issues/7766.
This fixes UT `GlutenReplaceHashWithSortAggSuite | Gluten - replace partial and final hash aggregate together with sort aggregate`
> [GLUTEN-7143][VL] RAS: Catch exceptions thrown from rewrite rules

- backends-clickhouse/src/main/java/org/apache/gluten/execution/CHNativeCacheManager.java
- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala
- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenRpcMessages.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCHCacheDataCommand.scala
- cpp-ch/local-engine/Storages/Cache/CacheManager.cpp
- cpp-ch/local-engine/Storages/Cache/CacheManager.h
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
> [GLUTEN-7765][CH] Support CACHE META command for MergeTree table

- gluten-core/src/main/scala/org/apache/gluten/softaffinity/SoftAffinityManager.scala
- gluten-core/src/main/scala/org/apache/gluten/softaffinity/strategy/SoftAffinityAllocationTrait.scala
- gluten-core/src/main/scala/org/apache/gluten/softaffinity/strategy/SoftAffinityStrategy.scala
- gluten-substrait/src/test/scala/org/apache/spark/softaffinity/SoftAffinitySuite.scala
Before this pr, the order of the soft affinity hash executor list is random, will lead to cache data missing after restarting the spark applications. Now make sure the softaffinity hash executor list is in order, after restarting the spark application, the computed file preferred location are the same as the ones before restarting.
Close #7775.
(Fixes: #7775)
> [GLUTEN-7775][CORE] Make sure the softaffinity hash executor list is in order

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/rewrite/PullOutPreProject.scala
- gluten-substrait/src/main/scala/org/apache/gluten/utils/PullOutProjectHelper.scala
> [GLUTEN-7753][CORE] Do not replace literals of expand's projects in `PullOutPreProject`

- dev/build-thirdparty.sh
Builds third party libs jar using the `jar` binary from `JAVA_HOME`. Just using `jar` would pick up the JDK from the classpath of the system, and that is not ideal since a dev env can have multiple JDK configured.
(Fixes: \#7446)
Existing unit and integration tests
> [GLUTEN-7446][BUILD] build third party libs using jar from JAVA_HOME

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFilterSuite.scala
Velox treat missing column as null, will output incorrect results when spark.sql.parquet.mergeSchema enabled.
Fixes: #7174
Enable some excluded tests.
> [GLUTEN-7174][VL] Force fallback scan operator when spark.sql.parquet.mergeSchema enabled

- .github/workflows/build_bundle_package.yml
Refine the package script
fixes #7741
pass GHA
> [GLUTEN-7741][VL] refine build package tool

- backends-velox/pom.xml
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
`gluten-substrait` is referred twice in `backends-velox`'s pom.xml and causes a compile time warning. Fix it.
And with a minor follow-up change for https://github.com/apache/incubator-gluten/pull/7764.
> [VL] Remove a duplicated Maven dependency, and some follow-ups for #7764

- cpp/core/jni/JniWrapper.cc
Add a check to determine whether a byte array is constructed when trying to serialize columnar batches, rather than crashing.
Relates: \#7624
> [VL] In `ColumnarBatchSerializerJniWrapper_serialize`, check if the byte array is constructed successfully

- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/operators/plannodes/RowVectorStream.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- gluten-substrait/src/main/scala/org/apache/gluten/extension/GlutenPlan.scala
This could be a better approach to replace https://github.com/apache/incubator-gluten/pull/7244.
Could remove [this commit](https://github.com/oap-project/velox/commit/b55c4dc49c1ea5c3f29793452dc48f77569164b2) from Gluten's Velox fork when this change is landed.
> [GLUTEN-7243][VL] Suspend the Velox task while reading an input Java iterator to make the task spillable

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Parser/RelParsers/CrossRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/JoinRelParser.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/tests/gtest_ch_join.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20241105)

- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/delta-20/org/apache/spark/sql/delta/rules/CHOptimizeMetadataOnlyDeltaQuery.scala
- backends-clickhouse/src/main/delta-23/org/apache/spark/sql/delta/rules/CHOptimizeMetadataOnlyDeltaQuery.scala
- backends-clickhouse/src/main/delta-23/org/apache/spark/sql/delta/stats/PrepareDeltaScan.scala
- backends-clickhouse/src/main/delta-32/io/delta/tables/ClickhouseTable.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/DeltaLog.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/Snapshot.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/catalog/ClickHouseTableV2.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/commands/DeleteCommand.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/commands/OptimizeTableCommand.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/commands/UpdateCommand.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/commands/VacuumCommand.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/commands/merge/ClassicMergeExecutor.scala
- backends-clickhouse/src/main/delta-32/org/apache/spark/sql/delta/rules/CHOptimizeMetadataOnlyDeltaQuery.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/SparkInjector.scala
For the Spark 3.3 + Delta 2.3, when the 'spark.databricks.delta.stats.skipping' is off, there are some queries failed with the subquery, the error message is below:
```
java.lang.IllegalArgumentException: requirement failed
at scala.Predef$.require(Predef.scala:268)
at org.apache.spark.sql.delta.SubqueryTransformerHelper.transformWithSubqueries(SubqueryTransformerHelper.scala:42)
at org.apache.spark.sql.delta.SubqueryTransformerHelper.transformWithSubqueries$(SubqueryTransformerHelper.scala:40)
at org.apache.spark.sql.delta.stats.PrepareDeltaScan.transformWithSubqueries(PrepareDeltaScan.scala:291)
at org.apache.spark.sql.delta.PreprocessTableWithDVs.preprocessTablesWithDVs(PreprocessTableWithDVs.scala:67)
at org.apache.spark.sql.delta.PreprocessTableWithDVs.preprocessTablesWithDVs$(Preproc …
```
> [GLUTEN-7812][CH] Fix the query failed for the mergetree format when the 'spark.databricks.delta.stats.skipping' is off

- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos7.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos8.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderCentos9.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderDebian11.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderDebian12.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderUbuntu2004.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoaderUbuntu2204.scala
velox does not depend on libhdfs.
> [VL] Remove load shared libhdfs

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDataFrameSuite.scala
Fixes: #7749, to align with Spark's change introduced by https://github.com/apache/spark/pull/41535.
> [GLUTEN-7749][VL] Trim ISOControl characters in string for casting to integral type

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- cpp-ch/local-engine/Common/GlutenConfig.cpp
- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Disks/ObjectStorages/CompactObjectStorageDiskTransaction.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/CompactObjectStorageDiskTransaction.h
- cpp-ch/local-engine/Storages/Cache/CacheManager.cpp
- cpp-ch/local-engine/Storages/Cache/CacheManager.h
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.h
Rename Mergetree part file name to avoid duplicated file name and support prefetch mergetree data file
unit tests
> [CH] Rename Mergetree part file name to avoid duplicated file name

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
fix https://github.com/apache/incubator-gluten/issues/7807. 
run tpc-ds q5, it work fine.
> [GLUTEN-7807] Transform relation bound attr using the name if attr'exprId not found.

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHMetricsApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxMetricsApi.scala
- backends-velox/src/main/scala/org/apache/gluten/metrics/InputIteratorMetricsUpdater.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxMetricsSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/MetricsApi.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
Fix issue https://github.com/apache/incubator-gluten/issues/7079 collecting metrics for `InputIteratorTransformer` of broadcast exchange.
Here is an example showing the difference before and after the change:
Execute below query on tpch test dataset, the table `lineitem` has 2 partitions:
```
select /*+ BROADCAST(part) */ * from part join lineitem on l_partkey = p_partkey
```
Before the change, the metrics showing in UI is:
After the change, the metrics showing in UI is:
UT added.
> [GLUTEN-7079][VL] Fix metrics for InputIteratorTransformer of broadcast exchange

- cpp/velox/config/VeloxConfig.h
- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/shuffle/VeloxRssSortShuffleWriter.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Add config `spark.gluten.sql.columnar.backend.velox.reclaimMaxWaitMs` to avoid dead lock when memory arbitration has bug, default timeout is 60min.
> [GLUTEN-7800][VL] Add config for max reclaim wait time to avoid dead lock when memory arbitration

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseExcelFormatSuite.scala
- cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.cpp
- cpp-ch/local-engine/Storages/Serializations/ExcelReadHelpers.h
> [GLUTEN-7829][CH] Fix read csv file with datetime field not equals spark

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
> [GLUTEN-7778][CH] Make aggregation output schema same as CH native

- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.h
  | Default | with PR
-- | -- | --
time of input iterator | 397.95 | 403.29
time of scan and filter | 246.58 | 253.03
not_counted | 216.78 | 224.2
time to shuffle c2r | **159.02** | **134.57**
time to compress | 93.77 | 93.09
time to deserialize | 67.05 | 67.93
time to decompress | 49.18 | 49.85
shuffle write time | 46.83 | 41.75
time of rowConstruction | 43.07 | 44.19
time to shuffle sort | 42.95 | 42.99
time of project | 42.16 | 41.24
time of hash probe | 41.04 | 40.54
idle | 34.21 | 23.12
time of aggregation | 14.53 | 14.33
time of postProjection | 7.83 | 7.83
> [VL] Sort shuffle writer use vectorized c2r

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFieldIdIOSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenCharVarcharTestSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFieldIdIOSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenCharVarcharTestSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFieldIdIOSuite.scala
The velox has supported parquet writer with the complex data type, such as MAP, ARRYY, so we may support them in gluten.
(Fixes: https://github.com/apache/incubator-gluten/issues/7675)
Add unittests
> [GLUTEN-7675][VL] Support parquet write with complex data type(eg. MAP, ARRYY)

- tools/gluten-te/ubuntu/dockerfile-buildenv
A follow-up for https://github.com/apache/incubator-gluten/pull/7578 to fix the [ubuntu-based containerized build](https://github.com/apache/incubator-gluten/tree/main/tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs).
Test will be run locally.
> [GLUTEN-7458][VL] Upgrade GCC to version 11 in gluten-te's ubuntu dockerfile

- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHWindowGroupLimitExecTransformer.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/HashAggregateExecTransformer.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/TopNTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicPhysicalOperatorTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/CartesianProductExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ExpandExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/GenerateExecTransformerBase.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/JoinUtils.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/LimitExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/SampleExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/SortExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WindowExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WindowGroupLimitExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/python/EvalPythonExecTransformer.scala
A code cleanup to remove used member `TransformContext#inputAttributes`.
> [CORE] Remove member TransformContext#inputAttributes as unused

- .github/workflows/velox_backend.yml
- backends-velox/src/test/java/org/apache/gluten/test/MockVeloxBackend.java
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Derived from discussion in https://github.com/apache/incubator-gluten/issues/7810.
We disabled Velox's background IO threads by default since https://github.com/apache/incubator-gluten/pull/7165. As we had added shared memory allocation lock and fixed [cross-task spilling issues](https://github.com/apache/incubator-gluten/issues/7243), could explore enabling the feature by default again.
> [VL] Re-enable background IO threads by default

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenWriterColumnarRules.scala
https://github.com/apache/incubator-gluten/issues/7850
unit tests
> [GLUTEN-7850][VL] Native writer support CreateHiveTableAsSelectCommand

- cpp/velox/CMakeLists.txt
- cpp/velox/symbols.map
- cpp/velox/tests/CMakeLists.txt
This is a follow-up pr for [this comment](https://github.com/apache/incubator-gluten/pull/7497#issuecomment-2408417284).
If not hidden, the below error can be reported when running gluten CPP test.
```
something wrong with flag 'velox_memory_num_shared_leaf_pools' in file '/__w/incubator-gluten/incubator-gluten/ep/build-velox/build/velox_ep/velox/flag_definitions/flags.cpp'.  One possibility: file '/__w/incubator-gluten/incubator-gluten/ep/build-velox/build/velox_ep/velox/flag_definitions/flags.cpp' is being linked both statically and dynamically into this executable.
CMake Error at /usr/local/lib64/python3.9/site-packages/cmake/data/share/cmake-3.28/Modules/GoogleTestAddTests.cmake:112 (message):
Error running test executable.
Path: …
```
> [VL] Do not use --version-script link option on Darwin

- .github/workflows/velox_weekly.yml
- dev/builddeps-veloxbe.sh
The dynamic build path on Ubuntu-20.04 is broken.
https://github.com/apache/incubator-gluten/actions/runs/11768073834/job/32777486610
The root cause is, we pre-install gcc-11, then create a symbolic link: `sudo ln -sf /usr/bin/gcc-11 /usr/bin/gcc` before executing Gluten script to build. But Velox also installs gcc-11 which overwrites the pre-installed one and then makes symbolic link invalid.
CI.
> [VL] Fix weekly scheduled GHA job

- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/Parser/ExpressionParser.h
> [GLUTEN-7907][CH] Fixed data race in `ExpresionParser::getUniqueName`

- .github/labeler.yml
`gluten-data` was renamed to `gluten-arow`. Update the name in labeler.yml.
> [VL] CI: Fix out-of-date module name in labeler.yml

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/FallbackRules.scala
(Fixes: \#7078)
performing fallback detection for Scan in advance is good and does not introduce any side effects.
manual tests
> [GLUTEN-7078][CORE] The fallback check for Scan should not be skipped when DPP is present

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/ExtendedGeneratorNestedColumnAliasing.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
- cpp-ch/local-engine/Storages/Output/WriteBufferBuilder.cpp
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
(Fixes: \#7868)
``` sql
CREATE TEMPORARY VIEW aj
USING parquet
OPTIONS (
path  "/data1/liyang/cppproject/spark/spark-3.3.2-bin-hadoop3/aj"
); 
select * from (
select 
game_name,  event.event_info['tab_type']  as entrance
from aj
lateral view explode(split(nvl(event.event_info['game_name'],'0'),',')) game_name as game_name
where  event.event_info['action'] > 100
)
where game_name = '-1' ;
set spark.gluten.sql.extendedGeneratorNestedColumnAliasing = true;
No rows selected (0.532 seconds)
No rows selected (0.445 seconds)
No rows selected (0.447 seconds)
set …
```
> [GLUTEN-7868][CH] Nested column pruning for Project(Filter(Generate))

- .github/workflows/util/install_spark_resources.sh
- .github/workflows/velox_backend.yml
- pom.xml
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/SparkShimProvider.scala
- tools/gluten-it/pom.xml
Revert Spark release version from v3.5.3 to v3.5.2 due to datalake issue.
(Fixes: \#7637)
> [CORE] Revert Spark version from v353 to v352

- cpp/velox/operators/plannodes/RowVectorStream.h
#7748 missed a local object name to make RAII work with correct scope.
Without the change, the suspend state will be cleared immediately since the local object will be destroyed right after it's created. So `hasNext()` call will not consider the current driver as suspended. As a result #7748 will not work and spill may still cause hanging.
> [GLUTEN-7243][VL] A follow-up fix for #7748

- cpp/velox/CMakeLists.txt
Currently, static google_cloud_cpp_storage lib is used in both static build and dynamic build. The lib suffix was wrongly set for CMake to find the lib.
Local verification.
> [VL] Fix wrong lib suffix for google_cloud_cpp_storage

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxScanSuite.scala
- gluten-substrait/src/test/scala/org/apache/gluten/benchmarks/RandomParquetDataGenerator.scala
Ports tests from https://github.com/apache/incubator-gluten/pull/5954 for scan with filter on decimal/timestamp/binary field.
Tested with unit tests.
> [VL] Add test for scan operator with filter on decimal/timestamp/binary field

- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
Fixes: \#7362
Resolved by #6754, add test for it.
UT
> [GLUTEN-7362][VL] Add test for 'IN' and 'OR' filter in Scan

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
Fixes: https://github.com/apache/incubator-gluten/issues/7837
Spark driver should not initialize cache if not in local mode
> [GLUTEN-7837][VL] Spark driver should not initialize cache if not in local mode

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/heuristic/OffloadSingleNode.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanNestedColumnPruning.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
> [GLUTEN-7267][CH]Support nested column pruning for `HiveTableScan`  json/parquet/orc format

- .github/workflows/velox_backend.yml
Just a minor change in case of ccache loses its efficacy for some reason.
P.S.
For the current pr, we got the below statistics printed.
```
cache directory                     /__w/incubator-gluten/incubator-gluten/.ccache
primary config                      /__w/incubator-gluten/incubator-gluten/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats updated                       Fri Nov 15 03:03:00 2024
cache hit (direct)                112337
cache hit (preprocessed)             899
cache miss                         10042
cache hit rate                     91.85 %
called for link                      368
cleanups performed                    59
files in cache                     11473
cache size                           4.3 GB
max cache size …
```
> [GLUTEN-7499][VL][CI] Print ccache statistics for tracking its efficacy

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
- gluten-iceberg/src/test/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/LocalFilesNode.java
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
To enable support for ViewFS in Gluten, we need to call FileSystem.get(viewPath.toUri, serializableHadoopConf.value) to convert the ViewFS path to an HDFS path. Prior to this PR, we passed serializableHadoopConf in getSplitInfosFromPartitions for the conversion. This PR updates the path values after obtaining the LocalFilesNode, thereby reducing the number of times serializableHadoopConf needs to be passed. With this PR, Jenkins performance can improve by about 5%.
Jenkins test
> Add config to support viewfs in Gluten.

- cpp/velox/tests/CMakeLists.txt
- cpp/velox/tests/MemoryManagerTest.cc
- gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
Port #6563 and #6679 to branch-1.2
local
> [VL][1.2] Port 6563 6679 for build options and collectQueryExecutionFallbackSummary fix

- gluten-celeborn/clickhouse/src/main/scala/org/apache/spark/shuffle/CHCelebornHashBasedColumnarShuffleWriter.scala
- gluten-celeborn/common/src/main/scala/org/apache/spark/shuffle/CelebornHashBasedColumnarShuffleWriter.scala
- gluten-celeborn/velox/src/main/scala/org/apache/spark/shuffle/VeloxCelebornHashBasedColumnarShuffleWriter.scala
Port #6432 and #6657 to branch 1.2 for Celeborn related bug fix
local
> [VL][1.2] Port 6432 6657 for Celeborn bug fix in branch 1.2

- backends-velox/pom.xml
- backends-velox/src/test-iceberg/scala/org/apache/gluten/execution/VeloxIcebergSuite.scala
- backends-velox/src/test-iceberg/scala/org/apache/gluten/execution/VeloxTPCHIcebergSuite.scala
- gluten-iceberg/pom.xml
- gluten-iceberg/src/test/scala/org/apache/gluten/execution/IcebergSuite.scala
#7910 
Make Maven module `backends-velox` depend on `gluten-iceberg` than the opposite, to make sure the common source code and UT code (particularly `IcebergSuite` at the moment) to be accessible from other backend modules (particularly `backends-clickhouse` at the moment).
The new source/test folder `backends-velox/src/main-iceberg` / `backends-velox/src/test-iceberg` are added for placing code that relate to Velox+Iceberg support.
TODO in subsequent PRs: 
1. Enable Maven code linters for `backends-velox/src/main-iceberg` / `backends-velox/src/test-iceberg`
> [GLUTEN-7910][CORE][VL] Flip dependency direction for gluten-iceberg

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/heuristic/ExpandFallbackPolicy.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenExplainUtils.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
Replace `spotless:off` with `format:off`. The latter can be recognized by any Scala linters backed by scalafmt.
After the fix, Intellij's reformat shortcut (`ctrl+alt+l` for gnome preset) will respect the disablers.
> [CORE] Avoid formatted comments from being messed by non-spotless linters (especially IDE linters)

- cpp-ch/local-engine/Operator/AdvancedExpandStep.cpp
- cpp-ch/local-engine/Operator/AdvancedExpandStep.h
Fixes: #7986
Always try to aggregate the expand rows which are without full grouping keys.
unit tests
> [GLUTEN-7986][CH] Improve lazy expand for high cardinality aggregation

- pom.xml
A minor cleanup. We'd use lower case on the first alphabet for Maven profile names.
> [CORE] Minor: Use lower case for Maven profile names

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/columnarbatch/CHBatch.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/main/scala/org/apache/gluten/columnarbatch/VeloxBatch.scala
- gluten-arrow/src/main/scala/org/apache/gluten/columnarbatch/ArrowBatches.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/property/Conv.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/EnsureLocalSortRequirements.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuite.scala
Add API `BatchType#ensureRegistered()` for explicit registration of the batch type. The previous way (e.g., `VeloxBatch.getClass`) is hard to reason about.
> [CORE] Query planner: A more explicit practice to register columnar batch types

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Common/GlutenStringUtils.h
- cpp-ch/local-engine/Operator/PartitionColumnFillingTransform.cpp
- cpp-ch/local-engine/Parser/FunctionExecutor.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- cpp-ch/local-engine/Storages/IO/NativeReader.cpp
- cpp-ch/local-engine/Storages/IO/NativeWriter.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/SubstraitFileSource.cpp
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
(Fixes: \#7979)
"SPARK-36673: Only merge nullability for Unions of struct" was excluded because of https://github.com/apache/incubator-gluten/issues/7985
> [GLUTEN-7979][CH] Fix exception cause by one child of UnionExec outputs Array(Nothing) while the other outputs Array(String)

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetAQESuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetColumnarShuffleAQESuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetColumnarShuffleSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpcds/GlutenClickHouseTPCDSParquetSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetAQESuite.scala
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
- gluten-substrait/src/main/scala/org/apache/gluten/execution/JoinUtils.scala
Now Vanilla Spark does not support the right anti/semi join, but CH backend does. According to the runtime statistics, it can convert the `A left anti/semi join B` to `B right anti/semi join A` when AQE is on and the side ot A table is the smaller than B table.
Close #7971.
(Fixes: #7971)
> [GLUTEN-7971][CH] Support using left side as the build table for the left anti/semi join

- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/compute/WholeStageResultIterator.h
- cpp/velox/config/VeloxConfig.h
- gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Port #7025 and #7132 for collectMetrics and skip command execution bugfix 
local
> [VL][1.2] Port #6573 #7025 #7132

- backends-clickhouse/pom.xml
- backends-velox/pom.xml
- gluten-core/pom.xml
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedApplier.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/util/AdaptiveContext.scala
- gluten-ut/pom.xml
Port #7121 and #7448 for search stack trace and security issue fix
local
> [VL][1.2] Port #7121 #7448

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/PruneNestedColumnsInHiveTableScan.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/offload/OffloadSingleNodeRules.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanNestedColumnPruning.scala
Following https://github.com/apache/incubator-gluten/pull/7268, move the new code to an individual rule `PruneNestedColumnsInHiveTableScan`.
The reason is `HiveTableScanNestedColumnPruning` actually matches on a `project + hive scan` pattern so is not simply offloading a project. Move the code out from `OffloadSingleNode` which targets to handle one single query plan node.
> [GLUTEN-7267][CORE][CH] Move schema pruning optimization of HiveTableScan to an individual post-transform rule

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
Fix #7999.
Add file suffix check in `CompressionCodecSuite`.
> [GLUTEN-7999][VL] Add compression codec extension to velox written parquet file

- gluten-core/src/main/scala/org/apache/gluten/execution/BroadcastNestedLoopJoinExecTransformer.scala
BNLJ with unsupported join type throw the following IllegalArgumentException, which fixed in https://github.com/apache/incubator-gluten/pull/6290. Backport to gluten 1.2.
```
java.lang.IllegalArgumentException: VeloxBroadcastNestedLoopJoinExecTransformer not take LeftAnti as the JoinType
at org.apache.gluten.execution.BroadcastNestedLoopJoinExecTransformer.output(BroadcastNestedLoopJoinExecTransformer.scala:83)
at org.apache.spark.sql.catalyst.plans.QueryPlan.schema$lzycompute(QueryPlan.scala:375)
at org.apache.spark.sql.catalyst.plans.QueryPlan.schema(QueryPlan.scala:375)
at org.apache.gluten.extension.GlutenPlan.doValidate(GlutenPlan.scala:72)
at org.apache.gluten.extension.GlutenPlan.doValidate$(GlutenPlan.scala:70)
at org.apache.gluten.execution.BroadcastNestedLoopJoinExecTransformer.d …
```
> [GLUTEN-7126][CORE][1.2] Fix issue that unsupported join type in BNLJ is not fallback

- gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/gluten/uniffle/UniffleShuffleManager.java
- gluten-uniffle/velox/src/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java
Port #6698 #7525 #7560 to fix Uniffle related bug fix in branch-1.2
local
> [GLUTEN-7126][VL][1.2] Port #6698 #7525 #7560 for Uniffle bug fix

- cpp/core/CMakeLists.txt
- ep/build-velox/src/get_velox.sh
1. Keep build flags consistent with Velox Module in cpp/velox/CMakeList.txt
2. Keep velox build flag to default to increase coverage of targeted CPU Platforms
Local Build and tested on multiple GCE VMs - N1, N2, C2, N2D, C2D etc
> [GLUTEN-7950][VL] Keep Core module's build flag consistent with Velox

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/Ras.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/RasPlanner.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/dp/DpPlanner.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/exaustive/ExhaustivePlanner.scala
- gluten-ras/common/src/test/scala/org/apache/gluten/ras/PropertySuite.scala
Remove parameter "altConstraintSets` from RAS planner as it's not an optimal approach for root-level physical property enforcement. Perhaps a better way is to enrich "requiredChildrenConstraint" in property model API to support multiple constraint combinations, then passing a fake root with wanted constraint sets.
And it's practical to remove the alternative constraint sets immediately since it is not likely strictly required by Gluten, because Gluten converts Spark plan nodes to Gluten plan nodes through regular RAS rules than through enforcer rules.
> [VL] RAS: Remove alternative constraint sets passing to RAS planner

- cpp/CMakeLists.txt
- cpp/core/CMakeLists.txt
- cpp/velox/CMakeLists.txt
This PR cleans up duplicate code in cpp/velox and cpp/core CMakeLists.txt and moves them to the top level common CMakeLists.txt
Local Build
> [VL] Clean up duplicate CMake code for setting CMAKE_CXX_FLAGS

- dev/vcpkg/ports/libelf/portfile.cmake
The link we use for downloading libelf no longer works and is causing failures in static build:
https://ftp.osuosl.org/pub/blfs/conglomeration/libelf/libelf-0.8.13.tar.gz
Change to another mirror.
> [VL] vcpkg: Broken libelf mirror

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
Velox does not support lead/lag when its input is foldable.
(Fixes: \#7631)
UT
> [GLUTEN-7631][VL] Fall back lead/lag if input is foldable

- backends-velox/src/main/scala/org/apache/spark/api/python/ColumnarArrowEvalPythonExec.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/ColumnarToColumnarExec.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/GlutenPlan.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/plan/GlutenPlanModel.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ColumnarToRowExecBase.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseTransformStages.scala
1. Simplify calls on `ConventionReq.of`
2. Remove unnecessary inheritances from `KnownChildConvention`
3. Rename `KnownRowTypeForSpark33AndLater` to `KnownRowTypeForSpark33OrLater`
4. Add comments for `GlutenPlan`
> [GLUTEN-6920][VL] Following #8036, append some code cleanups

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
Velox does not support nth_value when its input is foldable.
Although vanilla Spark supports foldable input of nth_value, there is almost no usage scenario in this case, and the values ​​obtained are all null, so simply fall back for it.
(Fixes: \#8061)
UT
> [GLUTEN-8061][VL] Fall back nth_value if input is foldable

- cpp/core/config/GlutenConfig.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/Options.h
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Spill.cc
- cpp/core/shuffle/Spill.h
- cpp/core/shuffle/Utils.cc
- cpp/core/shuffle/Utils.h
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
This pr fixed https://github.com/apache/incubator-gluten/issues/7860 by `MmapFileStream` extended `arrow:io::InputStream`. `MmapFileStream` will invoke MADV_DONTNEED to release previous memory when read next range of data.
``` scala
// Generate 10 partitions, each partition has about 10GB random data.
def gen(scale: Int, parts: Int) = {
sc.parallelize(1 to (1024*1024), numSlices = 1000)
.map(x => (x % 1000, randStr(scale * parts)))
.repartition(parts)
.toDF("a", "b")
.save./* ... */
}
// Trigger shuffle spill by `repartition(50)`.
def test(parts: Int = 50) = {
spark.read./* ... */.repartition(parts)
.filter(expr("a < 0*rand()")) // avoid pushdown repartition
}
```
``` shell
spark.executor.memory=512M
spark.yarn.executor.memoryOverhead=512M …
```
> [GLUTEN-7860][CORE] In shuffle writer, replace MemoryMappedFile to avoid OOM

- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/test-iceberg/scala/org/apache/gluten/execution/iceberg/ClickHouseIcebergSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHColumnarShuffleParquetAQESuite.scala
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.cpp
- gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/TransformerApi.scala
Support reading data from the iceberg with CH backend
- basic iceberg scan transformer
- read from the iceberg with the copy-on-write mode
> [GLUTEN-8094][CH][Part-1] Support reading data from the iceberg with CH backend

- gluten-core/src/main/scala/org/apache/spark/shuffle/GlutenShuffleManager.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/LookupKey.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/ShuffleManagerLookup.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/ShuffleManagerRegistry.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/ShuffleManagerRouter.scala
- gluten-core/src/test/scala/org/apache/spark/shuffle/GlutenShuffleManagerSuite.scala
#8060
Prepare `GlutenShuffleManager` as the new shuffle manager implementation of Gluten.
The shuffle manager is simply a router for all shuffle managers registered through API `ShuffleManagerRegistry.get().register`.
About backward compatibility:
1. Use of `ColumnarShuffleManager` / `CelebornShuffleManager` / `UniffleShuffleManager` will be deprecated in future (perhaps, in next few of PRs). Then once Spark configuration like `spark.shuffle.manager=....ColumnarShuffleManager` is specified explicitly, Gluten could still run but raise a warning indicating that the option is deprecated.
2. Instead, use of `GlutenShuffleManager` will be recommended. `GlutenShuffleManager` will maintain a mechanism (either automatically or by configuration) to route shuffle manager calls to the underlying …
> [GLUTEN-8060][CORE] GlutenShuffleManager as a registry of shuffle managers

- .github/workflows/velox_weekly.yml
Fixes job failure: https://github.com/apache/incubator-gluten/actions/runs/12108589900.
GHA checkout requires higher GLIBC version than that installed in centos-7 by default.
Existing test.
> [GLUTEN-8046][VL] Fix GHA checkout issue on centos-7 for weekly build job

- cpp/velox/operators/plannodes/RowVectorStream.h
SuspendedSection was removed from Velox code base from commit https://github.com/facebookincubator/velox/commit/fc5aa37fe44ca5bee9c91f9bee69069f0c804b11.
The PR introduce the code back to Gluten's code base to replace the temporary manual resource suspension code to avoid UBs when exception throws from `iterator_->hasNext()` or `iterator_->next()`.
> [VL] Add back RAII style Velox driver suspension into RowVectorStream

- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/config/VeloxConfig.h
- ep/build-velox/src/get_velox.sh
Prefix sort can reduce the spill sort time by 3x with the sampled Meta production query but timsort increase the sort time by 20%.  So timsort performance seems depends on the actual data pattern.
After pick this PR  https://github.com/facebookincubator/velox/pull/11527, a query in jenkins spill with string is 41s prefixsort vs 37s timsort vs 63s stdsort.
Config `spark.gluten.sql.columnar.backend.velox.spillPrefixsortEnabled` disable in this PR, enable it as default after test.
Relevant Velox PR: https://github.com/facebookincubator/velox/pull/11384
Resolves https://github.com/apache/incubator-gluten/issues/7900
> [GLUTEN-7900][VL] Enable prefix sort config in spill

- gluten-substrait/src/main/scala/org/apache/gluten/execution/BatchScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AbstractBatchScanExec.scala
SQL: `select l_partkey from lineitem where l_partkey + 1 > 5 and rand() < 0.5`
Before pr:
V1:
V2:
After pr:
V1:
V2:
> [CORE] Add nativeFilters info for simpleString of scan

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarWriteFilesExec.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/VeloxColumnarWriteFilesExec.scala
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/gluten/backend/Backend.scala
- gluten-core/src/main/scala/org/apache/gluten/component/Component.scala
- gluten-core/src/main/scala/org/apache/gluten/component/package.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenSessionExtensions.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/plan/GlutenPlanModel.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicTransform.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/LegacyOffload.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/ConventionFunc.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/validator/Validator.scala
- gluten-core/src/test/scala/org/apache/gluten/component/ComponentSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendsApiManager.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/EnsureLocalSortRequirements.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/offload/OffloadSingleNodeRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala
It's to remove all code in `FallbackByNativeValidation` instead reuse the code from offload rules for native validation. 
Also, amend a minor package name refactor following https://github.com/apache/incubator-gluten/pull/8143.
Test:
All existing UTs.
> [CORE] Query planner: Simplify validator `FallbackByNativeValidation` 

- .github/workflows/build_bundle_package.yml
Fix upload arrow path of build bundle package CI
https://github.com/wForget/gluten/actions/runs/12249799417
> [VL] Fix upload arrow path of build bundle package gha

- gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
When parsing Iceberg partition column fields, you should build the index first and then apply the filter. Otherwise, the field cannot correspond correctly when retrieving data using `partition.get`
for error
```
Error operating EXECUTE_STATEMENT: Wrong class, expected java.lang.Integer, but was java.lang.String, for object: xxx
java.lang.IllegalArgumentException: Wrong class, expected java.lang.Integer, but was java.lang.String, for object: xxxx
at org.apache.iceberg.PartitionData.get(PartitionData.java:119)
at org.apache.iceberg.spark.source.GlutenIcebergSourceUtil$.$anonfun$getPartitionColumns$3(GlutenIcebergSourceUtil.scala:180)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
```
[fix-8202](https://github.com/apache/incubator-gluten/issues/8202)
(Please …
> [GLUTEN-8202][ICEBERG] Fix get iceberg index error

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
Not all components' build information is printed. The patch fixes the issue.
Before:
```
2024-12-11T01:56:45.0402500Z Component: VeloxIceberg
2024-12-11T01:56:45.0402795Z Component Branch: N/A
2024-12-11T01:56:45.0403095Z Component Revision: N/A
2024-12-11T01:56:45.0403412Z Component Revision Time: N/A
...
```
After:
```
Components: Velox,VeloxIceberg
Component Velox Branch: HEAD
Component Velox Revision: 88964d4b480a8b5ff6bf85652b17a4b8b5fa6071
Component Velox Revision Time: 2024-11-19 08:07:56 +0800
Component VeloxIceberg Branch: N/A
Component VeloxIceberg Revision: N/A
Component VeloxIceberg Revision Time: N/A
...
```
> [CORE] Following #8192, amend a quick fix for build info message

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxScanSuite.scala
- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BatchScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ScanTransformerFactory.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/PushDownFilterToScan.scala
Scan used to fallback if there was an unsupported filter. This PR filters out the supported expressions and offloads scan as much as possible to improve the performance. Before this change, the plan was "vanilla vectorized scan + c2r + vanilla filter" when scan contained an unsupported filter, and now the plan becomes "native scan + c2r + vanilla filter".
(Fixes: \#7261)
UT
> [GLUTEN-7261][CORE] Support offloading partial filters to native scan

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/AddPreProjectionForHashJoin.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseJoinSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHBucketSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/metrics/GlutenClickHouseTPCHMetricsSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHParquetBucketSuite.scala
- cpp-ch/local-engine/Parser/RelParsers/JoinRelParser.cpp
Fixes: #8168
Add pre-projections for left/right plans to eliminate non-attribute expressions in join keys and condition
unit tests
> [GLUTEN-8168] Add pre-projections for join condition

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetReadSuite.scala
- cpp/velox/compute/VeloxBackend.cc
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
https://github.com/apache/incubator-gluten/pull/8186 followup, change the loadQuantum config if velox cache is enabled only.
manual tests
> [VL] Change the loadQuantum config if velox cache is enabled.

- cpp/core/shuffle/rss/RssPartitionWriter.cc
Fix oom when compress was disabled in spill.
> [VL] Fix sort based shuffle oom in spill when compress was disabled

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/CollectRewriteRule.scala
> [GLUTEN-8229][VL] Don't rewrite collect_list/collect_set in window

- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/config/VeloxConfig.h
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Respect Spark config `UNSAFE_SORTER_SPILL_READER_BUFFER_SIZE`. as  Velox `kSpillReadBufferSize`.
Add the config `spark.gluten.sql.columnar.backend.velox.spillCompressionCodec`, if not set, use Spark config `spark.io.compression.codec` instead.
Respect Spark  `spark.shuffle.spill.diskWriteBufferSize` as Velox `kSpillWriteBufferSize`.
> [GLUTEN-8025][VL] Respect config kSpillReadBufferSize and add spill compression codec

- cpp/velox/memory/VeloxMemoryManager.cc
A quick fix for a crash issue introduced by https://github.com/apache/incubator-gluten/pull/8223.
Error:
```
terminate called after throwing an instance of 'gluten::GlutenException'
what():  Unreachable code
```
> [VL] Fix crash when there are unreleased memory pools during termintating a Velox task

- cpp/core/shuffle/Payload.cc
- cpp/core/utils/Timer.h
Sometimes we need a timer in seconds, e.g., for measuring file write time. Enhance the gluten timer to support seconds, milliseconds, microseconds and nanoseconds.
Exist CI.
> [MINOR] [VL] Enhance the gluten timer to support seconds, milliseconds, and microseconds

- backends-velox/pom.xml
- backends-velox/src-hudi/test/scala/org/apache/execution/VeloxHudiSuite.scala
- backends-velox/src-hudi/test/scala/org/apache/execution/VeloxTPCHHudiSuite.scala
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumer.java
- gluten-core/src/main/scala/org/apache/spark/task/TaskResources.scala
- gluten-hudi/pom.xml
- gluten-hudi/src-hudi/test/scala/org/apache/gluten/execution/HudiSuite.scala
- gluten-ut/common/src/test/scala/org/apache/gluten/utils/BackendTestSettings.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/AbstractFileSourceScanExec.scala
https://github.com/apache/incubator-gluten/issues/7911
Make Maven module backends-velox depend on gluten-hudi than the opposite, to make sure the common source code and UT code (particularly hudiSuite at the moment) to be accessible from other backend modules.
The new folder backends-velox/src-hudi is added for placing code that relate to Velox+hudi support.
TODO in subsequent PRs:
Enable Maven code linters for backends-velox/src-hudi
> [GLUTEN-7911][CORE] Flip dependency direction for gluten-hudi

- gluten-arrow/src/main/java/org/apache/gluten/memory/listener/ReservationListeners.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/OverAcquire.java
Two minor updates:
1. Require overTarget only when sufficient target memory is granted.
2. overTarget doesn't need to really spill because overTarget.usedBytes() is always 0 after OverAcquire.borrow().
Exist CI.
> [CORE] Minor: OverTarget is required only with sufficient memory and doesn't spill due to zero used bytes post-borrow

- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/execution/FileDeltaColumnarWrite.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/execution/datasources/DeltaV1Writes.scala
- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/sql/execution/datasources/DeltaV1WritesSuite.scala
- backends-clickhouse/src/main/resources/org/apache/spark/sql/execution/datasources/v1/write_optimization.proto
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHTransformerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/RuntimeConfig.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarWrite.scala
- backends-clickhouse/src/test/delta-32/org/apache/spark/sql/execution/datasources/DeltaV1WritesSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseDeltaParquetWriteSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxTransformerApi.scala
- cpp-ch/local-engine/Parser/RelParsers/WriteRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/WriteRelParser.h
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeSink.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeSink.h
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeWriter.cpp
- cpp-ch/local-engine/tests/gtest_write_pipeline.cpp
- cpp-ch/local-engine/tests/gtest_write_pipeline_mergetree.cpp
- cpp-ch/local-engine/tests/json/mergetree/4_one_pipeline.json
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/TransformerApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
Since Clickhouse backend doesn't add local sort by itself,  this is differnet with velox backend. This PR and Local `SortExec`  based on `SparkPlan` instead of  `LogicalPlan` for **Delta Write** and remove `RemoveNativeWriteFilesSortAndProject` for datasource v1 write.
1. I  also fix an issue caused by `WriteRel` doesn't including partition column order issue by adding such information in [write_optimization.proto](https://github.com/apache/incubator-gluten/pull/8237/files#diff-c4d35f61ef1f60be2b950d7960c3f0fd1211366efc670f831d7ebd8bfed99538)
2. Since we already sort blocks, hence we can remove`ApplySquashingTransform` and `PlanSquashingTransform` from pipeline and adding `Squashing`  in `SparkMergeTreeSink`.
(Please explain how this patch was tested. E.g. unit tests, integration tests, …
> [GLUTEN-7028][CH][Part-12] Add Local SortExec for Partition Write in one pipeline mode

- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargetVisitor.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargets.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/RetryOnOomMemoryTarget.java
- gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
Retry memory borrow when granted less than requested size in multi-slot and Gluten shared mode. If ThrowOnOomMemoryTarget cannot acquire memory, spill more memory and then retry.
(Fixes: \#8128)
If the case in issue #8128 occurs, the first borrow(sizeA) will spill sizeA memory. After spill, if curMemory is greater than the maxPerTaskSize, we'll get 0 returned. So we retry spill(long.max), then re-borrow.
- Add argument `isDynamicCapacity` when construct `TreeMemoryTargets#Node`, which means multi-task-slot and shared mode.
Test with my production ETL.
> [GLUTEN-8128][VL] Retry borrowing when granted size is less than requested in multi-slot and shared mode

- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
Velox cast timestamp to string has incorrect result, but cast timestamp to date seems to be correct.
(Fixes: \#8215)
new UT and existing GlutenCastSuite
> [GLUTEN-8215][VL] Support cast timestamp to date

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ApplyResourceProfileExec.scala
This PR aims to add interface to GlutenPlan so that we can have the chance to set resource profile,
detailed design can be found https://github.com/apache/incubator-gluten/issues/8018.
To be added in the following commit.
> [GLUTEN-8018][CORE] Introduce ApplyResourceProfileExec to apply resource profile for query stage

- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
#8212 introduced `testGluten("function to_date") ` which is failed in spark32, let's ignore it
```
[2024-12-17T09:40:35.895Z] - Gluten - function to_date *** FAILED ***
[2024-12-17T09:40:35.895Z]   org.apache.spark.sql.catalyst.analysis.UnresolvedException: Invalid call to dataType on unresolved object
[2024-12-17T09:40:35.895Z]   at org.apache.spark.sql.catalyst.analysis.UnresolvedAttribute.dataType(unresolved.scala:160)
[2024-12-17T09:40:35.895Z]   at org.apache.gluten.extension.RewriteToDateExpresstionRule.rewriteParseToDate(RewriteToDateExpresstionRule.scala:98)
[2024-12-17T09:40:35.895Z]   at org.apache.gluten.extension.RewriteToDateExpresstionRule.visitExpression(RewriteToDateExpresstionRule.scala:66)
[2024-12-17T09:40:35.895Z]   at …
```
> [CH] Hotfix to #8212

- cpp/velox/CMakeLists.txt
This pr simply removes the setting for CMAKE_FIND_LIBRARY_SUFFIXES before finding lib GCS.
> [VL] Allow shared dependencies for lib GCS

- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargets.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/RetryOnOomMemoryTarget.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/TreeMemoryTargets.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumers.java
- gluten-core/src/main/scala/org/apache/spark/task/TaskResources.scala
- gluten-core/src/test/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumerTest.java
Includes:
1. Code cleanups for TreeMemoryConsumer
- Rephrase memory `shared mode` to `legacy mode` as `shared` is in a way misleading (what are shared, shared what, etc.). `legacy` means the behavior will be aligned with vanilla Spark. The new word is less confusing.
- Untangle the weak caching code of memory consumer and the factories.
2. Minor follow-ups for https://github.com/apache/incubator-gluten/pull/8132
> [CORE] Minor code cleanups for TreeMemoryConsumer

- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargetVisitor.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargets.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/TreeMemoryTargets.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumer.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumers.java
- gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
- gluten-core/src/test/java/org/apache/gluten/memory/memtarget/spark/TreeMemoryConsumerTest.java
Another follow-up for https://github.com/apache/incubator-gluten/pull/8254 and https://github.com/apache/incubator-gluten/pull/8132.
There is a issue introduced in #8254 unexpectedly, that `RetryOnOomMemoryTarget` only spills one single memory consumer when retrying happens. It should spill all the consumers in the same task instead. The patch fixes the issue with some other refactors in passing.
> [VL] Fix `RetryOnOomMemoryTarget` only spills one single consumer on retrying

- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/OverAcquire.java
After https://github.com/apache/incubator-gluten/pull/8132, overTarget.borrow(overSize) may trigger a retrying spill. If so, it calls OverAcquire.repay() during the spill procedure, which checks Preconditions.checkState(overTarget.usedBytes() == 0);. However, currently, 0 < overTarget.usedBytes() < overSize. We can remove this precondition in repay(), and only keep the precondition in borrow().
(Fixes: \#8268)
> [GLUTEN-8268][CORE] Remove preconditions in OverAcquire.repay

- .idea/vcs.xml
Make IDEA support IssueNavigationLink.
(Fixes: \#8257)
Manual test.
Before:
After:
> [GLUTEN-8257][CORE] Make IDEA support IssueNavigationLink

- backends-clickhouse/src-iceberg/main/resources/META-INF/services/org.apache.gluten.component.Component
- backends-clickhouse/src/main/resources/META-INF/services/org.apache.gluten.backend.Backend
- backends-velox/src-iceberg/main/resources/META-INF/services/org.apache.gluten.component.Component
- backends-velox/src/main/resources/META-INF/services/org.apache.gluten.backend.Backend
- gluten-core/src/main/java/org/apache/gluten/utils/ResourceUtil.java
- gluten-core/src/main/scala/org/apache/gluten/component/Discovery.scala
- gluten-core/src/main/scala/org/apache/gluten/component/package.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendsApiManager.scala
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/BaseMixin.java
A component file is a blank file with the target component class name as its file name under classpath container `META-INF/gluten-components`.
Details can be found in [code comment](https://github.com/apache/incubator-gluten/compare/main...zhztheplayer:wip-comp-file?expand=1#diff-06032b572a7c7aa8c391a42d0f47d86f5fabd9c781f97b1ecee156c6d21ef1deR34-R53).
The previous way of using service file to detect backend / component implementations is dropped since it may cause the files overwrites each other accidentally during maven goal `add-resources`.
> [CORE] Use component file to discover components

- .github/workflows/velox_backend.yml
> [GLUTEN-8266][VL] Use pre-installed resources for Spark/Celeborn

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
> [GLUTEN-8253][CH] Fix cast failed when in-filter with tuple values

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
Fix the scan fallback with viewfs system.
Fixes: #8050
Local test
> [GLUTEN-8050][VL] Add viewfs support in scan validation

- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/enumerated/planner/VeloxRasSuite.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/benchmark/VeloxRasBenchmark.scala
- gluten-ras/common/src/main/scala/org/apache/gluten/ras/rule/RuleApplier.scala
As title. Add `VeloxRasBenchmark` to measure on performance of query optimization with RAS planner.
The benchmark is based on TPC-H data and queires.
Current benchmark output:
```
OpenJDK 64-Bit Server VM 1.8.0_382-b05 on Linux 5.4.0-200-generic
Intel(R) Xeon(R) Platinum 8280 CPU @ 2.70GHz
org.apache.spark.sql.execution.benchmark.VeloxRasBenchmark$:  Best Time(ms)   Avg Time(ms)   Stdev(ms)    Rate(M/s)   Per Row(ns)   Relative
-------------------------------------------------------------------------------------------------------------------------------------------
RAS Planner                                                           3765           4484         546          0.0   171143418.3       1.0X
Legacy Planner                                                        5383 …
```
> [VL] RAS: A benchmark suite for performance of query optimization

- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/orc/OrcFileFormat.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/orc/OrcFileFormat.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
Fix the code style issue of 'prepareWrite' in Spark 3.2 and 3.3 shims.
CI
> [Shims] Fix the code style issue of prepareWrite

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-substrait/src/main/scala/org/apache/hadoop/fs/viewfs/ViewFileSystemUtils.scala
1. Avoid RPC calls.
2. Add a cache.
(Fixes: \#8330)
Manual tests, before: 225007 ms, after: 1330 ms:
```scala
import org.apache.hadoop.fs.viewfs.ViewFileSystemUtils
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.fs.{FileSystem, Path}
val fs = FileSystem.get(spark.sparkContext.hadoopConfiguration)
val paths = fs.listStatus(new Path("viewfs://my-cluster/path/to/table")).take(50000).map(_.getPath.toString)
val start1 = System.currentTimeMillis
paths.map(p => FileSystem.get(new Path(p).toUri, spark.sparkContext.hadoopConfiguration).resolvePath(new Path(p)))
println(s"Convert viewfs to HDFS using resolvePath took: ${System.currentTimeMillis - start1} ms")
val start2 = System.currentTimeMillis
paths.map(p => ViewFileSystemUtils.convertViewfsToHdfs(p, …
```
> [GLUTEN-8330][VL] Improve convert the viewfs path to hdfs path

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseStringFunctionsSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/regexp_extract.cpp
Fixes: #8325
align the meaning of `.` and `$` in vanila and ch
unit tests
> [GLUTEN-8325][CH] Fix miss matched result for `$` and `.` in reg expression

- dev/builddeps-veloxbe.sh
- dev/ci-velox-buildshared-centos-8.sh
- docs/get-started/Velox.md
- docs/get-started/build-guide.md
- ep/build-velox/src/build_velox.sh
- tools/gluten-te/centos/dockerfile-build
- tools/gluten-te/ubuntu/dockerfile-build
- tools/gluten-te/ubuntu/examples/buildhere-veloxbe-dev/scripts/all.sh
Remove `--enable_ep_cache` to simplify the build script. After the removal, `ccache` based build acceleration will be preferred.
Reason:
Overtime `--enable_ep_cache` brings more maintenance burden than its benefits. It was designed as a "smart" flag to let the build system decide whether to rebuild Velox code again, however ended up with a partial solution, which doesn't take all the build variables as the cache key. It's possible that we enhance the cache key generation code to make it consider all the variables however it will make the build script more complicated.
The patch removes `--enable_ep_cache` for the reason. `ccache` based build acceleration will be preferred. In future we could add a manual flag or a command line prompt to skip Velox build if similar functionality is still …
> [VL] Remove compile option `--enable_ep_cache`

- gluten-iceberg/src-iceberg/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
- gluten-iceberg/src-iceberg/test/scala/org/apache/gluten/execution/IcebergSuite.scala
When the p2 partition of Iceberg  v1 table  is deleted, the column is not physically removed in the code but marked as a VoidTransform. As a result, the file path changes to xxx/p2=null/xxx. During data reading, when encountering a VoidTransform, the data should be retrieved directly from the file instead of relying on the partition value. However, in this scenario, Gluten reads the p2 values as null for all records
(Fixes: \#8352)
> [GLUTEN-8352][ICEBERG] Fix read error when partition column was drop

- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHBroadcastBuildSideCache.scala
- backends-clickhouse/src/test/resources/log4j2.properties
Configure Log4j2 to print logs of `org.apache.iceberg` for tracing `ClickHouseIcebergSuite` aborted issues. I also remove threadLog in `CHBroadcastBuildSideCache`, since **Log4j2** supports printing thread name and id.
Current UTs
> [CH] [MINOR] Configure Log4j2 to print logs of `org.apache.iceberg` for tracing `ClickHouseIcebergSuite` aborted issues

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/ShuffleManagerLookup.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/ShuffleManagerRegistry.scala
- gluten-core/src/main/scala/org/apache/spark/shuffle/ShuffleManagerRouter.scala
- gluten-core/src/test/scala/org/apache/spark/shuffle/GlutenShuffleManagerSuite.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Note: `GlutenShuffleManager` is still experimental. The change shouldn't impact production behavior.
1. Register `SortShuffleManager` through  `GlutenShuffleManager` by default
2. (Velox backend) Register `ColumnarShuffleManager` through  `GlutenShuffleManager` by default
3. Make `GlutenShuffleManager` work correctly in cluster mode
4. Add some simple test code
This will remove some blockers against the mixed backend work.
> [GLUTEN-8060][CORE][VL] Various of fixes for the experimental `GlutenShuffleManager`

- ep/build-velox/src/get_velox.sh
Prevent multiple '#' additions
After multiple executions of setup
before
`###  dnf config-manager --set-enabled powertools`
after
`#  dnf config-manager --set-enabled powertools`
> [MINOR] Avoid duplicate comment symbol in setup scripts

- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/delta/ClickhouseOptimisticTransaction.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/execution/FileDeltaColumnarWrite.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/execution/MergeTreeDeltaColumnarWrite.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/CHColumnarWrite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeCacheDataSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreePathBasedWriteSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnHDFSWithRocksDBMetaSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionDecimalBinaryArithmetic.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeMeta.cpp
- cpp-ch/local-engine/Storages/MergeTree/StorageMergeTreeFactory.cpp
- cpp-ch/local-engine/Storages/MergeTree/StorageMergeTreeFactory.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.h
This PR fixed 3 UTs
1. **`GlutenClickHouseMergeTreeCacheDataSuite::test cache mergetree data no partition columns`**, it's fixed by #8346, just reopen test
2. **`GlutenClickHouseMergeTreePathBasedWriteSuite::test mergetree path based table update`** and **`GlutenClickHouseMergeTreePathBasedWriteSuite::test mergetree path based table delete`**, since one pipeline write will collect stats, so that pruning will be more accurate in point query, adding  `withSQLConf(("spark.databricks.delta.stats.skipping", "false"))` to make test suucess.
3.  **`test mergetree with partition with whitespace`**,  whitespace will be saved as `%20` in Delta commit protocol, so that we need follow this, and hence decode it to normal string in backend.
4. other ignored cases are bucket table case, let's ignore it. …
> [GLUTEN-7028][CH][Part-15] [MINOR] Fix UTs

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/BroadcastUtils.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeBytesBufferArray.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelation.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- cpp/core/jni/JniWrapper.cc
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ColumnarBatchSerializerJniWrapper.java
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/joins/BuildSideRelation.scala
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Implement feature: #7750 
Add unit test and manual run tpcds in my dev box.
> [GLUTEN-7750][VL] Move ColumnarBuildSideRelation's memory occupation to Spark off-heap

- cpp/velox/CMakeLists.txt
This pr removes the setting for CMAKE_FIND_LIBRARY_SUFFIXES 
before finding libs for s3 and abfs.
This is similar to https://github.com/apache/incubator-gluten/pull/8251
Without this change, users are forced to link statically with libcrypto, which is not feasible
with fips. https://github.com/apache/incubator-gluten/issues/8232
> [VL] Allow shared dependencies for s3 and abfs libs

- .github/workflows/velox_backend.yml
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxMetricsSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxOrcDataTypeValidationSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxParquetDataTypeValidationSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- ep/build-velox/src/get_velox.sh
- gluten-substrait/src/main/scala/org/apache/gluten/execution/SortMergeJoinExecTransformer.scala
1. Enable full outer join in smj.
2. Fix the inner join result mismatch caused by gluten's incorrect formulation of the join condition. Specifically, gluten incorrectly reorders the condition, such as changing "A = B and C = D" to "C = D and A = B", which leads to a mismatched final join result.
3. Fix the TPC-DS and TPC-H result mismatch issue in anti, semi and full outer join in https://github.com/facebookincubator/velox/pull/11772 and https://github.com/facebookincubator/velox/pull/11771
4. Set the ci job to cover the smj unit test.
Existing unit tests and locally run TPC-H and TPC-DS.
> [GLUTEN-8393][VL] Fix the smj result mismatch issue 

- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoader.scala
As Oracle systems are widely used in many companies, it is better to support compiling Gluten on this systems.
And Oracle systems are almost similar to Centos systems. I put them into one kind of OS system.
The UTs have been ran on a Oracle 7/8 system.
> [VL] Support loading dependency libs for Oracle linux

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/utils/ConfigExtractor.cc
- shims/common/src/main/scala/org/apache/gluten/GlutenConfig.scala
Velox added new authentication mechanisms for ABFS: https://github.com/facebookincubator/velox/pull/11623
We need to plumb these configs.
ABFS is not enabled in CI. Tested locally on a branch https://github.com/majetideepak/incubator-gluten/commit/2ed478617fe37c436216ef43b898b3ae16f6ce6d
> [VL] Plumb ABFS config

- .github/workflows/velox_backend.yml
- dev/docker/Dockerfile.centos8-dynamic-build
- gluten-celeborn/src-celeborn/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
- tools/gluten-it/pom.xml
1. Bump Celeborn from 0.4.2 to 0.4.3.
2. Bump `CelebornShuffleManager` to Celeborn v0.5.2 including backport https://github.com/apache/celeborn/pull/2639 and https://github.com/apache/celeborn/pull/2832. Follow up #8054.
Fixes: \#8398
GA.
> [GLUTEN-8398] Bump Celeborn 0.4.3 and 0.5.2

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenTryCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenTryCastSuite.scala
To align with Spark, we need consider session timezone in this cast operation. See https://github.com/facebookincubator/velox/pull/11958
Existing imported Spark tests.
> [VL] Support casting timestamp type to varchar type

- cpp-ch/local-engine/CMakeLists.txt
- cpp-ch/local-engine/Common/GlutenSignalHandler.cpp
- cpp-ch/local-engine/Parser/CHColumnToSparkRow.cpp
- cpp-ch/local-engine/Storages/MergeTree/MetaDataHelper.cpp
- cpp-ch/local-engine/Storages/Output/WriteBufferBuilder.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/CMakeLists.txt
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
- cpp-ch/local-engine/local_engine_jni.cpp
Fixes: #8397 
Disable hdfs while compiling clickhouse backend on macOS.
There will be no change for origin tests.
> [GLUTEN-8397][CH][Part-1]: Disable hdfs while compiling clickhouse backend on macOS

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/CollapseGetJsonObjectExpressionRule.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
> [GLUTEN-8304][CORE] Add an optimization rule to collapse nested get_json_object functions

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
https://github.com/facebookincubator/velox/pull/11530 add Int64 Timestamp in parquet reader, remove config VELOX_SCAN_FILE_SCHEME_VALIDATION_ENABLED and enable related ut.
(Fixes: \#8307)
> [GLUTEN-8307][VL] Support Int64 Timestamp in parquet reader

- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/BaseMixin.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/Preset.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Parameterized.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Queries.java
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Constants.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/QueryRunner.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/ShimUtils.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Suite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Parameterized.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Queries.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/TableRender.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/package.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/clickbench/ClickBenchSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/ds/TpcdsSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/h/TpchSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/metrics/MetricMapper.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/metrics/MetricTag.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/metrics/PlanMetric.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/VersionUtils.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/deploy/history/GlutenItHistoryServerPlugin.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkQueryRunner.scala
- tools/gluten-it/common/src/test/java/org/apache/gluten/integration/action/TableRenderTest.scala
New option `--collect-sql-metrics=execution-time` to make user be able to find out the top 10 query plan nodes that took longest time to execute in the benchmark report.
The option is only available with subcommand `gluten-it queries` at the moment.
For example, run:
```
<gluten-it> queries --local --data-gen=once --enable-history --collect-sql-metrics=execution-time
```
The test report will include:
```
Top 10 plan nodes that took longest time to execute: 
|  Query  | Node ID |         Node Name         |     Execution Time (ns)     |
|---------|---------|---------------------------|-----------------------------|
|   q1.sql|      573|     ProjectExecTransformer|  [time of project] 776031999|
|   q2.sql|     1299|  ColumnarBroadcastExchange|  [time to collect] 769000000|
|   q2.sql| …
```
> [VL] Gluten-it: New option `--collect-sql-metrics=execution-time` to collect slowest plan nodes into benchmark report

- cpp/velox/compute/VeloxBackend.cc
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Parameterized.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Queries.java
This is a follow-up minor fix for https://github.com/apache/incubator-gluten/pull/7845.
Enabling Velox background IO thread now no longer causes hanging or dead lock issues. Remove the related warning message which could be misleading for users.
Also, simplify gluten-it option `--collect-sql-metrics` which is introduced in https://github.com/apache/incubator-gluten/pull/8445 to `--sql-metrics`.
> [VL] Remove an out-of-date warning message

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
- backends-velox/src/test/java/org/apache/gluten/test/MockVeloxBackend.java
- backends-velox/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnarTableCacheBenchmark.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/HashAggregateExecBaseTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/RemoveNativeWriteFilesSortAndProject.scala
- gluten-substrait/src/test/scala/org/apache/spark/softaffinity/SoftAffinityWithRDDInfoSuite.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenSparkSessionExtensionSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenSparkSessionExtensionSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenSparkSessionExtensionSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenSparkSessionExtensionSuite.scala
- shims/common/src/main/scala/org/apache/gluten/config/ConfigBuilder.scala
- shims/common/src/main/scala/org/apache/gluten/config/ConfigEntry.scala
- shims/common/src/main/scala/org/apache/gluten/config/ConfigProvider.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- shims/common/src/main/scala/org/apache/spark/sql/internal/ConfigProvider.scala
- shims/common/src/main/scala/org/apache/spark/sql/internal/GlutenConfigUtil.scala
This PR is the part-3 of the revert [commit](https://github.com/apache/incubator-gluten/commit/70475328efb306b431252fc9eabf4e6c264b9fcb) back and is used to introduce the `ConfigEntry` to gluten config.
GA.
> [GLUTEN-8327][CORE][Part-3] Introduce the `ConfigEntry` to gluten config

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
This is a minor fix for warning "Memory overhead is set to ..." that is sometimes unexpectedly appearing, which is because of the incorrect precision of the overhead vs desired overhead comparison.
> [VL] Fix wrong warning of "Memory overhead is set to ..." under default Spark config settings

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/BucketWriteUtils.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- docs/developers/SubstraitModifications.md
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/RelBuilder.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/WriteRelNode.java
- gluten-substrait/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WriteFilesExecTransformer.scala
This PR amins to support write compatible-hive bucket table for Spark3.4 and Spark3.5. fix https://github.com/apache/incubator-gluten/issues/8385
unit tests.
> [GLUTEN-8385][VL] Support write compatible-hive bucket table for Spark3.4 and Spark3.5.

- .github/workflows/clickhouse_be_trigger.yml
Reverts apache/incubator-gluten#8337
ARM CI is enabled now
> Revert "[CH] Disable gluten arm ci"

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
- gluten-arrow/src/main/java/org/apache/gluten/columnarbatch/ColumnarBatches.java
- Currently the ColumnarCachedBatchSerializer does not support Arrow Heavy Batch.
- ColumnarCachedBatchSerializer expects light batch to offload to native. (In most cases it receives an already offloaded, however fails when the input is a heavy batch).
- Added conversion to offload it if the upstream operator produced an ArrowJavaBatch.
- Also makes the check light/heavy batch public, since they can be good utility functions and don't have critical logic inside.
- Note: This is a fix which will make it work, but ideally it should work with RAS and be compatible with the transitions added, to do this we can wrap the InMemoryTableScanExec and register as a Gluten operator to elegantly offload. I'll investigate as part 2
> [GLUTEN-8453] [VL] Allow Heavy Batch to be Processed by ColumnarCachedBatchSerializer

- cpp-ch/local-engine/Common/ArrayJoinHelper.cpp
- cpp-ch/local-engine/Common/DebugUtils.cpp
- cpp-ch/local-engine/Common/DebugUtils.h
- cpp-ch/local-engine/Parser/AggregateFunctionParser.cpp
> [CH] Add tools to dump ActionsDAG into tree graph

- gluten-core/src/main/scala/org/apache/gluten/component/package.scala
When no component files (with name `META-INF/gluten-components/<classname>`) found from classpath, raise an error instead of running into UB.
> [GLUTEN-8462][CORE] Raise a meaningful error when no component is found from classpath

- .github/workflows/velox_backend.yml
- dev/docker/Dockerfile.centos8-dynamic-build
- pom.xml
- tools/gluten-it/pom.xml
Bump Celeborn version from 0.5.2 to 0.5.3.
Fixes: \#8465
GA.
> [GLUTEN-8465] [VL] Bump Celeborn to 0.5.3

- gluten-core/src/main/java/org/apache/gluten/utils/ResourceUtil.java
#8271 Introduced Issue: Gluten failed to load the required Components and Backend during initialization, resulting in abnormal execution.
(Fixes: #8462 )
TEST ARM and x86
> [GLUTEN-8462][CH] Fixed the loading of Components and Backend

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionCheckDecimalOverflow.cpp
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
> [GLUTEN-8343][CH]Fix cast number to decimal

- gluten-core/src/main/java/org/apache/gluten/utils/ResourceUtil.java
- gluten-core/src/main/scala/org/apache/gluten/component/Discovery.scala
- gluten-core/src/test/java/org/apache/gluten/util/ResourceUtilTest.java
#8483 
Use `ClassLoader.getResources` for the discovery of the component files instead of reading system property `java.class.path`. The new way will be suitable for more scenarios including cases that class loader is customized or Gluten Jar file is not loaded with regular `-cp` JVM argument.
> [GLUTEN-8483][CORE] A stable and universal way to find component files

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Storages/MergeTree/SparkStorageMergeTree.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250110)

- cpp/core/benchmarks/CompressionBenchmark.cc
- cpp/core/memory/MemoryAllocator.cc
Allocate and free memory in the same module
(Fixes: \#8476)
> [GLUTEN-8476][VL] Fix allocate and free memory

- cpp/core/benchmarks/CompressionBenchmark.cc
Macro replacement lists should be parenthesized@cpp/core/benchmarks/[CompressionBenchmark.cc:61](http://compressionbenchmark.cc:61/)
(Fixes: \#8503)
> [GLUTEN-8503][VL] Fix macro parenthesis CVE

- cpp/velox/memory/VeloxMemoryManager.cc
Use of Uninitialized Variables
false positives(mainly since the file was most likely deleted and only contains 1480 lines now. Went over that file and tried to find any other Uninitialized Variables and change them accordingly. There is 9 FP below and also 9 changes in that file after taking a look at what could have been the line numbers):
cpp/velox/substrait/[SubstraitToVeloxPlan.cc:1902](http://substraittoveloxplan.cc:1902/)
cpp/velox/substrait/SubstraitToVeloxPlan.cc:1762
cpp/velox/substrait/SubstraitToVeloxPlan.cc:1680
cpp/velox/substrait/SubstraitToVeloxPlan.cc:1653
cpp/velox/substrait/SubstraitToVeloxPlan.cc:1927
pp/velox/substrait/SubstraitToVeloxPlan.cc:2539
cpp/velox/substrait/SubstraitToVeloxPlan.cc:1960
cpp/velox/substrait/SubstraitToVeloxPlan.cc:1932 …
> [GLUTEN-8471][VL] Fix usage of uninitialized variables

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxColumnarCacheSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/TransitionGraph.scala
https://github.com/apache/incubator-gluten/issues/8497
Add a bad case which is ignored at the moment to reproduce the bug described in https://github.com/apache/incubator-gluten/issues/8497.
I am still looking for a proper solution of the bug. Could merge the test code in advance so one could try with it if interested.
> [GLUTEN-8497][VL] A bad test case that fails columnar table cache query

- cpp/core/utils/qat/QatCodec.cc
Use parentheses within macros around parameter names
False Positive:
cpp/velox/substrait/[SubstraitToVeloxPlanValidator.cc:37](http://substraittoveloxplanvalidator.cc:37/)
cpp/velox/substrait/[SubstraitToVeloxPlanValidator.cc:48](http://substraittoveloxplanvalidator.cc:48/)
(Fixes: \#8532)
> [GLUTEN-8532][VL] Fix parenthesis within macro

- .github/workflows/docker_image.yml
- dev/docker/Dockerfile.centos8-dynamic-build-jdk17
This patch added JDK17 based Centos 8 image
> [GLUTEN-8487][VL] adding JDK17 based Centos8 image (#8513)

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/CHUtil.cpp
- cpp-ch/local-engine/Storages/MergeTree/MergeSparkMergeTreeTask.cpp
> [GLUTEN-1632][CH]Daily Update Clickhouse Version (20250115)

- cpp/core/shuffle/FallbackRangePartitioner.cc
- cpp/core/shuffle/HashPartitioner.cc
- cpp/core/shuffle/RandomPartitioner.cc
- cpp/core/shuffle/RoundRobinPartitioner.cc
- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
Use bitwise operators only on unsigned operands
False positives
cpp/velox/tests/[MemoryManagerTest.cc:43](http://memorymanagertest.cc:43/)
cpp/velox/benchmarks/[ColumnarToRowBenchmark.cc:215](http://columnartorowbenchmark.cc:215/)
cpp/core/shuffle/[RoundRobinPartitioner.cc:39](http://roundrobinpartitioner.cc:39/)
cpp/velox/compute/[WholeStageResultIterator.cc:255](http://wholestageresultiterator.cc:255/)
cpp/core/shuffle/[HashPartitioner.cc:55](http://hashpartitioner.cc:55/)
cpp/velox/tests/[VeloxColumnarToRowTest.cc:37](http://veloxcolumnartorowtest.cc:37/)
cpp/core/shuffle/[FallbackRangePartitioner.cc:44](http://fallbackrangepartitioner.cc:44/)
cpp/velox/benchmarks/[ColumnarToRowBenchmark.cc:160](http://columnartorowbenchmark.cc:160/) …
> [GLUTEN-8520][VL] Fix bitwise operators

- docs/get-started/Velox.md
- docs/get-started/build-guide.md
Doc is not updated when we bump to 3.5.2 by PR:
https://github.com/apache/incubator-gluten/pull/7138
> [GLUTEN-6876][VL] update spark 3.5.2 in doc

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/enumerated/planner/VeloxRasSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/component/Component.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/cost/GlutenCost.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/cost/GlutenCostModel.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/cost/LongCost.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/cost/LongCostModel.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/cost/LongCoster.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/cost/LongCosterChain.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/EnumeratedTransform.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/property/Conv.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/FloydWarshallGraph.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transition.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/TransitionGraph.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/injector/GlutenInjector.scala
- gluten-core/src/test/scala/org/apache/gluten/component/ComponentSuite.scala
- gluten-core/src/test/scala/org/apache/gluten/extension/columnar/transition/FloydWarshallGraphSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/cost/LegacyCoster.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/cost/RoughCoster.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuite.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Add new independent trait `GlutenCostModel` so legacy transition planner's cost model code doesn't have to depend on RAS cost model code.
After the change, both legacy transition planner and RAS optimizer will rely on `GlutenCostModel` through their own API adapters.
Also, make costers be registered directly through a individual API of `Component`. This will enable the code to create cost model from anywhere without having a Spark session started in advance.
> [CORE][VL] Cost model code refactors

- backends-velox/src/main/scala/org/apache/gluten/execution/HashAggregateExecTransformer.scala
> [MINOR] Fix comment of function VeloxAggregateFunctionsBuilder.create

- cpp/core/benchmarks/CompressionBenchmark.cc
- cpp/core/memory/MemoryAllocator.cc
- cpp/core/shuffle/Spill.cc
- cpp/core/utils/qat/QatCodec.cc
- cpp/core/utils/qpl/QplCodec.cc
- cpp/velox/jni/JniFileSystem.cc
- cpp/velox/operators/serializer/VeloxColumnarToRowConverter.cc
- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
- cpp/velox/shuffle/VeloxShuffleReader.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/substrait/SubstraitParser.cc
- cpp/velox/tests/FunctionTest.cc
- cpp/velox/tests/VeloxSubstraitRoundTripTest.cc
False positives for Do not Cast
cpp/velox/compute/[WholeStageResultIterator.cc:461](http://wholestageresultiterator.cc:461/)
cpp/velox/compute/WholeStageResultIterator.cc:463](http://wholestageresultiterator.cc:463/)
cpp/velox/shuffle/[VeloxSortShuffleWriter.cc:219](http://veloxsortshufflewriter.cc:219/)
cpp/velox/tests/[FunctionTest.cc:157](http://functiontest.cc:157/)
cpp/velox/shuffle/[VeloxShuffleReader.cc:437](http://veloxshufflereader.cc:437/)
cpp/velox/shuffle/[VeloxSortShuffleWriter.cc:347](http://veloxsortshufflewriter.cc:347/)
cpp/velox/substrait/[SubstraitToVeloxPlan.cc:1049](http://substraittoveloxplan.cc:1049/)
cpp/velox/substrait/[SubstraitToVeloxPlan.cc:1](http://substraittoveloxplan.cc:1102/)040
cpp/velox/substrait/[SubstraitToVeloxPlan.cc:1102](http://substraittoveloxplan. …
> [GLUTEN-8475][VL] Fix C-style casts to C++-style

- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
Allowing loops to iterate beyond the end of an array
Since we know bytesValue2 is size 16 the length needs to also be 16 or less so we do not iterate before(beyond) the size of that bytesValue2 array
(Fixes: \#8534)
> [GLUTEN-8534][VL] Fix allowing loops to iterate beyond end of array

- cpp/core/memory/MemoryAllocator.cc
Fix incorrect calculation of buffer size
False positives:
cpp/velox/udf/UdfLoader.cc:79
cpp/velox/udf/UdfLoader.cc:106
(Fixes: \#8538)
> [GLUTEN-8538][VL] Fix incorrect calculation of buffer size

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/BasicExpressionRewriteRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
> [GLUTEN-8406][CH] Replace `from_json(s, 'Map<String, String>')[k]` with `get_json_object(s, '$.k')`

- cpp/velox/CMakeLists.txt
`VELOX_COMPONENTS_PATH` should be removed and the usages should be replaced by `$VELOX_BUILD_PATH/velox` already. This line (for `facebook::velox::exec_test_lib`) was likely missing from a former cleanup. The path does a follow-up on this line.
> [VL] CMake configuration cleanup to remove variable VELOX_COMPONENTS_PATH

- cpp/velox/benchmarks/GenericBenchmark.cc
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/config/VeloxConfig.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlan.h
- docs/developers/QueryTrace.md
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Run the MicroBenchmark to generate stage level plan and then enable query trace in benchmark to profile node level query. Benchmark with query trace enabled replaces ValueStreamNode which is hard to serialize to ValuesNode. This issue may be fixed by plan serialization optimization that only serializes the plan node to  profile in velox query trace. https://github.com/facebookincubator/velox/issues/12084
> [GLUTEN-8379][VL] Support query trace

- gluten-core/src/main/scala/org/apache/gluten/component/Component.scala
The Scaladoc of Component API is out of date. The PR updates it.
> [VL] Update the Scaladoc of Component API

- backends-velox/src/test/scala/org/apache/gluten/utils/ParquetEncryptionDetectionSuite.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
- Adds support for encrypted parquet fallback for Spark 3.5.
- Previous Spark versions use an older parquet dependency which does not provide direct metadata to check encryption.
- Using `EncryptionType` provided by Parquet 1.13 for Spark 3.5.
> [GLUTEN-8455][VL] Support encrypted parquet fallback for 3.5

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/AddFallbackTags.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/PushDownInputFileExpression.scala
> [GLUTEN-8580][CORE][Part-2] Don't validate project generated by PushDownInputFileExpression

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarRangeExec.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/RangeExecBaseTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/offload/OffloadSingleNodeRules.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenSQLRangeExecSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- Currently the range operator fallsback leads to R2C overhead for downstream operators in velox.
- Added support for RangeExec which produces range in columnar batches.
- In the future the range generation can itself be offloaded to velox backend. 
- Plan reflects the new operator
- Added unit tests
> [GLUTEN-3620][VL] Support Range operator for Velox Backend

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/AutoAdjustStageResourceProfileSuite.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenAutoAdjustStageResourceProfile.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
It's a follow PR of https://github.com/apache/incubator-gluten/pull/8195 and demonstrate how to adjust resource profile through Rule. 
Unit test will be updated soon.
> [GLUTEN-8018][VL] Support adjusting stage resource profile dynamically

- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- cpp/velox/substrait/VeloxSubstraitSignature.cc
Support null type in HashAggregate
(Fixes: \#8410)
Added test
> [GLUTEN-8410][VL] Support null type in HashAggregate

- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenDateFunctionsSuite.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
The https://github.com/apache/incubator-gluten/pull/7375 has  enabled Velox simple date time formatter if the `spark.sql.legacy.timeParserPolicy` is set to `LEGACY`. But, it doesn't work when the `spark.sql.legacy.timeParserPolicy `is set to `legacy`.
(Fixes: https://github.com/apache/incubator-gluten/issues/8581)
Add unittests.
> [GLUTEN-8581][VL] Fix Spark legacy date formatter under case insensitive configuration

- docs/developers/clickhouse-backend-debug.md
When running the maven command in `Maven Build Gluten ClickHouse with Profile`, an exception occurred, as shown in the following figure.
Therefore, it is necessary to update the commands in the document.
- Just docs, not need add UT
- The execution result after changing the command.
> [CH][DOC] Fix Maven Build Gluten ClickHouse Command

- dev/builddeps-veloxbe.sh
After #8627 , I met the `dev/builddeps-veloxbe.sh: line 218: INSTALL_PREFIX: unbound variable`.
manual test on macos
> [VL][MIRROR] Fix build faile don Macos with INSTALL_PREFIX not set

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/ParquetMetadataUtils.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- Making parquet file scan limit as configurable.
- Currently it's hardcoded to default 10, now available as a user config can be changed externally.
- Default remains the same as before of 10.
- Existing UTs
> [GLUTEN-8616] [VL] Make filescan limit for encrypted fallback as configurable

- package/pom.xml
- pom.xml
After this fix, the jar name on macOS will be like:
gluten-velox-bundle-spark3.5_2.12-darwin_aarch64-1.4.0-SNAPSHOT.jar
gluten-velox-bundle-spark3.5_2.12-darwin_x86_64-1.4.0-SNAPSHOT.jar
Fixes: #8678
> [GLUTEN-8678] Fix jar name on macos

- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetWriterInjects.scala
- cpp/velox/operators/writer/VeloxParquetDataSource.cc
- ep/build-velox/src/get_velox.sh
Passes timestamp timezone to writeOption.
UT verified.
> [VL] Fix timezone for Parquet timestamp write 

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CoalesceAggregationUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenCoalesceAggregationUnionSuite.scala
> [GLUTEN-8675][CH] Rewrite union of multiple aggregates into one 

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/RuntimeSettings.scala
- cpp-ch/local-engine/Common/QueryContext.cpp
- cpp-ch/local-engine/Operator/GraceAggregatingTransform.cpp
- cpp-ch/local-engine/Operator/GraceAggregatingTransform.h
Fixes: #8705
It's a common case that there are multiple join steps in a subplan.  A previous solution, each join operator spills when its memory usage is over limit,unable to sense the exisitence of other operators. It's easy to cause OOM, even there is no any join operator reach the limit.
`MemorySpillScheduler` chooses one operator to  trigger it spill based on total memory usage and each operator's memory usage. It could avoid the above cases.
manual tests
> [GLUTEN-8705][CH] Enable MemorySpillScheduler

- cpp-ch/local-engine/AggregateFunctions/AggregateFunctionUniqHyperLogLogPlusPlus.h
Issue: The argument types passed to std::min do not match in a way that the template can resolve. Specifically:
- ow + K is of type size_t
- num_estimates is of type size_t, but the error message shows it being deduced as UInt64, which is likely an alias for unsigned long long.
Solution: Use static_cast to explicitly cast the types and resolve the mismatch.
rebuild
> [GLUTEN-8749][CH] Explicitly cast input data type for std::min

- cpp-ch/local-engine/Functions/SparkFunctionCastFloatToInt.cpp
- cpp-ch/local-engine/Functions/SparkFunctionCastFloatToInt.h
- cpp-ch/local-engine/Functions/SparkFunctionCheckDecimalOverflow.cpp
- cpp-ch/local-engine/Functions/SparkFunctionDecimalBinaryArithmetic.h
- cpp-ch/local-engine/Functions/SparkFunctionDivide.h
- cpp-ch/local-engine/Parser/ExpressionParser.cpp
- cpp-ch/local-engine/tests/CMakeLists.txt
- cpp-ch/local-engine/tests/benchmark_spark_functions.cpp
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
try accelerate some spark* function through vectorization
- sparkDivide: 
- vectorVector(1.09x)
- vectorConstant(25x) 
- castFloatToInt*: 2.67x
- checkDecimalOverflowSparkOrNull:
- decimal to decimal, scale up: 1.47x
- decimal to decimal, scale down: 1.94x
- decimal to decimal, no scale change: 274x
- int to decimal: 3.07x
- float to decimal: 10.98x
spark ut "SPARK-28224: Aggregate sum big decimal overflow" was excluded from spark3.5 because it runs in ansi mode, which is not fully supported in gluten currently. 
(Fixes: \#8704)
existing uts
baseline version
```
---------------------------------------------------------------------------------------
Benchmark                                             Time             CPU   Iterations …
```
> [GLUTEN-8704][CH] try accelerate some spark* function by optimizing tight loops

- tools/gluten-te/centos/centos-7-deps.sh
- tools/gluten-te/centos/centos-8-deps.sh
The following is reported by `shellcheck`:
```
In POSIX sh, [[ ]] is undefined.
See SC2039.
```
Fix by changing to `#/bin/bash`
> [VL] nit: gluten-it: Fix non-POSIX shell warnings in centos-7-deps.sh

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
`SubstraitToVeloxPlanValidator::validateLiteral` allows all literals to pass, so it should be removed
> [GLUTEN-8779][VL][Minor] Code cleanup for native validation

- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelation.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelationTest.scala
Fix mode field in UnsafeColumnarBuildSideRelation can not get properly serialized and deserialized, also fix when using Java default serializer potential data mismatch by change  `read` to `readFully`.
(Fixes: \#8761)
unit test
> [GLUTEN-8761][VL] Fix mode in UnsafeColumnarBuildSideRelation not get properly serialize

- cpp-ch/local-engine/Common/CHUtil.h
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
Allow users to pass parameters to determine whether to use virtual addressing or not.
(Fixes: \#8795)
self test with UT
> [GLUTEN-8795][CH] Support to use oss with gluten

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxTransformerApi.scala
- cpp/velox/operators/writer/VeloxParquetDataSource.cc
- cpp/velox/operators/writer/VeloxParquetDataSource.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
This adds support for the following write options to 3.4 / 3.5 Parquet write:
- block size
- sql conf: `spark.gluten.sql.columnar.parquet.write.blockSize`
- option: `parquet.block.size`
- block rows
- sql conf: `spark.gluten.sql.native.parquet.write.blockRows`
- option: `parquet.block.rows`
The options were supported in 3.2 / 3.3. The patch adds them to 3.4 / 3.5 to make sure the [document](https://github.com/apache/incubator-gluten/blob/e9bff4f27f341570bec270e0f327e59484b737bf/docs/velox-backend-limitations.md?plain=1#L132-L140) applies for all Spark versions.
With some other minor code cleanups.
> [VL] Add support for some Parquet write options to 3.4 / 3.5 to align with 3.2 / 3.3

- gluten-iceberg/src-iceberg/main/java/org/apache/gluten/substrait/rel/IcebergLocalFilesNode.java
- gluten-substrait/src/main/resources/substrait/proto/substrait/algebra.proto
Since the PR for Iceberg support of equality delete files in the Velox community has not been merged for a long time, ClickHouse backend needs to add support for equality delete files. We will first merge the protobuf definitions to facilitate ClickHouse's subsequent development.
N/A
> [CORE] Add iceberg equality delete file proto definition

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxValidatorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicPhysicalOperatorTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/ValidationResult.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenFallbackReporter.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
1. Add configuration `spark.gluten.sql.validation.failFast` to control whether to fail validation on the first failure or to continue verifying as much as possible. More validations can provide additional fallback reasons for a given query. `true` by default to follow the current fail-fast behaviour.
For example, with setting `spark.gluten.sql.validation.failFast=false` the log for query `SELECT convert_timezone('Europe/Moscow', 'America/Los_Angeles', timestamp_ntz'2022-01-01 00:00:00')` shows like
Before:
```
15:26:54.204 WARN org.apache.spark.sql.execution.GlutenFallbackReporter: Validation failed for plan: Project[QueryId=38], due to: Found schema check failure for StructType(StructField(convert_timezone(Europe/Moscow, America/Los_Angeles, TIMESTAMP_NTZ '2022-01-01 …
```
> [GLUTEN-8794] Support logging as many fallback reasons as possible

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
I note Velox's HDFS filesystem allows ViewFs scheme. 
https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/storage_adapters/hdfs/HdfsFileSystem.cpp#L112.
Then, we can just rely on the uniform JNI call through `allSupportedByRegisteredFileSystems`, instead of resolving the ViewFS file path in Gluten scan validation.
Customer validation.
> [VL] Remove resolving ViewFs file path from scan validation

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- gluten-iceberg/src-iceberg/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
- gluten-iceberg/src-iceberg/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala
- gluten-iceberg/src-iceberg/test/scala/org/apache/gluten/execution/IcebergSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/IteratorApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BatchScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
With storage partition join, suppose the left leaf partition is [1, 2], the right partition is [1, 2, 10], the number of partitions is not equal, use empty partition for those partition values that are not present.
```
index | left | right
0 | Seq(1) | Seq(1)
1 | Seq(2) | Seq(2)
2 |  Seq() | Seq(10)
```
Relevant Spark PR: 
https://github.com/apache/spark/pull/35657
> [GLUTEN-8811][VL]Fix bucket scan when some partitionValue is empty

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHBucketSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxMetricsSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxTPCHSuite.scala
- gluten-substrait/src/test/scala/org/apache/spark/sql/GlutenTestUtils.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseSQLQueryTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxSQLQueryTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
`GlutenSQLQueryTestSuite.scala` originates from `org.apache.spark.sql.SQLQueryTestSuite`, but the content of the file is not aligned with spark. It seems like the file was created by simply copying and pasting from the old file from spark33/spark34 shim when supporting new Spark versions in Gluten.
Update the content of `GlutenSQLQueryTestSuite.scala` and mark the modifications for Gluten. Developers who will be working on supporting future Spark versions should pay attention to the content changes in the original file in Spark.
> [GLUTEN-8738] Update GlutenSQLQueryTestSuite to match with the original file

- pom.xml
Make testFailureIgnore configurable for local tests.
`mvn ... -Dmaven.test.failure.ignore=true`
> [CORE] Make scalatest.testFailureIgnore configurable for convenience

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/BasicExpressionRewriteRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/compareSubstrings.cpp
> [GLUTEN-8859][CH] Take advantage of `compareSubstrings` to compare substrings

- docs/Configuration.md
- docs/get-started/Velox.md
https://github.com/apache/incubator-gluten/pull/8127 has introduced feature on moving memory use of broadcast  use from on heap to off-heap. This PR aims to add document on how to use it.
> [DOC] add doc about experimental feature using off-heap to store broadcast build relation

- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- cpp/velox/compute/VeloxBackend.cc
Velox is using 23 bits fro cache entry size
https://github.com/facebookincubator/velox/pull/10242
manually tested with local SSD cache enabled
> [GLUTEN-5884][VL] change default load quantum to 8M for local SSD cache

- backends-clickhouse/src/main/scala/org/apache/gluten/execution/GlutenMergeTreePartition.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/files/MergeTreeFileCommitProtocol.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/datasources/v2/clickhouse/metadata/AddFileTags.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseNativeWriteTableSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
- backends-clickhouse/src/test/scala/org/apache/spark/gluten/NativeWriteChecker.scala
- cpp-ch/local-engine/Functions/SparkPartitionEscape.cpp
- cpp-ch/local-engine/Functions/SparkPartitionEscape.h
- cpp-ch/local-engine/Parser/scalar_function_parser/CommonScalarFunctionParser.cpp
- cpp-ch/local-engine/Storages/MergeTree/SparkMergeTreeMeta.cpp
- cpp-ch/local-engine/Storages/Output/NormalFileWriter.h
- cpp-ch/local-engine/tests/CMakeLists.txt
- cpp-ch/local-engine/tests/benchmark_spark_partition_escape_function.cpp
> [GLUTEN-8836][CH] Fix partition values with escape char

- .github/workflows/util/install_spark_resources.sh
This PR changes binary release names with Scala 2.13, e.g. from
spark-3.5.2-bin-hadoop3-scala-2.13.tgz
to
spark-3.5.2-bin-hadoop3-scala2.13.tgz
1. invalid URL: https://www.apache.org/dyn/closer.lua/spark/spark-3.5.2/spark-3.5.2-bin-hadoop3-scala-2.13.tgz?action=download
2. valid URL: https://www.apache.org/dyn/closer.lua/spark/spark-3.5.2/spark-3.5.2-bin-hadoop3-scala2.13.tgz?action=download
> [HOTFIX] Fix binary release name for Spark 3.5.2 with Scala 2.13 

- backends-clickhouse/pom.xml
- backends-velox/pom.xml
- gluten-arrow/pom.xml
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/gluten/initializer/CodedInputStreamClassInitializer.scala
- gluten-core/src/main/scala/org/apache/gluten/initializer/Initializer.scala
- gluten-delta/pom.xml
- gluten-hudi/pom.xml
- gluten-iceberg/pom.xml
- gluten-substrait/pom.xml
- package/pom.xml
- pom.xml
We previously introduced custom protobuf dependency with only defaultRecursionLimit enlarged to avoid the limit is hit for deeply nested plans (one user reported this issue). It is not easy to upgrade this dependency since it requires local build and then publishing the jar to maven repo.
With this change, we can remove the custom protobuf dependency for easily upgrading protobuf when needed.
Verified by local remote debug.
> [CORE] Enlarge defaultRecursionLimit by pre-loading the protobuf class

- .github/workflows/velox_nightly.yml
This patch adds nightly release for Gluten. Currently it will do a build on 0:00 for Spark35, with vcpkg static build enabled. The package will be uploaded in the action artifacts 
example:
https://github.com/apache/incubator-gluten/actions/runs/13685858117
pass GHA
> [VL] Adding nightly release

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
Velox's type has isXXX func to check the type, using this function can make the code more concise.
N/A
> [VL] Use isType func to check type

- .github/workflows/util/install_spark_resources.sh
For spark distributions with scala 2.13, the folder has a scala2.13 prefix
tar --strip-components=1 -xf spark-3.5.2-bin-hadoop3-scala2.13.tgz spark-3.5.2-bin-hadoop3-scala2.13/jars/
Run `tar --strip-components=1 -xf spark-3.5.2-bin-hadoop3-scala2.13.tgz spark-3.5.2-bin-hadoop3-scala2.13/jars/` locally
> Add scala suffix to tar command

- backends-clickhouse/src/main/scala/org/apache/spark/sql/delta/ClickhouseSnapshot.scala
The method for obtaining parameters needs to be adjusted: when activeSession is None, retrieve defaultSession, or throw a more explicit exception.Spark provides this approach, accessible directly via SparkSession.active.
(Fixes: \#8926)
> [GLUTEN-8926][CH] MergeTree Parameter Configuration Optimization to Prevent Multithreading Competition for activeSession Being None

- .github/workflows/docker_image.yml
- dev/docker/Dockerfile.centos8-dynamic-build
- dev/docker/Dockerfile.centos8-dynamic-build-jdk17
- dev/docker/Dockerfile.centos8-static-build
- dev/docker/Makefile
- dev/vcpkg/env.sh
- dev/vcpkg/ports/duckdb/portfile.cmake
- dev/vcpkg/ports/libelf/portfile.cmake
- dev/vcpkg/setup-build-depends.sh
- docs/developers/velox-backend-build-in-docker.md
Fixes: #8802
[Build process](https://github.com/kevinw66/incubator-gluten/actions/runs/13438373999) on my local repo.
[Docker hub results](https://hub.docker.com/repository/docker/wzg547228197/gluten/tags)
* Since CentOS-7 does not fully support arm architecture, I added CentOS-8 static build here.
* We need to update image name on `velox_backend.yml` from `apache/gluten:centos-8` to `apache/gluten:centos-8-jdk8` on later PR, I didn't put it here because it may affect the CI process of this PR, and PRs raised while building image `apache/gluten:centos-8-jdk8` will also failed due to it doesn't exist.
> [GLUTEN-8802][VL] Support build static/dynamic docker images for arm

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/compatibility/GlutenClickhouseFunctionSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionCheckDecimalOverflow.cpp
- cpp-ch/local-engine/Parser/aggregate_function_parser/LeadLagParser.cpp
…d lead function
(Fixes: \#8921, #8922)
> [GLUTEN-8921][GLUTEN-8922][CH] Fix checkDecimalOverflowSparkOrNull and lead function

- cpp-ch/clickhouse.version
- cpp-ch/local-engine/Common/BlockTypeUtils.h
- cpp-ch/local-engine/Storages/Parquet/ParquetMeta.cpp
- cpp-ch/local-engine/Storages/Parquet/ParquetMeta.h
- cpp-ch/local-engine/Storages/Parquet/VectorizedParquetRecordReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/FileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/EqualityDeleteFileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/EqualityDeleteFileReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/IcebergMetadataColumn.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/IcebergReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/IcebergReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/PositionalDeleteFileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/PositionalDeleteFileReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/SimpleParquetReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/iceberg/SimpleParquetReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/substrait_fwd.h
- cpp-ch/local-engine/tests/gtest_iceberge_test.cpp
- cpp-ch/local-engine/tests/utils/ReaderTestBase.cpp
- cpp-ch/local-engine/tests/utils/ReaderTestBase.h
(Fixes: \#8846)
Enhance Parquet and Iceberg readers to handle delete columns not in select list and support positional delete operations in Iceberg tables.
- **Bitmap**  
Introduced `DeltaDVRoaringBitmapArray` for efficient position tracking:
```cpp
void rb_add(Int64 x);  // Add deleted positions
bool rb_contains(Int64 x) const;  // Check position existence
```
- **Reader Integration**  
- `PositionalDeleteFileReader` processes position delete files
- Iceberg metadata column handling:
```cpp
static std::shared_ptr<IcebergMetadataColumn> icebergDeletePosColumn();
```
- **Filter**  
Modified Iceberg reader to apply bitmap filters during chunk generation:
```cpp
delete_bitmap_array->rb_contains(pos[i]);
```
Fix an issue when excuting sql like `select c0 from t ` and **Equality Delete File** …
> [GLUTEN-8846][CH] [Part 1] Support Positional Deletes

- backends-clickhouse/src-delta-32/main/scala/org/apache/gluten/sql/shims/delta32/Delta32Shims.scala
- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaParquetDeletionVectorSuite.scala
- backends-clickhouse/src-delta/main/scala/org/apache/gluten/sql/shims/DeltaShims.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHInputPartitionsUtil.scala
- backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/commands/GlutenCacheFilesCommand.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxIteratorApi.scala
- cpp-ch/local-engine/Storages/SubstraitSource/CMakeLists.txt
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/Bitmap/DeltaDVRoaringBitmapArray.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/Bitmap/DeltaDVRoaringBitmapArray.h
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaReader.h
- cpp-ch/local-engine/Storages/SubstraitSource/FileReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/ParquetFormatFile.cpp
- gluten-iceberg/src-iceberg/main/java/org/apache/gluten/substrait/rel/IcebergLocalFilesNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/LocalFilesBuilder.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/rel/LocalFilesNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/utils/SubstraitUtil.java
- gluten-substrait/src/main/resources/substrait/proto/substrait/algebra.proto
- gluten-substrait/src/main/scala/org/apache/gluten/utils/InputPartitionsUtil.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HivePartitionConverter.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
Part-2:
Support reading deletion vectors bitmap when queryring
(Fixes: \#8872)
> [GLUTEN-8872][CH][Part-2] Support Delta Deletion Vectors read for CH backend

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
Enables map_concat function for both EXCEPTION and LAST_WIN deduplicate policies.
Verified with UT.
> [VL] Enable map_concat function

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/gluten/initializer/CodedInputStreamClassInitializer.scala
Follow-up fix for #8904. This exception can happen in maven test due to the class we are loading is shaded in final package phase.
No such exception printed in CI test.
> [CORE] Avoid ClassNotFoundException when loading a shaded protobuf class

- .github/workflows/velox_backend.yml
- dev/buildbundle-veloxbe.sh
- docs/developers/MicroBenchmarks.md
- docs/get-started/Velox.md
Remote shuffle service related build option is not necessary in some tests. To reduce the burden of CI workload, we can remove them. And in some docs, it is confusing to keep these options as they are not generally required by users.
> [VL] Remove unnecessary build options

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
velox does not support cast decimal to timestamp.
The `isInteger()` check in velox returns true for decimal type.
Fixes: #9019
> [GLUTEN-9019][VL] Add a check to fall back "cast decimal to timestamp"

- .github/workflows/velox_backend.yml
- backends-velox/src/test/scala/org/apache/gluten/execution/ArrowCsvScanSuite.scala
In #7789, Spark-3.4.4 support is added and JDK-17 docker is used to avoid some issues caused by arrow. This pr changes to use the unified docker image and switches JDK version before running the test, which can reduce the efforts a bit for maintaining docker images.
I cannot figure out the reason why this way didn't pass in previous test. Maybe, we can land this pr firstly and continue observing the CI feedback while still keeping the JDK-17 docker image available in docker hub for some time.
CI.
> [VL][CI] Use a unified docker image for Spark tests

- backends-velox/src-hudi/test/scala/org/apache/gluten/execution/VeloxHudiSuite.scala
- backends-velox/src-hudi/test/scala/org/apache/gluten/execution/VeloxTPCHHudiSuite.scala
The package name for the `src-hudi/test` in velox-backend is missing "gluten."
N/A
> [VL] Move hudi test package to org.apache.gluten.execution

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/BackendSettingsApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BroadcastNestedLoopJoinExecTransformer.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/joins/GlutenBroadcastJoinSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
Currently, BroadcastNestedLoopJoin doesn't support full outer join. That's because in velox/presto, it supposed that the probe side and build side(broadcast side) are all in one worker, so that it can output mismatch records from build side.
But for spark, the probe side are distributed across different executors, so that velox cann't recognize the mismatch records from build side.
But if the join condition is empty (which is usually the case where BroadcastedNestedLoopJoin take effect), there is no need to output mismatch records. 
(Fixes: \#8964)
UT and manually
> [GLUTEN-8964][VL] Support BNLJ full outer join without condition

- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaParquetDeletionVectorSuite.scala
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaReader.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/FileReader.cpp
Fix reading bug for the update operation with the deletion vectors: 
Add the '__delta_internal_is_row_deleted' column even if there is no DV for the parquet files
(Fixes: #8872)
> [GLUTEN-8872][CH][Part-3] Fix reading bug for the update operation with the deletion vectors

- cpp/velox/shuffle/VeloxShuffleReader.cc
Since the total size of the stream cannot be directly obtained while reading the RSS stream, the current remainingSize represents the remaining size of the current buffer, not the actual remaining size of the entire stream. However, in Velox, there is a validation process for remainingSize. Therefore, this PR is necessary to address the issue.
CI
> [GLUTEN-8437][VL] Fix the exception when verifying the PrestoPage header during the Presto deserialization process

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseExcelFormatSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ArrowCsvScanSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxWindowExpressionSuite.scala
- gluten-substrait/src/test/scala/org/apache/gluten/execution/WholeStageTransformerSuite.scala
Resolve compile warning, `runAndCompare("**") {}` should be used instead of `runAndCompare("**")()`, but param `f` is not used, so remove it.
```
[WARNING] /opt/gluten/backends-velox/src/test/scala/org/apache/gluten/execution/ArrowCsvScanSuite.scala:113: warning: [deprecation @ org.apache.gluten.execution.ArrowCsvScanSuite.<local ArrowCsvScanSuite>.df | origin=org.apache.gluten.execution.WholeStageTransformerSuite.runAndCompare | version=2.11.0] Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
[WARNING]         signature: WholeStageTransformerSuite.runAndCompare(sql: String)(f: => Unit): org.apache.spark.sql.DataFrame
[WARNING]   given arguments: <none>
[WARNING]  after adaptation: WholeStageTransformerSuite.runAndCompare((): Unit)
[WARNING] …
```
> [TEST] Remove useless param for runAndCompare

- backends-velox/src/main/scala/org/apache/spark/memory/GlobalOffHeapMemory.scala
- backends-velox/src/test/scala/org/apache/spark/memory/GlobalOffHeapMemorySuite.scala
- shims/common/src/main/scala/org/apache/spark/storage/BlockManagerUtils.scala
- shims/spark32/src/main/scala/org/apache/spark/TaskContextUtils.scala
- shims/spark33/src/main/scala/org/apache/spark/TaskContextUtils.scala
- shims/spark34/src/main/scala/org/apache/spark/TaskContextUtils.scala
- shims/spark35/src/main/scala/org/apache/spark/TaskContextUtils.scala
Add the following common APIs for acquiring / releasing global off-heap memory from Spark:
- GlobalOffHeapMemory.acquire()
- GlobalOffHeapMemory.free()
The API could be used to replace various of current practices to apply for global off-heap memory. E.g., the fake task memory manager used by off-heap broadcasting: https://github.com/apache/incubator-gluten/blob/bf980dcbb8bc912995381bed2ade6dd082ec324a/backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelation.scala#L151.
> [VL] Add API for reserving global off-heap memory from Spark

- backends-velox/src/main/scala/org/apache/spark/memory/GlobalOffHeapMemory.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeBytesBufferArray.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelation.scala
- backends-velox/src/test/scala/org/apache/spark/memory/GlobalOffHeapMemorySuite.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelationTest.scala
A follow-up for #8762 to avoid creating a dummy TaskMemoryManager (which was hack) for reserving off-heap memory for off-heap broadcast exchange. 
The code now calls new API introduced in https://github.com/apache/incubator-gluten/pull/9066 to acquire for off-heap storage memory.
> [VL] Acquire off-heap global memory via the new API for off-heap broadcast exchange

- gluten-core/src/main/scala/org/apache/spark/softaffinity/SoftAffinity.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/WholeStageTransformer.scala
There are two minor changes.
1. Simple the code when iterate over `allInputPartitions`, which is a bit confusion.
```
allInputPartitions.head.indices.foreach(
i => {
val currentPartitions = allInputPartitions.map(_(i))
currentPartitions.indices.foreach(
i =>
currentPartitions(i) match {
case f: FilePartition =>
SoftAffinity.updateFilePartitionLocations(f, rdd.id)
case _ =>
})
})
```
2.  Don't need to iterate and check whether `SoftAffinityManager.usingSoftAffinity` are enabled every time inside loop
(Fixes: \#9078)
Existing UT
> [GLUTEN-9078][CORE] Simplify code of SoftAffinity

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/HashAggregateExecTransformer.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/HashAggregateIgnoreNullKeysRule.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- gluten-substrait/src/main/scala/org/apache/gluten/execution/HashAggregateExecBaseTransformer.scala
For aggregation followed by an inner join on the grouping keys, it's safe to mark the `ignoreNullKeys` flag to true to avoid unnecessary aggregation on null keys.
(Fixes: \#8966)
UT and manually
> [GLUTEN-8966][VL] Propagate HashAggregate's ignoreNullKeys when possible

- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarPartialProjectExec.scala
- backends-velox/src/main/scala/org/apache/spark/sql/hive/VeloxHiveUDFTransformer.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/GlutenHiveUDFSuite.scala
Where both `spark.gluten.supported.hive.udfs` and `spark.gluten.sql.columnar.partial.project` rules are applicable, we should prioritize `UDFMapping` over `ColumnarPartialProject`.
For example,
```
set spark.gluten.supported.hive.udfs=udfB; # which means udfB is rewrite in velox side
select default.udfA(input1), default.udfB(input2), get_json_object(input3, '$.a') from t
```
Before this patch, the plan is
```
---------------------------------------------------------------------------------------------------------------------------------
| ColumnarPartialProject(default.udfA(input1) as _SparkPartialProject0,  default.udfB(input2) as _SparkPartialProject1, input3) |
------------------------------------------------------------------------------------------------------------------------------- …
```
> [GLUTEN-9076][VL] Prioritize offloading supported hive udf in ColumnarPartialProject

- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- We don't run TryCastSuite for CH 3.4 currently
- Enabling the same and bringing parity with other backends.
- Unit Test
> [GLUTEN-9093][CH] Add TryCastSuite for CH backend Spark 3.4

- .github/workflows/velox_backend.yml
This patch pined `setuptools` version to `77.0.3`. 
The new release `78.0.1` is requiring some changes not available in old pyspark
(Fixes: #9123 )
pass GHA
> [GLUTEN-9123][VL][CI] pin setuptools version in CI

- cpp/velox/shuffle/VeloxShuffleReader.cc
- cpp/velox/shuffle/VeloxShuffleReader.h
Optimize memory allocation for VeloxRssShuffleReader
CI
> [VL] Optimize memory allocation for VeloxRssShuffleReader

- cpp-ch/local-engine/Parser/SerializedPlanParser.cpp
Fix ut `test MicroBatchscanExecTransformer not fallback ` error with 'Kafka group.1d 1s not set'
Test by ut `test MicroBatchscanExecTransformer not fallback `
> [CH] Fix kafka unstable ut

- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/compute/VeloxRuntime.cc
- cpp/velox/config/VeloxConfig.h
- cpp/velox/memory/VeloxMemoryManager.cc
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Currently, the flags `FLAGS_velox_exception_user_stacktrace_enabled`, `FLAGS_velox_exception_system_stacktrace_enabled`, `FLAGS_velox_memory_use_hugepages`, `FLAGS_cache_prefetch_min_pct` and `FLAGS_velox_memory_pool_capacity_transfer_across_tasks` are utilized in the Velox runtime, but their configuration is currently limited to VeloxBackend. This PR migrates their configuration to VeloxRuntime, enabling dynamic modification through session configurations and runtime adjustments.
GA
> [VL][MIRROR] Migrate Velox runtime config flags to dynamic VeloxRuntime settings

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/main/scala/org/apache/spark/memory/GlobalOffHeapMemory.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeBytesBufferArray.scala
- backends-velox/src/test/scala/org/apache/spark/memory/GlobalOffHeapMemorySuite.scala
- cpp/core/jni/JniCommon.h
- cpp/core/jni/JniWrapper.cc
- cpp/core/memory/MemoryAllocator.cc
- cpp/velox/benchmarks/ParquetWriteBenchmark.cc
- cpp/velox/benchmarks/common/BenchmarkUtils.cc
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/compute/VeloxBackend.h
- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/memory/VeloxMemoryManager.cc
- cpp/velox/memory/VeloxMemoryManager.h
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/tests/BufferOutputStreamTest.cc
- cpp/velox/tests/MemoryManagerTest.cc
- cpp/velox/tests/RuntimeTest.cc
- gluten-arrow/src/main/java/org/apache/gluten/init/NativeBackendInitializer.java
1. Pass an allocation listener that reserves memory from `GlobalOffHeapmemory` from Java to C++ for `VeloxMemoryManager::getDefaultMemoryManager()`
2. Memory allocations during the following operations will be tracked with Spark global off-heap memory now (previously untracked):
- VeloxRuntime::planString
- nativeValidateWithFailureReason
- SubstraitToVeloxPlanConverter::constructValuesNode
- gluten::recordBatch2VeloxColumnarBatch (for testing)
Future TODOs:
1. leak-detection
2. evict / spill from global off-heap memory
> [VL] Account some C++ untracked memory allocations into Spark global off-heap memory

- cpp/core/jni/JniCommon.h
- cpp/velox/benchmarks/PlanValidatorUtil.cc
- cpp/velox/jni/VeloxJniWrapper.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.h
- cpp/velox/tests/Substrait2VeloxPlanValidatorTest.cc
Make global class reference for NativePlanValidationInfo. It's inefficient to find the class and creat a local reference in each JNI call.
Refactor SubstraitToVeloxPlanValidator.
> [VL] Improve native plan validation code

- cpp/velox/memory/VeloxColumnarBatch.cc
- cpp/velox/memory/VeloxColumnarBatch.h
- cpp/velox/operators/serializer/VeloxColumnarToRowConverter.cc
In some cases, `ensureFlattened` is a bit heavy. 
While in `ColumnarBatch.select`, not all children of input row vector are needed. 
In some of our test case, this can reduce ~5% vcore times.
(Fixes: \#9057)
manually
> [GLUTEN-9057][VL] Avoid flatten unnecessary vector in ColumnarBatch.select

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHExpressionTransformer.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Parser/scalar_function_parser/arrayHighOrderFunctions.cpp
(Fixes: \#9039)
Before opt: spark  array_sort(arr) ->  CH arraySparkSort(func, arr)
After opt:    spark  array_sort(arr) -> CH  arraySparkSort(arr) 
> [GLUTEN-9039][CH] Improve array_sort performance when only single argument is input 

- cpp/core/shuffle/LocalPartitionWriter.cc
The purpose of this change is to ensure that the shuffle data files allowing read access for the others to fix shuffle fetch fail.
The error message on NodeManager:
```
2025-03-25 07:18:11,497 ERROR org.apache.spark.network.server.ChunkFetchRequestHandler: Error sending result ChunkFetchSuccessWithExtraInfo[streamChunkId=StreamChunkId[streamId=1416440634155,chunkIndex=0],buffer=FileSegmentManagedBuffer[file=/hadoop/4/yarn/local/usercache/user/appcache/application_1736396393732_77665/blockmgr-4ce81eec-e4a1-4d47-a3c5-392fa718fc18/33/shuffle_3_2281_0.data,offset=10784763,length=78581]] to /10.18.80.16:49944
java.io.FileNotFoundException: /hadoop/4/yarn/local/usercache/user/appcache/application_1736396393732_77665/blockmgr-4ce81eec-e4a1-4d47-a3c5-392fa718fc18/33/shuffle_3_2281_0.data …
```
> [GLUTEN-9148] Fix shuffle file permission issue when using ColumnarShuffleManager

- .github/workflows/velox_weekly.yml
- dev/build-thirdparty.sh
- ep/build-velox/src/setup-centos7.sh
1. Since https://github.com/facebookincubator/velox/commit/e8c986c9b2edbcd32d6855959b957a6b906eec42, /usr/local/lib/libprotobuf.so.32 is not installed on Ubuntu but a static lib is installed, which causes packing third-party lib fails. 
2. The `tzdata-2025a-1.el9.noarch.rpm` rpm package cannot be installed on centos-7. Like Yuan's fix in velox_backend.yml, use pip to install and update zoneinfo.
```
Error: transaction check vs depsolve:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by tzdata-2025a-1.el9.noarch
```
Local test.
> [VL] Fix weekly build job

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/hive/GlutenClickHouseHiveTableSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/PushDownInputFileExpression.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala
Fixes: \#9055 by making PushDownInputFileExpression effective for hive text table.  
After fixing, there is still tiny diff between vanilla and gluten: when format is textfile, input_file_name() in vanilla returns paths like 'file:/xxx', ut in gluten it returns paths like 'file:///xxx', users who use input_file_name() in gluten should be aware of that.
> [GLUTEN-9055][CH] Fix input_file_name diff from hive text table

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashAggregateExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/SimplifySumRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
Simplify sum with the following rules: 
- Rule 1: sum(expr / literal) -> sum(expr) / literal
- Rule 2: sum(expr * literal) -> literal * sum(expr)
- Rule 3: sum(literal * expr) -> literal * sum(expr) 
If current rule is combined with https://github.com/apache/incubator-gluten/pull/9185, we can easily transform
- sum(if(cond, expr/literal, 0)) -> (sum(expr) filter (where cond)) / literal
- sum(if(cond, expr * literal, 0)) -> (sum(expr) filter (where cond)) * literal
- sum(if(cond, literal * expr, 0)) -> (sum(expr) filter (where cond)) * literal
(Fixes: \#9197)
> [GLUTEN-9197][CH] Simplify sum aggregate expression

- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
Enable more ut in VeloxTestSettings
Existing UT
> [VL] Enable more ut in VeloxTestSettings

- cpp/core/shuffle/LocalPartitionWriter.cc
Fixes #9199 by setting a default mode to the `open` call.
> [GLUTEN-9199][VL] Fix error when creating shuffle file: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments 

- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
This PR https://github.com/apache/incubator-gluten/pull/8583 fix the uppercase issue, but not drop the old config key
> [CORE] Fix duplicate setting for config LEGACY_TIME_PARSER_POLICY

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/AggregateIfToFilterRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
Rewrite aggregate if to aggregate with filter clause to use CH aggregate combinator -If . 
- Rule1: sum(if(cond, expr, 0)) -> sum(expr) FILTER (WHERE cond)
- Rule2: func(if(cond, expr, null)) -> func(expr) FILTER (WHERE cond)
(Fixes: \#9176)
> [GLUTEN-9176][CH] Rewrite aggregate if to aggregate with filter clause

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHFilterExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/expression/CHFlattenedExpression.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/FlattenNestedExpressions.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
- cpp-ch/local-engine/Functions/SparkFunctionTupleElement.cpp
- cpp-ch/local-engine/Parser/FunctionParser.cpp
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicPhysicalOperatorTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionConverter.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
> [GLUTEN-8557][CH] Flatten nested `And`/`Or` for performance optimization

- cpp/velox/utils/ConfigExtractor.cc
- docs/get-started/VeloxS3.md
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
This PR aims to add the s3a configuration supported by Velox in Gluten.
(Fixes: \#9182)
> [GLUTEN-9182][VL] Support new s3 configuration in Gluten

- backends-velox/src-celeborn/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarBatchSerializer.scala
Below code piece will create a buffered input stream on native side. The buffer is released on close() called when EOS is reached in `readValue()`. For empty input stream, the `readValue` function is never called, and the buffered memory can only be released at task end.
```
ShuffleReaderJniWrapper
.create(runtime)
.readStream(shuffleReaderHandle, byteIn))
```
> [VL] Celeborn shuffle reader OOM with many empty input stream

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHRuleApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/JoinAggregateToAggregateUnion.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenEliminateJoinSuite.scala
> [GLUTEN-9196][CH] Use wide-table aggregation to eliminate multi-table joins

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/main/scala/org/apache/spark/sql/expression/UDFResolver.scala
- gluten-core/src/main/java/org/apache/gluten/jni/JniLibLoader.java
- gluten-core/src/main/java/org/apache/gluten/jni/JniWorkspace.java
Make JniWorkspace not depend on spark.
(Fixes: \#9149)
This patch was tested by existing unit tests and integration tests.
> [GLUTEN-9149][CORE] Remove Spark-specific code from JniLibLoader & JniWorkspace

- backends-clickhouse/src/main/scala/org/apache/gluten/utils/CHExpressionUtil.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/JsonFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
This PR aims to support json_object_keys function.
(Fixes: \#9008)
unit tests
> [GLUTEN-9008][VL] Support json_object_keys function

- backends-clickhouse/pom.xml
- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/CHNativeExpressionEvaluator.java
- backends-clickhouse/src/main/java/org/apache/gluten/vectorized/ExpressionEvaluatorJniWrapper.java
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHListenerApi.scala
- cpp-ch/local-engine/local_engine_jni.cpp
Support JDK17 for the CH backend.
Due to the changes in the JNI OnUnLoad calling mechanism of the JDK17, it needs to manually call the destroy native function
to release ch resources and avoid core dump.
Close #9239.
(Fixes: #9239)
> [GLUTEN-9239][CH] Support JDK17 for the CH backend

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Functions/SparkParseURL.cpp
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
> [GLUTEN-9177][CH]Fix diff on parse host of url and refactor `SparkParseURL`

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenAutoAdjustStageResourceProfile.scala
For whole stage fallback case, we should not request the same offheap memory size as offload case.
Fix a feature that is still experimental.
> [CORE] Decrease offheap memory size in resource profile for whole stage fallback case

- backends-clickhouse/src-delta-32/main/java/org/apache/gluten/vectorized/DeltaWriterJNIWrapper.java
- backends-clickhouse/src-delta-32/main/scala/org/apache/gluten/sql/shims/delta32/Delta32Shims.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/delta/commands/DMLWithDeletionVectorsHelper.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/execution/ColumnarDeletionVectorWriteExec.scala
- backends-clickhouse/src-delta-32/main/scala/org/apache/spark/sql/execution/DeletionVectorWriteTransformer.scala
- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaParquetDeletionVectorSuite.scala
- backends-clickhouse/src-delta/main/scala/org/apache/gluten/component/CHDeltaComponent.scala
- backends-clickhouse/src-delta/main/scala/org/apache/gluten/sql/shims/DeltaShims.scala
- cpp-ch/local-engine/AggregateFunctions/AggregateFunctionDVRoaringBitmap.h
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/Bitmap/DeltaDVRoaringBitmapArray.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/Bitmap/DeltaDVRoaringBitmapArray.h
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaUtil.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaUtil.h
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaWriter.cpp
- cpp-ch/local-engine/Storages/SubstraitSource/Delta/DeltaWriter.h
- cpp-ch/local-engine/local_engine_jni.cpp
- cpp-ch/local-engine/tests/gtest_clickhouse_roaring_bitmap.cpp
> [GLUTEN-9205][CH] Support deletion vector native write

- cpp/velox/jni/VeloxJniWrapper.cc
The global reference to class object of `NativePlanValidationInfo` was introduced in #9092. It should be explicitly deleted in JNI unload.
> [VL] Delete global reference to a class object in JNI unload

- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarPartialProjectExec.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/UDFPartialProjectSuite.scala
With argument projectList in class `ColumnarPartialProjectExec`, function QueryPlan.expressions can return the Expression list correctly, then the function executeQuery can find the SubQuery from Expression.
> [GLUTEN-9245][VL] Fix partial project expression contains subquery

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxColumnarCacheSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/MiscColumnarRules.scala
This fixes the test case added in https://github.com/apache/incubator-gluten/pull/8498.
The patch conditionally adds a `ColumnarToRowRemovalGuard` node that does nothing on top of a 
```
+- ColumnarToRow
+- FileScan parquet
```
which is to be cached to avoid [this Spark code](https://github.com/apache/spark/blob/9d3f937c555ccab7777c976b66da7c7229582f26/sql/core/src/main/scala/org/apache/spark/sql/execution/columnar/InMemoryRelation.scala#L335-L351) from removing the C2R, the plan will become:
```
ColumnarToRowRemovalGuard
+- ColumnarToRow
+- FileScan parquet [l_orderkey_read#128L] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/tmp/spark-e732391d-d3f4-45e7-ae2e-d521d7658b01], PartitionFilters: [], PushedFilters: [], ReadSchema: …
```
> [GLUTEN-8497][VL] Fix columnar batch type mismatch in table cache

- cpp/core/config/GlutenConfig.h
- cpp/velox/compute/WholeStageResultIterator.cc
- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/execution/GlutenSQLAggregateFunctionSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/GlutenSQLAggregateFunctionSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/GlutenSQLAggregateFunctionSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/execution/GlutenSQLAggregateFunctionSuite.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
To align with Spark, https://github.com/facebookincubator/velox/pull/12566 introduced `spark.legacy_statistical_aggregate` configuration, which controls whether NULL or NaN is returned when dividing by zero. This PR enables this config if `spark.sql.legacy.statisticalAggregate` is set to true.
> [VL] Support Spark legacy statistical aggregation function behavior

- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/FlushableHashAggregateRule.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxAggregateFunctionsSuite.scala
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/config/VeloxConfig.h
(Fixes: \#8985)
1. Disable `FlushableHashAggregate` when aggregates contain `sum`/`avg` for floating types.
2. To control PartialAgg flush easily in unit tests, add a Velox configuration `s.g.s.c.b.v.maxPartialAggregationMemory` to set PartialAgg memory, which has higher priority than `s.g.s.c.b.v.maxPartialAggregationMemoryRatio`.
unit tests
> [VL] Disable FlushableHashAggreagte when aggregates contains sum/avg for floating type

- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenDriverEndpoint.scala
- backends-clickhouse/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala
This PR aims to add a comment to explain why the endpoint uses a single thread. We don't need to set thread count from SparkContext[1].  
[1] https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rpc/RpcEndpoint.scala#L166-L177
No need to add tests.
> [CH] Add a comment to explain why the endpoint uses a single thread

- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxLocalCacheSuite.scala
fix merge conflict on after #9274
pass GHA
> [VL] fix merge conflict on VeloxLocalCacheSuite

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/execution/CHHashJoinExecTransformer.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/EliminateDeduplicateAggregateWithAnyJoin.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/JoinAggregateToAggregateUnion.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/RewriteSortMergeJoinToHashJoinRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenEliminateJoinSuite.scala
> [GLUTEN-9267][CH] Fix a bug in `EliminateDeduplicateAggregateWithAnyJoin`

- backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
This PR is followup of the https://github.com/apache/incubator-gluten/pull/9109. It aims to disable spark ui for the VeloxUdfSuite.scala.
> [TESTS][FOLLOWUP] Disable spark ui in VeloxUdfSuite

- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarPartialProjectExec.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionUtils.scala
> [VL] Remove param original of ColumnarPartialProjectExec

- .github/workflows/velox_weekly.yml
- ep/build-velox/src/setup-centos7.sh
This issue was related to the recent pr #9207 which changes the script to use upstream Velox wget_and_untar function.
> [VL] Fix weekly build job on Centos 7

- backends-clickhouse/src/main/scala/org/apache/gluten/extension/CommonSubexpressionEliminateRule.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
> [GLUTEN-9178][CH] Fix cse in aggregate operator not working

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/GlutenFallbackReporter.scala
- gluten-ui/pom.xml
- gluten-ui/src/main/scala/org/apache/spark/sql/execution/ui/GlutenUIUtils.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/gluten/GlutenFallbackSuite.scala
Post events until both spark ui and gluten ui are enable. Prevents invalid gluten event post when the spark ui is not turned on
GA
> [CORE] Post events until both spark ui and gluten ui are enable

- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- shims/common/src/main/scala/org/apache/spark/sql/internal/SparkConfigUtil.scala
`spark.sql.extensions=org.apache.gluten.extension.GlutenSessionExtensions` should be set automatically when Spark driver started with Gluten. However if user explicitly sets it, unexpected errors will be caused. For example:
```
java.lang.UnsupportedOperationException: This operator doesn't support doTransform with SubstraitContext.
at org.apache.gluten.execution.TransformSupport.doTransform(WholeStageTransformer.scala:192)
at org.apache.gluten.execution.TransformSupport.doTransform$(WholeStageTransformer.scala:190)
at org.apache.gluten.execution.WholeStageTransformer.doTransform(WholeStageTransformer.scala:222)
at org.apache.gluten.execution.TransformSupport.$anonfun$transform$1(WholeStageTransformer.scala:185)
at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan. …
```
> [CORE] Correctly handle driver configurations when `spark.sql.extensions` is explicitly set for GlutenSessionExtensions

- .github/workflows/docker_image.yml
- cpp/CMakeLists.txt
- cpp/compile.sh
- cpp/velox/CMakeLists.txt
- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/config/VeloxConfig.h
- dev/builddeps-veloxbe.sh
- dev/docker/cudf/Dockerfile
- dev/start_cudf.sh
- docs/get-started/VeloxGPU.md
- ep/build-velox/src/build_velox.sh
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Enable this feature by compiling with `--enable_gpu`.
Now only support OrderBy operator.
Use this branch https://github.com/apache/incubator-gluten/tree/cudf
> [GLUTEN-8851][VL] feat: Support cudf

- docs/developers/HowTo.md
- docs/developers/NewToGluten.md
- docs/get-started/Velox.md
There are a few invalid links reported by markdown-link-check tool.
> [DOC] Fix broken links in documents

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHSuite.scala
- cpp-ch/local-engine/Parser/TypeParser.cpp
> [GLUTEN-9317][CH]Fix: duplicated column names in shuffle read

- tools/scripts/gen-function-support-docs.py
This PR aims to fix log path when parsing log in gen-function-support-docs.py.  
https://github.com/apache/incubator-gluten/blob/65ad57add72e665b4e07b2d994347c9881d9fc13/tools/scripts/log4j2.properties#L25
(Fixes: \#9329)
> [GLUTEN-9329][DOC] Fix log path when parsing log in gen-function-support-docs.py

- .github/workflows/velox_backend.yml
- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- backends-velox/src/test/java/org/apache/gluten/tags/SkipTest.java
- backends-velox/src/test/scala/org/apache/gluten/execution/DynamicOffHeapSizingSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/expression/VeloxUdfSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/fuzzer/RowToColumnarFuzzer.scala
- backends-velox/src/test/scala/org/apache/gluten/fuzzer/ShuffleWriterFuzzer.scala
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/DynamicOffHeapSizingMemoryTarget.java
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- shims/common/src/main/scala/org/apache/spark/sql/internal/SparkConfigUtil.scala
Previously the feature uses `total memory - free memory` as the on-heap occupied size, which was wrong. The free memory is unused by JVM but not yet returned to the OS. The heap occupation from operating system is always the total JVM memory.
The patch corrects the calculation by using the total JVM memory instead.
Related:
https://github.com/apache/incubator-gluten/pull/5439
https://github.com/apache/incubator-gluten/issues/9276
https://github.com/apache/incubator-gluten/discussions/8600
With some minor code cleanups in passing.
> [VL] Count total JVM memory as the on-heap portion for the off-heap sizing feature

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxStringFunctionsSuite.scala
- docs/velox-backend-scalar-function-support.md
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
- tools/scripts/gen-function-support-docs.py
This PR aims to add runtime replaceable scalar function map to support replacement expression in doc.
(Fixes: \#9300)
> [GLUTEN-9300][DOC] Support replacement expression in gen-function-support-docs

- cpp-ch/local-engine/libch-hide-jemalloc.map
- cpp-ch/local-engine/libch.map
- cpp-ch/local-engine/local_engine_jni.cpp
Remove `JNI_OnUnload`, since it is no longer needed.  using this PR to run gluten-dev ci for testing java-17
(Fixes: \#9239)
Using existed UTs
> [GLUTEN-9239][CH] [PART-1] Support Java-17 Rmove `JNI_OnUnload`

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxScanSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/tests/Substrait2VeloxPlanConversionTest.cc
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/hive/execution/GlutenHiveSQLQuerySuite.scala
Velox supports binary as string of parquet after https://github.com/facebookincubator/velox/pull/10399, we need to pass hive columns type to HiveTableHandle
Fixes: #7652
> [GLUTEN-7652][VL] Support binary as string

- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaMergetreeDeletionVectorSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseTPCHAbstractSuite.scala
- cpp-ch/local-engine/Parser/RelParsers/MergeTreeRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/MergeTreeRelParser.h
- cpp-ch/local-engine/Storages/SubstraitSource/FormatFile.h
> [Gluten-9334][CH] Support delta metadata column `file_path` and `row_index` for mergetree

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHIteratorApi.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseExcelFormatSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenClickHouseWholeStageTransformerSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/cache/GlutenClickHouseCacheBaseTestSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/cache/GlutenClickHouseHDFSSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/cache/GlutenClickHouseMINIOSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeCacheDataSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnHDFSSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnHDFSWithRocksDBMetaSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergeTreeWriteOnS3Suite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/mergetree/GlutenClickHouseMergetreeWriteStatsSuite.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/utils/CacheTestHelper.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/utils/HDFSTestHelper.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/utils/MinioTestHelper.scala
- cpp-ch/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp
The endpoint of  Minio may not start with `https://`,  so let's support `http://` endpoint
(Fixes: \#6867)
Introduce  `GlutenClickHouseCacheBaseTestSuite` and let  `GlutenClickHouseMINIOSuite` and `GlutenClickHouseHDFSSuite` inherit from it.
> [GLUTEN-6867][CH] Fix Bug that cann't read file on minio

- backends-velox/src/main/scala/org/apache/gluten/execution/ColumnarPartialProjectExec.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionMappings.scala
The `ColumnaPartialProject` can also supports build-in functions, especially the blacklist expressions.
One typical scenario is regexp. The native regexp lib `re2` is much slower than Java regexp lib, and also has some semantic difference with Java lib.
Take a simple sql in our production as an example
```
SELECT  p_date,
cast(id AS BIGINT) AS creative_id,
regexp_replace(DATA, '||    ', '') AS tmp
FROM    test_table
WHERE   p_date='20250227'
```
| Test  | Cost |
|--------|--------|
| Partial Project Fallback | 1284h |
| Whole Project Fallback | 1389h |
| Native (No Fallback) | 3384h |
In this PR, try to use `ColumnarPartialProject` to handle the blacklist expressions.
(Fixes: \#9313)
more UT
> [GLUTEN-9313][VL] ColumnarPartialProject supports built-in but blacklisted function

- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/DynamicOffHeapSizingMemoryTarget.java
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/MemoryTargets.java
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/spark/memory/SparkMemoryUtil.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Dynamic off-heap sizing was introduced in https://github.com/apache/incubator-gluten/pull/5439. The PR does a few of improvements against the implementation.
1. Move pre-configuration code from `GlutenConfig.scala` to `DynamicOffHeapSizingMemoryTarget`.
2. Avoid chaining `DynamicOffHeapSizingMemoryTarget` with Spark consumer since it basically never triggers spills because of its design. The target will manage OOMs by itself.
3. Do not set off-heap size automatically when dynamic off-heap sizing is enabled. All the memory allocation is from a counter that indicates the remaining unused size from JVM on-heap memory cap.
4. Other minor improvements.
> [VL] Move pre-configuration code of dynamic off-heap sizing to its own place

- cpp/core/jni/JniWrapper.cc
- cpp/core/memory/MemoryAllocator.cc
- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/LocalPartitionWriter.h
- cpp/core/shuffle/Options.h
- cpp/core/shuffle/PartitionWriter.h
- cpp/core/shuffle/Payload.cc
- cpp/core/shuffle/Payload.h
- cpp/core/shuffle/Spill.cc
- cpp/core/shuffle/Spill.h
- cpp/core/shuffle/Utils.h
- cpp/core/shuffle/rss/RssPartitionWriter.cc
- cpp/core/shuffle/rss/RssPartitionWriter.h
- cpp/velox/benchmarks/GenericBenchmark.cc
- cpp/velox/shuffle/VeloxHashShuffleWriter.cc
- cpp/velox/shuffle/VeloxShuffleReader.cc
- cpp/velox/shuffle/VeloxShuffleReader.h
- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/shuffle/VeloxSortShuffleWriter.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
- cpp/velox/utils/tests/VeloxShuffleWriterTestBase.h
For shuffle writer tasks with heavily spill, streaming compression should provide better compression ratio. Currently, spilled data is compressed before writing to the output stream. This patch modifies the compression logic for sort-based shuffle, removes that compression and uses the compressed output stream to do the work.
> [GLUTEN-9163][VL] Use stream de/compressor in sort-based shuffle

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- shims/common/src/main/scala/org/apache/gluten/expression/ExpressionNames.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
This PR aims to use the `ArrayRemoveNullFunction` in Velox to implement the Spark `array_compact` function.  
(Fixes: \#9287)
unit tests
> [GLUTEN-9287][VL] Enable array_compact function for Spark 3.4+

- gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenTestsTrait.scala
- GlutenCheckExpression currently falls back to internal row for certain complex/unsupported types.
- As discussed in the PR, this is running Vanilla Spark and does not mean anything for Gluten.
- Removing the same
- Unit Tests
> [GLUTEN-9095][UT] Remove Vanilla Spark InternalRow based checkEvaluation

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Port https://github.com/apache/spark/pull/50327 to make max broadcast table size configurable.
Also, remove our hardcoded ones and make some custom spark build happy
> [CORE] Make max broadcast table size configurable

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/DateTimeExpressionsTransformer.scala
> [GLUTEN-7589][VL] Support date_trunc function

- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- FAILFAST parsing mode is flaky and excluded from most settings. However still part of 3.5 GlutenCSVv1Suite.
- Excluding the same to prevent build failures
- Existing UT
> [GLUTEN][UT] Disable flaky UT from GlutenCSVv1Suite

- gluten-substrait/src/main/scala/org/apache/gluten/utils/PullOutProjectHelper.scala
- gluten-substrait/src/test/scala/org/apache/spark/sql/GlutenQueryTest.scala
- gluten-ut/test/src/test/scala/org/apache/gluten/extension/GlutenExtensionRewriteRuleSuite.scala
Pulling out expression from `PartialMerge` aggregate function results in invalid reference binding in `ProjectExecTransformer ` when there are `merge_sum` and `partial_count` aggreagate function with non-attribute expression in same `HashAggregate`.
Fixes issue: https://github.com/apache/incubator-gluten/issues/9279
UnitTest
> [GLUTEN-9279] Not pulling out expression from PartialMerge aggregate function to avoid invalid reference binding in ProjectExecTransformer

- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/sql/execution/GlutenDeltaExpressionSuite.scala
- backends-clickhouse/src-delta/main/scala/org/apache/gluten/component/CHDeltaComponent.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHMetricsApi.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/FilterMetricsUpdater.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/MetricsUtil.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/metrics/ProjectMetricsUpdater.scala
- cpp-ch/local-engine/Parser/RelParsers/FilterRelParser.cpp
- gluten-delta/src-delta-32/main/scala/org/apache/gluten/execution/DeltaProjectExecTransformer.scala
> [Gluten-8792][CH] Support delta project incrementMetric expr

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
Minor refactor config use in ColumnarCachedBatchSerialize
Existed test.
> [GLUTEN][VL] Minor refactor config use in ColumnarCachedBatchSerialize

- .github/workflows/build_bundle_package.yml
Improve build bundle package workflow:
+ Add repo ref parameter
+ Upgrade upload-artifact version to v4 (v3 has been deprecated: Error: Missing download info for actions/upload-artifact@v3)
+ Upgrade download-artifact version to v4 (v3 has been deprecated: Missing download info for actions/download-artifact@v3)
https://github.com/wForget/gluten/actions/runs/14631773617
> [VL][INFRA] Improve build bundle package workflow

- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
- We now support all backends for ColumnarCollectLimit.
- Remove unused `isColumnarLimitExecSupported` in shim layer.
- Existing UTs
> [VL] Remove unused checks for CollectLimit support

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
After https://github.com/apache/incubator-gluten/pull/9230, we are adding `ColumnarToRowRemovalGuard` which makes a `vanilla columnar + C2R` plan go around Spark's C2R removal code `InMemoryRelation#convertToColumnarIfPossible`, so the previous hard-coded configuration check is no longer needed.
Tested by existing UTs in `VeloxColumnarCacheSuite`.
Related: https://github.com/apache/incubator-gluten/pull/9408
> [VL] Remove unused logic in ColumnarCachedBatchSerializer#supportsColumnarInput

- dev/package-vcpkg.sh
- dev/vcpkg/env.sh
- dev/vcpkg/triplets/arm64-linux-neon.cmake
fixed #8981
And fixed “Environment variable VCPKG_FORCE_SYSTEM_BINARIES” warning
You only need to execute package-vcpkg.sh to complete the compilation of the corresponding platform
in arm platform， you can execute the package-vcpkg.sh like this:
./dev/package-vcpkage.sh
To execute package-vcpkg.sh to compile the dependency libraries in vcpkg.json and vcpkg-tool。
"Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm, s390x, ppc64le and riscv platforms" is not displayed.
i build it on my local pc（cpu：m1pro ； centos7 docker）. i will show the logs :
> [GLUTEN-8981][VL] Add vcpkg triplet for building Gluten on arm

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/test/scala/org/apache/gluten/execution/GlutenFunctionValidateSuite.scala
The `enable_aggregate_if_to_filter` rule may cause diff result for sum if.
> [CH] Change enable_aggregate_if_to_filter to fasle

- cpp/velox/memory/VeloxMemoryManager.cc
When allocationChanged fails in growCapacity, we should free reclaimed bytes
Fixes: #9383
After this repair, the failed job of #9383 succeeded
> [GLUTEN-9383][VL] Fix leak when growing capacity

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/offload/OffloadSingleNodeRules.scala
- In #8914 we moved to post transform rules to allow correct C2C transition for CollectLimit.
- With this change we don't need to covert the plan through offload rules, since post transform handles it.
- Removing the same.
- Existing UTs
> [VL] Remove CollectLimit dependency from Offload Rules

- ep/build-velox/src/setup-centos7.sh
Using wget_and_untar from upstream that accepts options for download tools
> [VL] Replace wget w/ wget_and_untar to make dependency download more reliable

- gluten-hudi/src/main/scala/org/apache/gluten/execution/HudiScanTransformer.scala
- gluten-hudi/src/main/scala/org/apache/gluten/execution/OffloadHudiScan.scala
When file format is `NewHoodieParquetFileFormat`, the condition was matched and the plan was passed to velox for execution. But the result wasn't correct - merging wasn't performed, only parquet records were returned.
We should fallback to spark for `NewHoodieParquetFileFormat`
Manual tests.
> [VL] Fix Hudi scan fallback

- cpp/core/utils/ObjectStore.cc
- cpp/core/utils/ObjectStore.h
The change is ported from https://github.com/velox4j/velox4j/pull/152.
The log message is like:
```
I20250428 16:15:48.877297 446254 ObjectStore.cc:34] Unclosed object [Store ID: 4, Resource handle ID: 4, Description: i] is found when object store is closing. Gluten will destroy it automatically but it's recommended to manually close the object through the Java closing API after use, to minimize peak memory pressure of the application.
```
The log is on verbose level 2.
In the future, addressing the unclosed objects in code following the messages in logs may reduce the peak off-heap memory usage of Gluten.
> [VL] Add additional logging for unclosed objects when the native runtime is being destroyed

- .github/workflows/docker_image.yml
Adding "1.4" to docker image name used in branch-1.4, so the changes in main branch does not impact the branch-1.4
A follow-up patch will modify the CI to use the right docker
> [branch-1.4][VL] Fix docker image name for 1.4 branch

- cpp/velox/compute/VeloxBackend.cc
- cpp/velox/config/VeloxConfig.h
- shims/common/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
This config is used to print cudf operator information.
```
Calling CudfHashJoinBridgeTranslator::toOperatorSupplierCalling CudfHashJoinBridgeTranslator::toOperatorSupplier
Calling CudfHashJoinBridgeTranslator::toJoinBridge
Calling CudfHashJoinBridgeTranslator::toJoinBridge
Calling CudfHashJoinBridgeTranslator::toJoinBridge
Calling CudfHashJoinBridgeTranslator::toJoinBridge
Operators before adapting for cuDF: count [2]
Operator: ID 0: TableScan[0] 0
Operator: ID 1: FilterProject[1] 1
Operators after adapting for cuDF: count [4]
Operator: ID 0: TableScan[0] 0
Operator: ID 1: CudfFromVelox[1-from-velox] 1
Operator: ID 2: CudfFilterProject[1] 2
Operator: ID 3: CudfToVelox[1-to-velox] 3
```
> [GLUTEN-8851][VL] Use separate debug config for cudf

- cpp/core/utils/ObjectStore.cc
- cpp/core/utils/ObjectStore.h
- Following up on #9455
- Added ObjectDebugInfo which can hold other attributes for the object (such as size) and used for logging.
- Existing UTs
> [VL] Support ObjectDebugInfo in ObjectStore during destruction of native runtime

- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
- gluten-iceberg/src/test/scala/org/apache/gluten/execution/IcebergSuite.scala
Properly sanitizes iceberg columns with special characters so it can be read.
(Fixes: \#9481)
unit tests
> [GLUTEN-9481][ICEBERG] Fix issue where iceberg columns where not properly being sanitized.

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Suite.scala
- tools/gluten-it/common/src/main/scala/org/apache/spark/sql/SparkSessionSwitcher.scala
Make the configuration settings override the one before it respectively:
1. Default configurations (The hard coded ones set by `addDefaultConf`)
2. Session configuration (The sessions configurations written in `Constants.scala`)
3. Extra configuration (Extra configurations set by `--extra-conf`)
> [VL] Gluten-it: Minor refactor on configuration priorities

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
This PR aims to enable concat function with array datatype for spark.
(Fixes: \#9496)
New unit test.
> [GLUTEN-9496][VL] Enable concat function with array datatype for spark

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
This PR aims to remove unused datatype check code from concat function, as this function only supports string / binary / array type in apache spark[1].  
[1] https://github.com/apache/spark/blob/v3.2.0/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/collectionOperations.scala#L2195
(Fixes: \#9502)
> [GLUTEN-9502][VL] Remove useless datatype check for concat function

- backends-velox/src/test/scala/org/apache/gluten/execution/ScalarFunctionsValidateSuite.scala
This PR aims to remove repeat function test from ScalarFunctionValidateSuite.
(Fixes: \#9512)
> [GLUTEN-9512][VL] Remove repeat function test from ScalarFunctionValidateSuite

- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelation.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala
When `ColumnarBuildSideRelation\UnsafeColumnarBuildSideRelation` calls `NativeColumnarToRowJniWrapper#nativeColumnarToRowConvert`, the `c2rId` and `batchHandle` parameters are passed in the wrong order.
(Fixes: \#9435)
> [GLUTEN-9435][VL] Fix [Unsafe]ColumnarBuildSideRelation not found ResourceHandle in resource map

- dev/build_arrow.sh
#9483 has removed the dependency on arrow parquet.
> [GLUTEN-9468][VL] Follow up: Remove parquet-arrow cpp build

- gluten-substrait/src/main/scala/org/apache/gluten/utils/InputPartitionsUtil.scala
This PR ports the changes from [SPARK-32985][SQL] to decouple bucket scan and bucket filter pruning into the Apache Gluten project.
(Fixes: \#8877)
Manual tests.
```sql
SELECT * FROM bucket_table WHERE bucket_column = 2243296260;
```
Before:
After:
> [GLUTEN-8877] Port [SPARK-32985][SQL] Decouple bucket scan and bucket filter pruning

- backends-velox/src/test/scala/org/apache/gluten/functions/ScalarFunctionsValidateSuite.scala
* The temporary logic to exclude specific tests (isnull function, null input for array_size, Test make_ym_interval function) has been removed as the underlying incompatibilities have been resolved (see https://github.com/apache/incubator-gluten/issues/7600).   
* These tests are now executed normally, improving test coverage and alignment with expected behavior.  
(Fixes: \#9557)
> [GLUTEN-9557][VL] Remove outdated test exclusion logic

- dev/vcpkg/ports/libelf/portfile.cmake
- `https://git.savannah.gnu.org/cgit/config.git/plain/config.guess` is no longer available causing builds to fail with vcpkg.
- Updated to gitweb interface which is correctly serving the files.
- Build succeed / CI
```
wget 'https://git.savannah.gnu.org/cgit/config.git/plain/config.guess'                      
--2025-05-08 02:22:32--  https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
Resolving git.savannah.gnu.org (git.savannah.gnu.org)... 209.51.188.168, 2001:470:142::168
Connecting to git.savannah.gnu.org (git.savannah.gnu.org)|209.51.188.168|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2025-05-08 02:22:33 ERROR 404: Not Found.
wget 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'  
--2025-05-08 02:22:23-- …
```
> [GLUTEN-9551][VL] Fix build failure due to libelf vcpkg unavailable files

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/BroadcastUtils.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
- cpp/core/jni/JniWrapper.cc
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ColumnarBatchSerializeResult.java
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ColumnarBatchSerializerJniWrapper.java
Serialize ColumnarBatch one by one when broadcasting
Fixes: #9475
After this fix, the original abnormal job will no longer have offheap OOM.
> [GLUTEN-9475][VL] Serialize ColumnarBatch one by one to reduce memory footprint when broadcasting

- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- ep/build-velox/src/build_velox.sh
- gluten-ut/spark32/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark34/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/catalyst/expressions/GlutenCastSuite.scala
- Add support for array integral to bool casts.
- Enabled the same in validator for array types.
- Minor refactor to the existing code for validations.
- New unit tests added, relying on existing Spark UTs
> [GLUTEN-9392][VL] Support integral to boolean array casts

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Suite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/metrics/PlanMetric.scala
Add more information to the test report when `--sql-metrics=execution-time` is specified.
Before:
```
Top 10 plan nodes that took longest time to execute: 
| Query  | Node ID |                       Node Name                        |            Execution Time (ns)            |
|--------|---------|--------------------------------------------------------|-------------------------------------------|
|  q1.sql|      864|                   FlushableHashAggregateExecTransformer|            [time of aggregation] 184268837|
|  q1.sql|      859|                                  ProjectExecTransformer|                [time of project] 141018941|
|  q1.sql|      794|  ScanTransformer parquet spark_catalog.default.lineitem|                    [time of scan] 12198000|
|  q1.sql|      870| …
```
> [VL] Gluten-it: Enrich test report with --sql-metrics=execution-time

- .github/workflows/docker_image.yml
Fix the error below, due to the name pattern is not matched.
```
An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/_temp/digests'. No such file or directory
```
https://github.com/apache/incubator-gluten/actions/runs/14975292026/job/42089276009
> [branch-1.4][VL] Fix docker build

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHBackend.scala
- backends-clickhouse/src/main/scala/org/apache/gluten/extension/ConvertWindowToAggregate.scala
- cpp-ch/local-engine/Parser/RelParsers/GroupLimitRelParser.cpp
AggregateDescription.parameters is not set in AggregateGroupLimitRelParser. It will cause the deserialization of intermediate aggregate data to fail.
Fixes: #9631 
manual tests
> [GLUTEN-9631][CH] Fix: `AggregateDescription.parameters` is not set in `AggregateGroupLimitRelParser`

- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaMergeTreeDeletionVectorSuite.scala
- backends-clickhouse/src-delta-32/test/scala/org/apache/spark/gluten/delta/GlutenDeltaParquetDeletionVectorSuite.scala
- cpp-ch/local-engine/Parser/RelParsers/MergeTreeRelParser.cpp
Fix incorrect columns order when deleting from the mergetree table with the delta dv： the error is below:
```
Cannot parse string 'R' as Int64: syntax error at begin of string. Note: there are toInt64OrZero and toInt64OrNull functions,
which returns zero/NULL instead of throwing exception.: while converting source column `tuple(file_path,l_returnflag)`
to destination column `tuple(file_path,l_returnflag)`: while executing
'FUNCTION _CAST(tuple(file_path,l_returnflag) :: 5, Tuple(file_path String, row_index Int64) :: 4)
-> tuple(file_path,l_returnflag) Tuple(file_path String, row_index Int64) : 1'
```
Close #9660.
(Fixes: #9660)
(If this patch involves UI changes, please attach a screenshot; …
> [GLUTEN-9660][CH]Fix incorrect columns order when deleting from the mergetree table with the delta dv

- backends-velox/src/main/scala/org/apache/gluten/execution/VeloxBroadcastNestedLoopJoinExecTransformer.scala
- cpp/velox/substrait/SubstraitToVeloxPlan.cc
- cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BroadcastNestedLoopJoinExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/utils/SubstraitUtil.scala
- gluten-ut/spark33/src/test/scala/org/apache/spark/sql/execution/joins/GlutenExistenceJoinSuite.scala
- Existence join falls back for broadcast nested loop join.
- Added support for the same in Velox as leftSemiProject in the cross join/nested loop join.
- Enabled existence join for conversion. https://github.com/facebookincubator/velox/pull/12172
- Upstream PR is now merged and available through https://github.com/apache/incubator-gluten/pull/9587.
- Existing + New UTs
> [GLUTEN-8616] [VL] Add support for Existence Join for broadcast nested loop join

- backends-clickhouse/src/main/scala/org/apache/gluten/columnarbatch/CHBatch.scala
- backends-velox/src/main/scala/org/apache/gluten/columnarbatch/VeloxBatch.scala
- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/enumerated/planner/VeloxRasSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/extension/columnar/transition/VeloxTransitionSuite.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/GlutenColumnarRule.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/enumerated/planner/plan/GlutenPlanModel.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/ConventionReq.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transition.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/package.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/RowToColumnarExecBase.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/MiscColumnarRulesSuite.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuite.scala
- gluten-substrait/src/test/scala/org/apache/gluten/extension/columnar/transition/TransitionSuiteBase.scala
In preparation for https://github.com/apache/incubator-gluten/issues/9666, the PR extends the transition planner to support alternative row types than `VanillaRow`, so in the future we could make the query planner automatically add transitions between columnar batch types to `FakeRow`s.
> [GLUTEN-9666][VL] Extend transition planner to support multiple row types

- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeBytesBufferArray.scala
(Fixes: #9691)
The type of `bytesBufferOffset`  in UnsafeBytesBufferArray.scala is Array[Int], while when `bytesBufferLengths ` are all large number, will cause the element in `bytesBufferOffset`  overflowed the Int.max_value, and finally lead to jvm coredump in other operation like 
``` scala 
Platform.copyMemory(
bytesBuffer,
Platform.BYTE_ARRAY_OFFSET,
longArray.getBaseObject,
longArray.getBaseOffset + bytesBufferOffset(index),
bytesBufferLengths(index))
```
Manually test in our production environment
> [GLUTEN-9691][VL]Fix driver core dump when broadcast too large when UnsafeColumnarBuildSideRelation enabled

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/CollapseProjectExecTransformer.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/extension/GlutenCollapseProjectExecTransformerSuite.scala
In Microsoft we have a set of internal tests that check logical links in final plans. Recently, when I was trying to turn on RAS by default, I saw an assertion failure due to missing logical link in a ProjectExecTransformer. After some investigation I found the problem:
`CollapseProjectExecTransformer` rule collapses two projects,
```
p1
| p2
```
into a single ProjectExecTransformer. Spark's `transformUpWithPruning` method would then [copy](https://github.com/apache/spark/blob/b84d3e6cca95470d3c26e76861b31308ec236e14/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/trees/TreeNode.scala#L537-L543) the tags from `p1` to the new collapsed project.
However, if `p1` has no tags but `p2` has, then the collapsed project would lose those tags. This PR fixes this problem - and now the …
> [VL] Fix missing tag after CollapseProjectExecTransformer rule

- cpp/core/jni/JniCommon.h
- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
Variable length array is not part of the c++ standard. We should avoid using it in the code.
```
/Users/rong/workspace/github/apache/gluten/cpp/core/jni/JniCommon.h:39:15: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
39 |   char buffer[clen + 1];
|               ^~~~~~~~
/Users/rong/workspace/github/apache/gluten/cpp/core/jni/JniCommon.h:39:15: note: read of non-const variable 'clen' is not allowed in a constant expression
/Users/rong/workspace/github/apache/gluten/cpp/core/jni/JniCommon.h:36:17: note: declared here
36 |   int32_t jlen, clen;
|                 ^
1 error generated.
```
```
/Users/rong/workspace/github/apache/gluten/cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc:109:26: error: variable length arrays in C++ are a …
```
> [VL] Fix VLA error when compiling with apple clang

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/test/java/org/apache/gluten/backendsapi/VeloxListenerApiTest.java
At present, velox conf has never been used on executor start, resulting in the conf inside `VeloxConfig` not being registered.
For example, if we set `spark.gluten.sql.columnar.backend.velox.filePreloadThreshold=50MB`
Then on the executor side, the following error will be reported
```
Caused by: org.apache.gluten.exception.GlutenException: Exception: VeloxRuntimeError
Error Code: INVALID_STATE
Reason: Operator::getOutput failed for [operator: TableScan, plan node ID: 0]: Non-whitespace character found after end of conversion: "MB"
Function: operator()
File: /velox/velox/exec/Driver.cpp
Line: 616
Stack trace:
```
(If this patch involves UI changes, please …
> [VL] Manually register velox conf on executor start

- cpp/velox/operators/serializer/VeloxColumnarToRowConverter.cc
- cpp/velox/operators/serializer/VeloxRowToColumnarConverter.cc
- ep/build-velox/src/get_velox.sh
```
db8a1df0c new: Added type validation for intermediate and output vectors (#13322)
b3955982b refactor: Setup scripts (#12321)
b8fd936c3 fix: Incorrect filter result when the range is outside of old type during schema evolution (#13459)
1aae6a028 feat: Add ColumnReaderOptions (#12840)
78578792e fix: Add alias substring for SubstrFunction (#13220)
8b2ff7195 refactor: Drop UnsafeRowDeserializer old API (#12817)
c6f4d283c fix(json): Bug with duplicate keys leading to incorrect writes (#13445)
bbf1f3410 feat: Create internal TableEvolutionFuzzer and add internal Nimble support during runs (#13441)
984d561b6 feat: Register Spark sqrt function (#13416)
d870492c0 refactor: Move the parquet reader and writer factory register into InsertTest (#13432)
845b7252a feat(functions): Support named rows …
```
> [GLUTEN-6887][VL] Daily Update Velox Version (2025_05_24)

- cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskS3.cpp
- cpp-ch/local-engine/Disks/ObjectStorages/GlutenDiskS3.h
(Fixes: #6609)
Removed the custom implementation of the `readFile` method from the `GlutenDiskS3` class as it's no longer required for the S3 compact version.  
Previously, this override forced the `remote_fs_method` to use `RemoteFSReadMethod::read` since threadpool reading wasn't supported for the S3 compact version. Now, we can simply rely on the parent `DiskObjectStorage` implementation.
This change simplifies the codebase and reduces maintenance overhead without affecting functionality
use existed uts
> [GLUTEN-6609][CH] Remove unnecessary readFile override in GlutenDiskS3

- cpp/velox/shuffle/VeloxSortShuffleWriter.cc
- cpp/velox/tests/VeloxShuffleWriterTest.cc
Fixed the issue reported [here](https://github.com/apache/incubator-gluten/pull/9278#issuecomment-2901970336)
> [GLUTEN-9163][VL][FOLLOWUP] Fix segfault triggered by fixed-width inputs

- gluten-substrait/src/test/scala/org/apache/spark/sql/WithQueryPlanListener.scala
Following: #9802 
Scala 2.12 doesn't copy a mutable seq when #toSeq is called so the listeners will not be invoked.
The patch quickly fixes the issue.
> [VL] Following #9802, fix the plan listener not working for Scala 2.12

- package/pom.xml
Exclude `com.google.code.findbugs:jsr305` from Gluten shade package. This is because Spark jars already include this jar: `${SPARK_HOME}/jars/jsr305-3.0.0.jar`.
(Fixes: #9823)
Manual tests:
Before| After
-- | --
> [GLUTEN-9823] Exclude jsr305 from Gluten shaded jar to reduce redundancy

- backends-velox/src/test/scala/org/apache/gluten/functions/DateFunctionsValidateSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/functions/JsonFunctionsValidateSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/functions/MathFunctionsValidateSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/functions/ScalarFunctionsValidateSuite.scala
Follow-up fix for this comment:
https://github.com/apache/incubator-gluten/pull/9782#discussion_r2113247329
Remove "Test" from test name if not very necessary. Keep "function" in test name only if it help avoid ambiguity.
> [VL] Minor fix: simplify a few function tests' verbose names

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxBackend.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala
Fix https://github.com/apache/incubator-gluten/issues/9382
Existing fallback unit tests
> [GLUTEN-9382][VL]Support bucket write with non partition table

- .github/workflows/nightly_sync.yml
fix rsync-development version to 5.2 
pass GHA
> [GLUTEN-9860] followup: Fix rsync version to 5.2

- .github/workflows/nightly_sync.yml
this patch adds the trailing '/' for the remote path. 
example from opendal: 
https://github.com/apache/opendal/blob/main/.github/workflows/docs.yml#L715
pass GHA
> [GLUTEN-9860] followup: Fix rsync remote path

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala
- backends-velox/src/main/scala/org/apache/gluten/utils/SharedLibraryLoader.scala
- gluten-core/src/main/scala/org/apache/gluten/GlutenPlugin.scala
- gluten-core/src/main/scala/org/apache/spark/sql/internal/SparkConfigUtil.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/UDFMappings.scala
#9876 causes [CH UT failed](https://opencicd.kyligence.com/blue/organizations/jenkins/gluten%2Fgluten-ci/detail/gluten-ci/16353/pipeline).
```
[2025-06-07T02:42:07.376Z] [ERROR] org.apache.gluten.execution.iceberg.TestPositionDeletesTableGluten -- Time elapsed: 8.793 s <<< ERROR!
[2025-06-07T02:42:07.376Z] java.lang.NumberFormatException: For input string: "2147483648b"
[2025-06-07T02:42:07.376Z] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[2025-06-07T02:42:07.376Z] 	at java.base/java.lang.Long.parseLong(Long.java:711)
[2025-06-07T02:42:07.376Z] 	at java.base/java.lang.Long.parseLong(Long.java:836)
[2025-06-07T02:42:07.376Z] 	at scala.collection.StringOps$.toLong$extension(StringOps.scala:928)
[2025-06-07T02:42:07.376Z] 	at …
```
> Revert "Add RichSparkConf to simplify the interoperations with gluten config entries (#9876)

- backends-velox/src/main/scala/org/apache/gluten/execution/VeloxBroadcastNestedLoopJoinExecTransformer.scala
https://github.com/facebookincubator/velox/pull/10651 ensure Nested Loop Join output follows probe order.
Adding output ordering can reduce unnecessary sort. For example:
```
spark.range(10).write.parquet("tmp/t1")
spark.range(10).write.parquet("tmp/t2")
spark.range(100).write.parquet("tmp/t3")
spark.range(10).write.parquet("tmp/t4")
spark.read.parquet("tmp/t1").createOrReplaceTempView("t1")
spark.read.parquet("tmp/t2").createOrReplaceTempView("t2")
spark.read.parquet("tmp/t3").createOrReplaceTempView("t3")
spark.read.parquet("tmp/t4").createOrReplaceTempView("t4")
sql("set spark.gluten.sql.columnar.forceShuffledHashJoin=false")
val query = """
|select /*+ MERGE(tt2) */ tt2.* from
| (select tt1.* from
| (select /*+ MERGE(t1) */ t1.* from
|  t1 left join t2 on t1.id = t2.id) tt1
|   left …
```
> [VL] Add outputOrdering for VeloxBroadcastNestedLoopJoinExecTransformer

- backends-velox/src-uniffle/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java
Reopen #6270, remove incBytesWritten in VeloxUniffleColumnarShuffleWriter to avoid double counting of shuffle bytesWritten
Fixes: #6269
Before this change:
> [GLUTEN-6269][VL][UNIFFLE] Remove incBytesWritten in VeloxUniffleColumnarShuffleWriter

- backends-velox/src/test/scala/org/apache/gluten/functions/ScalarFunctionsValidateSuite.scala
- gluten-substrait/src/main/java/org/apache/gluten/substrait/expression/ExpressionBuilder.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/expression/ListLiteralNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/expression/MapLiteralNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/BinaryTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/BooleanTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/DateTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/DecimalTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FP32TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FP64TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FixedBinaryTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/FixedCharTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I16TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I32TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I64TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/I8TypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/IntervalYearTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/ListNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/MapNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/NothingNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/StringTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/StructNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/TimestampTypeNode.java
- gluten-substrait/src/main/java/org/apache/gluten/substrait/type/TypeNode.java
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ConverterUtils.scala
Fix fallback sql
```
SELECT map_from_arrays(sequence(1, 5),sequence(1, 5)), string_column from t
```
```
java.lang.UnsupportedOperationException: Not supported on UnsafeArrayData.
at org.apache.spark.sql.catalyst.expressions.UnsafeArrayData.array(UnsafeArrayData.java:103)
at org.apache.gluten.substrait.expression.MapLiteralNode.updateLiteralBuilder(MapLiteralNode.java:34)
at org.apache.gluten.substrait.expression.MapLiteralNode.updateLiteralBuilder(MapLiteralNode.java:27)
at org.apache.gluten.substrait.expression.LiteralNodeWithValue.getLiteral(LiteralNodeWithValue.java:39)
at org.apache.gluten.substrait.expression.LiteralNode.toProtobuf(LiteralNode.java:41)
at org.apache.gluten.substrait.rel.ProjectRelNode.toProtobuf(ProjectRelNode.java:72)
at …
```
> [CORE][VL] Fix fallback for spark literal unsafe map data as input

- tools/workload/benchmark_velox/analysis/requirements.txt
tools/workload/benchmark_velox/analysis/requirements.txt b/tools/workload/benchmark_velox/analysis/requirements.txt 
(Fixes: #9952)
Mostly just creating a fresh virtualenv for 3 different Python versions (3.10, 3.11, 3.12) and making sure that pip can install this requirements file without any issues and using no cached versions.
> [GLUTEN-9952][VL] Python Security updates June 2025

- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Constants.scala
Fix
```
04:59:10.749 [task-result-getter-2] WARN  org.apache.spark.scheduler.TaskSetManager - Lost task 9.0 in stage 0.0 (TID 9) (43689e113b67 executor driver): scala.MatchError: 37 (of class scala.math.BigDecimal)
at org.apache.gluten.integration.Constants$$anon$5.modValue(Constants.scala:168)
at org.apache.gluten.integration.h.TpchDataGen.$anonfun$generate$4(TpchDataGen.scala:318)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
at scala.collection.TraversableLike.map(TraversableLike.scala:286)
at …
```
> [CORE] Minor: Fix gluten-it decimal as double decimal match

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicTransform.scala
- gluten-delta/src/test/scala/org/apache/gluten/execution/DeltaSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/enumerated/RasOffload.scala
When a Delta scan falls back, the reported reason is incorrect—please see below.
```
== Fallback Summary ==
(1) Scan parquet XX: Unsupported file format UnknownFormat.; Unsupported file format UnknownFormat.
```
UT.
> [VL] Fix FallbackTags for Delta ops

- cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc
There’s no need to create the IndexRange for every row.
> [VL] Refactor IndexRange usage in serializeColumnarBatches

- cpp/velox/memory/VeloxMemoryManager.cc
Address https://github.com/apache/incubator-gluten/pull/10000#discussion_r2156567040
after this:
```
I20250624 19:40:35.823493 1133374 VeloxMemoryManager.cc:266] Shrink[root/root]: Trying to shrink 43201331 bytes of data...
I20250624 19:40:35.823499 1133374 VeloxMemoryManager.cc:267] Shrink[root/root]: Pool has reserved 1635399552/1663041536/1663041536/9223372036854775807 bytes.
I20250624 19:40:35.823580 1133374 VeloxMemoryManager.cc:273] Shrink[root/root]: Velox memory usage stats:
Shrink[root/root]: +- root/root (used: 1.52GB, peak: 1.59GB)
Shrink[root/root]:    +- task.Gluten_Stage_5_TID_9419_VTID_83 (used: 1.52GB, peak: 1.59GB)
Shrink[root/root]:       +- node.2 (used: 0B, peak: 0B)
Shrink[root/root]:          +- op.2.1.0.ValueStream (used: 0B, peak: 0B)
Shrink[root/root]:       +- …
```
> [GLUTEN-9994][VL][FOLLOWUP] Use stringstream to construct velox memory usage stats log

- backends-velox/src/main/scala/org/apache/gluten/expression/VeloxBloomFilterMightContain.scala
- gluten-core/src/main/scala/org/apache/gluten/execution/GlutenExpression.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ScanTransformerFactory.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/clickhouse/ClickHouseTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenInjectRuntimeFilterSuite.scala
Exclude VeloxBloomFilterMightContain from FileSourceScan parition filters
Fixes: #9849
> [GLUTEN-9849][VL] Avoid VeloxBloomFilterMightContain being applied to FileSourceScan partition filters

- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
- package/pom.xml
The PR is marked with `[VL]` because the list is only read when building Gluten + Velox backend.
We have finished a series of clean up on the duplicated code so the list of overridden classes can be shorten. Update the list correspondingly for clearance and for avoiding regression.
Adds a trivial todo for the configuration code in passing.
> [VL] Clean up the duplicated class list in the Maven enforcer

- backends-clickhouse/src-delta33/main/scala/org/apache/spark/sql/delta/DeltaLog.scala
- pom.xml
Downgrade the wartremover version to `3.0.6` which is the latest version that was built on Scala 2.13.8 to ensure the compatibility between wartremover and Gluten / Spark.
Previously we may face an error in Intellij IDEA so wartremover was disabled for 2.13. The error has gone with the downgraded wartremover version.
> [CORE] Enable wartremover check for Scala 2.13

- docs/get-started/VeloxStageResourceAdj.md
The configuration section of https://apache.github.io/incubator-gluten/get-started/VeloxStageResourceAdj.html  is not rendered properly, I guess it's because the lack of empty line after markdown table code.
Try to fix this.
> [DOC] Fix VeloxStageResourceAdj config table style

- gluten-flink/runtime/src/main/java/org/apache/gluten/table/runtime/operators/GlutenSourceFunction.java
> [GLUTEN-10033][FLINK] Fix memory leak caused by unclosed RowVector in `GlutenSourceFunction`

- backends-clickhouse/src-delta33/main/scala/org/apache/spark/sql/execution/datasources/v1/clickhouse/MergeTreeFileFormatWriter.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/datasources/GlutenFormatWriterInjectsBase.scala
- shims/common/src/main/scala/org/apache/gluten/execution/datasource/GlutenFormatWriterInjects.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatWriter.scala
API
```scala
def executeWriterWrappedSparkPlan(plan: SparkPlan): RDD[InternalRow]
```
is being changed to
```scala
def getWriterWrappedSparkPlan(plan: SparkPlan): SparkPlan
```
We don't have to execute the SparkPlan before it's returned to the file format writer. This change will make it easier to debug or operate on the wrapped query plan. The previous use of RDD more or less limited the flexibility of coding and troubleshooting.
Related to #2205, #2553
> [CORE] Refactor: Make `GlutenFormatWriterInjects#executeWriterWrappedSparkPlan` return the wrapped query plan rather than the executed RDD

- .github/workflows/velox_backend_x86.yml
- dev/docker/Dockerfile.centos8-dynamic-build
- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornUtils.java
- pom.xml
- tools/gluten-it/pom.xml
Bump Celeborn version to 0.6.0. Backport:
- https://github.com/apache/celeborn/pull/2801
- https://github.com/apache/celeborn/pull/2807
- https://github.com/apache/celeborn/pull/2810
- https://github.com/apache/celeborn/pull/3109
- https://github.com/apache/celeborn/pull/3118
- https://github.com/apache/celeborn/pull/3324
- https://github.com/apache/celeborn/pull/3158
Fixes: #10151
CI.
> [GLUTEN-10151][CELEBORN] Bump Celeborn version to 0.6.0

- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxFormatWriterInjects.scala
- cpp/velox/jni/VeloxJniWrapper.cc
Related to #3076
Currently `VeloxDataSourceJniWrapper#splitBlockByPartitionAndBucket` doesn't do exactly what it's intended to do. It actually takes an array of data columns then directly select them out from the input columnar batch.
The patch fixes the code a bit by moving the partition keys -> data keys conversion down from Java code to native code so less confusing will be made by the code.
Note dynamic partition write is still not supported in v1 write. The patch just does code cleanup.
> [VL] Clarify the code objective of VeloxDataSourceJniWrapper#splitBlockByPartitionAndBucket

- docs/velox-backend-limitations.md
- gluten-substrait/src/main/scala/org/apache/gluten/execution/ValidatablePlan.scala
Fallback to vanilla spark rather than raising an `AnalysisException `during the validation stage.
Fix https://github.com/apache/incubator-gluten/issues/10103
Existing tests
> [GLUTEN-10103][VL] Fall back to vanilla spark when UnresolvedException occurs in the schema validation

- cpp/core/utils/ObjectStore.cc
Fix dead lock founded in #10112
(Fixes: \#10112)
The task thread on the Executor is blocked by a single runnable task thread. The runnable task thread continues to run in nativeSpill without exiting.
1. Observing the runnable task thread stack, it was found that the task is already in the resource release phase, and theoretically should not trigger spill operations again.
2. Checking the log of the runnable task and observing the task's operation logs, it was found that during the native write phase, insufficient OOM (Out Of Memory) triggered the task's failure cleanup action.
3. Why does the nativeSpill operation get triggered again during the resource release phase? 
Additional logs were added to record the native stack of the last reserveMemory operation
4. Why does triggering the …
> [GLUTEN-10112][VL] Fix deadLock caused by objectStore when native writer throws oom exception

- cpp/core/shuffle/LocalPartitionWriter.cc
- cpp/core/shuffle/rss/RssPartitionWriter.cc
- cpp/velox/tests/VeloxShuffleWriterTest.cc
Fix the bug introduced by a recent change https://github.com/apache/incubator-gluten/pull/9982/files#diff-d58dca9ecda139d81d2630e1adb22ae01953ad4de0a9c086bd07c07619a3a927L94-R93
> [GLUTEN-10168][VL] Sort shuffle produce wrong partition lengths in case of spill

- backends-velox/pom.xml
- pom.xml
1. Unify configuration of `build-helper-maven-plugin` in the root `pom.xml` together.
2. Correct `<type>test-jar</type>` / `<scope>test</scope>` usages in `backends-velox/pom.xml`.
> [CORE][VL] Minor cleanups for pom.xml

- cpp/velox/shuffle/VeloxShuffleReader.cc
- cpp/velox/shuffle/VeloxShuffleReader.h
- cpp/velox/tests/VeloxShuffleWriterTest.cc
- cpp/velox/tests/VeloxShuffleWriterTestBase.h
Segfault occurs when reading a row that exceed current rowBuffer size
https://github.com/apache/incubator-gluten/pull/10193/files#diff-c1147845fed4ad34faf580505712b04befdd3df0361297f93cb660069bedb7bdR646-R648
> [GLUTEN-10192][VL] Fix sort shuffle read segfault in some cases

- backends-velox/src/main/scala/org/apache/spark/sql/execution/datasources/velox/VeloxParquetWriterInjects.scala
- cpp/core/config/GlutenConfig.h
- cpp/velox/operators/writer/VeloxParquetDataSource.cc
- docs/Configuration.md
- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Respect parquet writer configs
1. parquet.page.size
2. parquet.compression.codec.zstd.level
3. parquet.enable.dictionary
4. parquet.writer.version
(Fixes: \#9571)
manually
> [GLUTEN-9571][VL] Respect parquet configs, parquet.page.size and parquet.compression.codec.zstd.level etc.

- gluten-core/pom.xml
- package/pom.xml
Fix issue reported here: https://github.com/apache/incubator-gluten/issues/10102#issuecomment-3095015236.
The build information related to backend is missing, such as GCC version,  backend branch/revision/revision time, etc. In the log and web UI, `"<unknown>"` is displayed for these items. 
The build information is added in two places during the compile phase: `gluten-core/pom.xml` and `gluten-substrait/pom.xml`. And they both modify `gluten-build-info.properties` placed in gluten-core's resource path: `gluten-core/target/generated-resources/`.
When building gluten-core module, the generated resources will be copied into target/classes/ and then be packed into module jar. In the later build for gluten-substrait module, the backend related build info is just added in the property file …
> [CORE] Fix missing build information

- cpp/core/memory/AllocationListener.h
We should reset `blocksReserved_` when `allocationChanged` fails to avoid inaccurate memory allocation.
Fixes: #10279
After this fix, the failed job of #10279 is successfully executed
> [GLUTEN-10279][VL] Reset reserved counter when allocationChanged fails

- gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Transitions.scala
This PR proposes to simplify `fillWithTransitions` for `InsertTransitions`.
unit tests, integration tests and manual tests
> [MINOR][CORE] Simplify fillWithTransitions for InsertTransitions

- dev/build-thirdparty.sh
…mpiling mode
#10306 
Package  libgeos into gluten-thirdparty-lib-centos-7-x86_64.jar when in dynamic compile mode in centos7.
(Fixes: \#10306 )
> [GLUTEN-10306] Package libgeos  when in dynamic compile mode

- gluten-core/src/main/java/org/apache/gluten/jni/JniLibLoader.java
This PR proposes to improve `moveToWorkDir` for `JniLibLoader` by avoiding string concatenation.
> [MINOR] Improve moveToWorkDir for JniLibLoader

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxValidatorApi.scala
- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergScanTransformer.scala
This PR proposes to avoid using the fields of `StructType`.
`StructType` implements the `Seq[StructField]`. Please see the declaration show below.
```
case class StructType(fields: Array[StructField]) extends DataType with Seq[StructField] {
// ignore code
}
```
> [MINOR] Avoid using the fields of StructType

- dev/build_arrow.sh
- ep/build-velox/src/cmake-compatibility.patch
Velox upgrade to use Cmake 4.0, thus we need a patch to build arrow
Fixes: #10369 
pass GHA
> [GLUTEN-10369][VL] Fix arrow cmake check

- .github/workflows/velox_nightly.yml
This patch updated the apache nightly sync action. The action with version tag we used are banned 
```
burnett01/rsync-deployments@5.2 is not allowed to be used in apache/incubator-gluten
```
https://github.com/apache/incubator-gluten/actions/runs/16764175107
pass GHA
> [GLUTEN-9860][VL] Fix nightly upload action

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/RemoveNativeWriteFilesSortAndProject.scala
Just check if sort columns are a subset of partition columns for RemoveNativeWriteFilesSortAndProject rule
Fixes: #10354
> [GLUTEN-10354][CORE] Just check if sort columns are a subset of partition columns

- cpp/core/utils/ObjectStore.h
This PR proposes to make code follows the modern C++ style.
> [MINOR] Use `static constexpr` to follow C++ style

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- gluten-core/src/main/scala/org/apache/spark/util/SparkVersionUtil.scala
- gluten-substrait/src/main/scala/org/apache/gluten/backendsapi/SparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/BasicScanExecTransformer.scala
- gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/execution/FileSourceScanExecShim.scala
In preparation for supporting deletion vector in Velox backend, move the specialized column mapping `__delta_internal_is_row_deleted` -> `row_index` from common place to CH backend.
> [GLUTEN-10377][CH] Move specialized delta internal column mapping to CH backend

- backends-velox/src-celeborn/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarShuffleWriter.scala
- backends-velox/src-uniffle/main/java/org/apache/spark/shuffle/writer/VeloxUniffleColumnarShuffleWriter.java
- backends-velox/src/main/scala/org/apache/spark/shuffle/ColumnarShuffleWriter.scala
- gluten-arrow/src/main/java/org/apache/gluten/vectorized/NativePlanEvaluator.java
- gluten-arrow/src/main/scala/org/apache/gluten/memory/NativeMemoryManager.scala
- gluten-core/src/main/java/org/apache/gluten/memory/memtarget/Spillers.java
This PR proposes remove the unnecessary `Set` and use enum directly
(Fixes: \#10349)
> [GLUTEN-10349] Remove the unnecessary Set and use enum directly

- cpp/core/utils/ObjectStore.cc
- cpp/core/utils/ObjectStore.h
This PR proposes to extract the common code from `ObjectStore` as a new method `lookup`.
(Fixes: \#10403)
> [GLUTEN-10403] Extract the common code from ObjectStore as a new method lookup

- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
The context hang issue has been fixed by https://github.com/facebookincubator/velox/commit/2e4a0835c9147651db68e90c45955523f092a93b. This PR enables the corresponding test.
Fixes https://github.com/apache/incubator-gluten/issues/10175.
Fixes https://github.com/apache/incubator-gluten/issues/10393.
UT verified.
> [GLUTEN-10175][VL] Enable test 'function current_timestamp and now'

- README.md
- docs/velox-parquet-write-configuration.md
- docs/velox-spark-configuration.md
It's a long-standing unpaid debt. We all know some of the spark configurations are used by Gluten, some of them are ignored by Gluten, some of them are transparent to Gluten. But we don't have a formal list for long time.
The PR started to draft the table. I still leave the columns as blank. Feel free to fill it if you happen to know the status. I will update in following PRs also.
The configurations are copied from Spark4.0 and the meaning column is removed. Initially I'm going to write a python script to do the work, but give a try to Copilot+ChatGPT. Fortunately copilot works pretty well.
> [VL] Add Spark configuration horhored status in Gluten

- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxStringFunctionsSuite.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/benchmark/VeloxRasBenchmark.scala
- backends-velox/src/test/scala/org/apache/spark/sql/execution/joins/GlutenExistenceJoinSuite.scala
- pom.xml
- shims/common/src/main/scala/org/apache/gluten/sql/shims/SparkShims.scala
- shims/spark32/src/main/scala/org/apache/gluten/sql/shims/spark32/Spark32Shims.scala
- shims/spark32/src/main/scala/org/apache/spark/sql/SparkSqlUtils.scala
- shims/spark33/src/main/scala/org/apache/gluten/sql/shims/spark33/Spark33Shims.scala
- shims/spark33/src/main/scala/org/apache/spark/sql/SparkSqlUtils.scala
- shims/spark34/src/main/scala/org/apache/gluten/sql/shims/spark34/Spark34Shims.scala
- shims/spark34/src/main/scala/org/apache/spark/sql/SparkSqlUtils.scala
- shims/spark35/src/main/scala/org/apache/gluten/sql/shims/spark35/Spark35Shims.scala
- shims/spark35/src/main/scala/org/apache/spark/sql/SparkSqlUtils.scala
- shims/spark40/src/main/scala/org/apache/gluten/sql/shims/spark40/Spark40Shims.scala
- shims/spark40/src/main/scala/org/apache/spark/sql/SparkSqlUtils.scala
https://github.com/apache/incubator-gluten/pull/9768 has support spark 400, but when build it, require 
```
rm -f backends-velox/src/test/scala/org/apache/gluten/execution/VeloxStringFunctionsSuite.scala \
backends-velox/src/test/scala/org/apache/spark/sql/execution/GlutenHiveUDFSuite.scala \
backends-velox/src/test/scala/org/apache/spark/sql/execution/VeloxParquetWriteForHiveSuite.scala \
backends-velox/src/test/scala/org/apache/spark/sql/execution/benchmark/VeloxRasBenchmark.scala \
backends-velox/src/test/scala/org/apache/spark/sql/execution/joins/GlutenExistenceJoinSuite.scala 
mvn clean package -Pbackends-velox -Pspark-4.0 -Pscala-2.13 -DskipTests
```
This PR aims to avoid manual remove such file by add shim to support VeloxStringFunctionsSuite/VeloxRasBenchmark/GlutenExistenceJoinSui …
> [GLUTEN-8852][VL] Fix compilation issues in existing tests for Spark 4.0.0

- gluten-substrait/src/main/scala/org/apache/gluten/expression/ConverterUtils.scala
This PR proposes to improve `collectAttributeNamesDFS` avoiding calls `supportStructType()` duplicately
Fixes #10482
GA tests.
> [GLUTEN-10482] Improve `collectAttributeNamesDFS` to avoid repeated check calls

- backends-velox/src/main/scala/org/apache/gluten/execution/HashAggregateExecTransformer.scala
This PR proposes to simplify the `extractStructNeeded` for `HashAggregateExecTransformer`.
Fixes #10491
GA tests.
> [GLUTEN-10491][VL] Simplify the extractStructNeeded for HashAggregateExecTransformer

- gluten-delta/src/test/scala/org/apache/gluten/execution/DeltaSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
Filter used to fallback when reading delta table in the scan-only execution. This PR fixes this issue.
UT verified.
> [GLUTEN-10392][VL] Fix filter fallback in scan-only execution

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/gluten/expression/ExpressionRestrictions.scala
- backends-velox/src/test/scala/org/apache/gluten/functions/JsonFunctionsValidateSuite.scala
- gluten-substrait/src/main/scala/org/apache/gluten/expression/ExpressionUtils.scala
Currently, gluten uses spark.sql.caseSensitive to determine whether to convert struct field names to lowercase and pass the converted field names to velox. This results in all struct field names becoming lowercase when spark.sql.caseSensitive is false. I haven't found a suitable solution to this problem for the current design, so let's fall back first.
unit test.
> [GLUTEN-10521][VL] Fall back `to_json` function for uppercase struct field name

- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/BaseMixin.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/DataGenMixin.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Parameterized.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/Queries.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/QueriesCompare.java
- tools/gluten-it/common/src/main/java/org/apache/gluten/integration/command/SparkShell.java
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/QueryRunner.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/Suite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/TableCreator.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/DataGenOnly.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Parameterized.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/Queries.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/QueriesCompare.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/action/SparkShell.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/clickbench/ClickBenchSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/clickbench/ClickBenchTableCreator.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/ds/TpcdsDataGen.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/ds/TpcdsSuite.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/h/TpchDataGen.scala
- tools/gluten-it/common/src/main/scala/org/apache/gluten/integration/h/TpchSuite.scala
Add a new option`--data-source`:
```bash
--data-source=<dataSource>
Datasource used to generate data and to create
tables
Default: parquet
```
Default value is `parquet`. And in this PR only `parquet` is supported. Error will be thrown otherwise.
The data generated will be in folder whose name has indicator of the data source type:
```
root@hongze-zhang-VMware20-1:/tmp# ls /tmp/tpcds-generated-1.0-parquet-partitioned
call_center   catalog_returns  customer          customer_demographics  household_demographics  inventory  promotion  ship_mode  store_returns  time_dim   web_page     web_sales
catalog_page  catalog_sales    customer_address  date_dim               income_band             item       reason     store      store_sales    warehouse  web_returns  web_site
```
The feature would …
> [VL] Extend gluten-it to support more data source types

- gluten-flink/docs/Flink.md
- gluten-flink/docs/Gluten-Flink-troubleshooting.md
- gluten-flink/pom.xml
https://github.com/apache/incubator-gluten/pull/10515 has made a great effort to decouple flink from parent gluten.
This PR adds a profile named java-17 to set both `maven.compiler.source/target` to 17 (defaults to 11) if users want to build the code with Java 17. 
This PR update compiler version and update  build jar version to match the master pom version change.
NA
> [FLINK] Add `java-17` profile for Flink build and update project version in flink doc

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/BroadcastModeUtils.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/BroadcastUtils.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarBuildSideRelation.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/unsafe/UnsafeColumnarBuildSideRelation.scala
This pull request introduces a safer and more robust approach for handling Spark's `BroadcastMode` during serialization. The main improvement is the introduction of a new `SafeBroadcastMode` abstraction and related utilities, which help avoid serialization issues that caused a Stackoverflow exception during broadcast exchanges. BroadcastMode was introduced in this [PR](https://github.com/apache/incubator-gluten/pull/8116) that caused the issue we observed. HashedRelationBroadcastMode embeds Catalyst expression trees, which are not safe to Kryo-serialize when running with `spark.kryo.referenceTracking=false` (default internally).
With this change, the broadcast payload now contains only primitives and byte arrays (no Catalyst trees). For bound keys, we serialize just column ordinals (+ …
> [GLUTEN-9671][VL] Fix broadcast exchange stackoverflow due to Kryo serialization

- dev/builddeps-veloxbe.sh
Currently, when using ```builddeps-veloxbe.sh``` to compile gluten cpp independently, it first fetches the velox code and installs related dependencies, so you can’t compile only gluten cpp even if velox has already been built. After this PR, running ```builddeps-veloxbe.sh <build_option> build_gluten_cpp``` will compile only gluten cpp.
CI
> [VL] Support independent Gluten CPP build

- backends-clickhouse/src/main/scala/org/apache/gluten/backendsapi/clickhouse/CHSparkPlanExecApi.scala
- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
The `isUseUniffleShuffleManager` configuration was originally introduced in PR #3767. However, subsequent refactoring efforts have relocated the Uniffle-related shuffle manager implementation to the `backends-velox` module. This configuration is now obsolete and should be removed. Additionally, we can eliminate the corresponding validation checks in the ClickHouse backends since the `UniffleShuffleManager` class will no longer be present in the classpath of CH-backends.
> [GLUEN-10107][INFRA]Deprecate isUseUniffleShuffleManager from glutenConfig

- gluten-flink/docs/Flink.md
Since https://github.com/apache/incubator-gluten/pull/10205/files has provide a runnable command to build velox4j, but it's broken after recent code commit. This PR re-update the build command.
NA
> [DOC][FLINK] Update flink build command to skip gpg and spotless check

- backends-velox/src-iceberg/main/scala/org/apache/gluten/connector/write/IcebergColumnarBatchDataWriter.scala
- backends-velox/src-iceberg/main/scala/org/apache/gluten/connector/write/IcebergDataWriteFactory.scala
- backends-velox/src-iceberg/main/scala/org/apache/iceberg/transforms/IcebergTransformUtil.scala
- backends-velox/src-iceberg/test/scala/org/apache/gluten/execution/VeloxTPCHIcebergSuite.scala
- backends-velox/src-iceberg/test/scala/org/apache/gluten/execution/enhanced/VeloxIcebergSuite.scala
- backends-velox/src/main/resources/org/apache/gluten/proto/IcebergPartitionSpec.proto
- cpp/velox/compute/iceberg/IcebergWriter.cc
- cpp/velox/tests/iceberg/IcebergWriteTest.cc
- cpp/velox/utils/ConfigExtractor.cc
- dev/ci-velox-buildstatic-centos-7-enhanced-features.sh
- gluten-iceberg/src/main/scala/org/apache/gluten/execution/IcebergWriteExec.scala
- gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/IcebergWriteUtil.scala
Add Protobuf struct IcebergPartitionField to transfer the iceberg id information, add IcebergPartitionSpec to transfer partition information.
Build with test and benchmark in CI and fix IcebergWriteTest build.
Set the file format to orc to bypass native parquet write for partitioned tpch iceberg suite, after https://github.com/facebookincubator/velox/pull/14670 which supports fanout false mode merged, we can relax the restriction.
Relevant PR: https://github.com/facebookincubator/velox/pull/13874
> [GLUTEN-9335][VL] Support iceberg partition write

- gluten-arrow/src/main/java/org/apache/gluten/vectorized/ArrowWritableColumnVector.java
If the Date type is nested within an Array, Map, or Struct, invoking `writeRow` may result in an exception due to DateWriter utilizing the unsafe set interface. The `set` interface does not reallocate the value buffer in cases of overflow. Consequently, this pull request changes to use the safer `setSafe` interface.
> [GLUTEN-10607][MINOR] Fix: Use  `setSafe` in DateWriter to avoid overflow

- backends-clickhouse/src-celeborn/main/scala/org/apache/spark/shuffle/CHCelebornColumnarBatchSerializerFactory.scala
- backends-clickhouse/src-celeborn/main/scala/org/apache/spark/shuffle/CHCelebornColumnarShuffleWriterFactory.scala
- backends-velox/src-celeborn/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarBatchSerializerFactory.scala
- backends-velox/src-celeborn/main/scala/org/apache/spark/shuffle/VeloxCelebornColumnarShuffleWriterFactory.scala
- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornColumnarBatchSerializerFactory.java
- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleManager.java
- gluten-celeborn/src/main/java/org/apache/spark/shuffle/gluten/celeborn/CelebornShuffleWriterFactory.java
Refactor CelebornShuffleManager use list instead of map to load the factory as described in #10577 .
> [GLUTEN-10577][CELEBORN] Refactor `CelebornShuffleManager` to load factory in a better way

- backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxRuleApi.scala
- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- backends-velox/src/main/scala/org/apache/gluten/extension/RewriteUnboundedWindow.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxWindowExpressionSuite.scala
For unbounded window, velox needs to load the entire partition's data into memory for calculation, which can easily cause OOM when the partition is too large. This rule rewrites unbounded window to an equivalent aggregate join operation to avoid OOM.
Input query:
```
SELECT *, SUM(c0) OVER (PARTITION BY c1) AS sum FROM t
```
Rewritten query:
```
SELECT t.*, t1.sum FROM t LEFT JOIN (SELECT c1, SUM(c0) AS sum FROM t GROUP BY c1) t1  ON t. c1 <=> t1.c1
```
UT
> [GLUTEN-10605][VL] Rewrite unbounded window to an equivalent aggregate join

- dev/build_arrow.sh
Although it can still be downloaded normally now, it seems to be a typo and it would be best to fix it.
> [VL] Fix arrow url typo

- gluten-ut/spark35/src/test/scala/org/apache/spark/sql/GlutenSQLQueryTestSuite.scala
Temporarily ignore the "datetime-legacy.sql" due to the below exception. A follow-up PR will be filed to override the sql test file.
```
Expected "[java.lang.ArithmeticException long overflow]", but got "[org.apache.gluten.exception.GlutenException
Could not convert Timestamp(1230219000123123, 0) to microseconds]" Result did not match for query #121
select TIMESTAMP_SECONDS(1230219000123123) (GlutenSQLQueryTestSuite.scala:993)
```
UT verified.
> [GLUTEN-10671][VL] Ignore datetime-legacy.sql

- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
This PR proposes to improve `expressionBlacklist` for `GlutenConfig` and make `expressionBlacklist` follows Scala style.
Fixes: #10687
GA tests.
> [GLUTEN-10687] Refactor `expressionBlacklist` to follow Scala style

- backends-velox/src/main/scala/org/apache/gluten/config/VeloxConfig.scala
- backends-velox/src/main/scala/org/apache/gluten/datasource/ArrowCSVFileFormat.scala
- backends-velox/src/main/scala/org/apache/gluten/execution/RowToVeloxColumnarExec.scala
- backends-velox/src/main/scala/org/apache/spark/sql/execution/ColumnarCachedBatchSerializer.scala
- backends-velox/src/test/java/org/apache/gluten/columnarbatch/ColumnarBatchTest.java
- backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
- cpp/velox/compute/WholeStageResultIterator.cc
- cpp/velox/config/VeloxConfig.h
- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
Velox supports a config preferred_output_batch_bytes which is a soft/best effort limit on the number of bytes consumed in
a batch output by an Operator. It is used alongside max_output_batch_rows and in place of preferred_output_batch_rows, and applies when the number of bytes in rows can be estimated and that estimate exceeds preferred_output_batch_bytes before max_output_batch_rows is reached. This can help the system to adapt to very wide rows without OOM'ing.
In addition to plumbing this config through Spark to Velox, I also modified RowToVeloxColumnarExec to respect preferred_output_batch_bytes. Here I limit the Arrow buffer it allocates to hold preferred_output_batch_bytes + whatever overflow is needed to hold the last row that causes us to exceed the limit (again it's a soft …
> [VL] Support Velox's preferred_output_batch_bytes config

- pom.xml
- tools/gluten-it/pom.xml
> Apache Spark 4.0.1 is a maintenance release containing important correctness and stability fixes. This release is based on the branch-4.0 maintenance branch of Spark. We strongly recommend all 4.0 users to upgrade to this stable release.
> [GLUTEN-10715][CORE] Bump Spark version from 4.0.0 to 4.0.1

- cpp/velox/shuffle/VeloxShuffleReader.cc
Fix the warning:
```c++
warning: ‘std::shared_ptr<gluten::VeloxColumnarBatch> gluten::{anonymous}::makeColumnarBatch(facebook::velox::RowTypePtr, std::unique_ptr<gluten::InMemoryPayload>, facebook::velox::memory::MemoryPool*, int64_t&)’ defined but not used [-Wunused-function]
299 | std::shared_ptr<VeloxColumnarBatch> makeColumnarBatch(
|                                     ^~~~~~~~~~~~~~~~~
```
Manually test
> [VL] Remove unused-function warning

- gluten-substrait/src/main/scala/org/apache/gluten/extension/columnar/validator/Validators.scala
As title. FallbackByNativeValidation is supposed to handle a single node. We currently pass a tree to the offload attempt which overkills the goal. It's functioning but may impact the performance.
> [CORE] Fix FallbackByNativeValidation attempts to offload a whole tree than a single node

- gluten-ut/spark32/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark33/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark34/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
- gluten-ut/spark35/src/test/scala/org/apache/gluten/utils/velox/VeloxTestSettings.scala
Enable disabled tests in GlutenJsonV1Suite, GlutenJsonV2Suite, and GlutenJsonLegacyTimeParserSuite which pass without failure.
CI.
> [VL] Enable passing JSON tests

- backends-clickhouse/src/test/scala/org/apache/gluten/execution/tpch/GlutenClickHouseTPCHSaltNullParquetSuite.scala
- cpp-ch/local-engine/Common/GlutenConfig.h
- cpp-ch/local-engine/Parser/RelParsers/GroupLimitRelParser.cpp
- cpp-ch/local-engine/Parser/RelParsers/GroupLimitRelParser.h
- cpp-ch/local-engine/Parser/RelParsers/SortParsingUtils.cpp
- cpp-ch/local-engine/Parser/RelParsers/SortParsingUtils.h
Fix #10741. When the sort keys contains a partition keys, the `GroupLimit` operator may generate incorrect data due to improper aggregation key generation.
test by UTs
> [GLUTEN-10741][CH] Invalid results: sort keys contains partition keys when get windows' topK

- gluten-substrait/src/main/scala/org/apache/gluten/execution/GenerateExecTransformerBase.scala
Suppose the following SQL:
```SQL
SELECT * FROM
(SELECT xxx, explode(split(xxx)) FROM a JOIN b ON a.joinkey = b.joinkey)
GROUP BY joinkey
```
There may exist `FlushableAggregateTransformer` in the executed plan because `GenerateExecTransformer` doesn't override method `outputPartitioning`, which makes `FlushableHashAggregateRule` can't determine that the inputs have already been distributed by aggregation keys. So we need to override `outputPartitioning` in `GenerateExecTransformerBase`.
> [MINOR] Override `outputPartitioning` in `GenerateExecTransformerBase`

- pom.xml
Gluten depends on `iceberg-spark-runtime-${sparkbundle.version}_${scala.binary.version}` in its iceberg module. Only starting from Iceberg 1.10.0, spark 4.0 is supported.
Reference:
https://mvnrepository.com/artifact/org.apache.iceberg/iceberg-spark-runtime-4.0_2.13
Manually verified.
> [CORE] Fix iceberg version to 1.10.0 for Spark 4.0

- backends-velox/src/test/scala/org/apache/gluten/execution/ArrowCsvScanSuite.scala
- backends-velox/src/test/scala/org/apache/gluten/execution/VeloxColumnarCacheSuite.scala
- gluten-core/src/main/scala/org/apache/spark/sql/execution/columnar/SparkCacheUtil.scala
- gluten-substrait/src/main/scala/org/apache/gluten/config/GlutenConfig.scala
We should always call `InMemoryRelation.clearSerializer()` for each Spark session that sets a new cache serializer. 
Failing to do this will cause flaky test results because whether the cache serializer is set to columnar or not is unclear when the test is run.
Unblocks https://github.com/apache/incubator-gluten/pull/10802.
> [VL] Fix flaky columnar cache tests by clearing the cache serializer states before the suites are run

- tools/workload/tpch/gen_data/parquet_dataset/tpch_datagen_parquet.scala
When using TPCH shell script to generate test data, the script got stuck when execute it again.
The tool dbGen will generate a lots of temporary files and not be deleted after the first running. When running the tool again, it asks whether to overwrite the temporary files, which make the script stuck.
The patch adds a function to delete these temporary files before running the dbGen tool.
> [VL] tools/workload/tpch: Delete temporary files generated by dbgen

- .github/workflows/build_release.yml
- dev/release/build-release.sh
- dev/release/package-release.sh
Use GHA to build Gluten jars for supported Spark versions, which can simplify the release process and ensure all required build options are enabled, avoiding potential omissions in manual builds.
Will backport it to branch-1.5 to help the coming 1.5.0 release.
> [GLUTEN-9615][INFRA] Automate release process with build script and GHA workflow

- backends-velox/src-delta33/test/scala/org/apache/spark/sql/delta/DeleteSQLSuite.scala
- gluten-delta/src/main/scala/org/apache/gluten/extension/DeltaPostTransformRules.scala
Issue is because of the incorrect application order of `pushDownInputFileExprRule` and `columnMappingRule`, sometimes the input file expressions are not pushed to Velox scan, causing the input file expression columns to be returned with empty values incorrectly by Gluten.
The PR fixes the issue by adjusting the application order of `pushDownInputFileExprRule` and `columnMappingRule`.
This fixes the ignored Delta test suite `DeleteSQLNameColumnMappingSuite`.
> [VL] Delta: Fix input file expressions not getting pushed to native scan when column mapping is applicable

- dev/builddeps-veloxbe.sh
- ep/build-velox/src/get_velox.sh
Wrapping the key steps into functions will help everyone understand the flow of the script.
> [VL] Minor refactoring of get_velox.sh for better readability

- gluten-substrait/src/main/scala/org/apache/spark/sql/execution/ColumnarShuffleExchangeExec.scala
```
before:
ColumnarExchange SinglePartition, ENSURE_REQUIREMENTS, [plan_id=744], [shuffle_writer_type=hash], [OUTPUT] List(sum:DoubleType, count:LongType), [OUTPUT] List(sum:DoubleType, count:LongType)
after:
ColumnarExchange SinglePartition, ENSURE_REQUIREMENTS, [plan_id=710], [shuffle_writer_type=hash], [output=[sum#133: double, count#134: bigint]]
```
The reason why the OUTPUT appeared twice previously is that verboseString internally calls simpleString. Moreover, simpleString generally does not include output information, so this PR simply removes it.
> [CORE] Optimize the verboseString of ColumnarShuffleExchangeExec
